var searchData=
[
  ['a_20collaborative_20session_20with_20new_20features_0',['Starting a Collaborative Session with New Features',['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'']]],
  ['a_20heredoc_1',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['a_20session_2',['a Session',['../md_IMPROVEMENTS__FINAL.html#autotoc_md539',1,'Starting a Session'],['../md_QUICK__REFERENCE.html#autotoc_md844',1,'Starting a Session'],['../md_QUICK__REFERENCE.html#autotoc_md852',1,'Starting a Session']]],
  ['a_20single_20command_3',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['a_20wad_20file_4',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['a_3a_20test_20execution_20logs_5',['Appendix A: Test Execution Logs',['../md_PR23__VALIDATION__REPORT.html#autotoc_md831',1,'']]],
  ['abbreviations_6',['abbreviations',['../classutils_1_1prompt__compressor_1_1PromptCompressor.html#a18b97b105bdb848033d21a6910080da7',1,'utils::prompt_compressor::PromptCompressor']]],
  ['about_20read_20write_20block_20syntax_7',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['about_20read_20write_20block_20syntax_20✅_8',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['absolute_20path_20fix_20implementation_20summary_9',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['absolute_5fpath_5ffix_5fsummary_2emd_10',['ABSOLUTE_PATH_FIX_SUMMARY.md',['../ABSOLUTE__PATH__FIX__SUMMARY_8md.html',1,'']]],
  ['abstract_20syntax_20trees_11',['ast (Abstract Syntax Trees)',['../md_workshop__dependency__validation.html#autotoc_md1371',1,'']]],
  ['acceptance_20criteria_12',['Acceptance Criteria',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md598',1,'']]],
  ['access_13',['Documentation Access',['../md__8collab__env.html#autotoc_md6',1,'']]],
  ['access_20control_14',['Access Control',['../md_SANDBOX.html#autotoc_md1031',1,'3. Filesystem Access Control'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1066',1,'3. Filesystem Access Control'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1488',1,'Directory Access Control']]],
  ['access_20denied_15',['Issue 1: READ Block Access Denied',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md173',1,'']]],
  ['access_20denied_20✅_16',['Issue 1: READ Block Access Denied ✅',['../md_FIXES__SUMMARY.html#autotoc_md363',1,'']]],
  ['accident_17',['accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['accuracy_18',['Taint Propagation Accuracy',['../md_workshop__benchmarks.html#autotoc_md1351',1,'']]],
  ['acp_5factions_19',['ACP_ACTIONS',['../namespacebenchmark__acp.html#a4ae0710ae5c1c6bc0dc5187d421eb073',1,'benchmark_acp']]],
  ['acp_5fvalidator_2epy_20',['acp_validator.py',['../acp__validator_8py.html',1,'']]],
  ['acpvalidator_21',['ACPValidator',['../classcore_1_1acp__validator_1_1ACPValidator.html',1,'core::acp_validator']]],
  ['actions_22',['Actions',['../md_workshop__test__results.html#autotoc_md1474',1,'Immediate Actions'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md735',1,'Post-Merge Actions']]],
  ['actions_20completed_23',['Immediate Actions (Completed)',['../md_workshop__security__audit.html#autotoc_md1444',1,'']]],
  ['active_20agents_20counter_20✅_24',['Bug 2: Active Agents Counter ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1325',1,'']]],
  ['activities_25',['Break Activities',['../md_IMPROVEMENTS__FINAL.html#autotoc_md501',1,'']]],
  ['actual_20implementation_26',['Part 1: PR Claims vs. Actual Implementation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md748',1,'']]],
  ['add_20more_20diet_20etc_20if_20tools_20expand_27',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['add_5fcache_5fcontrol_28',['add_cache_control',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#ac5875c33c281908713873f9268e32fca',1,'core::anthropic_features::AnthropicFeatures']]],
  ['add_5fdiff_5fpatch_29',['add_diff_patch',['../classmanagers_1_1shared__build__status_1_1SharedBuildStatusManager.html#a7f6c6ee3e48111e5f78e9c56158fc779',1,'managers::shared_build_status::SharedBuildStatusManager']]],
  ['add_5fmessage_30',['add_message',['../classcore_1_1multiprocess_1_1SharedContext.html#a7a1d9fb1459e1506f6df6b9eaca0d3bc',1,'core::multiprocess::SharedContext']]],
  ['add_5fshared_5fnote_31',['add_shared_note',['../classcore_1_1multiprocess_1_1SharedContext.html#a54bcd5f913c7059848f1f4939207a4f3',1,'core::multiprocess::SharedContext']]],
  ['add_5ftokens_32',['add_tokens',['../classutils_1_1rate__limiter_1_1RateLimiter.html#a52259d2a83257b6d2682c6e9beb61c29',1,'utils::rate_limiter::RateLimiter']]],
  ['add_5fusage_33',['add_usage',['../classutils_1_1token__stats_1_1TokenStats.html#a45a527585073694eaaa7c1cfe9e8b928',1,'utils::token_stats::TokenStats']]],
  ['added_34',['Added',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md449',1,'Commands Added'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1508',1,'Files Modified/Added'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md670',1,'New Functions Added'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md325',1,'New Tests Added'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md396',1,'New Tests Added']]],
  ['added_20get_5fdatabase_5fpath_20helper_20function_35',['1. Added &lt;span class=&quot;tt&quot;&gt;get_database_path()&lt;/span&gt; Helper Function',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md224',1,'']]],
  ['added_20to_20requirements_20txt_36',['Added to requirements.txt',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md721',1,'']]],
  ['adding_20distributed_20processing_20ray_37',['2. Adding Distributed Processing (Ray)',['../md_ARCHITECTURE.html#autotoc_md163',1,'']]],
  ['adding_20new_20ai_20providers_38',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md162',1,'']]],
  ['adding_20new_20token_20optimization_20strategies_39',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md165',1,'']]],
  ['adding_20new_20workshop_20tools_40',['3. Adding New Workshop Tools',['../md_ARCHITECTURE.html#autotoc_md164',1,'']]],
  ['additional_20languages_41',['Additional Languages',['../md__8collab__env.html#autotoc_md5',1,'']]],
  ['additional_20resources_42',['Additional Resources',['../md_AGENTS.html#autotoc_md67',1,'']]],
  ['addressed_43',['Addressed',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1138',1,'Code Review Addressed'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md674',1,'Code Review Issues Addressed'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1110',1,'Problem Addressed']]],
  ['addresssanitizer_20asan_44',['AddressSanitizer (ASan)',['../md_skills_2claude__build.html#autotoc_md1219',1,'']]],
  ['addresssanitizer_20for_20runtime_20detection_45',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md1237',1,'']]],
  ['advanced_20usage_46',['Advanced Usage',['../md_README.html#autotoc_md925',1,'']]],
  ['after_47',['After',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md175',1,'After'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md183',1,'After'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md237',1,'After'],['../md_REFACTORING__NOTES.html#autotoc_md996',1,'After'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md411',1,'Example - Before vs After']]],
  ['after_20axe_20yaml_48',['After (axe.yaml)',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md179',1,'']]],
  ['after_20comparison_20of_20fixes_49',['Before/After Comparison of Fixes',['../md_BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['after_20fix_50',['Impact After Fix',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md235',1,'']]],
  ['agent_51',['When to Use Each Agent',['../md_README.html#autotoc_md913',1,'']]],
  ['agent_52',['Security-Focused Agent (1 agent)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1144',1,'']]],
  ['agent_201_20agent_53',['Security-Focused Agent (1 agent)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1144',1,'']]],
  ['agent_20aliases_54',['Agent Aliases',['../md_IMPROVEMENTS__FINAL.html#autotoc_md512',1,'']]],
  ['agent_20aliasing_20system_20✅_55',['Phase 2: Agent Aliasing System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md544',1,'']]],
  ['agent_20code_20analysis_56',['Example: Multi-Agent Code Analysis',['../md_README.html#autotoc_md899',1,'']]],
  ['agent_20collaboration_57',['Agent Collaboration',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1161',1,'Example 3: Multi-Agent Collaboration'],['../md_skills_2build.html#autotoc_md1200',1,'Example 4: Multi-Agent Collaboration'],['../md_MODELS__FINAL.html#autotoc_md656',1,'Multi-Agent Collaboration'],['../md_README.html#autotoc_md931',1,'Multi-Agent Collaboration']]],
  ['agent_20collaboration_20issues_58',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_BUG__FIX__SUMMARY.html',1,'']]],
  ['agent_20commands_20during_20sessions_59',['New Agent Commands (During Sessions)',['../md_IMPROVEMENTS__README.html#autotoc_md554',1,'']]],
  ['agent_20communication_20tokens_60',['Agent Communication Tokens',['../md_MISSION.html#autotoc_md605',1,'']]],
  ['agent_20conversations_61',['Basic Agent Conversations',['../md_README.html#autotoc_md894',1,'']]],
  ['agent_20coordination_62',['Agent Coordination',['../md__8collab__shared.html#autotoc_md14',1,'']]],
  ['agent_20coverage_63',['Agent Coverage',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1152',1,'']]],
  ['agent_20execution_20engine_64',['Agent eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['agent_20execution_20engine_20✅_65',['AXE - Agent eXecution Engine ✅',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'']]],
  ['agent_20expert_66',['Python Agent Expert',['../md_skills_2python__agent__expert.html',1,'']]],
  ['agent_20integration_67',['GitHub Agent Integration',['../md_docs_2GITHUB__AGENT__INTEGRATION.html',1,'']]],
  ['agent_20lifecycle_68',['Agent Lifecycle',['../md_IMPROVEMENTS__README.html#autotoc_md563',1,'']]],
  ['agent_20ranks_20levels_69',['Agent Ranks &amp;amp; Levels',['../md_QUICK__REFERENCE.html#autotoc_md840',1,'']]],
  ['agent_20rate_20limiting_20✅_70',['3. Agent Rate Limiting ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md425',1,'']]],
  ['agent_20reference_71',['Agent Reference',['../md_README.html#autotoc_md911',1,'']]],
  ['agent_20session_20commands_72',['Agent Session Commands',['../md_IMPROVEMENTS__FINAL.html#autotoc_md538',1,'']]],
  ['agent_20skills_20system_20implementation_20summary_73',['Agent Skills System Implementation Summary',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['agent_20stuck_20or_20confused_74',['&quot;Agent stuck or confused&quot;',['../md_QUICK__REFERENCE.html#autotoc_md858',1,'']]],
  ['agent_20system_20improvement_20reference_20guide_75',['AXE Multi-Agent System - Improvement Reference Guide',['../md_IMPROVEMENTS__FINAL.html',1,'']]],
  ['agent_20system_20model_20configuration_20reference_76',['AXE Multi-Agent System - Model Configuration Reference',['../md_MODELS__FINAL.html',1,'']]],
  ['agent_20usage_77',['Agent Usage',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md294',1,'']]],
  ['agent_20work_78',['Test Projects for Multi-Agent Work',['../md_MODELS__FINAL.html#autotoc_md658',1,'']]],
  ['agent_20workspace_79',['Per-Agent Workspace',['../md_IMPROVEMENTS__FINAL.html#autotoc_md533',1,'']]],
  ['agent_5fabbrevs_80',['AGENT_ABBREVS',['../namespacebenchmark__acp.html#a5001408d35bc1fea7887cef4c9c6caf2',1,'benchmark_acp']]],
  ['agent_5faliases_81',['agent_aliases',['../classaxe_1_1CollaborativeSession.html#ab96c4604ab89c35f01d78a9133584ee0',1,'axe::CollaborativeSession']]],
  ['agent_5fconfigs_82',['agent_configs',['../classcore_1_1multiprocess_1_1MultiAgentCoordinator.html#a3f96caf551ff9006459a6995d5d265d2',1,'core::multiprocess::MultiAgentCoordinator']]],
  ['agent_5fdb_2epy_83',['agent_db.py',['../agent__db_8py.html',1,'']]],
  ['agent_5fid_84',['agent_id',['../classcore_1_1multiprocess_1_1AgentWorkerProcess.html#a8548f8b171f5b85099f8a836f60ed7ba',1,'core::multiprocess::AgentWorkerProcess']]],
  ['agent_5fids_85',['agent_ids',['../classaxe_1_1CollaborativeSession.html#ac380ead9bbca25a5579dbd99a5f1f1f7',1,'axe::CollaborativeSession']]],
  ['agent_5fmanager_20py_86',['3. &lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md341',1,'']]],
  ['agent_5fmanager_2epy_87',['agent_manager.py',['../agent__manager_8py.html',1,'']]],
  ['agent_5fmgr_88',['agent_mgr',['../classaxe_1_1CollaborativeSession.html#ab931398b863c755ac1cfda96f01cc320',1,'axe.CollaborativeSession.agent_mgr'],['../classaxe_1_1ChatSession.html#ae5266ac3557ae29c4bc51d1117c47918',1,'axe.ChatSession.agent_mgr']]],
  ['agent_5fname_89',['agent_name',['../classcore_1_1multiprocess_1_1AgentWorkerProcess.html#a30eeb225977669759867e300e3f8857a',1,'core::multiprocess::AgentWorkerProcess']]],
  ['agent_5frequest_5fpush_90',['agent_request_push',['../classcore_1_1github__agent_1_1GitHubAgent.html#a304a9df6d3a2226cc3c8d7cc29894a9c',1,'core::github_agent::GitHubAgent']]],
  ['agent_5fstate_5fmigrations_91',['AGENT_STATE_MIGRATIONS',['../namespacedatabase_1_1schema.html#abb008a4c84e15fa5ae3b0b98473ba98b',1,'database::schema']]],
  ['agent_5fstate_5ftable_92',['AGENT_STATE_TABLE',['../namespacedatabase_1_1schema.html#a361887f9cac360a4974f4396a8615717',1,'database::schema']]],
  ['agent_5fstats_93',['agent_stats',['../classutils_1_1token__stats_1_1TokenStats.html#a2dc0fcf256c5cfc0377272a0b982c809',1,'utils::token_stats::TokenStats']]],
  ['agent_5fstatus_94',['agent_status',['../classcore_1_1multiprocess_1_1SharedContext.html#a6e2e9ea4621f680426d28eefcf5c47bd',1,'core::multiprocess::SharedContext']]],
  ['agent_5ftoken_5fbreak_5frequest_95',['AGENT_TOKEN_BREAK_REQUEST',['../namespacecore_1_1constants.html#ae77a3f2ff99cb86ef3e6edb025668d5e',1,'core::constants']]],
  ['agent_5ftoken_5femergency_96',['AGENT_TOKEN_EMERGENCY',['../namespacecore_1_1constants.html#a472a8a978e957c7045853ec469c7e012',1,'core::constants']]],
  ['agent_5ftoken_5fgithub_5fready_97',['AGENT_TOKEN_GITHUB_READY',['../namespacecore_1_1constants.html#af2d3f8f391c2c51fb60376b2cffa67cb',1,'core::constants']]],
  ['agent_5ftoken_5fpass_98',['AGENT_TOKEN_PASS',['../namespacecore_1_1constants.html#a26f73e2e79eecaf06c38f035fb0aff1e',1,'core::constants']]],
  ['agent_5ftoken_5fspawn_99',['AGENT_TOKEN_SPAWN',['../namespacecore_1_1constants.html#a1c38858bf4fac9bbb8766cdbebb55911',1,'core::constants']]],
  ['agent_5ftoken_5fstatus_100',['AGENT_TOKEN_STATUS',['../namespacecore_1_1constants.html#ad6a4a88a8da17b21ca78e98a88e32395',1,'core::constants']]],
  ['agent_5ftoken_5ftask_5fcomplete_101',['AGENT_TOKEN_TASK_COMPLETE',['../namespacecore_1_1constants.html#a8dfdca2464b7ef53a688c534323208f5',1,'core::constants']]],
  ['agentdatabase_102',['AgentDatabase',['../classdatabase_1_1agent__db_1_1AgentDatabase.html',1,'database::agent_db']]],
  ['agentdatabase_20_5f_5finit_5f_5f_103',['2. Updated &lt;span class=&quot;tt&quot;&gt;AgentDatabase.__init__()&lt;/span&gt;',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md225',1,'']]],
  ['agentmanager_104',['AgentManager',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1301',1,'6. Integration with AgentManager'],['../classcore_1_1agent__manager_1_1AgentManager.html',1,'core.agent_manager.AgentManager']]],
  ['agents_105',['Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'1. Updated axe.yaml - BUILD GUIDELINES for All Agents'],['../md_README.html#autotoc_md912',1,'Available Agents'],['../md_README.html#autotoc_md951',1,'Integration with Agents'],['../md_README.html#autotoc_md969',1,'Integration with Agents'],['../md_workshop__quick__reference.html#autotoc_md1414',1,'Integration with Agents'],['../md__8collab__env.html#autotoc_md11',1,'Notes for Agents'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md532',1,'Safe Commands for Agents']]],
  ['agents_106',['agents',['../classaxe_1_1CollaborativeSession.html#a92644ec2213903477715a66705bd4eed',1,'axe.CollaborativeSession.agents'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1143',1,'General Agents (17 agents)']]],
  ['agents_2017_20agents_107',['General Agents (17 agents)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1143',1,'']]],
  ['agents_20confused_20about_20read_20write_20block_20syntax_108',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['agents_20confused_20about_20read_20write_20block_20syntax_20✅_109',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['agents_20counter_20✅_110',['Bug 2: Active Agents Counter ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1325',1,'']]],
  ['agents_20md_111',['Integration with AGENTS.md',['../md_skills_2claude__build.html#autotoc_md1250',1,'']]],
  ['agents_20md_20for_20axe_112',['AGENTS.md for AXE',['../md_AGENTS.html',1,'']]],
  ['agents_20md_20standard_20compliance_113',['2. AGENTS.md Standard Compliance',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1295',1,'']]],
  ['agents_20never_20get_20turns_20✅_114',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['agents_20not_20cooperating_115',['&quot;Agents not cooperating&quot;',['../md_QUICK__REFERENCE.html#autotoc_md857',1,'']]],
  ['agents_20now_20working_116',['Agents Now Working',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md34',1,'']]],
  ['agents_20see_117',['What Agents See',['../md_QUICK__REFERENCE.html#autotoc_md855',1,'']]],
  ['agents_2emd_118',['AGENTS.md',['../AGENTS_8md.html',1,'']]],
  ['agentworkerprocess_119',['AgentWorkerProcess',['../classcore_1_1multiprocess_1_1AgentWorkerProcess.html',1,'core::multiprocess']]],
  ['ai_120',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md169',1,'']]],
  ['ai_20providers_121',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md162',1,'']]],
  ['ai_20support_122',['Multi-Provider AI Support',['../md_README.html#autotoc_md871',1,'']]],
  ['alias_5fexists_123',['alias_exists',['../classdatabase_1_1agent__db_1_1AgentDatabase.html#abfdbfe1b8aea2627d8d17c2fc7ba74f6',1,'database::agent_db::AgentDatabase']]],
  ['alias_5fmappings_5ftable_124',['ALIAS_MAPPINGS_TABLE',['../namespacedatabase_1_1schema.html#afeebb21e25b7e572011b80fac5833190',1,'database::schema']]],
  ['aliases_125',['Aliases',['../md_IMPROVEMENTS__FINAL.html#autotoc_md512',1,'Agent Aliases'],['../md_QUICK__REFERENCE.html#autotoc_md845',1,'Aliases'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md515',1,'Special Aliases']]],
  ['aliasing_20system_20✅_126',['Phase 2: Agent Aliasing System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md544',1,'']]],
  ['all_20agents_127',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'']]],
  ['all_20features_20implemented_128',['✅ All Features Implemented',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md422',1,'']]],
  ['all_20implemented_20features_129',['Summary of All Implemented Features',['../md_IMPROVEMENTS__README.html#autotoc_md568',1,'']]],
  ['all_20met_130',['Success Criteria (All Met)',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1334',1,'']]],
  ['all_20output_131',['❌ Don&apos;t Remove All Output',['../md_skills_2build.html#autotoc_md1187',1,'']]],
  ['all_20tests_132',['[... all tests ...]',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1505',1,'']]],
  ['all_20tests_20passed_133',['✅ ALL TESTS PASSED!',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1506',1,'']]],
  ['all_20trials_20fail_134',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['all_20unit_20tests_135',['Run all unit tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md468',1,'']]],
  ['allow_20execution_136',['1. Default-Allow Execution',['../md_SANDBOX.html#autotoc_md1029',1,'']]],
  ['allow_20security_20model_137',['1. Default-Allow Security Model',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1064',1,'']]],
  ['allowed_20bug_20fixed_20_3a_138',['✅ Now Allowed (Bug Fixed):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md31',1,'']]],
  ['always_20use_20silent_20flags_20first_139',['1. Always Use Silent Flags First',['../md_skills_2build.html#autotoc_md1181',1,'']]],
  ['analysis_140',['Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md751',1,'✅ VALIDATED - Saw (Taint Analysis)'],['../md_README.html#autotoc_md923',1,'Analysis'],['../md_workshop__benchmarks.html#autotoc_md1350',1,'Code Snippet Analysis'],['../md_workshop__benchmarks.html#autotoc_md1358',1,'Comparative Analysis'],['../md_skills_2claude__build.html#autotoc_md1216',1,'Cppcheck (Static Analysis)'],['../md_workshop__security__audit.html#autotoc_md1435',1,'Dependency Security Analysis'],['../md_README.html#autotoc_md916',1,'Disassembly &amp;amp; Analysis'],['../md_workshop__test__results.html#autotoc_md1467',1,'Error Analysis'],['../md_README.html#autotoc_md899',1,'Example: Multi-Agent Code Analysis'],['../md_workshop__benchmarks.html#autotoc_md1348',1,'Function-Level Analysis'],['../md_workshop__security__audit.html#autotoc_md1424',1,'Issue #2: Memory Exhaustion in Chisel Analysis'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md793',1,'Part 5: Code Quality Analysis'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md799',1,'Part 6: Test Coverage Analysis'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md803',1,'Part 7: Dependency Analysis'],['../md_workshop__dependency__validation.html#autotoc_md1381',1,'Performance Impact Analysis'],['../md_workshop__benchmarks.html#autotoc_md1353',1,'Project-Scale Analysis'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md402',1,'Root Cause Analysis'],['../md_README.html#autotoc_md933',1,'Round-Robin Analysis'],['../md_README.html#autotoc_md962',1,'Saw - Taint Analysis'],['../md_workshop__quick__reference.html#autotoc_md1403',1,'Saw - Taint Analysis'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1084',1,'Scenario 2: Code Analysis'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md28',1,'Security Analysis'],['../md_FIXES__SUMMARY.html#autotoc_md376',1,'Security Analysis'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1307',1,'Token Efficiency Analysis'],['../md_skills_2claude__build.html#autotoc_md1213',1,'Valgrind (Memory Analysis)']]],
  ['analysis_20benchmarks_141',['Saw - Taint Analysis Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1349',1,'']]],
  ['analysis_20expanded_142',['Build Analysis (EXPANDED!)',['../md_README.html#autotoc_md905',1,'']]],
  ['analysis_20expert_143',['Analysis Expert',['../md_skills_2ida__pro__analysis__patterns.html',1,'IDA Pro / Decompiler Analysis Expert'],['../md_skills_2x86__assembly__expert.html',1,'x86 Assembly Analysis Expert']]],
  ['analysis_20framework_20comprehensive_20validation_20report_144',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_PR23__VALIDATION__REPORT.html',1,'']]],
  ['analysis_20framework_20executive_20summary_145',['PR #23 Workshop Dynamic Analysis Framework - Executive Summary',['../md_PR23__EXECUTIVE__SUMMARY.html',1,'']]],
  ['analysis_20history_146',['View Analysis History',['../md_README.html#autotoc_md966',1,'']]],
  ['analysis_20libraries_147',['Primary Analysis Libraries',['../md_workshop__dependency__validation.html#autotoc_md1366',1,'']]],
  ['analysis_20patterns_148',['Key Analysis Patterns',['../md_skills_2x86__assembly__expert.html#autotoc_md1288',1,'']]],
  ['analysis_20performance_149',['Binary Analysis Performance',['../md_workshop__benchmarks.html#autotoc_md1347',1,'']]],
  ['analysis_20quietly_150',['Run static analysis quietly',['../md_skills_2claude__build.html#autotoc_md1217',1,'']]],
  ['analysis_20results_151',['Performance Analysis Results',['../md_workshop__benchmarks.html#autotoc_md1344',1,'']]],
  ['analysis_20silent_152',['Phase 2: Static Analysis (Silent)',['../md_skills_2claude__build.html#autotoc_md1232',1,'']]],
  ['analysis_20silent_153',['analysis silent',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1160',1,'Runtime analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md1252',1,'Runtime analysis (silent)'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1159',1,'Static analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md1251',1,'Static analysis (silent)']]],
  ['analysis_20tools_154',['Analysis Tools',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md697',1,'✅ Four Dynamic Analysis Tools'],['../md_README.html#autotoc_md937',1,'Analysis Tools'],['../md_README.html#autotoc_md957',1,'Workshop - Dynamic Analysis Tools']]],
  ['analysis_20tools_20implemented_155',['Claim 1: Four Analysis Tools Implemented',['../md_PR23__VALIDATION__REPORT.html#autotoc_md749',1,'']]],
  ['analyze_5farchive_156',['analyze_archive',['../namespacetools_1_1build__analyzer.html#a9508c930f379c7a1a86cfcbce4656aa6',1,'tools::build_analyzer']]],
  ['analyze_5fbinary_157',['analyze_binary',['../classworkshop_1_1chisel_1_1ChiselAnalyzer.html#a08898a342ce3b5f527cc5ec8e235ffdb',1,'workshop::chisel::ChiselAnalyzer']]],
  ['analyze_5fbuild_5fstatus_5fefficiency_158',['analyze_build_status_efficiency',['../namespacetest__efficiency__analysis.html#a238b3c8c07dc1d001ddaf9a57d05d719',1,'test_efficiency_analysis']]],
  ['analyze_5fcode_159',['analyze_code',['../classworkshop_1_1saw_1_1SawTracker.html#a879cdc1cb42bceaff7f1ce6f2578c2bb',1,'workshop::saw::SawTracker']]],
  ['analyze_5fcollaboration_5fimprovements_160',['analyze_collaboration_improvements',['../namespacetest__efficiency__analysis.html#ac8d56aba10c1ef9afeba7929b99d56dd',1,'test_efficiency_analysis']]],
  ['analyze_5fcorpus_5ffile_161',['analyze_corpus_file',['../namespacebenchmark__acp.html#aa43f698f5f9ae95cf20fa9d98224edbc',1,'benchmark_acp']]],
  ['analyze_5fdiff_5fpatch_5fefficiency_162',['analyze_diff_patch_efficiency',['../namespacetest__efficiency__analysis.html#a8eeb792c37aa1f4c73b5e6151ac6d538',1,'test_efficiency_analysis']]],
  ['analyze_5fdirectory_163',['analyze_directory',['../namespacetools_1_1build__analyzer.html#adb11a626c64e923dfc5853158f9791fa',1,'tools::build_analyzer']]],
  ['analyze_5ffunction_164',['analyze_function',['../classworkshop_1_1chisel_1_1ChiselAnalyzer.html#a27aee86cdc5318fc86c52a95b4148b50',1,'workshop.chisel.ChiselAnalyzer.analyze_function()'],['../classworkshop_1_1saw_1_1SawTracker.html#a7ff782d2c81dd58f0af9bbca73d2caf9',1,'workshop.saw.SawTracker.analyze_function()']]],
  ['analyze_5flimit_5fchanges_165',['analyze_limit_changes',['../namespacetest__efficiency__analysis.html#ae66ff1876f3298ef19606bb494653fa8',1,'test_efficiency_analysis']]],
  ['analyze_5ftruncation_5fsavings_166',['analyze_truncation_savings',['../namespacetest__efficiency__analysis.html#a7933bfeaad467bd549a2b93625c1571c',1,'test_efficiency_analysis']]],
  ['analyzer_167',['Clang Static Analyzer',['../md_skills_2claude__build.html#autotoc_md1222',1,'']]],
  ['analyzer_20dependency_20helper_20✅_168',['5. Build Analyzer Dependency Helper ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md427',1,'']]],
  ['analyzer_20helper_169',['Build Analyzer Helper',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md447',1,'']]],
  ['analyzer_20quietly_170',['Run Clang static analyzer quietly',['../md_skills_2claude__build.html#autotoc_md1223',1,'']]],
  ['and_20build_20quietly_171',['Clean and build quietly',['../md_skills_2build.html#autotoc_md1195',1,'']]],
  ['and_20extensibility_20guide_172',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['and_20feedback_173',['Rejection and Feedback',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md300',1,'']]],
  ['and_20files_174',['3. Created Skills Directory and Files',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1146',1,'']]],
  ['and_20heredoc_20parsing_20bug_20fixes_175',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['and_20permissions_176',['Security and Permissions',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1487',1,'']]],
  ['and_20run_20tests_20silently_177',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md1220',1,'']]],
  ['and_20setup_178',['Clone and Setup',['../md_README.html#autotoc_md879',1,'']]],
  ['angr_20symbolic_20execution_20engine_179',['angr (Symbolic Execution Engine)',['../md_workshop__dependency__validation.html#autotoc_md1367',1,'']]],
  ['anthropic_20claude_180',['Anthropic Claude',['../md_API__PROVIDERS.html#autotoc_md107',1,'Anthropic (Claude)'],['../md_MODELS__FINAL.html#autotoc_md621',1,'Anthropic (Claude)'],['../md_README.html#autotoc_md889',1,'Anthropic (Claude)']]],
  ['anthropic_20claude_20specific_20features_20in_20axe_181',['Anthropic Claude-Specific Features in AXE',['../md_docs_2ANTHROPIC__FEATURES.html',1,'']]],
  ['anthropic_20claude_20specific_20optimizations_20implementation_20summary_182',['Anthropic Claude-Specific Optimizations - Implementation Summary',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['anthropic_20sdk_20error_20fixed_20✓_183',['1. Anthropic SDK Error Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md347',1,'']]],
  ['anthropic_5ffeatures_184',['anthropic_features',['../classcore_1_1agent__manager_1_1AgentManager.html#ab9e7169142475363dde711cae91b47f4',1,'core::agent_manager::AgentManager']]],
  ['anthropic_5ffeatures_2emd_185',['ANTHROPIC_FEATURES.md',['../ANTHROPIC__FEATURES_8md.html',1,'']]],
  ['anthropic_5ffeatures_2epy_186',['anthropic_features.py',['../anthropic__features_8py.html',1,'']]],
  ['anthropic_5ffeatures_5fdemo_187',['anthropic_features_demo',['../namespaceanthropic__features__demo.html',1,'']]],
  ['anthropic_5ffeatures_5fdemo_2epy_188',['anthropic_features_demo.py',['../anthropic__features__demo_8py.html',1,'']]],
  ['anthropic_5fimplementation_5fsummary_2emd_189',['ANTHROPIC_IMPLEMENTATION_SUMMARY.md',['../ANTHROPIC__IMPLEMENTATION__SUMMARY_8md.html',1,'']]],
  ['anthropicfeatures_190',['AnthropicFeatures',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html',1,'core::anthropic_features']]],
  ['api_191',['API',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1305',1,'SkillsManager Class API'],['../md_MODELS__FINAL.html#autotoc_md630',1,'Usage - OpenAI-Compatible API']]],
  ['api_20beta_192',['4. Files API (Beta)',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md262',1,'']]],
  ['api_20beta_20optional_20✅_193',['4. Files API (Beta, Optional) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md77',1,'']]],
  ['api_20connections_194',['Testing API Connections',['../md_README.html#autotoc_md978',1,'']]],
  ['api_20endpoints_20summary_195',['API Endpoints Summary',['../md_API__PROVIDERS.html#autotoc_md153',1,'']]],
  ['api_20keys_196',['Testing API Keys',['../md_API__PROVIDERS.html#autotoc_md158',1,'']]],
  ['api_20keys_197',['Manual testing (requires API keys)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md470',1,'']]],
  ['api_20keys_20setup_198',['API Keys Setup',['../md_README.html#autotoc_md882',1,'']]],
  ['api_20not_20working_199',['Files API not working',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md276',1,'']]],
  ['api_20parameter_20error_20critical_200',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md460',1,'']]],
  ['api_20provider_20documentation_201',['AXE API Provider Documentation',['../md_API__PROVIDERS.html',1,'']]],
  ['api_20provider_20limits_202',['API Provider Limits',['../md_IMPROVEMENTS__FINAL.html#autotoc_md505',1,'']]],
  ['api_20providers_203',['API Providers',['../md_README.html#autotoc_md885',1,'']]],
  ['api_20usage_204',['API Usage',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md260',1,'']]],
  ['api_5fproviders_2emd_205',['API_PROVIDERS.md',['../API__PROVIDERS_8md.html',1,'']]],
  ['appearing_206',['No Results Appearing?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1524',1,'']]],
  ['append_20results_20to_20response_207',['Append results to response',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md463',1,'']]],
  ['append_5fto_5fshared_208',['append_to_shared',['../classaxe_1_1SharedWorkspace.html#a2bc73dc80bbc403c5171caf656937cb2',1,'axe::SharedWorkspace']]],
  ['appendix_20a_3a_20test_20execution_20logs_209',['Appendix A: Test Execution Logs',['../md_PR23__VALIDATION__REPORT.html#autotoc_md831',1,'']]],
  ['appendix_20b_3a_20file_20changes_20summary_210',['Appendix B: File Changes Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md834',1,'']]],
  ['applied_211',['Best Practices Applied',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md94',1,'']]],
  ['approach_212',['Approach',['../md_AGENTS.html#autotoc_md58',1,'Default Build Approach'],['../md_REFACTORING__NOTES.html#autotoc_md1002',1,'Implementation Approach']]],
  ['approve_20mode_20non_20interactive_213',['Auto-Approve Mode (Non-Interactive)',['../md_README.html#autotoc_md927',1,'']]],
  ['approve_20not_20default_20in_20collab_20mode_214',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['approve_20not_20default_20in_20collab_20mode_20✅_215',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['approve_5fbreak_216',['approve_break',['../classmanagers_1_1break__system_1_1BreakSystem.html#a320c4885461546fbe14f59f4ea29ed0b',1,'managers::break_system::BreakSystem']]],
  ['approved_20for_20merge_217',['✅ APPROVED FOR MERGE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md822',1,'']]],
  ['architecture_218',['Architecture',['../md_AGENTS.html#autotoc_md60',1,'Architecture'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md494',1,'Architecture'],['../md_SANDBOX.html#autotoc_md1045',1,'Architecture']]],
  ['architecture_20and_20extensibility_20guide_219',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['architecture_20diagrams_220',['AXE Architecture Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md279',1,'']]],
  ['architecture_20notes_221',['Architecture Notes',['../md_IMPROVEMENTS__README.html#autotoc_md561',1,'']]],
  ['architecture_20overview_222',['Architecture Overview',['../md_MISSION.html#autotoc_md609',1,'']]],
  ['architecture_2emd_223',['ARCHITECTURE.md',['../ARCHITECTURE_8md.html',1,'']]],
  ['are_20now_20handled_20exclusively_20by_20axe_20py_20responseprocessor_224',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['as_20a_20single_20command_225',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['as_20before_226',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['asan_227',['AddressSanitizer (ASan)',['../md_skills_2claude__build.html#autotoc_md1219',1,'']]],
  ['asan_20and_20run_20tests_20silently_228',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md1220',1,'']]],
  ['assembly_20analysis_20expert_229',['x86 Assembly Analysis Expert',['../md_skills_2x86__assembly__expert.html',1,'']]],
  ['assessment_230',['Assessment',['../md_workshop__security__audit.html#autotoc_md1441',1,'Compliance Assessment'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md746',1,'Overall Assessment'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md825',1,'Part 12: Risk Assessment'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md729',1,'Risk Assessment']]],
  ['assignment_231',['Supervisor Role Assignment',['../md_MODELS__FINAL.html#autotoc_md659',1,'']]],
  ['assume_20silence_20means_20success_232',['❌ Don&apos;t Assume Silence Means Success',['../md_skills_2build.html#autotoc_md1188',1,'']]],
  ['assurance_233',['Assurance',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md437',1,'Quality Assurance'],['../md_workshop__quick__reference.html#autotoc_md1416',1,'Validation &amp;amp; Quality Assurance']]],
  ['ast_20abstract_20syntax_20trees_234',['ast (Abstract Syntax Trees)',['../md_workshop__dependency__validation.html#autotoc_md1371',1,'']]],
  ['at_20session_20start_20pinned_20message_20_3a_235',['Display at session start (pinned message):',['../md_IMPROVEMENTS__FINAL.html#autotoc_md524',1,'']]],
  ['attack_20surface_20reduction_236',['Attack Surface Reduction',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1074',1,'']]],
  ['attributions_20credits_237',['Attributions &amp;amp; Credits',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1342',1,'']]],
  ['audit_238',['Audit',['../md_PR23__VALIDATION__REPORT.html#autotoc_md770',1,'Document 3: Security Audit'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1158',1,'Example 2: Claude Security Audit'],['../md_workshop__security__audit.html',1,'Workshop Tools Security Audit']]],
  ['audit_20scope_239',['Audit Scope',['../md_workshop__security__audit.html#autotoc_md1419',1,'']]],
  ['audit_20workflow_240',['Real-World Example: Security Audit Workflow',['../md_README.html#autotoc_md972',1,'']]],
  ['audit_20workflow_20example_241',['Security Audit Workflow Example',['../md_skills_2claude__build.html#autotoc_md1228',1,'']]],
  ['auditing_20workflow_242',['Security Auditing Workflow',['../md_skills_2claude__build.html#autotoc_md1209',1,'']]],
  ['audits_243',['Audits',['../md_skills_2claude__build.html#autotoc_md1240',1,'Best Practices for Security Audits'],['../md_skills_2claude__build.html#autotoc_md1239',1,'Token Savings in Security Audits']]],
  ['author_244',['Author',['../md_README.html#autotoc_md987',1,'']]],
  ['auto_20approve_20mode_20non_20interactive_245',['Auto-Approve Mode (Non-Interactive)',['../md_README.html#autotoc_md927',1,'']]],
  ['auto_20approve_20not_20default_20in_20collab_20mode_246',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['auto_20approve_20not_20default_20in_20collab_20mode_20✅_247',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['autoconf_20configure_248',['Autoconf/Configure',['../md_skills_2build.html#autotoc_md1171',1,'']]],
  ['automake_5fpatterns_249',['AUTOMAKE_PATTERNS',['../namespacetools_1_1build__analyzer.html#a1736fdaf188ae783fd3ef47eee47a661',1,'tools::build_analyzer']]],
  ['automated_20installation_20testing_250',['Automated Installation Testing',['../md_workshop__dependency__validation.html#autotoc_md1379',1,'']]],
  ['automated_20tests_251',['Run automated tests',['../md_QUICK__REFERENCE.html#autotoc_md849',1,'']]],
  ['automatic_252',['Basic Usage (Automatic)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1311',1,'']]],
  ['automatic_20features_253',['Automatic Features',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md250',1,'']]],
  ['autonomous_20collaborative_20sessions_20new_254',['Autonomous Collaborative Sessions (NEW!)',['../md_README.html#autotoc_md932',1,'']]],
  ['available_255',['HuggingFace (Llama) - Free Tier Available!',['../md_README.html#autotoc_md886',1,'']]],
  ['available_256',['Extended thinking not available',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md274',1,'']]],
  ['available_20agents_257',['Available Agents',['../md_README.html#autotoc_md912',1,'']]],
  ['available_20docs_258',['Available Docs',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1094',1,'']]],
  ['available_20falling_20back_20to_20whitelist_20mode_259',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['available_20models_260',['Available Models',['../md_MODELS__FINAL.html#autotoc_md649',1,'']]],
  ['award_5fxp_261',['award_xp',['../classdatabase_1_1agent__db_1_1AgentDatabase.html#a296bb2622baac11158a1d47114fc1507',1,'database::agent_db::AgentDatabase']]],
  ['award_5fxp_5ffor_5factivity_262',['award_xp_for_activity',['../namespaceprogression_1_1xp__system.html#a6981e4eb92d958095f443501eead4979',1,'progression::xp_system']]],
  ['awards_263',['Awards',['../md_QUICK__REFERENCE.html#autotoc_md841',1,'XP Awards'],['../md_workshop__quick__reference.html#autotoc_md1412',1,'XP Awards']]],
  ['awards_20dictionary_264',['✅ VALIDATED - XP Awards Dictionary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md760',1,'']]],
  ['axe_265',['AXE',['../md_AGENTS.html',1,'AGENTS.md for AXE'],['../md_docs_2ANTHROPIC__FEATURES.html',1,'Anthropic Claude-Specific Features in AXE'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1155',1,'Integration with AXE'],['../md_llm__prep_2project__guidance.html',1,'Project Guidance for AXE'],['../md_AGENTS.html#autotoc_md45',1,'Running AXE'],['../md_README.html#autotoc_md867',1,'Why AXE?']]],
  ['axe_266',['axe',['../namespaceaxe.html',1,'']]],
  ['axe_20agent_20execution_20engine_267',['AXE Agent eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['axe_20agent_20execution_20engine_20✅_268',['AXE - Agent eXecution Engine ✅',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'']]],
  ['axe_20api_20provider_20documentation_269',['AXE API Provider Documentation',['../md_API__PROVIDERS.html',1,'']]],
  ['axe_20architecture_20and_20extensibility_20guide_270',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['axe_20architecture_20diagrams_271',['AXE Architecture Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md279',1,'']]],
  ['axe_20enhancement_20implementation_20complete_20✅_272',['AXE Enhancement Implementation - Complete ✅',['../md_IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['axe_20framework_20compatibility_273',['AXE Framework Compatibility',['../md_workshop__dependency__validation.html#autotoc_md1389',1,'']]],
  ['axe_20integration_274',['✅ Complete AXE Integration',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md698',1,'']]],
  ['axe_20multi_20agent_20system_20improvement_20reference_20guide_275',['AXE Multi-Agent System - Improvement Reference Guide',['../md_IMPROVEMENTS__FINAL.html',1,'']]],
  ['axe_20multi_20agent_20system_20model_20configuration_20reference_276',['AXE Multi-Agent System - Model Configuration Reference',['../md_MODELS__FINAL.html',1,'']]],
  ['axe_20multiagent_20improvements_20implementation_20summary_277',['AXE Multiagent Improvements - Implementation Summary',['../md_IMPROVEMENTS__README.html',1,'']]],
  ['axe_20multiagent_20quick_20reference_20card_278',['AXE Multiagent - Quick Reference Card',['../md_QUICK__REFERENCE.html',1,'']]],
  ['axe_20multiple_20issues_20fix_20summary_279',['AXE Multiple Issues Fix Summary',['../md_FIXES__SUMMARY.html',1,'']]],
  ['axe_20native_20blocks_280',['3. AXE Native Blocks',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md691',1,'']]],
  ['axe_20native_20format_281',['Example 3: AXE Native Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md685',1,'']]],
  ['axe_20native_20read_20write_20exec_20blocks_282',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['axe_20project_20security_20report_283',['AXE Project Security Report',['../md_SECURITY__REPORT.html',1,'']]],
  ['axe_20py_20collaborativesession_284',['4. &lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt; (CollaborativeSession)',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md342',1,'']]],
  ['axe_20py_20refactoring_20notes_285',['AXE.PY Refactoring Notes',['../md_REFACTORING__NOTES.html',1,'']]],
  ['axe_20py_20responseprocessor_286',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['axe_20session_20termination_20bugs_287',['Fix Summary: AXE Session Termination Bugs',['../md_TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['axe_20test_20mission_288',['AXE Test Mission',['../md_tests_2MISSION.html',1,'']]],
  ['axe_20yaml_289',['axe yaml',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md179',1,'After (axe.yaml)'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md178',1,'Before (axe.yaml)'],['../md_README.html#autotoc_md883',1,'Configuration File (axe.yaml)'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md590',1,'Enable in axe.yaml'],['../md_skills_2build.html#autotoc_md1178',1,'Integration with axe.yaml']]],
  ['axe_20yaml_20build_20guidelines_20for_20all_20agents_290',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'']]],
  ['axe_20yaml_20updates_291',['&lt;span class=&quot;tt&quot;&gt;axe.yaml&lt;/span&gt; Updates',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1300',1,'']]],
  ['axe_2epy_292',['axe.py',['../axe_8py.html',1,'']]]
];
