var searchData=
[
  ['namespace_20isolation_0',['Namespace Isolation',['../md_SANDBOX.html#autotoc_md1030',1,'2. Linux Namespace Isolation'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1065',1,'2. Namespace Isolation']]],
  ['namespaces_1',['namespaces',['../classcore_1_1sandbox_1_1SandboxManager.html#a8db40d2ec58d885009d8be2e6465d195',1,'core::sandbox::SandboxManager']]],
  ['naming_2',['File Naming',['../md_AGENTS.html#autotoc_md52',1,'']]],
  ['native_20blocks_3',['3. AXE Native Blocks',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md691',1,'']]],
  ['native_20format_4',['Example 3: AXE Native Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md685',1,'']]],
  ['native_20read_20write_20exec_20blocks_5',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['natural_20format_6',['Example 1: Claude&apos;s Natural Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md683',1,'']]],
  ['needed_7',['Create parent dirs if needed',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md466',1,'']]],
  ['nested_20subshells_8',['3. Nested Subshells',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1122',1,'']]],
  ['network_20isolated_9',['Scenario 3: Network Isolated',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1085',1,'']]],
  ['network_20isolated_20sandbox_10',['Example 3: Network-Isolated Sandbox',['../md_SANDBOX.html#autotoc_md1039',1,'']]],
  ['never_20get_20turns_20✅_11',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['new_12',['NEW',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md344',1,'6. &lt;span class=&quot;tt&quot;&gt;tests/test_dynamic_max_tokens.py&lt;/span&gt; (NEW)'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md345',1,'7. &lt;span class=&quot;tt&quot;&gt;demo_dynamic_tokens.py&lt;/span&gt; (NEW)'],['../md_README.html#autotoc_md932',1,'Autonomous Collaborative Sessions (NEW!)'],['../md_README.html#autotoc_md906',1,'Rate Limiting (NEW!)'],['../md_README.html#autotoc_md903',1,'Session Management (NEW!)'],['../md_README.html#autotoc_md902',1,'Token Usage Commands (NEW!)'],['../md_README.html#autotoc_md907',1,'Token-Saving Optimizations (NEW!)']]],
  ['new_13',['New',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1515',1,'What&apos;s New?'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1518',1,'XML Format (New!)']]],
  ['new_20agent_20commands_20during_20sessions_14',['New Agent Commands (During Sessions)',['../md_IMPROVEMENTS__README.html#autotoc_md554',1,'']]],
  ['new_20ai_20providers_15',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md162',1,'']]],
  ['new_20code_16',['For New Code',['../md_REFACTORING__NOTES.html#autotoc_md1023',1,'']]],
  ['new_20codebase_20exploration_17',['1. New Codebase Exploration',['../md_README.html#autotoc_md953',1,'']]],
  ['new_20features_18',['Starting a Collaborative Session with New Features',['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'']]],
  ['new_20files_19',['New Files',['../md_PR23__VALIDATION__REPORT.html#autotoc_md836',1,'New Files'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1509',1,'New Files']]],
  ['new_20functions_20added_20',['New Functions Added',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md670',1,'']]],
  ['new_20module_20structure_21',['New Module Structure',['../md_REFACTORING__NOTES.html#autotoc_md997',1,'']]],
  ['new_20skills_22',['Creating New Skills',['../md_AGENTS.html#autotoc_md55',1,'']]],
  ['new_20test_20files_23',['New Test Files',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md26',1,'']]],
  ['new_20tests_20added_24',['New Tests Added',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md325',1,'New Tests Added'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md396',1,'New Tests Added']]],
  ['new_20token_20optimization_20strategies_25',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md165',1,'']]],
  ['new_20workshop_20tools_26',['3. Adding New Workshop Tools',['../md_ARCHITECTURE.html#autotoc_md164',1,'']]],
  ['newline_20e_20g_20cat_20eof_27',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['newly_20fixed_20_3a_28',['Edge Cases (newly fixed):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1134',1,'']]],
  ['next_20steps_29',['Next Steps',['../md_FIXES__SUMMARY.html#autotoc_md386',1,'Next Steps'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md453',1,'Next Steps'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md600',1,'Next Steps']]],
  ['ninja_30',['Ninja',['../md_skills_2build.html#autotoc_md1174',1,'']]],
  ['no_20breakage_31',['Existing tests (verify no breakage)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1522',1,'']]],
  ['no_20credits_20error_32',['No Credits Error',['../md_MODELS__FINAL.html#autotoc_md662',1,'']]],
  ['no_20duplicate_20execution_33',['Example 1: No Duplicate Execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md328',1,'']]],
  ['no_20hardcoded_20secrets_20verified_34',['No Hardcoded Secrets - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md786',1,'']]],
  ['no_20heredoc_20process_20line_20by_20line_20as_20before_35',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['no_20installation_20required_36',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md282',1,'']]],
  ['no_20rate_20limiting_37',['Finding #3: No Rate Limiting',['../md_workshop__security__audit.html#autotoc_md1432',1,'']]],
  ['no_20real_20bullying_38',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['no_20regressions_39',['✅ No Regressions',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md438',1,'']]],
  ['no_20results_20appearing_40',['No Results Appearing?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1524',1,'']]],
  ['node_41',['Node',['../structNode.html',1,'Node'],['../depklite_8c.html#a3b09f37e675bcd48a01bf22155996872',1,'Node:&#160;depklite.c']]],
  ['noise_42',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md1248',1,'']]],
  ['non_20blocking_43',['Non Blocking',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md708',1,'Minor Issues (Non-Blocking)'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md813',1,'Minor Issues Identified (Non-Blocking)']]],
  ['non_20interactive_44',['Auto-Approve Mode (Non-Interactive)',['../md_README.html#autotoc_md927',1,'']]],
  ['none_45',['Test Failures (None)',['../md_workshop__test__results.html#autotoc_md1468',1,'']]],
  ['normalize_5ftool_5fname_46',['normalize_tool_name',['../namespaceutils_1_1xml__tool__parser.html#acd18e34b8713011c876e3ae157a4fb6c',1,'utils::xml_tool_parser']]],
  ['not_20available_47',['Extended thinking not available',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md274',1,'']]],
  ['not_20available_20falling_20back_20to_20whitelist_20mode_48',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['not_20cooperating_49',['&quot;Agents not cooperating&quot;',['../md_QUICK__REFERENCE.html#autotoc_md857',1,'']]],
  ['not_20default_20in_20collab_20mode_50',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['not_20default_20in_20collab_20mode_20✅_51',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['not_20executing_20high_52',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['not_20handled_20✅_53',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['not_20sandbox_20mode_54',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['not_20supported_20✅_55',['Bug 1: XML Tag Formats Not Supported ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md196',1,'']]],
  ['not_20working_56',['not working',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md273',1,'Caching not working'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md276',1,'Files API not working']]],
  ['not_20yet_20implemented_57',['Future Features (Not Yet Implemented)',['../md_QUICK__REFERENCE.html#autotoc_md861',1,'']]],
  ['note_20on_20whistleblower_20feature_58',['Note on Whistleblower Feature',['../md_README.html#autotoc_md870',1,'']]],
  ['notes_59',['Notes',['../md_IMPROVEMENTS__README.html#autotoc_md561',1,'Architecture Notes'],['../md_REFACTORING__NOTES.html',1,'AXE.PY Refactoring Notes'],['../md__8collab__shared.html',1,'Collaborative Session Notes'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1135',1,'Implementation Notes'],['../md_MODELS__FINAL.html#autotoc_md625',1,'Notes'],['../md_MODELS__FINAL.html#autotoc_md632',1,'Notes'],['../md_MODELS__FINAL.html#autotoc_md638',1,'Notes'],['../md_MODELS__FINAL.html#autotoc_md645',1,'Notes'],['../md_MODELS__FINAL.html#autotoc_md651',1,'Notes'],['../md_tests_2MISSION.html#autotoc_md1338',1,'Notes']]],
  ['notes_20for_20agents_60',['Notes for Agents',['../md__8collab__env.html#autotoc_md11',1,'']]],
  ['now_20allowed_20bug_20fixed_20_3a_61',['✅ Now Allowed (Bug Fixed):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md31',1,'']]],
  ['now_20handled_20exclusively_20by_20axe_20py_20responseprocessor_62',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['now_20working_63',['Now Working',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md34',1,'Agents Now Working'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1132',1,'Commands Now Working']]]
];
