var searchData=
[
  ['b_3a_20file_20changes_20summary_0',['Appendix B: File Changes Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md834',1,'']]],
  ['back_20to_20whitelist_20mode_1',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['background_20monitor_20thread_2',['Background Monitor Thread',['../md_IMPROVEMENTS__FINAL.html#autotoc_md531',1,'']]],
  ['background_5fthink_3',['background_think',['../classcore_1_1multiprocess_1_1AgentWorkerProcess.html#acd76bd1ba490767b6cd053d02b609f64',1,'core::multiprocess::AgentWorkerProcess']]],
  ['backticks_20that_20may_20be_20included_20by_20accident_4',['backticks that may be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['backup_5fdir_5',['backup_dir',['../classaxe_1_1SharedWorkspace.html#a49f6696341ece335965eebfa767af646',1,'axe::SharedWorkspace']]],
  ['backup_5fext_6',['backup_ext',['../unlzexe_8c.html#a86abd9de8d139455a66ff49f843534cc',1,'unlzexe.c']]],
  ['backup_5ffile_7',['backup_file',['../classaxe_1_1SharedWorkspace.html#ab5e70300394328ef57e127c7dd59cace',1,'axe::SharedWorkspace']]],
  ['backward_20compatibility_8',['Backward Compatibility',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md35',1,'Backward Compatibility'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md86',1,'Backward Compatibility'],['../md_BUG__FIX__SUMMARY.html#autotoc_md206',1,'Backward Compatibility'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md239',1,'Backward Compatibility'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md268',1,'Backward Compatibility'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md353',1,'Backward Compatibility'],['../md_FIXES__SUMMARY.html#autotoc_md384',1,'Backward Compatibility'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md680',1,'Backward Compatibility'],['../md_REFACTORING__NOTES.html#autotoc_md1010',1,'Backward Compatibility'],['../md_SANDBOX.html#autotoc_md1035',1,'Backward Compatibility'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1075',1,'Backward Compatibility'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1527',1,'Backward Compatibility'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md331',1,'Example 3: Backward Compatibility']]],
  ['based_20error_20detection_20metrics_9',['Diff-Based Error Detection Metrics',['../md_IMPROVEMENTS__FINAL.html#autotoc_md488',1,'']]],
  ['based_20sleep_20system_10',['Permission-Based Sleep System',['../md_IMPROVEMENTS__FINAL.html#autotoc_md478',1,'']]],
  ['bash_20xml_20tags_20claude_20s_20favorite_11',['1. Bash XML Tags (Claude&apos;s Favorite)',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md689',1,'']]],
  ['basic_20agent_20conversations_12',['Basic Agent Conversations',['../md_README.html#autotoc_md894',1,'']]],
  ['basic_20usage_20automatic_13',['Basic Usage (Automatic)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1311',1,'']]],
  ['batch_20processing_14',['Batch Processing',['../md_README.html#autotoc_md928',1,'']]],
  ['be_20included_20by_20accident_15',['be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['before_16',['Before',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md174',1,'Before'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md182',1,'Before'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md186',1,'Before'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md236',1,'Before'],['../md_REFACTORING__NOTES.html#autotoc_md995',1,'Before']]],
  ['before_17',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['before_20after_20comparison_20of_20fixes_18',['Before/After Comparison of Fixes',['../md_BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['before_20axe_20yaml_19',['Before (axe.yaml)',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md178',1,'']]],
  ['before_20fix_20',['Before Fix',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'Example of Duplicate Execution (Before Fix)'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md221',1,'Impact Before Fix']]],
  ['before_20vs_20after_21',['Example - Before vs After',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md411',1,'']]],
  ['before_5fafter_5fcomparison_2emd_22',['BEFORE_AFTER_COMPARISON.md',['../BEFORE__AFTER__COMPARISON_8md.html',1,'']]],
  ['behavior_23',['Behavior',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1489',1,'Behavior'],['../md_QUICK__REFERENCE.html#autotoc_md854',1,'Encouraging Good Behavior'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md216',1,'Expected Behavior']]],
  ['being_20–_20no_20real_20bullying_24',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['benchmark_5facp_25',['benchmark_acp',['../namespacebenchmark__acp.html',1,'']]],
  ['benchmark_5facp_2epy_26',['benchmark_acp.py',['../benchmark__acp_8py.html',1,'']]],
  ['benchmark_5fmessage_5fformats_27',['benchmark_message_formats',['../namespacebenchmark__acp.html#aeda14e93f5d44e64563223f33d6aa911',1,'benchmark_acp']]],
  ['benchmarks_28',['Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1346',1,'Chisel - Symbolic Execution Benchmarks'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md769',1,'Document 2: Performance Benchmarks'],['../md_workshop__benchmarks.html#autotoc_md1355',1,'Hammer - Live Instrumentation Benchmarks'],['../md_workshop__test__results.html#autotoc_md1461',1,'Performance Benchmarks'],['../md_workshop__benchmarks.html#autotoc_md1352',1,'Plane - Source/Sink Enumeration Benchmarks'],['../md_workshop__benchmarks.html#autotoc_md1349',1,'Saw - Taint Analysis Benchmarks'],['../md_workshop__benchmarks.html',1,'Workshop Tools Benchmarks']]],
  ['benefits_29',['Benefits',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md261',1,'Benefits'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md346',1,'Benefits'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md593',1,'Benefits'],['../md_REFACTORING__NOTES.html#autotoc_md1017',1,'Benefits'],['../md_README.html#autotoc_md942',1,'Expected Benefits'],['../md_README.html#autotoc_md949',1,'Expected Benefits'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1072',1,'Security Benefits']]],
  ['best_20practices_30',['Best Practices',['../md_IMPROVEMENTS__FINAL.html#autotoc_md510',1,'Best Practices'],['../md_skills_2build.html#autotoc_md1180',1,'Best Practices'],['../md_skills_2python__agent__expert.html#autotoc_md1280',1,'Best Practices'],['../md_skills_2reverse__engineering__expert.html#autotoc_md1285',1,'Best Practices'],['../md_skills_2x86__assembly__expert.html#autotoc_md1290',1,'Best Practices'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1496',1,'Best Practices'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md92',1,'Security &amp;amp; Best Practices']]],
  ['best_20practices_20applied_31',['Best Practices Applied',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md94',1,'']]],
  ['best_20practices_20for_20security_20audits_32',['Best Practices for Security Audits',['../md_skills_2claude__build.html#autotoc_md1240',1,'']]],
  ['beta_33',['4. Files API (Beta)',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md262',1,'']]],
  ['beta_20optional_20✅_34',['4. Files API (Beta, Optional) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md77',1,'']]],
  ['beta_5fheader_35',['beta_header',['../classcore_1_1anthropic__features_1_1FilesAPIManager.html#ac2db3a4abfa989d97523aaab42e86381',1,'core::anthropic_features::FilesAPIManager']]],
  ['binary_20analysis_20performance_36',['Binary Analysis Performance',['../md_workshop__benchmarks.html#autotoc_md1347',1,'']]],
  ['bitarray_37',['bitArray',['../structGetNextBit__Data.html#a10e18692595f6810acd13784cfa0bb38',1,'GetNextBit_Data']]],
  ['bitsread_38',['bitsRead',['../structGetNextBit__Data.html#a8bbe6c1e02bb05cd57ae1e3f566d7fee',1,'GetNextBit_Data']]],
  ['bitstream_39',['bitstream',['../structbitstream.html',1,'']]],
  ['bittree_40',['BitTree',['../depklite_8c.html#ad98e9dc2ce8ddf0c8769a7e50f25261c',1,'depklite.c']]],
  ['bittree1_41',['bitTree1',['../depklite_8c.html#a7d31bc962170c70724f77bc2fecb5d85',1,'depklite.c']]],
  ['bittree2_42',['bitTree2',['../depklite_8c.html#ab4a11370c4c4d675400ca218d0835d24',1,'depklite.c']]],
  ['bittree_5fget_43',['BitTree_get',['../depklite_8c.html#a1a918d28cd72b0a8e04d0b697f8e0742',1,'depklite.c']]],
  ['blacklist_44',['Example 2: Restricted Sandbox with Blacklist',['../md_SANDBOX.html#autotoc_md1038',1,'']]],
  ['block_45',['Process each block',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['block_20absolute_20path_20fix_20implementation_20summary_46',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['block_20access_20denied_47',['Issue 1: READ Block Access Denied',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md173',1,'']]],
  ['block_20access_20denied_20✅_48',['Issue 1: READ Block Access Denied ✅',['../md_FIXES__SUMMARY.html#autotoc_md363',1,'']]],
  ['block_20as_20a_20single_20command_49',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['block_20contains_20a_20heredoc_50',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['block_20format_51',['Block Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md684',1,'Example 2: Code Block Format'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1480',1,'WRITE Block Format']]],
  ['block_20functionality_20user_20guide_52',['WRITE Block Functionality - User Guide',['../md_WRITE__BLOCKS__GUIDE.html',1,'']]],
  ['block_20in_20order_53',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['block_20parser_54',['Code Block Parser',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1495',1,'']]],
  ['block_20sanitization_55',['block sanitization',['../md_FIXES__SUMMARY.html#autotoc_md370',1,'READ block sanitization'],['../md_FIXES__SUMMARY.html#autotoc_md371',1,'WRITE block sanitization']]],
  ['block_20syntax_56',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['block_20syntax_20✅_57',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['blocked_20security_20maintained_20_3a_58',['✅ Still Blocked (Security Maintained):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md29',1,'']]],
  ['blocking_59',['Blocking',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md708',1,'Minor Issues (Non-Blocking)'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md813',1,'Minor Issues Identified (Non-Blocking)']]],
  ['blocks_60',['Blocks',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md690',1,'2. Shell Code Blocks'],['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md691',1,'3. AXE Native Blocks'],['../md_IMPLEMENTATION__SUMMARY.html',1,'Implementation Summary: GPT-5 Fix &amp; WRITE Blocks'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1486',1,'Integration with Other Blocks']]],
  ['blocks_61',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['blocks_20not_20executing_20high_62',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['blue_63',['BLUE',['../classutils_1_1formatting_1_1Colors.html#af738b04013b31547b1494e357c886dea',1,'utils::formatting::Colors']]],
  ['bold_64',['BOLD',['../classutils_1_1formatting_1_1Colors.html#adf2edf0a85163f14eec0c93530154afd',1,'utils::formatting::Colors']]],
  ['bonus_20xp_20calculation_65',['✅ VALIDATED - Bonus XP Calculation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md761',1,'']]],
  ['bool_20lines_201410_201458_66',['5. &lt;span class=&quot;tt&quot;&gt;_needs_shell(cmd: str) -&amp;gt; bool&lt;/span&gt; (Lines 1410-1458)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1116',1,'']]],
  ['boot_5fflow_5freconstruction_67',['boot_flow_reconstruction',['../md_skills_2boot__flow__reconstruction.html',1,'']]],
  ['boot_5fflow_5freconstruction_2emd_68',['boot_flow_reconstruction.md',['../boot__flow__reconstruction_8md.html',1,'']]],
  ['both_20present_3a_20combine_20with_20newline_20e_20g_20cat_20eof_69',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['boundaries_70',['Security Boundaries',['../md_SANDBOX.html#autotoc_md1040',1,'']]],
  ['break_20activities_71',['Break Activities',['../md_IMPROVEMENTS__FINAL.html#autotoc_md501',1,'']]],
  ['break_20system_72',['Break System',['../md_IMPROVEMENTS__FINAL.html#autotoc_md498',1,'']]],
  ['break_20system_20✅_73',['Phase 9: Break System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md552',1,'']]],
  ['break_20triggers_74',['Break Triggers',['../md_IMPROVEMENTS__FINAL.html#autotoc_md499',1,'']]],
  ['break_5fqueue_75',['break_queue',['../classmanagers_1_1break__system_1_1BreakSystem.html#a742fa40e98d637ef41f516c3fbe10598',1,'managers::break_system::BreakSystem']]],
  ['break_5fsystem_76',['break_system',['../classaxe_1_1CollaborativeSession.html#aa0e3798df96749e8f367dbde2ac247a9',1,'axe::CollaborativeSession']]],
  ['break_5fsystem_2epy_77',['break_system.py',['../break__system_8py.html',1,'']]],
  ['breakage_78',['Existing tests (verify no breakage)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1522',1,'']]],
  ['breakdown_79',['Module Breakdown',['../md_REFACTORING__NOTES.html#autotoc_md1016',1,'']]],
  ['breaking_20changes_80',['Breaking Changes',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1314',1,'']]],
  ['breaksystem_81',['BreakSystem',['../classmanagers_1_1break__system_1_1BreakSystem.html',1,'managers::break_system']]],
  ['broadcast_5fcontext_5fupdate_82',['broadcast_context_update',['../classcore_1_1multiprocess_1_1MultiAgentCoordinator.html#a7b433e0205bfead8ea415279a93c953d',1,'core::multiprocess::MultiAgentCoordinator']]],
  ['bubblewrap_20limitations_83',['Bubblewrap Limitations',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1080',1,'']]],
  ['bubblewrap_20not_20available_20falling_20back_20to_20whitelist_20mode_84',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['bubblewrap_20sandbox_20implementation_20summary_85',['Bubblewrap Sandbox Implementation - Summary',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['bubblewrap_20sandbox_20security_20model_86',['Bubblewrap Sandbox Security Model',['../md_SANDBOX.html',1,'']]],
  ['buf_87',['buf',['../structbitstream.html#a1425fc46c3f51db6a8c2a2c9cd78ae60',1,'bitstream::buf'],['../structmemstream.html#a52889670e096ed245354920a0b53c18c',1,'memstream::buf']]],
  ['bug_20✅_88',['Bug 4: Double Execution Bug ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['bug_201_3a_20duplicate_20command_20execution_20❌_20→_20✅_89',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md310',1,'']]],
  ['bug_201_3a_20false_20task_20complete_20detection_20✅_90',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1320',1,'']]],
  ['bug_201_3a_20xml_20tag_20formats_20not_20supported_20✅_91',['Bug 1: XML Tag Formats Not Supported ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md196',1,'']]],
  ['bug_202_3a_20active_20agents_20counter_20✅_92',['Bug 2: Active Agents Counter ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1325',1,'']]],
  ['bug_202_3a_20spawned_20agents_20never_20get_20turns_20✅_93',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['bug_203_3a_20token_20limit_20errors_20413_20not_20handled_20✅_94',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['bug_204_3a_20double_20execution_20bug_20✅_95',['Bug 4: Double Execution Bug ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['bug_20fix_20summary_20multi_20agent_20collaboration_20issues_96',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_BUG__FIX__SUMMARY.html',1,'']]],
  ['bug_20fixed_20_3a_97',['✅ Now Allowed (Bug Fixed):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md31',1,'']]],
  ['bug_20fixes_98',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['bug_5ffix_5fsummary_2emd_99',['BUG_FIX_SUMMARY.md',['../BUG__FIX__SUMMARY_8md.html',1,'']]],
  ['bugs_100',['Fix Summary: AXE Session Termination Bugs',['../md_TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['bugs_20fixed_101',['Bugs Fixed',['../md_BUG__FIX__SUMMARY.html#autotoc_md195',1,'']]],
  ['build_102',['Build',['../md_skills_2claude__build.html#autotoc_md1254',1,'Pattern 1: Hardening Flags (Silent Build)'],['../md_skills_2claude__build.html#autotoc_md1229',1,'Phase 1: Initial Silent Build']]],
  ['build_20analysis_20expanded_103',['Build Analysis (EXPANDED!)',['../md_README.html#autotoc_md905',1,'']]],
  ['build_20analyzer_20dependency_20helper_20✅_104',['5. Build Analyzer Dependency Helper ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md427',1,'']]],
  ['build_20analyzer_20helper_105',['Build Analyzer Helper',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md447',1,'']]],
  ['build_20approach_106',['Default Build Approach',['../md_AGENTS.html#autotoc_md58',1,'']]],
  ['build_20guidelines_107',['Build Guidelines',['../md_AGENTS.html#autotoc_md57',1,'']]],
  ['build_20guidelines_20content_108',['2. BUILD GUIDELINES Content',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1145',1,'']]],
  ['build_20guidelines_20for_20all_20agents_109',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'']]],
  ['build_20instructions_110',['Build Instructions',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1340',1,'']]],
  ['build_20issue_20debugging_111',['2. Build Issue Debugging',['../md_README.html#autotoc_md954',1,'']]],
  ['build_20md_209_204kb_112',['skills/build.md (9.4KB)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1147',1,'']]],
  ['build_20patterns_113',['Common Security Build Patterns',['../md_skills_2claude__build.html#autotoc_md1253',1,'']]],
  ['build_20quietly_114',['Clean and build quietly',['../md_skills_2build.html#autotoc_md1195',1,'']]],
  ['build_20silently_115',['Build silently',['../md_skills_2build.html#autotoc_md1193',1,'Build silently'],['../md_skills_2claude__build.html#autotoc_md1231',1,'Build silently']]],
  ['build_20skill_116',['Claude Security-Focused Build Skill',['../md_skills_2claude__build.html',1,'']]],
  ['build_20system_20detection_117',['build_analyzer - Build System Detection',['../md_README.html#autotoc_md944',1,'']]],
  ['build_20systems_118',['Build Systems',['../md_skills_2claude__build.html#autotoc_md1211',1,'Core Build Systems'],['../md_README.html#autotoc_md947',1,'Detected Build Systems'],['../md_skills_2build.html#autotoc_md1169',1,'Supported Build Systems']]],
  ['build_20toolchain_119',['Build Toolchain',['../md__8collab__env.html#autotoc_md3',1,'']]],
  ['build_2emd_120',['build.md',['../build_8md.html',1,'']]],
  ['build_5fanalyzer_20build_20system_20detection_121',['build_analyzer - Build System Detection',['../md_README.html#autotoc_md944',1,'']]],
  ['build_5fanalyzer_2epy_122',['build_analyzer.py',['../build__analyzer_8py.html',1,'']]],
  ['build_5fanalyzer_5fscript_123',['build_analyzer_script',['../classtest__analysis__tools_1_1TestBuildAnalyzerIntegration.html#a0943cdf65b4dcc218c6f169a1f15cdf8',1,'test_analysis_tools::TestBuildAnalyzerIntegration']]],
  ['build_5fbwrap_5fcommand_124',['build_bwrap_command',['../classcore_1_1sandbox_1_1SandboxManager.html#ac935b8aa94fa41939daa96a1866d21aa',1,'core::sandbox::SandboxManager']]],
  ['build_5ffile_5fpatterns_125',['BUILD_FILE_PATTERNS',['../namespacetools_1_1build__analyzer.html#a0beb87e8946fe4d22292034221391224',1,'tools::build_analyzer']]],
  ['build_5fstatus_126',['build_status',['../classaxe_1_1SharedWorkspace.html#a8cca1c9f37d3e77bf7f0046b59658c55',1,'axe::SharedWorkspace']]],
  ['build_5ftools_127',['BUILD_TOOLS',['../classaxe_1_1ResponseProcessor.html#aa83336c1074c8362720e9b8a637115e2',1,'axe::ResponseProcessor']]],
  ['builderror_128',['BuildError',['../classmanagers_1_1shared__build__status_1_1BuildError.html',1,'managers::shared_build_status']]],
  ['building_129',['Building',['../md_README.html#autotoc_md918',1,'']]],
  ['building_20c_20project_130',['Example 1: GPT Building C++ Project',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1157',1,'']]],
  ['builds_131',['Builds',['../md_skills_2claude__build.html#autotoc_md1210',1,'Silent Security Builds'],['../md_skills_2build.html#autotoc_md1167',1,'Why Silent Builds?']]],
  ['builds_20feature_20implementation_20summary_132',['Silent Builds Feature - Implementation Summary',['../md_SILENT__BUILDS__IMPLEMENTATION.html',1,'']]],
  ['builds_20skill_133',['Silent Builds Skill',['../md_skills_2build.html',1,'']]],
  ['buildstatus_134',['BuildStatus',['../classmanagers_1_1shared__build__status_1_1BuildStatus.html',1,'managers::shared_build_status']]],
  ['bullying_135',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['but_20not_20sandbox_20mode_136',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['by_20accident_137',['by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['by_20axe_20py_20responseprocessor_138',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['by_20default_139',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md1189',1,'']]],
  ['by_20design_140',['Limitations (By Design)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md814',1,'']]],
  ['by_20design_141',['What Sandbox Doesn&apos;t Protect (by design)',['../md_SANDBOX.html#autotoc_md1042',1,'']]],
  ['by_20line_20as_20before_142',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['byte_143',['BYTE',['../unlzexe_8c.html#aae9749d96e15ccb4f482dd5f55d98f9b',1,'unlzexe.c']]],
  ['byteindex_144',['byteIndex',['../structGetNextByte__Data.html#a0081d1f9b11654e1097820b74de5309f',1,'GetNextByte_Data']]]
];
