var searchData=
[
  ['b_0',['B',['../md_TODO.html#autotoc_md2205',1,'B'],['../md_TODO.html#autotoc_md2222',1,'B']]],
  ['b_3a_20file_20changes_20summary_1',['Appendix B: File Changes Summary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md956',1,'']]],
  ['b_3a_20using_20mkpyenv_20tool_2',['Option B: Using mkpyenv tool',['../md_README.html#autotoc_md2001',1,'']]],
  ['baars_201988_3',['Global Workspace (Baars, 1988)',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1349',1,'']]],
  ['back_20to_20unrestricted_20mode_4',['&quot;bubblewrap not available, falling back to unrestricted mode&quot;',['../md_docs_2features_2sandbox.html#autotoc_md1270',1,'']]],
  ['background_5',['Background',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1516',1,'1. Ollama Running in Background'],['../md_docs_2global-workspace.html#autotoc_md1302',1,'Theory Background'],['../md_docs_2privilege__mapping.html#autotoc_md1473',1,'Theory Background']]],
  ['background_20monitor_20thread_6',['Background Monitor Thread',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md468',1,'']]],
  ['background_5fthink_7',['background_think',['../classcore_1_1multiprocess_1_1AgentWorkerProcess.html#acd76bd1ba490767b6cd053d02b609f64',1,'core::multiprocess::AgentWorkerProcess']]],
  ['backticks_20that_20may_20be_20included_20by_20accident_8',['backticks that may be included by accident',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md191',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['backup_5fdir_9',['backup_dir',['../classaxe_1_1SharedWorkspace.html#a49f6696341ece335965eebfa767af646',1,'axe::SharedWorkspace']]],
  ['backup_5fext_10',['backup_ext',['../unlzexe_8c.html#a86abd9de8d139455a66ff49f843534cc',1,'unlzexe.c']]],
  ['backup_5ffile_11',['backup_file',['../classaxe_1_1SharedWorkspace.html#ab5e70300394328ef57e127c7dd59cace',1,'axe::SharedWorkspace']]],
  ['backward_20compatibility_12',['Backward Compatibility',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md135',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md156',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md208',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md241',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md290',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md321',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md598',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md629',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md662',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md812',1,'Backward Compatibility'],['../md_docs_2features_2anthropic-features.html#autotoc_md1150',1,'Backward Compatibility'],['../md_docs_2features_2configuration.html#autotoc_md1178',1,'Backward Compatibility'],['../md_docs_2features_2parsers.html#autotoc_md1233',1,'Backward Compatibility'],['../md_docs_2features_2sandbox.html#autotoc_md1254',1,'Backward Compatibility'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1929',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md268',1,'Example 3: Backward Compatibility']]],
  ['backwards_20compatibility_13',['Backwards Compatibility',['../md_docs_2codex-implementation.html#autotoc_md1020',1,'']]],
  ['balance_14',['Small Models (1-2GB) - Good Balance',['../md_docs_2ollama-guide.html#autotoc_md1439',1,'']]],
  ['base_5fdir_15',['base_dir',['../classcore_1_1config_1_1Config.html#a29db4b11fbfdf6949ad8fd0040f937ad',1,'core::config::Config']]],
  ['based_20error_20detection_20metrics_16',['Diff-Based Error Detection Metrics',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md425',1,'']]],
  ['based_20round_20robin_20multi_20agent_17',['🔄 Turn-based Round-Robin Multi-Agent',['../md_TODO.html#autotoc_md2242',1,'']]],
  ['based_20sleep_20system_18',['Permission-Based Sleep System',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md415',1,'']]],
  ['bash_20example_19',['Bash Example',['../md_docs_2socket__interface.html#autotoc_md1645',1,'']]],
  ['bash_20xml_20tags_20claude_20s_20favorite_20',['Bash XML Tags Claude s Favorite',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md607',1,'1. Bash XML Tags (Claude&apos;s Favorite)'],['../md_docs_2features_2parsers.html#autotoc_md1215',1,'1. Bash XML Tags (Claude&apos;s Favorite)']]],
  ['basic_20commands_21',['Basic Commands',['../md_README.html#autotoc_md2010',1,'']]],
  ['basic_20setup_22',['Basic Setup',['../md_docs_2subsumption__architecture.html#autotoc_md1710',1,'']]],
  ['basic_20usage_20automatic_23',['Basic Usage (Automatic)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md761',1,'']]],
  ['basic_20usage_20examples_24',['Basic Usage Examples',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1842',1,'']]],
  ['batch_20mode_25',['Batch Mode',['../md_README.html#autotoc_md2025',1,'']]],
  ['batch_20mode_20c_20task_26',['Section 1 – Batch Mode (&lt;span class=&quot;tt&quot;&gt;-c &quot;@agent task&quot;&lt;/span&gt;)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1385',1,'']]],
  ['batch_20mode_20test_27',['Batch Mode Test',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1456',1,'']]],
  ['batch_20mode_20test_20results_28',['Ollama Batch Mode Test Results',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html',1,'']]],
  ['be_20included_20by_20accident_29',['be included by accident',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md191',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['before_30',['Before',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md176',1,'Before'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md184',1,'Before'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Before'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md238',1,'Before'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md614',1,'Before']]],
  ['before_31',['No heredoc - process line by line as before',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md259',1,'']]],
  ['before_20after_20comparison_20of_20fixes_32',['Before/After Comparison of Fixes',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['before_20axe_20yaml_33',['Before (axe.yaml)',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md180',1,'']]],
  ['before_20fix_34',['Before Fix',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md250',1,'Example of Duplicate Execution (Before Fix)'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md223',1,'Impact Before Fix']]],
  ['before_20vs_20after_35',['Example - Before vs After',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md348',1,'']]],
  ['before_5fafter_5fcomparison_2emd_36',['BEFORE_AFTER_COMPARISON.md',['../BEFORE__AFTER__COMPARISON_8md.html',1,'']]],
  ['behavior_37',['Behavior',['../md_docs_2features_2write-blocks.html#autotoc_md1289',1,'Behavior'],['../md_docs_2references_2quick-reference.html#autotoc_md1579',1,'Encouraging Good Behavior'],['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md218',1,'Expected Behavior']]],
  ['behaviour_20—_20xp_20rewards_20for_20good_20output_38',['4. Supervision Behaviour — XP Rewards for Good Output',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md988',1,'']]],
  ['being_20–_20no_20real_20bullying_39',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md463',1,'']]],
  ['benchmark_5facp_40',['benchmark_acp',['../namespacebenchmark__acp.html',1,'']]],
  ['benchmark_5facp_2epy_41',['benchmark_acp.py',['../benchmark__acp_8py.html',1,'']]],
  ['benchmark_5fmessage_5fformats_42',['benchmark_message_formats',['../namespacebenchmark__acp.html#aeda14e93f5d44e64563223f33d6aa911',1,'benchmark_acp']]],
  ['benchmarks_43',['Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1756',1,'Chisel - Symbolic Execution Benchmarks'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md891',1,'Document 2: Performance Benchmarks'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1765',1,'Hammer - Live Instrumentation Benchmarks'],['../md_docs_2workshop_2test-results.html#autotoc_md1896',1,'Performance Benchmarks'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1762',1,'Plane - Source/Sink Enumeration Benchmarks'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1759',1,'Saw - Taint Analysis Benchmarks'],['../md_docs_2workshop_2benchmarks.html',1,'Workshop Tools Benchmarks']]],
  ['benchmarks_20md_44',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2benchmarks.html&quot;&gt;benchmarks.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1836',1,'']]],
  ['benchmarks_20md_20benchmarks_20md_45',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2benchmarks.html&quot;&gt;benchmarks.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1836',1,'']]],
  ['benchmarks_2emd_46',['benchmarks.md',['../benchmarks_8md.html',1,'']]],
  ['benefits_47',['Benefits',['../md_docs_2subsumption__architecture.html#autotoc_md1726',1,'Architecture Benefits'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md283',1,'Benefits'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md522',1,'Benefits'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md636',1,'Benefits'],['../md_docs_2features_2anthropic-features.html#autotoc_md1143',1,'Benefits'],['../md_docs_2features_2configuration.html#autotoc_md1182',1,'Benefits'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1555',1,'Benefits'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md659',1,'Security Benefits']]],
  ['best_20for_20ci_20minimal_20resources_48',['Tiny Models (&amp;lt; 1GB) - Best for CI/Minimal Resources',['../md_docs_2ollama-guide.html#autotoc_md1438',1,'']]],
  ['best_20practices_49',['Best Practices',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md447',1,'Best Practices'],['../md_docs_2features_2configuration.html#autotoc_md1191',1,'Best Practices'],['../md_docs_2features_2write-blocks.html#autotoc_md1296',1,'Best Practices'],['../md_docs_2global-workspace.html#autotoc_md1320',1,'Best Practices'],['../md_docs_2xp__voting.html#autotoc_md1955',1,'Best Practices'],['../md_skills_2build.html#autotoc_md2071',1,'Best Practices'],['../md_skills_2python__agent__expert.html#autotoc_md2171',1,'Best Practices'],['../md_skills_2reverse__engineering__expert.html#autotoc_md2176',1,'Best Practices'],['../md_skills_2x86__assembly__expert.html#autotoc_md2181',1,'Best Practices'],['../md_llm__prep_2project__guidance.html#autotoc_md1973',1,'C/C++ Best Practices'],['../md_docs_2features_2configuration.html#autotoc_md1177',1,'Override Best Practices'],['../md_llm__prep_2project__guidance.html#autotoc_md1974',1,'Python Best Practices'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md162',1,'Security &amp;amp; Best Practices']]],
  ['best_20practices_20applied_50',['Best Practices Applied',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md164',1,'']]],
  ['best_20practices_20for_20security_20audits_51',['Best Practices for Security Audits',['../md_skills_2claude__build.html#autotoc_md2131',1,'']]],
  ['best_20quality_52',['Large Models (&amp;gt; 30GB) - Best Quality',['../md_docs_2ollama-guide.html#autotoc_md1441',1,'']]],
  ['beta_53',['4. Files API (Beta)',['../md_docs_2features_2anthropic-features.html#autotoc_md1144',1,'']]],
  ['beta_20optional_20✅_54',['4. Files API (Beta, Optional) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md147',1,'']]],
  ['beta_5fheader_55',['beta_header',['../classcore_1_1anthropic__features_1_1FilesAPIManager.html#ac2db3a4abfa989d97523aaab42e86381',1,'core::anthropic_features::FilesAPIManager']]],
  ['bin_20and_20path_56',['&lt;span class=&quot;tt&quot;&gt;/tmp/bin&lt;/span&gt; and PATH',['../md_docs_2TESTING.html#autotoc_md1737',1,'']]],
  ['binary_20analysis_20performance_57',['Binary Analysis Performance',['../md_docs_2workshop_2benchmarks.html#autotoc_md1757',1,'']]],
  ['binary_20fixtures_20dos_5fbinaries_58',['DOS binary fixtures (&lt;span class=&quot;tt&quot;&gt;dos_binaries/&lt;/span&gt;)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2187',1,'']]],
  ['bitarray_59',['bitArray',['../structGetNextBit__Data.html#a10e18692595f6810acd13784cfa0bb38',1,'GetNextBit_Data']]],
  ['bitsread_60',['bitsRead',['../structGetNextBit__Data.html#a8bbe6c1e02bb05cd57ae1e3f566d7fee',1,'GetNextBit_Data']]],
  ['bitstream_61',['bitstream',['../structbitstream.html',1,'']]],
  ['bittree_62',['BitTree',['../depklite_8c.html#ad98e9dc2ce8ddf0c8769a7e50f25261c',1,'depklite.c']]],
  ['bittree1_63',['bitTree1',['../depklite_8c.html#a7d31bc962170c70724f77bc2fecb5d85',1,'depklite.c']]],
  ['bittree2_64',['bitTree2',['../depklite_8c.html#ab4a11370c4c4d675400ca218d0835d24',1,'depklite.c']]],
  ['bittree_5fget_65',['BitTree_get',['../depklite_8c.html#a1a918d28cd72b0a8e04d0b697f8e0742',1,'depklite.c']]],
  ['blacklist_66',['Example 2: Restricted Sandbox with Blacklist',['../md_docs_2features_2sandbox.html#autotoc_md1257',1,'']]],
  ['blacklist_67',['blacklist',['../classcore_1_1tool__runner_1_1ToolRunner.html#ac172290159510f6f2c00b763b2ed7276',1,'core::tool_runner::ToolRunner']]],
  ['block_68',['Process each block',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'']]],
  ['block_20absolute_20path_20fix_20implementation_20summary_69',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['block_20access_20denied_70',['Issue 1: READ Block Access Denied',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md175',1,'']]],
  ['block_20access_20denied_20✅_71',['Issue 1: READ Block Access Denied ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md300',1,'']]],
  ['block_20as_20a_20single_20command_72',['If so, treat the whole block as a single command',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md258',1,'']]],
  ['block_20contains_20a_20heredoc_73',['Check if the entire block contains a heredoc',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md257',1,'']]],
  ['block_20format_74',['Block Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md602',1,'Example 2: Code Block Format'],['../md_docs_2features_2write-blocks.html#autotoc_md1280',1,'WRITE Block Format']]],
  ['block_20functionality_20user_20guide_75',['WRITE Block Functionality - User Guide',['../md_docs_2features_2write-blocks.html',1,'']]],
  ['block_20in_20order_76',['Execute each block in order',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md399',1,'']]],
  ['block_20parser_77',['Code Block Parser',['../md_docs_2features_2write-blocks.html#autotoc_md1295',1,'']]],
  ['block_20sanitization_78',['block sanitization',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md307',1,'READ block sanitization'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md308',1,'WRITE block sanitization']]],
  ['block_20syntax_79',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['block_20syntax_20✅_80',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md306',1,'']]],
  ['blocked_20security_20maintained_20_3a_81',['✅ Still Blocked (Security Maintained):',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md129',1,'']]],
  ['blocking_82',['Blocking',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md830',1,'Minor Issues (Non-Blocking)'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md935',1,'Minor Issues Identified (Non-Blocking)']]],
  ['blocks_83',['Blocks',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md608',1,'2. Shell Code Blocks'],['../md_docs_2features_2parsers.html#autotoc_md1216',1,'2. Shell Code Blocks'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md609',1,'3. AXE Native Blocks'],['../md_docs_2features_2parsers.html#autotoc_md1217',1,'3. AXE Native Blocks'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html',1,'Implementation Summary: GPT-5 Fix &amp; WRITE Blocks'],['../md_docs_2features_2write-blocks.html#autotoc_md1286',1,'Integration with Other Blocks']]],
  ['blocks_84',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md252',1,'']]],
  ['blocks_20md_85',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2write-blocks.html&quot;&gt;write-blocks.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1237',1,'']]],
  ['blocks_20md_20write_20blocks_20md_86',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2write-blocks.html&quot;&gt;write-blocks.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1237',1,'']]],
  ['blocks_20not_20executing_20high_87',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md398',1,'']]],
  ['blue_88',['BLUE',['../classutils_1_1formatting_1_1Colors.html#af738b04013b31547b1494e357c886dea',1,'utils::formatting::Colors']]],
  ['bold_89',['BOLD',['../classutils_1_1formatting_1_1Colors.html#adf2edf0a85163f14eec0c93530154afd',1,'utils::formatting::Colors']]],
  ['bonus_20xp_20calculation_90',['✅ VALIDATED - Bonus XP Calculation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md883',1,'']]],
  ['bool_20lines_201410_201458_91',['5. &lt;span class=&quot;tt&quot;&gt;_needs_shell(cmd: str) -&amp;gt; bool&lt;/span&gt; (Lines 1410-1458)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md692',1,'']]],
  ['boot_5fflow_5freconstruction_92',['boot_flow_reconstruction',['../md_skills_2boot__flow__reconstruction.html',1,'']]],
  ['boot_5fflow_5freconstruction_2emd_93',['boot_flow_reconstruction.md',['../boot__flow__reconstruction_8md.html',1,'']]],
  ['both_20present_3a_20combine_20with_20newline_20e_20g_20cat_20eof_94',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md328',1,'']]],
  ['boundaries_95',['Security Boundaries',['../md_docs_2features_2sandbox.html#autotoc_md1259',1,'']]],
  ['break_20activities_96',['Break Activities',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md438',1,'']]],
  ['break_20system_97',['Break System',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md435',1,'']]],
  ['break_20system_20✅_98',['Phase 9: Break System ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md489',1,'']]],
  ['break_20triggers_99',['Break Triggers',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md436',1,'']]],
  ['break_5fqueue_100',['break_queue',['../classmanagers_1_1break__system_1_1BreakSystem.html#a742fa40e98d637ef41f516c3fbe10598',1,'managers::break_system::BreakSystem']]],
  ['break_5fsystem_101',['break_system',['../classaxe_1_1CollaborativeSession.html#aa0e3798df96749e8f367dbde2ac247a9',1,'axe::CollaborativeSession']]],
  ['break_5fsystem_2epy_102',['break_system.py',['../break__system_8py.html',1,'']]],
  ['breakage_103',['Existing tests (verify no breakage)',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md807',1,'']]],
  ['breakdown_104',['Module Breakdown',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md635',1,'']]],
  ['breaking_20changes_105',['Breaking Changes',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md764',1,'Breaking Changes'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1552',1,'Breaking Changes']]],
  ['breaksystem_106',['BreakSystem',['../classmanagers_1_1break__system_1_1BreakSystem.html',1,'managers::break_system']]],
  ['broadcast_107',['Resolution Broadcast',['../md_docs_2conflict__resolution__examples.html#autotoc_md1060',1,'']]],
  ['broadcast_108',['broadcast',['../classcore_1_1global__workspace_1_1GlobalWorkspace.html#abbe9a85d0b127fa1591f9043431538b0',1,'core::global_workspace::GlobalWorkspace']]],
  ['broadcast_20agent_5falias_20agent_5flevel_20category_20message_109',['&lt;span class=&quot;tt&quot;&gt;broadcast(agent_alias, agent_level, category, message, ...)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1307',1,'']]],
  ['broadcast_20categories_110',['Broadcast Categories',['../md_docs_2global-workspace.html#autotoc_md1304',1,'Broadcast Categories'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1336',1,'Broadcast Categories']]],
  ['broadcast_20limits_111',['Broadcast Limits',['../md_docs_2global-workspace.html#autotoc_md1319',1,'']]],
  ['broadcast_20system_112',['Broadcast System',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1330',1,'']]],
  ['broadcast_5fcontext_5fupdate_113',['broadcast_context_update',['../classcore_1_1multiprocess_1_1MultiAgentCoordinator.html#a7b433e0205bfead8ea415279a93c953d',1,'core::multiprocess::MultiAgentCoordinator']]],
  ['broadcast_5fid_20agent_5falias_20comment_20none_114',['&lt;span class=&quot;tt&quot;&gt;acknowledge(broadcast_id, agent_alias, comment=None)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1308',1,'']]],
  ['broadcast_5findexes_115',['BROADCAST_INDEXES',['../namespacedatabase_1_1schema.html#a3dd97b2c018f7fcf593c379aba2e7558',1,'database::schema']]],
  ['broadcast_5ftable_116',['BROADCAST_TABLE',['../namespacedatabase_1_1schema.html#a22ae54e3c7cb234bff838293340f14a5',1,'database::schema']]],
  ['broadcasting_20global_20workspace_117',['1. Broadcasting (Global Workspace)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1031',1,'']]],
  ['broadcasts_118',['Broadcasts',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md990',1,'5. Automation — Periodic Summary Broadcasts'],['../md_docs_2conflict__resolution__examples.html#autotoc_md1054',1,'Broadcasts'],['../md_docs_2conflict__resolution__examples.html#autotoc_md1063',1,'Broadcasts']]],
  ['brooks_201986_119',['Brooks 1986',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1085',1,'PR #54: Subsumption Architecture (Brooks 1986)'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1350',1,'Subsumption Architecture (Brooks, 1986)']]],
  ['bubblewrap_20command_20generation_120',['Bubblewrap Command Generation',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1927',1,'']]],
  ['bubblewrap_20limitations_121',['Bubblewrap Limitations',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md667',1,'']]],
  ['bubblewrap_20not_20available_20falling_20back_20to_20unrestricted_20mode_122',['&quot;bubblewrap not available, falling back to unrestricted mode&quot;',['../md_docs_2features_2sandbox.html#autotoc_md1270',1,'']]],
  ['bubblewrap_20ollama_123',['Manual Testing (Requires bubblewrap + ollama)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1925',1,'']]],
  ['bubblewrap_20sandbox_20implementation_20summary_124',['Bubblewrap Sandbox Implementation - Summary',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['bubblewrap_20sandbox_20security_20model_125',['Bubblewrap Sandbox Security Model',['../md_docs_2features_2sandbox.html',1,'']]],
  ['buf_126',['buf',['../structbitstream.html#a1425fc46c3f51db6a8c2a2c9cd78ae60',1,'bitstream::buf'],['../structmemstream.html#a52889670e096ed245354920a0b53c18c',1,'memstream::buf']]],
  ['bug_127',['Note on Workspace Bug',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1103',1,'']]],
  ['bug_128',['⚠️ COM disassembly limitation (known bug)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2191',1,'']]],
  ['bug_20✅_129',['Bug 4: Double Execution Bug ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md204',1,'']]],
  ['bug_201_3a_20duplicate_20command_20execution_20❌_20→_20✅_130',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md247',1,'']]],
  ['bug_201_3a_20false_20task_20complete_20detection_20✅_131',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md770',1,'']]],
  ['bug_201_3a_20xml_20tag_20formats_20not_20supported_20✅_132',['Bug 1: XML Tag Formats Not Supported ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['bug_202_3a_20active_20agents_20counter_20✅_133',['Bug 2: Active Agents Counter ✅',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md775',1,'']]],
  ['bug_202_3a_20spawned_20agents_20never_20get_20turns_20✅_134',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['bug_203_3a_20token_20limit_20errors_20413_20not_20handled_20✅_135',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['bug_204_3a_20double_20execution_20bug_20✅_136',['Bug 4: Double Execution Bug ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md204',1,'']]],
  ['bug_20fix_20and_20multiple_20workspace_20support_137',['Workspace Path Bug Fix and Multiple Workspace Support',['../md_docs_2WORKSPACE__FIX.html',1,'']]],
  ['bug_20fix_20summary_20multi_20agent_20collaboration_20issues_138',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html',1,'']]],
  ['bug_20fixed_20_3a_139',['✅ Now Allowed (Bug Fixed):',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md131',1,'']]],
  ['bug_20fixes_140',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['bug_5ffix_5fsummary_2emd_141',['BUG_FIX_SUMMARY.md',['../BUG__FIX__SUMMARY_8md.html',1,'']]],
  ['bugs_142',['Fix Summary: AXE Session Termination Bugs',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['bugs_20fixed_143',['Bugs Fixed',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md197',1,'']]],
  ['build_144',['Build',['../md_skills_2claude__build.html#autotoc_md2145',1,'Pattern 1: Hardening Flags (Silent Build)'],['../md_skills_2claude__build.html#autotoc_md2120',1,'Phase 1: Initial Silent Build']]],
  ['build_20analyzer_20dependency_20helper_20✅_145',['5. Build Analyzer Dependency Helper ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md364',1,'']]],
  ['build_20analyzer_20helper_146',['Build Analyzer Helper',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md384',1,'']]],
  ['build_20approach_147',['Default Build Approach',['../md_AGENTS.html#autotoc_md35',1,'']]],
  ['build_20guidelines_148',['Build Guidelines',['../md_AGENTS.html#autotoc_md34',1,'']]],
  ['build_20guidelines_20content_149',['2. BUILD GUIDELINES Content',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md721',1,'']]],
  ['build_20guidelines_20for_20all_20agents_150',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md718',1,'']]],
  ['build_20instructions_151',['Build Instructions',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md2254',1,'']]],
  ['build_20md_209_204kb_152',['skills/build.md (9.4KB)',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md723',1,'']]],
  ['build_20patches_20versioned_20under_20scripts_20patches_20dosbox_20staging_153',['dosbox-staging build patches (versioned under &lt;span class=&quot;tt&quot;&gt;scripts/patches/dosbox-staging/&lt;/span&gt;)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2195',1,'']]],
  ['build_20patterns_154',['Common Security Build Patterns',['../md_skills_2claude__build.html#autotoc_md2144',1,'']]],
  ['build_20quietly_155',['Clean and build quietly',['../md_skills_2build.html#autotoc_md2086',1,'']]],
  ['build_20silently_156',['Build silently',['../md_skills_2build.html#autotoc_md2084',1,'Build silently'],['../md_skills_2claude__build.html#autotoc_md2122',1,'Build silently']]],
  ['build_20skill_157',['Claude Security-Focused Build Skill',['../md_skills_2claude__build.html',1,'']]],
  ['build_20systems_158',['Build Systems',['../md_skills_2claude__build.html#autotoc_md2102',1,'Core Build Systems'],['../md_skills_2build.html#autotoc_md2060',1,'Supported Build Systems']]],
  ['build_20toolchain_159',['Build Toolchain',['../md__8collab__env.html#autotoc_md3',1,'']]],
  ['build_2emd_160',['build.md',['../build_8md.html',1,'']]],
  ['build_5fanalyzer_161',['build_analyzer',['../md_README.html#autotoc_md2040',1,'']]],
  ['build_5fanalyzer_2epy_162',['build_analyzer.py',['../build__analyzer_8py.html',1,'']]],
  ['build_5fanalyzer_5fscript_163',['build_analyzer_script',['../classtest__analysis__tools_1_1TestBuildAnalyzerIntegration.html#a0943cdf65b4dcc218c6f169a1f15cdf8',1,'test_analysis_tools::TestBuildAnalyzerIntegration']]],
  ['build_5fbwrap_5fcommand_164',['build_bwrap_command',['../classcore_1_1sandbox_1_1SandboxManager.html#ac935b8aa94fa41939daa96a1866d21aa',1,'core::sandbox::SandboxManager']]],
  ['build_5ffile_5fpatterns_165',['BUILD_FILE_PATTERNS',['../namespacetools_1_1build__analyzer.html#a0beb87e8946fe4d22292034221391224',1,'tools::build_analyzer']]],
  ['build_5fstatus_166',['build_status',['../classaxe_1_1SharedWorkspace.html#a8cca1c9f37d3e77bf7f0046b59658c55',1,'axe::SharedWorkspace']]],
  ['build_5ftools_167',['BUILD_TOOLS',['../classaxe_1_1ResponseProcessor.html#aa83336c1074c8362720e9b8a637115e2',1,'axe::ResponseProcessor']]],
  ['builderror_168',['BuildError',['../classmanagers_1_1shared__build__status_1_1BuildError.html',1,'managers::shared_build_status']]],
  ['building_20c_20project_169',['Example 1: GPT Building C++ Project',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md733',1,'']]],
  ['building_20dosbox_20staging_170',['Building dosbox-staging',['../md_docs_2TESTING.html#autotoc_md1738',1,'']]],
  ['building_20dumpexe_171',['Building dumpexe',['../md_docs_2TESTING.html#autotoc_md1739',1,'']]],
  ['builds_172',['Builds',['../md_skills_2claude__build.html#autotoc_md2101',1,'Silent Security Builds'],['../md_skills_2build.html#autotoc_md2058',1,'Why Silent Builds?']]],
  ['builds_20feature_20implementation_20summary_173',['Silent Builds Feature - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html',1,'']]],
  ['builds_20skill_174',['Silent Builds Skill',['../md_skills_2build.html',1,'']]],
  ['buildstatus_175',['BuildStatus',['../classmanagers_1_1shared__build__status_1_1BuildStatus.html',1,'managers::shared_build_status']]],
  ['built_20in_20cognitive_20architecture_176',['🧠 Built-in Cognitive Architecture',['../md_README.html#autotoc_md1995',1,'']]],
  ['bullying_177',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md463',1,'']]],
  ['but_20not_20sandbox_20mode_178',['Commands work in unrestricted mode but not sandbox mode',['../md_docs_2features_2sandbox.html#autotoc_md1272',1,'']]],
  ['bwrap_20command_20test_179',['Bwrap Command Test',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1427',1,'']]],
  ['by_20accident_180',['by accident',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md191',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['by_20axe_20py_20responseprocessor_181',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md253',1,'']]],
  ['by_20default_182',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md2080',1,'']]],
  ['by_20design_183',['Limitations (By Design)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md936',1,'']]],
  ['by_20design_184',['What Sandbox Doesn&apos;t Protect (by design)',['../md_docs_2features_2sandbox.html#autotoc_md1261',1,'']]],
  ['by_20line_20as_20before_185',['No heredoc - process line by line as before',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md259',1,'']]],
  ['byte_186',['BYTE',['../unlzexe_8c.html#aae9749d96e15ccb4f482dd5f55d98f9b',1,'unlzexe.c']]],
  ['byteindex_187',['byteIndex',['../structGetNextByte__Data.html#a0081d1f9b11654e1097820b74de5309f',1,'GetNextByte_Data']]]
];
