var searchData=
[
  ['e_0',['E',['../md_TODO.html#autotoc_md2208',1,'E'],['../md_TODO.html#autotoc_md2225',1,'E']]],
  ['e_20g_20cat_20eof_1',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md328',1,'']]],
  ['e_5fcblp_2',['e_cblp',['../structdos__header.html#a180329371c3c5509f05d4294d4266a53',1,'dos_header']]],
  ['e_5fcp_3',['e_cp',['../structdos__header.html#a55e887cd9cb9be3d67c2c4325a092873',1,'dos_header']]],
  ['e_5fcparhdr_4',['e_cparhdr',['../structdos__header.html#af94cfd88a7ec7235892b498f78647502',1,'dos_header']]],
  ['e_5fcrlc_5',['e_crlc',['../structdos__header.html#ab250b1bfedbf8ccb32aa46dab26726ae',1,'dos_header']]],
  ['e_5fcs_6',['e_cs',['../structdos__header.html#a83481d43e1af58d8cba1c51533b7d115',1,'dos_header']]],
  ['e_5fcsum_7',['e_csum',['../structdos__header.html#a54b3a79cb758a4dc44b1769c17e0ee0f',1,'dos_header']]],
  ['e_5fip_8',['e_ip',['../structdos__header.html#a2de4e696b5d56c68392c7c1fc0a4dd23',1,'dos_header']]],
  ['e_5flfarlc_9',['e_lfarlc',['../structdos__header.html#a1a7a97aa6d3f42ed56eacc5aa14d465f',1,'dos_header']]],
  ['e_5fmagic_10',['e_magic',['../structdos__header.html#aaea84e35472ecf5b61ccdf870156059f',1,'dos_header']]],
  ['e_5fmaxalloc_11',['e_maxalloc',['../structdos__header.html#a1ae043f12241c6bff9e1614277562d7e',1,'dos_header']]],
  ['e_5fminalloc_12',['e_minalloc',['../structdos__header.html#a5996f6524c7fa12d3d3a71016a9d546e',1,'dos_header']]],
  ['e_5fovno_13',['e_ovno',['../structdos__header.html#a19052ddf010264429cdb4d1afabdff0c',1,'dos_header']]],
  ['e_5fsp_14',['e_sp',['../structdos__header.html#afd49fa1a6618b22636a53b9d429b8bb3',1,'dos_header']]],
  ['e_5fss_15',['e_ss',['../structdos__header.html#a9135b825c12c08dc22d560a192a35b72',1,'dos_header']]],
  ['each_20block_16',['Process each block',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'']]],
  ['each_20block_20in_20order_17',['Execute each block in order',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md399',1,'']]],
  ['each_20level_18',['When to Use Each Level',['../md_docs_2codex-implementation.html#autotoc_md1009',1,'']]],
  ['edge_20case_20test_20suite_20test_5ftool_5frunner_5fedge_5fcases_20py_19',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md705',1,'']]],
  ['edge_20cases_20fixed_20',['Edge Cases Fixed',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md695',1,'']]],
  ['edge_20cases_20newly_20fixed_20_3a_21',['Edge Cases (newly fixed):',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md710',1,'']]],
  ['effectiveness_22',['Effectiveness',['../md_docs_2workshop_2benchmarks.html#autotoc_md1767',1,'Monitoring Effectiveness'],['../md_docs_2workshop_2test-results.html#autotoc_md1898',1,'Test Effectiveness']]],
  ['efficiency_20analysis_23',['Token Efficiency Analysis',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md757',1,'']]],
  ['efficiency_20comparison_24',['Tool Efficiency Comparison',['../md_docs_2workshop_2benchmarks.html#autotoc_md1769',1,'']]],
  ['effort_20levels_25',['Reasoning Effort Levels',['../md_docs_2codex-implementation.html#autotoc_md1007',1,'']]],
  ['effort_20parameter_26',['Reasoning Effort Parameter',['../md_docs_2codex-implementation.html#autotoc_md1006',1,'']]],
  ['eligible_20levels_2030_27',['Deputy Supervisor / Supervisor-Eligible (Levels 30+)',['../md_docs_2privilege__mapping.html#autotoc_md1485',1,'']]],
  ['emergency_20mailbox_28',['Emergency Mailbox',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md429',1,'']]],
  ['emergency_20mailbox_20✅_29',['Phase 8: Emergency Mailbox ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md488',1,'']]],
  ['emergency_20override_30',['Example 2: Emergency Override',['../md_docs_2subsumption__architecture.html#autotoc_md1723',1,'']]],
  ['emergency_5fmailbox_31',['emergency_mailbox',['../classaxe_1_1CollaborativeSession.html#a0dd9ab753e3e615c9ac6599ddd0b7858',1,'axe::CollaborativeSession']]],
  ['emergency_5fmailbox_2epy_32',['emergency_mailbox.py',['../emergency__mailbox_8py.html',1,'']]],
  ['emergency_5fmailbox_5fdir_33',['EMERGENCY_MAILBOX_DIR',['../namespacecore_1_1constants.html#a168da638d87daba5752732b52d9913e4',1,'core::constants']]],
  ['emergencymailbox_34',['EmergencyMailbox',['../classmanagers_1_1emergency__mailbox_1_1EmergencyMailbox.html',1,'managers::emergency_mailbox']]],
  ['enable_20in_20axe_20yaml_35',['Enable in axe.yaml',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md519',1,'']]],
  ['enable_20ollama_36',['Enable Ollama',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1559',1,'']]],
  ['enabled_37',['Use Cases Enabled',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md136',1,'']]],
  ['enabled_38',['enabled',['../classcore_1_1github__agent_1_1GitHubAgent.html#a168eb32e18fb2b942f219e047f178a5f',1,'core.github_agent.GitHubAgent.enabled'],['../classcore_1_1sandbox_1_1SandboxManager.html#a40c23ba39bac5884be01fc4b0a12d470',1,'core.sandbox.SandboxManager.enabled'],['../classutils_1_1rate__limiter_1_1RateLimiter.html#aef7fb7add502ec52347a9ec8f20b696c',1,'utils.rate_limiter.RateLimiter.enabled']]],
  ['enabling_20disabling_20privilege_20prompts_39',['Enabling/Disabling Privilege Prompts',['../md_docs_2privilege__mapping.html#autotoc_md1492',1,'']]],
  ['enabling_20sandbox_20mode_40',['Enabling Sandbox Mode',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md658',1,'Enabling Sandbox Mode'],['../md_docs_2features_2sandbox.html#autotoc_md1253',1,'Enabling Sandbox Mode']]],
  ['encouraging_20good_20behavior_41',['Encouraging Good Behavior',['../md_docs_2references_2quick-reference.html#autotoc_md1579',1,'']]],
  ['endpoints_20summary_42',['API Endpoints Summary',['../md_docs_2api-providers.html#autotoc_md111',1,'']]],
  ['engine_43',['Engine',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1777',1,'angr (Symbolic Execution Engine)'],['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1782',1,'sqlite3 (Database Engine)']]],
  ['engine_20✅_44',['AXE - Agent eXecution Engine ✅',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md192',1,'']]],
  ['engineering_45',['Reverse Engineering',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1845',1,'']]],
  ['engineering_20expert_46',['Reverse Engineering Expert',['../md_skills_2reverse__engineering__expert.html',1,'']]],
  ['engineering_20tools_47',['Reverse Engineering Tools',['../md__8collab__env.html#autotoc_md4',1,'']]],
  ['engineering_20workflow_20—_20dumpexe_20integration_48',['6. Reverse-Engineering Workflow — dumpexe Integration',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md992',1,'']]],
  ['engineering_20workflow_20notes_49',['Reverse-Engineering Workflow Notes',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md1000',1,'']]],
  ['enhanced_20documentation_50',['2. Enhanced Documentation',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md343',1,'']]],
  ['enhanced_20reasoning_20✅_51',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md145',1,'']]],
  ['enhanced_20user_20namespace_20detection_52',['1. Enhanced User Namespace Detection',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1417',1,'']]],
  ['enhancement_20implementation_20complete_20✅_53',['AXE Enhancement Implementation - Complete ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['enhancements_54',['Enhancements',['../md_ARCHITECTURE.html#autotoc_md57',1,'Future Enhancements'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md165',1,'Future Enhancements'],['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md210',1,'Future Enhancements'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md292',1,'Future Enhancements'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md677',1,'Future Enhancements'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md763',1,'Future Enhancements'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md797',1,'Future Enhancements'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1049',1,'Future Enhancements'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1112',1,'Future Enhancements'],['../md_docs_2features_2sandbox.html#autotoc_md1276',1,'Future Enhancements'],['../md_docs_2features_2write-blocks.html#autotoc_md1299',1,'Future Enhancements'],['../md_docs_2privilege__mapping.html#autotoc_md1494',1,'Future Enhancements'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1561',1,'Future Enhancements'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1635',1,'Future Enhancements'],['../md_docs_2socket__interface.html#autotoc_md1662',1,'Future Enhancements'],['../md_docs_2workshop_2security-audit.html#autotoc_md1880',1,'Future Enhancements'],['../md_docs_2workshop_2test-results.html#autotoc_md1910',1,'Future Enhancements'],['../md_docs_2xp__voting.html#autotoc_md1961',1,'Future Enhancements']]],
  ['entire_20block_20contains_20a_20heredoc_55',['Check if the entire block contains a heredoc',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md257',1,'']]],
  ['entry_56',['Entry',['../structEntry.html',1,'Entry'],['../classhello__world_1_1Entry.html',1,'hello_world.Entry']]],
  ['enumerate_5ffile_57',['enumerate_file',['../classworkshop_1_1plane_1_1PlaneEnumerator.html#a5b59f8b59266e8e020af58011ba17320',1,'workshop::plane::PlaneEnumerator']]],
  ['enumerate_5fproject_58',['enumerate_project',['../classworkshop_1_1plane_1_1PlaneEnumerator.html#ac3fcd149453031fc5c03323e9fedfde8',1,'workshop::plane::PlaneEnumerator']]],
  ['enumeratedsink_59',['EnumeratedSink',['../classworkshop_1_1plane_1_1EnumeratedSink.html',1,'workshop::plane']]],
  ['enumeratedsource_60',['EnumeratedSource',['../classworkshop_1_1plane_1_1EnumeratedSource.html',1,'workshop::plane']]],
  ['enumeration_61',['Enumeration',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md874',1,'✅ VALIDATED - Plane (Source/Sink Enumeration)'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1833',1,'&lt;b&gt;Plane&lt;/b&gt; (Source/Sink Enumeration)'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1814',1,'Plane - Source/Sink Enumeration']]],
  ['enumeration_20benchmarks_62',['Plane - Source/Sink Enumeration Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1762',1,'']]],
  ['enumeration_20coverage_63',['Enumeration Coverage',['../md_docs_2workshop_2benchmarks.html#autotoc_md1764',1,'']]],
  ['environment_64',['Environment',['../md_AGENTS.html#autotoc_md19',1,'Development Environment'],['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1512',1,'Environment'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1362',1,'Test Environment'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1381',1,'Test Environment'],['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1462',1,'Test Environment'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1755',1,'Test Environment'],['../md_docs_2workshop_2test-results.html#autotoc_md1884',1,'Test Environment'],['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1460',1,'Testing in Real Environment']]],
  ['environment_20detection_65',['4. Environment Detection',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md654',1,'']]],
  ['environment_20restrictions_66',['Environment Restrictions',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md666',1,'']]],
  ['environment_20setup_67',['Environment Setup',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md536',1,'']]],
  ['environment_20summary_68',['Environment Summary',['../md__8collab__env.html',1,'']]],
  ['environment_20validation_69',['Test Environment Validation',['../md_docs_2workshop_2test-results.html#autotoc_md1905',1,'']]],
  ['environment_20variable_70',['Environment Variable',['../md_docs_2api-providers.html#autotoc_md68',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md76',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md86',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md95',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md104',1,'Environment Variable']]],
  ['environment_20variables_20summary_71',['Environment Variables Summary',['../md_docs_2api-providers.html#autotoc_md110',1,'']]],
  ['environment_5fprobe_2epy_72',['environment_probe.py',['../environment__probe_8py.html',1,'']]],
  ['environment_5fprobe_5fconfig_73',['environment_probe_config',['../classcore_1_1session__preprocessor_1_1SessionPreprocessor.html#a176dab18fe842a0a09b8cb17c196ce96',1,'core::session_preprocessor::SessionPreprocessor']]],
  ['environmentprobe_74',['EnvironmentProbe',['../classcore_1_1environment__probe_1_1EnvironmentProbe.html',1,'core::environment_probe']]],
  ['environments_20tested_75',['Environments Tested',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1428',1,'']]],
  ['eof_76',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md328',1,'']]],
  ['error_77',['No Credits Error',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md580',1,'']]],
  ['error_20analysis_78',['Error Analysis',['../md_docs_2workshop_2test-results.html#autotoc_md1902',1,'']]],
  ['error_20critical_79',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md397',1,'']]],
  ['error_20detection_20metrics_80',['Diff-Based Error Detection Metrics',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md425',1,'']]],
  ['error_20fixed_20✓_81',['1. Anthropic SDK Error Fixed ✓',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md284',1,'']]],
  ['error_20handling_82',['Error Handling',['../md_docs_2features_2github-agent-integration.html#autotoc_md1209',1,'Error Handling'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1620',1,'Error Handling'],['../md_docs_2socket__interface.html#autotoc_md1652',1,'Error Handling']]],
  ['error_20handling_20robust_83',['Error Handling - ROBUST',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md917',1,'']]],
  ['error_20messages_84',['Issue #3: Information Disclosure in Error Messages',['../md_docs_2workshop_2security-audit.html#autotoc_md1861',1,'']]],
  ['error_20recovery_85',['Error Recovery',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1803',1,'Error Recovery'],['../md_docs_2workshop_2security-audit.html#autotoc_md1866',1,'Finding #2: Limited Error Recovery']]],
  ['error_3a_86',['&quot;Sandbox execution error: ...&quot;',['../md_docs_2features_2sandbox.html#autotoc_md1271',1,'']]],
  ['error_5fthreshold_5fpercent_87',['ERROR_THRESHOLD_PERCENT',['../namespacecore_1_1constants.html#aa4776b3cf6771f5921023c231d1fae6d',1,'core::constants']]],
  ['errors_88',['Errors',['../md_docs_2socket__interface.html#autotoc_md1653',1,'Common Errors'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md810',1,'Path Errors?'],['../md_docs_2features_2configuration.html#autotoc_md1170',1,'Validation Errors']]],
  ['errors_20413_20not_20handled_20✅_89',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['errors_20inside_20sandbox_90',['&quot;Permission denied&quot; errors inside sandbox',['../md_docs_2features_2sandbox.html#autotoc_md1273',1,'']]],
  ['escalate_20properly_91',['3. Chain of Command – Escalate Properly',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md464',1,'']]],
  ['escalate_5farbitration_92',['escalate_arbitration',['../classcore_1_1arbitration_1_1ArbitrationProtocol.html#aa390533e2d62429534b16732e86b5514',1,'core::arbitration::ArbitrationProtocol']]],
  ['escalation_93',['Example 4: Deadline Auto-Escalation',['../md_docs_2conflict__resolution__examples.html#autotoc_md1071',1,'']]],
  ['escalation_20due_20to_20complexity_94',['Example 3: Escalation Due to Complexity',['../md_docs_2conflict__resolution__examples.html#autotoc_md1066',1,'']]],
  ['essential_20commands_95',['Essential Commands',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1592',1,'']]],
  ['estimate_5fcost_96',['estimate_cost',['../namespaceutils_1_1token__stats.html#a54a42760c488a25025c244562ac9500b',1,'utils::token_stats']]],
  ['estimate_5ftoken_5fcount_97',['estimate_token_count',['../namespacetest__efficiency__analysis.html#a6fca3b5bf54437dbd2d9986142f1931c',1,'test_efficiency_analysis']]],
  ['estimate_5ftoken_5fsavings_98',['estimate_token_savings',['../namespaceutils_1_1context__optimizer.html#ac536fec2687fa7bfe77048815fcf5107',1,'utils::context_optimizer']]],
  ['estimate_5ftokens_99',['estimate_tokens',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#a805441baae1756d437100197a4485951',1,'core.anthropic_features.AnthropicFeatures.estimate_tokens()'],['../namespacebenchmark__acp.html#a0d2edd8caa4f70efabefa35938f79e35',1,'benchmark_acp.estimate_tokens()']]],
  ['estimatelength_100',['estimateLength',['../depklite_8c.html#a0ba3adf2d91169675b5f216a301d9da4',1,'depklite.c']]],
  ['estimates_101',['Estimates',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md730',1,'Token Savings Estimates'],['../md_skills_2build.html#autotoc_md2059',1,'Token Savings Estimates']]],
  ['estimates_20✅_102',['3. Token Counting (Precise Estimates) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md146',1,'']]],
  ['etc_20if_20tools_20expand_103',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md2162',1,'']]],
  ['evidence_104',['Testing Evidence',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1357',1,'']]],
  ['evidence_20from_20live_20testing_105',['Evidence from Live Testing',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md319',1,'']]],
  ['evidence_20of_20the_20problem_106',['Evidence of the Problem',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md119',1,'']]],
  ['example_107',['Example',['../md_docs_2socket__interface.html#autotoc_md1645',1,'Bash Example'],['../md_docs_2api-providers.html#autotoc_md88',1,'Chat-style cURL Example'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md657',1,'Configuration Example'],['../md_docs_2api-providers.html#autotoc_md69',1,'cURL Example'],['../md_docs_2api-providers.html#autotoc_md77',1,'cURL Example'],['../md_docs_2api-providers.html#autotoc_md87',1,'cURL Example'],['../md_docs_2api-providers.html#autotoc_md96',1,'cURL Example'],['../md_docs_2api-providers.html#autotoc_md105',1,'cURL Example'],['../md_AGENTS.html#autotoc_md28',1,'Example'],['../md_docs_2features_2anthropic-features.html#autotoc_md1138',1,'Example'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md575',1,'Model Communication Example'],['../md_docs_2api-providers.html#autotoc_md70',1,'Python Example'],['../md_docs_2api-providers.html#autotoc_md78',1,'Python Example'],['../md_docs_2api-providers.html#autotoc_md89',1,'Python Example'],['../md_docs_2socket__interface.html#autotoc_md1644',1,'Python Example'],['../md_skills_2claude__build.html#autotoc_md2119',1,'Security Audit Workflow Example'],['../md_docs_2features_2anthropic-features.html#autotoc_md1131',1,'Token Savings Example'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1628',1,'Usage Example'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1551',1,'Validation Example']]],
  ['example_201_3a_20c_20project_20with_20cmake_108',['Example 1: C++ Project with CMake',['../md_skills_2build.html#autotoc_md2082',1,'']]],
  ['example_201_3a_20claude_20s_20natural_20format_109',['Example 1: Claude&apos;s Natural Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md601',1,'']]],
  ['example_201_3a_20default_20sandbox_20mode_110',['Example 1: Default Sandbox Mode',['../md_docs_2features_2sandbox.html#autotoc_md1256',1,'']]],
  ['example_201_3a_20gpt_20building_20c_20project_111',['Example 1: GPT Building C++ Project',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md733',1,'']]],
  ['example_201_3a_20no_20duplicate_20execution_112',['Example 1: No Duplicate Execution',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md265',1,'']]],
  ['example_201_3a_20reading_20a_20file_20multiple_20ways_113',['Example 1: Reading a File (Multiple Ways)',['../md_docs_2features_2parsers.html#autotoc_md1230',1,'']]],
  ['example_201_3a_20security_20vulnerability_20disagreement_114',['Example 1: Security Vulnerability Disagreement',['../md_docs_2conflict__resolution__examples.html#autotoc_md1052',1,'']]],
  ['example_201_3a_20strategic_20planning_115',['Example 1: Strategic Planning',['../md_docs_2subsumption__architecture.html#autotoc_md1722',1,'']]],
  ['example_202_3a_20claude_20security_20audit_116',['Example 2: Claude Security Audit',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md734',1,'']]],
  ['example_202_3a_20code_20block_20format_117',['Example 2: Code Block Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md602',1,'']]],
  ['example_202_3a_20creating_20a_20file_118',['Example 2: Creating a File',['../md_docs_2features_2parsers.html#autotoc_md1231',1,'']]],
  ['example_202_3a_20emergency_20override_119',['Example 2: Emergency Override',['../md_docs_2subsumption__architecture.html#autotoc_md1723',1,'']]],
  ['example_202_3a_20heredoc_20preserved_120',['Example 2: Heredoc Preserved',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md266',1,'']]],
  ['example_202_3a_20java_20project_20with_20maven_121',['Example 2: Java Project with Maven',['../md_skills_2build.html#autotoc_md2085',1,'']]],
  ['example_202_3a_20refactoring_20approach_20conflict_122',['Example 2: Refactoring Approach Conflict',['../md_docs_2conflict__resolution__examples.html#autotoc_md1061',1,'']]],
  ['example_202_3a_20restricted_20sandbox_20with_20blacklist_123',['Example 2: Restricted Sandbox with Blacklist',['../md_docs_2features_2sandbox.html#autotoc_md1257',1,'']]],
  ['example_203_3a_20axe_20native_20format_124',['Example 3: AXE Native Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md603',1,'']]],
  ['example_203_3a_20backward_20compatibility_125',['Example 3: Backward Compatibility',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md268',1,'']]],
  ['example_203_3a_20escalation_20due_20to_20complexity_126',['Example 3: Escalation Due to Complexity',['../md_docs_2conflict__resolution__examples.html#autotoc_md1066',1,'']]],
  ['example_203_3a_20mixed_20operations_127',['Example 3: Mixed Operations',['../md_docs_2features_2parsers.html#autotoc_md1232',1,'']]],
  ['example_203_3a_20multi_20agent_20collaboration_128',['Example 3: Multi-Agent Collaboration',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md737',1,'']]],
  ['example_203_3a_20network_20isolated_20sandbox_129',['Example 3: Network-Isolated Sandbox',['../md_docs_2features_2sandbox.html#autotoc_md1258',1,'']]],
  ['example_203_3a_20python_20project_20with_20make_130',['Example 3: Python Project with Make',['../md_skills_2build.html#autotoc_md2088',1,'']]],
  ['example_204_3a_20deadline_20auto_20escalation_131',['Example 4: Deadline Auto-Escalation',['../md_docs_2conflict__resolution__examples.html#autotoc_md1071',1,'']]],
  ['example_204_3a_20multi_20agent_20collaboration_132',['Example 4: Multi-Agent Collaboration',['../md_skills_2build.html#autotoc_md2091',1,'']]],
  ['example_20before_20vs_20after_133',['Example - Before vs After',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md348',1,'']]],
  ['example_20images_134',['Vision Example (Images)',['../md_docs_2api-providers.html#autotoc_md79',1,'']]],
  ['example_20of_20duplicate_20execution_20before_20fix_135',['Example of Duplicate Execution (Before Fix)',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md250',1,'']]],
  ['example_20openai_20sdk_136',['Example OpenAI SDK',['../md_docs_2api-providers.html#autotoc_md97',1,'Python Example (OpenAI SDK)'],['../md_docs_2api-providers.html#autotoc_md106',1,'Python Example (OpenAI SDK)']]],
  ['example_20output_137',['Example Output',['../md_docs_2features_2anthropic-features.html#autotoc_md1133',1,'']]],
  ['example_20penalty_20scenario_138',['Example Penalty Scenario',['../md_docs_2conflict__resolution__examples.html#autotoc_md1077',1,'']]],
  ['example_20prompt_20output_139',['Example Prompt Output',['../md_docs_2privilege__mapping.html#autotoc_md1486',1,'']]],
  ['example_20session_140',['Example Session',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1037',1,'Example Session'],['../md_docs_2features_2github-agent-integration.html#autotoc_md1208',1,'Example Session']]],
  ['example_20skill_20template_141',['Example Skill Template',['../md_AGENTS.html#autotoc_md33',1,'']]],
  ['example_20startup_20output_142',['Example Startup Output',['../md_docs_2features_2configuration.html#autotoc_md1169',1,'']]],
  ['example_20usage_143',['Example Usage',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1337',1,'']]],
  ['example_20workflow_20savings_144',['Example Workflow Savings',['../md_docs_2features_2anthropic-features.html#autotoc_md1152',1,'']]],
  ['example_3a_20security_20audit_20workflow_145',['Example: Security Audit Workflow',['../md_docs_2global-workspace.html#autotoc_md1321',1,'']]],
  ['example_5fextended_5fthinking_146',['example_extended_thinking',['../namespaceanthropic__features__demo.html#ab2e39b6a9072090bfe008755bdfaf535',1,'anthropic_features_demo']]],
  ['example_5fprompt_5fcaching_147',['example_prompt_caching',['../namespaceanthropic__features__demo.html#a92085a1d8fb488ebc175f97bfdf9f610',1,'anthropic_features_demo']]],
  ['examples_148',['Examples',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1842',1,'Basic Usage Examples'],['../md_docs_2conflict__resolution__examples.html',1,'Conflict Resolution Examples'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md264',1,'Examples'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md451',1,'Examples'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md600',1,'Examples'],['../md_docs_2features_2parsers.html#autotoc_md1229',1,'Examples'],['../md_docs_2features_2write-blocks.html#autotoc_md1281',1,'Examples'],['../md_docs_2subsumption__architecture.html#autotoc_md1721',1,'Examples'],['../md_docs_2xp__voting.html#autotoc_md1940',1,'Examples'],['../md_README.html#autotoc_md2017',1,'Examples'],['../md_skills_2build.html#autotoc_md2081',1,'Examples'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md289',1,'Model Examples'],['../md_docs_2privilege__mapping__quickref.html#autotoc_md1500',1,'Quick Code Examples'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md493',1,'Usage Examples'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md573',1,'Usage Examples'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md732',1,'Usage Examples'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md760',1,'Usage Examples'],['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1242',1,'Usage Examples'],['../md_docs_2features_2sandbox.html#autotoc_md1255',1,'Usage Examples'],['../md_docs_2privilege__mapping.html#autotoc_md1487',1,'Usage Examples'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1556',1,'Usage Examples'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1920',1,'Usage Examples'],['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md2255',1,'Usage Examples']]],
  ['excellent_149',['Code Structure - EXCELLENT',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md916',1,'']]],
  ['exception_3a_20github_20models_150',['Exception: GitHub Models',['../md_docs_2features_2configuration.html#autotoc_md1174',1,'']]],
  ['exclude_5fdirs_151',['exclude_dirs',['../classtools_1_1minifier_1_1Minifier.html#a2a7936ca1c128718218998425616af4e',1,'tools::minifier::Minifier']]],
  ['exclusively_20by_20axe_20py_20responseprocessor_152',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md253',1,'']]],
  ['exe_20unpackers_153',['DOS EXE Unpackers',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md2253',1,'']]],
  ['exec_20blocks_154',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md252',1,'']]],
  ['exec_20run_20commands_155',['EXEC - Run Commands',['../md_docs_2features_2parsers.html#autotoc_md1225',1,'']]],
  ['exec_5flog_156',['exec_log',['../classcore_1_1tool__runner_1_1ToolRunner.html#acdd4a8cc75397bd8031234b497ff0091',1,'core::tool_runner::ToolRunner']]],
  ['execute_20each_20block_20in_20order_157',['Execute each block in order',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md399',1,'']]],
  ['execute_5fparsed_5fcall_158',['execute_parsed_call',['../namespaceutils_1_1xml__tool__parser.html#aa150ac2b37ac7c5d29a193a6b9331ada',1,'utils::xml_tool_parser']]],
  ['execute_5fpush_159',['execute_push',['../classcore_1_1github__agent_1_1GitHubAgent.html#a63c00b98acb12c898c52b54b98dcfade',1,'core::github_agent::GitHubAgent']]],
  ['executed_160',['Executed',['../md_docs_2workshop_2test-results.html#autotoc_md1886',1,'Test Files Executed'],['../md_docs_2workshop_2security-audit.html#autotoc_md1874',1,'Test Scenarios Executed']]],
  ['executing_20high_161',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md398',1,'']]],
  ['execution_162',['Execution',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md872',1,'✅ VALIDATED - Chisel (Symbolic Execution)'],['../md_docs_2features_2sandbox.html#autotoc_md1248',1,'1. Default-Allow Execution'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1830',1,'&lt;b&gt;Chisel&lt;/b&gt; (Symbolic Execution)'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1812',1,'Chisel - Symbolic Execution'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md265',1,'Example 1: No Duplicate Execution']]],
  ['execution_163',['to prevent duplicate execution',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md254',1,'']]],
  ['execution_20⚠️_20medium_164',['2. &lt;b&gt;Command Execution&lt;/b&gt; ⚠️ Medium',['../md_docs_2security.html#autotoc_md1603',1,'']]],
  ['execution_20❌_20→_20✅_165',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md247',1,'']]],
  ['execution_20and_20heredoc_20parsing_20bug_20fixes_166',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['execution_20before_20fix_167',['Example of Duplicate Execution (Before Fix)',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md250',1,'']]],
  ['execution_20benchmarks_168',['Chisel - Symbolic Execution Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1756',1,'']]],
  ['execution_20bug_20✅_169',['Bug 4: Double Execution Bug ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md204',1,'']]],
  ['execution_20engine_170',['angr (Symbolic Execution Engine)',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1777',1,'']]],
  ['execution_20engine_171',['eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['execution_20engine_20✅_172',['AXE - Agent eXecution Engine ✅',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md192',1,'']]],
  ['execution_20error_3a_173',['&quot;Sandbox execution error: ...&quot;',['../md_docs_2features_2sandbox.html#autotoc_md1271',1,'']]],
  ['execution_20fix_20implementation_20summary_174',['Heredoc Execution Fix - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['execution_20fix_20summary_175',['Heredoc Execution Fix Summary',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html',1,'']]],
  ['execution_20logs_176',['Appendix A: Test Execution Logs',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md953',1,'']]],
  ['execution_20order_177',['Execution Order',['../md_docs_2subsumption__architecture.html#autotoc_md1715',1,'']]],
  ['execution_20original_20version_20_3a_178',['Execution (original version):',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md351',1,'']]],
  ['execution_20results_179',['Workshop Tools Test Suite Execution Results',['../md_docs_2workshop_2test-results.html',1,'']]],
  ['execution_20summary_180',['Execution Summary',['../md_docs_2workshop_2test-results.html#autotoc_md1883',1,'Test Execution Summary'],['../md_docs_2workshop_2test-results.html#autotoc_md1894',1,'Test Execution Summary']]],
  ['executive_181',['EXECUTIVE',['../classcore_1_1subsumption__layer_1_1SubsumptionLayer.html#ab6cae0e3db775cb3d283ff26a861ae76',1,'core::subsumption_layer::SubsumptionLayer']]],
  ['executive_20summary_182',['Executive Summary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md867',1,'Executive Summary'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1344',1,'Executive Summary'],['../md_docs_2security.html#autotoc_md1599',1,'Executive Summary'],['../md_docs_2workshop_2security-audit.html#autotoc_md1853',1,'Executive Summary'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html',1,'PR #23 Workshop Dynamic Analysis Framework - Executive Summary']]],
  ['exepack_183',['Then EXEPACK',['../md_skills_2dos__packer__detector.html#autotoc_md2161',1,'']]],
  ['exepack_5fheader_184',['exepack_header',['../structexepack__header.html',1,'']]],
  ['exepack_5fsignature_185',['EXEPACK_SIGNATURE',['../unpack_8c.html#afa2e9a07eba95966b1bac5907b834905',1,'unpack.c']]],
  ['exepack_5fsize_186',['exepack_size',['../structexepack__header.html#a49e4cbeb3d505d9c0938e7b8ecdbe267',1,'exepack_header']]],
  ['exhaustion_20in_20chisel_20analysis_187',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_docs_2workshop_2security-audit.html#autotoc_md1859',1,'']]],
  ['existing_20code_188',['For Existing Code',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md641',1,'']]],
  ['existing_20tests_189',['Existing Tests',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md312',1,'Existing Tests'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md334',1,'Existing Tests']]],
  ['existing_20tests_20verify_20no_20breakage_190',['Existing tests (verify no breakage)',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md807',1,'']]],
  ['exists_191',['Only one present: use whichever exists',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md329',1,'']]],
  ['exists_20today_192',['What Exists Today',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1686',1,'']]],
  ['exit_193',['Exit',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md984',1,'2. Session Persistence — Autosave on Exit'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1369',1,'Test 7: Exit']]],
  ['expand_194',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md2162',1,'']]],
  ['expected_195',['Known Limitations (Expected)',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1378',1,'']]],
  ['expected_20behavior_196',['Expected Behavior',['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md218',1,'']]],
  ['experience_197',['User Experience',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1377',1,'']]],
  ['experience_20level_20system_20✅_198',['Phase 3: Experience &amp;amp; Level System ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md482',1,'']]],
  ['expert_199',['Expert',['../md_skills_2c__modernization__expert.html',1,'C Modernization Expert'],['../md_skills_2cpp__modernization__expert.html',1,'C++ Modernization Expert'],['../md_skills_2cpp__refactoring__expert.html',1,'C++ Refactoring Expert'],['../md_skills_2ida__pro__analysis__patterns.html',1,'IDA Pro / Decompiler Analysis Expert'],['../md_skills_2python__agent__expert.html',1,'Python Agent Expert'],['../md_skills_2reverse__engineering__expert.html',1,'Reverse Engineering Expert'],['../md_skills_2x86__assembly__expert.html',1,'x86 Assembly Analysis Expert']]],
  ['exponential_200',['Progression Curve (Hybrid Linear/Exponential)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md456',1,'']]],
  ['exported_20helper_20function_201',['4. Exported Helper Function',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md229',1,'']]],
  ['extend_20parse_5faxe_5fnative_5fblocks_20response_20commented_20out_202',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md255',1,'']]],
  ['extended_20thinking_203',['2. Extended Thinking',['../md_docs_2features_2anthropic-features.html#autotoc_md1134',1,'']]],
  ['extended_20thinking_20enhanced_20reasoning_20✅_204',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md145',1,'']]],
  ['extended_20thinking_20not_20available_205',['Extended thinking not available',['../md_docs_2features_2anthropic-features.html#autotoc_md1156',1,'']]],
  ['extensibility_206',['Extensibility',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md679',1,'']]],
  ['extensibility_20guide_207',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['extension_208',['5. Database Schema Extension',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1093',1,'']]],
  ['extension_20points_209',['Extension Points',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md167',1,'Extension Points'],['../md_ARCHITECTURE.html#autotoc_md51',1,'Key Extension Points']]],
  ['extensions_210',['Future Extensions',['../md_docs_2codex-implementation.html#autotoc_md1021',1,'']]],
  ['extensions_211',['extensions',['../classaxe_1_1ProjectContext.html#ac5c5832f33934d640b6b337a8c42e697',1,'axe::ProjectContext']]],
  ['extract_20functions_20✅_212',['Phase 2: Extract Functions ✅',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md623',1,'']]],
  ['extract_20large_20classes_213',['PR #2: Extract Large Classes',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md638',1,'']]],
  ['extract_20session_20management_214',['PR #3: Extract Session Management',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md639',1,'']]],
  ['extract_5fbuild_5ffiles_5fto_5fmemory_215',['extract_build_files_to_memory',['../namespacetools_1_1build__analyzer.html#aaca7acb4ee4ffc81aaadd176db622eeb',1,'tools::build_analyzer']]],
  ['extract_5fcritical_5fdirectives_216',['extract_critical_directives',['../classutils_1_1prompt__compressor_1_1PromptCompressor.html#a68496fd700eeaac8a761decfb9fbeffd',1,'utils::prompt_compressor::PromptCompressor']]]
];
