var searchData=
[
  ['facts_0',['Quick Facts',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md694',1,'']]],
  ['fail_1',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['failed_2',['FAILED',['../classmanagers_1_1shared__build__status_1_1BuildStatus.html#a2fba2526e184b3b9503b84b0ee35a074',1,'managers::shared_build_status::BuildStatus']]],
  ['failing_20from_20problem_20statement_20_3a_3',['Previously Failing (from problem statement):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1133',1,'']]],
  ['fails_4',['Command Fails?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1526',1,'']]],
  ['fails_5',['Token counting fails',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md275',1,'']]],
  ['failure_6',['FAILURE',['../unlzexe_8c.html#a6d58f9ac447476b4e084d7ca383f5183',1,'unlzexe.c']]],
  ['failure_7',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md1182',1,'']]],
  ['failures_20none_8',['Test Failures (None)',['../md_workshop__test__results.html#autotoc_md1468',1,'']]],
  ['fallback_20mechanisms_9',['Fallback Mechanisms',['../md_workshop__dependency__validation.html#autotoc_md1391',1,'']]],
  ['fallback_20signature_20quick_20check_20if_20all_20trials_20fail_10',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['falling_20back_20to_20whitelist_20mode_11',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['false_20task_20complete_20detection_20✅_12',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1320',1,'']]],
  ['favorite_13',['1. Bash XML Tags (Claude&apos;s Favorite)',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md689',1,'']]],
  ['feature_14',['Note on Whistleblower Feature',['../md_README.html#autotoc_md870',1,'']]],
  ['feature_20details_15',['Feature Details',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md442',1,'']]],
  ['feature_20implementation_20summary_16',['Silent Builds Feature - Implementation Summary',['../md_SILENT__BUILDS__IMPLEMENTATION.html',1,'']]],
  ['features_17',['Features',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md250',1,'Automatic Features'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md477',1,'Core Safety Features'],['../md_API__PROVIDERS.html#autotoc_md109',1,'Features'],['../md_API__PROVIDERS.html#autotoc_md117',1,'Features'],['../md_API__PROVIDERS.html#autotoc_md126',1,'Features'],['../md_API__PROVIDERS.html#autotoc_md136',1,'Features'],['../md_API__PROVIDERS.html#autotoc_md144',1,'Features'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md245',1,'Features'],['../md_README.html#autotoc_md869',1,'Features'],['../md_README.html#autotoc_md939',1,'Features'],['../md_README.html#autotoc_md945',1,'Features'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md585',1,'Key Features'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md672',1,'Key Features'],['../md_SANDBOX.html#autotoc_md1028',1,'Key Features'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1063',1,'Key Features'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md292',1,'Safety Features'],['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'Starting a Collaborative Session with New Features'],['../md_IMPROVEMENTS__README.html#autotoc_md568',1,'Summary of All Implemented Features']]],
  ['features_20⚠️_20medium_18',['5. &lt;b&gt;Collaboration Features&lt;/b&gt; ⚠️ Medium',['../md_SECURITY__REPORT.html#autotoc_md1105',1,'']]],
  ['features_20delivered_19',['Features Delivered',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md73',1,'']]],
  ['features_20implemented_20',['Features Implemented',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md422',1,'✅ All Features Implemented'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1293',1,'Key Features Implemented']]],
  ['features_20in_20axe_21',['Anthropic Claude-Specific Features in AXE',['../md_docs_2ANTHROPIC__FEATURES.html',1,'']]],
  ['features_20not_20yet_20implemented_22',['Future Features (Not Yet Implemented)',['../md_QUICK__REFERENCE.html#autotoc_md861',1,'']]],
  ['features_20phases_201_205_23',['Implemented Features (Phases 1-5)',['../md_IMPROVEMENTS__README.html#autotoc_md542',1,'']]],
  ['features_20phases_206_2010_24',['Implemented Features (Phases 6-10)',['../md_IMPROVEMENTS__README.html#autotoc_md548',1,'']]],
  ['feedback_25',['Rejection and Feedback',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md300',1,'']]],
  ['file_26',['File',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1482',1,'1. Simple Text File'],['../md_README.html#autotoc_md898',1,'Real-World Example: Reverse Engineering a WAD File']]],
  ['file_27',['file',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1507',1,'Configuration file'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md467',1,'Write file']]],
  ['file_201_3a_20unit_20tests_28',['Test File 1: Unit Tests',['../md_PR23__VALIDATION__REPORT.html#autotoc_md776',1,'']]],
  ['file_202_3a_20integration_20tests_29',['Test File 2: Integration Tests',['../md_PR23__VALIDATION__REPORT.html#autotoc_md777',1,'']]],
  ['file_20axe_20yaml_30',['Configuration File (axe.yaml)',['../md_README.html#autotoc_md883',1,'']]],
  ['file_20changes_20summary_31',['Appendix B: File Changes Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md834',1,'']]],
  ['file_20handling_20✅_20fixed_32',['1. &lt;b&gt;Path &amp;amp; File Handling&lt;/b&gt; ✅ Fixed',['../md_SECURITY__REPORT.html#autotoc_md1101',1,'']]],
  ['file_20in_20subdirectory_33',['3. File in Subdirectory',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1484',1,'']]],
  ['file_20modifications_34',['File Modifications',['../md_PR23__VALIDATION__REPORT.html#autotoc_md809',1,'']]],
  ['file_20naming_35',['File Naming',['../md_AGENTS.html#autotoc_md52',1,'']]],
  ['file_20size_36',['File Size',['../md_REFACTORING__NOTES.html#autotoc_md1015',1,'']]],
  ['file_20structure_37',['File Structure',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1308',1,'']]],
  ['file_5fpath_38',['file_path',['../classworkshop_1_1plane_1_1SourceSinkVisitor.html#a4007befb20677ad30cef1a8405aeb55c',1,'workshop::plane::SourceSinkVisitor']]],
  ['filename_39',['Validate filename',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md464',1,'']]],
  ['filename_3a_20strip_20trailing_20backticks_20that_20may_20be_20included_20by_20accident_40',['filename: strip trailing backticks that may be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['files_41',['Files',['../md_PR23__VALIDATION__REPORT.html#autotoc_md767',1,'✅ VALIDATED - Documentation Files'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md775',1,'✅ VALIDATED - Test Files'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1146',1,'3. Created Skills Directory and Files'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1296',1,'3. Domain-Specific Skill Files'],['../md_AGENTS.html#autotoc_md62',1,'Configuration Files'],['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md280',1,'Files'],['../md_README.html#autotoc_md941',1,'Generated Files'],['../md_SANDBOX.html#autotoc_md1047',1,'Key Files'],['../md_llm__prep_2codebase__overview.html#autotoc_md574',1,'LLM Context Files'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md835',1,'Modified Files'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1510',1,'Modified Files'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md836',1,'New Files'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1509',1,'New Files'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md26',1,'New Test Files'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md801',1,'PR Test Files'],['../md__8collab__shared.html#autotoc_md13',1,'Related Collaboration Files'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1153',1,'Skills Files'],['../md_README.html#autotoc_md896',1,'Working with Files']]],
  ['files_20api_20beta_42',['4. Files API (Beta)',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md262',1,'']]],
  ['files_20api_20beta_20optional_20✅_43',['4. Files API (Beta, Optional) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md77',1,'']]],
  ['files_20api_20not_20working_44',['Files API not working',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md276',1,'']]],
  ['files_20changed_45',['Files Changed',['../md_BUG__FIX__SUMMARY.html#autotoc_md207',1,'Files Changed'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md399',1,'Files Changed'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md679',1,'Files Changed'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1162',1,'Files Changed']]],
  ['files_20created_46',['Files Created',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md580',1,'Files Created'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1061',1,'Files Created']]],
  ['files_20created_205_47',['Files Created (5)',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md79',1,'']]],
  ['files_20executed_48',['Test Files Executed',['../md_workshop__test__results.html#autotoc_md1451',1,'']]],
  ['files_20in_20one_20response_49',['4. Multiple Files in One Response',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1485',1,'']]],
  ['files_20modified_50',['Files Modified',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md38',1,'Files Modified'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md215',1,'Files Modified'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md241',1,'Files Modified'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md333',1,'Files Modified'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md357',1,'Files Modified'],['../md_FIXES__SUMMARY.html#autotoc_md380',1,'Files Modified'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md416',1,'Files Modified'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md581',1,'Files Modified'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1062',1,'Files Modified'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1136',1,'Files Modified'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1332',1,'Files Modified']]],
  ['files_20modified_205_51',['Files Modified (5)',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md80',1,'']]],
  ['files_20modified_20added_52',['Files Modified/Added',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1508',1,'']]],
  ['files_5fapi_53',['files_api',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#a0f1c522045ca0ebe8d34603478b6d6c1',1,'core::anthropic_features::AnthropicFeatures']]],
  ['filesapimanager_54',['FilesAPIManager',['../classcore_1_1anthropic__features_1_1FilesAPIManager.html',1,'core::anthropic_features']]],
  ['filesystem_20access_20control_55',['Filesystem Access Control',['../md_SANDBOX.html#autotoc_md1031',1,'3. Filesystem Access Control'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1066',1,'3. Filesystem Access Control']]],
  ['find_5fentry_5fpoints_56',['find_entry_points',['../md_skills_2find__entry__points.html',1,'']]],
  ['find_5fentry_5fpoints_2emd_57',['find_entry_points.md',['../find__entry__points_8md.html',1,'']]],
  ['find_5fproject_5froots_58',['find_project_roots',['../namespacetools_1_1build__analyzer.html#ae46450f0cf52ad119daa6c8d0abc38da',1,'tools::build_analyzer']]],
  ['finding_201_3a_20missing_20input_20size_20validation_59',['Finding #1: Missing Input Size Validation',['../md_workshop__security__audit.html#autotoc_md1430',1,'']]],
  ['finding_202_3a_20limited_20error_20recovery_60',['Finding #2: Limited Error Recovery',['../md_workshop__security__audit.html#autotoc_md1431',1,'']]],
  ['finding_203_3a_20no_20rate_20limiting_61',['Finding #3: No Rate Limiting',['../md_workshop__security__audit.html#autotoc_md1432',1,'']]],
  ['finding_204_3a_20dependency_20version_20pinning_62',['Finding #4: Dependency Version Pinning',['../md_workshop__security__audit.html#autotoc_md1433',1,'']]],
  ['finding_205_3a_20logging_20of_20sensitive_20data_63',['Finding #5: Logging of Sensitive Data',['../md_workshop__security__audit.html#autotoc_md1434',1,'']]],
  ['findings_64',['Findings',['../md_workshop__security__audit.html#autotoc_md1421',1,'Detailed Findings'],['../md_workshop__security__audit.html#autotoc_md1429',1,'Informational Findings']]],
  ['findings_65',['findings',['../md_skills_2claude__build.html#autotoc_md1244',1,'Good: Only high-severity findings'],['../md_skills_2claude__build.html#autotoc_md1224',1,'Review findings']]],
  ['findings_20post_20fix_66',['Key Findings (Post-Fix)',['../md_SECURITY__REPORT.html#autotoc_md1100',1,'']]],
  ['findings_20summary_67',['Findings Summary',['../md_workshop__security__audit.html#autotoc_md1420',1,'']]],
  ['firmware_5fbinwalk_5fscan_68',['firmware_binwalk_scan',['../md_skills_2firmware__binwalk__scan.html',1,'']]],
  ['firmware_5fbinwalk_5fscan_2emd_69',['firmware_binwalk_scan.md',['../firmware__binwalk__scan_8md.html',1,'']]],
  ['firmware_5fentropy_5fanalyzer_70',['firmware_entropy_analyzer',['../md_skills_2firmware__entropy__analyzer.html',1,'']]],
  ['firmware_5fentropy_5fanalyzer_2emd_71',['firmware_entropy_analyzer.md',['../firmware__entropy__analyzer_8md.html',1,'']]],
  ['firmware_5fextract_5fcomponents_72',['firmware_extract_components',['../md_skills_2firmware__extract__components.html',1,'']]],
  ['firmware_5fextract_5fcomponents_2emd_73',['firmware_extract_components.md',['../firmware__extract__components_8md.html',1,'']]],
  ['firmware_5fheader_5fidentify_74',['firmware_header_identify',['../md_skills_2firmware__header__identify.html',1,'']]],
  ['firmware_5fheader_5fidentify_2emd_75',['firmware_header_identify.md',['../firmware__header__identify_8md.html',1,'']]],
  ['first_76',['First',['../md_skills_2build.html#autotoc_md1181',1,'1. Always Use Silent Flags First'],['../md_REFACTORING__NOTES.html#autotoc_md1009',1,'Why These Modules First?']]],
  ['first_20–_20the_20project_20task_20is_20sacred_77',['1. Mission First – The Project / Task Is Sacred',['../md_IMPROVEMENTS__FINAL.html#autotoc_md525',1,'']]],
  ['first_20very_20common_78',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md1268',1,'']]],
  ['fix_79',['Fix',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'Example of Duplicate Execution (Before Fix)'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md235',1,'Impact After Fix'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md221',1,'Impact Before Fix'],['../md_SECURITY__REPORT.html#autotoc_md1100',1,'Key Findings (Post-Fix)']]],
  ['fix_20implementation_20summary_80',['Fix Implementation Summary',['../md_DATABASE__LOCATION__FIX__SUMMARY.html',1,'Database Location Fix - Implementation Summary'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'Heredoc Execution Fix - Implementation Summary'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'WRITE Block Absolute Path Fix - Implementation Summary']]],
  ['fix_20summary_81',['Fix Summary',['../md_FIXES__SUMMARY.html',1,'AXE Multiple Issues Fix Summary'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html',1,'Collaborative Mode Tool Syntax Fix - Summary'],['../md_HEREDOC__EXECUTION__FIX.html',1,'Heredoc Execution Fix Summary']]],
  ['fix_20summary_20multi_20agent_20collaboration_20issues_82',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_BUG__FIX__SUMMARY.html',1,'']]],
  ['fix_20summary_3a_20axe_20session_20termination_20bugs_83',['Fix Summary: AXE Session Termination Bugs',['../md_TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['fix_20write_20blocks_84',['Implementation Summary: GPT-5 Fix &amp;amp; WRITE Blocks',['../md_IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['fixed_85',['Fixed',['../md_SECURITY__REPORT.html#autotoc_md1101',1,'1. &lt;b&gt;Path &amp;amp; File Handling&lt;/b&gt; ✅ Fixed'],['../md_SECURITY__REPORT.html#autotoc_md1104',1,'4. &lt;b&gt;Database/Storage&lt;/b&gt; ✅ Fixed'],['../md_BUG__FIX__SUMMARY.html#autotoc_md195',1,'Bugs Fixed'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1119',1,'Edge Cases Fixed'],['../md_FIXES__SUMMARY.html#autotoc_md362',1,'Issues Fixed']]],
  ['fixed_86',['fixed',['../classmanagers_1_1shared__build__status_1_1BuildError.html#abb86dcc69bd6635d2178fd313c37a1d1',1,'managers::shared_build_status::BuildError']]],
  ['fixed_20✓_87',['Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md347',1,'1. Anthropic SDK Error Fixed ✓'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md348',1,'2. Token Truncation Fixed ✓'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md349',1,'3. Wasted Capacity Fixed ✓']]],
  ['fixed_20_3a_88',['✅ Now Allowed (Bug Fixed):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md31',1,'']]],
  ['fixed_20_3a_89',['Edge Cases (newly fixed):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1134',1,'']]],
  ['fixes_90',['Fixes',['../md_BEFORE__AFTER__COMPARISON.html',1,'Before/After Comparison of Fixes'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'Duplicate Execution and Heredoc Parsing Bug Fixes']]],
  ['fixes_5fsummary_2emd_91',['FIXES_SUMMARY.md',['../FIXES__SUMMARY_8md.html',1,'']]],
  ['flags_92',['4. Combine Multiple Silent Flags',['../md_skills_2build.html#autotoc_md1184',1,'']]],
  ['flags_93',['flags',['../md_skills_2build.html#autotoc_md1192',1,'Configure with quiet flags'],['../md_skills_2claude__build.html#autotoc_md1230',1,'Configure with security flags']]],
  ['flags_20first_94',['1. Always Use Silent Flags First',['../md_skills_2build.html#autotoc_md1181',1,'']]],
  ['flags_20in_20ci_20cd_20security_20checks_95',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md1246',1,'']]],
  ['flags_20silent_20build_96',['Pattern 1: Hardening Flags (Silent Build)',['../md_skills_2claude__build.html#autotoc_md1254',1,'']]],
  ['flawfinder_20c_20c_20security_20scanner_97',['Flawfinder (C/C++ Security Scanner)',['../md_skills_2claude__build.html#autotoc_md1225',1,'']]],
  ['flawfinder_20for_20security_20issues_98',['Flawfinder for security issues',['../md_skills_2claude__build.html#autotoc_md1234',1,'']]],
  ['flow_99',['Flow',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md403',1,'Code Flow'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md299',1,'Review Flow']]],
  ['flows_100',['flows',['../classworkshop_1_1saw_1_1TaintAnalyzer.html#a5b573949b59c0d32b77989a80a251666',1,'workshop::saw::TaintAnalyzer']]],
  ['fnamechg_101',['fnamechg',['../unlzexe_8c.html#a019eabe66c4e1eb74dee48f721fce3a7',1,'unlzexe.c']]],
  ['fnamechk_102',['fnamechk',['../unlzexe_8c.html#a38648f3d653a7637c80328a81f21fa31',1,'unlzexe.c']]],
  ['focus_20on_20security_20relevant_20output_103',['2. Focus on Security-Relevant Output',['../md_skills_2claude__build.html#autotoc_md1242',1,'']]],
  ['focused_20agent_201_20agent_104',['Security-Focused Agent (1 agent)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1144',1,'']]],
  ['focused_20build_20skill_105',['Claude Security-Focused Build Skill',['../md_skills_2claude__build.html',1,'']]],
  ['for_20agents_106',['for Agents',['../md__8collab__env.html#autotoc_md11',1,'Notes for Agents'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md532',1,'Safe Commands for Agents']]],
  ['for_20all_20agents_107',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'']]],
  ['for_20axe_108',['for AXE',['../md_AGENTS.html',1,'AGENTS.md for AXE'],['../md_llm__prep_2project__guidance.html',1,'Project Guidance for AXE']]],
  ['for_20c_20c_20issues_109',['Cppcheck for C/C++ issues',['../md_skills_2claude__build.html#autotoc_md1233',1,'']]],
  ['for_20existing_20code_110',['For Existing Code',['../md_REFACTORING__NOTES.html#autotoc_md1022',1,'']]],
  ['for_20humans_111',['Tips for Humans',['../md_QUICK__REFERENCE.html#autotoc_md851',1,'']]],
  ['for_20implementation_112',['Ready for Implementation',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md96',1,'']]],
  ['for_20maintainers_113',['For Maintainers',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md100',1,'']]],
  ['for_20maximum_20shared_20view_114',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['for_20memory_20issues_20silent_115',['Quick check for memory issues (silent)',['../md_skills_2claude__build.html#autotoc_md1214',1,'']]],
  ['for_20merge_116',['✅ APPROVED FOR MERGE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md822',1,'']]],
  ['for_20multi_20agent_20work_117',['Test Projects for Multi-Agent Work',['../md_MODELS__FINAL.html#autotoc_md658',1,'']]],
  ['for_20new_20code_118',['For New Code',['../md_REFACTORING__NOTES.html#autotoc_md1023',1,'']]],
  ['for_20production_3a_119',['For Production:',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md455',1,'']]],
  ['for_20regressions_120',['Check for regressions',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md469',1,'']]],
  ['for_20runtime_20detection_121',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md1237',1,'']]],
  ['for_20security_20audits_122',['Best Practices for Security Audits',['../md_skills_2claude__build.html#autotoc_md1240',1,'']]],
  ['for_20security_20issues_123',['Flawfinder for security issues',['../md_skills_2claude__build.html#autotoc_md1234',1,'']]],
  ['for_20user_3a_124',['For User:',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md454',1,'']]],
  ['for_20users_125',['For Users',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md99',1,'']]],
  ['force_5fsleep_126',['force_sleep',['../classmanagers_1_1sleep__manager_1_1SleepManager.html#a2380705e53ed4a517c711eef10d7490c',1,'managers::sleep_manager::SleepManager']]],
  ['format_127',['Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md683',1,'Example 1: Claude&apos;s Natural Format'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md684',1,'Example 2: Code Block Format'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md685',1,'Example 3: AXE Native Format'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md513',1,'Format'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md496',1,'Message Format'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md298',1,'Token Format'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1480',1,'WRITE Block Format']]],
  ['format_128',['format',['../namespacetools_1_1build__analyzer.html#a41d92c9d0c8210453cb630064736635c',1,'tools::build_analyzer']]],
  ['format_20new_129',['XML Format (New!)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1518',1,'']]],
  ['format_20original_130',['Markdown Format (Original)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1519',1,'']]],
  ['format_20tool_20call_20parser_20implementation_131',['Multi-Format Tool Call Parser Implementation',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'']]],
  ['format_20tool_20call_20parser_20quick_20reference_132',['Multi-Format Tool Call Parser - Quick Reference',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['format_5fcost_133',['format_cost',['../namespaceutils_1_1token__stats.html#af749d8ae6c60119851a792d66884337b',1,'utils::token_stats']]],
  ['format_5finput_5fmodes_134',['format_input_modes',['../namespacemodels_1_1metadata.html#a6b6eea40b2ea7d4a925a2f34d7f17ca4',1,'models::metadata']]],
  ['format_5foutput_5fmodes_135',['format_output_modes',['../namespacemodels_1_1metadata.html#a959bd8a8f487f3c829e22b33879b288b',1,'models::metadata']]],
  ['format_5ftoken_5fcount_136',['format_token_count',['../namespacemodels_1_1metadata.html#ab6ab0f84d1398bf8ca3ea3619c414fd9',1,'models::metadata']]],
  ['format_5fxml_5fresult_137',['format_xml_result',['../namespaceutils_1_1xml__tool__parser.html#a57988f65906393ac9687744afaca5b0e',1,'utils::xml_tool_parser']]],
  ['formats_138',['Formats',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md668',1,'Supported Formats'],['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md688',1,'Supported Formats'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1517',1,'Supported Formats']]],
  ['formats_20not_20supported_20✅_139',['Bug 1: XML Tag Formats Not Supported ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md196',1,'']]],
  ['formatting_2epy_140',['formatting.py',['../formatting_8py.html',1,'']]],
  ['found_20re_20run_20with_20full_20details_3a_141',['found re run with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md1215',1,'If issues found, re-run with full details:']]],
  ['found_20run_20full_20scan_3a_142',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md1227',1,'']]],
  ['four_20analysis_20tools_20implemented_143',['Claim 1: Four Analysis Tools Implemented',['../md_PR23__VALIDATION__REPORT.html#autotoc_md749',1,'']]],
  ['four_20dynamic_20analysis_20tools_144',['✅ Four Dynamic Analysis Tools',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md697',1,'']]],
  ['fp_145',['fp',['../structbitstream.html#a0120309c54e22e1c3644af7e411d1f7a',1,'bitstream']]],
  ['framework_146',['frida-python (Instrumentation Framework)',['../md_workshop__dependency__validation.html#autotoc_md1368',1,'']]],
  ['framework_20compatibility_147',['AXE Framework Compatibility',['../md_workshop__dependency__validation.html#autotoc_md1389',1,'']]],
  ['framework_20comprehensive_20validation_20report_148',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_PR23__VALIDATION__REPORT.html',1,'']]],
  ['framework_20executive_20summary_149',['PR #23 Workshop Dynamic Analysis Framework - Executive Summary',['../md_PR23__EXECUTIVE__SUMMARY.html',1,'']]],
  ['free_20tier_20available_150',['HuggingFace (Llama) - Free Tier Available!',['../md_README.html#autotoc_md886',1,'']]],
  ['free_20with_20copilot_151',['GitHub Models - Free with Copilot',['../md_README.html#autotoc_md887',1,'']]],
  ['frida_20python_20instrumentation_20framework_152',['frida-python (Instrumentation Framework)',['../md_workshop__dependency__validation.html#autotoc_md1368',1,'']]],
  ['from_20live_20testing_153',['Evidence from Live Testing',['../md_FIXES__SUMMARY.html#autotoc_md382',1,'']]],
  ['from_20problem_20statement_20_3a_154',['Previously Failing (from problem statement):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1133',1,'']]],
  ['from_20whitelist_20to_20sandbox_155',['From Whitelist to Sandbox',['../md_SANDBOX.html#autotoc_md1049',1,'']]],
  ['fulfillment_20summary_156',['Claims Fulfillment Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md817',1,'']]],
  ['full_20details_157',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md1236',1,'']]],
  ['full_20details_3a_158',['full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md1215',1,'If issues found, re-run with full details:']]],
  ['full_20scan_3a_159',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md1227',1,'']]],
  ['function_160',['Function',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md224',1,'1. Added &lt;span class=&quot;tt&quot;&gt;get_database_path()&lt;/span&gt; Helper Function'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md227',1,'4. Exported Helper Function']]],
  ['function_20call_20parser_20implementation_20summary_161',['XML Function Call Parser - Implementation Summary',['../md_XML__PARSER__IMPLEMENTATION.html',1,'']]],
  ['function_20call_20support_20quick_20reference_162',['XML Function Call Support - Quick Reference',['../md_XML__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['function_20level_20analysis_163',['Function-Level Analysis',['../md_workshop__benchmarks.html#autotoc_md1348',1,'']]],
  ['function_20signatures_164',['3. Updated Function Signatures',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md226',1,'']]],
  ['functionality_165',['Functionality',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md586',1,'Core Functionality'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1076',1,'Preserved Functionality']]],
  ['functionality_20user_20guide_166',['WRITE Block Functionality - User Guide',['../md_WRITE__BLOCKS__GUIDE.html',1,'']]],
  ['functions_167',['Updated Functions',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md671',1,'']]],
  ['functions_20✅_168',['Phase 2: Extract Functions ✅',['../md_REFACTORING__NOTES.html#autotoc_md1004',1,'']]],
  ['functions_20added_169',['New Functions Added',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md670',1,'']]],
  ['future_170',['Optional (Future)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md738',1,'']]],
  ['future_20considerations_171',['Future Considerations',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md240',1,'']]],
  ['future_20enhancements_172',['Future Enhancements',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md95',1,'Future Enhancements'],['../md_ARCHITECTURE.html#autotoc_md167',1,'Future Enhancements'],['../md_BUG__FIX__SUMMARY.html#autotoc_md208',1,'Future Enhancements'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md355',1,'Future Enhancements'],['../md_SANDBOX.html#autotoc_md1057',1,'Future Enhancements'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1090',1,'Future Enhancements'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1313',1,'Future Enhancements'],['../md_workshop__security__audit.html#autotoc_md1445',1,'Future Enhancements'],['../md_workshop__test__results.html#autotoc_md1475',1,'Future Enhancements'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1499',1,'Future Enhancements'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1512',1,'Future Enhancements']]],
  ['future_20features_20not_20yet_20implemented_173',['Future Features (Not Yet Implemented)',['../md_QUICK__REFERENCE.html#autotoc_md861',1,'']]],
  ['future_20optimization_20opportunities_174',['Future Optimization Opportunities',['../md_workshop__benchmarks.html#autotoc_md1362',1,'']]],
  ['future_20refactoring_20prs_202_203_175',['Future Refactoring (PRs #2 &amp;amp; #3)',['../md_REFACTORING__NOTES.html#autotoc_md1018',1,'']]],
  ['fuzzing_20setup_20silent_176',['Pattern 4: Fuzzing Setup (Silent)',['../md_skills_2claude__build.html#autotoc_md1257',1,'']]]
];
