var searchData=
[
  ['n_0',['N',['../md_TODO.html#autotoc_md2229',1,'']]],
  ['names_1',['Parameter Names',['../md_docs_2features_2parsers.html#autotoc_md1227',1,'']]],
  ['namespace_2',['Namespace',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1422',1,'What Works Without User Namespace'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1423',1,'What&apos;s Missing Without User Namespace']]],
  ['namespace_20detection_3',['1. Enhanced User Namespace Detection',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1417',1,'']]],
  ['namespace_20detection_20and_20safety_20improvements_4',['User Namespace Detection and Safety Improvements',['../md_docs_2NAMESPACE__DETECTION.html',1,'']]],
  ['namespace_20isolation_5',['Namespace Isolation',['../md_docs_2features_2sandbox.html#autotoc_md1249',1,'2. Linux Namespace Isolation'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md652',1,'2. Namespace Isolation']]],
  ['namespace_5fdetection_2emd_6',['NAMESPACE_DETECTION.md',['../NAMESPACE__DETECTION_8md.html',1,'']]],
  ['namespaces_7',['namespaces',['../classcore_1_1sandbox_1_1SandboxManager.html#a8db40d2ec58d885009d8be2e6465d195',1,'core::sandbox::SandboxManager']]],
  ['naming_8',['Naming',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1546',1,'2. Standardized Key Naming'],['../md_AGENTS.html#autotoc_md29',1,'File Naming']]],
  ['naming_20standard_3a_20context_5ftokens_9',['Key Naming Standard: &lt;span class=&quot;tt&quot;&gt;context_tokens&lt;/span&gt;',['../md_docs_2features_2configuration.html#autotoc_md1171',1,'']]],
  ['native_20blocks_10',['Native Blocks',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md609',1,'3. AXE Native Blocks'],['../md_docs_2features_2parsers.html#autotoc_md1217',1,'3. AXE Native Blocks']]],
  ['native_20format_11',['Example 3: AXE Native Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md603',1,'']]],
  ['native_20read_20write_20exec_20blocks_12',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md252',1,'']]],
  ['natural_20format_13',['Example 1: Claude&apos;s Natural Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md601',1,'']]],
  ['need_14',['🔍 Finding What You Need',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1531',1,'']]],
  ['needed_15',['Create parent dirs if needed',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md403',1,'']]],
  ['negative_20votes_16',['Using Negative Votes',['../md_docs_2xp__voting.html#autotoc_md1957',1,'']]],
  ['nested_20subshells_17',['3. Nested Subshells',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md698',1,'']]],
  ['network_20isolated_18',['Scenario 3: Network Isolated',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md672',1,'']]],
  ['network_20isolated_20sandbox_19',['Example 3: Network-Isolated Sandbox',['../md_docs_2features_2sandbox.html#autotoc_md1258',1,'']]],
  ['never_20does_20',['What AXE NEVER Does',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1430',1,'']]],
  ['never_20get_20turns_20✅_21',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['new_22',['NEW',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md281',1,'6. &lt;span class=&quot;tt&quot;&gt;tests/test_dynamic_max_tokens.py&lt;/span&gt; (NEW)'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md282',1,'7. &lt;span class=&quot;tt&quot;&gt;demo_dynamic_tokens.py&lt;/span&gt; (NEW)']]],
  ['new_23',['New',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md800',1,'What&apos;s New?'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md803',1,'XML Format (New!)']]],
  ['new_20agent_20commands_20during_20sessions_24',['New Agent Commands (During Sessions)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md491',1,'']]],
  ['new_20ai_20providers_25',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md52',1,'']]],
  ['new_20code_26',['For New Code',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md642',1,'']]],
  ['new_20features_27',['New Features',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1548',1,'4. New Features'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md494',1,'Starting a Collaborative Session with New Features']]],
  ['new_20files_28',['New Files',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md794',1,'New Files'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md958',1,'New Files'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1327',1,'New Files']]],
  ['new_20files_20created_29',['New Files Created',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1542',1,'']]],
  ['new_20functions_20added_30',['New Functions Added',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md588',1,'']]],
  ['new_20module_20structure_31',['New Module Structure',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md616',1,'']]],
  ['new_20provider_32',['Adding a New Provider',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1557',1,'']]],
  ['new_20providers_33',['Adding New Providers',['../md_docs_2features_2configuration.html#autotoc_md1184',1,'']]],
  ['new_20skills_34',['Creating New Skills',['../md_AGENTS.html#autotoc_md32',1,'']]],
  ['new_20test_20files_35',['New Test Files',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md126',1,'']]],
  ['new_20tests_20added_36',['New Tests Added',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md262',1,'New Tests Added'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md333',1,'New Tests Added']]],
  ['new_20token_20optimization_20strategies_37',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md55',1,'']]],
  ['new_20workshop_20tools_38',['3. Adding New Workshop Tools',['../md_ARCHITECTURE.html#autotoc_md54',1,'']]],
  ['new_20workspace_20command_20axe_20py_39',['5. New &lt;span class=&quot;tt&quot;&gt;/workspace&lt;/span&gt; Command (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1919',1,'']]],
  ['newline_20e_20g_20cat_20eof_40',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md328',1,'']]],
  ['newly_20fixed_20_3a_41',['Edge Cases (newly fixed):',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md710',1,'']]],
  ['next_20promotion_42',['Check Next Promotion',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1504',1,'']]],
  ['next_20steps_43',['Next Steps',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md323',1,'Next Steps'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md390',1,'Next Steps'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md529',1,'Next Steps'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1110',1,'Next Steps'],['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1704',1,'Recommended Next Steps']]],
  ['next_20steps_20integration_44',['Next Steps (Integration)',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1339',1,'']]],
  ['ninja_45',['Ninja',['../md_skills_2build.html#autotoc_md2065',1,'']]],
  ['no_20breakage_46',['Existing tests (verify no breakage)',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md807',1,'']]],
  ['no_20credits_20error_47',['No Credits Error',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md580',1,'']]],
  ['no_20duplicate_20execution_48',['Example 1: No Duplicate Execution',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md265',1,'']]],
  ['no_20hardcoded_20secrets_20verified_49',['No Hardcoded Secrets - VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md908',1,'']]],
  ['no_20heredoc_20process_20line_20by_20line_20as_20before_50',['No heredoc - process line by line as before',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md259',1,'']]],
  ['no_20installation_20required_51',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1117',1,'']]],
  ['no_20prefixes_52',['General Rule: Lowercase, No Prefixes',['../md_docs_2features_2configuration.html#autotoc_md1173',1,'']]],
  ['no_20rate_20limiting_53',['Finding #3: No Rate Limiting',['../md_docs_2workshop_2security-audit.html#autotoc_md1867',1,'']]],
  ['no_20real_20bullying_54',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md463',1,'']]],
  ['no_20regressions_55',['✅ No Regressions',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md375',1,'']]],
  ['no_20results_20appearing_56',['No Results Appearing?',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md809',1,'']]],
  ['node_57',['Node',['../structNode.html',1,'Node'],['../depklite_8c.html#a3b09f37e675bcd48a01bf22155996872',1,'Node:&#160;depklite.c']]],
  ['noise_58',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md2139',1,'']]],
  ['non_20blocking_59',['Non Blocking',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md830',1,'Minor Issues (Non-Blocking)'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md935',1,'Minor Issues Identified (Non-Blocking)']]],
  ['none_60',['None',['../md_docs_2global-workspace.html#autotoc_md1308',1,'&lt;span class=&quot;tt&quot;&gt;acknowledge(broadcast_id, agent_alias, comment=None)&lt;/span&gt;'],['../md_docs_2socket__interface.html#autotoc_md1668',1,'&lt;span class=&quot;tt&quot;&gt;check_and_cleanup_stale_files() -&amp;gt; None&lt;/span&gt;'],['../md_docs_2socket__interface.html#autotoc_md1669',1,'&lt;span class=&quot;tt&quot;&gt;cleanup_files() -&amp;gt; None&lt;/span&gt;'],['../md_docs_2xp__voting.html#autotoc_md1945',1,'&lt;span class=&quot;tt&quot;&gt;get_vote_history(agent_alias=None)&lt;/span&gt;'],['../md_docs_2socket__interface.html#autotoc_md1670',1,'&lt;span class=&quot;tt&quot;&gt;setup_signal_handlers() -&amp;gt; None&lt;/span&gt;'],['../md_docs_2socket__interface.html#autotoc_md1667',1,'&lt;span class=&quot;tt&quot;&gt;write_pid_file() -&amp;gt; None&lt;/span&gt;'],['../md_docs_2workshop_2test-results.html#autotoc_md1903',1,'Test Failures (None)']]],
  ['none_20agent_20none_20requires_5fack_5fonly_20false_20limit_2050_61',['&lt;span class=&quot;tt&quot;&gt;get_broadcasts(since=None, category=None, agent=None, requires_ack_only=False, limit=50)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1309',1,'']]],
  ['none_20category_20none_20agent_20none_20requires_5fack_5fonly_20false_20limit_2050_62',['&lt;span class=&quot;tt&quot;&gt;get_broadcasts(since=None, category=None, agent=None, requires_ack_only=False, limit=50)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1309',1,'']]],
  ['none_20requires_5fack_5fonly_20false_20limit_2050_63',['&lt;span class=&quot;tt&quot;&gt;get_broadcasts(since=None, category=None, agent=None, requires_ack_only=False, limit=50)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1309',1,'']]],
  ['normalize_5ftool_5fname_64',['normalize_tool_name',['../namespaceutils_1_1xml__tool__parser.html#acd18e34b8713011c876e3ae157a4fb6c',1,'utils::xml_tool_parser']]],
  ['not_20applied_65',['Votes Not Applied?',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1046',1,'']]],
  ['not_20archive_66',['Do NOT Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md970',1,'']]],
  ['not_20available_67',['Extended thinking not available',['../md_docs_2features_2anthropic-features.html#autotoc_md1156',1,'']]],
  ['not_20available_20falling_20back_20to_20unrestricted_20mode_68',['&quot;bubblewrap not available, falling back to unrestricted mode&quot;',['../md_docs_2features_2sandbox.html#autotoc_md1270',1,'']]],
  ['not_20cooperating_69',['&quot;Agents not cooperating&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1582',1,'']]],
  ['not_20default_20in_20collab_20mode_70',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md183',1,'']]],
  ['not_20default_20in_20collab_20mode_20✅_71',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md304',1,'']]],
  ['not_20executing_20high_72',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md398',1,'']]],
  ['not_20found_73',['Not Found',['../md_docs_2features_2configuration.html#autotoc_md1187',1,'Model Not Found'],['../md_docs_2socket__interface.html#autotoc_md1659',1,'Socket File Not Found']]],
  ['not_20handled_20✅_74',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['not_20running_75',['Server Not Running?',['../md_docs_2ollama-guide.html#autotoc_md1446',1,'']]],
  ['not_20sandbox_20mode_76',['Commands work in unrestricted mode but not sandbox mode',['../md_docs_2features_2sandbox.html#autotoc_md1272',1,'']]],
  ['not_20supported_20✅_77',['Bug 1: XML Tag Formats Not Supported ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['not_20working_78',['Tokens Not Working?',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1045',1,'']]],
  ['not_20working_79',['not working',['../md_docs_2features_2anthropic-features.html#autotoc_md1155',1,'Caching not working'],['../md_docs_2features_2anthropic-features.html#autotoc_md1158',1,'Files API not working']]],
  ['not_20yet_20implemented_80',['Future Features (Not Yet Implemented)',['../md_docs_2references_2quick-reference.html#autotoc_md1586',1,'']]],
  ['note_20on_20workspace_20bug_81',['Note on Workspace Bug',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1103',1,'']]],
  ['notes_82',['Notes',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md498',1,'Architecture Notes'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1048',1,'Architecture Notes'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html',1,'AXE.PY Refactoring Notes'],['../md__8collab__shared.html',1,'Collaborative Session Notes'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md711',1,'Implementation Notes'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md543',1,'Notes'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md550',1,'Notes'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md556',1,'Notes'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md563',1,'Notes'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md569',1,'Notes'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1634',1,'Notes'],['../md_tests_2MISSION.html#autotoc_md2201',1,'Notes'],['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md1000',1,'Reverse-Engineering Workflow Notes'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1849',1,'Safety Notes']]],
  ['notes_20for_20agents_83',['Notes for Agents',['../md__8collab__env.html#autotoc_md11',1,'']]],
  ['now_20allowed_20bug_20fixed_20_3a_84',['✅ Now Allowed (Bug Fixed):',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md131',1,'']]],
  ['now_20handled_20exclusively_20by_20axe_20py_20responseprocessor_85',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md253',1,'']]],
  ['now_20working_86',['Now Working',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md134',1,'Agents Now Working'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md708',1,'Commands Now Working']]]
];
