var searchData=
[
  ['v_0',['V',['../md_TODO.html#autotoc_md2234',1,'']]],
  ['v1_200_20current_1',['v1.0 (Current)',['../md_docs_2features_2write-blocks.html#autotoc_md1298',1,'']]],
  ['valgrind_20memory_20analysis_2',['Valgrind (Memory Analysis)',['../md_skills_2claude__build.html#autotoc_md2104',1,'']]],
  ['valid_5freasoning_5fefforts_3',['VALID_REASONING_EFFORTS',['../namespacemodels_1_1metadata.html#aa6a1a2138c8dfb2ef7edd0c4f9da70e0',1,'models::metadata']]],
  ['validate_20command_4',['Validate Command',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1503',1,'']]],
  ['validate_20filename_5',['Validate filename',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md401',1,'']]],
  ['validate_5fcodex_5fconfig_6',['validate_codex_config',['../namespacevalidate__codex__config.html',1,'']]],
  ['validate_5fcodex_5fconfig_2epy_7',['validate_codex_config.py',['../validate__codex__config_8py.html',1,'']]],
  ['validate_5fcodex_5fconfiguration_8',['validate_codex_configuration',['../namespacevalidate__codex__config.html#afbc1163d2096de4c5e1f9bfc22399994',1,'validate_codex_config']]],
  ['validate_5fcollab_5fcodex_5ffix_9',['validate_collab_codex_fix',['../namespacevalidate__collab__codex__fix.html',1,'']]],
  ['validate_5fcollab_5fcodex_5ffix_2epy_10',['validate_collab_codex_fix.py',['../validate__collab__codex__fix_8py.html',1,'']]],
  ['validate_5fcommand_11',['validate_command',['../namespacecore_1_1privilege__mapping.html#a8d25ce26515587b7461cabab336a58d1',1,'core::privilege_mapping']]],
  ['validate_5fcustom_5fabbreviations_12',['validate_custom_abbreviations',['../classcore_1_1acp__validator_1_1ACPValidator.html#a948b52fa82a4a216404331d08f9d964e',1,'core::acp_validator::ACPValidator']]],
  ['validate_5fdpi_13',['validate_dpi',['../namespacepdfocr.html#abfb3d61192e485a1e34e0fe83935043d',1,'pdfocr']]],
  ['validate_5ffix_14',['validate_fix',['../namespacevalidate__collab__codex__fix.html#a6f0a23a4dae59ee1d141cc2ef988efc0',1,'validate_collab_codex_fix']]],
  ['validate_5freasoning_5feffort_15',['validate_reasoning_effort',['../namespacemodels_1_1metadata.html#a444f301466304bfc7a8c55216ea0e655',1,'models::metadata']]],
  ['validated_20bonus_20xp_20calculation_16',['✅ VALIDATED - Bonus XP Calculation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md883',1,'']]],
  ['validated_20chisel_20symbolic_20execution_17',['✅ VALIDATED - Chisel (Symbolic Execution)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md872',1,'']]],
  ['validated_20configuration_20structure_18',['✅ VALIDATED - Configuration Structure',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md886',1,'']]],
  ['validated_20database_20methods_19',['✅ VALIDATED - Database Methods',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md879',1,'']]],
  ['validated_20database_20schema_20',['✅ VALIDATED - Database Schema',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md878',1,'']]],
  ['validated_20documentation_20files_21',['✅ VALIDATED - Documentation Files',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md889',1,'']]],
  ['validated_20hammer_20live_20instrumentation_22',['✅ VALIDATED - Hammer (Live Instrumentation)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md875',1,'']]],
  ['validated_20plane_20source_20sink_20enumeration_23',['✅ VALIDATED - Plane (Source/Sink Enumeration)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md874',1,'']]],
  ['validated_20saw_20taint_20analysis_24',['✅ VALIDATED - Saw (Taint Analysis)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md873',1,'']]],
  ['validated_20test_20files_25',['✅ VALIDATED - Test Files',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md897',1,'']]],
  ['validated_20xp_20awards_20dictionary_26',['✅ VALIDATED - XP Awards Dictionary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md882',1,'']]],
  ['validation_27',['Validation',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1547',1,'3. Comprehensive Validation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md927',1,'Dependency Validation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md893',1,'Document 4: Dependency Validation'],['../md_docs_2workshop_2security-audit.html#autotoc_md1865',1,'Finding #1: Missing Input Size Validation'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1788',1,'Installation Validation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md907',1,'Part 3: Security Validation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md912',1,'Part 4: Performance Validation'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1795',1,'Security Validation'],['../md_docs_2workshop_2test-results.html#autotoc_md1905',1,'Test Environment Validation'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md331',1,'Validation'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md766',1,'Validation'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md779',1,'Validation'],['../md_docs_2workshop_2dependency-validation.html',1,'Workshop Tools Dependency Validation'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md727',1,'YAML Validation']]],
  ['validation_20checklist_28',['Feature Validation Checklist',['../md_docs_2TESTING.html#autotoc_md1746',1,'']]],
  ['validation_20conclusion_29',['Part 10: Validation Conclusion',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md938',1,'']]],
  ['validation_20errors_30',['Validation Errors',['../md_docs_2features_2configuration.html#autotoc_md1170',1,'']]],
  ['validation_20example_31',['Validation Example',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1551',1,'']]],
  ['validation_20internal_20stripped_20version_20_3a_32',['Validation (internal, stripped version):',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md350',1,'']]],
  ['validation_20md_33',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2dependency-validation.html&quot;&gt;dependency-validation.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1838',1,'']]],
  ['validation_20md_20dependency_20validation_20md_34',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2dependency-validation.html&quot;&gt;dependency-validation.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1838',1,'']]],
  ['validation_20quality_20assurance_35',['Validation &amp;amp; Quality Assurance',['../md_docs_2workshop_2quick-reference.html#autotoc_md1826',1,'']]],
  ['validation_20report_36',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html',1,'']]],
  ['validation_20results_37',['Validation Results',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md835',1,'']]],
  ['validation_20sign_20off_38',['Validation Sign-Off',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md951',1,'']]],
  ['validation_20suite_39',['Custom Validation Suite',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md836',1,'']]],
  ['validation_20summary_40',['Validation Summary',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md978',1,'Feature Validation Summary'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1774',1,'Validation Summary']]],
  ['validation_20test_20suite_41',['Validation Test Suite',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md954',1,'']]],
  ['validation_20tests_20created_42',['Custom Validation Tests Created',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md922',1,'']]],
  ['validation_20verified_43',['Input Validation - VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md909',1,'']]],
  ['value_44',['value',['../structEntry.html#a73971df7dd165eb6841f8c4ee61c97d9',1,'Entry::value'],['../structNode.html#aaa0cd30d78a90c5a6ab64eb3d58b8f87',1,'Node::value']]],
  ['var_5ftaint_5fmap_45',['var_taint_map',['../classworkshop_1_1saw_1_1TaintAnalyzer.html#a05a84206ddebb81e4cb53aa1ba0315a3',1,'workshop::saw::TaintAnalyzer']]],
  ['variable_46',['Variable',['../md_docs_2api-providers.html#autotoc_md68',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md76',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md86',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md95',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md104',1,'Environment Variable']]],
  ['variables_20summary_47',['Environment Variables Summary',['../md_docs_2api-providers.html#autotoc_md110',1,'']]],
  ['variants_48',['Pre-configured Reasoning Variants',['../md_docs_2codex-implementation.html#autotoc_md1008',1,'']]],
  ['venv_20pip_49',['Option A: Standard venv + pip',['../md_README.html#autotoc_md2000',1,'']]],
  ['verbose_50',['Verbose',['../md_skills_2claude__build.html#autotoc_md2132',1,'1. Start Silent, Investigate Verbose'],['../md_skills_2claude__build.html#autotoc_md2126',1,'Phase 3: Detailed Investigation (Verbose)']]],
  ['verbose_51',['verbose',['../depklite_8c.html#ab46784744f0c75c40a5591adc24f2dea',1,'depklite.c']]],
  ['verbose_20by_20default_52',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md2080',1,'']]],
  ['verbose_20on_20failure_53',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md2073',1,'']]],
  ['verbose_20output_54',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md36',1,'']]],
  ['verbose_20output_3a_55',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md2112',1,'']]],
  ['verbosely_56',['5. Test Silently, Debug Verbosely',['../md_skills_2build.html#autotoc_md2076',1,'']]],
  ['verification_57',['Verification',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md236',1,'Manual Verification'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md901',1,'Part 2: Integration Verification'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1359',1,'Runtime Verification'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md137',1,'Verification'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md234',1,'Verification'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md271',1,'Verification'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md347',1,'Verification'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md713',1,'Verification']]],
  ['verification_58',['Manual verification',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md806',1,'']]],
  ['verification_20✅_59',['Test 1: Ollama Setup Verification ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1464',1,'']]],
  ['verification_20and_20reporting_60',['7. Token Savings — Verification and Reporting',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md994',1,'']]],
  ['verification_20commands_61',['Verification Commands',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1519',1,'']]],
  ['verification_20results_62',['Verification Results',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1347',1,'2. Verification Results'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md726',1,'Verification Results']]],
  ['verified_63',['VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md909',1,'Input Validation - VERIFIED'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md908',1,'No Hardcoded Secrets - VERIFIED'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md910',1,'Resource Controls - VERIFIED']]],
  ['verified_64',['Features Verified',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1373',1,'']]],
  ['verify_20no_20breakage_65',['Existing tests (verify no breakage)',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md807',1,'']]],
  ['verify_5fintegration_66',['verify_integration',['../namespaceverify__integration.html',1,'']]],
  ['verify_5fintegration_2epy_67',['verify_integration.py',['../verify__integration_8py.html',1,'']]],
  ['verifying_20integration_68',['Verifying Integration',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1040',1,'']]],
  ['version_69',['VERSION',['../unlzexe_8c.html#a1c6d5de492ac61ad29aec7aa9a436bbf',1,'unlzexe.c']]],
  ['version_20_3a_70',['version :',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md351',1,'Execution (original version):'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md350',1,'Validation (internal, stripped version):']]],
  ['version_20check_71',['Tool Version Check',['../md__8collab__env.html#autotoc_md9',1,'']]],
  ['version_20pinning_72',['Finding #4: Dependency Version Pinning',['../md_docs_2workshop_2security-audit.html#autotoc_md1868',1,'']]],
  ['version_20support_73',['Python Version Support',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1786',1,'']]],
  ['version_5fkey_74',['version_key',['../namespacetools_1_1build__analyzer.html#a5a0d0bf7af120fdae4d537c9c852a3d9',1,'tools::build_analyzer']]],
  ['versioned_20history_75',['3. Session Persistence — Versioned History',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md986',1,'']]],
  ['versioned_20session_20store_76',['2. Versioned Session Store',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1698',1,'']]],
  ['versioned_20under_20scripts_20patches_20dosbox_20staging_77',['dosbox-staging build patches (versioned under &lt;span class=&quot;tt&quot;&gt;scripts/patches/dosbox-staging/&lt;/span&gt;)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2195',1,'']]],
  ['very_20common_78',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md2159',1,'']]],
  ['vflag_79',['vflag',['../depklite_8c.html#ac710816f73e3cefff5011aab1bc9a796',1,'depklite.c']]],
  ['via_20ollama_80',['Meta Llama (via Ollama)',['../md_README.html#autotoc_md2031',1,'']]],
  ['via_20socket_81',['Sending Commands via Socket',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1630',1,'']]],
  ['view_82',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['viewing_20diagrams_83',['Viewing Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1116',1,'']]],
  ['viewing_20session_20rules_84',['Viewing Session Rules',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md495',1,'']]],
  ['vision_20—_20alignment_20assessment_85',['The &quot;Office&quot; Vision — Alignment Assessment',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md998',1,'']]],
  ['vision_20and_20sri_86',['The &quot;Office&quot; Vision and SRI',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1702',1,'']]],
  ['vision_20example_20images_87',['Vision Example (Images)',['../md_docs_2api-providers.html#autotoc_md79',1,'']]],
  ['visit_5fassign_88',['visit_Assign',['../classworkshop_1_1saw_1_1TaintAnalyzer.html#a82e632e124fa2892f991ffa8cccd9805',1,'workshop::saw::TaintAnalyzer']]],
  ['visit_5fattribute_89',['visit_Attribute',['../classworkshop_1_1plane_1_1SourceSinkVisitor.html#a269bdc8ac096e820b482aa7534dec102',1,'workshop::plane::SourceSinkVisitor']]],
  ['visit_5fcall_90',['visit_Call',['../classworkshop_1_1plane_1_1SourceSinkVisitor.html#ac1dc92f8690ddc76a55f1a71115b48bc',1,'workshop.plane.SourceSinkVisitor.visit_Call()'],['../classworkshop_1_1saw_1_1TaintAnalyzer.html#a5c28b8c11ae8d515895a15bf742320d4',1,'workshop.saw.TaintAnalyzer.visit_Call()']]],
  ['vote_91',['Vote',['../md_docs_2xp__voting.html#autotoc_md1939',1,'Casting a Vote'],['../md_docs_2xp__voting.html#autotoc_md1956',1,'When to Vote']]],
  ['vote_20limits_20anti_20abuse_92',['Vote Limits (Anti-Abuse)',['../md_docs_2xp__voting.html#autotoc_md1937',1,'']]],
  ['vote_20power_20scales_20with_20level_93',['Vote Power Scales with Level',['../md_docs_2xp__voting.html#autotoc_md1936',1,'']]],
  ['vote_20reasons_94',['Vote Reasons',['../md_docs_2xp__voting.html#autotoc_md1958',1,'']]],
  ['vote_5fid_95',['&lt;span class=&quot;tt&quot;&gt;mark_vote_applied(vote_id)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1948',1,'']]],
  ['vote_5flimits_96',['VOTE_LIMITS',['../namespacecore_1_1global__workspace.html#add719ed074df5dc0dde0b3b7d417e46a',1,'core::global_workspace']]],
  ['vote_5fxp_97',['vote_xp',['../classcore_1_1global__workspace_1_1GlobalWorkspace.html#aa4c7c5568edf109eb066f476e43b748a',1,'core::global_workspace::GlobalWorkspace']]],
  ['vote_5fxp_20voter_5falias_20voter_5flevel_20target_5falias_20xp_5fdelta_20reason_98',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['voter_5falias_20voter_5flevel_20target_5falias_20xp_5fdelta_20reason_99',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['voter_5flevel_20target_5falias_20xp_5fdelta_20reason_100',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['votes_101',['Using Negative Votes',['../md_docs_2xp__voting.html#autotoc_md1957',1,'']]],
  ['votes_102',['&lt;span class=&quot;tt&quot;&gt;apply_xp_votes(votes)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1951',1,'']]],
  ['votes_20not_20applied_103',['Votes Not Applied?',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1046',1,'']]],
  ['voting_20minsky_201986_104',['XP Voting (Minsky, 1986)',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1351',1,'']]],
  ['voting_20peer_20reputation_105',['2. XP Voting (Peer Reputation)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1032',1,'']]],
  ['voting_20system_106',['Peer XP Voting System',['../md_docs_2xp__voting.html',1,'']]],
  ['voting_20system_20database_20✅_107',['Test 3: XP Voting System + Database ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1466',1,'']]],
  ['voting_20system_20minsky_201986_108',['PR #55: XP Voting System (Minsky 1986)',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1086',1,'']]],
  ['vs_20active_20documentation_109',['Archive vs. Active Documentation',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md967',1,'']]],
  ['vs_20actual_20implementation_110',['Part 1: PR Claims vs. Actual Implementation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md870',1,'']]],
  ['vs_20after_111',['Example - Before vs After',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md348',1,'']]],
  ['vs_20chat_20completions_112',['Key Differences: Responses API vs Chat Completions',['../md_docs_2codex-implementation.html#autotoc_md1016',1,'']]],
  ['vs_20code_113',['VS Code',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1119',1,'']]],
  ['vs_20runtime_114',['Key Differences: Demos vs Runtime',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1356',1,'']]],
  ['vulnerability_20disagreement_115',['Example 1: Security Vulnerability Disagreement',['../md_docs_2conflict__resolution__examples.html#autotoc_md1052',1,'']]],
  ['vulnerability_20scan_116',['Dependency Vulnerability Scan',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1796',1,'']]]
];
