var searchData=
[
  ['e_20g_20cat_20eof_0',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['e_5fcblp_1',['e_cblp',['../structdos__header.html#a180329371c3c5509f05d4294d4266a53',1,'dos_header']]],
  ['e_5fcp_2',['e_cp',['../structdos__header.html#a55e887cd9cb9be3d67c2c4325a092873',1,'dos_header']]],
  ['e_5fcparhdr_3',['e_cparhdr',['../structdos__header.html#af94cfd88a7ec7235892b498f78647502',1,'dos_header']]],
  ['e_5fcrlc_4',['e_crlc',['../structdos__header.html#ab250b1bfedbf8ccb32aa46dab26726ae',1,'dos_header']]],
  ['e_5fcs_5',['e_cs',['../structdos__header.html#a83481d43e1af58d8cba1c51533b7d115',1,'dos_header']]],
  ['e_5fcsum_6',['e_csum',['../structdos__header.html#a54b3a79cb758a4dc44b1769c17e0ee0f',1,'dos_header']]],
  ['e_5fip_7',['e_ip',['../structdos__header.html#a2de4e696b5d56c68392c7c1fc0a4dd23',1,'dos_header']]],
  ['e_5flfarlc_8',['e_lfarlc',['../structdos__header.html#a1a7a97aa6d3f42ed56eacc5aa14d465f',1,'dos_header']]],
  ['e_5fmagic_9',['e_magic',['../structdos__header.html#aaea84e35472ecf5b61ccdf870156059f',1,'dos_header']]],
  ['e_5fmaxalloc_10',['e_maxalloc',['../structdos__header.html#a1ae043f12241c6bff9e1614277562d7e',1,'dos_header']]],
  ['e_5fminalloc_11',['e_minalloc',['../structdos__header.html#a5996f6524c7fa12d3d3a71016a9d546e',1,'dos_header']]],
  ['e_5fovno_12',['e_ovno',['../structdos__header.html#a19052ddf010264429cdb4d1afabdff0c',1,'dos_header']]],
  ['e_5fsp_13',['e_sp',['../structdos__header.html#afd49fa1a6618b22636a53b9d429b8bb3',1,'dos_header']]],
  ['e_5fss_14',['e_ss',['../structdos__header.html#a9135b825c12c08dc22d560a192a35b72',1,'dos_header']]],
  ['each_20agent_15',['When to Use Each Agent',['../md_README.html#autotoc_md913',1,'']]],
  ['each_20block_16',['Process each block',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['each_20block_20in_20order_17',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['edge_20case_20test_20suite_20test_5ftool_5frunner_5fedge_5fcases_20py_18',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1129',1,'']]],
  ['edge_20cases_20fixed_19',['Edge Cases Fixed',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1119',1,'']]],
  ['edge_20cases_20newly_20fixed_20_3a_20',['Edge Cases (newly fixed):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1134',1,'']]],
  ['effectiveness_21',['Effectiveness',['../md_workshop__benchmarks.html#autotoc_md1357',1,'Monitoring Effectiveness'],['../md_workshop__test__results.html#autotoc_md1463',1,'Test Effectiveness']]],
  ['efficiency_20analysis_22',['Token Efficiency Analysis',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1307',1,'']]],
  ['efficiency_20comparison_23',['Tool Efficiency Comparison',['../md_workshop__benchmarks.html#autotoc_md1359',1,'']]],
  ['emergency_20mailbox_24',['Emergency Mailbox',['../md_IMPROVEMENTS__FINAL.html#autotoc_md492',1,'']]],
  ['emergency_20mailbox_20✅_25',['Phase 8: Emergency Mailbox ✅',['../md_IMPROVEMENTS__README.html#autotoc_md551',1,'']]],
  ['emergency_5fmailbox_26',['emergency_mailbox',['../classaxe_1_1CollaborativeSession.html#a0dd9ab753e3e615c9ac6599ddd0b7858',1,'axe::CollaborativeSession']]],
  ['emergency_5fmailbox_2epy_27',['emergency_mailbox.py',['../emergency__mailbox_8py.html',1,'']]],
  ['emergency_5fmailbox_5fdir_28',['EMERGENCY_MAILBOX_DIR',['../namespacecore_1_1constants.html#a168da638d87daba5752732b52d9913e4',1,'core::constants']]],
  ['emergencymailbox_29',['EmergencyMailbox',['../classmanagers_1_1emergency__mailbox_1_1EmergencyMailbox.html',1,'managers::emergency_mailbox']]],
  ['emulation_30',['Emulation',['../md_README.html#autotoc_md922',1,'']]],
  ['enable_20in_20axe_20yaml_31',['Enable in axe.yaml',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md590',1,'']]],
  ['enabled_32',['Use Cases Enabled',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md36',1,'']]],
  ['enabled_33',['enabled',['../classcore_1_1github__agent_1_1GitHubAgent.html#a168eb32e18fb2b942f219e047f178a5f',1,'core.github_agent.GitHubAgent.enabled'],['../classcore_1_1sandbox_1_1SandboxManager.html#a40c23ba39bac5884be01fc4b0a12d470',1,'core.sandbox.SandboxManager.enabled'],['../classutils_1_1rate__limiter_1_1RateLimiter.html#aef7fb7add502ec52347a9ec8f20b696c',1,'utils.rate_limiter.RateLimiter.enabled']]],
  ['enabling_20sandbox_20mode_34',['Enabling Sandbox Mode',['../md_SANDBOX.html#autotoc_md1034',1,'Enabling Sandbox Mode'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1071',1,'Enabling Sandbox Mode']]],
  ['encouraging_20good_20behavior_35',['Encouraging Good Behavior',['../md_QUICK__REFERENCE.html#autotoc_md854',1,'']]],
  ['end_36',['END',['../classutils_1_1formatting_1_1Colors.html#af740df9b972fe9d4b9e14b1176484339',1,'utils::formatting::Colors']]],
  ['endpoints_20summary_37',['API Endpoints Summary',['../md_API__PROVIDERS.html#autotoc_md153',1,'']]],
  ['engine_38',['Engine',['../md_workshop__dependency__validation.html#autotoc_md1367',1,'angr (Symbolic Execution Engine)'],['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine'],['../md_workshop__dependency__validation.html#autotoc_md1372',1,'sqlite3 (Database Engine)']]],
  ['engine_20✅_39',['AXE - Agent eXecution Engine ✅',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'']]],
  ['engineering_20a_20wad_20file_40',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['engineering_20expert_41',['Reverse Engineering Expert',['../md_skills_2reverse__engineering__expert.html',1,'']]],
  ['engineering_20tools_42',['Reverse Engineering Tools',['../md__8collab__env.html#autotoc_md4',1,'']]],
  ['enhanced_20documentation_43',['2. Enhanced Documentation',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md406',1,'']]],
  ['enhanced_20reasoning_20✅_44',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md75',1,'']]],
  ['enhancement_20implementation_20complete_20✅_45',['AXE Enhancement Implementation - Complete ✅',['../md_IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['enhancements_46',['Enhancements',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md95',1,'Future Enhancements'],['../md_ARCHITECTURE.html#autotoc_md167',1,'Future Enhancements'],['../md_BUG__FIX__SUMMARY.html#autotoc_md208',1,'Future Enhancements'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md355',1,'Future Enhancements'],['../md_SANDBOX.html#autotoc_md1057',1,'Future Enhancements'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1090',1,'Future Enhancements'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1313',1,'Future Enhancements'],['../md_workshop__security__audit.html#autotoc_md1445',1,'Future Enhancements'],['../md_workshop__test__results.html#autotoc_md1475',1,'Future Enhancements'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1499',1,'Future Enhancements'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1512',1,'Future Enhancements']]],
  ['entire_20block_20contains_20a_20heredoc_47',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['enumerate_5ffile_48',['enumerate_file',['../classworkshop_1_1plane_1_1PlaneEnumerator.html#a5b59f8b59266e8e020af58011ba17320',1,'workshop::plane::PlaneEnumerator']]],
  ['enumerate_5fproject_49',['enumerate_project',['../classworkshop_1_1plane_1_1PlaneEnumerator.html#ac3fcd149453031fc5c03323e9fedfde8',1,'workshop::plane::PlaneEnumerator']]],
  ['enumeratedsink_50',['EnumeratedSink',['../classworkshop_1_1plane_1_1EnumeratedSink.html',1,'workshop::plane']]],
  ['enumeratedsource_51',['EnumeratedSource',['../classworkshop_1_1plane_1_1EnumeratedSource.html',1,'workshop::plane']]],
  ['enumeration_52',['Enumeration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md752',1,'✅ VALIDATED - Plane (Source/Sink Enumeration)'],['../md_README.html#autotoc_md963',1,'Plane - Source/Sink Enumeration'],['../md_workshop__quick__reference.html#autotoc_md1404',1,'Plane - Source/Sink Enumeration']]],
  ['enumeration_20benchmarks_53',['Plane - Source/Sink Enumeration Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1352',1,'']]],
  ['enumeration_20coverage_54',['Enumeration Coverage',['../md_workshop__benchmarks.html#autotoc_md1354',1,'']]],
  ['environment_55',['Environment',['../md_AGENTS.html#autotoc_md42',1,'Development Environment'],['../md_workshop__benchmarks.html#autotoc_md1345',1,'Test Environment'],['../md_workshop__test__results.html#autotoc_md1449',1,'Test Environment']]],
  ['environment_20detection_56',['4. Environment Detection',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1067',1,'']]],
  ['environment_20restrictions_57',['Environment Restrictions',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1079',1,'']]],
  ['environment_20setup_58',['Environment Setup',['../md_MODELS__FINAL.html#autotoc_md618',1,'']]],
  ['environment_20summary_59',['Environment Summary',['../md__8collab__env.html',1,'']]],
  ['environment_20validation_60',['Test Environment Validation',['../md_workshop__test__results.html#autotoc_md1470',1,'']]],
  ['environment_20variable_61',['Environment Variable',['../md_API__PROVIDERS.html#autotoc_md110',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md118',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md128',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md137',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md146',1,'Environment Variable']]],
  ['environment_20variables_20summary_62',['Environment Variables Summary',['../md_API__PROVIDERS.html#autotoc_md152',1,'']]],
  ['environment_5fprobe_2epy_63',['environment_probe.py',['../environment__probe_8py.html',1,'']]],
  ['environment_5fprobe_5fconfig_64',['environment_probe_config',['../classcore_1_1session__preprocessor_1_1SessionPreprocessor.html#a176dab18fe842a0a09b8cb17c196ce96',1,'core::session_preprocessor::SessionPreprocessor']]],
  ['environmentprobe_65',['EnvironmentProbe',['../classcore_1_1environment__probe_1_1EnvironmentProbe.html',1,'core::environment_probe']]],
  ['eof_66',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['error_67',['No Credits Error',['../md_MODELS__FINAL.html#autotoc_md662',1,'']]],
  ['error_20analysis_68',['Error Analysis',['../md_workshop__test__results.html#autotoc_md1467',1,'']]],
  ['error_20critical_69',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md460',1,'']]],
  ['error_20detection_20metrics_70',['Diff-Based Error Detection Metrics',['../md_IMPROVEMENTS__FINAL.html#autotoc_md488',1,'']]],
  ['error_20fixed_20✓_71',['1. Anthropic SDK Error Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md347',1,'']]],
  ['error_20handling_72',['Error Handling',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md305',1,'']]],
  ['error_20handling_20robust_73',['Error Handling - ROBUST',['../md_PR23__VALIDATION__REPORT.html#autotoc_md795',1,'']]],
  ['error_20messages_74',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['error_20recovery_75',['Error Recovery',['../md_workshop__dependency__validation.html#autotoc_md1393',1,'Error Recovery'],['../md_workshop__security__audit.html#autotoc_md1431',1,'Finding #2: Limited Error Recovery']]],
  ['error_3a_76',['&quot;Sandbox execution error: ...&quot;',['../md_SANDBOX.html#autotoc_md1052',1,'']]],
  ['error_5fthreshold_5fpercent_77',['ERROR_THRESHOLD_PERCENT',['../namespacecore_1_1constants.html#aa4776b3cf6771f5921023c231d1fae6d',1,'core::constants']]],
  ['errors_78',['Path Errors?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1525',1,'']]],
  ['errors_20413_20not_20handled_20✅_79',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['errors_20inside_20sandbox_80',['&quot;Permission denied&quot; errors inside sandbox',['../md_SANDBOX.html#autotoc_md1054',1,'']]],
  ['escalate_20properly_81',['3. Chain of Command – Escalate Properly',['../md_IMPROVEMENTS__FINAL.html#autotoc_md527',1,'']]],
  ['estimate_5fcost_82',['estimate_cost',['../namespaceutils_1_1token__stats.html#a54a42760c488a25025c244562ac9500b',1,'utils::token_stats']]],
  ['estimate_5ftoken_5fcount_83',['estimate_token_count',['../namespacetest__efficiency__analysis.html#a6fca3b5bf54437dbd2d9986142f1931c',1,'test_efficiency_analysis']]],
  ['estimate_5ftoken_5fsavings_84',['estimate_token_savings',['../namespaceutils_1_1context__optimizer.html#ac536fec2687fa7bfe77048815fcf5107',1,'utils::context_optimizer']]],
  ['estimate_5ftokens_85',['estimate_tokens',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#a805441baae1756d437100197a4485951',1,'core.anthropic_features.AnthropicFeatures.estimate_tokens()'],['../namespacebenchmark__acp.html#a0d2edd8caa4f70efabefa35938f79e35',1,'benchmark_acp.estimate_tokens()']]],
  ['estimatelength_86',['estimateLength',['../depklite_8c.html#a0ba3adf2d91169675b5f216a301d9da4',1,'depklite.c']]],
  ['estimates_87',['Estimates',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1154',1,'Token Savings Estimates'],['../md_skills_2build.html#autotoc_md1168',1,'Token Savings Estimates']]],
  ['estimates_20✅_88',['3. Token Counting (Precise Estimates) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md76',1,'']]],
  ['etc_20if_20tools_20expand_89',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['evidence_20from_20live_20testing_90',['Evidence from Live Testing',['../md_FIXES__SUMMARY.html#autotoc_md382',1,'']]],
  ['evidence_20of_20the_20problem_91',['Evidence of the Problem',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md19',1,'']]],
  ['example_92',['Example',['../md_API__PROVIDERS.html#autotoc_md130',1,'Chat-style cURL Example'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1070',1,'Configuration Example'],['../md_API__PROVIDERS.html#autotoc_md111',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md119',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md129',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md138',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md147',1,'cURL Example'],['../md_AGENTS.html#autotoc_md51',1,'Example'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md256',1,'Example'],['../md_MODELS__FINAL.html#autotoc_md657',1,'Model Communication Example'],['../md_API__PROVIDERS.html#autotoc_md112',1,'Python Example'],['../md_API__PROVIDERS.html#autotoc_md120',1,'Python Example'],['../md_API__PROVIDERS.html#autotoc_md131',1,'Python Example'],['../md_skills_2claude__build.html#autotoc_md1228',1,'Security Audit Workflow Example'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md249',1,'Token Savings Example']]],
  ['example_201_3a_20c_20project_20with_20cmake_93',['Example 1: C++ Project with CMake',['../md_skills_2build.html#autotoc_md1191',1,'']]],
  ['example_201_3a_20claude_20s_20natural_20format_94',['Example 1: Claude&apos;s Natural Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md683',1,'']]],
  ['example_201_3a_20default_20sandbox_20mode_95',['Example 1: Default Sandbox Mode',['../md_SANDBOX.html#autotoc_md1037',1,'']]],
  ['example_201_3a_20gpt_20building_20c_20project_96',['Example 1: GPT Building C++ Project',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1157',1,'']]],
  ['example_201_3a_20no_20duplicate_20execution_97',['Example 1: No Duplicate Execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md328',1,'']]],
  ['example_202_3a_20claude_20security_20audit_98',['Example 2: Claude Security Audit',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1158',1,'']]],
  ['example_202_3a_20code_20block_20format_99',['Example 2: Code Block Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md684',1,'']]],
  ['example_202_3a_20heredoc_20preserved_100',['Example 2: Heredoc Preserved',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md329',1,'']]],
  ['example_202_3a_20java_20project_20with_20maven_101',['Example 2: Java Project with Maven',['../md_skills_2build.html#autotoc_md1194',1,'']]],
  ['example_202_3a_20restricted_20sandbox_20with_20blacklist_102',['Example 2: Restricted Sandbox with Blacklist',['../md_SANDBOX.html#autotoc_md1038',1,'']]],
  ['example_203_3a_20axe_20native_20format_103',['Example 3: AXE Native Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md685',1,'']]],
  ['example_203_3a_20backward_20compatibility_104',['Example 3: Backward Compatibility',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md331',1,'']]],
  ['example_203_3a_20multi_20agent_20collaboration_105',['Example 3: Multi-Agent Collaboration',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1161',1,'']]],
  ['example_203_3a_20network_20isolated_20sandbox_106',['Example 3: Network-Isolated Sandbox',['../md_SANDBOX.html#autotoc_md1039',1,'']]],
  ['example_203_3a_20python_20project_20with_20make_107',['Example 3: Python Project with Make',['../md_skills_2build.html#autotoc_md1197',1,'']]],
  ['example_204_3a_20multi_20agent_20collaboration_108',['Example 4: Multi-Agent Collaboration',['../md_skills_2build.html#autotoc_md1200',1,'']]],
  ['example_20before_20vs_20after_109',['Example - Before vs After',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md411',1,'']]],
  ['example_20images_110',['Vision Example (Images)',['../md_API__PROVIDERS.html#autotoc_md121',1,'']]],
  ['example_20of_20duplicate_20execution_20before_20fix_111',['Example of Duplicate Execution (Before Fix)',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'']]],
  ['example_20openai_20sdk_112',['Example OpenAI SDK',['../md_API__PROVIDERS.html#autotoc_md139',1,'Python Example (OpenAI SDK)'],['../md_API__PROVIDERS.html#autotoc_md148',1,'Python Example (OpenAI SDK)']]],
  ['example_20output_113',['Example Output',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md251',1,'Example Output'],['../md_README.html#autotoc_md948',1,'Example Output']]],
  ['example_20session_114',['Example Session',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md304',1,'']]],
  ['example_20skill_20template_115',['Example Skill Template',['../md_AGENTS.html#autotoc_md56',1,'']]],
  ['example_20workflow_20savings_116',['Example Workflow Savings',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md270',1,'']]],
  ['example_3a_20multi_20agent_20code_20analysis_117',['Example: Multi-Agent Code Analysis',['../md_README.html#autotoc_md899',1,'']]],
  ['example_3a_20reverse_20engineering_20a_20wad_20file_118',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['example_3a_20security_20audit_20workflow_119',['Real-World Example: Security Audit Workflow',['../md_README.html#autotoc_md972',1,'']]],
  ['example_5fextended_5fthinking_120',['example_extended_thinking',['../namespaceanthropic__features__demo.html#ab2e39b6a9072090bfe008755bdfaf535',1,'anthropic_features_demo']]],
  ['example_5fprompt_5fcaching_121',['example_prompt_caching',['../namespaceanthropic__features__demo.html#a92085a1d8fb488ebc175f97bfdf9f610',1,'anthropic_features_demo']]],
  ['examples_122',['Examples',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md327',1,'Examples'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md514',1,'Examples'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md682',1,'Examples'],['../md_skills_2build.html#autotoc_md1190',1,'Examples'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1481',1,'Examples'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md352',1,'Model Examples'],['../md_README.html#autotoc_md960',1,'Quick Examples'],['../md_IMPROVEMENTS__README.html#autotoc_md556',1,'Usage Examples'],['../md_MODELS__FINAL.html#autotoc_md655',1,'Usage Examples'],['../md_README.html#autotoc_md892',1,'Usage Examples'],['../md_SANDBOX.html#autotoc_md1036',1,'Usage Examples'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1156',1,'Usage Examples'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1310',1,'Usage Examples'],['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1341',1,'Usage Examples'],['../md_README.html#autotoc_md952',1,'Workflow Examples']]],
  ['excellent_123',['Code Structure - EXCELLENT',['../md_PR23__VALIDATION__REPORT.html#autotoc_md794',1,'']]],
  ['exclude_5fdirs_124',['exclude_dirs',['../classtools_1_1minifier_1_1Minifier.html#a2a7936ca1c128718218998425616af4e',1,'tools::minifier::Minifier']]],
  ['exclusively_20by_20axe_20py_20responseprocessor_125',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['exe_20unpackers_126',['DOS EXE Unpackers',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1339',1,'']]],
  ['exec_20blocks_127',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['exec_5flog_128',['exec_log',['../classcore_1_1tool__runner_1_1ToolRunner.html#acdd4a8cc75397bd8031234b497ff0091',1,'core::tool_runner::ToolRunner']]],
  ['execute_20each_20block_20in_20order_129',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['execute_5fparsed_5fcall_130',['execute_parsed_call',['../namespaceutils_1_1xml__tool__parser.html#aa150ac2b37ac7c5d29a193a6b9331ada',1,'utils::xml_tool_parser']]],
  ['execute_5fpush_131',['execute_push',['../classcore_1_1github__agent_1_1GitHubAgent.html#a63c00b98acb12c898c52b54b98dcfade',1,'core::github_agent::GitHubAgent']]],
  ['executed_132',['Executed',['../md_workshop__test__results.html#autotoc_md1451',1,'Test Files Executed'],['../md_workshop__security__audit.html#autotoc_md1439',1,'Test Scenarios Executed']]],
  ['executing_20high_133',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['executing_20tools_134',['Executing Tools',['../md_README.html#autotoc_md897',1,'']]],
  ['execution_135',['Execution',['../md_PR23__VALIDATION__REPORT.html#autotoc_md750',1,'✅ VALIDATED - Chisel (Symbolic Execution)'],['../md_SANDBOX.html#autotoc_md1029',1,'1. Default-Allow Execution'],['../md_README.html#autotoc_md961',1,'Chisel - Symbolic Execution'],['../md_workshop__quick__reference.html#autotoc_md1402',1,'Chisel - Symbolic Execution'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md328',1,'Example 1: No Duplicate Execution']]],
  ['execution_136',['to prevent duplicate execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md317',1,'']]],
  ['execution_20⚠️_20medium_137',['2. &lt;b&gt;Command Execution&lt;/b&gt; ⚠️ Medium',['../md_SECURITY__REPORT.html#autotoc_md1102',1,'']]],
  ['execution_20❌_20→_20✅_138',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md310',1,'']]],
  ['execution_20and_20heredoc_20parsing_20bug_20fixes_139',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['execution_20before_20fix_140',['Example of Duplicate Execution (Before Fix)',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'']]],
  ['execution_20benchmarks_141',['Chisel - Symbolic Execution Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1346',1,'']]],
  ['execution_20bug_20✅_142',['Bug 4: Double Execution Bug ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['execution_20engine_143',['angr (Symbolic Execution Engine)',['../md_workshop__dependency__validation.html#autotoc_md1367',1,'']]],
  ['execution_20engine_144',['eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['execution_20engine_20✅_145',['AXE - Agent eXecution Engine ✅',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'']]],
  ['execution_20error_3a_146',['&quot;Sandbox execution error: ...&quot;',['../md_SANDBOX.html#autotoc_md1052',1,'']]],
  ['execution_20fix_20implementation_20summary_147',['Heredoc Execution Fix - Implementation Summary',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['execution_20fix_20summary_148',['Heredoc Execution Fix Summary',['../md_HEREDOC__EXECUTION__FIX.html',1,'']]],
  ['execution_20logs_149',['Appendix A: Test Execution Logs',['../md_PR23__VALIDATION__REPORT.html#autotoc_md831',1,'']]],
  ['execution_20original_20version_20_3a_150',['Execution (original version):',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md414',1,'']]],
  ['execution_20results_151',['Workshop Tools Test Suite Execution Results',['../md_workshop__test__results.html',1,'']]],
  ['execution_20summary_152',['Execution Summary',['../md_workshop__test__results.html#autotoc_md1448',1,'Test Execution Summary'],['../md_workshop__test__results.html#autotoc_md1459',1,'Test Execution Summary']]],
  ['executive_20summary_153',['Executive Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md745',1,'Executive Summary'],['../md_SECURITY__REPORT.html#autotoc_md1098',1,'Executive Summary'],['../md_workshop__security__audit.html#autotoc_md1418',1,'Executive Summary'],['../md_PR23__EXECUTIVE__SUMMARY.html',1,'PR #23 Workshop Dynamic Analysis Framework - Executive Summary']]],
  ['exepack_154',['Then EXEPACK',['../md_skills_2dos__packer__detector.html#autotoc_md1270',1,'']]],
  ['exepack_5fheader_155',['exepack_header',['../structexepack__header.html',1,'']]],
  ['exepack_5fsignature_156',['EXEPACK_SIGNATURE',['../unpack_8c.html#afa2e9a07eba95966b1bac5907b834905',1,'unpack.c']]],
  ['exepack_5fsize_157',['exepack_size',['../structexepack__header.html#a49e4cbeb3d505d9c0938e7b8ecdbe267',1,'exepack_header']]],
  ['exhaustion_20in_20chisel_20analysis_158',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_workshop__security__audit.html#autotoc_md1424',1,'']]],
  ['existing_20code_159',['For Existing Code',['../md_REFACTORING__NOTES.html#autotoc_md1022',1,'']]],
  ['existing_20tests_160',['Existing Tests',['../md_FIXES__SUMMARY.html#autotoc_md375',1,'Existing Tests'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md397',1,'Existing Tests']]],
  ['existing_20tests_20verify_20no_20breakage_161',['Existing tests (verify no breakage)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1522',1,'']]],
  ['exists_162',['Only one present: use whichever exists',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md392',1,'']]],
  ['expand_163',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['expanded_164',['EXPANDED',['../md_README.html#autotoc_md905',1,'Build Analysis (EXPANDED!)'],['../md_README.html#autotoc_md904',1,'Workshop Commands (EXPANDED!)']]],
  ['expected_20behavior_165',['Expected Behavior',['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md216',1,'']]],
  ['expected_20benefits_166',['Expected Benefits',['../md_README.html#autotoc_md942',1,'Expected Benefits'],['../md_README.html#autotoc_md949',1,'Expected Benefits']]],
  ['experience_20level_20system_20✅_167',['Phase 3: Experience &amp;amp; Level System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md545',1,'']]],
  ['expert_168',['Expert',['../md_skills_2c__modernization__expert.html',1,'C Modernization Expert'],['../md_skills_2cpp__modernization__expert.html',1,'C++ Modernization Expert'],['../md_skills_2cpp__refactoring__expert.html',1,'C++ Refactoring Expert'],['../md_skills_2ida__pro__analysis__patterns.html',1,'IDA Pro / Decompiler Analysis Expert'],['../md_skills_2python__agent__expert.html',1,'Python Agent Expert'],['../md_skills_2reverse__engineering__expert.html',1,'Reverse Engineering Expert'],['../md_skills_2x86__assembly__expert.html',1,'x86 Assembly Analysis Expert']]],
  ['exploration_169',['1. New Codebase Exploration',['../md_README.html#autotoc_md953',1,'']]],
  ['exponential_170',['Progression Curve (Hybrid Linear/Exponential)',['../md_IMPROVEMENTS__FINAL.html#autotoc_md519',1,'']]],
  ['exported_20helper_20function_171',['4. Exported Helper Function',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md227',1,'']]],
  ['extend_20parse_5faxe_5fnative_5fblocks_20response_20commented_20out_172',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md318',1,'']]],
  ['extended_20thinking_173',['2. Extended Thinking',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md252',1,'']]],
  ['extended_20thinking_20enhanced_20reasoning_20✅_174',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md75',1,'']]],
  ['extended_20thinking_20not_20available_175',['Extended thinking not available',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md274',1,'']]],
  ['extensibility_176',['Extensibility',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1092',1,'']]],
  ['extensibility_20guide_177',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['extension_20points_178',['Extension Points',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md97',1,'Extension Points'],['../md_ARCHITECTURE.html#autotoc_md161',1,'Key Extension Points']]],
  ['extensions_179',['extensions',['../classaxe_1_1ProjectContext.html#ac5c5832f33934d640b6b337a8c42e697',1,'axe::ProjectContext']]],
  ['extract_20functions_20✅_180',['Phase 2: Extract Functions ✅',['../md_REFACTORING__NOTES.html#autotoc_md1004',1,'']]],
  ['extract_20large_20classes_181',['PR #2: Extract Large Classes',['../md_REFACTORING__NOTES.html#autotoc_md1019',1,'']]],
  ['extract_20session_20management_182',['PR #3: Extract Session Management',['../md_REFACTORING__NOTES.html#autotoc_md1020',1,'']]],
  ['extract_5fbuild_5ffiles_5fto_5fmemory_183',['extract_build_files_to_memory',['../namespacetools_1_1build__analyzer.html#aaca7acb4ee4ffc81aaadd176db622eeb',1,'tools::build_analyzer']]],
  ['extract_5fcritical_5fdirectives_184',['extract_critical_directives',['../classutils_1_1prompt__compressor_1_1PromptCompressor.html#a68496fd700eeaac8a761decfb9fbeffd',1,'utils::prompt_compressor::PromptCompressor']]]
];
