var searchData=
[
  ['i_0',['I',['../md_TODO.html#autotoc_md2227',1,'']]],
  ['i_20o_1',['Disk I/O',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1794',1,'']]],
  ['i_20want_20to_2',['I want to...',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1532',1,'']]],
  ['id_20case_3',['Model ID Case',['../md_docs_2features_2configuration.html#autotoc_md1189',1,'']]],
  ['id_20generation_4',['Issue #5: Weak Random ID Generation',['../md_docs_2workshop_2security-audit.html#autotoc_md1863',1,'']]],
  ['id_20rules_5',['ID Rules',['../md_docs_2features_2configuration.html#autotoc_md1172',1,'Model ID Rules'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1553',1,'Model ID Rules']]],
  ['ida_20pro_20decompiler_20analysis_20expert_6',['IDA Pro / Decompiler Analysis Expert',['../md_skills_2ida__pro__analysis__patterns.html',1,'']]],
  ['ida_5fpro_5fanalysis_5fpatterns_2emd_7',['ida_pro_analysis_patterns.md',['../ida__pro__analysis__patterns_8md.html',1,'']]],
  ['identified_20non_20blocking_8',['Minor Issues Identified (Non-Blocking)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md935',1,'']]],
  ['if_20all_20trials_20fail_9',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md2163',1,'']]],
  ['if_20critical_20issues_20found_20re_20run_20with_20full_20details_3a_10',['If critical issues found, re-run with full details:',['../md_skills_2claude__build.html#autotoc_md2109',1,'']]],
  ['if_20features_20are_20active_11',['Check if Features are Active',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1041',1,'']]],
  ['if_20issues_20detected_20re_20run_20with_20verbose_20output_3a_12',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md2112',1,'']]],
  ['if_20issues_20found_20re_20run_20with_20full_20details_3a_13',['If issues found, re-run with full details:',['../md_skills_2claude__build.html#autotoc_md2106',1,'']]],
  ['if_20issues_20found_20run_20full_20scan_3a_14',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md2118',1,'']]],
  ['if_20needed_15',['Create parent dirs if needed',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md403',1,'']]],
  ['if_20so_20treat_20the_20whole_20block_20as_20a_20single_20command_16',['If so, treat the whole block as a single command',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md258',1,'']]],
  ['if_20the_20entire_20block_20contains_20a_20heredoc_17',['Check if the entire block contains a heredoc',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md257',1,'']]],
  ['if_20tools_20expand_18',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md2162',1,'']]],
  ['ihead_19',['ihead',['../unlzexe_8c.html#ab6d1fca4cbd607c7359331a9e5032fd4',1,'unlzexe.c']]],
  ['image_20generation_20',['Usage - Image Generation',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md562',1,'']]],
  ['images_21',['Vision Example (Images)',['../md_docs_2api-providers.html#autotoc_md79',1,'']]],
  ['immediate_22',['Immediate',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1111',1,'']]],
  ['immediate_20actions_23',['Immediate Actions',['../md_docs_2workshop_2test-results.html#autotoc_md1909',1,'']]],
  ['immediate_20actions_20completed_24',['Immediate Actions (Completed)',['../md_docs_2workshop_2security-audit.html#autotoc_md1879',1,'']]],
  ['immediate_20same_20day_25',['Immediate (Same Day)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md858',1,'']]],
  ['immediately_26',['✅ &lt;b&gt;MERGE IMMEDIATELY&lt;/b&gt;',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md855',1,'']]],
  ['impact_27',['Impact',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md133',1,'Impact'],['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md207',1,'Impact'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md269',1,'Impact'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md315',1,'Impact'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md335',1,'Impact'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md599',1,'Impact'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md783',1,'Impact'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md846',1,'Integration Impact'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md296',1,'Performance Impact'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md674',1,'Performance Impact'],['../md_docs_2features_2anthropic-features.html#autotoc_md1151',1,'Performance Impact'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md154',1,'Real-World Impact']]],
  ['impact_20after_20fix_28',['Impact After Fix',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md237',1,'']]],
  ['impact_20analysis_29',['Performance Impact Analysis',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1791',1,'']]],
  ['impact_20before_20fix_30',['Impact Before Fix',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md223',1,'']]],
  ['implementation_31',['Implementation',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md422',1,'Implementation'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md427',1,'Implementation'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md587',1,'Implementation'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'Multi-Format Tool Call Parser Implementation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md870',1,'Part 1: PR Claims vs. Actual Implementation'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md166',1,'Ready for Implementation']]],
  ['implementation_20approach_32',['Implementation Approach',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md621',1,'']]],
  ['implementation_20axe_20py_33',['1. Core Implementation (axe.py)',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1612',1,'']]],
  ['implementation_20complete_20✅_34',['Implementation Complete ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html',1,'AXE Enhancement Implementation - Complete ✅'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1325',1,'Implementation Complete ✅']]],
  ['implementation_20details_35',['Implementation Details',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md508',1,'Implementation Details'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md647',1,'Implementation Details'],['../md_docs_2codex-implementation.html#autotoc_md1010',1,'Implementation Details'],['../md_docs_2features_2write-blocks.html#autotoc_md1294',1,'Implementation Details'],['../md_docs_2privilege__mapping.html#autotoc_md1477',1,'Implementation Details'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md754',1,'Technical Implementation Details']]],
  ['implementation_20guide_36',['Implementation Guide',['../md_docs_2global-workspace.html',1,'Global Workspace - Implementation Guide'],['../md_docs_2codex-implementation.html',1,'GPT-5.2 Codex Implementation Guide']]],
  ['implementation_20notes_37',['Implementation Notes',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md711',1,'']]],
  ['implementation_20priority_38',['Implementation Priority',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md472',1,'']]],
  ['implementation_20status_3a_20✅_20complete_39',['Implementation Status: ✅ COMPLETE',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md142',1,'']]],
  ['implementation_20summaries_40',['Implementation Summaries (&lt;span class=&quot;tt&quot;&gt;implementation-summaries/&lt;/span&gt;)',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md962',1,'']]],
  ['implementation_20summaries_20implementation_20summaries_41',['Implementation Summaries (&lt;span class=&quot;tt&quot;&gt;implementation-summaries/&lt;/span&gt;)',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md962',1,'']]],
  ['implementation_20summaries_20index_42',['Implementation Summaries Index',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md971',1,'']]],
  ['implementation_20summary_43',['Implementation Summary',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'Agent Skills System Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'Anthropic Claude-Specific Optimizations - Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html',1,'AXE Multiagent Improvements - Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html',1,'Bubblewrap Sandbox Implementation - Summary'],['../md_docs_2REFACTOR__SUMMARY.html',1,'Configuration Refactor - Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html',1,'Database Location Fix - Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html',1,'Dynamic Max Output Tokens Implementation Summary'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html',1,'Global Workspace Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'Heredoc Execution Fix - Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html',1,'Shell Operator Support Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html',1,'Silent Builds Feature - Implementation Summary'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html',1,'Socket Interface Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html',1,'Source Code Minifier Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html',1,'WRITE Block Absolute Path Fix - Implementation Summary'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html',1,'XML Function Call Parser - Implementation Summary']]],
  ['implementation_20summary_3a_20gpt_205_20fix_20write_20blocks_44',['Implementation Summary: GPT-5 Fix &amp;amp; WRITE Blocks',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['implementation_5fcomplete_2emd_45',['IMPLEMENTATION_COMPLETE.md',['../IMPLEMENTATION__COMPLETE_8md.html',1,'']]],
  ['implementation_5fsummary_2emd_46',['IMPLEMENTATION_SUMMARY.md',['../IMPLEMENTATION__SUMMARY_8md.html',1,'']]],
  ['implemented_47',['Implemented',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md359',1,'✅ All Features Implemented'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md871',1,'Claim 1: Four Analysis Tools Implemented'],['../md_docs_2references_2quick-reference.html#autotoc_md1586',1,'Future Features (Not Yet Implemented)'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md743',1,'Key Features Implemented'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1329',1,'Key Features Implemented'],['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md214',1,'Solution Implemented'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md224',1,'Solution Implemented'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md341',1,'Solution Implemented'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md687',1,'Solution Implemented'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md717',1,'What Was Implemented']]],
  ['implemented_20features_48',['Implemented Features',['../md_README.html#autotoc_md2004',1,'Key Implemented Features'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md505',1,'Summary of All Implemented Features']]],
  ['implemented_20features_20alphabetical_49',['Implemented Features (Alphabetical)',['../md_TODO.html#autotoc_md2203',1,'']]],
  ['implemented_20features_20phases_201_205_50',['Implemented Features (Phases 1-5)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md479',1,'']]],
  ['implemented_20features_20phases_206_2010_51',['Implemented Features (Phases 6-10)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md485',1,'']]],
  ['implications_20for_20axe_20roadmap_52',['Implications for AXE Roadmap',['../md_docs_2SRI__AGENT__DISCUSSION.html#autotoc_md1680',1,'']]],
  ['imports_20✅_53',['Phase 3: Update Imports ✅',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md624',1,'']]],
  ['improved_20warning_20message_54',['2. Improved Warning Message',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1418',1,'']]],
  ['improvement_20—_20future_20work_55',['SRI (Self-Recursive Improvement) — Future Work',['../md_docs_2SRI__FUTURE__WORK.html',1,'']]],
  ['improvement_20reference_20guide_56',['AXE Multi-Agent System - Improvement Reference Guide',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html',1,'']]],
  ['improvement_20suggestions_57',['Improvement Suggestions',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html',1,'AXE Improvement Suggestions'],['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md980',1,'Concrete Improvement Suggestions']]],
  ['improvements_58',['Improvements',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md678',1,'Potential Improvements'],['../md_docs_2NAMESPACE__DETECTION.html',1,'User Namespace Detection and Safety Improvements']]],
  ['improvements_20implementation_20summary_59',['AXE Multiagent Improvements - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html',1,'']]],
  ['improvements_5ffinal_2emd_60',['IMPROVEMENTS_FINAL.md',['../IMPROVEMENTS__FINAL_8md.html',1,'']]],
  ['improvements_5freadme_2emd_61',['IMPROVEMENTS_README.md',['../IMPROVEMENTS__README_8md.html',1,'']]],
  ['in_20axe_62',['Anthropic Claude-Specific Features in AXE',['../md_docs_2features_2anthropic-features.html',1,'']]],
  ['in_20axe_20directory_63',['2. Agent Interactions in AXE Directory',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1517',1,'']]],
  ['in_20axe_20directory_20✅_64',['Test 5: Full Integration in AXE Directory ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1468',1,'']]],
  ['in_20axe_20runtime_65',['Integration Complete: Cognitive Architecture in AXE Runtime',['../md_docs_2INTEGRATION__COMPLETE.html',1,'']]],
  ['in_20axe_20sessions_66',['Using Cognitive Features in AXE Sessions',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1028',1,'']]],
  ['in_20axe_20user_20guide_67',['Cognitive Architecture in AXE - User Guide',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html',1,'']]],
  ['in_20axe_20yaml_68',['Enable in axe.yaml',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md519',1,'']]],
  ['in_20background_69',['1. Ollama Running in Background',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1516',1,'']]],
  ['in_20chisel_20analysis_70',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_docs_2workshop_2security-audit.html#autotoc_md1859',1,'']]],
  ['in_20ci_20cd_20security_20checks_71',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md2137',1,'']]],
  ['in_20cognitive_20architecture_72',['🧠 Built-in Cognitive Architecture',['../md_README.html#autotoc_md1995',1,'']]],
  ['in_20collab_20mode_73',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md183',1,'']]],
  ['in_20collab_20mode_20✅_74',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md304',1,'']]],
  ['in_20database_20operations_75',['Issue #4: Race Condition in Database Operations',['../md_docs_2workshop_2security-audit.html#autotoc_md1862',1,'']]],
  ['in_20error_20messages_76',['Issue #3: Information Disclosure in Error Messages',['../md_docs_2workshop_2security-audit.html#autotoc_md1861',1,'']]],
  ['in_20hammer_20module_77',['Issue #1: Potential Command Injection in Hammer Module',['../md_docs_2workshop_2security-audit.html#autotoc_md1858',1,'']]],
  ['in_20one_20response_78',['4. Multiple Files in One Response',['../md_docs_2features_2write-blocks.html#autotoc_md1285',1,'']]],
  ['in_20order_79',['Execute each block in order',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md399',1,'']]],
  ['in_20real_20environment_80',['Testing in Real Environment',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1460',1,'']]],
  ['in_20run_20method_81',['1. Defensive Programming in &lt;span class=&quot;tt&quot;&gt;run()&lt;/span&gt; Method',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md342',1,'']]],
  ['in_20runtime_82',['3. Features Available in Runtime',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1348',1,'']]],
  ['in_20security_20audits_83',['Token Savings in Security Audits',['../md_skills_2claude__build.html#autotoc_md2130',1,'']]],
  ['in_20session_20commands_84',['In-Session Commands',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1593',1,'']]],
  ['in_20subdirectory_85',['3. File in Subdirectory',['../md_docs_2features_2write-blocks.html#autotoc_md1284',1,'']]],
  ['in_20the_20axe_20context_86',['What Is SRI in the AXE Context?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1684',1,'']]],
  ['in_20unrestricted_20mode_20but_20not_20sandbox_20mode_87',['Commands work in unrestricted mode but not sandbox mode',['../md_docs_2features_2sandbox.html#autotoc_md1272',1,'']]],
  ['included_20by_20accident_88',['included by accident',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md191',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['increased_20for_20maximum_20shared_20view_89',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['increment_5fturn_90',['increment_turn',['../classcore_1_1arbitration_1_1ArbitrationProtocol.html#a5e1ec6db69c8436febdc6404d989f8ba',1,'core::arbitration::ArbitrationProtocol']]],
  ['independence_91',['Module Independence',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md630',1,'']]],
  ['index_92',['Index',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1523',1,'📚 Documentation Index'],['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md971',1,'Implementation Summaries Index'],['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md972',1,'PR Reports Index'],['../md_llm__prep_2codebase__overview.html#autotoc_md1969',1,'Symbol Index']]],
  ['index_93',['Sample file index',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2192',1,'']]],
  ['indirect_5fflow_5fhunter_94',['indirect_flow_hunter',['../md_skills_2indirect__flow__hunter.html',1,'']]],
  ['indirect_5fflow_5fhunter_2emd_95',['indirect_flow_hunter.md',['../indirect__flow__hunter_8md.html',1,'']]],
  ['inf_96',['inf',['../unlzexe_8c.html#a71234cf87d5b69e75361edd77e1cfb13',1,'unlzexe.c']]],
  ['information_97',['More Information',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md813',1,'']]],
  ['information_20disclosure_20in_20error_20messages_98',['Issue #3: Information Disclosure in Error Messages',['../md_docs_2workshop_2security-audit.html#autotoc_md1861',1,'']]],
  ['informational_20findings_99',['Informational Findings',['../md_docs_2workshop_2security-audit.html#autotoc_md1864',1,'']]],
  ['infrastructure_100',['2. providers.yaml (Provider Infrastructure)',['../md_docs_2features_2configuration.html#autotoc_md1165',1,'']]],
  ['initbits_101',['initbits',['../unlzexe_8c.html#a88a8845e0edb63f4a80a773bb60d1a29',1,'unlzexe.c']]],
  ['initial_20silent_20build_102',['Phase 1: Initial Silent Build',['../md_skills_2claude__build.html#autotoc_md2120',1,'']]],
  ['initial_20state_103',['Initial State',['../md_docs_2conflict__resolution__examples.html#autotoc_md1068',1,'']]],
  ['inject_5fskills_5fto_5fprompt_104',['inject_skills_to_prompt',['../classcore_1_1skills__manager_1_1SkillsManager.html#a2173e7aed8615ebd15767803aeda17f8',1,'core::skills_manager::SkillsManager']]],
  ['injection_20in_20hammer_20module_105',['Issue #1: Potential Command Injection in Hammer Module',['../md_docs_2workshop_2security-audit.html#autotoc_md1858',1,'']]],
  ['inline_20comments_106',['3. Inline Comments',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md344',1,'']]],
  ['input_20size_20validation_107',['Finding #1: Missing Input Size Validation',['../md_docs_2workshop_2security-audit.html#autotoc_md1865',1,'']]],
  ['input_20validation_20verified_108',['Input Validation - VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md909',1,'']]],
  ['input_3a_109',['Input:',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md260',1,'']]],
  ['input_5fqueue_110',['input_queue',['../classcore_1_1multiprocess_1_1AgentWorkerProcess.html#a9e9a0778b61261b93ace3b0fcb47119a',1,'core::multiprocess::AgentWorkerProcess']]],
  ['input_5fqueues_111',['input_queues',['../classcore_1_1multiprocess_1_1MultiAgentCoordinator.html#a61e5ea0f40f3827471dccafab1c09261',1,'core::multiprocess::MultiAgentCoordinator']]],
  ['inside_20interactive_20mode_112',['Section 8 – &lt;span class=&quot;tt&quot;&gt;/collab&lt;/span&gt; Inside Interactive Mode',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1399',1,'']]],
  ['inside_20sandbox_113',['&quot;Permission denied&quot; errors inside sandbox',['../md_docs_2features_2sandbox.html#autotoc_md1273',1,'']]],
  ['inspection_114',['Database Inspection',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md497',1,'']]],
  ['install_20dependencies_20silently_115',['Install dependencies silently',['../md_skills_2build.html#autotoc_md2089',1,'']]],
  ['install_20tl_20dr_116',['Quick Install (TL;DR)',['../md_README.html#autotoc_md1999',1,'']]],
  ['installation_117',['Installation',['../md_docs_2TESTING.html#autotoc_md1732',1,'Dependency Installation'],['../md_AGENTS.html#autotoc_md21',1,'Installation'],['../md_docs_2ollama-guide.html#autotoc_md1436',1,'Installation']]],
  ['installation_20required_118',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1117',1,'']]],
  ['installation_20testing_119',['Automated Installation Testing',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1789',1,'']]],
  ['installation_20validation_120',['Installation Validation',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1788',1,'']]],
  ['instructions_121',['Build Instructions',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md2254',1,'']]],
  ['instrument_5fprocess_122',['instrument_process',['../classworkshop_1_1hammer_1_1HammerInstrumentor.html#acb37c7042f0b40915e6b0e19610b994c',1,'workshop::hammer::HammerInstrumentor']]],
  ['instrument_5fscript_123',['instrument_script',['../classworkshop_1_1hammer_1_1HammerInstrumentor.html#acbb48087ecc8ff4ed7dfc5895661c6de',1,'workshop::hammer::HammerInstrumentor']]],
  ['instrumentation_124',['Instrumentation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md875',1,'✅ VALIDATED - Hammer (Live Instrumentation)'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1831',1,'&lt;b&gt;Hammer&lt;/b&gt; (Live Instrumentation)'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1815',1,'Hammer - Live Instrumentation']]],
  ['instrumentation_20benchmarks_125',['Hammer - Live Instrumentation Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1765',1,'']]],
  ['instrumentation_20framework_126',['frida-python (Instrumentation Framework)',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1778',1,'']]],
  ['instrumentation_20performance_127',['Process Instrumentation Performance',['../md_docs_2workshop_2benchmarks.html#autotoc_md1766',1,'']]],
  ['integrated_3a_128',['What&apos;s Integrated:',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1026',1,'']]],
  ['integration_129',['Integration',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md820',1,'✅ Complete AXE Integration'],['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md992',1,'6. Reverse-Engineering Workflow — dumpexe Integration'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md877',1,'Claim 2: Database Integration'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md881',1,'Claim 3: XP System Integration'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md885',1,'Claim 4: Configuration Integration'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1820',1,'Database Integration'],['../md_docs_2features_2github-agent-integration.html',1,'GitHub Agent Integration'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md516',1,'Integration'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1376',1,'Integration'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1339',1,'Next Steps (Integration)'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1101',1,'Ollama Integration'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1345',1,'Proof of Integration'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1621',1,'REPL Integration'],['../md_docs_2conflict__resolution__examples.html#autotoc_md1081',1,'Session Rules Integration'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1040',1,'Verifying Integration']]],
  ['integration_209_2010_130',['🔧 Integration (9/10)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md826',1,'']]],
  ['integration_20axe_20py_131',['1. Code Integration (axe.py)',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1346',1,'']]],
  ['integration_20challenges_20resolved_132',['Integration Challenges Resolved',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1088',1,'']]],
  ['integration_20complete_133',['Integration COMPLETE',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md904',1,'Configuration Integration - COMPLETE'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md902',1,'Database Integration - COMPLETE'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md903',1,'XP System Integration - COMPLETE']]],
  ['integration_20complete_3a_20cognitive_20architecture_20in_20axe_20runtime_134',['Integration Complete: Cognitive Architecture in AXE Runtime',['../md_docs_2INTEGRATION__COMPLETE.html',1,'']]],
  ['integration_20core_20tool_5frunner_20py_135',['2. Tool Runner Integration (&lt;span class=&quot;tt&quot;&gt;core/tool_runner.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1916',1,'']]],
  ['integration_20demo_136',['Comprehensive Integration Demo',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1100',1,'']]],
  ['integration_20distributed_20ai_137',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md59',1,'']]],
  ['integration_20guide_138',['Ollama Integration Guide',['../md_docs_2ollama-guide.html',1,'']]],
  ['integration_20impact_139',['Integration Impact',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md846',1,'']]],
  ['integration_20in_20axe_20directory_20✅_140',['Test 5: Full Integration in AXE Directory ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1468',1,'']]],
  ['integration_20local_20models_141',['Ollama Integration (Local Models)',['../md_ARCHITECTURE.html#autotoc_md58',1,'']]],
  ['integration_20md_142',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2github-agent-integration.html&quot;&gt;github-agent-integration.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1240',1,'']]],
  ['integration_20md_20github_20agent_20integration_20md_143',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2github-agent-integration.html&quot;&gt;github-agent-integration.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1240',1,'']]],
  ['integration_20points_20summary_144',['Part 8: Integration Points Summary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md930',1,'']]],
  ['integration_20ready_145',['Integration Ready',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1334',1,'']]],
  ['integration_20status_146',['Integration Status',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md932',1,'Integration Status'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1025',1,'Integration Status']]],
  ['integration_20test_147',['Ollama Integration Test',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1358',1,'']]],
  ['integration_20test_20results_148',['Integration Test Results',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md155',1,'Integration Test Results'],['../md_docs_2OLLAMA__TEST__RESULTS.html',1,'Ollama Integration Test Results']]],
  ['integration_20test_20results_20test_5fworkshop_5fintegration_20py_149',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1890',1,'']]],
  ['integration_20test_20test_5fintegration_5fdatabase_5ffix_20py_150',['Integration Test (&lt;span class=&quot;tt&quot;&gt;test_integration_database_fix.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md232',1,'']]],
  ['integration_20testing_151',['Integration Testing',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1798',1,'']]],
  ['integration_20tests_152',['Test File 2: Integration Tests',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md899',1,'']]],
  ['integration_20tests_20passed_153',['✅ Integration Tests Passed',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md371',1,'']]],
  ['integration_20verification_154',['Part 2: Integration Verification',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md901',1,'']]],
  ['integration_20with_20agentmanager_155',['6. Integration with AgentManager',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md751',1,'']]],
  ['integration_20with_20agents_156',['Integration with Agents',['../md_docs_2workshop_2quick-reference.html#autotoc_md1824',1,'']]],
  ['integration_20with_20agents_20md_157',['Integration with AGENTS.md',['../md_skills_2claude__build.html#autotoc_md2141',1,'']]],
  ['integration_20with_20axe_158',['Integration with AXE',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md731',1,'Integration with AXE'],['../md_docs_2xp__voting.html#autotoc_md1959',1,'Integration with AXE']]],
  ['integration_20with_20axe_20yaml_159',['Integration with axe.yaml',['../md_skills_2build.html#autotoc_md2069',1,'']]],
  ['integration_20with_20collaborations_160',['Integration with Collaborations',['../md_skills_2build.html#autotoc_md2070',1,'']]],
  ['integration_20with_20collaborative_20sessions_161',['Integration with Collaborative Sessions',['../md_docs_2global-workspace.html#autotoc_md1315',1,'']]],
  ['integration_20with_20globalworkspace_162',['Integration with GlobalWorkspace',['../md_docs_2subsumption__architecture.html#autotoc_md1720',1,'']]],
  ['integration_20with_20other_20blocks_163',['Integration with Other Blocks',['../md_docs_2features_2write-blocks.html#autotoc_md1286',1,'']]],
  ['integration_20with_20other_20systems_164',['Integration with Other Systems',['../md_docs_2conflict__resolution__examples.html#autotoc_md1078',1,'']]],
  ['integration_3a_20axe_20py_165',['Integration: &lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;',['../md_docs_2privilege__mapping.html#autotoc_md1480',1,'']]],
  ['integration_5fcomplete_2emd_166',['INTEGRATION_COMPLETE.md',['../INTEGRATION__COMPLETE_8md.html',1,'']]],
  ['integrity_167',['Test Data Integrity',['../md_docs_2workshop_2test-results.html#autotoc_md1907',1,'']]],
  ['interaction_20flow_168',['Agent Interaction Flow',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1038',1,'']]],
  ['interactions_169',['Interactions',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1800',1,'Cross-Tool Interactions'],['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1513',1,'Test: Live Agent Interactions']]],
  ['interactions_20in_20axe_20directory_170',['2. Agent Interactions in AXE Directory',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1517',1,'']]],
  ['interactive_20commands_171',['Interactive Commands',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1375',1,'']]],
  ['interactive_20demo_172',['Run interactive demo',['../md_docs_2references_2quick-reference.html#autotoc_md1575',1,'']]],
  ['interactive_20gui_20tests_20with_20xvfb_173',['Running interactive/GUI tests with Xvfb',['../md_docs_2TESTING.html#autotoc_md1744',1,'']]],
  ['interactive_20mode_174',['Interactive Mode',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1922',1,'Interactive Mode'],['../md_README.html#autotoc_md2008',1,'Interactive Mode'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1399',1,'Section 8 – &lt;span class=&quot;tt&quot;&gt;/collab&lt;/span&gt; Inside Interactive Mode']]],
  ['interactive_20slash_20commands_175',['Section 7 – Interactive Slash Commands',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1397',1,'']]],
  ['interactive_20testing_176',['Interactive Testing',['../md_docs_2features_2write-blocks.html#autotoc_md1293',1,'']]],
  ['interactive_20testing_20results_20workspace_20commands_177',['Interactive Testing Results - Workspace Commands',['../md_docs_2INTERACTIVE__TEST__RESULTS.html',1,'']]],
  ['interactive_5ftest_5fresults_2emd_178',['INTERACTIVE_TEST_RESULTS.md',['../INTERACTIVE__TEST__RESULTS_8md.html',1,'']]],
  ['interface_179',['Interface',['../md_TODO.html#autotoc_md2246',1,'🔌 Unix Socket Interface'],['../md_docs_2features_2github-agent-integration.html#autotoc_md1199',1,'Review Interface'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1395',1,'Section 6 – Unix Socket Interface']]],
  ['interface_20for_20agent_20communication_180',['Unix Socket Interface for Agent Communication',['../md_docs_2socket__interface.html',1,'']]],
  ['interface_20implementation_20summary_181',['Socket Interface Implementation Summary',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['internal_20stripped_20version_20_3a_182',['Validation (internal, stripped version):',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md350',1,'']]],
  ['investigate_20verbose_183',['1. Start Silent, Investigate Verbose',['../md_skills_2claude__build.html#autotoc_md2132',1,'']]],
  ['investigation_20verbose_184',['Phase 3: Detailed Investigation (Verbose)',['../md_skills_2claude__build.html#autotoc_md2126',1,'']]],
  ['ipath_185',['ipath',['../unlzexe_8c.html#a863e2897ee772ec6d99baca957496865',1,'unlzexe.c']]],
  ['is_20axe_186',['What is AXE?',['../md_README.html#autotoc_md1989',1,'']]],
  ['is_20missing_20for_20full_20sri_187',['What Is Missing for Full SRI',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1692',1,'']]],
  ['is_20sacred_188',['1. Mission First – The Project / Task Is Sacred',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md462',1,'']]],
  ['is_20safe_189',['Why &lt;span class=&quot;tt&quot;&gt;--unshare-user-try&lt;/span&gt; is Safe',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1421',1,'']]],
  ['is_20sri_20in_20the_20axe_20context_190',['What Is SRI in the AXE Context?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1684',1,'']]],
  ['is_5fanthropic_5fmodel_191',['is_anthropic_model',['../namespacemodels_1_1metadata.html#a2c5be0de038b417bd4c9c156fca253b1',1,'models::metadata']]],
  ['is_5favailable_192',['is_available',['../classcore_1_1sandbox_1_1SandboxManager.html#ae0139e54ec4099aafd66e88ad6a2306f',1,'core::sandbox::SandboxManager']]],
  ['is_5fenabled_193',['is_enabled',['../classcore_1_1anthropic__features_1_1FilesAPIManager.html#ab869a3faaad1f8aeb4943f5d1d72134d',1,'core.anthropic_features.FilesAPIManager.is_enabled()'],['../classcore_1_1session__preprocessor_1_1SessionPreprocessor.html#ad00de885732a8826585771f29d25eeda',1,'core.session_preprocessor.SessionPreprocessor.is_enabled()']]],
  ['is_5ffiles_5fapi_5fenabled_194',['is_files_api_enabled',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#a9f391e07bb747b23ee1f490a5ceca240',1,'core::anthropic_features::AnthropicFeatures']]],
  ['is_5fgenuine_5ftask_5fcompletion_195',['is_genuine_task_completion',['../namespaceaxe.html#aed941049819dac642905b812e754e2fa',1,'axe']]],
  ['is_5fprompt_5fcaching_5fenabled_196',['is_prompt_caching_enabled',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#ae4cd2fc680f6eee97b78bf22a249bb50',1,'core::anthropic_features::AnthropicFeatures']]],
  ['is_5frunning_197',['is_running',['../classaxe_1_1CollaborativeSession.html#a17613664271470a880ce760a7a8ae835',1,'axe::CollaborativeSession']]],
  ['is_5fsafe_5ftar_5fmember_198',['is_safe_tar_member',['../namespacetools_1_1build__analyzer.html#a41726c547bb435a3ff3dccb41fc6e5d3',1,'tools::build_analyzer']]],
  ['is_5fsuppressed_199',['is_suppressed',['../classcore_1_1subsumption__layer_1_1SubsumptionController.html#ae9766daf799285ddfc9801f12bab9739',1,'core::subsumption_layer::SubsumptionController']]],
  ['is_5ftar_5farchive_200',['is_tar_archive',['../namespacetools_1_1build__analyzer.html#ad3c492d6e19c78b5a075cf2d226bcbd0',1,'tools::build_analyzer']]],
  ['is_5ftoken_5fcounting_5fenabled_201',['is_token_counting_enabled',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#a264f65c13464b92c1ee4945375adb5f9',1,'core::anthropic_features::AnthropicFeatures']]],
  ['is_5ftool_5fallowed_202',['is_tool_allowed',['../classcore_1_1tool__runner_1_1ToolRunner.html#abd254d33291077274c09bef339b4c6c2',1,'core::tool_runner::ToolRunner']]],
  ['is_5ftool_5fallowed_20cmd_3a_20str_20lines_201460_201542_203',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md693',1,'']]],
  ['is_5ftool_5fblacklisted_204',['is_tool_blacklisted',['../classcore_1_1sandbox_1_1SandboxManager.html#a2d7dce26ef10f64fb3e7b1c38ded9ae2',1,'core::sandbox::SandboxManager']]],
  ['isjapan_205',['isjapan',['../unlzexe_8c.html#ac31e4a877b09226400b2ca4aa48987c0',1,'unlzexe.c']]],
  ['iskanji_206',['iskanji',['../unlzexe_8c.html#adb31912976d1b01a9e2575a9fde9d4d2',1,'unlzexe.c']]],
  ['isolated_207',['Scenario 3: Network Isolated',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md672',1,'']]],
  ['isolated_20sandbox_208',['Example 3: Network-Isolated Sandbox',['../md_docs_2features_2sandbox.html#autotoc_md1258',1,'']]],
  ['isolation_209',['Isolation',['../md_docs_2features_2sandbox.html#autotoc_md1249',1,'2. Linux Namespace Isolation'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md652',1,'2. Namespace Isolation'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md833',1,'3. Database Test Isolation']]],
  ['issue_210',['The Issue',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md326',1,'']]],
  ['issue_201_3a_20gpt_205_20api_20parameter_20error_20critical_211',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md397',1,'']]],
  ['issue_201_3a_20potential_20command_20injection_20in_20hammer_20module_212',['Issue #1: Potential Command Injection in Hammer Module',['../md_docs_2workshop_2security-audit.html#autotoc_md1858',1,'']]],
  ['issue_201_3a_20read_20block_20access_20denied_213',['Issue 1: READ Block Access Denied',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md175',1,'']]],
  ['issue_201_3a_20read_20block_20access_20denied_20✅_214',['Issue 1: READ Block Access Denied ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md300',1,'']]],
  ['issue_202_3a_20llama_20405b_20model_20deprecated_215',['Issue 2: Llama 405B Model Deprecated',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md179',1,'']]],
  ['issue_202_3a_20llama_20405b_20model_20deprecated_20✅_216',['Issue 2: Llama 405B Model Deprecated ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md302',1,'']]],
  ['issue_202_3a_20memory_20exhaustion_20in_20chisel_20analysis_217',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_docs_2workshop_2security-audit.html#autotoc_md1859',1,'']]],
  ['issue_202_3a_20write_20blocks_20not_20executing_20high_218',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md398',1,'']]],
  ['issue_203_3a_20auto_20approve_20not_20default_20in_20collab_20mode_219',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md183',1,'']]],
  ['issue_203_3a_20auto_20approve_20not_20default_20in_20collab_20mode_20✅_220',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md304',1,'']]],
  ['issue_203_3a_20information_20disclosure_20in_20error_20messages_221',['Issue #3: Information Disclosure in Error Messages',['../md_docs_2workshop_2security-audit.html#autotoc_md1861',1,'']]],
  ['issue_204_3a_20agents_20confused_20about_20read_20write_20block_20syntax_222',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['issue_204_3a_20agents_20confused_20about_20read_20write_20block_20syntax_20✅_223',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md306',1,'']]],
  ['issue_204_3a_20race_20condition_20in_20database_20operations_224',['Issue #4: Race Condition in Database Operations',['../md_docs_2workshop_2security-audit.html#autotoc_md1862',1,'']]],
  ['issue_205_3a_20weak_20random_20id_20generation_225',['Issue #5: Weak Random ID Generation',['../md_docs_2workshop_2security-audit.html#autotoc_md1863',1,'']]],
  ['issues_226',['Issues',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html',1,'Bug Fix Summary - Multi-Agent Collaboration Issues'],['../md_docs_2api-providers.html#autotoc_md115',1,'Common Issues'],['../md_README.html#autotoc_md2048',1,'Contact &amp;amp; Issues'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1797',1,'Known Security Issues'],['../md_docs_2workshop_2security-audit.html#autotoc_md1860',1,'Low Severity Issues'],['../md_docs_2workshop_2security-audit.html#autotoc_md1857',1,'Medium Severity Issues'],['../md_docs_2ollama-guide.html#autotoc_md1447',1,'Performance Issues?']]],
  ['issues_227',['issues',['../md_skills_2claude__build.html#autotoc_md2124',1,'Cppcheck for C/C++ issues'],['../md_skills_2claude__build.html#autotoc_md2125',1,'Flawfinder for security issues']]],
  ['issues_20addressed_228',['Issues Addressed',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md592',1,'Code Review Issues Addressed'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1627',1,'Code Review Issues Addressed']]],
  ['issues_20detected_20re_20run_20with_20verbose_20output_3a_229',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md2112',1,'']]],
  ['issues_20fix_20summary_230',['AXE Multiple Issues Fix Summary',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html',1,'']]],
  ['issues_20fixed_231',['Issues Fixed',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md299',1,'']]],
  ['issues_20found_20re_20run_20with_20full_20details_3a_232',['issues found re run with full details:',['../md_skills_2claude__build.html#autotoc_md2109',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md2106',1,'If issues found, re-run with full details:']]],
  ['issues_20found_20run_20full_20scan_3a_233',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md2118',1,'']]],
  ['issues_20identified_20non_20blocking_234',['Minor Issues Identified (Non-Blocking)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md935',1,'']]],
  ['issues_20limitations_235',['Part 9: Known Issues &amp;amp; Limitations',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md934',1,'']]],
  ['issues_20non_20blocking_236',['Minor Issues (Non-Blocking)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md830',1,'']]],
  ['issues_20resolved_237',['Issues Resolved',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md396',1,'']]],
  ['issues_20silent_238',['Quick check for memory issues (silent)',['../md_skills_2claude__build.html#autotoc_md2105',1,'']]],
  ['it_20works_239',['It Works',['../md_docs_2features_2anthropic-features.html#autotoc_md1130',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1137',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1141',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1146',1,'How It Works'],['../md_docs_2xp__voting.html#autotoc_md1935',1,'How It Works']]],
  ['it_3a_240',['Where to Find It:',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1027',1,'']]],
  ['itob_241',['itob',['../depklite_8c.html#a746cee407a9dac3b866f8da6600581c5',1,'depklite.c']]]
];
