var searchData=
[
  ['i_20o_0',['Disk I/O',['../md_workshop__dependency__validation.html#autotoc_md1384',1,'']]],
  ['id_20generation_1',['Issue #5: Weak Random ID Generation',['../md_workshop__security__audit.html#autotoc_md1428',1,'']]],
  ['ida_20pro_20decompiler_20analysis_20expert_2',['IDA Pro / Decompiler Analysis Expert',['../md_skills_2ida__pro__analysis__patterns.html',1,'']]],
  ['ida_5fpro_5fanalysis_5fpatterns_2emd_3',['ida_pro_analysis_patterns.md',['../ida__pro__analysis__patterns_8md.html',1,'']]],
  ['identified_20non_20blocking_4',['Minor Issues Identified (Non-Blocking)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md813',1,'']]],
  ['if_20all_20trials_20fail_5',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['if_20critical_20issues_20found_20re_20run_20with_20full_20details_3a_6',['If critical issues found, re-run with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'']]],
  ['if_20issues_20detected_20re_20run_20with_20verbose_20output_3a_7',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['if_20issues_20found_20re_20run_20with_20full_20details_3a_8',['If issues found, re-run with full details:',['../md_skills_2claude__build.html#autotoc_md1215',1,'']]],
  ['if_20issues_20found_20run_20full_20scan_3a_9',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md1227',1,'']]],
  ['if_20needed_10',['Create parent dirs if needed',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md466',1,'']]],
  ['if_20so_20treat_20the_20whole_20block_20as_20a_20single_20command_11',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['if_20the_20entire_20block_20contains_20a_20heredoc_12',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['if_20tools_20expand_13',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['ihead_14',['ihead',['../unlzexe_8c.html#ab6d1fca4cbd607c7359331a9e5032fd4',1,'unlzexe.c']]],
  ['image_20generation_15',['Usage - Image Generation',['../md_MODELS__FINAL.html#autotoc_md644',1,'']]],
  ['images_16',['Vision Example (Images)',['../md_API__PROVIDERS.html#autotoc_md121',1,'']]],
  ['immediate_20actions_17',['Immediate Actions',['../md_workshop__test__results.html#autotoc_md1474',1,'']]],
  ['immediate_20actions_20completed_18',['Immediate Actions (Completed)',['../md_workshop__security__audit.html#autotoc_md1444',1,'']]],
  ['immediate_20same_20day_19',['Immediate (Same Day)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md736',1,'']]],
  ['immediately_20',['✅ &lt;b&gt;MERGE IMMEDIATELY&lt;/b&gt;',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md733',1,'']]],
  ['impact_21',['Impact',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md33',1,'Impact'],['../md_BUG__FIX__SUMMARY.html#autotoc_md205',1,'Impact'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md332',1,'Impact'],['../md_FIXES__SUMMARY.html#autotoc_md378',1,'Impact'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md398',1,'Impact'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md681',1,'Impact'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1333',1,'Impact'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md724',1,'Integration Impact'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md269',1,'Performance Impact'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md359',1,'Performance Impact'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1087',1,'Performance Impact'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md84',1,'Real-World Impact']]],
  ['impact_20after_20fix_22',['Impact After Fix',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md235',1,'']]],
  ['impact_20analysis_23',['Performance Impact Analysis',['../md_workshop__dependency__validation.html#autotoc_md1381',1,'']]],
  ['impact_20before_20fix_24',['Impact Before Fix',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md221',1,'']]],
  ['implementation_25',['Implementation',['../md_IMPROVEMENTS__FINAL.html#autotoc_md485',1,'Implementation'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md490',1,'Implementation'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md669',1,'Implementation'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'Multi-Format Tool Call Parser Implementation'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md748',1,'Part 1: PR Claims vs. Actual Implementation'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md96',1,'Ready for Implementation']]],
  ['implementation_20approach_26',['Implementation Approach',['../md_REFACTORING__NOTES.html#autotoc_md1002',1,'']]],
  ['implementation_20complete_20✅_27',['AXE Enhancement Implementation - Complete ✅',['../md_IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['implementation_20details_28',['Implementation Details',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md579',1,'Implementation Details'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1060',1,'Implementation Details'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1494',1,'Implementation Details'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1304',1,'Technical Implementation Details']]],
  ['implementation_20notes_29',['Implementation Notes',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1135',1,'']]],
  ['implementation_20priority_30',['Implementation Priority',['../md_IMPROVEMENTS__FINAL.html#autotoc_md535',1,'']]],
  ['implementation_20status_3a_20✅_20complete_31',['Implementation Status: ✅ COMPLETE',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md72',1,'']]],
  ['implementation_20summary_32',['Implementation Summary',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'Agent Skills System Implementation Summary'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'Anthropic Claude-Specific Optimizations - Implementation Summary'],['../md_IMPROVEMENTS__README.html',1,'AXE Multiagent Improvements - Implementation Summary'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html',1,'Bubblewrap Sandbox Implementation - Summary'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html',1,'Database Location Fix - Implementation Summary'],['../md_DYNAMIC__TOKENS__SUMMARY.html',1,'Dynamic Max Output Tokens Implementation Summary'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'Heredoc Execution Fix - Implementation Summary'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html',1,'Shell Operator Support Implementation Summary'],['../md_SILENT__BUILDS__IMPLEMENTATION.html',1,'Silent Builds Feature - Implementation Summary'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html',1,'Source Code Minifier Implementation Summary'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'WRITE Block Absolute Path Fix - Implementation Summary'],['../md_XML__PARSER__IMPLEMENTATION.html',1,'XML Function Call Parser - Implementation Summary']]],
  ['implementation_20summary_3a_20gpt_205_20fix_20write_20blocks_33',['Implementation Summary: GPT-5 Fix &amp;amp; WRITE Blocks',['../md_IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['implementation_5fcomplete_2emd_34',['IMPLEMENTATION_COMPLETE.md',['../IMPLEMENTATION__COMPLETE_8md.html',1,'']]],
  ['implementation_5fsummary_2emd_35',['IMPLEMENTATION_SUMMARY.md',['../IMPLEMENTATION__SUMMARY_8md.html',1,'']]],
  ['implemented_36',['Implemented',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md422',1,'✅ All Features Implemented'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md749',1,'Claim 1: Four Analysis Tools Implemented'],['../md_QUICK__REFERENCE.html#autotoc_md861',1,'Future Features (Not Yet Implemented)'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1293',1,'Key Features Implemented'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md212',1,'Solution Implemented'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md222',1,'Solution Implemented'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md404',1,'Solution Implemented'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1111',1,'Solution Implemented'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1141',1,'What Was Implemented']]],
  ['implemented_20features_37',['Summary of All Implemented Features',['../md_IMPROVEMENTS__README.html#autotoc_md568',1,'']]],
  ['implemented_20features_20phases_201_205_38',['Implemented Features (Phases 1-5)',['../md_IMPROVEMENTS__README.html#autotoc_md542',1,'']]],
  ['implemented_20features_20phases_206_2010_39',['Implemented Features (Phases 6-10)',['../md_IMPROVEMENTS__README.html#autotoc_md548',1,'']]],
  ['imports_20✅_40',['Phase 3: Update Imports ✅',['../md_REFACTORING__NOTES.html#autotoc_md1005',1,'']]],
  ['improvement_20reference_20guide_41',['AXE Multi-Agent System - Improvement Reference Guide',['../md_IMPROVEMENTS__FINAL.html',1,'']]],
  ['improvements_42',['Potential Improvements',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1091',1,'']]],
  ['improvements_20implementation_20summary_43',['AXE Multiagent Improvements - Implementation Summary',['../md_IMPROVEMENTS__README.html',1,'']]],
  ['improvements_5ffinal_2emd_44',['IMPROVEMENTS_FINAL.md',['../IMPROVEMENTS__FINAL_8md.html',1,'']]],
  ['improvements_5freadme_2emd_45',['IMPROVEMENTS_README.md',['../IMPROVEMENTS__README_8md.html',1,'']]],
  ['in_20axe_46',['Anthropic Claude-Specific Features in AXE',['../md_docs_2ANTHROPIC__FEATURES.html',1,'']]],
  ['in_20axe_20yaml_47',['Enable in axe.yaml',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md590',1,'']]],
  ['in_20chisel_20analysis_48',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_workshop__security__audit.html#autotoc_md1424',1,'']]],
  ['in_20ci_20cd_20security_20checks_49',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md1246',1,'']]],
  ['in_20collab_20mode_50',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['in_20collab_20mode_20✅_51',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['in_20database_20operations_52',['Issue #4: Race Condition in Database Operations',['../md_workshop__security__audit.html#autotoc_md1427',1,'']]],
  ['in_20error_20messages_53',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['in_20hammer_20module_54',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['in_20one_20response_55',['4. Multiple Files in One Response',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1485',1,'']]],
  ['in_20order_56',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['in_20run_20method_57',['1. Defensive Programming in &lt;span class=&quot;tt&quot;&gt;run()&lt;/span&gt; Method',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md405',1,'']]],
  ['in_20security_20audits_58',['Token Savings in Security Audits',['../md_skills_2claude__build.html#autotoc_md1239',1,'']]],
  ['in_20subdirectory_59',['3. File in Subdirectory',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1484',1,'']]],
  ['in_20whitelist_20mode_20but_20not_20sandbox_20mode_60',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['included_20by_20accident_61',['included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['increased_20for_20maximum_20shared_20view_62',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['independence_63',['Module Independence',['../md_REFACTORING__NOTES.html#autotoc_md1011',1,'']]],
  ['index_64',['Symbol Index',['../md_llm__prep_2codebase__overview.html#autotoc_md573',1,'']]],
  ['indexing_65',['3. Collaborative Session Pre-indexing',['../md_README.html#autotoc_md955',1,'']]],
  ['indirect_5fflow_5fhunter_66',['indirect_flow_hunter',['../md_skills_2indirect__flow__hunter.html',1,'']]],
  ['indirect_5fflow_5fhunter_2emd_67',['indirect_flow_hunter.md',['../indirect__flow__hunter_8md.html',1,'']]],
  ['inf_68',['inf',['../unlzexe_8c.html#a71234cf87d5b69e75361edd77e1cfb13',1,'unlzexe.c']]],
  ['information_69',['More Information',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1528',1,'']]],
  ['information_20disclosure_20in_20error_20messages_70',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['informational_20findings_71',['Informational Findings',['../md_workshop__security__audit.html#autotoc_md1429',1,'']]],
  ['initbits_72',['initbits',['../unlzexe_8c.html#a88a8845e0edb63f4a80a773bb60d1a29',1,'unlzexe.c']]],
  ['initial_20silent_20build_73',['Phase 1: Initial Silent Build',['../md_skills_2claude__build.html#autotoc_md1229',1,'']]],
  ['inject_5fskills_5fto_5fprompt_74',['inject_skills_to_prompt',['../classcore_1_1skills__manager_1_1SkillsManager.html#a2173e7aed8615ebd15767803aeda17f8',1,'core::skills_manager::SkillsManager']]],
  ['injection_20in_20hammer_20module_75',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['inline_20comments_76',['3. Inline Comments',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md407',1,'']]],
  ['input_20size_20validation_77',['Finding #1: Missing Input Size Validation',['../md_workshop__security__audit.html#autotoc_md1430',1,'']]],
  ['input_20validation_20verified_78',['Input Validation - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md787',1,'']]],
  ['input_3a_79',['Input:',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md323',1,'']]],
  ['input_5fqueue_80',['input_queue',['../classcore_1_1multiprocess_1_1AgentWorkerProcess.html#a9e9a0778b61261b93ace3b0fcb47119a',1,'core::multiprocess::AgentWorkerProcess']]],
  ['input_5fqueues_81',['input_queues',['../classcore_1_1multiprocess_1_1MultiAgentCoordinator.html#a61e5ea0f40f3827471dccafab1c09261',1,'core::multiprocess::MultiAgentCoordinator']]],
  ['inside_20sandbox_82',['&quot;Permission denied&quot; errors inside sandbox',['../md_SANDBOX.html#autotoc_md1054',1,'']]],
  ['inspection_83',['Database Inspection',['../md_IMPROVEMENTS__README.html#autotoc_md560',1,'']]],
  ['install_20dependencies_84',['Install Dependencies',['../md_README.html#autotoc_md878',1,'']]],
  ['install_20dependencies_20silently_85',['Install dependencies silently',['../md_skills_2build.html#autotoc_md1198',1,'']]],
  ['installation_86',['Installation',['../md_AGENTS.html#autotoc_md44',1,'Installation'],['../md_README.html#autotoc_md876',1,'Installation'],['../md_README.html#autotoc_md959',1,'Installation']]],
  ['installation_20required_87',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md282',1,'']]],
  ['installation_20testing_88',['Automated Installation Testing',['../md_workshop__dependency__validation.html#autotoc_md1379',1,'']]],
  ['installation_20validation_89',['Installation Validation',['../md_workshop__dependency__validation.html#autotoc_md1378',1,'']]],
  ['instructions_90',['Build Instructions',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1340',1,'']]],
  ['instrument_5fprocess_91',['instrument_process',['../classworkshop_1_1hammer_1_1HammerInstrumentor.html#acb37c7042f0b40915e6b0e19610b994c',1,'workshop::hammer::HammerInstrumentor']]],
  ['instrument_5fscript_92',['instrument_script',['../classworkshop_1_1hammer_1_1HammerInstrumentor.html#acbb48087ecc8ff4ed7dfc5895661c6de',1,'workshop::hammer::HammerInstrumentor']]],
  ['instrumentation_93',['Instrumentation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md753',1,'✅ VALIDATED - Hammer (Live Instrumentation)'],['../md_README.html#autotoc_md964',1,'Hammer - Live Instrumentation'],['../md_workshop__quick__reference.html#autotoc_md1405',1,'Hammer - Live Instrumentation']]],
  ['instrumentation_20benchmarks_94',['Hammer - Live Instrumentation Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1355',1,'']]],
  ['instrumentation_20framework_95',['frida-python (Instrumentation Framework)',['../md_workshop__dependency__validation.html#autotoc_md1368',1,'']]],
  ['instrumentation_20performance_96',['Process Instrumentation Performance',['../md_workshop__benchmarks.html#autotoc_md1356',1,'']]],
  ['integrated_20tools_97',['Integrated Tools',['../md_README.html#autotoc_md872',1,'']]],
  ['integration_98',['Integration',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md698',1,'✅ Complete AXE Integration'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md755',1,'Claim 2: Database Integration'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md759',1,'Claim 3: XP System Integration'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md763',1,'Claim 4: Configuration Integration'],['../md_README.html#autotoc_md970',1,'Database Integration'],['../md_workshop__quick__reference.html#autotoc_md1410',1,'Database Integration'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html',1,'GitHub Agent Integration'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md587',1,'Integration']]],
  ['integration_209_2010_99',['🔧 Integration (9/10)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md704',1,'']]],
  ['integration_20complete_100',['Integration COMPLETE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md782',1,'Configuration Integration - COMPLETE'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md780',1,'Database Integration - COMPLETE'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md781',1,'XP System Integration - COMPLETE']]],
  ['integration_20distributed_20ai_101',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md169',1,'']]],
  ['integration_20impact_102',['Integration Impact',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md724',1,'']]],
  ['integration_20local_20models_103',['Ollama Integration (Local Models)',['../md_ARCHITECTURE.html#autotoc_md168',1,'']]],
  ['integration_20points_20summary_104',['Part 8: Integration Points Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md808',1,'']]],
  ['integration_20status_105',['Integration Status',['../md_PR23__VALIDATION__REPORT.html#autotoc_md810',1,'']]],
  ['integration_20test_20results_106',['Integration Test Results',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md85',1,'']]],
  ['integration_20test_20results_20test_5fworkshop_5fintegration_20py_107',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1455',1,'']]],
  ['integration_20test_20test_5fintegration_5fdatabase_5ffix_20py_108',['Integration Test (&lt;span class=&quot;tt&quot;&gt;test_integration_database_fix.py&lt;/span&gt;)',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md230',1,'']]],
  ['integration_20testing_109',['Integration Testing',['../md_workshop__dependency__validation.html#autotoc_md1388',1,'']]],
  ['integration_20tests_110',['Test File 2: Integration Tests',['../md_PR23__VALIDATION__REPORT.html#autotoc_md777',1,'']]],
  ['integration_20tests_20passed_111',['✅ Integration Tests Passed',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md434',1,'']]],
  ['integration_20verification_112',['Part 2: Integration Verification',['../md_PR23__VALIDATION__REPORT.html#autotoc_md779',1,'']]],
  ['integration_20with_20agentmanager_113',['6. Integration with AgentManager',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1301',1,'']]],
  ['integration_20with_20agents_114',['Integration with Agents',['../md_README.html#autotoc_md951',1,'Integration with Agents'],['../md_README.html#autotoc_md969',1,'Integration with Agents'],['../md_workshop__quick__reference.html#autotoc_md1414',1,'Integration with Agents']]],
  ['integration_20with_20agents_20md_115',['Integration with AGENTS.md',['../md_skills_2claude__build.html#autotoc_md1250',1,'']]],
  ['integration_20with_20axe_116',['Integration with AXE',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1155',1,'']]],
  ['integration_20with_20axe_20yaml_117',['Integration with axe.yaml',['../md_skills_2build.html#autotoc_md1178',1,'']]],
  ['integration_20with_20collaborations_118',['Integration with Collaborations',['../md_skills_2build.html#autotoc_md1179',1,'']]],
  ['integration_20with_20other_20blocks_119',['Integration with Other Blocks',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1486',1,'']]],
  ['integrity_120',['Test Data Integrity',['../md_workshop__test__results.html#autotoc_md1472',1,'']]],
  ['interactions_121',['Cross-Tool Interactions',['../md_workshop__dependency__validation.html#autotoc_md1390',1,'']]],
  ['interactive_122',['Auto-Approve Mode (Non-Interactive)',['../md_README.html#autotoc_md927',1,'']]],
  ['interactive_20demo_123',['Run interactive demo',['../md_QUICK__REFERENCE.html#autotoc_md850',1,'']]],
  ['interactive_20mode_124',['Interactive Mode',['../md_README.html#autotoc_md893',1,'']]],
  ['interactive_20testing_125',['Interactive Testing',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1493',1,'']]],
  ['interface_126',['Review Interface',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md295',1,'']]],
  ['internal_20stripped_20version_20_3a_127',['Validation (internal, stripped version):',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md413',1,'']]],
  ['investigate_20verbose_128',['1. Start Silent, Investigate Verbose',['../md_skills_2claude__build.html#autotoc_md1241',1,'']]],
  ['investigation_20verbose_129',['Phase 3: Detailed Investigation (Verbose)',['../md_skills_2claude__build.html#autotoc_md1235',1,'']]],
  ['ipath_130',['ipath',['../unlzexe_8c.html#a863e2897ee772ec6d99baca957496865',1,'unlzexe.c']]],
  ['is_20sacred_131',['1. Mission First – The Project / Task Is Sacred',['../md_IMPROVEMENTS__FINAL.html#autotoc_md525',1,'']]],
  ['is_5fanthropic_5fmodel_132',['is_anthropic_model',['../namespacemodels_1_1metadata.html#a2c5be0de038b417bd4c9c156fca253b1',1,'models::metadata']]],
  ['is_5favailable_133',['is_available',['../classcore_1_1sandbox_1_1SandboxManager.html#ae0139e54ec4099aafd66e88ad6a2306f',1,'core::sandbox::SandboxManager']]],
  ['is_5fenabled_134',['is_enabled',['../classcore_1_1anthropic__features_1_1FilesAPIManager.html#ab869a3faaad1f8aeb4943f5d1d72134d',1,'core.anthropic_features.FilesAPIManager.is_enabled()'],['../classcore_1_1session__preprocessor_1_1SessionPreprocessor.html#ad00de885732a8826585771f29d25eeda',1,'core.session_preprocessor.SessionPreprocessor.is_enabled()']]],
  ['is_5ffiles_5fapi_5fenabled_135',['is_files_api_enabled',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#a9f391e07bb747b23ee1f490a5ceca240',1,'core::anthropic_features::AnthropicFeatures']]],
  ['is_5fgenuine_5ftask_5fcompletion_136',['is_genuine_task_completion',['../namespaceaxe.html#aed941049819dac642905b812e754e2fa',1,'axe']]],
  ['is_5fprompt_5fcaching_5fenabled_137',['is_prompt_caching_enabled',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#ae4cd2fc680f6eee97b78bf22a249bb50',1,'core::anthropic_features::AnthropicFeatures']]],
  ['is_5frunning_138',['is_running',['../classaxe_1_1CollaborativeSession.html#a17613664271470a880ce760a7a8ae835',1,'axe::CollaborativeSession']]],
  ['is_5fsafe_5ftar_5fmember_139',['is_safe_tar_member',['../namespacetools_1_1build__analyzer.html#a41726c547bb435a3ff3dccb41fc6e5d3',1,'tools::build_analyzer']]],
  ['is_5ftar_5farchive_140',['is_tar_archive',['../namespacetools_1_1build__analyzer.html#ad3c492d6e19c78b5a075cf2d226bcbd0',1,'tools::build_analyzer']]],
  ['is_5ftoken_5fcounting_5fenabled_141',['is_token_counting_enabled',['../classcore_1_1anthropic__features_1_1AnthropicFeatures.html#a264f65c13464b92c1ee4945375adb5f9',1,'core::anthropic_features::AnthropicFeatures']]],
  ['is_5ftool_5fallowed_142',['is_tool_allowed',['../classcore_1_1tool__runner_1_1ToolRunner.html#abd254d33291077274c09bef339b4c6c2',1,'core::tool_runner::ToolRunner']]],
  ['is_5ftool_5fallowed_20cmd_3a_20str_20lines_201460_201542_143',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1117',1,'']]],
  ['is_5ftool_5fblacklisted_144',['is_tool_blacklisted',['../classcore_1_1sandbox_1_1SandboxManager.html#a2d7dce26ef10f64fb3e7b1c38ded9ae2',1,'core::sandbox::SandboxManager']]],
  ['isjapan_145',['isjapan',['../unlzexe_8c.html#ac31e4a877b09226400b2ca4aa48987c0',1,'unlzexe.c']]],
  ['iskanji_146',['iskanji',['../unlzexe_8c.html#adb31912976d1b01a9e2575a9fde9d4d2',1,'unlzexe.c']]],
  ['isolated_147',['Scenario 3: Network Isolated',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1085',1,'']]],
  ['isolated_20sandbox_148',['Example 3: Network-Isolated Sandbox',['../md_SANDBOX.html#autotoc_md1039',1,'']]],
  ['isolation_149',['Isolation',['../md_SANDBOX.html#autotoc_md1030',1,'2. Linux Namespace Isolation'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1065',1,'2. Namespace Isolation'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md711',1,'3. Database Test Isolation']]],
  ['issue_150',['The Issue',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md389',1,'']]],
  ['issue_201_3a_20gpt_205_20api_20parameter_20error_20critical_151',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md460',1,'']]],
  ['issue_201_3a_20potential_20command_20injection_20in_20hammer_20module_152',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['issue_201_3a_20read_20block_20access_20denied_153',['Issue 1: READ Block Access Denied',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md173',1,'']]],
  ['issue_201_3a_20read_20block_20access_20denied_20✅_154',['Issue 1: READ Block Access Denied ✅',['../md_FIXES__SUMMARY.html#autotoc_md363',1,'']]],
  ['issue_202_3a_20llama_20405b_20model_20deprecated_155',['Issue 2: Llama 405B Model Deprecated',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md177',1,'']]],
  ['issue_202_3a_20llama_20405b_20model_20deprecated_20✅_156',['Issue 2: Llama 405B Model Deprecated ✅',['../md_FIXES__SUMMARY.html#autotoc_md365',1,'']]],
  ['issue_202_3a_20memory_20exhaustion_20in_20chisel_20analysis_157',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_workshop__security__audit.html#autotoc_md1424',1,'']]],
  ['issue_202_3a_20write_20blocks_20not_20executing_20high_158',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['issue_203_3a_20auto_20approve_20not_20default_20in_20collab_20mode_159',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['issue_203_3a_20auto_20approve_20not_20default_20in_20collab_20mode_20✅_160',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['issue_203_3a_20information_20disclosure_20in_20error_20messages_161',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['issue_204_3a_20agents_20confused_20about_20read_20write_20block_20syntax_162',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['issue_204_3a_20agents_20confused_20about_20read_20write_20block_20syntax_20✅_163',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['issue_204_3a_20race_20condition_20in_20database_20operations_164',['Issue #4: Race Condition in Database Operations',['../md_workshop__security__audit.html#autotoc_md1427',1,'']]],
  ['issue_205_3a_20weak_20random_20id_20generation_165',['Issue #5: Weak Random ID Generation',['../md_workshop__security__audit.html#autotoc_md1428',1,'']]],
  ['issue_20debugging_166',['2. Build Issue Debugging',['../md_README.html#autotoc_md954',1,'']]],
  ['issues_167',['Issues',['../md_BUG__FIX__SUMMARY.html',1,'Bug Fix Summary - Multi-Agent Collaboration Issues'],['../md_API__PROVIDERS.html#autotoc_md157',1,'Common Issues'],['../md_README.html#autotoc_md977',1,'Common Issues'],['../md_workshop__dependency__validation.html#autotoc_md1387',1,'Known Security Issues'],['../md_workshop__security__audit.html#autotoc_md1425',1,'Low Severity Issues'],['../md_workshop__security__audit.html#autotoc_md1422',1,'Medium Severity Issues']]],
  ['issues_168',['issues',['../md_skills_2claude__build.html#autotoc_md1233',1,'Cppcheck for C/C++ issues'],['../md_skills_2claude__build.html#autotoc_md1234',1,'Flawfinder for security issues']]],
  ['issues_20addressed_169',['Code Review Issues Addressed',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md674',1,'']]],
  ['issues_20detected_20re_20run_20with_20verbose_20output_3a_170',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['issues_20fix_20summary_171',['AXE Multiple Issues Fix Summary',['../md_FIXES__SUMMARY.html',1,'']]],
  ['issues_20fixed_172',['Issues Fixed',['../md_FIXES__SUMMARY.html#autotoc_md362',1,'']]],
  ['issues_20found_20re_20run_20with_20full_20details_3a_173',['issues found re run with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md1215',1,'If issues found, re-run with full details:']]],
  ['issues_20found_20run_20full_20scan_3a_174',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md1227',1,'']]],
  ['issues_20identified_20non_20blocking_175',['Minor Issues Identified (Non-Blocking)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md813',1,'']]],
  ['issues_20limitations_176',['Part 9: Known Issues &amp;amp; Limitations',['../md_PR23__VALIDATION__REPORT.html#autotoc_md812',1,'']]],
  ['issues_20non_20blocking_177',['Minor Issues (Non-Blocking)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md708',1,'']]],
  ['issues_20resolved_178',['Issues Resolved',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md459',1,'']]],
  ['issues_20silent_179',['Quick check for memory issues (silent)',['../md_skills_2claude__build.html#autotoc_md1214',1,'']]],
  ['it_20works_180',['It Works',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md248',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md255',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md259',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md264',1,'How It Works']]],
  ['itob_181',['itob',['../depklite_8c.html#a746cee407a9dac3b866f8da6600581c5',1,'depklite.c']]]
];
