var searchData=
[
  ['c_5fmodernization_5fexpert_2emd_0',['c_modernization_expert.md',['../c__modernization__expert_8md.html',1,'']]],
  ['chisel_2epy_1',['chisel.py',['../chisel_8py.html',1,'']]],
  ['claude_5fbuild_2emd_2',['claude_build.md',['../claude__build_8md.html',1,'']]],
  ['codebase_5foverview_2emd_3',['codebase_overview.md',['../codebase__overview_8md.html',1,'']]],
  ['codex_2dimplementation_2emd_4',['codex-implementation.md',['../codex-implementation_8md.html',1,'']]],
  ['cognitive_5farchitecture_5fguide_2emd_5',['COGNITIVE_ARCHITECTURE_GUIDE.md',['../COGNITIVE__ARCHITECTURE__GUIDE_8md.html',1,'']]],
  ['collab_5ftool_5fsyntax_5ffix_5fsummary_2emd_6',['COLLAB_TOOL_SYNTAX_FIX_SUMMARY.md',['../COLLAB__TOOL__SYNTAX__FIX__SUMMARY_8md.html',1,'']]],
  ['config_2epy_7',['config.py',['../config_8py.html',1,'']]],
  ['configuration_2emd_8',['configuration.md',['../configuration_8md.html',1,'']]],
  ['conflict_5fresolution_5fexamples_2emd_9',['conflict_resolution_examples.md',['../conflict__resolution__examples_8md.html',1,'']]],
  ['consolidation_5fsummary_2emd_10',['CONSOLIDATION_SUMMARY.md',['../CONSOLIDATION__SUMMARY_8md.html',1,'']]],
  ['constants_2epy_11',['constants.py',['../constants_8py.html',1,'']]],
  ['context_5foptimizer_2epy_12',['context_optimizer.py',['../context__optimizer_8py.html',1,'']]],
  ['cpp_5fmodernization_5fexpert_2emd_13',['cpp_modernization_expert.md',['../cpp__modernization__expert_8md.html',1,'']]],
  ['cpp_5frefactoring_5fexpert_2emd_14',['cpp_refactoring_expert.md',['../cpp__refactoring__expert_8md.html',1,'']]],
  ['create_5fabbreviations_5fdb_2epy_15',['create_abbreviations_db.py',['../create__abbreviations__db_8py.html',1,'']]]
];
