var searchData=
[
  ['e_20g_20cat_20eof_0',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['each_20agent_1',['When to Use Each Agent',['../md_README.html#autotoc_md913',1,'']]],
  ['each_20block_2',['Process each block',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['each_20block_20in_20order_3',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['edge_20case_20test_20suite_20test_5ftool_5frunner_5fedge_5fcases_20py_4',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1129',1,'']]],
  ['edge_20cases_20fixed_5',['Edge Cases Fixed',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1119',1,'']]],
  ['edge_20cases_20newly_20fixed_20_3a_6',['Edge Cases (newly fixed):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1134',1,'']]],
  ['effectiveness_7',['Effectiveness',['../md_workshop__benchmarks.html#autotoc_md1357',1,'Monitoring Effectiveness'],['../md_workshop__test__results.html#autotoc_md1463',1,'Test Effectiveness']]],
  ['efficiency_20analysis_8',['Token Efficiency Analysis',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1307',1,'']]],
  ['efficiency_20comparison_9',['Tool Efficiency Comparison',['../md_workshop__benchmarks.html#autotoc_md1359',1,'']]],
  ['emergency_20mailbox_10',['Emergency Mailbox',['../md_IMPROVEMENTS__FINAL.html#autotoc_md492',1,'']]],
  ['emergency_20mailbox_20✅_11',['Phase 8: Emergency Mailbox ✅',['../md_IMPROVEMENTS__README.html#autotoc_md551',1,'']]],
  ['emulation_12',['Emulation',['../md_README.html#autotoc_md922',1,'']]],
  ['enable_20in_20axe_20yaml_13',['Enable in axe.yaml',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md590',1,'']]],
  ['enabled_14',['Use Cases Enabled',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md36',1,'']]],
  ['enabling_20sandbox_20mode_15',['Enabling Sandbox Mode',['../md_SANDBOX.html#autotoc_md1034',1,'Enabling Sandbox Mode'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1071',1,'Enabling Sandbox Mode']]],
  ['encouraging_20good_20behavior_16',['Encouraging Good Behavior',['../md_QUICK__REFERENCE.html#autotoc_md854',1,'']]],
  ['endpoints_20summary_17',['API Endpoints Summary',['../md_API__PROVIDERS.html#autotoc_md153',1,'']]],
  ['engine_18',['Engine',['../md_workshop__dependency__validation.html#autotoc_md1367',1,'angr (Symbolic Execution Engine)'],['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine'],['../md_workshop__dependency__validation.html#autotoc_md1372',1,'sqlite3 (Database Engine)']]],
  ['engine_20✅_19',['AXE - Agent eXecution Engine ✅',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'']]],
  ['engineering_20a_20wad_20file_20',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['engineering_20expert_21',['Reverse Engineering Expert',['../md_skills_2reverse__engineering__expert.html',1,'']]],
  ['engineering_20tools_22',['Reverse Engineering Tools',['../md__8collab__env.html#autotoc_md4',1,'']]],
  ['enhanced_20documentation_23',['2. Enhanced Documentation',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md406',1,'']]],
  ['enhanced_20reasoning_20✅_24',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md75',1,'']]],
  ['enhancement_20implementation_20complete_20✅_25',['AXE Enhancement Implementation - Complete ✅',['../md_IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['enhancements_26',['Enhancements',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md95',1,'Future Enhancements'],['../md_ARCHITECTURE.html#autotoc_md167',1,'Future Enhancements'],['../md_BUG__FIX__SUMMARY.html#autotoc_md208',1,'Future Enhancements'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md355',1,'Future Enhancements'],['../md_SANDBOX.html#autotoc_md1057',1,'Future Enhancements'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1090',1,'Future Enhancements'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1313',1,'Future Enhancements'],['../md_workshop__security__audit.html#autotoc_md1445',1,'Future Enhancements'],['../md_workshop__test__results.html#autotoc_md1475',1,'Future Enhancements'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1499',1,'Future Enhancements'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1512',1,'Future Enhancements']]],
  ['entire_20block_20contains_20a_20heredoc_27',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['enumeration_28',['Enumeration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md752',1,'✅ VALIDATED - Plane (Source/Sink Enumeration)'],['../md_README.html#autotoc_md963',1,'Plane - Source/Sink Enumeration'],['../md_workshop__quick__reference.html#autotoc_md1404',1,'Plane - Source/Sink Enumeration']]],
  ['enumeration_20benchmarks_29',['Plane - Source/Sink Enumeration Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1352',1,'']]],
  ['enumeration_20coverage_30',['Enumeration Coverage',['../md_workshop__benchmarks.html#autotoc_md1354',1,'']]],
  ['environment_31',['Environment',['../md_AGENTS.html#autotoc_md42',1,'Development Environment'],['../md_workshop__benchmarks.html#autotoc_md1345',1,'Test Environment'],['../md_workshop__test__results.html#autotoc_md1449',1,'Test Environment']]],
  ['environment_20detection_32',['4. Environment Detection',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1067',1,'']]],
  ['environment_20restrictions_33',['Environment Restrictions',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1079',1,'']]],
  ['environment_20setup_34',['Environment Setup',['../md_MODELS__FINAL.html#autotoc_md618',1,'']]],
  ['environment_20summary_35',['Environment Summary',['../md__8collab__env.html',1,'']]],
  ['environment_20validation_36',['Test Environment Validation',['../md_workshop__test__results.html#autotoc_md1470',1,'']]],
  ['environment_20variable_37',['Environment Variable',['../md_API__PROVIDERS.html#autotoc_md110',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md118',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md128',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md137',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md146',1,'Environment Variable']]],
  ['environment_20variables_20summary_38',['Environment Variables Summary',['../md_API__PROVIDERS.html#autotoc_md152',1,'']]],
  ['eof_39',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['error_40',['No Credits Error',['../md_MODELS__FINAL.html#autotoc_md662',1,'']]],
  ['error_20analysis_41',['Error Analysis',['../md_workshop__test__results.html#autotoc_md1467',1,'']]],
  ['error_20critical_42',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md460',1,'']]],
  ['error_20detection_20metrics_43',['Diff-Based Error Detection Metrics',['../md_IMPROVEMENTS__FINAL.html#autotoc_md488',1,'']]],
  ['error_20fixed_20✓_44',['1. Anthropic SDK Error Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md347',1,'']]],
  ['error_20handling_45',['Error Handling',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md305',1,'']]],
  ['error_20handling_20robust_46',['Error Handling - ROBUST',['../md_PR23__VALIDATION__REPORT.html#autotoc_md795',1,'']]],
  ['error_20messages_47',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['error_20recovery_48',['Error Recovery',['../md_workshop__dependency__validation.html#autotoc_md1393',1,'Error Recovery'],['../md_workshop__security__audit.html#autotoc_md1431',1,'Finding #2: Limited Error Recovery']]],
  ['error_3a_49',['&quot;Sandbox execution error: ...&quot;',['../md_SANDBOX.html#autotoc_md1052',1,'']]],
  ['errors_50',['Path Errors?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1525',1,'']]],
  ['errors_20413_20not_20handled_20✅_51',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['errors_20inside_20sandbox_52',['&quot;Permission denied&quot; errors inside sandbox',['../md_SANDBOX.html#autotoc_md1054',1,'']]],
  ['escalate_20properly_53',['3. Chain of Command – Escalate Properly',['../md_IMPROVEMENTS__FINAL.html#autotoc_md527',1,'']]],
  ['estimates_54',['Estimates',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1154',1,'Token Savings Estimates'],['../md_skills_2build.html#autotoc_md1168',1,'Token Savings Estimates']]],
  ['estimates_20✅_55',['3. Token Counting (Precise Estimates) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md76',1,'']]],
  ['etc_20if_20tools_20expand_56',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['evidence_20from_20live_20testing_57',['Evidence from Live Testing',['../md_FIXES__SUMMARY.html#autotoc_md382',1,'']]],
  ['evidence_20of_20the_20problem_58',['Evidence of the Problem',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md19',1,'']]],
  ['example_59',['Example',['../md_API__PROVIDERS.html#autotoc_md130',1,'Chat-style cURL Example'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1070',1,'Configuration Example'],['../md_API__PROVIDERS.html#autotoc_md111',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md119',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md129',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md138',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md147',1,'cURL Example'],['../md_AGENTS.html#autotoc_md51',1,'Example'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md256',1,'Example'],['../md_MODELS__FINAL.html#autotoc_md657',1,'Model Communication Example'],['../md_API__PROVIDERS.html#autotoc_md112',1,'Python Example'],['../md_API__PROVIDERS.html#autotoc_md120',1,'Python Example'],['../md_API__PROVIDERS.html#autotoc_md131',1,'Python Example'],['../md_skills_2claude__build.html#autotoc_md1228',1,'Security Audit Workflow Example'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md249',1,'Token Savings Example']]],
  ['example_201_3a_20c_20project_20with_20cmake_60',['Example 1: C++ Project with CMake',['../md_skills_2build.html#autotoc_md1191',1,'']]],
  ['example_201_3a_20claude_20s_20natural_20format_61',['Example 1: Claude&apos;s Natural Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md683',1,'']]],
  ['example_201_3a_20default_20sandbox_20mode_62',['Example 1: Default Sandbox Mode',['../md_SANDBOX.html#autotoc_md1037',1,'']]],
  ['example_201_3a_20gpt_20building_20c_20project_63',['Example 1: GPT Building C++ Project',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1157',1,'']]],
  ['example_201_3a_20no_20duplicate_20execution_64',['Example 1: No Duplicate Execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md328',1,'']]],
  ['example_202_3a_20claude_20security_20audit_65',['Example 2: Claude Security Audit',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1158',1,'']]],
  ['example_202_3a_20code_20block_20format_66',['Example 2: Code Block Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md684',1,'']]],
  ['example_202_3a_20heredoc_20preserved_67',['Example 2: Heredoc Preserved',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md329',1,'']]],
  ['example_202_3a_20java_20project_20with_20maven_68',['Example 2: Java Project with Maven',['../md_skills_2build.html#autotoc_md1194',1,'']]],
  ['example_202_3a_20restricted_20sandbox_20with_20blacklist_69',['Example 2: Restricted Sandbox with Blacklist',['../md_SANDBOX.html#autotoc_md1038',1,'']]],
  ['example_203_3a_20axe_20native_20format_70',['Example 3: AXE Native Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md685',1,'']]],
  ['example_203_3a_20backward_20compatibility_71',['Example 3: Backward Compatibility',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md331',1,'']]],
  ['example_203_3a_20multi_20agent_20collaboration_72',['Example 3: Multi-Agent Collaboration',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1161',1,'']]],
  ['example_203_3a_20network_20isolated_20sandbox_73',['Example 3: Network-Isolated Sandbox',['../md_SANDBOX.html#autotoc_md1039',1,'']]],
  ['example_203_3a_20python_20project_20with_20make_74',['Example 3: Python Project with Make',['../md_skills_2build.html#autotoc_md1197',1,'']]],
  ['example_204_3a_20multi_20agent_20collaboration_75',['Example 4: Multi-Agent Collaboration',['../md_skills_2build.html#autotoc_md1200',1,'']]],
  ['example_20before_20vs_20after_76',['Example - Before vs After',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md411',1,'']]],
  ['example_20images_77',['Vision Example (Images)',['../md_API__PROVIDERS.html#autotoc_md121',1,'']]],
  ['example_20of_20duplicate_20execution_20before_20fix_78',['Example of Duplicate Execution (Before Fix)',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'']]],
  ['example_20openai_20sdk_79',['Example OpenAI SDK',['../md_API__PROVIDERS.html#autotoc_md139',1,'Python Example (OpenAI SDK)'],['../md_API__PROVIDERS.html#autotoc_md148',1,'Python Example (OpenAI SDK)']]],
  ['example_20output_80',['Example Output',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md251',1,'Example Output'],['../md_README.html#autotoc_md948',1,'Example Output']]],
  ['example_20session_81',['Example Session',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md304',1,'']]],
  ['example_20skill_20template_82',['Example Skill Template',['../md_AGENTS.html#autotoc_md56',1,'']]],
  ['example_20workflow_20savings_83',['Example Workflow Savings',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md270',1,'']]],
  ['example_3a_20multi_20agent_20code_20analysis_84',['Example: Multi-Agent Code Analysis',['../md_README.html#autotoc_md899',1,'']]],
  ['example_3a_20reverse_20engineering_20a_20wad_20file_85',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['example_3a_20security_20audit_20workflow_86',['Real-World Example: Security Audit Workflow',['../md_README.html#autotoc_md972',1,'']]],
  ['examples_87',['Examples',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md327',1,'Examples'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md514',1,'Examples'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md682',1,'Examples'],['../md_skills_2build.html#autotoc_md1190',1,'Examples'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1481',1,'Examples'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md352',1,'Model Examples'],['../md_README.html#autotoc_md960',1,'Quick Examples'],['../md_IMPROVEMENTS__README.html#autotoc_md556',1,'Usage Examples'],['../md_MODELS__FINAL.html#autotoc_md655',1,'Usage Examples'],['../md_README.html#autotoc_md892',1,'Usage Examples'],['../md_SANDBOX.html#autotoc_md1036',1,'Usage Examples'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1156',1,'Usage Examples'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1310',1,'Usage Examples'],['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1341',1,'Usage Examples'],['../md_README.html#autotoc_md952',1,'Workflow Examples']]],
  ['excellent_88',['Code Structure - EXCELLENT',['../md_PR23__VALIDATION__REPORT.html#autotoc_md794',1,'']]],
  ['exclusively_20by_20axe_20py_20responseprocessor_89',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['exe_20unpackers_90',['DOS EXE Unpackers',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1339',1,'']]],
  ['exec_20blocks_91',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['execute_20each_20block_20in_20order_92',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['executed_93',['Executed',['../md_workshop__test__results.html#autotoc_md1451',1,'Test Files Executed'],['../md_workshop__security__audit.html#autotoc_md1439',1,'Test Scenarios Executed']]],
  ['executing_20high_94',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['executing_20tools_95',['Executing Tools',['../md_README.html#autotoc_md897',1,'']]],
  ['execution_96',['Execution',['../md_PR23__VALIDATION__REPORT.html#autotoc_md750',1,'✅ VALIDATED - Chisel (Symbolic Execution)'],['../md_SANDBOX.html#autotoc_md1029',1,'1. Default-Allow Execution'],['../md_README.html#autotoc_md961',1,'Chisel - Symbolic Execution'],['../md_workshop__quick__reference.html#autotoc_md1402',1,'Chisel - Symbolic Execution'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md328',1,'Example 1: No Duplicate Execution']]],
  ['execution_97',['to prevent duplicate execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md317',1,'']]],
  ['execution_20⚠️_20medium_98',['2. &lt;b&gt;Command Execution&lt;/b&gt; ⚠️ Medium',['../md_SECURITY__REPORT.html#autotoc_md1102',1,'']]],
  ['execution_20❌_20→_20✅_99',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md310',1,'']]],
  ['execution_20and_20heredoc_20parsing_20bug_20fixes_100',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['execution_20before_20fix_101',['Example of Duplicate Execution (Before Fix)',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'']]],
  ['execution_20benchmarks_102',['Chisel - Symbolic Execution Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1346',1,'']]],
  ['execution_20bug_20✅_103',['Bug 4: Double Execution Bug ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['execution_20engine_104',['angr (Symbolic Execution Engine)',['../md_workshop__dependency__validation.html#autotoc_md1367',1,'']]],
  ['execution_20engine_105',['eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['execution_20engine_20✅_106',['AXE - Agent eXecution Engine ✅',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'']]],
  ['execution_20error_3a_107',['&quot;Sandbox execution error: ...&quot;',['../md_SANDBOX.html#autotoc_md1052',1,'']]],
  ['execution_20fix_20implementation_20summary_108',['Heredoc Execution Fix - Implementation Summary',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['execution_20fix_20summary_109',['Heredoc Execution Fix Summary',['../md_HEREDOC__EXECUTION__FIX.html',1,'']]],
  ['execution_20logs_110',['Appendix A: Test Execution Logs',['../md_PR23__VALIDATION__REPORT.html#autotoc_md831',1,'']]],
  ['execution_20original_20version_20_3a_111',['Execution (original version):',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md414',1,'']]],
  ['execution_20results_112',['Workshop Tools Test Suite Execution Results',['../md_workshop__test__results.html',1,'']]],
  ['execution_20summary_113',['Execution Summary',['../md_workshop__test__results.html#autotoc_md1448',1,'Test Execution Summary'],['../md_workshop__test__results.html#autotoc_md1459',1,'Test Execution Summary']]],
  ['executive_20summary_114',['Executive Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md745',1,'Executive Summary'],['../md_SECURITY__REPORT.html#autotoc_md1098',1,'Executive Summary'],['../md_workshop__security__audit.html#autotoc_md1418',1,'Executive Summary'],['../md_PR23__EXECUTIVE__SUMMARY.html',1,'PR #23 Workshop Dynamic Analysis Framework - Executive Summary']]],
  ['exepack_115',['Then EXEPACK',['../md_skills_2dos__packer__detector.html#autotoc_md1270',1,'']]],
  ['exhaustion_20in_20chisel_20analysis_116',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_workshop__security__audit.html#autotoc_md1424',1,'']]],
  ['existing_20code_117',['For Existing Code',['../md_REFACTORING__NOTES.html#autotoc_md1022',1,'']]],
  ['existing_20tests_118',['Existing Tests',['../md_FIXES__SUMMARY.html#autotoc_md375',1,'Existing Tests'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md397',1,'Existing Tests']]],
  ['existing_20tests_20verify_20no_20breakage_119',['Existing tests (verify no breakage)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1522',1,'']]],
  ['exists_120',['Only one present: use whichever exists',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md392',1,'']]],
  ['expand_121',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['expanded_122',['EXPANDED',['../md_README.html#autotoc_md905',1,'Build Analysis (EXPANDED!)'],['../md_README.html#autotoc_md904',1,'Workshop Commands (EXPANDED!)']]],
  ['expected_20behavior_123',['Expected Behavior',['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md216',1,'']]],
  ['expected_20benefits_124',['Expected Benefits',['../md_README.html#autotoc_md942',1,'Expected Benefits'],['../md_README.html#autotoc_md949',1,'Expected Benefits']]],
  ['experience_20level_20system_20✅_125',['Phase 3: Experience &amp;amp; Level System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md545',1,'']]],
  ['expert_126',['Expert',['../md_skills_2c__modernization__expert.html',1,'C Modernization Expert'],['../md_skills_2cpp__modernization__expert.html',1,'C++ Modernization Expert'],['../md_skills_2cpp__refactoring__expert.html',1,'C++ Refactoring Expert'],['../md_skills_2ida__pro__analysis__patterns.html',1,'IDA Pro / Decompiler Analysis Expert'],['../md_skills_2python__agent__expert.html',1,'Python Agent Expert'],['../md_skills_2reverse__engineering__expert.html',1,'Reverse Engineering Expert'],['../md_skills_2x86__assembly__expert.html',1,'x86 Assembly Analysis Expert']]],
  ['exploration_127',['1. New Codebase Exploration',['../md_README.html#autotoc_md953',1,'']]],
  ['exponential_128',['Progression Curve (Hybrid Linear/Exponential)',['../md_IMPROVEMENTS__FINAL.html#autotoc_md519',1,'']]],
  ['exported_20helper_20function_129',['4. Exported Helper Function',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md227',1,'']]],
  ['extend_20parse_5faxe_5fnative_5fblocks_20response_20commented_20out_130',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md318',1,'']]],
  ['extended_20thinking_131',['2. Extended Thinking',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md252',1,'']]],
  ['extended_20thinking_20enhanced_20reasoning_20✅_132',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md75',1,'']]],
  ['extended_20thinking_20not_20available_133',['Extended thinking not available',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md274',1,'']]],
  ['extensibility_134',['Extensibility',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1092',1,'']]],
  ['extensibility_20guide_135',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['extension_20points_136',['Extension Points',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md97',1,'Extension Points'],['../md_ARCHITECTURE.html#autotoc_md161',1,'Key Extension Points']]],
  ['extract_20functions_20✅_137',['Phase 2: Extract Functions ✅',['../md_REFACTORING__NOTES.html#autotoc_md1004',1,'']]],
  ['extract_20large_20classes_138',['PR #2: Extract Large Classes',['../md_REFACTORING__NOTES.html#autotoc_md1019',1,'']]],
  ['extract_20session_20management_139',['PR #3: Extract Session Management',['../md_REFACTORING__NOTES.html#autotoc_md1020',1,'']]]
];
