var searchData=
[
  ['namespace_20isolation_0',['Namespace Isolation',['../md_SANDBOX.html#autotoc_md1030',1,'2. Linux Namespace Isolation'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1065',1,'2. Namespace Isolation']]],
  ['naming_1',['File Naming',['../md_AGENTS.html#autotoc_md52',1,'']]],
  ['native_20blocks_2',['3. AXE Native Blocks',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md691',1,'']]],
  ['native_20format_3',['Example 3: AXE Native Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md685',1,'']]],
  ['native_20read_20write_20exec_20blocks_4',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['natural_20format_5',['Example 1: Claude&apos;s Natural Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md683',1,'']]],
  ['needed_6',['Create parent dirs if needed',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md466',1,'']]],
  ['nested_20subshells_7',['3. Nested Subshells',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1122',1,'']]],
  ['network_20isolated_8',['Scenario 3: Network Isolated',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1085',1,'']]],
  ['network_20isolated_20sandbox_9',['Example 3: Network-Isolated Sandbox',['../md_SANDBOX.html#autotoc_md1039',1,'']]],
  ['never_20get_20turns_20✅_10',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['new_11',['NEW',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md344',1,'6. &lt;span class=&quot;tt&quot;&gt;tests/test_dynamic_max_tokens.py&lt;/span&gt; (NEW)'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md345',1,'7. &lt;span class=&quot;tt&quot;&gt;demo_dynamic_tokens.py&lt;/span&gt; (NEW)'],['../md_README.html#autotoc_md932',1,'Autonomous Collaborative Sessions (NEW!)'],['../md_README.html#autotoc_md906',1,'Rate Limiting (NEW!)'],['../md_README.html#autotoc_md903',1,'Session Management (NEW!)'],['../md_README.html#autotoc_md902',1,'Token Usage Commands (NEW!)'],['../md_README.html#autotoc_md907',1,'Token-Saving Optimizations (NEW!)']]],
  ['new_12',['New',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1515',1,'What&apos;s New?'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1518',1,'XML Format (New!)']]],
  ['new_20agent_20commands_20during_20sessions_13',['New Agent Commands (During Sessions)',['../md_IMPROVEMENTS__README.html#autotoc_md554',1,'']]],
  ['new_20ai_20providers_14',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md162',1,'']]],
  ['new_20code_15',['For New Code',['../md_REFACTORING__NOTES.html#autotoc_md1023',1,'']]],
  ['new_20codebase_20exploration_16',['1. New Codebase Exploration',['../md_README.html#autotoc_md953',1,'']]],
  ['new_20features_17',['Starting a Collaborative Session with New Features',['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'']]],
  ['new_20files_18',['New Files',['../md_PR23__VALIDATION__REPORT.html#autotoc_md836',1,'New Files'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1509',1,'New Files']]],
  ['new_20functions_20added_19',['New Functions Added',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md670',1,'']]],
  ['new_20module_20structure_20',['New Module Structure',['../md_REFACTORING__NOTES.html#autotoc_md997',1,'']]],
  ['new_20skills_21',['Creating New Skills',['../md_AGENTS.html#autotoc_md55',1,'']]],
  ['new_20test_20files_22',['New Test Files',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md26',1,'']]],
  ['new_20tests_20added_23',['New Tests Added',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md325',1,'New Tests Added'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md396',1,'New Tests Added']]],
  ['new_20token_20optimization_20strategies_24',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md165',1,'']]],
  ['new_20workshop_20tools_25',['3. Adding New Workshop Tools',['../md_ARCHITECTURE.html#autotoc_md164',1,'']]],
  ['newline_20e_20g_20cat_20eof_26',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['newly_20fixed_20_3a_27',['Edge Cases (newly fixed):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1134',1,'']]],
  ['next_20steps_28',['Next Steps',['../md_FIXES__SUMMARY.html#autotoc_md386',1,'Next Steps'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md453',1,'Next Steps'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md600',1,'Next Steps']]],
  ['ninja_29',['Ninja',['../md_skills_2build.html#autotoc_md1174',1,'']]],
  ['no_20breakage_30',['Existing tests (verify no breakage)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1522',1,'']]],
  ['no_20credits_20error_31',['No Credits Error',['../md_MODELS__FINAL.html#autotoc_md662',1,'']]],
  ['no_20duplicate_20execution_32',['Example 1: No Duplicate Execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md328',1,'']]],
  ['no_20hardcoded_20secrets_20verified_33',['No Hardcoded Secrets - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md786',1,'']]],
  ['no_20heredoc_20process_20line_20by_20line_20as_20before_34',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['no_20installation_20required_35',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md282',1,'']]],
  ['no_20rate_20limiting_36',['Finding #3: No Rate Limiting',['../md_workshop__security__audit.html#autotoc_md1432',1,'']]],
  ['no_20real_20bullying_37',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['no_20regressions_38',['✅ No Regressions',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md438',1,'']]],
  ['no_20results_20appearing_39',['No Results Appearing?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1524',1,'']]],
  ['noise_40',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md1248',1,'']]],
  ['non_20blocking_41',['Non Blocking',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md708',1,'Minor Issues (Non-Blocking)'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md813',1,'Minor Issues Identified (Non-Blocking)']]],
  ['non_20interactive_42',['Auto-Approve Mode (Non-Interactive)',['../md_README.html#autotoc_md927',1,'']]],
  ['none_43',['Test Failures (None)',['../md_workshop__test__results.html#autotoc_md1468',1,'']]],
  ['not_20available_44',['Extended thinking not available',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md274',1,'']]],
  ['not_20available_20falling_20back_20to_20whitelist_20mode_45',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['not_20cooperating_46',['&quot;Agents not cooperating&quot;',['../md_QUICK__REFERENCE.html#autotoc_md857',1,'']]],
  ['not_20default_20in_20collab_20mode_47',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['not_20default_20in_20collab_20mode_20✅_48',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['not_20executing_20high_49',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['not_20handled_20✅_50',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['not_20sandbox_20mode_51',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['not_20supported_20✅_52',['Bug 1: XML Tag Formats Not Supported ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md196',1,'']]],
  ['not_20working_53',['not working',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md273',1,'Caching not working'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md276',1,'Files API not working']]],
  ['not_20yet_20implemented_54',['Future Features (Not Yet Implemented)',['../md_QUICK__REFERENCE.html#autotoc_md861',1,'']]],
  ['note_20on_20whistleblower_20feature_55',['Note on Whistleblower Feature',['../md_README.html#autotoc_md870',1,'']]],
  ['notes_56',['Notes',['../md_IMPROVEMENTS__README.html#autotoc_md561',1,'Architecture Notes'],['../md_REFACTORING__NOTES.html',1,'AXE.PY Refactoring Notes'],['../md__8collab__shared.html',1,'Collaborative Session Notes'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1135',1,'Implementation Notes'],['../md_MODELS__FINAL.html#autotoc_md625',1,'Notes'],['../md_MODELS__FINAL.html#autotoc_md632',1,'Notes'],['../md_MODELS__FINAL.html#autotoc_md638',1,'Notes'],['../md_MODELS__FINAL.html#autotoc_md645',1,'Notes'],['../md_MODELS__FINAL.html#autotoc_md651',1,'Notes'],['../md_tests_2MISSION.html#autotoc_md1338',1,'Notes']]],
  ['notes_20for_20agents_57',['Notes for Agents',['../md__8collab__env.html#autotoc_md11',1,'']]],
  ['now_20allowed_20bug_20fixed_20_3a_58',['✅ Now Allowed (Bug Fixed):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md31',1,'']]],
  ['now_20handled_20exclusively_20by_20axe_20py_20responseprocessor_59',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['now_20working_60',['Now Working',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md34',1,'Agents Now Working'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1132',1,'Commands Now Working']]]
];
