var searchData=
[
  ['c_20c_20issues_0',['Cppcheck for C/C++ issues',['../md_skills_2claude__build.html#autotoc_md1233',1,'']]],
  ['c_20c_20security_20scanner_1',['Flawfinder (C/C++ Security Scanner)',['../md_skills_2claude__build.html#autotoc_md1225',1,'']]],
  ['c_20issues_2',['Cppcheck for C/C++ issues',['../md_skills_2claude__build.html#autotoc_md1233',1,'']]],
  ['c_20modernization_20expert_3',['C Modernization Expert',['../md_skills_2c__modernization__expert.html',1,'C Modernization Expert'],['../md_skills_2cpp__modernization__expert.html',1,'C++ Modernization Expert']]],
  ['c_20project_4',['Example 1: GPT Building C++ Project',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1157',1,'']]],
  ['c_20project_20with_20cmake_5',['Example 1: C++ Project with CMake',['../md_skills_2build.html#autotoc_md1191',1,'']]],
  ['c_20refactoring_20expert_6',['C++ Refactoring Expert',['../md_skills_2cpp__refactoring__expert.html',1,'']]],
  ['c_20security_20scanner_7',['Flawfinder (C/C++ Security Scanner)',['../md_skills_2claude__build.html#autotoc_md1225',1,'']]],
  ['cache_20tracking_8',['Token Statistics with Cache Tracking',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md266',1,'']]],
  ['caching_9',['1. Prompt Caching',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md246',1,'']]],
  ['caching_2090_20token_20savings_20✅_10',['1. Prompt Caching (90% Token Savings) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md74',1,'']]],
  ['caching_20not_20working_11',['Caching not working',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md273',1,'']]],
  ['calculation_12',['✅ VALIDATED - Bonus XP Calculation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md761',1,'']]],
  ['call_20graph_13',['Call Graph',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md288',1,'']]],
  ['call_20parser_20implementation_14',['Multi-Format Tool Call Parser Implementation',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'']]],
  ['call_20parser_20implementation_20summary_15',['XML Function Call Parser - Implementation Summary',['../md_XML__PARSER__IMPLEMENTATION.html',1,'']]],
  ['call_20parser_20quick_20reference_16',['Multi-Format Tool Call Parser - Quick Reference',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['call_20support_20quick_20reference_17',['XML Function Call Support - Quick Reference',['../md_XML__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['calls_20extend_20parse_5faxe_5fnative_5fblocks_20response_20commented_20out_18',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md318',1,'']]],
  ['capabilities_20matrix_19',['Model Capabilities Matrix',['../md_MODELS__FINAL.html#autotoc_md653',1,'']]],
  ['capacity_20fixed_20✓_20',['3. Wasted Capacity Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md349',1,'']]],
  ['card_21',['Card',['../md_QUICK__REFERENCE.html',1,'AXE Multiagent - Quick Reference Card'],['../md_README.html#autotoc_md990',1,'Quick Reference Card']]],
  ['case_20test_20suite_20test_5ftool_5frunner_5fedge_5fcases_20py_22',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1129',1,'']]],
  ['cases_20enabled_23',['Use Cases Enabled',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md36',1,'']]],
  ['cases_20fixed_24',['Edge Cases Fixed',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1119',1,'']]],
  ['cases_20newly_20fixed_20_3a_25',['Edge Cases (newly fixed):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1134',1,'']]],
  ['cat_20eof_26',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['categories_27',['Test Categories',['../md_workshop__test__results.html#autotoc_md1452',1,'']]],
  ['cause_28',['Cause',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md20',1,'Root Cause'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md211',1,'Root Cause'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md312',1,'Root Cause'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md390',1,'Root Cause']]],
  ['cause_20analysis_29',['Root Cause Analysis',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md402',1,'']]],
  ['cd_20security_20checks_30',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md1246',1,'']]],
  ['chain_20of_20command_20–_20escalate_20properly_31',['3. Chain of Command – Escalate Properly',['../md_IMPROVEMENTS__FINAL.html#autotoc_md527',1,'']]],
  ['chain_20of_20thought_32',['Chain of Thought',['../md_README.html#autotoc_md934',1,'']]],
  ['chain_20silent_33',['Pattern 2: Security Tool Chain (Silent)',['../md_skills_2claude__build.html#autotoc_md1255',1,'']]],
  ['changed_34',['Changed',['../md_BUG__FIX__SUMMARY.html#autotoc_md207',1,'Files Changed'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md399',1,'Files Changed'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md679',1,'Files Changed'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1162',1,'Files Changed'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md242',1,'Lines Changed']]],
  ['changelog_35',['Changelog',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1497',1,'']]],
  ['changes_36',['Changes',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1314',1,'Breaking Changes'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md22',1,'Code Changes'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md214',1,'Code Changes'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md223',1,'Core Changes'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md217',1,'Minimal Changes'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md192',1,'Summary of Changes']]],
  ['changes_20made_37',['Changes Made',['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md213',1,'Changes Made'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md338',1,'Changes Made'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1323',1,'Changes Made'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1328',1,'Changes Made']]],
  ['changes_20summary_38',['Changes Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md834',1,'Appendix B: File Changes Summary'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md430',1,'Code Changes Summary']]],
  ['changes_3a_39',['Key Changes:',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md23',1,'']]],
  ['characteristics_40',['Performance Characteristics',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md718',1,'']]],
  ['chat_20commands_41',['Chat Commands',['../md_QUICK__REFERENCE.html#autotoc_md843',1,'']]],
  ['chat_20commands_20reference_42',['Chat Commands Reference',['../md_README.html#autotoc_md901',1,'']]],
  ['chat_20style_20curl_20example_43',['Chat-style cURL Example',['../md_API__PROVIDERS.html#autotoc_md130',1,'']]],
  ['check_44',['Tool Version Check',['../md__8collab__env.html#autotoc_md9',1,'']]],
  ['check_45',['Syntax check',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md471',1,'']]],
  ['check_20for_20memory_20issues_20silent_46',['Quick check for memory issues (silent)',['../md_skills_2claude__build.html#autotoc_md1214',1,'']]],
  ['check_20for_20regressions_47',['Check for regressions',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md469',1,'']]],
  ['check_20if_20all_20trials_20fail_48',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['check_20if_20the_20entire_20block_20contains_20a_20heredoc_49',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['check_20permissions_50',['Check permissions',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md465',1,'']]],
  ['checking_20resource_20usage_51',['Checking Resource Usage',['../md_IMPROVEMENTS__README.html#autotoc_md559',1,'']]],
  ['checklist_52',['Code Review Checklist',['../md_AGENTS.html#autotoc_md65',1,'']]],
  ['checks_53',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md1246',1,'']]],
  ['chisel_20analysis_54',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_workshop__security__audit.html#autotoc_md1424',1,'']]],
  ['chisel_20symbolic_20execution_55',['Chisel Symbolic Execution',['../md_PR23__VALIDATION__REPORT.html#autotoc_md750',1,'✅ VALIDATED - Chisel (Symbolic Execution)'],['../md_README.html#autotoc_md961',1,'Chisel - Symbolic Execution'],['../md_workshop__quick__reference.html#autotoc_md1402',1,'Chisel - Symbolic Execution']]],
  ['chisel_20symbolic_20execution_20benchmarks_56',['Chisel - Symbolic Execution Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1346',1,'']]],
  ['choices_57',['3. Document Your Choices',['../md_skills_2build.html#autotoc_md1183',1,'']]],
  ['ci_20cd_20security_20checks_58',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md1246',1,'']]],
  ['claim_201_3a_20four_20analysis_20tools_20implemented_59',['Claim 1: Four Analysis Tools Implemented',['../md_PR23__VALIDATION__REPORT.html#autotoc_md749',1,'']]],
  ['claim_202_3a_20database_20integration_60',['Claim 2: Database Integration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md755',1,'']]],
  ['claim_203_3a_20xp_20system_20integration_61',['Claim 3: XP System Integration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md759',1,'']]],
  ['claim_204_3a_20configuration_20integration_62',['Claim 4: Configuration Integration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md763',1,'']]],
  ['claim_205_3a_20documentation_63',['Claim 5: Documentation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md766',1,'']]],
  ['claim_206_3a_20test_20suite_64',['Claim 6: Test Suite',['../md_PR23__VALIDATION__REPORT.html#autotoc_md774',1,'']]],
  ['claimed_20performance_20metrics_65',['Claimed Performance Metrics',['../md_PR23__VALIDATION__REPORT.html#autotoc_md791',1,'']]],
  ['claims_20fulfillment_20summary_66',['Claims Fulfillment Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md817',1,'']]],
  ['claims_20vs_20actual_20implementation_67',['Part 1: PR Claims vs. Actual Implementation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md748',1,'']]],
  ['clang_20static_20analyzer_68',['Clang Static Analyzer',['../md_skills_2claude__build.html#autotoc_md1222',1,'']]],
  ['clang_20static_20analyzer_20quietly_69',['Run Clang static analyzer quietly',['../md_skills_2claude__build.html#autotoc_md1223',1,'']]],
  ['class_20api_70',['SkillsManager Class API',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1305',1,'']]],
  ['class_20constants_20lines_201121_201148_71',['1. Class Constants (Lines 1121-1148)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1112',1,'']]],
  ['class_20diagram_72',['Class Diagram',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md286',1,'']]],
  ['class_20diagrams_20pyreverse_73',['Python Class Diagrams (pyreverse)',['../md_llm__prep_2codebase__overview.html#autotoc_md572',1,'']]],
  ['classes_74',['PR #2: Extract Large Classes',['../md_REFACTORING__NOTES.html#autotoc_md1019',1,'']]],
  ['claude_75',['Claude',['../md_API__PROVIDERS.html#autotoc_md107',1,'Anthropic (Claude)'],['../md_MODELS__FINAL.html#autotoc_md621',1,'Anthropic (Claude)'],['../md_README.html#autotoc_md889',1,'Anthropic (Claude)']]],
  ['claude_20s_20favorite_76',['1. Bash XML Tags (Claude&apos;s Favorite)',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md689',1,'']]],
  ['claude_20s_20natural_20format_77',['Example 1: Claude&apos;s Natural Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md683',1,'']]],
  ['claude_20security_20audit_78',['Example 2: Claude Security Audit',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1158',1,'']]],
  ['claude_20security_20focused_20build_20skill_79',['Claude Security-Focused Build Skill',['../md_skills_2claude__build.html',1,'']]],
  ['claude_20specific_20features_20in_20axe_80',['Anthropic Claude-Specific Features in AXE',['../md_docs_2ANTHROPIC__FEATURES.html',1,'']]],
  ['claude_20specific_20optimizations_20implementation_20summary_81',['Anthropic Claude-Specific Optimizations - Implementation Summary',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['claude_5fbuild_20md_2011_202kb_82',['skills/claude_build.md (11.2KB)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1148',1,'']]],
  ['clean_83',['6. &lt;b&gt;Dependencies &amp;amp; Git&lt;/b&gt; ✅ Clean',['../md_SECURITY__REPORT.html#autotoc_md1106',1,'']]],
  ['clean_20and_20build_20quietly_84',['Clean and build quietly',['../md_skills_2build.html#autotoc_md1195',1,'']]],
  ['cleanup_20✅_85',['Phase 5: Cleanup ✅',['../md_REFACTORING__NOTES.html#autotoc_md1007',1,'']]],
  ['cli_86',['Standalone CLI',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md591',1,'']]],
  ['cli_20commands_20missing_87',['2. CLI Commands Missing',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md710',1,'']]],
  ['clone_20and_20setup_88',['Clone and Setup',['../md_README.html#autotoc_md879',1,'']]],
  ['cmake_89',['CMake',['../md_skills_2build.html#autotoc_md1172',1,'CMake'],['../md_skills_2build.html#autotoc_md1191',1,'Example 1: C++ Project with CMake']]],
  ['cmd_3a_20str_20bool_20lines_201410_201458_90',['5. &lt;span class=&quot;tt&quot;&gt;_needs_shell(cmd: str) -&amp;gt; bool&lt;/span&gt; (Lines 1410-1458)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1116',1,'']]],
  ['cmd_3a_20str_20lines_201460_201542_91',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1117',1,'']]],
  ['cmd_3a_20str_20lines_201544_201629_92',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1118',1,'']]],
  ['cmd_3a_20str_20list_20str_20lines_201289_201408_93',['4. &lt;span class=&quot;tt&quot;&gt;_extract_commands_from_shell(cmd: str) -&amp;gt; List[str]&lt;/span&gt; (Lines 1289-1408)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1115',1,'']]],
  ['cmd_3a_20str_20str_20lines_201173_201287_94',['3. &lt;span class=&quot;tt&quot;&gt;_strip_heredoc_content(cmd: str) -&amp;gt; str&lt;/span&gt; (Lines 1173-1287)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1114',1,'']]],
  ['code_95',['Code',['../md_REFACTORING__NOTES.html#autotoc_md1022',1,'For Existing Code'],['../md_REFACTORING__NOTES.html#autotoc_md1023',1,'For New Code'],['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md284',1,'VS Code']]],
  ['code_20analysis_96',['Code Analysis',['../md_README.html#autotoc_md899',1,'Example: Multi-Agent Code Analysis'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1084',1,'Scenario 2: Code Analysis']]],
  ['code_20block_20format_97',['Example 2: Code Block Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md684',1,'']]],
  ['code_20block_20parser_98',['Code Block Parser',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1495',1,'']]],
  ['code_20blocks_99',['2. Shell Code Blocks',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md690',1,'']]],
  ['code_20changes_100',['Code Changes',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md22',1,'Code Changes'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md214',1,'Code Changes']]],
  ['code_20changes_20summary_101',['Code Changes Summary',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md430',1,'']]],
  ['code_20comments_20coverage_102',['Code Comments Coverage',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1124',1,'']]],
  ['code_20coverage_20report_103',['Code Coverage Report',['../md_workshop__test__results.html#autotoc_md1460',1,'']]],
  ['code_20flow_104',['Code Flow',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md403',1,'']]],
  ['code_20minifier_20implementation_20summary_105',['Source Code Minifier Implementation Summary',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['code_20quality_106',['Code Quality',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md440',1,'✅ Code Quality'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md78',1,'Code Quality'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md354',1,'Code Quality'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md673',1,'Code Quality'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1331',1,'Code Quality']]],
  ['code_20quality_209_2010_107',['🏆 Code Quality (9/10)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md702',1,'']]],
  ['code_20quality_20analysis_108',['Part 5: Code Quality Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md793',1,'']]],
  ['code_20review_109',['Code Review',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md82',1,'']]],
  ['code_20review_20addressed_110',['Code Review Addressed',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1138',1,'']]],
  ['code_20review_20checklist_111',['Code Review Checklist',['../md_AGENTS.html#autotoc_md65',1,'']]],
  ['code_20review_20issues_20addressed_112',['Code Review Issues Addressed',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md674',1,'']]],
  ['code_20snippet_20analysis_113',['Code Snippet Analysis',['../md_workshop__benchmarks.html#autotoc_md1350',1,'']]],
  ['code_20statistics_114',['Code Statistics',['../md_llm__prep_2codebase__overview.html#autotoc_md571',1,'']]],
  ['code_20structure_20excellent_115',['Code Structure - EXCELLENT',['../md_PR23__VALIDATION__REPORT.html#autotoc_md794',1,'']]],
  ['codebase_20exploration_116',['1. New Codebase Exploration',['../md_README.html#autotoc_md953',1,'']]],
  ['codebase_20overview_20—_202026_2001_2013_117',['LLM-Ready Codebase Overview — 2026-01-13',['../md_llm__prep_2codebase__overview.html',1,'']]],
  ['codebase_20preparation_118',['llmprep - Codebase Preparation',['../md_README.html#autotoc_md938',1,'']]],
  ['coding_20conventions_119',['Coding Conventions',['../md_AGENTS.html#autotoc_md49',1,'']]],
  ['collab_20mode_120',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['collab_20mode_20✅_121',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['collaboration_122',['Collaboration',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1161',1,'Example 3: Multi-Agent Collaboration'],['../md_skills_2build.html#autotoc_md1200',1,'Example 4: Multi-Agent Collaboration'],['../md_MODELS__FINAL.html#autotoc_md656',1,'Multi-Agent Collaboration'],['../md_README.html#autotoc_md931',1,'Multi-Agent Collaboration']]],
  ['collaboration_20features_20⚠️_20medium_123',['5. &lt;b&gt;Collaboration Features&lt;/b&gt; ⚠️ Medium',['../md_SECURITY__REPORT.html#autotoc_md1105',1,'']]],
  ['collaboration_20files_124',['Related Collaboration Files',['../md__8collab__shared.html#autotoc_md13',1,'']]],
  ['collaboration_20issues_125',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_BUG__FIX__SUMMARY.html',1,'']]],
  ['collaborations_126',['Integration with Collaborations',['../md_skills_2build.html#autotoc_md1179',1,'']]],
  ['collaborative_20mode_20tool_20syntax_20fix_20summary_127',['Collaborative Mode Tool Syntax Fix - Summary',['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html',1,'']]],
  ['collaborative_20problem_20solving_128',['Collaborative Problem Solving',['../md_README.html#autotoc_md935',1,'']]],
  ['collaborative_20session_20notes_129',['Collaborative Session Notes',['../md__8collab__shared.html',1,'']]],
  ['collaborative_20session_20pre_20indexing_130',['3. Collaborative Session Pre-indexing',['../md_README.html#autotoc_md955',1,'']]],
  ['collaborative_20session_20with_20new_20features_131',['Starting a Collaborative Session with New Features',['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'']]],
  ['collaborative_20sessions_20new_132',['Autonomous Collaborative Sessions (NEW!)',['../md_README.html#autotoc_md932',1,'']]],
  ['collaborativesession_133',['4. &lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt; (CollaborativeSession)',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md342',1,'']]],
  ['combine_20multiple_20security_20tools_20quietly_134',['5. Combine Multiple Security Tools Quietly',['../md_skills_2claude__build.html#autotoc_md1247',1,'']]],
  ['combine_20multiple_20silent_20flags_135',['4. Combine Multiple Silent Flags',['../md_skills_2build.html#autotoc_md1184',1,'']]],
  ['combine_20with_20newline_20e_20g_20cat_20eof_136',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['command_137',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['command_20–_20escalate_20properly_138',['3. Chain of Command – Escalate Properly',['../md_IMPROVEMENTS__FINAL.html#autotoc_md527',1,'']]],
  ['command_20execution_20⚠️_20medium_139',['2. &lt;b&gt;Command Execution&lt;/b&gt; ⚠️ Medium',['../md_SECURITY__REPORT.html#autotoc_md1102',1,'']]],
  ['command_20execution_20❌_20→_20✅_140',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md310',1,'']]],
  ['command_20fails_141',['Command Fails?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1526',1,'']]],
  ['command_20injection_20in_20hammer_20module_142',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['command_20line_20option_143',['Command Line Option',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md297',1,'']]],
  ['command_20line_20requires_20graphviz_144',['Command Line (Requires GraphViz)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md283',1,'']]],
  ['command_20mode_145',['Single Command Mode',['../md_README.html#autotoc_md895',1,'']]],
  ['command_3a_146',['Command:',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md412',1,'']]],
  ['commands_147',['Commands',['../md_IMPROVEMENTS__FINAL.html#autotoc_md538',1,'Agent Session Commands'],['../md_QUICK__REFERENCE.html#autotoc_md843',1,'Chat Commands'],['../md_QUICK__REFERENCE.html#autotoc_md842',1,'Commands'],['../md__8collab__env.html#autotoc_md8',1,'Documentation Commands'],['../md_README.html#autotoc_md965',1,'Management Commands'],['../md_workshop__quick__reference.html#autotoc_md1406',1,'Management Commands'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md537',1,'Quick Reference Commands'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md495',1,'Setup Commands']]],
  ['commands_20added_148',['Commands Added',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md449',1,'']]],
  ['commands_20during_20sessions_149',['New Agent Commands (During Sessions)',['../md_IMPROVEMENTS__README.html#autotoc_md554',1,'']]],
  ['commands_20expanded_150',['Workshop Commands (EXPANDED!)',['../md_README.html#autotoc_md904',1,'']]],
  ['commands_20for_20agents_151',['Safe Commands for Agents',['../md_IMPROVEMENTS__FINAL.html#autotoc_md532',1,'']]],
  ['commands_20missing_152',['2. CLI Commands Missing',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md710',1,'']]],
  ['commands_20new_153',['Token Usage Commands (NEW!)',['../md_README.html#autotoc_md902',1,'']]],
  ['commands_20now_20working_154',['Commands Now Working',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1132',1,'']]],
  ['commands_20reference_155',['Chat Commands Reference',['../md_README.html#autotoc_md901',1,'']]],
  ['commands_20work_20in_20whitelist_20mode_20but_20not_20sandbox_20mode_156',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['commented_20out_157',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md318',1,'']]],
  ['comments_158',['Comments',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md407',1,'3. Inline Comments'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1123',1,'Documentation &amp;amp; Comments']]],
  ['comments_20coverage_159',['Code Comments Coverage',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1124',1,'']]],
  ['commercial_20license_160',['Commercial License',['../md_README.html#autotoc_md986',1,'']]],
  ['common_161',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md1268',1,'']]],
  ['common_20issues_162',['Common Issues',['../md_API__PROVIDERS.html#autotoc_md157',1,'Common Issues'],['../md_README.html#autotoc_md977',1,'Common Issues']]],
  ['common_20modernizations_163',['Common Modernizations',['../md_skills_2c__modernization__expert.html#autotoc_md1205',1,'']]],
  ['common_20pitfalls_164',['Common Pitfalls',['../md_skills_2build.html#autotoc_md1186',1,'']]],
  ['common_20refactors_165',['Common Refactors',['../md_skills_2cpp__refactoring__expert.html#autotoc_md1266',1,'']]],
  ['common_20scenarios_166',['Common Scenarios',['../md_QUICK__REFERENCE.html#autotoc_md856',1,'']]],
  ['common_20security_20build_20patterns_167',['Common Security Build Patterns',['../md_skills_2claude__build.html#autotoc_md1253',1,'']]],
  ['common_20tasks_168',['Common Tasks',['../md_skills_2python__agent__expert.html#autotoc_md1281',1,'']]],
  ['communication_20example_169',['Model Communication Example',['../md_MODELS__FINAL.html#autotoc_md657',1,'']]],
  ['communication_20tokens_170',['Agent Communication Tokens',['../md_MISSION.html#autotoc_md605',1,'']]],
  ['comparative_20analysis_171',['Comparative Analysis',['../md_workshop__benchmarks.html#autotoc_md1358',1,'']]],
  ['compared_20to_20whitelist_20mode_172',['Compared to Whitelist Mode',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1073',1,'']]],
  ['comparison_173',['Comparison',['../md_workshop__test__results.html#autotoc_md1466',1,'Historical Comparison'],['../md_workshop__benchmarks.html#autotoc_md1359',1,'Tool Efficiency Comparison']]],
  ['comparison_20of_20fixes_174',['Before/After Comparison of Fixes',['../md_BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['compatibility_175',['Compatibility',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md709',1,'1. Test Compatibility'],['../md_workshop__dependency__validation.html#autotoc_md1389',1,'AXE Framework Compatibility'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md35',1,'Backward Compatibility'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md86',1,'Backward Compatibility'],['../md_BUG__FIX__SUMMARY.html#autotoc_md206',1,'Backward Compatibility'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md239',1,'Backward Compatibility'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md268',1,'Backward Compatibility'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md353',1,'Backward Compatibility'],['../md_FIXES__SUMMARY.html#autotoc_md384',1,'Backward Compatibility'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md680',1,'Backward Compatibility'],['../md_REFACTORING__NOTES.html#autotoc_md1010',1,'Backward Compatibility'],['../md_SANDBOX.html#autotoc_md1035',1,'Backward Compatibility'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1075',1,'Backward Compatibility'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1527',1,'Backward Compatibility'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md331',1,'Example 3: Backward Compatibility'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md87',1,'Guaranteed Compatibility']]],
  ['compatibility_20matrix_176',['Compatibility Matrix',['../md_workshop__dependency__validation.html#autotoc_md1375',1,'']]],
  ['compatible_20api_177',['Usage - OpenAI-Compatible API',['../md_MODELS__FINAL.html#autotoc_md630',1,'']]],
  ['compile_20with_20addresssanitizer_20for_20runtime_20detection_178',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md1237',1,'']]],
  ['compile_20with_20asan_20and_20run_20tests_20silently_179',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md1220',1,'']]],
  ['complete_180',['COMPLETE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md782',1,'Configuration Integration - COMPLETE'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md780',1,'Database Integration - COMPLETE'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md72',1,'Implementation Status: ✅ COMPLETE'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md783',1,'Module Structure - COMPLETE'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md781',1,'XP System Integration - COMPLETE']]],
  ['complete_20✅_181',['AXE Enhancement Implementation - Complete ✅',['../md_IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['complete_20axe_20integration_182',['✅ Complete AXE Integration',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md698',1,'']]],
  ['complete_20detection_20✅_183',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1320',1,'']]],
  ['completed_184',['Immediate Actions (Completed)',['../md_workshop__security__audit.html#autotoc_md1444',1,'']]],
  ['compliance_185',['Compliance',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1295',1,'2. AGENTS.md Standard Compliance'],['../md_workshop__security__audit.html#autotoc_md1442',1,'Security Standards Compliance']]],
  ['compliance_20assessment_186',['Compliance Assessment',['../md_workshop__security__audit.html#autotoc_md1441',1,'']]],
  ['component_20overview_187',['Component Overview',['../md_SANDBOX.html#autotoc_md1046',1,'']]],
  ['components_188',['Core Components',['../md_AGENTS.html#autotoc_md61',1,'']]],
  ['comprehensive_189',['Documentation - COMPREHENSIVE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md797',1,'']]],
  ['comprehensive_20coverage_190',['Comprehensive Coverage',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md90',1,'']]],
  ['comprehensive_20documentation_191',['✅ Comprehensive Documentation',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md699',1,'']]],
  ['comprehensive_20documentation_20✅_192',['6. Comprehensive Documentation ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md428',1,'']]],
  ['comprehensive_20security_20scan_20with_20minimal_20noise_193',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md1248',1,'']]],
  ['comprehensive_20test_20suite_194',['4. Comprehensive Test Suite',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md408',1,'']]],
  ['comprehensive_20test_20suite_20tests_20test_5fskills_5fmanager_20py_195',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1302',1,'']]],
  ['comprehensive_20testing_196',['4. Comprehensive Testing',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1149',1,'']]],
  ['comprehensive_20validation_20report_197',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_PR23__VALIDATION__REPORT.html',1,'']]],
  ['compression_20warnings_198',['Compression Warnings',['../md_README.html#autotoc_md909',1,'']]],
  ['conclusion_199',['Conclusion',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md39',1,'Conclusion'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md102',1,'Conclusion'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md218',1,'Conclusion'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md335',1,'Conclusion'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md418',1,'Conclusion'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md457',1,'Conclusion'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md472',1,'Conclusion'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1096',1,'Conclusion'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1164',1,'Conclusion'],['../md_workshop__dependency__validation.html#autotoc_md1398',1,'Conclusion'],['../md_workshop__security__audit.html#autotoc_md1446',1,'Conclusion'],['../md_workshop__test__results.html#autotoc_md1476',1,'Conclusion'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1513',1,'Conclusion'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md816',1,'Part 10: Validation Conclusion']]],
  ['condition_20in_20database_20operations_200',['Issue #4: Race Condition in Database Operations',['../md_workshop__security__audit.html#autotoc_md1427',1,'']]],
  ['config_20✅_20low_201',['3. &lt;b&gt;YAML Config&lt;/b&gt; ✅ Low',['../md_SECURITY__REPORT.html#autotoc_md1103',1,'']]],
  ['config_20project_5fdir_3a_20str_20lines_201150_201171_202',['2. &lt;span class=&quot;tt&quot;&gt;__init__(config: Config, project_dir: str)&lt;/span&gt; (Lines 1150-1171)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1113',1,'']]],
  ['config_3a_20config_20project_5fdir_3a_20str_20lines_201150_201171_203',['2. &lt;span class=&quot;tt&quot;&gt;__init__(config: Config, project_dir: str)&lt;/span&gt; (Lines 1150-1171)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1113',1,'']]],
  ['configuration_204',['Configuration',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md247',1,'Configuration'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md253',1,'Configuration'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md258',1,'Configuration'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md263',1,'Configuration'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md296',1,'Configuration'],['../md_MODELS__FINAL.html#autotoc_md622',1,'Configuration'],['../md_MODELS__FINAL.html#autotoc_md628',1,'Configuration'],['../md_MODELS__FINAL.html#autotoc_md635',1,'Configuration'],['../md_MODELS__FINAL.html#autotoc_md641',1,'Configuration'],['../md_MODELS__FINAL.html#autotoc_md648',1,'Configuration'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md727',1,'Configuration'],['../md_README.html#autotoc_md881',1,'Configuration'],['../md_README.html#autotoc_md968',1,'Configuration'],['../md_SANDBOX.html#autotoc_md1033',1,'Configuration'],['../md_workshop__quick__reference.html#autotoc_md1409',1,'Configuration']]],
  ['configuration_20example_205',['Configuration Example',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1070',1,'']]],
  ['configuration_20file_206',['Configuration file',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1507',1,'']]],
  ['configuration_20file_20axe_20yaml_207',['Configuration File (axe.yaml)',['../md_README.html#autotoc_md883',1,'']]],
  ['configuration_20files_208',['Configuration Files',['../md_AGENTS.html#autotoc_md62',1,'']]],
  ['configuration_20integration_209',['Claim 4: Configuration Integration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md763',1,'']]],
  ['configuration_20integration_20complete_210',['Configuration Integration - COMPLETE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md782',1,'']]],
  ['configuration_20options_211',['Configuration Options',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md595',1,'']]],
  ['configuration_20reference_212',['Configuration Reference',['../md_MODELS__FINAL.html',1,'AXE Multi-Agent System - Model Configuration Reference'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md267',1,'Configuration Reference']]],
  ['configuration_20structure_213',['✅ VALIDATED - Configuration Structure',['../md_PR23__VALIDATION__REPORT.html#autotoc_md764',1,'']]],
  ['configuration_20updates_214',['5. Configuration Updates',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1298',1,'']]],
  ['configure_215',['Autoconf/Configure',['../md_skills_2build.html#autotoc_md1171',1,'']]],
  ['configure_20with_20quiet_20flags_216',['Configure with quiet flags',['../md_skills_2build.html#autotoc_md1192',1,'']]],
  ['configure_20with_20security_20flags_217',['Configure with security flags',['../md_skills_2claude__build.html#autotoc_md1230',1,'']]],
  ['confused_218',['&quot;Agent stuck or confused&quot;',['../md_QUICK__REFERENCE.html#autotoc_md858',1,'']]],
  ['confused_20about_20read_20write_20block_20syntax_219',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['confused_20about_20read_20write_20block_20syntax_20✅_220',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['connection_221',['Test Connection',['../md_MODELS__FINAL.html#autotoc_md619',1,'']]],
  ['connections_222',['Testing API Connections',['../md_README.html#autotoc_md978',1,'']]],
  ['considerations_223',['Considerations',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md240',1,'Future Considerations'],['../md_workshop__quick__reference.html#autotoc_md1415',1,'Safety Considerations'],['../md_AGENTS.html#autotoc_md66',1,'Security Considerations'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md93',1,'Security Considerations'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md306',1,'Security Considerations'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md358',1,'Security Considerations'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md417',1,'Security Considerations']]],
  ['constants_20lines_201121_201148_224',['1. Class Constants (Lines 1121-1148)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1112',1,'']]],
  ['contact_20support_225',['Contact &amp;amp; Support',['../md_AGENTS.html#autotoc_md68',1,'']]],
  ['contains_20a_20heredoc_226',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['content_227',['2. BUILD GUIDELINES Content',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1145',1,'']]],
  ['contents_228',['Contents',['../md_API__PROVIDERS.html#autotoc_md105',1,'Table of Contents'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md475',1,'Table of Contents'],['../md_MODELS__FINAL.html#autotoc_md615',1,'Table of Contents'],['../md_README.html#autotoc_md864',1,'Table of Contents']]],
  ['context_20files_229',['LLM Context Files',['../md_llm__prep_2codebase__overview.html#autotoc_md574',1,'']]],
  ['contributing_230',['Contributing',['../md_AGENTS.html#autotoc_md63',1,'Contributing'],['../md_ARCHITECTURE.html#autotoc_md171',1,'Contributing'],['../md_MISSION.html#autotoc_md611',1,'Contributing'],['../md_README.html#autotoc_md982',1,'Contributing']]],
  ['control_231',['Control',['../md_SANDBOX.html#autotoc_md1031',1,'3. Filesystem Access Control'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1066',1,'3. Filesystem Access Control'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1488',1,'Directory Access Control'],['../md_README.html#autotoc_md920',1,'Version Control']]],
  ['controls_20verified_232',['Resource Controls - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md788',1,'']]],
  ['conventions_233',['Coding Conventions',['../md_AGENTS.html#autotoc_md49',1,'']]],
  ['conversations_234',['Basic Agent Conversations',['../md_README.html#autotoc_md894',1,'']]],
  ['cooperating_235',['&quot;Agents not cooperating&quot;',['../md_QUICK__REFERENCE.html#autotoc_md857',1,'']]],
  ['coordination_236',['Agent Coordination',['../md__8collab__shared.html#autotoc_md14',1,'']]],
  ['copilot_237',['GitHub Models - Free with Copilot',['../md_README.html#autotoc_md887',1,'']]],
  ['core_20agent_5fmanager_20py_238',['3. &lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md341',1,'']]],
  ['core_20build_20systems_239',['Core Build Systems',['../md_skills_2claude__build.html#autotoc_md1211',1,'']]],
  ['core_20changes_240',['Core Changes',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md223',1,'']]],
  ['core_20components_241',['Core Components',['../md_AGENTS.html#autotoc_md61',1,'']]],
  ['core_20dependencies_242',['Core Dependencies',['../md_workshop__dependency__validation.html#autotoc_md1365',1,'Core Dependencies'],['../md_workshop__security__audit.html#autotoc_md1436',1,'Core Dependencies']]],
  ['core_20functionality_243',['Core Functionality',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md586',1,'']]],
  ['core_20principles_244',['Core Principles',['../md_MISSION.html#autotoc_md604',1,'Core Principles'],['../md_skills_2c__modernization__expert.html#autotoc_md1204',1,'Core Principles'],['../md_skills_2cpp__modernization__expert.html#autotoc_md1261',1,'Core Principles'],['../md_skills_2cpp__refactoring__expert.html#autotoc_md1265',1,'Core Principles'],['../md_skills_2ida__pro__analysis__patterns.html#autotoc_md1275',1,'Core Principles'],['../md_skills_2python__agent__expert.html#autotoc_md1279',1,'Core Principles'],['../md_skills_2reverse__engineering__expert.html#autotoc_md1283',1,'Core Principles'],['../md_skills_2x86__assembly__expert.html#autotoc_md1287',1,'Core Principles']]],
  ['core_20safety_20features_245',['Core Safety Features',['../md_IMPROVEMENTS__FINAL.html#autotoc_md477',1,'']]],
  ['core_20skills_20manager_20core_20skills_5fmanager_20py_246',['1. Core Skills Manager (&lt;span class=&quot;tt&quot;&gt;core/skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1294',1,'']]],
  ['core_20skills_5fmanager_20py_247',['1. Core Skills Manager (&lt;span class=&quot;tt&quot;&gt;core/skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1294',1,'']]],
  ['count_248',['Line Count',['../md_REFACTORING__NOTES.html#autotoc_md1014',1,'']]],
  ['counter_20✅_249',['Bug 2: Active Agents Counter ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1325',1,'']]],
  ['counting_250',['3. Token Counting',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md257',1,'']]],
  ['counting_20fails_251',['Token counting fails',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md275',1,'']]],
  ['counting_20precise_20estimates_20✅_252',['3. Token Counting (Precise Estimates) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md76',1,'']]],
  ['coverage_253',['Coverage',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1152',1,'Agent Coverage'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1124',1,'Code Comments Coverage'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md90',1,'Comprehensive Coverage'],['../md_workshop__benchmarks.html#autotoc_md1354',1,'Enumeration Coverage'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md24',1,'Test Coverage'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md81',1,'Test Coverage'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md324',1,'Test Coverage'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md677',1,'Test Coverage'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1069',1,'Test Coverage'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1127',1,'Test Coverage']]],
  ['coverage_20analysis_254',['Part 6: Test Coverage Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md799',1,'']]],
  ['coverage_20report_255',['Code Coverage Report',['../md_workshop__test__results.html#autotoc_md1460',1,'']]],
  ['cppcheck_20for_20c_20c_20issues_256',['Cppcheck for C/C++ issues',['../md_skills_2claude__build.html#autotoc_md1233',1,'']]],
  ['cppcheck_20static_20analysis_257',['Cppcheck (Static Analysis)',['../md_skills_2claude__build.html#autotoc_md1216',1,'']]],
  ['cppcheck_20with_20full_20details_258',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md1236',1,'']]],
  ['cpu_20usage_259',['CPU Usage',['../md_workshop__dependency__validation.html#autotoc_md1383',1,'']]],
  ['create_20directory_20structure_20✅_260',['Phase 1: Create Directory Structure ✅',['../md_REFACTORING__NOTES.html#autotoc_md1003',1,'']]],
  ['create_20parent_20dirs_20if_20needed_261',['Create parent dirs if needed',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md466',1,'']]],
  ['created_262',['Created',['../md_PR23__VALIDATION__REPORT.html#autotoc_md800',1,'Custom Validation Tests Created'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md580',1,'Files Created'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1061',1,'Files Created'],['../md_FIXES__SUMMARY.html#autotoc_md374',1,'Unit Tests Created']]],
  ['created_205_263',['Files Created (5)',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md79',1,'']]],
  ['created_20skills_20directory_20and_20files_264',['3. Created Skills Directory and Files',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1146',1,'']]],
  ['creating_20new_20skills_265',['Creating New Skills',['../md_AGENTS.html#autotoc_md55',1,'']]],
  ['credits_266',['Credits',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1342',1,'Attributions &amp;amp; Credits'],['../md_IMPROVEMENTS__README.html#autotoc_md566',1,'Credits']]],
  ['credits_20error_267',['No Credits Error',['../md_MODELS__FINAL.html#autotoc_md662',1,'']]],
  ['criteria_268',['Criteria',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md598',1,'Acceptance Criteria'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md101',1,'Success Criteria'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1511',1,'Success Criteria']]],
  ['criteria_20✓_269',['Success Criteria ✓',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1309',1,'']]],
  ['criteria_20all_20met_270',['Success Criteria (All Met)',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1334',1,'']]],
  ['criteria_20met_271',['Criteria Met',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md238',1,'Success Criteria Met'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1163',1,'Success Criteria Met']]],
  ['critical_272',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md460',1,'']]],
  ['critical_20issues_20found_20re_20run_20with_20full_20details_3a_273',['If critical issues found, re-run with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'']]],
  ['cross_20tool_20interactions_274',['Cross-Tool Interactions',['../md_workshop__dependency__validation.html#autotoc_md1390',1,'']]],
  ['curl_20example_275',['cURL Example',['../md_API__PROVIDERS.html#autotoc_md130',1,'Chat-style cURL Example'],['../md_API__PROVIDERS.html#autotoc_md111',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md119',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md129',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md138',1,'cURL Example'],['../md_API__PROVIDERS.html#autotoc_md147',1,'cURL Example']]],
  ['current_276',['v1.0 (Current)',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1498',1,'']]],
  ['curve_20hybrid_20linear_20exponential_277',['Progression Curve (Hybrid Linear/Exponential)',['../md_IMPROVEMENTS__FINAL.html#autotoc_md519',1,'']]],
  ['custom_20project_20directory_278',['Custom Project Directory',['../md_README.html#autotoc_md926',1,'']]],
  ['custom_20system_20prompts_279',['Custom System Prompts',['../md_README.html#autotoc_md929',1,'']]],
  ['custom_20validation_20suite_280',['Custom Validation Suite',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md714',1,'']]],
  ['custom_20validation_20tests_20created_281',['Custom Validation Tests Created',['../md_PR23__VALIDATION__REPORT.html#autotoc_md800',1,'']]]
];
