var searchData=
[
  ['o_0',['Disk I/O',['../md_workshop__dependency__validation.html#autotoc_md1384',1,'']]],
  ['of_20all_20implemented_20features_1',['Summary of All Implemented Features',['../md_IMPROVEMENTS__README.html#autotoc_md568',1,'']]],
  ['of_20changes_2',['Summary of Changes',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md192',1,'']]],
  ['of_20command_20–_20escalate_20properly_3',['3. Chain of Command – Escalate Properly',['../md_IMPROVEMENTS__FINAL.html#autotoc_md527',1,'']]],
  ['of_20contents_4',['of Contents',['../md_API__PROVIDERS.html#autotoc_md105',1,'Table of Contents'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md475',1,'Table of Contents'],['../md_MODELS__FINAL.html#autotoc_md615',1,'Table of Contents'],['../md_README.html#autotoc_md864',1,'Table of Contents']]],
  ['of_20duplicate_20execution_20before_20fix_5',['Example of Duplicate Execution (Before Fix)',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'']]],
  ['of_20fixes_6',['Before/After Comparison of Fixes',['../md_BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['of_20sensitive_20data_7',['Finding #5: Logging of Sensitive Data',['../md_workshop__security__audit.html#autotoc_md1434',1,'']]],
  ['of_20the_20problem_8',['Evidence of the Problem',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md19',1,'']]],
  ['of_20thought_9',['Chain of Thought',['../md_README.html#autotoc_md934',1,'']]],
  ['off_10',['Off',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md740',1,'Sign-Off'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md829',1,'Validation Sign-Off']]],
  ['ollama_20integration_20local_20models_11',['Ollama Integration (Local Models)',['../md_ARCHITECTURE.html#autotoc_md168',1,'']]],
  ['on_20failure_12',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md1182',1,'']]],
  ['on_20security_20relevant_20output_13',['2. Focus on Security-Relevant Output',['../md_skills_2claude__build.html#autotoc_md1242',1,'']]],
  ['on_20whistleblower_20feature_14',['Note on Whistleblower Feature',['../md_README.html#autotoc_md870',1,'']]],
  ['one_20present_3a_20use_20whichever_20exists_15',['Only one present: use whichever exists',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md392',1,'']]],
  ['one_20response_16',['4. Multiple Files in One Response',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1485',1,'']]],
  ['online_20no_20installation_20required_17',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md282',1,'']]],
  ['only_18',['Quick security scan (high severity only)',['../md_skills_2claude__build.html#autotoc_md1226',1,'']]],
  ['only_20high_20severity_20findings_19',['Good: Only high-severity findings',['../md_skills_2claude__build.html#autotoc_md1244',1,'']]],
  ['only_20one_20present_3a_20use_20whichever_20exists_20',['Only one present: use whichever exists',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md392',1,'']]],
  ['only_20security_20warnings_21',['Good: Only security warnings',['../md_skills_2claude__build.html#autotoc_md1243',1,'']]],
  ['open_20source_20license_20default_22',['Open Source License (Default)',['../md_README.html#autotoc_md985',1,'']]],
  ['openai_20compatible_20api_23',['Usage - OpenAI-Compatible API',['../md_MODELS__FINAL.html#autotoc_md630',1,'']]],
  ['openai_20gpt_24',['OpenAI GPT',['../md_API__PROVIDERS.html#autotoc_md115',1,'OpenAI (GPT)'],['../md_MODELS__FINAL.html#autotoc_md634',1,'OpenAI (GPT)'],['../md_README.html#autotoc_md890',1,'OpenAI (GPT)']]],
  ['openai_20sdk_25',['OpenAI SDK',['../md_API__PROVIDERS.html#autotoc_md139',1,'Python Example (OpenAI SDK)'],['../md_API__PROVIDERS.html#autotoc_md148',1,'Python Example (OpenAI SDK)']]],
  ['operating_20system_20support_26',['Operating System Support',['../md_workshop__dependency__validation.html#autotoc_md1377',1,'']]],
  ['operations_27',['Issue #4: Race Condition in Database Operations',['../md_workshop__security__audit.html#autotoc_md1427',1,'']]],
  ['operator_20support_20implementation_20summary_28',['Shell Operator Support Implementation Summary',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html',1,'']]],
  ['opportunities_29',['Future Optimization Opportunities',['../md_workshop__benchmarks.html#autotoc_md1362',1,'']]],
  ['optimization_30',['Optimization',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1089',1,'']]],
  ['optimization_20opportunities_31',['Future Optimization Opportunities',['../md_workshop__benchmarks.html#autotoc_md1362',1,'']]],
  ['optimization_20strategies_32',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md165',1,'']]],
  ['optimizations_20implementation_20summary_33',['Anthropic Claude-Specific Optimizations - Implementation Summary',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['optimizations_20new_34',['Token-Saving Optimizations (NEW!)',['../md_README.html#autotoc_md907',1,'']]],
  ['option_35',['Command Line Option',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md297',1,'']]],
  ['optional_20✅_36',['4. Files API (Beta, Optional) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md77',1,'']]],
  ['optional_20dependencies_37',['Optional Dependencies',['../md_README.html#autotoc_md943',1,'']]],
  ['optional_20future_38',['Optional (Future)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md738',1,'']]],
  ['optional_3a_20add_20more_20diet_20etc_20if_20tools_20expand_39',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['options_40',['Configuration Options',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md595',1,'']]],
  ['or_20confused_41',['&quot;Agent stuck or confused&quot;',['../md_QUICK__REFERENCE.html#autotoc_md858',1,'']]],
  ['order_42',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['original_43',['Markdown Format (Original)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1519',1,'']]],
  ['original_20test_20suite_20test_5ftool_5frunner_20py_44',['Original Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1128',1,'']]],
  ['original_20version_20_3a_45',['Execution (original version):',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md414',1,'']]],
  ['other_20blocks_46',['Integration with Other Blocks',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1486',1,'']]],
  ['out_47',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md318',1,'']]],
  ['output_48',['Output',['../md_skills_2build.html#autotoc_md1187',1,'❌ Don&apos;t Remove All Output'],['../md_skills_2claude__build.html#autotoc_md1242',1,'2. Focus on Security-Relevant Output'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md251',1,'Example Output'],['../md_README.html#autotoc_md948',1,'Example Output'],['../md_AGENTS.html#autotoc_md59',1,'When to Use Verbose Output']]],
  ['output_20tokens_20implementation_20summary_49',['Dynamic Max Output Tokens Implementation Summary',['../md_DYNAMIC__TOKENS__SUMMARY.html',1,'']]],
  ['output_3a_50',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['overall_20assessment_51',['Overall Assessment',['../md_PR23__VALIDATION__REPORT.html#autotoc_md746',1,'']]],
  ['overall_20score_3a_209_204_2010_52',['Overall Score: 9.4/10',['../md_PR23__VALIDATION__REPORT.html#autotoc_md819',1,'']]],
  ['overall_20test_20statistics_53',['Overall Test Statistics',['../md_workshop__test__results.html#autotoc_md1458',1,'']]],
  ['overhead_54',['Overhead',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1088',1,'']]],
  ['overview_55',['Overview',['../md_MISSION.html#autotoc_md609',1,'Architecture Overview'],['../md_SANDBOX.html#autotoc_md1046',1,'Component Overview'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md71',1,'Overview'],['../md_BUG__FIX__SUMMARY.html#autotoc_md194',1,'Overview'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md244',1,'Overview'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md291',1,'Overview'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md337',1,'Overview'],['../md_FIXES__SUMMARY.html#autotoc_md361',1,'Overview'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md578',1,'Overview'],['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md687',1,'Overview'],['../md_README.html#autotoc_md866',1,'Overview'],['../md_README.html#autotoc_md958',1,'Overview'],['../md_REFACTORING__NOTES.html#autotoc_md992',1,'Overview'],['../md_SANDBOX.html#autotoc_md1027',1,'Overview'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1059',1,'Overview'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1109',1,'Overview'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1140',1,'Overview'],['../md_skills_2build.html#autotoc_md1166',1,'Overview'],['../md_skills_2claude__build.html#autotoc_md1208',1,'Overview'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1292',1,'Overview'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1319',1,'Overview'],['../md_workshop__quick__reference.html#autotoc_md1400',1,'Overview'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1478',1,'Overview'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1501',1,'Overview'],['../md_AGENTS.html#autotoc_md41',1,'Project Overview'],['../md_workshop__test__results.html#autotoc_md1450',1,'Test Suite Overview']]],
  ['overview_20—_202026_2001_2013_56',['LLM-Ready Codebase Overview — 2026-01-13',['../md_llm__prep_2codebase__overview.html',1,'']]]
];
