var searchData=
[
  ['packer_20detection_20report_0',['DOS Packer Detection Report',['../md_skills_2dos__packer__detector.html#autotoc_md1273',1,'']]],
  ['parameter_20error_20critical_1',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md460',1,'']]],
  ['parent_20dirs_20if_20needed_2',['Create parent dirs if needed',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md466',1,'']]],
  ['parentheses_3',['1. Subshells with Parentheses',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1120',1,'']]],
  ['parse_5faxe_5fnative_5fblocks_20response_20commented_20out_4',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md318',1,'']]],
  ['parser_5',['Code Block Parser',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1495',1,'']]],
  ['parser_20implementation_6',['Multi-Format Tool Call Parser Implementation',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'']]],
  ['parser_20implementation_20summary_7',['XML Function Call Parser - Implementation Summary',['../md_XML__PARSER__IMPLEMENTATION.html',1,'']]],
  ['parser_20quick_20reference_8',['Multi-Format Tool Call Parser - Quick Reference',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['parser_20test_20suite_9',['XML TOOL PARSER TEST SUITE',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1504',1,'']]],
  ['parsing_20bug_20fixes_10',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['part_2010_3a_20validation_20conclusion_11',['Part 10: Validation Conclusion',['../md_PR23__VALIDATION__REPORT.html#autotoc_md816',1,'']]],
  ['part_2011_3a_20merge_20recommendation_12',['Part 11: Merge Recommendation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md821',1,'']]],
  ['part_2012_3a_20risk_20assessment_13',['Part 12: Risk Assessment',['../md_PR23__VALIDATION__REPORT.html#autotoc_md825',1,'']]],
  ['part_201_3a_20pr_20claims_20vs_20actual_20implementation_14',['Part 1: PR Claims vs. Actual Implementation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md748',1,'']]],
  ['part_202_3a_20integration_20verification_15',['Part 2: Integration Verification',['../md_PR23__VALIDATION__REPORT.html#autotoc_md779',1,'']]],
  ['part_203_3a_20security_20validation_16',['Part 3: Security Validation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md785',1,'']]],
  ['part_204_3a_20performance_20validation_17',['Part 4: Performance Validation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md790',1,'']]],
  ['part_205_3a_20code_20quality_20analysis_18',['Part 5: Code Quality Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md793',1,'']]],
  ['part_206_3a_20test_20coverage_20analysis_19',['Part 6: Test Coverage Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md799',1,'']]],
  ['part_207_3a_20dependency_20analysis_20',['Part 7: Dependency Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md803',1,'']]],
  ['part_208_3a_20integration_20points_20summary_21',['Part 8: Integration Points Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md808',1,'']]],
  ['part_209_3a_20known_20issues_20limitations_22',['Part 9: Known Issues &amp;amp; Limitations',['../md_PR23__VALIDATION__REPORT.html#autotoc_md812',1,'']]],
  ['passed_23',['✅ ALL TESTS PASSED!',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1506',1,'']]],
  ['passed_24',['Passed',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md434',1,'✅ Integration Tests Passed'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md433',1,'✅ Unit Tests Passed']]],
  ['path_25',['Path',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md88',1,'Migration Path'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1077',1,'Migration Path']]],
  ['path_20errors_26',['Path Errors?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1525',1,'']]],
  ['path_20file_20handling_20✅_20fixed_27',['1. &lt;b&gt;Path &amp;amp; File Handling&lt;/b&gt; ✅ Fixed',['../md_SECURITY__REPORT.html#autotoc_md1101',1,'']]],
  ['path_20fix_20implementation_20summary_28',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['path_20handling_29',['pathlib (Path Handling)',['../md_workshop__dependency__validation.html#autotoc_md1374',1,'']]],
  ['pathlib_20path_20handling_30',['pathlib (Path Handling)',['../md_workshop__dependency__validation.html#autotoc_md1374',1,'']]],
  ['pattern_201_3a_20hardening_20flags_20silent_20build_31',['Pattern 1: Hardening Flags (Silent Build)',['../md_skills_2claude__build.html#autotoc_md1254',1,'']]],
  ['pattern_202_3a_20security_20tool_20chain_20silent_32',['Pattern 2: Security Tool Chain (Silent)',['../md_skills_2claude__build.html#autotoc_md1255',1,'']]],
  ['pattern_203_3a_20regression_20testing_20silent_33',['Pattern 3: Regression Testing (Silent)',['../md_skills_2claude__build.html#autotoc_md1256',1,'']]],
  ['pattern_204_3a_20fuzzing_20setup_20silent_34',['Pattern 4: Fuzzing Setup (Silent)',['../md_skills_2claude__build.html#autotoc_md1257',1,'']]],
  ['patterns_35',['Patterns',['../md_skills_2claude__build.html#autotoc_md1253',1,'Common Security Build Patterns'],['../md_skills_2x86__assembly__expert.html#autotoc_md1288',1,'Key Analysis Patterns']]],
  ['penetration_20testing_20results_36',['Penetration Testing Results',['../md_workshop__security__audit.html#autotoc_md1438',1,'']]],
  ['per_20agent_20workspace_37',['Per-Agent Workspace',['../md_IMPROVEMENTS__FINAL.html#autotoc_md533',1,'']]],
  ['performance_38',['Performance',['../md_workshop__benchmarks.html#autotoc_md1347',1,'Binary Analysis Performance'],['../md_workshop__benchmarks.html#autotoc_md1356',1,'Process Instrumentation Performance']]],
  ['performance_20analysis_20results_39',['Performance Analysis Results',['../md_workshop__benchmarks.html#autotoc_md1344',1,'']]],
  ['performance_20benchmarks_40',['Performance Benchmarks',['../md_PR23__VALIDATION__REPORT.html#autotoc_md769',1,'Document 2: Performance Benchmarks'],['../md_workshop__test__results.html#autotoc_md1461',1,'Performance Benchmarks']]],
  ['performance_20characteristics_41',['Performance Characteristics',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md718',1,'']]],
  ['performance_20impact_42',['Performance Impact',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md269',1,'Performance Impact'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md359',1,'Performance Impact'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1087',1,'Performance Impact']]],
  ['performance_20impact_20analysis_43',['Performance Impact Analysis',['../md_workshop__dependency__validation.html#autotoc_md1381',1,'']]],
  ['performance_20metrics_44',['Performance Metrics',['../md_PR23__VALIDATION__REPORT.html#autotoc_md791',1,'Claimed Performance Metrics'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md83',1,'Performance Metrics']]],
  ['performance_20results_45',['Performance Results',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md582',1,'']]],
  ['performance_20rewards_20–_20good_20work_20gets_20recognized_46',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_IMPROVEMENTS__FINAL.html#autotoc_md528',1,'']]],
  ['performance_20test_20results_20test_5fworkshop_5fperformance_20py_47',['Performance Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_performance.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1456',1,'']]],
  ['performance_20validation_48',['Part 4: Performance Validation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md790',1,'']]],
  ['peripheral_5fregister_5fpatterns_49',['peripheral_register_patterns',['../md_skills_2peripheral__register__patterns.html',1,'']]],
  ['permission_20based_20sleep_20system_50',['Permission-Based Sleep System',['../md_IMPROVEMENTS__FINAL.html#autotoc_md478',1,'']]],
  ['permission_20denied_20errors_20inside_20sandbox_51',['&quot;Permission denied&quot; errors inside sandbox',['../md_SANDBOX.html#autotoc_md1054',1,'']]],
  ['permissions_52',['Security and Permissions',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1487',1,'']]],
  ['permissions_53',['Check permissions',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md465',1,'']]],
  ['persistence_20strategy_54',['Persistence Strategy',['../md_IMPROVEMENTS__README.html#autotoc_md564',1,'']]],
  ['persistent_20sqlite_20storage_20✅_55',['Phase 4: Persistent SQLite Storage ✅',['../md_IMPROVEMENTS__README.html#autotoc_md546',1,'']]],
  ['persistent_20storage_56',['Persistent Storage',['../md_IMPROVEMENTS__FINAL.html#autotoc_md508',1,'']]],
  ['phase_2010_3a_20dynamic_20spawning_20✅_57',['Phase 10: Dynamic Spawning ✅',['../md_IMPROVEMENTS__README.html#autotoc_md553',1,'']]],
  ['phase_201_3a_20create_20directory_20structure_20✅_58',['Phase 1: Create Directory Structure ✅',['../md_REFACTORING__NOTES.html#autotoc_md1003',1,'']]],
  ['phase_201_3a_20initial_20silent_20build_59',['Phase 1: Initial Silent Build',['../md_skills_2claude__build.html#autotoc_md1229',1,'']]],
  ['phase_201_3a_20session_20rules_20guidelines_20✅_60',['Phase 1: Session Rules &amp;amp; Guidelines ✅',['../md_IMPROVEMENTS__README.html#autotoc_md543',1,'']]],
  ['phase_202_3a_20agent_20aliasing_20system_20✅_61',['Phase 2: Agent Aliasing System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md544',1,'']]],
  ['phase_202_3a_20extract_20functions_20✅_62',['Phase 2: Extract Functions ✅',['../md_REFACTORING__NOTES.html#autotoc_md1004',1,'']]],
  ['phase_202_3a_20static_20analysis_20silent_63',['Phase 2: Static Analysis (Silent)',['../md_skills_2claude__build.html#autotoc_md1232',1,'']]],
  ['phase_203_3a_20detailed_20investigation_20verbose_64',['Phase 3: Detailed Investigation (Verbose)',['../md_skills_2claude__build.html#autotoc_md1235',1,'']]],
  ['phase_203_3a_20experience_20level_20system_20✅_65',['Phase 3: Experience &amp;amp; Level System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md545',1,'']]],
  ['phase_203_3a_20update_20imports_20✅_66',['Phase 3: Update Imports ✅',['../md_REFACTORING__NOTES.html#autotoc_md1005',1,'']]],
  ['phase_204_3a_20persistent_20sqlite_20storage_20✅_67',['Phase 4: Persistent SQLite Storage ✅',['../md_IMPROVEMENTS__README.html#autotoc_md546',1,'']]],
  ['phase_204_3a_20security_20report_68',['Phase 4: Security Report',['../md_skills_2claude__build.html#autotoc_md1238',1,'']]],
  ['phase_204_3a_20testing_20✅_69',['Phase 4: Testing ✅',['../md_REFACTORING__NOTES.html#autotoc_md1006',1,'']]],
  ['phase_205_3a_20cleanup_20✅_70',['Phase 5: Cleanup ✅',['../md_REFACTORING__NOTES.html#autotoc_md1007',1,'']]],
  ['phase_205_3a_20resource_20tracking_20✅_71',['Phase 5: Resource Tracking ✅',['../md_IMPROVEMENTS__README.html#autotoc_md547',1,'']]],
  ['phase_206_3a_20mandatory_20sleep_20system_20✅_72',['Phase 6: Mandatory Sleep System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md549',1,'']]],
  ['phase_207_3a_20degradation_20monitoring_20✅_73',['Phase 7: Degradation Monitoring ✅',['../md_IMPROVEMENTS__README.html#autotoc_md550',1,'']]],
  ['phase_208_3a_20emergency_20mailbox_20✅_74',['Phase 8: Emergency Mailbox ✅',['../md_IMPROVEMENTS__README.html#autotoc_md551',1,'']]],
  ['phase_209_3a_20break_20system_20✅_75',['Phase 9: Break System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md552',1,'']]],
  ['phases_201_205_76',['Implemented Features (Phases 1-5)',['../md_IMPROVEMENTS__README.html#autotoc_md542',1,'']]],
  ['phases_206_2010_77',['Implemented Features (Phases 6-10)',['../md_IMPROVEMENTS__README.html#autotoc_md548',1,'']]],
  ['pinned_20message_20_3a_78',['Display at session start (pinned message):',['../md_IMPROVEMENTS__FINAL.html#autotoc_md524',1,'']]],
  ['pinning_79',['Finding #4: Dependency Version Pinning',['../md_workshop__security__audit.html#autotoc_md1433',1,'']]],
  ['pitfalls_80',['Common Pitfalls',['../md_skills_2build.html#autotoc_md1186',1,'']]],
  ['pklite_81',['Then PKLITE',['../md_skills_2dos__packer__detector.html#autotoc_md1269',1,'']]],
  ['plan_82',['Rollback Plan',['../md_PR23__VALIDATION__REPORT.html#autotoc_md827',1,'']]],
  ['plane_20source_20sink_20enumeration_83',['Plane Source Sink Enumeration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md752',1,'✅ VALIDATED - Plane (Source/Sink Enumeration)'],['../md_README.html#autotoc_md963',1,'Plane - Source/Sink Enumeration'],['../md_workshop__quick__reference.html#autotoc_md1404',1,'Plane - Source/Sink Enumeration']]],
  ['plane_20source_20sink_20enumeration_20benchmarks_84',['Plane - Source/Sink Enumeration Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1352',1,'']]],
  ['plugin_20system_85',['Plugin System',['../md_ARCHITECTURE.html#autotoc_md170',1,'']]],
  ['points_86',['Points',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md97',1,'Extension Points'],['../md_ARCHITECTURE.html#autotoc_md161',1,'Key Extension Points']]],
  ['points_20summary_87',['Part 8: Integration Points Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md808',1,'']]],
  ['post_20fix_88',['Key Findings (Post-Fix)',['../md_SECURITY__REPORT.html#autotoc_md1100',1,'']]],
  ['post_20merge_20actions_89',['Post-Merge Actions',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md735',1,'']]],
  ['post_20merge_20recommendations_90',['Post-Merge Recommendations',['../md_PR23__VALIDATION__REPORT.html#autotoc_md823',1,'']]],
  ['potential_20command_20injection_20in_20hammer_20module_91',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['potential_20improvements_92',['Potential Improvements',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1091',1,'']]],
  ['pr_2023_20workshop_20dynamic_20analysis_20framework_20comprehensive_20validation_20report_93',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_PR23__VALIDATION__REPORT.html',1,'']]],
  ['pr_2023_20workshop_20dynamic_20analysis_20framework_20executive_20summary_94',['PR #23 Workshop Dynamic Analysis Framework - Executive Summary',['../md_PR23__EXECUTIVE__SUMMARY.html',1,'']]],
  ['pr_202_3a_20extract_20large_20classes_95',['PR #2: Extract Large Classes',['../md_REFACTORING__NOTES.html#autotoc_md1019',1,'']]],
  ['pr_203_3a_20extract_20session_20management_96',['PR #3: Extract Session Management',['../md_REFACTORING__NOTES.html#autotoc_md1020',1,'']]],
  ['pr_20claims_20vs_20actual_20implementation_97',['Part 1: PR Claims vs. Actual Implementation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md748',1,'']]],
  ['pr_20test_20files_98',['PR Test Files',['../md_PR23__VALIDATION__REPORT.html#autotoc_md801',1,'']]],
  ['pr_20test_20suite_99',['PR Test Suite',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md715',1,'']]],
  ['practices_100',['Practices',['../md_IMPROVEMENTS__FINAL.html#autotoc_md510',1,'Best Practices'],['../md_skills_2build.html#autotoc_md1180',1,'Best Practices'],['../md_skills_2python__agent__expert.html#autotoc_md1280',1,'Best Practices'],['../md_skills_2reverse__engineering__expert.html#autotoc_md1285',1,'Best Practices'],['../md_skills_2x86__assembly__expert.html#autotoc_md1290',1,'Best Practices'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1496',1,'Best Practices'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md92',1,'Security &amp;amp; Best Practices']]],
  ['practices_20applied_101',['Best Practices Applied',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md94',1,'']]],
  ['practices_20for_20security_20audits_102',['Best Practices for Security Audits',['../md_skills_2claude__build.html#autotoc_md1240',1,'']]],
  ['pre_20indexing_103',['3. Collaborative Session Pre-indexing',['../md_README.html#autotoc_md955',1,'']]],
  ['precise_20estimates_20✅_104',['3. Token Counting (Precise Estimates) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md76',1,'']]],
  ['preparation_105',['llmprep - Codebase Preparation',['../md_README.html#autotoc_md938',1,'']]],
  ['prerequisites_106',['Prerequisites',['../md_README.html#autotoc_md877',1,'']]],
  ['present_3a_20combine_20with_20newline_20e_20g_20cat_20eof_107',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['present_3a_20use_20whichever_20exists_108',['Only one present: use whichever exists',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md392',1,'']]],
  ['preserved_109',['Example 2: Heredoc Preserved',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md329',1,'']]],
  ['preserved_20functionality_110',['Preserved Functionality',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1076',1,'']]],
  ['prevent_20duplicate_20execution_111',['to prevent duplicate execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md317',1,'']]],
  ['previously_20failing_20from_20problem_20statement_20_3a_112',['Previously Failing (from problem statement):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1133',1,'']]],
  ['primary_20analysis_20libraries_113',['Primary Analysis Libraries',['../md_workshop__dependency__validation.html#autotoc_md1366',1,'']]],
  ['principles_114',['Principles',['../md_MISSION.html#autotoc_md604',1,'Core Principles'],['../md_skills_2c__modernization__expert.html#autotoc_md1204',1,'Core Principles'],['../md_skills_2cpp__modernization__expert.html#autotoc_md1261',1,'Core Principles'],['../md_skills_2cpp__refactoring__expert.html#autotoc_md1265',1,'Core Principles'],['../md_skills_2ida__pro__analysis__patterns.html#autotoc_md1275',1,'Core Principles'],['../md_skills_2python__agent__expert.html#autotoc_md1279',1,'Core Principles'],['../md_skills_2reverse__engineering__expert.html#autotoc_md1283',1,'Core Principles'],['../md_skills_2x86__assembly__expert.html#autotoc_md1287',1,'Core Principles'],['../md_ARCHITECTURE.html#autotoc_md166',1,'Design Principles'],['../md_IMPROVEMENTS__README.html#autotoc_md565',1,'Design Principles'],['../md_QUICK__REFERENCE.html#autotoc_md839',1,'Session Rules (The 4 Principles)']]],
  ['prioritized_115',['Recommendations (Prioritized)',['../md_SECURITY__REPORT.html#autotoc_md1107',1,'']]],
  ['priority_116',['Implementation Priority',['../md_IMPROVEMENTS__FINAL.html#autotoc_md535',1,'']]],
  ['pro_20decompiler_20analysis_20expert_117',['IDA Pro / Decompiler Analysis Expert',['../md_skills_2ida__pro__analysis__patterns.html',1,'']]],
  ['problem_118',['Problem',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md19',1,'Evidence of the Problem'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md311',1,'Problem'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md388',1,'Problem'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1321',1,'Problem'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1326',1,'Problem']]],
  ['problem_20addressed_119',['Problem Addressed',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1110',1,'']]],
  ['problem_20solved_120',['Problem Solved',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md667',1,'Problem Solved'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1502',1,'Problem Solved']]],
  ['problem_20solving_121',['Collaborative Problem Solving',['../md_README.html#autotoc_md935',1,'']]],
  ['problem_20statement_122',['Problem Statement',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md18',1,'Problem Statement'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md210',1,'Problem Statement'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md220',1,'Problem Statement'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md401',1,'Problem Statement']]],
  ['problem_20statement_20_3a_123',['Previously Failing (from problem statement):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1133',1,'']]],
  ['process_124',['Pull Request Process',['../md_AGENTS.html#autotoc_md64',1,'']]],
  ['process_20each_20block_125',['Process each block',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['process_20instrumentation_20performance_126',['Process Instrumentation Performance',['../md_workshop__benchmarks.html#autotoc_md1356',1,'']]],
  ['process_20line_20by_20line_20as_20before_127',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['processing_128',['Batch Processing',['../md_README.html#autotoc_md928',1,'']]],
  ['processing_20ray_129',['2. Adding Distributed Processing (Ray)',['../md_ARCHITECTURE.html#autotoc_md163',1,'']]],
  ['production_20deployment_130',['Production Deployment',['../md_workshop__dependency__validation.html#autotoc_md1395',1,'']]],
  ['production_3a_131',['For Production:',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md455',1,'']]],
  ['programmatic_20usage_132',['Programmatic Usage',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md592',1,'']]],
  ['programming_20in_20run_20method_133',['1. Defensive Programming in &lt;span class=&quot;tt&quot;&gt;run()&lt;/span&gt; Method',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md405',1,'']]],
  ['progression_2067_20lines_134',['&lt;span class=&quot;tt&quot;&gt;progression/&lt;/span&gt; (67 lines)',['../md_REFACTORING__NOTES.html#autotoc_md999',1,'']]],
  ['progression_20curve_20hybrid_20linear_20exponential_135',['Progression Curve (Hybrid Linear/Exponential)',['../md_IMPROVEMENTS__FINAL.html#autotoc_md519',1,'']]],
  ['project_136',['Example 1: GPT Building C++ Project',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1157',1,'']]],
  ['project_20directory_137',['Custom Project Directory',['../md_README.html#autotoc_md926',1,'']]],
  ['project_20guidance_20for_20axe_138',['Project Guidance for AXE',['../md_llm__prep_2project__guidance.html',1,'']]],
  ['project_20overview_139',['Project Overview',['../md_AGENTS.html#autotoc_md41',1,'']]],
  ['project_20scale_20analysis_140',['Project-Scale Analysis',['../md_workshop__benchmarks.html#autotoc_md1353',1,'']]],
  ['project_20security_20report_141',['AXE Project Security Report',['../md_SECURITY__REPORT.html',1,'']]],
  ['project_20structure_142',['Project Structure',['../md_README.html#autotoc_md980',1,'']]],
  ['project_20task_20is_20sacred_143',['1. Mission First – The Project / Task Is Sacred',['../md_IMPROVEMENTS__FINAL.html#autotoc_md525',1,'']]],
  ['project_20with_20cmake_144',['Example 1: C++ Project with CMake',['../md_skills_2build.html#autotoc_md1191',1,'']]],
  ['project_20with_20make_145',['Example 3: Python Project with Make',['../md_skills_2build.html#autotoc_md1197',1,'']]],
  ['project_20with_20maven_146',['Example 2: Java Project with Maven',['../md_skills_2build.html#autotoc_md1194',1,'']]],
  ['project_5fdir_3a_20str_20lines_201150_201171_147',['2. &lt;span class=&quot;tt&quot;&gt;__init__(config: Config, project_dir: str)&lt;/span&gt; (Lines 1150-1171)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1113',1,'']]],
  ['projects_20for_20multi_20agent_20work_148',['Test Projects for Multi-Agent Work',['../md_MODELS__FINAL.html#autotoc_md658',1,'']]],
  ['prompt_20caching_149',['1. Prompt Caching',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md246',1,'']]],
  ['prompt_20caching_2090_20token_20savings_20✅_150',['1. Prompt Caching (90% Token Savings) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md74',1,'']]],
  ['prompts_151',['Custom System Prompts',['../md_README.html#autotoc_md929',1,'']]],
  ['propagation_20accuracy_152',['Taint Propagation Accuracy',['../md_workshop__benchmarks.html#autotoc_md1351',1,'']]],
  ['properly_153',['3. Chain of Command – Escalate Properly',['../md_IMPROVEMENTS__FINAL.html#autotoc_md527',1,'']]],
  ['protect_20by_20design_154',['What Sandbox Doesn&apos;t Protect (by design)',['../md_SANDBOX.html#autotoc_md1042',1,'']]],
  ['protects_155',['What Sandbox Protects',['../md_SANDBOX.html#autotoc_md1041',1,'']]],
  ['protocol_156',['Request Protocol',['../md_IMPROVEMENTS__FINAL.html#autotoc_md502',1,'']]],
  ['provider_20ai_20support_157',['Multi-Provider AI Support',['../md_README.html#autotoc_md871',1,'']]],
  ['provider_20documentation_158',['AXE API Provider Documentation',['../md_API__PROVIDERS.html',1,'']]],
  ['provider_20limits_159',['API Provider Limits',['../md_IMPROVEMENTS__FINAL.html#autotoc_md505',1,'']]],
  ['providers_160',['Providers',['../md_ARCHITECTURE.html#autotoc_md162',1,'1. Adding New AI Providers'],['../md_README.html#autotoc_md885',1,'API Providers']]],
  ['prs_202_203_161',['Future Refactoring (PRs #2 &amp;amp; #3)',['../md_REFACTORING__NOTES.html#autotoc_md1018',1,'']]],
  ['psutil_20system_20monitoring_162',['psutil (System Monitoring)',['../md_workshop__dependency__validation.html#autotoc_md1369',1,'']]],
  ['pull_20request_20process_163',['Pull Request Process',['../md_AGENTS.html#autotoc_md64',1,'']]],
  ['purpose_164',['Purpose',['../md_IMPROVEMENTS__FINAL.html#autotoc_md493',1,'Purpose'],['../md_tests_2MISSION.html#autotoc_md1336',1,'Purpose'],['../md_MISSION.html#autotoc_md607',1,'Token Purpose']]],
  ['py_165',['py',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1503',1,'$ python3 test_xml_tool_parser.py'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md339',1,'1. &lt;span class=&quot;tt&quot;&gt;models/metadata.py&lt;/span&gt;'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1294',1,'1. Core Skills Manager (&lt;span class=&quot;tt&quot;&gt;core/skills_manager.py&lt;/span&gt;)'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md341',1,'3. &lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md343',1,'5. &lt;span class=&quot;tt&quot;&gt;tests/test_models_yaml.py&lt;/span&gt;'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1302',1,'7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1303',1,'8. Demonstration Script (&lt;span class=&quot;tt&quot;&gt;demo_skills_system.py&lt;/span&gt;)'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1129',1,'Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md230',1,'Integration Test (&lt;span class=&quot;tt&quot;&gt;test_integration_database_fix.py&lt;/span&gt;)'],['../md_workshop__test__results.html#autotoc_md1455',1,'Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1128',1,'Original Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner.py&lt;/span&gt;)'],['../md_workshop__test__results.html#autotoc_md1456',1,'Performance Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_performance.py&lt;/span&gt;)'],['../md_workshop__test__results.html#autotoc_md1457',1,'Security Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_security.py&lt;/span&gt;)'],['../md_workshop__test__results.html#autotoc_md1454',1,'Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md229',1,'Unit Tests (&lt;span class=&quot;tt&quot;&gt;test_database_location.py&lt;/span&gt;)']]],
  ['py_20collaborativesession_166',['4. &lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt; (CollaborativeSession)',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md342',1,'']]],
  ['py_20new_167',['py NEW',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md344',1,'6. &lt;span class=&quot;tt&quot;&gt;tests/test_dynamic_max_tokens.py&lt;/span&gt; (NEW)'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md345',1,'7. &lt;span class=&quot;tt&quot;&gt;demo_dynamic_tokens.py&lt;/span&gt; (NEW)']]],
  ['py_20refactoring_20notes_168',['AXE.PY Refactoring Notes',['../md_REFACTORING__NOTES.html',1,'']]],
  ['py_20responseprocessor_169',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['pyreverse_170',['Python Class Diagrams (pyreverse)',['../md_llm__prep_2codebase__overview.html#autotoc_md572',1,'']]],
  ['python_171',['Python',['../md_README.html#autotoc_md919',1,'']]],
  ['python_20agent_20expert_172',['Python Agent Expert',['../md_skills_2python__agent__expert.html',1,'']]],
  ['python_20class_20diagrams_20pyreverse_173',['Python Class Diagrams (pyreverse)',['../md_llm__prep_2codebase__overview.html#autotoc_md572',1,'']]],
  ['python_20example_174',['Python Example',['../md_API__PROVIDERS.html#autotoc_md112',1,'Python Example'],['../md_API__PROVIDERS.html#autotoc_md120',1,'Python Example'],['../md_API__PROVIDERS.html#autotoc_md131',1,'Python Example']]],
  ['python_20example_20openai_20sdk_175',['Python Example OpenAI SDK',['../md_API__PROVIDERS.html#autotoc_md139',1,'Python Example (OpenAI SDK)'],['../md_API__PROVIDERS.html#autotoc_md148',1,'Python Example (OpenAI SDK)']]],
  ['python_20instrumentation_20framework_176',['frida-python (Instrumentation Framework)',['../md_workshop__dependency__validation.html#autotoc_md1368',1,'']]],
  ['python_20project_20with_20make_177',['Example 3: Python Project with Make',['../md_skills_2build.html#autotoc_md1197',1,'']]],
  ['python_20script_178',['2. Python Script',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1483',1,'']]],
  ['python_20style_179',['Python Style',['../md_AGENTS.html#autotoc_md50',1,'']]],
  ['python_20version_20support_180',['Python Version Support',['../md_workshop__dependency__validation.html#autotoc_md1376',1,'']]],
  ['python3_20test_5fxml_5ftool_5fparser_20py_181',['$ python3 test_xml_tool_parser.py',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1503',1,'']]]
];
