var searchData=
[
  ['hammer_20live_20instrumentation_0',['Hammer Live Instrumentation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md753',1,'✅ VALIDATED - Hammer (Live Instrumentation)'],['../md_README.html#autotoc_md964',1,'Hammer - Live Instrumentation'],['../md_workshop__quick__reference.html#autotoc_md1405',1,'Hammer - Live Instrumentation']]],
  ['hammer_20live_20instrumentation_20benchmarks_1',['Hammer - Live Instrumentation Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1355',1,'']]],
  ['hammer_20module_2',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['handled_20✅_3',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['handled_20exclusively_20by_20axe_20py_20responseprocessor_4',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['handling_5',['Handling',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md305',1,'Error Handling'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1081',1,'Graceful Handling'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md521',1,'Level 40+ Handling'],['../md_workshop__dependency__validation.html#autotoc_md1374',1,'pathlib (Path Handling)']]],
  ['handling_20✅_20fixed_6',['1. &lt;b&gt;Path &amp;amp; File Handling&lt;/b&gt; ✅ Fixed',['../md_SECURITY__REPORT.html#autotoc_md1101',1,'']]],
  ['handling_20robust_7',['Error Handling - ROBUST',['../md_PR23__VALIDATION__REPORT.html#autotoc_md795',1,'']]],
  ['hardcoded_20secrets_20verified_8',['No Hardcoded Secrets - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md786',1,'']]],
  ['hardening_20flags_20silent_20build_9',['Pattern 1: Hardening Flags (Silent Build)',['../md_skills_2claude__build.html#autotoc_md1254',1,'']]],
  ['header_10',['Header',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md330',1,'']]],
  ['health_11',['Dependency Health',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md722',1,'']]],
  ['help_12',['Help',['../md_README.html#autotoc_md974',1,'']]],
  ['helper_13',['Build Analyzer Helper',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md447',1,'']]],
  ['helper_20✅_14',['5. Build Analyzer Dependency Helper ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md427',1,'']]],
  ['helper_20function_15',['Helper Function',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md224',1,'1. Added &lt;span class=&quot;tt&quot;&gt;get_database_path()&lt;/span&gt; Helper Function'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md227',1,'4. Exported Helper Function']]],
  ['heredoc_16',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['heredoc_20execution_20fix_20implementation_20summary_17',['Heredoc Execution Fix - Implementation Summary',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['heredoc_20execution_20fix_20summary_18',['Heredoc Execution Fix Summary',['../md_HEREDOC__EXECUTION__FIX.html',1,'']]],
  ['heredoc_20parsing_20bug_20fixes_19',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['heredoc_20preserved_20',['Example 2: Heredoc Preserved',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md329',1,'']]],
  ['heredoc_20process_20line_20by_20line_20as_20before_21',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['high_22',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['high_20severity_20findings_23',['Good: Only high-severity findings',['../md_skills_2claude__build.html#autotoc_md1244',1,'']]],
  ['high_20severity_20only_24',['Quick security scan (high severity only)',['../md_skills_2claude__build.html#autotoc_md1226',1,'']]],
  ['hints_20good_25',['Type Hints - GOOD',['../md_PR23__VALIDATION__REPORT.html#autotoc_md796',1,'']]],
  ['historical_20comparison_26',['Historical Comparison',['../md_workshop__test__results.html#autotoc_md1466',1,'']]],
  ['history_27',['History',['../md_workshop__quick__reference.html#autotoc_md1407',1,'History'],['../md_README.html#autotoc_md966',1,'View Analysis History']]],
  ['how_20it_20works_28',['How It Works',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md248',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md255',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md259',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md264',1,'How It Works']]],
  ['how_20to_20use_29',['How to Use',['../md_llm__prep_2codebase__overview.html#autotoc_md575',1,'']]],
  ['huggingface_20llama_30',['HuggingFace Llama',['../md_API__PROVIDERS.html#autotoc_md124',1,'HuggingFace (Llama)'],['../md_MODELS__FINAL.html#autotoc_md627',1,'HuggingFace (Llama)']]],
  ['huggingface_20llama_20free_20tier_20available_31',['HuggingFace (Llama) - Free Tier Available!',['../md_README.html#autotoc_md886',1,'']]],
  ['humans_32',['Tips for Humans',['../md_QUICK__REFERENCE.html#autotoc_md851',1,'']]],
  ['hybrid_20linear_20exponential_33',['Progression Curve (Hybrid Linear/Exponential)',['../md_IMPROVEMENTS__FINAL.html#autotoc_md519',1,'']]]
];
