var searchData=
[
  ['u_0',['U',['../md_TODO.html#autotoc_md2216',1,'']]],
  ['ui_20✅_1',['1. Token Usage Tracking UI ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md360',1,'']]],
  ['under_20scripts_20patches_20dosbox_20staging_2',['dosbox-staging build patches (versioned under &lt;span class=&quot;tt&quot;&gt;scripts/patches/dosbox-staging/&lt;/span&gt;)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2195',1,'']]],
  ['unification_3',['2. GlobalWorkspace API Unification',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1090',1,'']]],
  ['unified_20system_20architecture_4',['Unified System Architecture',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1094',1,'']]],
  ['unit_20test_20results_20test_5fworkshop_20py_5',['Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1889',1,'']]],
  ['unit_20tests_6',['Unit Tests',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md898',1,'Test File 1: Unit Tests'],['../md_docs_2features_2write-blocks.html#autotoc_md1291',1,'Unit Tests'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1924',1,'Unit Tests']]],
  ['unit_20tests_7',['Unit tests',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md805',1,'']]],
  ['unit_20tests_8',['Run all unit tests',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md405',1,'']]],
  ['unit_20tests_20created_9',['Unit Tests Created',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md311',1,'']]],
  ['unit_20tests_20passed_10',['✅ Unit Tests Passed',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md370',1,'']]],
  ['unit_20tests_20test_5fdatabase_5flocation_20py_11',['Unit Tests (&lt;span class=&quot;tt&quot;&gt;test_database_location.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md231',1,'']]],
  ['unix_20socket_20interface_12',['Unix Socket Interface',['../md_TODO.html#autotoc_md2246',1,'🔌 Unix Socket Interface'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1395',1,'Section 6 – Unix Socket Interface']]],
  ['unix_20socket_20interface_20for_20agent_20communication_13',['Unix Socket Interface for Agent Communication',['../md_docs_2socket__interface.html',1,'']]],
  ['unlzexe_20first_20very_20common_14',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md2159',1,'']]],
  ['unpackers_15',['DOS EXE Unpackers',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md2253',1,'']]],
  ['unrestricted_20mode_16',['&quot;bubblewrap not available, falling back to unrestricted mode&quot;',['../md_docs_2features_2sandbox.html#autotoc_md1270',1,'']]],
  ['unrestricted_20mode_20but_20not_20sandbox_20mode_17',['Commands work in unrestricted mode but not sandbox mode',['../md_docs_2features_2sandbox.html#autotoc_md1272',1,'']]],
  ['unshare_20user_20try_20is_20safe_18',['Why &lt;span class=&quot;tt&quot;&gt;--unshare-user-try&lt;/span&gt; is Safe',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1421',1,'']]],
  ['up_20triggers_19',['Wake-up Triggers',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md417',1,'']]],
  ['update_20imports_20✅_20',['Phase 3: Update Imports ✅',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md624',1,'']]],
  ['updated_20agentdatabase_20_5f_5finit_5f_5f_21',['2. Updated &lt;span class=&quot;tt&quot;&gt;AgentDatabase.__init__()&lt;/span&gt;',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md227',1,'']]],
  ['updated_20axe_20yaml_20build_20guidelines_20for_20all_20agents_22',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md718',1,'']]],
  ['updated_20code_23',['Restarting AXE With Updated Code',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1690',1,'']]],
  ['updated_20function_20signatures_24',['3. Updated Function Signatures',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md228',1,'']]],
  ['updated_20functions_25',['Updated Functions',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md589',1,'']]],
  ['updated_20is_5ftool_5fallowed_20cmd_3a_20str_20lines_201460_201542_26',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md693',1,'']]],
  ['updated_20run_20cmd_3a_20str_20lines_201544_201629_27',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md694',1,'']]],
  ['updated_20tests_28',['Updated Tests',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md125',1,'']]],
  ['updates_29',['Updates',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md748',1,'5. Configuration Updates'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md750',1,'&lt;span class=&quot;tt&quot;&gt;axe.yaml&lt;/span&gt; Updates'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md749',1,'&lt;span class=&quot;tt&quot;&gt;models.yaml&lt;/span&gt; Updates'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md233',1,'Documentation Updates'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md388',1,'Documentation Updates']]],
  ['updating_20diagrams_30',['Updating Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1124',1,'']]],
  ['upgrades_31',['Key Upgrades',['../md_skills_2cpp__modernization__expert.html#autotoc_md2153',1,'']]],
  ['usage_32',['Usage',['../md_docs_2features_2github-agent-integration.html#autotoc_md1198',1,'Agent Usage'],['../md_docs_2features_2anthropic-features.html#autotoc_md1142',1,'API Usage'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md496',1,'Checking Resource Usage'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1793',1,'CPU Usage'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1337',1,'Example Usage'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1792',1,'Memory Usage'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md521',1,'Programmatic Usage'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md518',1,'Usage'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md542',1,'Usage'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md555',1,'Usage'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md568',1,'Usage'],['../md_docs_2codex-implementation.html#autotoc_md1018',1,'Usage'],['../md_docs_2features_2anthropic-features.html#autotoc_md1147',1,'Usage'],['../md_docs_2features_2github-agent-integration.html#autotoc_md1197',1,'Usage'],['../md_docs_2ollama-guide.html#autotoc_md1443',1,'Usage'],['../md_docs_2subsumption__architecture.html#autotoc_md1709',1,'Usage'],['../md_docs_2xp__voting.html#autotoc_md1938',1,'Usage']]],
  ['usage_20automatic_33',['Basic Usage (Automatic)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md761',1,'']]],
  ['usage_20example_34',['Usage Example',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1628',1,'']]],
  ['usage_20examples_35',['Usage Examples',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1842',1,'Basic Usage Examples'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md493',1,'Usage Examples'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md573',1,'Usage Examples'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md732',1,'Usage Examples'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md760',1,'Usage Examples'],['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1242',1,'Usage Examples'],['../md_docs_2features_2sandbox.html#autotoc_md1255',1,'Usage Examples'],['../md_docs_2privilege__mapping.html#autotoc_md1487',1,'Usage Examples'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1556',1,'Usage Examples'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1920',1,'Usage Examples'],['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md2255',1,'Usage Examples']]],
  ['usage_20guidelines_36',['Usage Guidelines',['../md_MISSION.html#autotoc_md1982',1,'']]],
  ['usage_20image_20generation_37',['Usage - Image Generation',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md562',1,'']]],
  ['usage_20openai_20compatible_20api_38',['Usage - OpenAI-Compatible API',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md548',1,'']]],
  ['usage_20scenarios_39',['Usage Scenarios',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md669',1,'']]],
  ['usage_20text_20generation_40',['Usage - Text Generation',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md561',1,'']]],
  ['usage_20tracking_41',['Token Usage Tracking',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md380',1,'']]],
  ['usage_20tracking_20ui_20✅_42',['1. Token Usage Tracking UI ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md360',1,'']]],
  ['usage_20transformers_20local_43',['Usage - Transformers (Local)',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md549',1,'']]],
  ['use_44',['How to Use',['../md_llm__prep_2codebase__overview.html#autotoc_md1971',1,'']]],
  ['use_20archive_45',['When to Use Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md966',1,'']]],
  ['use_20cases_46',['Use Cases',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1844',1,'']]],
  ['use_20cases_20enabled_47',['Use Cases Enabled',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md136',1,'']]],
  ['use_20cases_20for_20overrides_48',['Use Cases for Overrides',['../md_docs_2features_2configuration.html#autotoc_md1176',1,'']]],
  ['use_20each_20level_49',['When to Use Each Level',['../md_docs_2codex-implementation.html#autotoc_md1009',1,'']]],
  ['use_20quiet_20flags_20in_20ci_20cd_20security_20checks_50',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md2137',1,'']]],
  ['use_20silent_20flags_20first_51',['1. Always Use Silent Flags First',['../md_skills_2build.html#autotoc_md2072',1,'']]],
  ['use_20verbose_20by_20default_52',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md2080',1,'']]],
  ['use_20verbose_20output_53',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md36',1,'']]],
  ['use_20whichever_20exists_54',['Only one present: use whichever exists',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md329',1,'']]],
  ['user_20configuration_55',['3. axe.yaml (User Configuration)',['../md_docs_2features_2configuration.html#autotoc_md1166',1,'']]],
  ['user_20experience_56',['User Experience',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1377',1,'']]],
  ['user_20guide_57',['User Guide',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html',1,'Cognitive Architecture in AXE - User Guide'],['../md_docs_2features_2write-blocks.html',1,'WRITE Block Functionality - User Guide']]],
  ['user_20namespace_58',['User Namespace',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1422',1,'What Works Without User Namespace'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1423',1,'What&apos;s Missing Without User Namespace']]],
  ['user_20namespace_20detection_59',['1. Enhanced User Namespace Detection',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1417',1,'']]],
  ['user_20namespace_20detection_20and_20safety_20improvements_60',['User Namespace Detection and Safety Improvements',['../md_docs_2NAMESPACE__DETECTION.html',1,'']]],
  ['user_20try_20is_20safe_61',['Why &lt;span class=&quot;tt&quot;&gt;--unshare-user-try&lt;/span&gt; is Safe',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1421',1,'']]],
  ['user_3a_62',['For User:',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md391',1,'']]],
  ['users_63',['For Users',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md169',1,'']]],
  ['using_20cognitive_20features_20in_20axe_20sessions_64',['Using Cognitive Features in AXE Sessions',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1028',1,'']]],
  ['using_20mkpyenv_20tool_65',['Option B: Using mkpyenv tool',['../md_README.html#autotoc_md2001',1,'']]],
  ['using_20negative_20votes_66',['Using Negative Votes',['../md_docs_2xp__voting.html#autotoc_md1957',1,'']]],
  ['using_20these_20references_67',['Using These References',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1595',1,'']]],
  ['utilities_68',['4. Utilities',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1615',1,'']]],
  ['utilization_20trends_69',['Resource Utilization Trends',['../md_docs_2workshop_2benchmarks.html#autotoc_md1770',1,'']]],
  ['utils_2033_20lines_70',['&lt;span class=&quot;tt&quot;&gt;utils/&lt;/span&gt; (33 lines)',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md617',1,'']]],
  ['ux_20polish_71',['8. Multiple Workspace Directories — UX Polish',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md996',1,'']]]
];
