var searchData=
[
  ['a_20collaborative_20session_20with_20new_20features_0',['Starting a Collaborative Session with New Features',['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'']]],
  ['a_20heredoc_1',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['a_20session_2',['a Session',['../md_IMPROVEMENTS__FINAL.html#autotoc_md539',1,'Starting a Session'],['../md_QUICK__REFERENCE.html#autotoc_md844',1,'Starting a Session'],['../md_QUICK__REFERENCE.html#autotoc_md852',1,'Starting a Session']]],
  ['a_20single_20command_3',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['a_20wad_20file_4',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['a_3a_20test_20execution_20logs_5',['Appendix A: Test Execution Logs',['../md_PR23__VALIDATION__REPORT.html#autotoc_md831',1,'']]],
  ['about_20read_20write_20block_20syntax_6',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['about_20read_20write_20block_20syntax_20✅_7',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['absolute_20path_20fix_20implementation_20summary_8',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['abstract_20syntax_20trees_9',['ast (Abstract Syntax Trees)',['../md_workshop__dependency__validation.html#autotoc_md1371',1,'']]],
  ['acceptance_20criteria_10',['Acceptance Criteria',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md598',1,'']]],
  ['access_11',['Documentation Access',['../md__8collab__env.html#autotoc_md6',1,'']]],
  ['access_20control_12',['Access Control',['../md_SANDBOX.html#autotoc_md1031',1,'3. Filesystem Access Control'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1066',1,'3. Filesystem Access Control'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1488',1,'Directory Access Control']]],
  ['access_20denied_13',['Issue 1: READ Block Access Denied',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md173',1,'']]],
  ['access_20denied_20✅_14',['Issue 1: READ Block Access Denied ✅',['../md_FIXES__SUMMARY.html#autotoc_md363',1,'']]],
  ['accident_15',['accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['accuracy_16',['Taint Propagation Accuracy',['../md_workshop__benchmarks.html#autotoc_md1351',1,'']]],
  ['actions_17',['Actions',['../md_workshop__test__results.html#autotoc_md1474',1,'Immediate Actions'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md735',1,'Post-Merge Actions']]],
  ['actions_20completed_18',['Immediate Actions (Completed)',['../md_workshop__security__audit.html#autotoc_md1444',1,'']]],
  ['active_20agents_20counter_20✅_19',['Bug 2: Active Agents Counter ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1325',1,'']]],
  ['activities_20',['Break Activities',['../md_IMPROVEMENTS__FINAL.html#autotoc_md501',1,'']]],
  ['actual_20implementation_21',['Part 1: PR Claims vs. Actual Implementation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md748',1,'']]],
  ['add_20more_20diet_20etc_20if_20tools_20expand_22',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['added_23',['Added',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md449',1,'Commands Added'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1508',1,'Files Modified/Added'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md670',1,'New Functions Added'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md325',1,'New Tests Added'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md396',1,'New Tests Added']]],
  ['added_20get_5fdatabase_5fpath_20helper_20function_24',['1. Added &lt;span class=&quot;tt&quot;&gt;get_database_path()&lt;/span&gt; Helper Function',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md224',1,'']]],
  ['added_20to_20requirements_20txt_25',['Added to requirements.txt',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md721',1,'']]],
  ['adding_20distributed_20processing_20ray_26',['2. Adding Distributed Processing (Ray)',['../md_ARCHITECTURE.html#autotoc_md163',1,'']]],
  ['adding_20new_20ai_20providers_27',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md162',1,'']]],
  ['adding_20new_20token_20optimization_20strategies_28',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md165',1,'']]],
  ['adding_20new_20workshop_20tools_29',['3. Adding New Workshop Tools',['../md_ARCHITECTURE.html#autotoc_md164',1,'']]],
  ['additional_20languages_30',['Additional Languages',['../md__8collab__env.html#autotoc_md5',1,'']]],
  ['additional_20resources_31',['Additional Resources',['../md_AGENTS.html#autotoc_md67',1,'']]],
  ['addressed_32',['Addressed',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1138',1,'Code Review Addressed'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md674',1,'Code Review Issues Addressed'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1110',1,'Problem Addressed']]],
  ['addresssanitizer_20asan_33',['AddressSanitizer (ASan)',['../md_skills_2claude__build.html#autotoc_md1219',1,'']]],
  ['addresssanitizer_20for_20runtime_20detection_34',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md1237',1,'']]],
  ['advanced_20usage_35',['Advanced Usage',['../md_README.html#autotoc_md925',1,'']]],
  ['after_36',['After',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md175',1,'After'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md183',1,'After'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md237',1,'After'],['../md_REFACTORING__NOTES.html#autotoc_md996',1,'After'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md411',1,'Example - Before vs After']]],
  ['after_20axe_20yaml_37',['After (axe.yaml)',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md179',1,'']]],
  ['after_20comparison_20of_20fixes_38',['Before/After Comparison of Fixes',['../md_BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['after_20fix_39',['Impact After Fix',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md235',1,'']]],
  ['agent_40',['When to Use Each Agent',['../md_README.html#autotoc_md913',1,'']]],
  ['agent_41',['Security-Focused Agent (1 agent)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1144',1,'']]],
  ['agent_201_20agent_42',['Security-Focused Agent (1 agent)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1144',1,'']]],
  ['agent_20aliases_43',['Agent Aliases',['../md_IMPROVEMENTS__FINAL.html#autotoc_md512',1,'']]],
  ['agent_20aliasing_20system_20✅_44',['Phase 2: Agent Aliasing System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md544',1,'']]],
  ['agent_20code_20analysis_45',['Example: Multi-Agent Code Analysis',['../md_README.html#autotoc_md899',1,'']]],
  ['agent_20collaboration_46',['Agent Collaboration',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1161',1,'Example 3: Multi-Agent Collaboration'],['../md_skills_2build.html#autotoc_md1200',1,'Example 4: Multi-Agent Collaboration'],['../md_MODELS__FINAL.html#autotoc_md656',1,'Multi-Agent Collaboration'],['../md_README.html#autotoc_md931',1,'Multi-Agent Collaboration']]],
  ['agent_20collaboration_20issues_47',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_BUG__FIX__SUMMARY.html',1,'']]],
  ['agent_20commands_20during_20sessions_48',['New Agent Commands (During Sessions)',['../md_IMPROVEMENTS__README.html#autotoc_md554',1,'']]],
  ['agent_20communication_20tokens_49',['Agent Communication Tokens',['../md_MISSION.html#autotoc_md605',1,'']]],
  ['agent_20conversations_50',['Basic Agent Conversations',['../md_README.html#autotoc_md894',1,'']]],
  ['agent_20coordination_51',['Agent Coordination',['../md__8collab__shared.html#autotoc_md14',1,'']]],
  ['agent_20coverage_52',['Agent Coverage',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1152',1,'']]],
  ['agent_20execution_20engine_53',['Agent eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['agent_20execution_20engine_20✅_54',['AXE - Agent eXecution Engine ✅',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'']]],
  ['agent_20expert_55',['Python Agent Expert',['../md_skills_2python__agent__expert.html',1,'']]],
  ['agent_20integration_56',['GitHub Agent Integration',['../md_docs_2GITHUB__AGENT__INTEGRATION.html',1,'']]],
  ['agent_20lifecycle_57',['Agent Lifecycle',['../md_IMPROVEMENTS__README.html#autotoc_md563',1,'']]],
  ['agent_20ranks_20levels_58',['Agent Ranks &amp;amp; Levels',['../md_QUICK__REFERENCE.html#autotoc_md840',1,'']]],
  ['agent_20rate_20limiting_20✅_59',['3. Agent Rate Limiting ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md425',1,'']]],
  ['agent_20reference_60',['Agent Reference',['../md_README.html#autotoc_md911',1,'']]],
  ['agent_20session_20commands_61',['Agent Session Commands',['../md_IMPROVEMENTS__FINAL.html#autotoc_md538',1,'']]],
  ['agent_20skills_20system_20implementation_20summary_62',['Agent Skills System Implementation Summary',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['agent_20stuck_20or_20confused_63',['&quot;Agent stuck or confused&quot;',['../md_QUICK__REFERENCE.html#autotoc_md858',1,'']]],
  ['agent_20system_20improvement_20reference_20guide_64',['AXE Multi-Agent System - Improvement Reference Guide',['../md_IMPROVEMENTS__FINAL.html',1,'']]],
  ['agent_20system_20model_20configuration_20reference_65',['AXE Multi-Agent System - Model Configuration Reference',['../md_MODELS__FINAL.html',1,'']]],
  ['agent_20usage_66',['Agent Usage',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md294',1,'']]],
  ['agent_20work_67',['Test Projects for Multi-Agent Work',['../md_MODELS__FINAL.html#autotoc_md658',1,'']]],
  ['agent_20workspace_68',['Per-Agent Workspace',['../md_IMPROVEMENTS__FINAL.html#autotoc_md533',1,'']]],
  ['agent_5fmanager_20py_69',['3. &lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md341',1,'']]],
  ['agentdatabase_20_5f_5finit_5f_5f_70',['2. Updated &lt;span class=&quot;tt&quot;&gt;AgentDatabase.__init__()&lt;/span&gt;',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md225',1,'']]],
  ['agentmanager_71',['6. Integration with AgentManager',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1301',1,'']]],
  ['agents_72',['Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'1. Updated axe.yaml - BUILD GUIDELINES for All Agents'],['../md_README.html#autotoc_md912',1,'Available Agents'],['../md_README.html#autotoc_md951',1,'Integration with Agents'],['../md_README.html#autotoc_md969',1,'Integration with Agents'],['../md_workshop__quick__reference.html#autotoc_md1414',1,'Integration with Agents'],['../md__8collab__env.html#autotoc_md11',1,'Notes for Agents'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md532',1,'Safe Commands for Agents']]],
  ['agents_73',['General Agents (17 agents)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1143',1,'']]],
  ['agents_2017_20agents_74',['General Agents (17 agents)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1143',1,'']]],
  ['agents_20confused_20about_20read_20write_20block_20syntax_75',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['agents_20confused_20about_20read_20write_20block_20syntax_20✅_76',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['agents_20counter_20✅_77',['Bug 2: Active Agents Counter ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1325',1,'']]],
  ['agents_20md_78',['Integration with AGENTS.md',['../md_skills_2claude__build.html#autotoc_md1250',1,'']]],
  ['agents_20md_20for_20axe_79',['AGENTS.md for AXE',['../md_AGENTS.html',1,'']]],
  ['agents_20md_20standard_20compliance_80',['2. AGENTS.md Standard Compliance',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1295',1,'']]],
  ['agents_20never_20get_20turns_20✅_81',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['agents_20not_20cooperating_82',['&quot;Agents not cooperating&quot;',['../md_QUICK__REFERENCE.html#autotoc_md857',1,'']]],
  ['agents_20now_20working_83',['Agents Now Working',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md34',1,'']]],
  ['agents_20see_84',['What Agents See',['../md_QUICK__REFERENCE.html#autotoc_md855',1,'']]],
  ['ai_85',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md169',1,'']]],
  ['ai_20providers_86',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md162',1,'']]],
  ['ai_20support_87',['Multi-Provider AI Support',['../md_README.html#autotoc_md871',1,'']]],
  ['aliases_88',['Aliases',['../md_IMPROVEMENTS__FINAL.html#autotoc_md512',1,'Agent Aliases'],['../md_QUICK__REFERENCE.html#autotoc_md845',1,'Aliases'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md515',1,'Special Aliases']]],
  ['aliasing_20system_20✅_89',['Phase 2: Agent Aliasing System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md544',1,'']]],
  ['all_20agents_90',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'']]],
  ['all_20features_20implemented_91',['✅ All Features Implemented',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md422',1,'']]],
  ['all_20implemented_20features_92',['Summary of All Implemented Features',['../md_IMPROVEMENTS__README.html#autotoc_md568',1,'']]],
  ['all_20met_93',['Success Criteria (All Met)',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1334',1,'']]],
  ['all_20output_94',['❌ Don&apos;t Remove All Output',['../md_skills_2build.html#autotoc_md1187',1,'']]],
  ['all_20tests_95',['[... all tests ...]',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1505',1,'']]],
  ['all_20tests_20passed_96',['✅ ALL TESTS PASSED!',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1506',1,'']]],
  ['all_20trials_20fail_97',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['all_20unit_20tests_98',['Run all unit tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md468',1,'']]],
  ['allow_20execution_99',['1. Default-Allow Execution',['../md_SANDBOX.html#autotoc_md1029',1,'']]],
  ['allow_20security_20model_100',['1. Default-Allow Security Model',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1064',1,'']]],
  ['allowed_20bug_20fixed_20_3a_101',['✅ Now Allowed (Bug Fixed):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md31',1,'']]],
  ['always_20use_20silent_20flags_20first_102',['1. Always Use Silent Flags First',['../md_skills_2build.html#autotoc_md1181',1,'']]],
  ['analysis_103',['Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md751',1,'✅ VALIDATED - Saw (Taint Analysis)'],['../md_README.html#autotoc_md923',1,'Analysis'],['../md_workshop__benchmarks.html#autotoc_md1350',1,'Code Snippet Analysis'],['../md_workshop__benchmarks.html#autotoc_md1358',1,'Comparative Analysis'],['../md_skills_2claude__build.html#autotoc_md1216',1,'Cppcheck (Static Analysis)'],['../md_workshop__security__audit.html#autotoc_md1435',1,'Dependency Security Analysis'],['../md_README.html#autotoc_md916',1,'Disassembly &amp;amp; Analysis'],['../md_workshop__test__results.html#autotoc_md1467',1,'Error Analysis'],['../md_README.html#autotoc_md899',1,'Example: Multi-Agent Code Analysis'],['../md_workshop__benchmarks.html#autotoc_md1348',1,'Function-Level Analysis'],['../md_workshop__security__audit.html#autotoc_md1424',1,'Issue #2: Memory Exhaustion in Chisel Analysis'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md793',1,'Part 5: Code Quality Analysis'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md799',1,'Part 6: Test Coverage Analysis'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md803',1,'Part 7: Dependency Analysis'],['../md_workshop__dependency__validation.html#autotoc_md1381',1,'Performance Impact Analysis'],['../md_workshop__benchmarks.html#autotoc_md1353',1,'Project-Scale Analysis'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md402',1,'Root Cause Analysis'],['../md_README.html#autotoc_md933',1,'Round-Robin Analysis'],['../md_README.html#autotoc_md962',1,'Saw - Taint Analysis'],['../md_workshop__quick__reference.html#autotoc_md1403',1,'Saw - Taint Analysis'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1084',1,'Scenario 2: Code Analysis'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md28',1,'Security Analysis'],['../md_FIXES__SUMMARY.html#autotoc_md376',1,'Security Analysis'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1307',1,'Token Efficiency Analysis'],['../md_skills_2claude__build.html#autotoc_md1213',1,'Valgrind (Memory Analysis)']]],
  ['analysis_20benchmarks_104',['Saw - Taint Analysis Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1349',1,'']]],
  ['analysis_20expanded_105',['Build Analysis (EXPANDED!)',['../md_README.html#autotoc_md905',1,'']]],
  ['analysis_20expert_106',['Analysis Expert',['../md_skills_2ida__pro__analysis__patterns.html',1,'IDA Pro / Decompiler Analysis Expert'],['../md_skills_2x86__assembly__expert.html',1,'x86 Assembly Analysis Expert']]],
  ['analysis_20framework_20comprehensive_20validation_20report_107',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_PR23__VALIDATION__REPORT.html',1,'']]],
  ['analysis_20framework_20executive_20summary_108',['PR #23 Workshop Dynamic Analysis Framework - Executive Summary',['../md_PR23__EXECUTIVE__SUMMARY.html',1,'']]],
  ['analysis_20history_109',['View Analysis History',['../md_README.html#autotoc_md966',1,'']]],
  ['analysis_20libraries_110',['Primary Analysis Libraries',['../md_workshop__dependency__validation.html#autotoc_md1366',1,'']]],
  ['analysis_20patterns_111',['Key Analysis Patterns',['../md_skills_2x86__assembly__expert.html#autotoc_md1288',1,'']]],
  ['analysis_20performance_112',['Binary Analysis Performance',['../md_workshop__benchmarks.html#autotoc_md1347',1,'']]],
  ['analysis_20quietly_113',['Run static analysis quietly',['../md_skills_2claude__build.html#autotoc_md1217',1,'']]],
  ['analysis_20results_114',['Performance Analysis Results',['../md_workshop__benchmarks.html#autotoc_md1344',1,'']]],
  ['analysis_20silent_115',['Phase 2: Static Analysis (Silent)',['../md_skills_2claude__build.html#autotoc_md1232',1,'']]],
  ['analysis_20silent_116',['analysis silent',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1160',1,'Runtime analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md1252',1,'Runtime analysis (silent)'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1159',1,'Static analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md1251',1,'Static analysis (silent)']]],
  ['analysis_20tools_117',['Analysis Tools',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md697',1,'✅ Four Dynamic Analysis Tools'],['../md_README.html#autotoc_md937',1,'Analysis Tools'],['../md_README.html#autotoc_md957',1,'Workshop - Dynamic Analysis Tools']]],
  ['analysis_20tools_20implemented_118',['Claim 1: Four Analysis Tools Implemented',['../md_PR23__VALIDATION__REPORT.html#autotoc_md749',1,'']]],
  ['analyzer_119',['Clang Static Analyzer',['../md_skills_2claude__build.html#autotoc_md1222',1,'']]],
  ['analyzer_20dependency_20helper_20✅_120',['5. Build Analyzer Dependency Helper ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md427',1,'']]],
  ['analyzer_20helper_121',['Build Analyzer Helper',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md447',1,'']]],
  ['analyzer_20quietly_122',['Run Clang static analyzer quietly',['../md_skills_2claude__build.html#autotoc_md1223',1,'']]],
  ['and_20build_20quietly_123',['Clean and build quietly',['../md_skills_2build.html#autotoc_md1195',1,'']]],
  ['and_20extensibility_20guide_124',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['and_20feedback_125',['Rejection and Feedback',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md300',1,'']]],
  ['and_20files_126',['3. Created Skills Directory and Files',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1146',1,'']]],
  ['and_20heredoc_20parsing_20bug_20fixes_127',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['and_20permissions_128',['Security and Permissions',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1487',1,'']]],
  ['and_20run_20tests_20silently_129',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md1220',1,'']]],
  ['and_20setup_130',['Clone and Setup',['../md_README.html#autotoc_md879',1,'']]],
  ['angr_20symbolic_20execution_20engine_131',['angr (Symbolic Execution Engine)',['../md_workshop__dependency__validation.html#autotoc_md1367',1,'']]],
  ['anthropic_20claude_132',['Anthropic Claude',['../md_API__PROVIDERS.html#autotoc_md107',1,'Anthropic (Claude)'],['../md_MODELS__FINAL.html#autotoc_md621',1,'Anthropic (Claude)'],['../md_README.html#autotoc_md889',1,'Anthropic (Claude)']]],
  ['anthropic_20claude_20specific_20features_20in_20axe_133',['Anthropic Claude-Specific Features in AXE',['../md_docs_2ANTHROPIC__FEATURES.html',1,'']]],
  ['anthropic_20claude_20specific_20optimizations_20implementation_20summary_134',['Anthropic Claude-Specific Optimizations - Implementation Summary',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['anthropic_20sdk_20error_20fixed_20✓_135',['1. Anthropic SDK Error Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md347',1,'']]],
  ['api_136',['API',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1305',1,'SkillsManager Class API'],['../md_MODELS__FINAL.html#autotoc_md630',1,'Usage - OpenAI-Compatible API']]],
  ['api_20beta_137',['4. Files API (Beta)',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md262',1,'']]],
  ['api_20beta_20optional_20✅_138',['4. Files API (Beta, Optional) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md77',1,'']]],
  ['api_20connections_139',['Testing API Connections',['../md_README.html#autotoc_md978',1,'']]],
  ['api_20endpoints_20summary_140',['API Endpoints Summary',['../md_API__PROVIDERS.html#autotoc_md153',1,'']]],
  ['api_20keys_141',['Testing API Keys',['../md_API__PROVIDERS.html#autotoc_md158',1,'']]],
  ['api_20keys_142',['Manual testing (requires API keys)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md470',1,'']]],
  ['api_20keys_20setup_143',['API Keys Setup',['../md_README.html#autotoc_md882',1,'']]],
  ['api_20not_20working_144',['Files API not working',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md276',1,'']]],
  ['api_20parameter_20error_20critical_145',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md460',1,'']]],
  ['api_20provider_20documentation_146',['AXE API Provider Documentation',['../md_API__PROVIDERS.html',1,'']]],
  ['api_20provider_20limits_147',['API Provider Limits',['../md_IMPROVEMENTS__FINAL.html#autotoc_md505',1,'']]],
  ['api_20providers_148',['API Providers',['../md_README.html#autotoc_md885',1,'']]],
  ['api_20usage_149',['API Usage',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md260',1,'']]],
  ['appearing_150',['No Results Appearing?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1524',1,'']]],
  ['append_20results_20to_20response_151',['Append results to response',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md463',1,'']]],
  ['appendix_20a_3a_20test_20execution_20logs_152',['Appendix A: Test Execution Logs',['../md_PR23__VALIDATION__REPORT.html#autotoc_md831',1,'']]],
  ['appendix_20b_3a_20file_20changes_20summary_153',['Appendix B: File Changes Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md834',1,'']]],
  ['applied_154',['Best Practices Applied',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md94',1,'']]],
  ['approach_155',['Approach',['../md_AGENTS.html#autotoc_md58',1,'Default Build Approach'],['../md_REFACTORING__NOTES.html#autotoc_md1002',1,'Implementation Approach']]],
  ['approve_20mode_20non_20interactive_156',['Auto-Approve Mode (Non-Interactive)',['../md_README.html#autotoc_md927',1,'']]],
  ['approve_20not_20default_20in_20collab_20mode_157',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['approve_20not_20default_20in_20collab_20mode_20✅_158',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['approved_20for_20merge_159',['✅ APPROVED FOR MERGE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md822',1,'']]],
  ['architecture_160',['Architecture',['../md_AGENTS.html#autotoc_md60',1,'Architecture'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md494',1,'Architecture'],['../md_SANDBOX.html#autotoc_md1045',1,'Architecture']]],
  ['architecture_20and_20extensibility_20guide_161',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['architecture_20diagrams_162',['AXE Architecture Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md279',1,'']]],
  ['architecture_20notes_163',['Architecture Notes',['../md_IMPROVEMENTS__README.html#autotoc_md561',1,'']]],
  ['architecture_20overview_164',['Architecture Overview',['../md_MISSION.html#autotoc_md609',1,'']]],
  ['are_20now_20handled_20exclusively_20by_20axe_20py_20responseprocessor_165',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['as_20a_20single_20command_166',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['as_20before_167',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['asan_168',['AddressSanitizer (ASan)',['../md_skills_2claude__build.html#autotoc_md1219',1,'']]],
  ['asan_20and_20run_20tests_20silently_169',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md1220',1,'']]],
  ['assembly_20analysis_20expert_170',['x86 Assembly Analysis Expert',['../md_skills_2x86__assembly__expert.html',1,'']]],
  ['assessment_171',['Assessment',['../md_workshop__security__audit.html#autotoc_md1441',1,'Compliance Assessment'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md746',1,'Overall Assessment'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md825',1,'Part 12: Risk Assessment'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md729',1,'Risk Assessment']]],
  ['assignment_172',['Supervisor Role Assignment',['../md_MODELS__FINAL.html#autotoc_md659',1,'']]],
  ['assume_20silence_20means_20success_173',['❌ Don&apos;t Assume Silence Means Success',['../md_skills_2build.html#autotoc_md1188',1,'']]],
  ['assurance_174',['Assurance',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md437',1,'Quality Assurance'],['../md_workshop__quick__reference.html#autotoc_md1416',1,'Validation &amp;amp; Quality Assurance']]],
  ['ast_20abstract_20syntax_20trees_175',['ast (Abstract Syntax Trees)',['../md_workshop__dependency__validation.html#autotoc_md1371',1,'']]],
  ['at_20session_20start_20pinned_20message_20_3a_176',['Display at session start (pinned message):',['../md_IMPROVEMENTS__FINAL.html#autotoc_md524',1,'']]],
  ['attack_20surface_20reduction_177',['Attack Surface Reduction',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1074',1,'']]],
  ['attributions_20credits_178',['Attributions &amp;amp; Credits',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1342',1,'']]],
  ['audit_179',['Audit',['../md_PR23__VALIDATION__REPORT.html#autotoc_md770',1,'Document 3: Security Audit'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1158',1,'Example 2: Claude Security Audit'],['../md_workshop__security__audit.html',1,'Workshop Tools Security Audit']]],
  ['audit_20scope_180',['Audit Scope',['../md_workshop__security__audit.html#autotoc_md1419',1,'']]],
  ['audit_20workflow_181',['Real-World Example: Security Audit Workflow',['../md_README.html#autotoc_md972',1,'']]],
  ['audit_20workflow_20example_182',['Security Audit Workflow Example',['../md_skills_2claude__build.html#autotoc_md1228',1,'']]],
  ['auditing_20workflow_183',['Security Auditing Workflow',['../md_skills_2claude__build.html#autotoc_md1209',1,'']]],
  ['audits_184',['Audits',['../md_skills_2claude__build.html#autotoc_md1240',1,'Best Practices for Security Audits'],['../md_skills_2claude__build.html#autotoc_md1239',1,'Token Savings in Security Audits']]],
  ['author_185',['Author',['../md_README.html#autotoc_md987',1,'']]],
  ['auto_20approve_20mode_20non_20interactive_186',['Auto-Approve Mode (Non-Interactive)',['../md_README.html#autotoc_md927',1,'']]],
  ['auto_20approve_20not_20default_20in_20collab_20mode_187',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['auto_20approve_20not_20default_20in_20collab_20mode_20✅_188',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['autoconf_20configure_189',['Autoconf/Configure',['../md_skills_2build.html#autotoc_md1171',1,'']]],
  ['automated_20installation_20testing_190',['Automated Installation Testing',['../md_workshop__dependency__validation.html#autotoc_md1379',1,'']]],
  ['automated_20tests_191',['Run automated tests',['../md_QUICK__REFERENCE.html#autotoc_md849',1,'']]],
  ['automatic_192',['Basic Usage (Automatic)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1311',1,'']]],
  ['automatic_20features_193',['Automatic Features',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md250',1,'']]],
  ['autonomous_20collaborative_20sessions_20new_194',['Autonomous Collaborative Sessions (NEW!)',['../md_README.html#autotoc_md932',1,'']]],
  ['available_195',['HuggingFace (Llama) - Free Tier Available!',['../md_README.html#autotoc_md886',1,'']]],
  ['available_196',['Extended thinking not available',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md274',1,'']]],
  ['available_20agents_197',['Available Agents',['../md_README.html#autotoc_md912',1,'']]],
  ['available_20docs_198',['Available Docs',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1094',1,'']]],
  ['available_20falling_20back_20to_20whitelist_20mode_199',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['available_20models_200',['Available Models',['../md_MODELS__FINAL.html#autotoc_md649',1,'']]],
  ['awards_201',['Awards',['../md_QUICK__REFERENCE.html#autotoc_md841',1,'XP Awards'],['../md_workshop__quick__reference.html#autotoc_md1412',1,'XP Awards']]],
  ['awards_20dictionary_202',['✅ VALIDATED - XP Awards Dictionary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md760',1,'']]],
  ['axe_203',['AXE',['../md_AGENTS.html',1,'AGENTS.md for AXE'],['../md_docs_2ANTHROPIC__FEATURES.html',1,'Anthropic Claude-Specific Features in AXE'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1155',1,'Integration with AXE'],['../md_llm__prep_2project__guidance.html',1,'Project Guidance for AXE'],['../md_AGENTS.html#autotoc_md45',1,'Running AXE'],['../md_README.html#autotoc_md867',1,'Why AXE?']]],
  ['axe_20agent_20execution_20engine_204',['AXE Agent eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['axe_20agent_20execution_20engine_20✅_205',['AXE - Agent eXecution Engine ✅',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'']]],
  ['axe_20api_20provider_20documentation_206',['AXE API Provider Documentation',['../md_API__PROVIDERS.html',1,'']]],
  ['axe_20architecture_20and_20extensibility_20guide_207',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['axe_20architecture_20diagrams_208',['AXE Architecture Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md279',1,'']]],
  ['axe_20enhancement_20implementation_20complete_20✅_209',['AXE Enhancement Implementation - Complete ✅',['../md_IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['axe_20framework_20compatibility_210',['AXE Framework Compatibility',['../md_workshop__dependency__validation.html#autotoc_md1389',1,'']]],
  ['axe_20integration_211',['✅ Complete AXE Integration',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md698',1,'']]],
  ['axe_20multi_20agent_20system_20improvement_20reference_20guide_212',['AXE Multi-Agent System - Improvement Reference Guide',['../md_IMPROVEMENTS__FINAL.html',1,'']]],
  ['axe_20multi_20agent_20system_20model_20configuration_20reference_213',['AXE Multi-Agent System - Model Configuration Reference',['../md_MODELS__FINAL.html',1,'']]],
  ['axe_20multiagent_20improvements_20implementation_20summary_214',['AXE Multiagent Improvements - Implementation Summary',['../md_IMPROVEMENTS__README.html',1,'']]],
  ['axe_20multiagent_20quick_20reference_20card_215',['AXE Multiagent - Quick Reference Card',['../md_QUICK__REFERENCE.html',1,'']]],
  ['axe_20multiple_20issues_20fix_20summary_216',['AXE Multiple Issues Fix Summary',['../md_FIXES__SUMMARY.html',1,'']]],
  ['axe_20native_20blocks_217',['3. AXE Native Blocks',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md691',1,'']]],
  ['axe_20native_20format_218',['Example 3: AXE Native Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md685',1,'']]],
  ['axe_20native_20read_20write_20exec_20blocks_219',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['axe_20project_20security_20report_220',['AXE Project Security Report',['../md_SECURITY__REPORT.html',1,'']]],
  ['axe_20py_20collaborativesession_221',['4. &lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt; (CollaborativeSession)',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md342',1,'']]],
  ['axe_20py_20refactoring_20notes_222',['AXE.PY Refactoring Notes',['../md_REFACTORING__NOTES.html',1,'']]],
  ['axe_20py_20responseprocessor_223',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['axe_20session_20termination_20bugs_224',['Fix Summary: AXE Session Termination Bugs',['../md_TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['axe_20test_20mission_225',['AXE Test Mission',['../md_tests_2MISSION.html',1,'']]],
  ['axe_20yaml_226',['axe yaml',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md179',1,'After (axe.yaml)'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md178',1,'Before (axe.yaml)'],['../md_README.html#autotoc_md883',1,'Configuration File (axe.yaml)'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md590',1,'Enable in axe.yaml'],['../md_skills_2build.html#autotoc_md1178',1,'Integration with axe.yaml']]],
  ['axe_20yaml_20build_20guidelines_20for_20all_20agents_227',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'']]],
  ['axe_20yaml_20updates_228',['&lt;span class=&quot;tt&quot;&gt;axe.yaml&lt;/span&gt; Updates',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1300',1,'']]]
];
