var searchData=
[
  ['t_0',['T',['../md_TODO.html#autotoc_md2215',1,'T'],['../md_TODO.html#autotoc_md2233',1,'T']]],
  ['t_20assume_20silence_20means_20success_1',['❌ Don&apos;t Assume Silence Means Success',['../md_skills_2build.html#autotoc_md2079',1,'']]],
  ['t_20protect_20by_20design_2',['What Sandbox Doesn&apos;t Protect (by design)',['../md_docs_2features_2sandbox.html#autotoc_md1261',1,'']]],
  ['t_20remove_20all_20output_3',['❌ Don&apos;t Remove All Output',['../md_skills_2build.html#autotoc_md2078',1,'']]],
  ['t_20use_20verbose_20by_20default_4',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md2080',1,'']]],
  ['table_20of_20contents_5',['Table of Contents',['../md_docs_2api-providers.html#autotoc_md63',1,'Table of Contents'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md412',1,'Table of Contents'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md533',1,'Table of Contents']]],
  ['tag_20formats_20not_20supported_20✅_6',['Bug 1: XML Tag Formats Not Supported ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['tags_7',['4. Simple XML Tags',['../md_docs_2features_2parsers.html#autotoc_md1218',1,'']]],
  ['tags_20claude_20s_20favorite_8',['Tags Claude s Favorite',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md607',1,'1. Bash XML Tags (Claude&apos;s Favorite)'],['../md_docs_2features_2parsers.html#autotoc_md1215',1,'1. Bash XML Tags (Claude&apos;s Favorite)']]],
  ['tags_20like_9',['5. Simple XML tags like &amp;lt;read_file&amp;gt;, &amp;lt;shell&amp;gt;',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md256',1,'']]],
  ['taint_20analysis_10',['Taint Analysis',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md873',1,'✅ VALIDATED - Saw (Taint Analysis)'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1832',1,'&lt;b&gt;Saw&lt;/b&gt; (Taint Analysis)'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1813',1,'Saw - Taint Analysis']]],
  ['taint_20analysis_20benchmarks_11',['Saw - Taint Analysis Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1759',1,'']]],
  ['taint_20propagation_20accuracy_12',['Taint Propagation Accuracy',['../md_docs_2workshop_2benchmarks.html#autotoc_md1761',1,'']]],
  ['talking_20model_13',['Talking Model',['../md_README.html#autotoc_md1993',1,'💬 Works with ANY Talking Model'],['../md_TODO.html#autotoc_md2239',1,'💬 Works with ANY Talking Model']]],
  ['target_5falias_20xp_5fdelta_20reason_14',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['task_15',['Section 1 – Batch Mode (&lt;span class=&quot;tt&quot;&gt;-c &quot;@agent task&quot;&lt;/span&gt;)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1385',1,'']]],
  ['task_20complete_20detection_20✅_16',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md770',1,'']]],
  ['task_20is_20sacred_17',['1. Mission First – The Project / Task Is Sacred',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md462',1,'']]],
  ['tasks_18',['Common Tasks',['../md_skills_2python__agent__expert.html#autotoc_md2172',1,'']]],
  ['team_20leader_20deputy_20supervisor_20levels_2020_2029_19',['Team Leader / Deputy Supervisor (Levels 20-29)',['../md_docs_2privilege__mapping.html#autotoc_md1484',1,'']]],
  ['team_20leader_20levels_2010_2019_20',['Senior Worker / Team Leader (Levels 10-19)',['../md_docs_2privilege__mapping.html#autotoc_md1483',1,'']]],
  ['technical_20details_21',['Technical Details',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1420',1,'Technical Details'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1926',1,'Technical Details']]],
  ['technical_20implementation_20details_22',['Technical Implementation Details',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md754',1,'']]],
  ['techniques_23',['Key Techniques',['../md_skills_2ida__pro__analysis__patterns.html#autotoc_md2167',1,'']]],
  ['template_24',['Template',['../md_AGENTS.html#autotoc_md33',1,'Example Skill Template'],['../md_skills_2reverse__engineering__expert.html#autotoc_md2175',1,'Workflow Template']]],
  ['term_20this_20week_25',['Short-Term (This Week)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md859',1,'']]],
  ['termination_20bugs_26',['Fix Summary: AXE Session Termination Bugs',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['test_27',['Test',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1456',1,'Batch Mode Test'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1427',1,'Bwrap Command Test'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1425',1,'Detection Test'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1358',1,'Ollama Integration Test'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1426',1,'Startup Warning Test']]],
  ['test_201_3a_20multiple_20workspaces_20from_20cli_28',['Test 1: Multiple Workspaces from CLI',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1363',1,'']]],
  ['test_201_3a_20ollama_20setup_20verification_20✅_29',['Test 1: Ollama Setup Verification ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1464',1,'']]],
  ['test_202_3a_20show_20current_20workspaces_30',['Test 2: Show Current Workspaces',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1364',1,'']]],
  ['test_202_3a_20subsumption_20architecture_20database_20✅_31',['Test 2: Subsumption Architecture + Database ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1465',1,'']]],
  ['test_203_3a_20add_20workspace_32',['Test 3: Add Workspace',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1365',1,'']]],
  ['test_203_3a_20xp_20voting_20system_20database_20✅_33',['Test 3: XP Voting System + Database ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1466',1,'']]],
  ['test_204_3a_20conflict_20detection_20arbitration_20✅_34',['Test 4: Conflict Detection &amp;amp; Arbitration ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1467',1,'']]],
  ['test_204_3a_20remove_20workspace_35',['Test 4: Remove Workspace',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1366',1,'']]],
  ['test_205_3a_20full_20integration_20in_20axe_20directory_20✅_36',['Test 5: Full Integration in AXE Directory ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1468',1,'']]],
  ['test_205_3a_20set_20multiple_20workspaces_20comma_20separated_37',['Test 5: Set Multiple Workspaces (Comma-Separated)',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1367',1,'']]],
  ['test_206_3a_20clear_20workspaces_38',['Test 6: Clear Workspaces',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1368',1,'']]],
  ['test_207_3a_20exit_39',['Test 7: Exit',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1369',1,'']]],
  ['test_208_3a_20workspace_20files_20access_40',['Test 8: Workspace Files Access',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1370',1,'']]],
  ['test_209_3a_20toolrunner_20synchronization_41',['Test 9: ToolRunner Synchronization',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1371',1,'']]],
  ['test_20adaptation_42',['4. Test Adaptation',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1092',1,'']]],
  ['test_20categories_43',['Test Categories',['../md_docs_2workshop_2test-results.html#autotoc_md1887',1,'']]],
  ['test_20compatibility_44',['1. Test Compatibility',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md831',1,'']]],
  ['test_20configuration_45',['Test Configuration',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1454',1,'']]],
  ['test_20connection_46',['Test Connection',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md537',1,'']]],
  ['test_20coverage_47',['Test Coverage',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md124',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md151',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md261',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md595',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md656',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md703',1,'Test Coverage']]],
  ['test_20coverage_20analysis_48',['Part 6: Test Coverage Analysis',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md921',1,'']]],
  ['test_20data_20integrity_49',['Test Data Integrity',['../md_docs_2workshop_2test-results.html#autotoc_md1907',1,'']]],
  ['test_20documentation_50',['Test Documentation',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md701',1,'']]],
  ['test_20effectiveness_51',['Test Effectiveness',['../md_docs_2workshop_2test-results.html#autotoc_md1898',1,'']]],
  ['test_20environment_52',['Test Environment',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1362',1,'Test Environment'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1381',1,'Test Environment'],['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1462',1,'Test Environment'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1755',1,'Test Environment'],['../md_docs_2workshop_2test-results.html#autotoc_md1884',1,'Test Environment']]],
  ['test_20environment_20validation_53',['Test Environment Validation',['../md_docs_2workshop_2test-results.html#autotoc_md1905',1,'']]],
  ['test_20execution_20logs_54',['Appendix A: Test Execution Logs',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md953',1,'']]],
  ['test_20execution_20summary_55',['Test Execution Summary',['../md_docs_2workshop_2test-results.html#autotoc_md1883',1,'Test Execution Summary'],['../md_docs_2workshop_2test-results.html#autotoc_md1894',1,'Test Execution Summary']]],
  ['test_20failures_20none_56',['Test Failures (None)',['../md_docs_2workshop_2test-results.html#autotoc_md1903',1,'']]],
  ['test_20file_201_3a_20unit_20tests_57',['Test File 1: Unit Tests',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md898',1,'']]],
  ['test_20file_202_3a_20integration_20tests_58',['Test File 2: Integration Tests',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md899',1,'']]],
  ['test_20files_59',['Test Files',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md897',1,'✅ VALIDATED - Test Files'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md126',1,'New Test Files'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md923',1,'PR Test Files']]],
  ['test_20files_20executed_60',['Test Files Executed',['../md_docs_2workshop_2test-results.html#autotoc_md1886',1,'']]],
  ['test_20fixtures_61',['Test Fixtures',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2183',1,'']]],
  ['test_20isolation_62',['3. Database Test Isolation',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md833',1,'']]],
  ['test_20mission_63',['AXE Test Mission',['../md_tests_2MISSION.html',1,'']]],
  ['test_20modules_64',['Other test modules',['../md_docs_2TESTING.html#autotoc_md1743',1,'']]],
  ['test_20projects_20for_20multi_20agent_20work_65',['Test Projects for Multi-Agent Work',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md576',1,'']]],
  ['test_20quality_20metrics_66',['Test Quality Metrics',['../md_docs_2workshop_2test-results.html#autotoc_md1897',1,'']]],
  ['test_20requirements_67',['Test Requirements',['../md_AGENTS.html#autotoc_md25',1,'']]],
  ['test_20results_68',['Test Results',['../md_docs_2LIVE__TEST__RESULTS.html',1,'AXE Live Feature Test Results'],['../md_docs_2workshop_2test-results.html#autotoc_md1888',1,'Detailed Test Results'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md894',1,'Document 5: Test Results'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md155',1,'Integration Test Results'],['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html',1,'Ollama Batch Mode Test Results'],['../md_docs_2OLLAMA__TEST__RESULTS.html',1,'Ollama Integration Test Results'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md127',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md206',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md235',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md263',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md346',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md513',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md596',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md655',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md780',1,'Test Results'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1549',1,'Test Results'],['../md_docs_2workshop_2security-audit.html#autotoc_md1875',1,'Test Results']]],
  ['test_20results_20md_69',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2test-results.html&quot;&gt;test-results.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1839',1,'']]],
  ['test_20results_20md_20test_20results_20md_70',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2test-results.html&quot;&gt;test-results.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1839',1,'']]],
  ['test_20results_20test_5fworkshop_20py_71',['Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1889',1,'']]],
  ['test_20results_20test_5fworkshop_5fintegration_20py_72',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1890',1,'']]],
  ['test_20results_20test_5fworkshop_5fperformance_20py_73',['Performance Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_performance.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1891',1,'']]],
  ['test_20results_20test_5fworkshop_5fsecurity_20py_74',['Security Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_security.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1892',1,'']]],
  ['test_20scenarios_75',['Test Scenarios',['../md_tests_2MISSION.html#autotoc_md2200',1,'']]],
  ['test_20scenarios_20executed_76',['Test Scenarios Executed',['../md_docs_2workshop_2security-audit.html#autotoc_md1874',1,'']]],
  ['test_20silently_20debug_20verbosely_77',['5. Test Silently, Debug Verbosely',['../md_skills_2build.html#autotoc_md2076',1,'']]],
  ['test_20statistics_78',['Overall Test Statistics',['../md_docs_2workshop_2test-results.html#autotoc_md1893',1,'']]],
  ['test_20suite_79',['XML TOOL PARSER TEST SUITE',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md789',1,'']]],
  ['test_20suite_80',['Test Suite',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md345',1,'4. Comprehensive Test Suite'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md896',1,'Claim 6: Test Suite'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md837',1,'PR Test Suite'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md954',1,'Validation Test Suite']]],
  ['test_20suite_20execution_20results_81',['Workshop Tools Test Suite Execution Results',['../md_docs_2workshop_2test-results.html',1,'']]],
  ['test_20suite_20overview_82',['Test Suite Overview',['../md_docs_2TESTING.html#autotoc_md1741',1,'Test Suite Overview'],['../md_docs_2workshop_2test-results.html#autotoc_md1885',1,'Test Suite Overview']]],
  ['test_20suite_20test_5ftool_5frunner_20py_83',['Original Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md704',1,'']]],
  ['test_20suite_20test_5ftool_5frunner_5fedge_5fcases_20py_84',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md705',1,'']]],
  ['test_20suite_20tests_20test_5fskills_5fmanager_20py_85',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md752',1,'']]],
  ['test_20suite_3a_20test_5follama_5fintegration_20py_86',['Test Suite: &lt;span class=&quot;tt&quot;&gt;test_ollama_integration.py&lt;/span&gt;',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1463',1,'']]],
  ['test_20summary_87',['Test Summary',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1099',1,'']]],
  ['test_20test_5fintegration_5fdatabase_5ffix_20py_88',['Integration Test (&lt;span class=&quot;tt&quot;&gt;test_integration_database_fix.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md232',1,'']]],
  ['test_3a_20live_20agent_20interactions_89',['Test: Live Agent Interactions',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1513',1,'']]],
  ['test_5fdatabase_5flocation_20py_90',['Unit Tests (&lt;span class=&quot;tt&quot;&gt;test_database_location.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md231',1,'']]],
  ['test_5fdynamic_5fmax_5ftokens_20py_20new_91',['6. &lt;span class=&quot;tt&quot;&gt;tests/test_dynamic_max_tokens.py&lt;/span&gt; (NEW)',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md281',1,'']]],
  ['test_5fend_5fto_5fend_20py_20main_20suite_92',['&lt;span class=&quot;tt&quot;&gt;tests/test_end_to_end.py&lt;/span&gt; (main suite)',['../md_docs_2TESTING.html#autotoc_md1742',1,'']]],
  ['test_5fintegration_5fdatabase_5ffix_20py_93',['Integration Test (&lt;span class=&quot;tt&quot;&gt;test_integration_database_fix.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md232',1,'']]],
  ['test_5fmodels_5fyaml_20py_94',['5. &lt;span class=&quot;tt&quot;&gt;tests/test_models_yaml.py&lt;/span&gt;',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md280',1,'']]],
  ['test_5follama_5fintegration_20py_95',['Test Suite: &lt;span class=&quot;tt&quot;&gt;test_ollama_integration.py&lt;/span&gt;',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1463',1,'']]],
  ['test_5fskills_5fmanager_20py_96',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md752',1,'']]],
  ['test_5ftool_5frunner_20py_97',['Original Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md704',1,'']]],
  ['test_5ftool_5frunner_5fedge_5fcases_20py_98',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md705',1,'']]],
  ['test_5fworkshop_20py_99',['Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1889',1,'']]],
  ['test_5fworkshop_5fintegration_20py_100',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1890',1,'']]],
  ['test_5fworkshop_5fperformance_20py_101',['Performance Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_performance.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1891',1,'']]],
  ['test_5fworkshop_5fsecurity_20py_102',['Security Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_security.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1892',1,'']]],
  ['test_5fxml_5ftool_5fparser_20py_103',['$ python3 test_xml_tool_parser.py',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md788',1,'']]],
  ['tested_104',['Environments Tested',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1428',1,'']]],
  ['testing_105',['Testing',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md725',1,'4. Comprehensive Testing'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1789',1,'Automated Installation Testing'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1790',1,'Dependency Resolution Testing'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md319',1,'Evidence from Live Testing'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1798',1,'Integration Testing'],['../md_docs_2features_2write-blocks.html#autotoc_md1293',1,'Interactive Testing'],['../md_docs_2features_2sandbox.html#autotoc_md1274',1,'Manual Testing'],['../md_docs_2features_2write-blocks.html#autotoc_md1292',1,'Manual Testing'],['../md_docs_2privilege__mapping.html#autotoc_md1490',1,'Manual Testing'],['../md_docs_2workshop_2test-results.html#autotoc_md1900',1,'Regression Testing'],['../md_AGENTS.html#autotoc_md23',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md230',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md288',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md310',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md332',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md492',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md523',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md594',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md631',1,'Testing'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md774',1,'Testing'],['../md_docs_2codex-implementation.html#autotoc_md1019',1,'Testing'],['../md_docs_2features_2anthropic-features.html#autotoc_md1153',1,'Testing'],['../md_docs_2features_2github-agent-integration.html#autotoc_md1211',1,'Testing'],['../md_docs_2features_2sandbox.html#autotoc_md1263',1,'Testing'],['../md_docs_2features_2write-blocks.html#autotoc_md1290',1,'Testing'],['../md_docs_2global-workspace.html#autotoc_md1322',1,'Testing'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1424',1,'Testing'],['../md_docs_2ollama-guide.html#autotoc_md1450',1,'Testing'],['../md_docs_2privilege__mapping.html#autotoc_md1489',1,'Testing'],['../md_docs_2privilege__mapping__quickref.html#autotoc_md1507',1,'Testing'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1560',1,'Testing'],['../md_docs_2references_2quick-reference.html#autotoc_md1573',1,'Testing'],['../md_docs_2socket__interface.html#autotoc_md1657',1,'Testing'],['../md_docs_2subsumption__architecture.html#autotoc_md1724',1,'Testing'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1923',1,'Testing'],['../md_docs_2xp__voting.html#autotoc_md1960',1,'Testing']]],
  ['testing_20✅_106',['Phase 4: Testing ✅',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md625',1,'']]],
  ['testing_209_2010_107',['✅ Testing (9/10)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md828',1,'']]],
  ['testing_20api_20keys_108',['Testing API Keys',['../md_docs_2api-providers.html#autotoc_md116',1,'']]],
  ['testing_20ci_109',['Recommended Models for Testing/CI',['../md_docs_2ollama-guide.html#autotoc_md1437',1,'']]],
  ['testing_20evidence_110',['Testing Evidence',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1357',1,'']]],
  ['testing_20guide_111',['AXE Testing Guide',['../md_docs_2TESTING.html',1,'']]],
  ['testing_20in_20real_20environment_112',['Testing in Real Environment',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1460',1,'']]],
  ['testing_20required_113',['⚠️ Manual Testing Required',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md372',1,'']]],
  ['testing_20requires_20api_20keys_114',['Manual testing (requires API keys)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md407',1,'']]],
  ['testing_20requires_20bubblewrap_20ollama_115',['Manual Testing (Requires bubblewrap + ollama)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1925',1,'']]],
  ['testing_20results_116',['Testing Results',['../md_docs_2workshop_2security-audit.html#autotoc_md1873',1,'Penetration Testing Results'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1098',1,'Testing Results'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1335',1,'Testing Results'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1625',1,'Testing Results']]],
  ['testing_20results_20workspace_20commands_117',['Interactive Testing Results - Workspace Commands',['../md_docs_2INTERACTIVE__TEST__RESULTS.html',1,'']]],
  ['testing_20silent_118',['Pattern 3: Regression Testing (Silent)',['../md_skills_2claude__build.html#autotoc_md2147',1,'']]],
  ['testing_20status_119',['Testing Status',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md369',1,'']]],
  ['testing_20tests_120',['2. Testing (tests/)',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1613',1,'']]],
  ['tests_121',['Tests',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md706',1,'Documentation Tests'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md312',1,'Existing Tests'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md334',1,'Existing Tests'],['../md_AGENTS.html#autotoc_md24',1,'Running Tests'],['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1470',1,'Running the Tests'],['../md_docs_2workshop_2test-results.html#autotoc_md1904',1,'Skipped Tests'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md898',1,'Test File 1: Unit Tests'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md899',1,'Test File 2: Integration Tests'],['../md_docs_2features_2write-blocks.html#autotoc_md1291',1,'Unit Tests'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1924',1,'Unit Tests'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md125',1,'Updated Tests']]],
  ['tests_122',['tests',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1613',1,'2. Testing (tests/)'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md790',1,'[... all tests ...]'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md405',1,'Run all unit tests'],['../md_docs_2references_2quick-reference.html#autotoc_md1574',1,'Run automated tests'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md805',1,'Unit tests']]],
  ['tests_20added_123',['Tests Added',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md262',1,'New Tests Added'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md333',1,'New Tests Added']]],
  ['tests_20created_124',['Tests Created',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md922',1,'Custom Validation Tests Created'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md311',1,'Unit Tests Created']]],
  ['tests_20fixtures_20readme_20md_125',['tests/fixtures/README.md',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2182',1,'']]],
  ['tests_20passed_126',['✅ ALL TESTS PASSED!',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md791',1,'']]],
  ['tests_20passed_127',['Tests Passed',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md371',1,'✅ Integration Tests Passed'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md370',1,'✅ Unit Tests Passed']]],
  ['tests_20quietly_128',['Run tests quietly',['../md_skills_2build.html#autotoc_md2087',1,'']]],
  ['tests_20silently_129',['tests silently',['../md_skills_2claude__build.html#autotoc_md2111',1,'Compile with ASan and run tests silently'],['../md_skills_2build.html#autotoc_md2090',1,'Run tests silently']]],
  ['tests_20test_5fdatabase_5flocation_20py_130',['Unit Tests (&lt;span class=&quot;tt&quot;&gt;test_database_location.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md231',1,'']]],
  ['tests_20test_5fdynamic_5fmax_5ftokens_20py_20new_131',['6. &lt;span class=&quot;tt&quot;&gt;tests/test_dynamic_max_tokens.py&lt;/span&gt; (NEW)',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md281',1,'']]],
  ['tests_20test_5fend_5fto_5fend_20py_20main_20suite_132',['&lt;span class=&quot;tt&quot;&gt;tests/test_end_to_end.py&lt;/span&gt; (main suite)',['../md_docs_2TESTING.html#autotoc_md1742',1,'']]],
  ['tests_20test_5fmodels_5fyaml_20py_133',['5. &lt;span class=&quot;tt&quot;&gt;tests/test_models_yaml.py&lt;/span&gt;',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md280',1,'']]],
  ['tests_20test_5fskills_5fmanager_20py_134',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md752',1,'']]],
  ['tests_20verify_20no_20breakage_135',['Existing tests (verify no breakage)',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md807',1,'']]],
  ['tests_20with_20xvfb_136',['Running interactive/GUI tests with Xvfb',['../md_docs_2TESTING.html#autotoc_md1744',1,'']]],
  ['text_20file_137',['1. Simple Text File',['../md_docs_2features_2write-blocks.html#autotoc_md1282',1,'']]],
  ['text_20generation_138',['Usage - Text Generation',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md561',1,'']]],
  ['that_20may_20be_20included_20by_20accident_139',['that may be included by accident',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md191',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['the_204_20principles_140',['Session Rules (The 4 Principles)',['../md_docs_2references_2quick-reference.html#autotoc_md1564',1,'']]],
  ['the_20axe_20context_141',['What Is SRI in the AXE Context?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1684',1,'']]],
  ['the_20entire_20block_20contains_20a_20heredoc_142',['Check if the entire block contains a heredoc',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md257',1,'']]],
  ['the_20issue_143',['The Issue',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md326',1,'']]],
  ['the_20office_20vision_20—_20alignment_20assessment_144',['The &quot;Office&quot; Vision — Alignment Assessment',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md998',1,'']]],
  ['the_20office_20vision_20and_20sri_145',['The &quot;Office&quot; Vision and SRI',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1702',1,'']]],
  ['the_20problem_146',['The Problem',['../md_docs_2codex-implementation.html#autotoc_md1004',1,'']]],
  ['the_20problem_147',['Evidence of the Problem',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md119',1,'']]],
  ['the_20project_20task_20is_20sacred_148',['1. Mission First – The Project / Task Is Sacred',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md462',1,'']]],
  ['the_20solution_149',['The Solution',['../md_docs_2codex-implementation.html#autotoc_md1005',1,'']]],
  ['the_20tests_150',['Running the Tests',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1470',1,'']]],
  ['the_20whole_20block_20as_20a_20single_20command_151',['If so, treat the whole block as a single command',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md258',1,'']]],
  ['then_20exepack_152',['Then EXEPACK',['../md_skills_2dos__packer__detector.html#autotoc_md2161',1,'']]],
  ['then_20pklite_153',['Then PKLITE',['../md_skills_2dos__packer__detector.html#autotoc_md2160',1,'']]],
  ['theoretical_20foundations_154',['Theoretical Foundations',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1109',1,'']]],
  ['theory_155',['Theory',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1509',1,'']]],
  ['theory_20alignment_156',['Theory Alignment',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1338',1,'']]],
  ['theory_20alignment_20minsky_201986_157',['Theory Alignment (Minsky 1986)',['../md_docs_2xp__voting.html#autotoc_md1953',1,'']]],
  ['theory_20background_158',['Theory Background',['../md_docs_2global-workspace.html#autotoc_md1302',1,'Theory Background'],['../md_docs_2privilege__mapping.html#autotoc_md1473',1,'Theory Background']]],
  ['these_20are_20now_20handled_20exclusively_20by_20axe_20py_20responseprocessor_159',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md253',1,'']]],
  ['these_20limits_160',['Why These Limits?',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md421',1,'']]],
  ['these_20modules_20first_161',['Why These Modules First?',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md628',1,'']]],
  ['these_20references_162',['Using These References',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1595',1,'']]],
  ['thinking_163',['2. Extended Thinking',['../md_docs_2features_2anthropic-features.html#autotoc_md1134',1,'']]],
  ['thinking_20enhanced_20reasoning_20✅_164',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md145',1,'']]],
  ['thinking_20not_20available_165',['Extended thinking not available',['../md_docs_2features_2anthropic-features.html#autotoc_md1156',1,'']]],
  ['this_20matters_166',['Why This Matters',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md801',1,'']]],
  ['this_20proves_167',['What This Proves',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1515',1,'']]],
  ['this_20week_168',['Short-Term (This Week)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md859',1,'']]],
  ['this_20works_169',['Why This Works',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md330',1,'']]],
  ['thread_170',['Background Monitor Thread',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md468',1,'']]],
  ['thread_20safety_171',['Thread Safety',['../md_docs_2global-workspace.html#autotoc_md1317',1,'Thread Safety'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1333',1,'Thread Safety']]],
  ['three_20file_20architecture_172',['1. Three-File Architecture',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1545',1,'']]],
  ['tiers_173',['Tiers',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1498',1,'Level Tiers'],['../md_docs_2privilege__mapping.html#autotoc_md1475',1,'Privilege Tiers'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md416',1,'Sleep Quality Tiers']]],
  ['timeline_174',['Timeline',['../md_docs_2conflict__resolution__examples.html#autotoc_md1073',1,'']]],
  ['tiny_20models_201gb_20best_20for_20ci_20minimal_20resources_175',['Tiny Models (&amp;lt; 1GB) - Best for CI/Minimal Resources',['../md_docs_2ollama-guide.html#autotoc_md1438',1,'']]],
  ['tips_20for_20humans_176',['Tips for Humans',['../md_docs_2references_2quick-reference.html#autotoc_md1576',1,'']]],
  ['title_20progression_177',['Title Progression',['../md_TODO.html#autotoc_md2243',1,'🎮 XP/Level/Title Progression'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1405',1,'Section 11 – XP / Level / Title Progression']]],
  ['tl_20dr_178',['Quick Install (TL;DR)',['../md_README.html#autotoc_md1999',1,'']]],
  ['tmp_20axe_20docs_20features_20anthropic_20features_20md_20anthropic_20features_20md_179',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2anthropic-features.html&quot;&gt;anthropic-features.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1239',1,'']]],
  ['tmp_20axe_20docs_20features_20github_20agent_20integration_20md_20github_20agent_20integration_20md_180',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2github-agent-integration.html&quot;&gt;github-agent-integration.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1240',1,'']]],
  ['tmp_20axe_20docs_20features_20parsers_20md_20parsers_20md_181',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2parsers.html&quot;&gt;parsers.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1238',1,'']]],
  ['tmp_20axe_20docs_20features_20sandbox_20md_20sandbox_20md_182',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2sandbox.html&quot;&gt;sandbox.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1236',1,'']]],
  ['tmp_20axe_20docs_20features_20write_20blocks_20md_20write_20blocks_20md_183',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2write-blocks.html&quot;&gt;write-blocks.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1237',1,'']]],
  ['tmp_20axe_20docs_20references_20quick_20reference_20md_20quick_20reference_20md_184',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2references_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1590',1,'']]],
  ['tmp_20axe_20docs_20workshop_20benchmarks_20md_20benchmarks_20md_185',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2benchmarks.html&quot;&gt;benchmarks.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1836',1,'']]],
  ['tmp_20axe_20docs_20workshop_20dependency_20validation_20md_20dependency_20validation_20md_186',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2dependency-validation.html&quot;&gt;dependency-validation.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1838',1,'']]],
  ['tmp_20axe_20docs_20workshop_20quick_20reference_20md_20quick_20reference_20md_187',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1835',1,'']]],
  ['tmp_20axe_20docs_20workshop_20security_20audit_20md_20security_20audit_20md_188',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2security-audit.html&quot;&gt;security-audit.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1837',1,'']]],
  ['tmp_20axe_20docs_20workshop_20test_20results_20md_20test_20results_20md_189',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2test-results.html&quot;&gt;test-results.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1839',1,'']]],
  ['tmp_20bin_20and_20path_190',['&lt;span class=&quot;tt&quot;&gt;/tmp/bin&lt;/span&gt; and PATH',['../md_docs_2TESTING.html#autotoc_md1737',1,'']]],
  ['to_191',['I want to...',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1532',1,'']]],
  ['to_20archive_192',['to Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md969',1,'Adding to Archive'],['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md968',1,'Contributing to Archive']]],
  ['to_20complexity_193',['Example 3: Escalation Due to Complexity',['../md_docs_2conflict__resolution__examples.html#autotoc_md1066',1,'']]],
  ['to_20files_194',['APPEND - Append to Files',['../md_docs_2features_2parsers.html#autotoc_md1224',1,'']]],
  ['to_20find_20it_3a_195',['Where to Find It:',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1027',1,'']]],
  ['to_20prevent_20duplicate_20execution_196',['to prevent duplicate execution',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md254',1,'']]],
  ['to_20privilege_20mapping_20system_197',['Level-to-Privilege Mapping System',['../md_docs_2privilege__mapping.html',1,'']]],
  ['to_20re_20run_198',['How to re-run',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1383',1,'']]],
  ['to_20readme_20md_199',['Academic References Added to README.md',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1353',1,'']]],
  ['to_20requirements_20txt_200',['Added to requirements.txt',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md843',1,'']]],
  ['to_20response_201',['Append results to response',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md400',1,'']]],
  ['to_20resume_20later_202',['&quot;Want to resume later&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1584',1,'']]],
  ['to_20sandbox_203',['From Whitelist to Sandbox',['../md_docs_2features_2sandbox.html#autotoc_md1268',1,'']]],
  ['to_20supervisor_204',['Question posed to supervisor',['../md_docs_2SRI__AGENT__DISCUSSION.html#autotoc_md1675',1,'']]],
  ['to_20unrestricted_20mode_205',['&quot;bubblewrap not available, falling back to unrestricted mode&quot;',['../md_docs_2features_2sandbox.html#autotoc_md1270',1,'']]],
  ['to_20use_206',['How to Use',['../md_llm__prep_2codebase__overview.html#autotoc_md1971',1,'']]],
  ['to_20use_20archive_207',['When to Use Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md966',1,'']]],
  ['to_20use_20each_20level_208',['When to Use Each Level',['../md_docs_2codex-implementation.html#autotoc_md1009',1,'']]],
  ['to_20use_20verbose_20output_209',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md36',1,'']]],
  ['to_20vote_210',['When to Vote',['../md_docs_2xp__voting.html#autotoc_md1956',1,'']]],
  ['to_20whitelist_20mode_211',['Compared to Whitelist Mode',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md660',1,'']]],
  ['today_212',['What Exists Today',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1686',1,'']]],
  ['token_20counting_213',['3. Token Counting',['../md_docs_2features_2anthropic-features.html#autotoc_md1139',1,'']]],
  ['token_20counting_20fails_214',['Token counting fails',['../md_docs_2features_2anthropic-features.html#autotoc_md1157',1,'']]],
  ['token_20counting_20precise_20estimates_20✅_215',['3. Token Counting (Precise Estimates) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md146',1,'']]],
  ['token_20efficiency_20analysis_216',['Token Efficiency Analysis',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md757',1,'']]],
  ['token_20format_217',['Token Format',['../md_docs_2features_2github-agent-integration.html#autotoc_md1202',1,'']]],
  ['token_20limit_20errors_20413_20not_20handled_20✅_218',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['token_20optimization_20savings_219',['Section 4 – Token Optimization / Savings',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1391',1,'']]],
  ['token_20optimization_20strategies_220',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md55',1,'']]],
  ['token_20purpose_221',['Token Purpose',['../md_MISSION.html#autotoc_md1981',1,'']]],
  ['token_20reduction_222',['Token Reduction',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md512',1,'']]],
  ['token_20reference_223',['Token Reference',['../md_MISSION.html#autotoc_md1980',1,'']]],
  ['token_20saving_20system_224',['💾 Token Saving System',['../md_TODO.html#autotoc_md2245',1,'']]],
  ['token_20savings_20—_20verification_20and_20reporting_225',['7. Token Savings — Verification and Reporting',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md994',1,'']]],
  ['token_20savings_20✅_226',['1. Prompt Caching (90% Token Savings) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md144',1,'']]],
  ['token_20savings_20estimates_227',['Token Savings Estimates',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md730',1,'Token Savings Estimates'],['../md_skills_2build.html#autotoc_md2059',1,'Token Savings Estimates']]],
  ['token_20savings_20example_228',['Token Savings Example',['../md_docs_2features_2anthropic-features.html#autotoc_md1131',1,'']]],
  ['token_20savings_20in_20security_20audits_229',['Token Savings in Security Audits',['../md_skills_2claude__build.html#autotoc_md2130',1,'']]],
  ['token_20statistics_20with_20cache_20tracking_230',['Token Statistics with Cache Tracking',['../md_docs_2features_2anthropic-features.html#autotoc_md1148',1,'']]],
  ['token_20truncation_20fixed_20✓_231',['2. Token Truncation Fixed ✓',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md285',1,'']]],
  ['token_20usage_20tracking_232',['Token Usage Tracking',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md380',1,'']]],
  ['token_20usage_20tracking_20ui_20✅_233',['1. Token Usage Tracking UI ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md360',1,'']]],
  ['tokens_234',['Tokens',['../md_MISSION.html#autotoc_md1979',1,'Agent Communication Tokens'],['../md_docs_2subsumption__architecture.html#autotoc_md1718',1,'Agent Tokens'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1030',1,'Cognitive Architecture Tokens']]],
  ['tokens_20implementation_20summary_235',['Dynamic Max Output Tokens Implementation Summary',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html',1,'']]],
  ['tokens_20not_20working_236',['Tokens Not Working?',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1045',1,'']]],
  ['too_20large_237',['Model Too Large?',['../md_docs_2ollama-guide.html#autotoc_md1445',1,'']]],
  ['tool_238',['Option B: Using mkpyenv tool',['../md_README.html#autotoc_md2001',1,'']]],
  ['tool_20call_20parser_20implementation_239',['Multi-Format Tool Call Parser Implementation',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'']]],
  ['tool_20call_20parser_20quick_20reference_240',['Multi-Format Tool Call Parser - Quick Reference',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['tool_20call_20parsers_241',['Tool Call Parsers',['../md_docs_2features_2parsers.html',1,'']]],
  ['tool_20chain_20silent_242',['Pattern 2: Security Tool Chain (Silent)',['../md_skills_2claude__build.html#autotoc_md2146',1,'']]],
  ['tool_20efficiency_20comparison_243',['Tool Efficiency Comparison',['../md_docs_2workshop_2benchmarks.html#autotoc_md1769',1,'']]],
  ['tool_20interactions_244',['Cross-Tool Interactions',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1800',1,'']]],
  ['tool_20parser_20test_20suite_245',['XML TOOL PARSER TEST SUITE',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md789',1,'']]],
  ['tool_20quick_20reference_246',['Security Tool Quick Reference',['../md_skills_2claude__build.html#autotoc_md2140',1,'']]],
  ['tool_20runner_20integration_20core_20tool_5frunner_20py_247',['2. Tool Runner Integration (&lt;span class=&quot;tt&quot;&gt;core/tool_runner.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1916',1,'']]],
  ['tool_20setup_248',['Helper Tool Setup',['../md_docs_2TESTING.html#autotoc_md1736',1,'']]],
  ['tool_20syntax_20fix_20summary_249',['Collaborative Mode Tool Syntax Fix - Summary',['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html',1,'']]],
  ['tool_20version_20check_250',['Tool Version Check',['../md__8collab__env.html#autotoc_md9',1,'']]],
  ['tool_5frunner_20py_251',['2. Tool Runner Integration (&lt;span class=&quot;tt&quot;&gt;core/tool_runner.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1916',1,'']]],
  ['toolchain_252',['Build Toolchain',['../md__8collab__env.html#autotoc_md3',1,'']]],
  ['toolchain_20summary_253',['RE Toolchain summary',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2197',1,'']]],
  ['toolrunner_20synchronization_254',['Test 9: ToolRunner Synchronization',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1371',1,'']]],
  ['tools_255',['Tools',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md819',1,'✅ Four Dynamic Analysis Tools'],['../md_ARCHITECTURE.html#autotoc_md54',1,'3. Adding New Workshop Tools'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1841',1,'Accessing Workshop Tools'],['../md_README.html#autotoc_md2012',1,'Analysis Tools'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1827',1,'AXE Workshop Tools'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1829',1,'Core Tools'],['../md__8collab__env.html#autotoc_md4',1,'Reverse Engineering Tools'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1407',1,'Section 12 – Workshop Tools'],['../md_skills_2claude__build.html#autotoc_md2103',1,'Security-Specific Tools'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1811',1,'Tools'],['../md_docs_2conflict__resolution__examples.html#autotoc_md1079',1,'Workshop Tools'],['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1527',1,'Workshop Tools'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1828',1,'Workshop Tools'],['../md_README.html#autotoc_md2014',1,'Workshop Tools']]],
  ['tools_20benchmarks_256',['Workshop Tools Benchmarks',['../md_docs_2workshop_2benchmarks.html',1,'']]],
  ['tools_20dependency_20validation_257',['Workshop Tools Dependency Validation',['../md_docs_2workshop_2dependency-validation.html',1,'']]],
  ['tools_20directory_258',['Tools Directory',['../md_README.html#autotoc_md2036',1,'']]],
  ['tools_20expand_259',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md2162',1,'']]],
  ['tools_20implemented_260',['Claim 1: Four Analysis Tools Implemented',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md871',1,'']]],
  ['tools_20quick_20reference_261',['Workshop Tools Quick Reference',['../md_docs_2workshop_2quick-reference.html',1,'']]],
  ['tools_20quietly_262',['5. Combine Multiple Security Tools Quietly',['../md_skills_2claude__build.html#autotoc_md2138',1,'']]],
  ['tools_20security_20audit_263',['Workshop Tools Security Audit',['../md_docs_2workshop_2security-audit.html',1,'']]],
  ['tools_20status_20discovery_20✅_264',['4. Workshop Tools Status &amp;amp; Discovery ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md363',1,'']]],
  ['tools_20test_20suite_20execution_20results_265',['Workshop Tools Test Suite Execution Results',['../md_docs_2workshop_2test-results.html',1,'']]],
  ['top_20models_266',['Top Models',['../md_docs_2api-providers.html#autotoc_md66',1,'Top Models'],['../md_docs_2api-providers.html#autotoc_md74',1,'Top Models'],['../md_docs_2api-providers.html#autotoc_md83',1,'Top Models'],['../md_docs_2api-providers.html#autotoc_md93',1,'Top Models'],['../md_docs_2api-providers.html#autotoc_md101',1,'Top Models']]],
  ['total_20lines_20of_20code_267',['Total Lines of Code',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1633',1,'']]],
  ['trace_20configuration_268',['dosbox-staging trace configuration',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2194',1,'']]],
  ['trace_5fexecution_5fpath_269',['trace_execution_path',['../md_skills_2trace__execution__path.html',1,'']]],
  ['tracking_270',['Tracking',['../md_docs_2features_2anthropic-features.html#autotoc_md1148',1,'Token Statistics with Cache Tracking'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md380',1,'Token Usage Tracking']]],
  ['tracking_20✅_271',['Phase 5: Resource Tracking ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md484',1,'']]],
  ['tracking_20ui_20✅_272',['1. Token Usage Tracking UI ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md360',1,'']]],
  ['trailing_20backticks_20that_20may_20be_20included_20by_20accident_273',['trailing backticks that may be included by accident',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md191',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['transformers_20local_274',['Usage - Transformers (Local)',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md549',1,'']]],
  ['treat_20the_20whole_20block_20as_20a_20single_20command_275',['If so, treat the whole block as a single command',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md258',1,'']]],
  ['trees_276',['ast (Abstract Syntax Trees)',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1781',1,'']]],
  ['trends_277',['Resource Utilization Trends',['../md_docs_2workshop_2benchmarks.html#autotoc_md1770',1,'']]],
  ['trials_20fail_278',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md2163',1,'']]],
  ['trigger_20a_20session_20save_279',['Can an Agent Trigger a Session Save?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1689',1,'']]],
  ['triggers_280',['Triggers',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md436',1,'Break Triggers'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md417',1,'Wake-up Triggers']]],
  ['troubleshooting_281',['Troubleshooting',['../md_docs_2api-providers.html#autotoc_md114',1,'Troubleshooting'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md579',1,'Troubleshooting'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md808',1,'Troubleshooting'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1044',1,'Troubleshooting'],['../md_docs_2features_2anthropic-features.html#autotoc_md1154',1,'Troubleshooting'],['../md_docs_2features_2configuration.html#autotoc_md1186',1,'Troubleshooting'],['../md_docs_2features_2sandbox.html#autotoc_md1269',1,'Troubleshooting'],['../md_docs_2ollama-guide.html#autotoc_md1444',1,'Troubleshooting'],['../md_docs_2socket__interface.html#autotoc_md1658',1,'Troubleshooting'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1807',1,'Troubleshooting']]],
  ['true_282',['&lt;span class=&quot;tt&quot;&gt;get_directives(active_only=True)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1312',1,'']]],
  ['truncation_20fixed_20✓_283',['2. Token Truncation Fixed ✓',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md285',1,'']]],
  ['try_20is_20safe_284',['Why &lt;span class=&quot;tt&quot;&gt;--unshare-user-try&lt;/span&gt; is Safe',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1421',1,'']]],
  ['try_20unlzexe_20first_20very_20common_285',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md2159',1,'']]],
  ['turn_20based_20round_20robin_20multi_20agent_286',['🔄 Turn-based Round-Robin Multi-Agent',['../md_TODO.html#autotoc_md2242',1,'']]],
  ['turn_20management_287',['Turn Management',['../md_docs_2subsumption__architecture.html#autotoc_md1716',1,'']]],
  ['turns_20✅_288',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['txt_289',['Added to requirements.txt',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md843',1,'']]],
  ['type_20hints_20good_290',['Type Hints - GOOD',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md918',1,'']]]
];
