var searchData=
[
  ['v1_200_20current_0',['v1.0 (Current)',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1498',1,'']]],
  ['valgrind_20memory_20analysis_1',['Valgrind (Memory Analysis)',['../md_skills_2claude__build.html#autotoc_md1213',1,'']]],
  ['validate_20filename_2',['Validate filename',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md464',1,'']]],
  ['validated_20bonus_20xp_20calculation_3',['✅ VALIDATED - Bonus XP Calculation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md761',1,'']]],
  ['validated_20chisel_20symbolic_20execution_4',['✅ VALIDATED - Chisel (Symbolic Execution)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md750',1,'']]],
  ['validated_20configuration_20structure_5',['✅ VALIDATED - Configuration Structure',['../md_PR23__VALIDATION__REPORT.html#autotoc_md764',1,'']]],
  ['validated_20database_20methods_6',['✅ VALIDATED - Database Methods',['../md_PR23__VALIDATION__REPORT.html#autotoc_md757',1,'']]],
  ['validated_20database_20schema_7',['✅ VALIDATED - Database Schema',['../md_PR23__VALIDATION__REPORT.html#autotoc_md756',1,'']]],
  ['validated_20documentation_20files_8',['✅ VALIDATED - Documentation Files',['../md_PR23__VALIDATION__REPORT.html#autotoc_md767',1,'']]],
  ['validated_20hammer_20live_20instrumentation_9',['✅ VALIDATED - Hammer (Live Instrumentation)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md753',1,'']]],
  ['validated_20plane_20source_20sink_20enumeration_10',['✅ VALIDATED - Plane (Source/Sink Enumeration)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md752',1,'']]],
  ['validated_20saw_20taint_20analysis_11',['✅ VALIDATED - Saw (Taint Analysis)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md751',1,'']]],
  ['validated_20test_20files_12',['✅ VALIDATED - Test Files',['../md_PR23__VALIDATION__REPORT.html#autotoc_md775',1,'']]],
  ['validated_20xp_20awards_20dictionary_13',['✅ VALIDATED - XP Awards Dictionary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md760',1,'']]],
  ['validation_14',['Validation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md805',1,'Dependency Validation'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md771',1,'Document 4: Dependency Validation'],['../md_workshop__security__audit.html#autotoc_md1430',1,'Finding #1: Missing Input Size Validation'],['../md_workshop__dependency__validation.html#autotoc_md1378',1,'Installation Validation'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md785',1,'Part 3: Security Validation'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md790',1,'Part 4: Performance Validation'],['../md_workshop__dependency__validation.html#autotoc_md1385',1,'Security Validation'],['../md_workshop__test__results.html#autotoc_md1470',1,'Test Environment Validation'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md394',1,'Validation'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1316',1,'Validation'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1329',1,'Validation'],['../md_workshop__dependency__validation.html',1,'Workshop Tools Dependency Validation'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1151',1,'YAML Validation']]],
  ['validation_20conclusion_15',['Part 10: Validation Conclusion',['../md_PR23__VALIDATION__REPORT.html#autotoc_md816',1,'']]],
  ['validation_20internal_20stripped_20version_20_3a_16',['Validation (internal, stripped version):',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md413',1,'']]],
  ['validation_20quality_20assurance_17',['Validation &amp;amp; Quality Assurance',['../md_workshop__quick__reference.html#autotoc_md1416',1,'']]],
  ['validation_20report_18',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_PR23__VALIDATION__REPORT.html',1,'']]],
  ['validation_20results_19',['Validation Results',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md713',1,'']]],
  ['validation_20sign_20off_20',['Validation Sign-Off',['../md_PR23__VALIDATION__REPORT.html#autotoc_md829',1,'']]],
  ['validation_20suite_21',['Custom Validation Suite',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md714',1,'']]],
  ['validation_20summary_22',['Validation Summary',['../md_workshop__dependency__validation.html#autotoc_md1364',1,'']]],
  ['validation_20test_20suite_23',['Validation Test Suite',['../md_PR23__VALIDATION__REPORT.html#autotoc_md832',1,'']]],
  ['validation_20tests_20created_24',['Custom Validation Tests Created',['../md_PR23__VALIDATION__REPORT.html#autotoc_md800',1,'']]],
  ['validation_20verified_25',['Input Validation - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md787',1,'']]],
  ['variable_26',['Variable',['../md_API__PROVIDERS.html#autotoc_md110',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md118',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md128',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md137',1,'Environment Variable'],['../md_API__PROVIDERS.html#autotoc_md146',1,'Environment Variable']]],
  ['variables_20summary_27',['Environment Variables Summary',['../md_API__PROVIDERS.html#autotoc_md152',1,'']]],
  ['verbose_28',['Verbose',['../md_skills_2claude__build.html#autotoc_md1241',1,'1. Start Silent, Investigate Verbose'],['../md_skills_2claude__build.html#autotoc_md1235',1,'Phase 3: Detailed Investigation (Verbose)']]],
  ['verbose_20by_20default_29',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md1189',1,'']]],
  ['verbose_20on_20failure_30',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md1182',1,'']]],
  ['verbose_20output_31',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md59',1,'']]],
  ['verbose_20output_3a_32',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['verbosely_33',['5. Test Silently, Debug Verbosely',['../md_skills_2build.html#autotoc_md1185',1,'']]],
  ['verification_34',['Verification',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md234',1,'Manual Verification'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md779',1,'Part 2: Integration Verification'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md37',1,'Verification'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md232',1,'Verification'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md334',1,'Verification'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md410',1,'Verification'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1137',1,'Verification']]],
  ['verification_35',['Manual verification',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1521',1,'']]],
  ['verification_20results_36',['Verification Results',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1150',1,'']]],
  ['verified_37',['VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md787',1,'Input Validation - VERIFIED'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md786',1,'No Hardcoded Secrets - VERIFIED'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md788',1,'Resource Controls - VERIFIED']]],
  ['verify_20no_20breakage_38',['Existing tests (verify no breakage)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1522',1,'']]],
  ['version_20_3a_39',['version :',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md414',1,'Execution (original version):'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md413',1,'Validation (internal, stripped version):']]],
  ['version_20check_40',['Tool Version Check',['../md__8collab__env.html#autotoc_md9',1,'']]],
  ['version_20control_41',['Version Control',['../md_README.html#autotoc_md920',1,'']]],
  ['version_20pinning_42',['Finding #4: Dependency Version Pinning',['../md_workshop__security__audit.html#autotoc_md1433',1,'']]],
  ['version_20support_43',['Python Version Support',['../md_workshop__dependency__validation.html#autotoc_md1376',1,'']]],
  ['very_20common_44',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md1268',1,'']]],
  ['view_45',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['view_20analysis_20history_46',['View Analysis History',['../md_README.html#autotoc_md966',1,'']]],
  ['view_20usage_20statistics_47',['View Usage Statistics',['../md_README.html#autotoc_md967',1,'']]],
  ['viewing_20diagrams_48',['Viewing Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md281',1,'']]],
  ['viewing_20session_20rules_49',['Viewing Session Rules',['../md_IMPROVEMENTS__README.html#autotoc_md558',1,'']]],
  ['vision_20example_20images_50',['Vision Example (Images)',['../md_API__PROVIDERS.html#autotoc_md121',1,'']]],
  ['vs_20actual_20implementation_51',['Part 1: PR Claims vs. Actual Implementation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md748',1,'']]],
  ['vs_20after_52',['Example - Before vs After',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md411',1,'']]],
  ['vs_20code_53',['VS Code',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md284',1,'']]],
  ['vulnerability_20scan_54',['Dependency Vulnerability Scan',['../md_workshop__dependency__validation.html#autotoc_md1386',1,'']]]
];
