var searchData=
[
  ['b_3a_20file_20changes_20summary_0',['Appendix B: File Changes Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md834',1,'']]],
  ['back_20to_20whitelist_20mode_1',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['background_20monitor_20thread_2',['Background Monitor Thread',['../md_IMPROVEMENTS__FINAL.html#autotoc_md531',1,'']]],
  ['backticks_20that_20may_20be_20included_20by_20accident_3',['backticks that may be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['backward_20compatibility_4',['Backward Compatibility',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md35',1,'Backward Compatibility'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md86',1,'Backward Compatibility'],['../md_BUG__FIX__SUMMARY.html#autotoc_md206',1,'Backward Compatibility'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md239',1,'Backward Compatibility'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md268',1,'Backward Compatibility'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md353',1,'Backward Compatibility'],['../md_FIXES__SUMMARY.html#autotoc_md384',1,'Backward Compatibility'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md680',1,'Backward Compatibility'],['../md_REFACTORING__NOTES.html#autotoc_md1010',1,'Backward Compatibility'],['../md_SANDBOX.html#autotoc_md1035',1,'Backward Compatibility'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1075',1,'Backward Compatibility'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1527',1,'Backward Compatibility'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md331',1,'Example 3: Backward Compatibility']]],
  ['based_20error_20detection_20metrics_5',['Diff-Based Error Detection Metrics',['../md_IMPROVEMENTS__FINAL.html#autotoc_md488',1,'']]],
  ['based_20sleep_20system_6',['Permission-Based Sleep System',['../md_IMPROVEMENTS__FINAL.html#autotoc_md478',1,'']]],
  ['bash_20xml_20tags_20claude_20s_20favorite_7',['1. Bash XML Tags (Claude&apos;s Favorite)',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md689',1,'']]],
  ['basic_20agent_20conversations_8',['Basic Agent Conversations',['../md_README.html#autotoc_md894',1,'']]],
  ['basic_20usage_20automatic_9',['Basic Usage (Automatic)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1311',1,'']]],
  ['batch_20processing_10',['Batch Processing',['../md_README.html#autotoc_md928',1,'']]],
  ['be_20included_20by_20accident_11',['be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['before_12',['Before',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md174',1,'Before'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md182',1,'Before'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md186',1,'Before'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md236',1,'Before'],['../md_REFACTORING__NOTES.html#autotoc_md995',1,'Before']]],
  ['before_13',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['before_20after_20comparison_20of_20fixes_14',['Before/After Comparison of Fixes',['../md_BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['before_20axe_20yaml_15',['Before (axe.yaml)',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md178',1,'']]],
  ['before_20fix_16',['Before Fix',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'Example of Duplicate Execution (Before Fix)'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md221',1,'Impact Before Fix']]],
  ['before_20vs_20after_17',['Example - Before vs After',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md411',1,'']]],
  ['behavior_18',['Behavior',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1489',1,'Behavior'],['../md_QUICK__REFERENCE.html#autotoc_md854',1,'Encouraging Good Behavior'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md216',1,'Expected Behavior']]],
  ['being_20–_20no_20real_20bullying_19',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['benchmarks_20',['Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1346',1,'Chisel - Symbolic Execution Benchmarks'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md769',1,'Document 2: Performance Benchmarks'],['../md_workshop__benchmarks.html#autotoc_md1355',1,'Hammer - Live Instrumentation Benchmarks'],['../md_workshop__test__results.html#autotoc_md1461',1,'Performance Benchmarks'],['../md_workshop__benchmarks.html#autotoc_md1352',1,'Plane - Source/Sink Enumeration Benchmarks'],['../md_workshop__benchmarks.html#autotoc_md1349',1,'Saw - Taint Analysis Benchmarks'],['../md_workshop__benchmarks.html',1,'Workshop Tools Benchmarks']]],
  ['benefits_21',['Benefits',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md261',1,'Benefits'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md346',1,'Benefits'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md593',1,'Benefits'],['../md_REFACTORING__NOTES.html#autotoc_md1017',1,'Benefits'],['../md_README.html#autotoc_md942',1,'Expected Benefits'],['../md_README.html#autotoc_md949',1,'Expected Benefits'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1072',1,'Security Benefits']]],
  ['best_20practices_22',['Best Practices',['../md_IMPROVEMENTS__FINAL.html#autotoc_md510',1,'Best Practices'],['../md_skills_2build.html#autotoc_md1180',1,'Best Practices'],['../md_skills_2python__agent__expert.html#autotoc_md1280',1,'Best Practices'],['../md_skills_2reverse__engineering__expert.html#autotoc_md1285',1,'Best Practices'],['../md_skills_2x86__assembly__expert.html#autotoc_md1290',1,'Best Practices'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1496',1,'Best Practices'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md92',1,'Security &amp;amp; Best Practices']]],
  ['best_20practices_20applied_23',['Best Practices Applied',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md94',1,'']]],
  ['best_20practices_20for_20security_20audits_24',['Best Practices for Security Audits',['../md_skills_2claude__build.html#autotoc_md1240',1,'']]],
  ['beta_25',['4. Files API (Beta)',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md262',1,'']]],
  ['beta_20optional_20✅_26',['4. Files API (Beta, Optional) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md77',1,'']]],
  ['binary_20analysis_20performance_27',['Binary Analysis Performance',['../md_workshop__benchmarks.html#autotoc_md1347',1,'']]],
  ['blacklist_28',['Example 2: Restricted Sandbox with Blacklist',['../md_SANDBOX.html#autotoc_md1038',1,'']]],
  ['block_29',['Process each block',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['block_20absolute_20path_20fix_20implementation_20summary_30',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['block_20access_20denied_31',['Issue 1: READ Block Access Denied',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md173',1,'']]],
  ['block_20access_20denied_20✅_32',['Issue 1: READ Block Access Denied ✅',['../md_FIXES__SUMMARY.html#autotoc_md363',1,'']]],
  ['block_20as_20a_20single_20command_33',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['block_20contains_20a_20heredoc_34',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['block_20format_35',['Block Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md684',1,'Example 2: Code Block Format'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1480',1,'WRITE Block Format']]],
  ['block_20functionality_20user_20guide_36',['WRITE Block Functionality - User Guide',['../md_WRITE__BLOCKS__GUIDE.html',1,'']]],
  ['block_20in_20order_37',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['block_20parser_38',['Code Block Parser',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1495',1,'']]],
  ['block_20sanitization_39',['block sanitization',['../md_FIXES__SUMMARY.html#autotoc_md370',1,'READ block sanitization'],['../md_FIXES__SUMMARY.html#autotoc_md371',1,'WRITE block sanitization']]],
  ['block_20syntax_40',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['block_20syntax_20✅_41',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['blocked_20security_20maintained_20_3a_42',['✅ Still Blocked (Security Maintained):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md29',1,'']]],
  ['blocking_43',['Blocking',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md708',1,'Minor Issues (Non-Blocking)'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md813',1,'Minor Issues Identified (Non-Blocking)']]],
  ['blocks_44',['Blocks',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md690',1,'2. Shell Code Blocks'],['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md691',1,'3. AXE Native Blocks'],['../md_IMPLEMENTATION__SUMMARY.html',1,'Implementation Summary: GPT-5 Fix &amp; WRITE Blocks'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1486',1,'Integration with Other Blocks']]],
  ['blocks_45',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['blocks_20not_20executing_20high_46',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['bonus_20xp_20calculation_47',['✅ VALIDATED - Bonus XP Calculation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md761',1,'']]],
  ['bool_20lines_201410_201458_48',['5. &lt;span class=&quot;tt&quot;&gt;_needs_shell(cmd: str) -&amp;gt; bool&lt;/span&gt; (Lines 1410-1458)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1116',1,'']]],
  ['boot_5fflow_5freconstruction_49',['boot_flow_reconstruction',['../md_skills_2boot__flow__reconstruction.html',1,'']]],
  ['both_20present_3a_20combine_20with_20newline_20e_20g_20cat_20eof_50',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['boundaries_51',['Security Boundaries',['../md_SANDBOX.html#autotoc_md1040',1,'']]],
  ['break_20activities_52',['Break Activities',['../md_IMPROVEMENTS__FINAL.html#autotoc_md501',1,'']]],
  ['break_20system_53',['Break System',['../md_IMPROVEMENTS__FINAL.html#autotoc_md498',1,'']]],
  ['break_20system_20✅_54',['Phase 9: Break System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md552',1,'']]],
  ['break_20triggers_55',['Break Triggers',['../md_IMPROVEMENTS__FINAL.html#autotoc_md499',1,'']]],
  ['breakage_56',['Existing tests (verify no breakage)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1522',1,'']]],
  ['breakdown_57',['Module Breakdown',['../md_REFACTORING__NOTES.html#autotoc_md1016',1,'']]],
  ['breaking_20changes_58',['Breaking Changes',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1314',1,'']]],
  ['bubblewrap_20limitations_59',['Bubblewrap Limitations',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1080',1,'']]],
  ['bubblewrap_20not_20available_20falling_20back_20to_20whitelist_20mode_60',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['bubblewrap_20sandbox_20implementation_20summary_61',['Bubblewrap Sandbox Implementation - Summary',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['bubblewrap_20sandbox_20security_20model_62',['Bubblewrap Sandbox Security Model',['../md_SANDBOX.html',1,'']]],
  ['bug_20✅_63',['Bug 4: Double Execution Bug ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['bug_201_3a_20duplicate_20command_20execution_20❌_20→_20✅_64',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md310',1,'']]],
  ['bug_201_3a_20false_20task_20complete_20detection_20✅_65',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1320',1,'']]],
  ['bug_201_3a_20xml_20tag_20formats_20not_20supported_20✅_66',['Bug 1: XML Tag Formats Not Supported ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md196',1,'']]],
  ['bug_202_3a_20active_20agents_20counter_20✅_67',['Bug 2: Active Agents Counter ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1325',1,'']]],
  ['bug_202_3a_20spawned_20agents_20never_20get_20turns_20✅_68',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['bug_203_3a_20token_20limit_20errors_20413_20not_20handled_20✅_69',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['bug_204_3a_20double_20execution_20bug_20✅_70',['Bug 4: Double Execution Bug ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['bug_20fix_20summary_20multi_20agent_20collaboration_20issues_71',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_BUG__FIX__SUMMARY.html',1,'']]],
  ['bug_20fixed_20_3a_72',['✅ Now Allowed (Bug Fixed):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md31',1,'']]],
  ['bug_20fixes_73',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['bugs_74',['Fix Summary: AXE Session Termination Bugs',['../md_TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['bugs_20fixed_75',['Bugs Fixed',['../md_BUG__FIX__SUMMARY.html#autotoc_md195',1,'']]],
  ['build_76',['Build',['../md_skills_2claude__build.html#autotoc_md1254',1,'Pattern 1: Hardening Flags (Silent Build)'],['../md_skills_2claude__build.html#autotoc_md1229',1,'Phase 1: Initial Silent Build']]],
  ['build_20analysis_20expanded_77',['Build Analysis (EXPANDED!)',['../md_README.html#autotoc_md905',1,'']]],
  ['build_20analyzer_20dependency_20helper_20✅_78',['5. Build Analyzer Dependency Helper ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md427',1,'']]],
  ['build_20analyzer_20helper_79',['Build Analyzer Helper',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md447',1,'']]],
  ['build_20approach_80',['Default Build Approach',['../md_AGENTS.html#autotoc_md58',1,'']]],
  ['build_20guidelines_81',['Build Guidelines',['../md_AGENTS.html#autotoc_md57',1,'']]],
  ['build_20guidelines_20content_82',['2. BUILD GUIDELINES Content',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1145',1,'']]],
  ['build_20guidelines_20for_20all_20agents_83',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'']]],
  ['build_20instructions_84',['Build Instructions',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1340',1,'']]],
  ['build_20issue_20debugging_85',['2. Build Issue Debugging',['../md_README.html#autotoc_md954',1,'']]],
  ['build_20md_209_204kb_86',['skills/build.md (9.4KB)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1147',1,'']]],
  ['build_20patterns_87',['Common Security Build Patterns',['../md_skills_2claude__build.html#autotoc_md1253',1,'']]],
  ['build_20quietly_88',['Clean and build quietly',['../md_skills_2build.html#autotoc_md1195',1,'']]],
  ['build_20silently_89',['Build silently',['../md_skills_2build.html#autotoc_md1193',1,'Build silently'],['../md_skills_2claude__build.html#autotoc_md1231',1,'Build silently']]],
  ['build_20skill_90',['Claude Security-Focused Build Skill',['../md_skills_2claude__build.html',1,'']]],
  ['build_20system_20detection_91',['build_analyzer - Build System Detection',['../md_README.html#autotoc_md944',1,'']]],
  ['build_20systems_92',['Build Systems',['../md_skills_2claude__build.html#autotoc_md1211',1,'Core Build Systems'],['../md_README.html#autotoc_md947',1,'Detected Build Systems'],['../md_skills_2build.html#autotoc_md1169',1,'Supported Build Systems']]],
  ['build_20toolchain_93',['Build Toolchain',['../md__8collab__env.html#autotoc_md3',1,'']]],
  ['build_5fanalyzer_20build_20system_20detection_94',['build_analyzer - Build System Detection',['../md_README.html#autotoc_md944',1,'']]],
  ['building_95',['Building',['../md_README.html#autotoc_md918',1,'']]],
  ['building_20c_20project_96',['Example 1: GPT Building C++ Project',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1157',1,'']]],
  ['builds_97',['Builds',['../md_skills_2claude__build.html#autotoc_md1210',1,'Silent Security Builds'],['../md_skills_2build.html#autotoc_md1167',1,'Why Silent Builds?']]],
  ['builds_20feature_20implementation_20summary_98',['Silent Builds Feature - Implementation Summary',['../md_SILENT__BUILDS__IMPLEMENTATION.html',1,'']]],
  ['builds_20skill_99',['Silent Builds Skill',['../md_skills_2build.html',1,'']]],
  ['bullying_100',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['but_20not_20sandbox_20mode_101',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['by_20accident_102',['by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['by_20axe_20py_20responseprocessor_103',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['by_20default_104',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md1189',1,'']]],
  ['by_20design_105',['Limitations (By Design)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md814',1,'']]],
  ['by_20design_106',['What Sandbox Doesn&apos;t Protect (by design)',['../md_SANDBOX.html#autotoc_md1042',1,'']]],
  ['by_20line_20as_20before_107',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]]
];
