var searchData=
[
  ['c_0',['C',['../md_TODO.html#autotoc_md2206',1,'C'],['../md_TODO.html#autotoc_md2223',1,'C'],['../md_llm__prep_2codebase__overview.html#autotoc_md1967',1,'Doxygen Documentation (C/C++)']]],
  ['c_20best_20practices_1',['C/C++ Best Practices',['../md_llm__prep_2project__guidance.html#autotoc_md1973',1,'']]],
  ['c_20c_2',['Doxygen Documentation (C/C++)',['../md_llm__prep_2codebase__overview.html#autotoc_md1967',1,'']]],
  ['c_20c_20best_20practices_3',['C/C++ Best Practices',['../md_llm__prep_2project__guidance.html#autotoc_md1973',1,'']]],
  ['c_20c_20issues_4',['Cppcheck for C/C++ issues',['../md_skills_2claude__build.html#autotoc_md2124',1,'']]],
  ['c_20c_20security_20scanner_5',['Flawfinder (C/C++ Security Scanner)',['../md_skills_2claude__build.html#autotoc_md2116',1,'']]],
  ['c_20issues_6',['Cppcheck for C/C++ issues',['../md_skills_2claude__build.html#autotoc_md2124',1,'']]],
  ['c_20modernization_20expert_7',['C Modernization Expert',['../md_skills_2c__modernization__expert.html',1,'C Modernization Expert'],['../md_skills_2cpp__modernization__expert.html',1,'C++ Modernization Expert']]],
  ['c_20project_8',['Example 1: GPT Building C++ Project',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md733',1,'']]],
  ['c_20project_20with_20cmake_9',['Example 1: C++ Project with CMake',['../md_skills_2build.html#autotoc_md2082',1,'']]],
  ['c_20refactoring_20expert_10',['C++ Refactoring Expert',['../md_skills_2cpp__refactoring__expert.html',1,'']]],
  ['c_20security_20scanner_11',['Flawfinder (C/C++ Security Scanner)',['../md_skills_2claude__build.html#autotoc_md2116',1,'']]],
  ['c_20task_12',['Section 1 – Batch Mode (&lt;span class=&quot;tt&quot;&gt;-c &quot;@agent task&quot;&lt;/span&gt;)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1385',1,'']]],
  ['cache_20tracking_13',['Token Statistics with Cache Tracking',['../md_docs_2features_2anthropic-features.html#autotoc_md1148',1,'']]],
  ['caching_14',['1. Prompt Caching',['../md_docs_2features_2anthropic-features.html#autotoc_md1128',1,'']]],
  ['caching_2090_20token_20savings_20✅_15',['1. Prompt Caching (90% Token Savings) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md144',1,'']]],
  ['caching_20not_20working_16',['Caching not working',['../md_docs_2features_2anthropic-features.html#autotoc_md1155',1,'']]],
  ['calculation_17',['✅ VALIDATED - Bonus XP Calculation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md883',1,'']]],
  ['call_20graph_18',['Call Graph',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1123',1,'']]],
  ['call_20logic_20core_20agent_5fmanager_20py_19',['5. API Call Logic (&lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;)',['../md_docs_2codex-implementation.html#autotoc_md1015',1,'']]],
  ['call_20parser_20implementation_20',['Multi-Format Tool Call Parser Implementation',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'']]],
  ['call_20parser_20implementation_20summary_21',['XML Function Call Parser - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html',1,'']]],
  ['call_20parser_20quick_20reference_22',['Multi-Format Tool Call Parser - Quick Reference',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['call_20parsers_23',['Tool Call Parsers',['../md_docs_2features_2parsers.html',1,'']]],
  ['call_20support_24',['XML Function Call Support',['../md_docs_2features_2parsers.html#autotoc_md1220',1,'']]],
  ['call_20support_20quick_20reference_25',['XML Function Call Support - Quick Reference',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['calls_20extend_20parse_5faxe_5fnative_5fblocks_20response_20commented_20out_26',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md255',1,'']]],
  ['calls_20standard_20llm_20format_27',['5. XML Function Calls (Standard LLM Format)',['../md_docs_2features_2parsers.html#autotoc_md1219',1,'']]],
  ['can_20an_20agent_20trigger_20a_20session_20save_28',['Can an Agent Trigger a Session Save?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1689',1,'']]],
  ['capabilities_20matrix_29',['Model Capabilities Matrix',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md571',1,'']]],
  ['capacity_20fixed_20✓_30',['3. Wasted Capacity Fixed ✓',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md286',1,'']]],
  ['captured_20samples_20dumpexe_5fsamples_31',['dumpexe pre-captured samples (&lt;span class=&quot;tt&quot;&gt;dumpexe_samples/&lt;/span&gt;)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2189',1,'']]],
  ['card_32',['AXE Multiagent - Quick Reference Card',['../md_docs_2references_2quick-reference.html',1,'']]],
  ['case_33',['Model ID Case',['../md_docs_2features_2configuration.html#autotoc_md1189',1,'']]],
  ['case_20test_20suite_20test_5ftool_5frunner_5fedge_5fcases_20py_34',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md705',1,'']]],
  ['cases_35',['Use Cases',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1844',1,'']]],
  ['cases_20enabled_36',['Use Cases Enabled',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md136',1,'']]],
  ['cases_20fixed_37',['Edge Cases Fixed',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md695',1,'']]],
  ['cases_20for_20overrides_38',['Use Cases for Overrides',['../md_docs_2features_2configuration.html#autotoc_md1176',1,'']]],
  ['cases_20newly_20fixed_20_3a_39',['Edge Cases (newly fixed):',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md710',1,'']]],
  ['casting_20a_20vote_40',['Casting a Vote',['../md_docs_2xp__voting.html#autotoc_md1939',1,'']]],
  ['cat_20eof_41',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md328',1,'']]],
  ['catalog_42',['AXE Feature Catalog',['../md_TODO.html',1,'']]],
  ['categories_43',['Categories',['../md_docs_2global-workspace.html#autotoc_md1304',1,'Broadcast Categories'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1336',1,'Broadcast Categories'],['../md_docs_2workshop_2test-results.html#autotoc_md1887',1,'Test Categories']]],
  ['category_20message_44',['&lt;span class=&quot;tt&quot;&gt;broadcast(agent_alias, agent_level, category, message, ...)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1307',1,'']]],
  ['category_20none_20agent_20none_20requires_5fack_5fonly_20false_20limit_2050_45',['&lt;span class=&quot;tt&quot;&gt;get_broadcasts(since=None, category=None, agent=None, requires_ack_only=False, limit=50)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1309',1,'']]],
  ['cause_46',['Cause',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md120',1,'Root Cause'],['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md213',1,'Root Cause'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md249',1,'Root Cause'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md327',1,'Root Cause']]],
  ['cause_20analysis_47',['Root Cause Analysis',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md339',1,'']]],
  ['cd_20security_20checks_48',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md2137',1,'']]],
  ['chain_20of_20command_20–_20escalate_20properly_49',['3. Chain of Command – Escalate Properly',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md464',1,'']]],
  ['chain_20silent_50',['Pattern 2: Security Tool Chain (Silent)',['../md_skills_2claude__build.html#autotoc_md2146',1,'']]],
  ['challenges_20resolved_51',['Integration Challenges Resolved',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1088',1,'']]],
  ['changed_52',['Changed',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md209',1,'Files Changed'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md336',1,'Files Changed'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md597',1,'Files Changed'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md738',1,'Files Changed'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1541',1,'Files Changed'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md244',1,'Lines Changed']]],
  ['changelog_53',['Changelog',['../md_docs_2features_2write-blocks.html#autotoc_md1297',1,'']]],
  ['changes_54',['Changes',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md764',1,'Breaking Changes'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1552',1,'Breaking Changes'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md122',1,'Code Changes'],['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md216',1,'Code Changes'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md225',1,'Core Changes'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1544',1,'Key Changes'],['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md219',1,'Minimal Changes'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md194',1,'Summary of Changes']]],
  ['changes_20made_55',['Changes Made',['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md215',1,'Changes Made'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md275',1,'Changes Made'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md773',1,'Changes Made'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md778',1,'Changes Made'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1416',1,'Changes Made'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1611',1,'Changes Made'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1914',1,'Changes Made']]],
  ['changes_20summary_56',['Changes Summary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md956',1,'Appendix B: File Changes Summary'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md367',1,'Code Changes Summary']]],
  ['changes_3a_57',['Key Changes:',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md123',1,'']]],
  ['characteristics_58',['Performance Characteristics',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md840',1,'']]],
  ['chat_20commands_59',['Chat Commands',['../md_docs_2references_2quick-reference.html#autotoc_md1568',1,'']]],
  ['chat_20completions_60',['Key Differences: Responses API vs Chat Completions',['../md_docs_2codex-implementation.html#autotoc_md1016',1,'']]],
  ['chat_20style_20curl_20example_61',['Chat-style cURL Example',['../md_docs_2api-providers.html#autotoc_md88',1,'']]],
  ['check_62',['Tool Version Check',['../md__8collab__env.html#autotoc_md9',1,'']]],
  ['check_63',['Syntax check',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md408',1,'']]],
  ['check_20database_64',['Check Database',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1042',1,'']]],
  ['check_20for_20memory_20issues_20silent_65',['Quick check for memory issues (silent)',['../md_skills_2claude__build.html#autotoc_md2105',1,'']]],
  ['check_20for_20regressions_66',['Check for regressions',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md406',1,'']]],
  ['check_20if_20all_20trials_20fail_67',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md2163',1,'']]],
  ['check_20if_20features_20are_20active_68',['Check if Features are Active',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1041',1,'']]],
  ['check_20if_20the_20entire_20block_20contains_20a_20heredoc_69',['Check if the entire block contains a heredoc',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md257',1,'']]],
  ['check_20next_20promotion_70',['Check Next Promotion',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1504',1,'']]],
  ['check_20permissions_71',['Check permissions',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md402',1,'']]],
  ['check_5fand_5fcleanup_5fstale_5ffiles_20none_72',['&lt;span class=&quot;tt&quot;&gt;check_and_cleanup_stale_files() -&amp;gt; None&lt;/span&gt;',['../md_docs_2socket__interface.html#autotoc_md1668',1,'']]],
  ['checking_20resource_20usage_73',['Checking Resource Usage',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md496',1,'']]],
  ['checking_20suppression_20status_74',['Checking Suppression Status',['../md_docs_2subsumption__architecture.html#autotoc_md1713',1,'']]],
  ['checklist_75',['Checklist',['../md_AGENTS.html#autotoc_md42',1,'Code Review Checklist'],['../md_docs_2TESTING.html#autotoc_md1746',1,'Feature Validation Checklist']]],
  ['checkpoint_76',['1. Automatic Session Checkpoint',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1697',1,'']]],
  ['checks_77',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md2137',1,'']]],
  ['chisel_20analysis_78',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_docs_2workshop_2security-audit.html#autotoc_md1859',1,'']]],
  ['chisel_20symbolic_20execution_79',['Chisel Symbolic Execution',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md872',1,'✅ VALIDATED - Chisel (Symbolic Execution)'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1830',1,'&lt;b&gt;Chisel&lt;/b&gt; (Symbolic Execution)'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1812',1,'Chisel - Symbolic Execution']]],
  ['chisel_20symbolic_20execution_20benchmarks_80',['Chisel - Symbolic Execution Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1756',1,'']]],
  ['choices_81',['3. Document Your Choices',['../md_skills_2build.html#autotoc_md2074',1,'']]],
  ['ci_82',['Recommended Models for Testing/CI',['../md_docs_2ollama-guide.html#autotoc_md1437',1,'']]],
  ['ci_20cd_20security_20checks_83',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md2137',1,'']]],
  ['ci_20minimal_20resources_84',['Tiny Models (&amp;lt; 1GB) - Best for CI/Minimal Resources',['../md_docs_2ollama-guide.html#autotoc_md1438',1,'']]],
  ['claim_201_3a_20four_20analysis_20tools_20implemented_85',['Claim 1: Four Analysis Tools Implemented',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md871',1,'']]],
  ['claim_202_3a_20database_20integration_86',['Claim 2: Database Integration',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md877',1,'']]],
  ['claim_203_3a_20xp_20system_20integration_87',['Claim 3: XP System Integration',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md881',1,'']]],
  ['claim_204_3a_20configuration_20integration_88',['Claim 4: Configuration Integration',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md885',1,'']]],
  ['claim_205_3a_20documentation_89',['Claim 5: Documentation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md888',1,'']]],
  ['claim_206_3a_20test_20suite_90',['Claim 6: Test Suite',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md896',1,'']]],
  ['claimed_20performance_20metrics_91',['Claimed Performance Metrics',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md913',1,'']]],
  ['claims_20fulfillment_20summary_92',['Claims Fulfillment Summary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md939',1,'']]],
  ['claims_20vs_20actual_20implementation_93',['Part 1: PR Claims vs. Actual Implementation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md870',1,'']]],
  ['clang_20static_20analyzer_94',['Clang Static Analyzer',['../md_skills_2claude__build.html#autotoc_md2113',1,'']]],
  ['clang_20static_20analyzer_20quietly_95',['Run Clang static analyzer quietly',['../md_skills_2claude__build.html#autotoc_md2114',1,'']]],
  ['class_96',['GlobalWorkspace Class',['../md_docs_2xp__voting.html#autotoc_md1943',1,'']]],
  ['class_20api_97',['SkillsManager Class API',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md755',1,'']]],
  ['class_20constants_20lines_201121_201148_98',['1. Class Constants (Lines 1121-1148)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md688',1,'']]],
  ['class_20diagram_99',['Class Diagram',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1121',1,'']]],
  ['class_20diagrams_20pyreverse_100',['Python Class Diagrams (pyreverse)',['../md_llm__prep_2codebase__overview.html#autotoc_md1968',1,'']]],
  ['classes_101',['PR #2: Extract Large Classes',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md638',1,'']]],
  ['claude_102',['Claude',['../md_docs_2api-providers.html#autotoc_md65',1,'Anthropic (Claude)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md539',1,'Anthropic (Claude)'],['../md_README.html#autotoc_md2028',1,'Anthropic (Claude)']]],
  ['claude_20s_20favorite_103',['Claude s Favorite',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md607',1,'1. Bash XML Tags (Claude&apos;s Favorite)'],['../md_docs_2features_2parsers.html#autotoc_md1215',1,'1. Bash XML Tags (Claude&apos;s Favorite)']]],
  ['claude_20s_20natural_20format_104',['Example 1: Claude&apos;s Natural Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md601',1,'']]],
  ['claude_20security_20audit_105',['Example 2: Claude Security Audit',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md734',1,'']]],
  ['claude_20security_20focused_20build_20skill_106',['Claude Security-Focused Build Skill',['../md_skills_2claude__build.html',1,'']]],
  ['claude_20specific_20features_20in_20axe_107',['Anthropic Claude-Specific Features in AXE',['../md_docs_2features_2anthropic-features.html',1,'']]],
  ['claude_20specific_20optimizations_20implementation_20summary_108',['Anthropic Claude-Specific Optimizations - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['claude_5fbuild_20md_2011_202kb_109',['skills/claude_build.md (11.2KB)',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md724',1,'']]],
  ['clean_110',['6. &lt;b&gt;Dependencies &amp;amp; Git&lt;/b&gt; ✅ Clean',['../md_docs_2security.html#autotoc_md1607',1,'']]],
  ['clean_20and_20build_20quietly_111',['Clean and build quietly',['../md_skills_2build.html#autotoc_md2086',1,'']]],
  ['cleanup_20✅_112',['Phase 5: Cleanup ✅',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md626',1,'']]],
  ['cleanup_5ffiles_20none_113',['&lt;span class=&quot;tt&quot;&gt;cleanup_files() -&amp;gt; None&lt;/span&gt;',['../md_docs_2socket__interface.html#autotoc_md1669',1,'']]],
  ['clear_20workspaces_114',['Test 6: Clear Workspaces',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1368',1,'']]],
  ['cli_115',['CLI',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md520',1,'Standalone CLI'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1363',1,'Test 1: Multiple Workspaces from CLI']]],
  ['cli_20argument_20parsing_20axe_20py_116',['3. CLI Argument Parsing (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1917',1,'']]],
  ['cli_20arguments_117',['CLI Arguments',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1374',1,'']]],
  ['cli_20commands_20missing_118',['2. CLI Commands Missing',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md832',1,'']]],
  ['cloud_20local_119',['Mixed Cloud + Local',['../md_README.html#autotoc_md2022',1,'']]],
  ['cloud_20models_120',['With Cloud Models',['../md_README.html#autotoc_md2020',1,'']]],
  ['cmake_121',['CMake',['../md_skills_2build.html#autotoc_md2063',1,'CMake'],['../md_skills_2build.html#autotoc_md2082',1,'Example 1: C++ Project with CMake']]],
  ['cmd_3a_20str_20bool_20lines_201410_201458_122',['5. &lt;span class=&quot;tt&quot;&gt;_needs_shell(cmd: str) -&amp;gt; bool&lt;/span&gt; (Lines 1410-1458)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md692',1,'']]],
  ['cmd_3a_20str_20lines_201460_201542_123',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md693',1,'']]],
  ['cmd_3a_20str_20lines_201544_201629_124',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md694',1,'']]],
  ['cmd_3a_20str_20list_20str_20lines_201289_201408_125',['4. &lt;span class=&quot;tt&quot;&gt;_extract_commands_from_shell(cmd: str) -&amp;gt; List[str]&lt;/span&gt; (Lines 1289-1408)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md691',1,'']]],
  ['cmd_3a_20str_20str_20lines_201173_201287_126',['3. &lt;span class=&quot;tt&quot;&gt;_strip_heredoc_content(cmd: str) -&amp;gt; str&lt;/span&gt; (Lines 1173-1287)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md690',1,'']]],
  ['code_127',['Code',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md641',1,'For Existing Code'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md642',1,'For New Code'],['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1690',1,'Restarting AXE With Updated Code'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1633',1,'Total Lines of Code'],['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1119',1,'VS Code']]],
  ['code_20analysis_128',['Scenario 2: Code Analysis',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md671',1,'']]],
  ['code_20block_20format_129',['Example 2: Code Block Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md602',1,'']]],
  ['code_20block_20parser_130',['Code Block Parser',['../md_docs_2features_2write-blocks.html#autotoc_md1295',1,'']]],
  ['code_20blocks_131',['Code Blocks',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md608',1,'2. Shell Code Blocks'],['../md_docs_2features_2parsers.html#autotoc_md1216',1,'2. Shell Code Blocks']]],
  ['code_20changes_132',['Code Changes',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md122',1,'Code Changes'],['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md216',1,'Code Changes']]],
  ['code_20changes_20summary_133',['Code Changes Summary',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md367',1,'']]],
  ['code_20comments_20coverage_134',['Code Comments Coverage',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md700',1,'']]],
  ['code_20coverage_20report_135',['Code Coverage Report',['../md_docs_2workshop_2test-results.html#autotoc_md1895',1,'']]],
  ['code_20examples_136',['Quick Code Examples',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1500',1,'']]],
  ['code_20flow_137',['Code Flow',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md340',1,'']]],
  ['code_20integration_20axe_20py_138',['1. Code Integration (axe.py)',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1346',1,'']]],
  ['code_20minifier_20implementation_20summary_139',['Source Code Minifier Implementation Summary',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['code_20quality_140',['Code Quality',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md377',1,'✅ Code Quality'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md148',1,'Code Quality'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md291',1,'Code Quality'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md591',1,'Code Quality'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md781',1,'Code Quality']]],
  ['code_20quality_209_2010_141',['🏆 Code Quality (9/10)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md824',1,'']]],
  ['code_20quality_20analysis_142',['Part 5: Code Quality Analysis',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md915',1,'']]],
  ['code_20review_143',['Code Review',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md152',1,'']]],
  ['code_20review_20addressed_144',['Code Review Addressed',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md714',1,'']]],
  ['code_20review_20checklist_145',['Code Review Checklist',['../md_AGENTS.html#autotoc_md42',1,'']]],
  ['code_20review_20issues_20addressed_146',['Code Review Issues Addressed',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md592',1,'Code Review Issues Addressed'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1627',1,'Code Review Issues Addressed']]],
  ['code_20snippet_20analysis_147',['Code Snippet Analysis',['../md_docs_2workshop_2benchmarks.html#autotoc_md1760',1,'']]],
  ['code_20statistics_148',['Code Statistics',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1104',1,'Code Statistics'],['../md_llm__prep_2codebase__overview.html#autotoc_md1966',1,'Code Statistics']]],
  ['code_20structure_20excellent_149',['Code Structure - EXCELLENT',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md916',1,'']]],
  ['codebase_20overview_20—_202026_2003_2017_150',['LLM-Ready Codebase Overview — 2026-03-17',['../md_llm__prep_2codebase__overview.html',1,'']]],
  ['coder_3a1_205b_151',['Supervisor response (qwen2.5-coder:1.5b)',['../md_docs_2SRI__AGENT__DISCUSSION.html#autotoc_md1676',1,'']]],
  ['codex_20implementation_20guide_152',['GPT-5.2 Codex Implementation Guide',['../md_docs_2codex-implementation.html',1,'']]],
  ['coding_20conventions_153',['Coding Conventions',['../md_AGENTS.html#autotoc_md26',1,'']]],
  ['cognitive_20architecture_154',['Cognitive Architecture',['../md_README.html#autotoc_md1995',1,'🧠 Built-in Cognitive Architecture'],['../md_TODO.html#autotoc_md2241',1,'🧠 Cognitive Architecture'],['../md_README.html#autotoc_md2045',1,'Cognitive Architecture']]],
  ['cognitive_20architecture_20consolidation_20summary_155',['Cognitive Architecture Consolidation Summary',['../md_docs_2CONSOLIDATION__SUMMARY.html',1,'']]],
  ['cognitive_20architecture_20features_20working_156',['3. Cognitive Architecture Features Working',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1518',1,'']]],
  ['cognitive_20architecture_20in_20axe_20runtime_157',['Integration Complete: Cognitive Architecture in AXE Runtime',['../md_docs_2INTEGRATION__COMPLETE.html',1,'']]],
  ['cognitive_20architecture_20in_20axe_20user_20guide_158',['Cognitive Architecture in AXE - User Guide',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html',1,'']]],
  ['cognitive_20architecture_20papers_159',['Cognitive Architecture Papers',['../md_TODO.html#autotoc_md2251',1,'']]],
  ['cognitive_20architecture_20tokens_160',['Cognitive Architecture Tokens',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1030',1,'']]],
  ['cognitive_20architecture_20working_20with_20ollama_161',['PROOF: AXE Cognitive Architecture Working with Ollama',['../md_docs_2PROOF__OLLAMA__DEMO.html',1,'']]],
  ['cognitive_20features_20in_20axe_20sessions_162',['Using Cognitive Features in AXE Sessions',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1028',1,'']]],
  ['collab_163',['Section 2 – Collaborative Session (&lt;span class=&quot;tt&quot;&gt;--collab&lt;/span&gt;)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1387',1,'']]],
  ['collab_20inside_20interactive_20mode_164',['Section 8 – &lt;span class=&quot;tt&quot;&gt;/collab&lt;/span&gt; Inside Interactive Mode',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1399',1,'']]],
  ['collab_20mode_165',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md183',1,'']]],
  ['collab_20mode_20✅_166',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md304',1,'']]],
  ['collaboration_167',['Collaboration',['../md_README.html#autotoc_md1994',1,'🤝 Strong Multi-Agent Collaboration'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md737',1,'Example 3: Multi-Agent Collaboration'],['../md_skills_2build.html#autotoc_md2091',1,'Example 4: Multi-Agent Collaboration'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md574',1,'Multi-Agent Collaboration']]],
  ['collaboration_20—_20supervisor_20feedback_20loop_168',['1. Collaboration — Supervisor Feedback Loop',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md982',1,'']]],
  ['collaboration_20features_20⚠️_20medium_169',['5. &lt;b&gt;Collaboration Features&lt;/b&gt; ⚠️ Medium',['../md_docs_2security.html#autotoc_md1606',1,'']]],
  ['collaboration_20files_170',['Related Collaboration Files',['../md__8collab__shared.html#autotoc_md13',1,'']]],
  ['collaboration_20issues_171',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html',1,'']]],
  ['collaboration_20mode_172',['Collaboration Mode',['../md_README.html#autotoc_md2019',1,'']]],
  ['collaboration_20session_173',['Starting a Collaboration Session',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1029',1,'']]],
  ['collaborations_174',['Integration with Collaborations',['../md_skills_2build.html#autotoc_md2070',1,'']]],
  ['collaborative_20mode_175',['Collaborative Mode',['../md_README.html#autotoc_md2015',1,'']]],
  ['collaborative_20mode_20tool_20syntax_20fix_20summary_176',['Collaborative Mode Tool Syntax Fix - Summary',['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html',1,'']]],
  ['collaborative_20session_20collab_177',['Section 2 – Collaborative Session (&lt;span class=&quot;tt&quot;&gt;--collab&lt;/span&gt;)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1387',1,'']]],
  ['collaborative_20session_20notes_178',['Collaborative Session Notes',['../md__8collab__shared.html',1,'']]],
  ['collaborative_20session_20support_20axe_20py_179',['4. Collaborative Session Support (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1918',1,'']]],
  ['collaborative_20session_20with_20new_20features_180',['Starting a Collaborative Session with New Features',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md494',1,'']]],
  ['collaborative_20sessions_181',['Integration with Collaborative Sessions',['../md_docs_2global-workspace.html#autotoc_md1315',1,'']]],
  ['collaborativesession_182',['4. &lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt; (CollaborativeSession)',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md279',1,'']]],
  ['com_20disassembly_20limitation_20known_20bug_183',['⚠️ COM disassembly limitation (known bug)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2191',1,'']]],
  ['combine_20multiple_20security_20tools_20quietly_184',['5. Combine Multiple Security Tools Quietly',['../md_skills_2claude__build.html#autotoc_md2138',1,'']]],
  ['combine_20multiple_20silent_20flags_185',['4. Combine Multiple Silent Flags',['../md_skills_2build.html#autotoc_md2075',1,'']]],
  ['combine_20with_20newline_20e_20g_20cat_20eof_186',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md328',1,'']]],
  ['coming_20soon_187',['Coming Soon',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1241',1,'']]],
  ['comma_20separated_188',['Test 5: Set Multiple Workspaces (Comma-Separated)',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1367',1,'']]],
  ['command_189',['Validate Command',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1503',1,'']]],
  ['command_190',['If so, treat the whole block as a single command',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md258',1,'']]],
  ['command_20–_20escalate_20properly_191',['3. Chain of Command – Escalate Properly',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md464',1,'']]],
  ['command_20authorization_20matrix_192',['Command Authorization Matrix',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1499',1,'']]],
  ['command_20axe_20py_193',['5. New &lt;span class=&quot;tt&quot;&gt;/workspace&lt;/span&gt; Command (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1919',1,'']]],
  ['command_20execution_20⚠️_20medium_194',['2. &lt;b&gt;Command Execution&lt;/b&gt; ⚠️ Medium',['../md_docs_2security.html#autotoc_md1603',1,'']]],
  ['command_20execution_20❌_20→_20✅_195',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md247',1,'']]],
  ['command_20fails_196',['Command Fails?',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md811',1,'']]],
  ['command_20format_197',['Command Format',['../md_docs_2socket__interface.html#autotoc_md1642',1,'']]],
  ['command_20generation_198',['Bubblewrap Command Generation',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1927',1,'']]],
  ['command_20injection_20in_20hammer_20module_199',['Issue #1: Potential Command Injection in Hammer Module',['../md_docs_2workshop_2security-audit.html#autotoc_md1858',1,'']]],
  ['command_20line_200',['Command Line',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1921',1,'']]],
  ['command_20line_20option_201',['Command Line Option',['../md_docs_2features_2github-agent-integration.html#autotoc_md1201',1,'']]],
  ['command_20line_20options_202',['Command-Line Options',['../md_README.html#autotoc_md2006',1,'']]],
  ['command_20line_20requires_20graphviz_203',['Command Line (Requires GraphViz)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1118',1,'']]],
  ['command_20lookup_204',['Quick Command Lookup',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1591',1,'']]],
  ['command_20primitive_205',['3. &lt;span class=&quot;tt&quot;&gt;restart&lt;/span&gt; Slash Command / Primitive',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1699',1,'']]],
  ['command_20reference_206',['dumpexe command reference',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2190',1,'']]],
  ['command_20test_207',['Bwrap Command Test',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1427',1,'']]],
  ['command_3a_208',['Command:',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md349',1,'']]],
  ['commands_209',['Commands',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md475',1,'Agent Session Commands'],['../md_README.html#autotoc_md2010',1,'Basic Commands'],['../md_docs_2references_2quick-reference.html#autotoc_md1568',1,'Chat Commands'],['../md_docs_2references_2quick-reference.html#autotoc_md1567',1,'Commands'],['../md_README.html#autotoc_md2009',1,'Commands'],['../md__8collab__env.html#autotoc_md8',1,'Documentation Commands'],['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1592',1,'Essential Commands'],['../md_docs_2features_2parsers.html#autotoc_md1225',1,'EXEC - Run Commands'],['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1593',1,'In-Session Commands'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1375',1,'Interactive Commands'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html',1,'Interactive Testing Results - Workspace Commands'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1816',1,'Management Commands'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md474',1,'Quick Reference Commands'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1397',1,'Section 7 – Interactive Slash Commands'],['../md_docs_2socket__interface.html#autotoc_md1641',1,'Sending Commands'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md432',1,'Setup Commands'],['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1519',1,'Verification Commands']]],
  ['commands_210',['Session Saving and Loading — &lt;span class=&quot;tt&quot;&gt;/session&lt;/span&gt; commands',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1687',1,'']]],
  ['commands_20added_211',['Commands Added',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md386',1,'']]],
  ['commands_20during_20sessions_212',['New Agent Commands (During Sessions)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md491',1,'']]],
  ['commands_20for_20agents_213',['Safe Commands for Agents',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md469',1,'']]],
  ['commands_20missing_214',['2. CLI Commands Missing',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md832',1,'']]],
  ['commands_20now_20working_215',['Commands Now Working',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md708',1,'']]],
  ['commands_20via_20socket_216',['Sending Commands via Socket',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1630',1,'']]],
  ['commands_20work_20in_20unrestricted_20mode_20but_20not_20sandbox_20mode_217',['Commands work in unrestricted mode but not sandbox mode',['../md_docs_2features_2sandbox.html#autotoc_md1272',1,'']]],
  ['comment_20none_218',['&lt;span class=&quot;tt&quot;&gt;acknowledge(broadcast_id, agent_alias, comment=None)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1308',1,'']]],
  ['commented_20out_219',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md255',1,'']]],
  ['comments_220',['Comments',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md344',1,'3. Inline Comments'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md699',1,'Documentation &amp;amp; Comments']]],
  ['comments_20coverage_221',['Code Comments Coverage',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md700',1,'']]],
  ['commit_20history_222',['Commit History',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1106',1,'']]],
  ['commits_223',['Commits',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1355',1,'']]],
  ['common_224',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md2159',1,'']]],
  ['common_20errors_225',['Common Errors',['../md_docs_2socket__interface.html#autotoc_md1653',1,'']]],
  ['common_20issues_226',['Common Issues',['../md_docs_2api-providers.html#autotoc_md115',1,'']]],
  ['common_20modernizations_227',['Common Modernizations',['../md_skills_2c__modernization__expert.html#autotoc_md2096',1,'']]],
  ['common_20pitfalls_228',['Common Pitfalls',['../md_skills_2build.html#autotoc_md2077',1,'']]],
  ['common_20refactors_229',['Common Refactors',['../md_skills_2cpp__refactoring__expert.html#autotoc_md2157',1,'']]],
  ['common_20scenarios_230',['Common Scenarios',['../md_docs_2references_2quick-reference.html#autotoc_md1581',1,'']]],
  ['common_20security_20build_20patterns_231',['Common Security Build Patterns',['../md_skills_2claude__build.html#autotoc_md2144',1,'']]],
  ['common_20tasks_232',['Common Tasks',['../md_skills_2python__agent__expert.html#autotoc_md2172',1,'']]],
  ['communication_233',['Communication',['../md_docs_2socket__interface.html#autotoc_md1649',1,'Local-Only Communication'],['../md_docs_2socket__interface.html',1,'Unix Socket Interface for Agent Communication']]],
  ['communication_20example_234',['Model Communication Example',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md575',1,'']]],
  ['communication_20protocol_235',['Communication Protocol',['../md_docs_2socket__interface.html#autotoc_md1640',1,'']]],
  ['communication_20tokens_236',['Agent Communication Tokens',['../md_MISSION.html#autotoc_md1979',1,'']]],
  ['comparative_20analysis_237',['Comparative Analysis',['../md_docs_2workshop_2benchmarks.html#autotoc_md1768',1,'']]],
  ['compared_20to_20whitelist_20mode_238',['Compared to Whitelist Mode',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md660',1,'']]],
  ['comparison_239',['Comparison',['../md_docs_2workshop_2test-results.html#autotoc_md1901',1,'Historical Comparison'],['../md_docs_2ollama-guide.html#autotoc_md1448',1,'Model Comparison'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1769',1,'Tool Efficiency Comparison']]],
  ['comparison_20of_20fixes_240',['Before/After Comparison of Fixes',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['compatibility_241',['Compatibility',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md831',1,'1. Test Compatibility'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1799',1,'AXE Framework Compatibility'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md135',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md156',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md208',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md241',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md290',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md321',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md598',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md629',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md662',1,'Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md812',1,'Backward Compatibility'],['../md_docs_2features_2anthropic-features.html#autotoc_md1150',1,'Backward Compatibility'],['../md_docs_2features_2configuration.html#autotoc_md1178',1,'Backward Compatibility'],['../md_docs_2features_2parsers.html#autotoc_md1233',1,'Backward Compatibility'],['../md_docs_2features_2sandbox.html#autotoc_md1254',1,'Backward Compatibility'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1929',1,'Backward Compatibility'],['../md_docs_2codex-implementation.html#autotoc_md1020',1,'Backwards Compatibility'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md268',1,'Example 3: Backward Compatibility'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md157',1,'Guaranteed Compatibility']]],
  ['compatibility_20matrix_242',['Compatibility Matrix',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1785',1,'']]],
  ['compatible_20api_243',['Usage - OpenAI-Compatible API',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md548',1,'']]],
  ['compile_20with_20addresssanitizer_20for_20runtime_20detection_244',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md2128',1,'']]],
  ['compile_20with_20asan_20and_20run_20tests_20silently_245',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md2111',1,'']]],
  ['complete_246',['COMPLETE',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md904',1,'Configuration Integration - COMPLETE'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md902',1,'Database Integration - COMPLETE'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md142',1,'Implementation Status: ✅ COMPLETE'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md905',1,'Module Structure - COMPLETE'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md903',1,'XP System Integration - COMPLETE']]],
  ['complete_247',['Setup Complete',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1102',1,'']]],
  ['complete_20✅_248',['Complete ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html',1,'AXE Enhancement Implementation - Complete ✅'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1325',1,'Implementation Complete ✅']]],
  ['complete_20axe_20integration_249',['✅ Complete AXE Integration',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md820',1,'']]],
  ['complete_20detection_20✅_250',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md770',1,'']]],
  ['complete_3a_20cognitive_20architecture_20in_20axe_20runtime_251',['Integration Complete: Cognitive Architecture in AXE Runtime',['../md_docs_2INTEGRATION__COMPLETE.html',1,'']]],
  ['completed_252',['Immediate Actions (Completed)',['../md_docs_2workshop_2security-audit.html#autotoc_md1879',1,'']]],
  ['completions_253',['Key Differences: Responses API vs Chat Completions',['../md_docs_2codex-implementation.html#autotoc_md1016',1,'']]],
  ['complexity_254',['Example 3: Escalation Due to Complexity',['../md_docs_2conflict__resolution__examples.html#autotoc_md1066',1,'']]],
  ['compliance_255',['Compliance',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md745',1,'2. AGENTS.md Standard Compliance'],['../md_docs_2workshop_2security-audit.html#autotoc_md1877',1,'Security Standards Compliance']]],
  ['compliance_20assessment_256',['Compliance Assessment',['../md_docs_2workshop_2security-audit.html#autotoc_md1876',1,'']]],
  ['component_20overview_257',['Component Overview',['../md_docs_2features_2sandbox.html#autotoc_md1265',1,'']]],
  ['components_258',['Components',['../md_AGENTS.html#autotoc_md38',1,'Core Components'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1095',1,'Core Components']]],
  ['comprehensive_259',['Documentation - COMPREHENSIVE',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md919',1,'']]],
  ['comprehensive_20coverage_260',['Comprehensive Coverage',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md160',1,'']]],
  ['comprehensive_20documentation_261',['✅ Comprehensive Documentation',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md821',1,'']]],
  ['comprehensive_20documentation_20✅_262',['6. Comprehensive Documentation ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md365',1,'']]],
  ['comprehensive_20integration_20demo_263',['Comprehensive Integration Demo',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1100',1,'']]],
  ['comprehensive_20security_20scan_20with_20minimal_20noise_264',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md2139',1,'']]],
  ['comprehensive_20test_20suite_265',['4. Comprehensive Test Suite',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md345',1,'']]],
  ['comprehensive_20test_20suite_20tests_20test_5fskills_5fmanager_20py_266',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md752',1,'']]],
  ['comprehensive_20testing_267',['4. Comprehensive Testing',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md725',1,'']]],
  ['comprehensive_20validation_268',['3. Comprehensive Validation',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1547',1,'']]],
  ['comprehensive_20validation_20report_269',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html',1,'']]],
  ['conclusion_270',['Conclusion',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md139',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md172',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md220',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md272',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md355',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md394',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md409',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md683',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md740',1,'Conclusion'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md798',1,'Conclusion'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1113',1,'Conclusion'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1360',1,'Conclusion'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1379',1,'Conclusion'],['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1459',1,'Conclusion'],['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1521',1,'Conclusion'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1562',1,'Conclusion'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1808',1,'Conclusion'],['../md_docs_2workshop_2security-audit.html#autotoc_md1881',1,'Conclusion'],['../md_docs_2workshop_2test-results.html#autotoc_md1911',1,'Conclusion'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md938',1,'Part 10: Validation Conclusion']]],
  ['concrete_20improvement_20suggestions_271',['Concrete Improvement Suggestions',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md980',1,'']]],
  ['condition_20in_20database_20operations_272',['Issue #4: Race Condition in Database Operations',['../md_docs_2workshop_2security-audit.html#autotoc_md1862',1,'']]],
  ['config_20✅_20low_273',['3. &lt;b&gt;YAML Config&lt;/b&gt; ✅ Low',['../md_docs_2security.html#autotoc_md1604',1,'']]],
  ['config_20project_5fdir_3a_20str_20lines_201150_201171_274',['2. &lt;span class=&quot;tt&quot;&gt;__init__(config: Config, project_dir: str)&lt;/span&gt; (Lines 1150-1171)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md689',1,'']]],
  ['config_3a_20config_20project_5fdir_3a_20str_20lines_201150_201171_275',['2. &lt;span class=&quot;tt&quot;&gt;__init__(config: Config, project_dir: str)&lt;/span&gt; (Lines 1150-1171)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md689',1,'']]],
  ['configuration_276',['Configuration',['../md_docs_2features_2configuration.html#autotoc_md1166',1,'3. axe.yaml (User Configuration)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md540',1,'Configuration'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md546',1,'Configuration'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md553',1,'Configuration'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md559',1,'Configuration'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md566',1,'Configuration'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md849',1,'Configuration'],['../md_docs_2features_2anthropic-features.html#autotoc_md1129',1,'Configuration'],['../md_docs_2features_2anthropic-features.html#autotoc_md1135',1,'Configuration'],['../md_docs_2features_2anthropic-features.html#autotoc_md1140',1,'Configuration'],['../md_docs_2features_2anthropic-features.html#autotoc_md1145',1,'Configuration'],['../md_docs_2features_2github-agent-integration.html#autotoc_md1200',1,'Configuration'],['../md_docs_2features_2sandbox.html#autotoc_md1252',1,'Configuration'],['../md_docs_2ollama-guide.html#autotoc_md1442',1,'Configuration'],['../md_docs_2privilege__mapping.html#autotoc_md1491',1,'Configuration'],['../md_docs_2privilege__mapping__quickref.html#autotoc_md1505',1,'Configuration'],['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1535',1,'Configuration'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1819',1,'Configuration'],['../md_README.html#autotoc_md2034',1,'Configuration'],['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1454',1,'Test Configuration']]],
  ['configuration_277',['dosbox-staging trace configuration',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2194',1,'']]],
  ['configuration_20architecture_278',['Configuration Architecture',['../md_docs_2features_2configuration.html',1,'']]],
  ['configuration_20axe_20yaml_279',['3. Agent Configuration (&lt;span class=&quot;tt&quot;&gt;axe.yaml&lt;/span&gt;)',['../md_docs_2codex-implementation.html#autotoc_md1013',1,'']]],
  ['configuration_20example_280',['Configuration Example',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md657',1,'']]],
  ['configuration_20file_281',['Configuration file',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md792',1,'']]],
  ['configuration_20files_282',['Configuration Files',['../md_AGENTS.html#autotoc_md39',1,'']]],
  ['configuration_20files_20location_283',['Configuration Files Location',['../md_docs_2features_2configuration.html#autotoc_md1185',1,'']]],
  ['configuration_20integration_284',['Claim 4: Configuration Integration',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md885',1,'']]],
  ['configuration_20integration_20complete_285',['Configuration Integration - COMPLETE',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md904',1,'']]],
  ['configuration_20loading_20process_286',['Configuration Loading Process',['../md_docs_2features_2configuration.html#autotoc_md1167',1,'']]],
  ['configuration_20options_287',['Configuration Options',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md524',1,'']]],
  ['configuration_20providers_20yaml_288',['2. Provider Configuration (&lt;span class=&quot;tt&quot;&gt;providers.yaml&lt;/span&gt;)',['../md_docs_2codex-implementation.html#autotoc_md1012',1,'']]],
  ['configuration_20refactor_20implementation_20summary_289',['Configuration Refactor - Implementation Summary',['../md_docs_2REFACTOR__SUMMARY.html',1,'']]],
  ['configuration_20reference_290',['Configuration Reference',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html',1,'AXE Multi-Agent System - Model Configuration Reference'],['../md_docs_2features_2anthropic-features.html#autotoc_md1149',1,'Configuration Reference']]],
  ['configuration_20structure_291',['✅ VALIDATED - Configuration Structure',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md886',1,'']]],
  ['configuration_20updates_292',['5. Configuration Updates',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md748',1,'']]],
  ['configure_293',['Autoconf/Configure',['../md_skills_2build.html#autotoc_md2062',1,'']]],
  ['configure_20with_20quiet_20flags_294',['Configure with quiet flags',['../md_skills_2build.html#autotoc_md2083',1,'']]],
  ['configure_20with_20security_20flags_295',['Configure with security flags',['../md_skills_2claude__build.html#autotoc_md2121',1,'']]],
  ['configured_20reasoning_20variants_296',['Pre-configured Reasoning Variants',['../md_docs_2codex-implementation.html#autotoc_md1008',1,'']]],
  ['confirmation_297',['Security Confirmation',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1429',1,'']]],
  ['conflict_298',['Example 2: Refactoring Approach Conflict',['../md_docs_2conflict__resolution__examples.html#autotoc_md1061',1,'']]],
  ['conflict_20detection_299',['Conflict Detection',['../md_docs_2conflict__resolution__examples.html#autotoc_md1055',1,'']]],
  ['conflict_20detection_20arbitration_20✅_300',['Test 4: Conflict Detection &amp;amp; Arbitration ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1467',1,'']]],
  ['conflict_20detection_20arbitration_20minsky_201986_301',['Conflict Detection Arbitration Minsky 1986',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1352',1,'Conflict Detection &amp;amp; Arbitration (Minsky, 1986)'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1087',1,'PR #56: Conflict Detection &amp;amp; Arbitration (Minsky 1986)']]],
  ['conflict_20flagging_302',['Conflict Flagging',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1035',1,'5. Conflict Flagging'],['../md_docs_2conflict__resolution__examples.html#autotoc_md1064',1,'Manual Conflict Flagging']]],
  ['conflict_20resolution_20examples_303',['Conflict Resolution Examples',['../md_docs_2conflict__resolution__examples.html',1,'']]],
  ['confused_304',['&quot;Agent stuck or confused&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1583',1,'']]],
  ['confused_20about_20read_20write_20block_20syntax_305',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['confused_20about_20read_20write_20block_20syntax_20✅_306',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md306',1,'']]],
  ['connection_307',['Test Connection',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md537',1,'']]],
  ['considerations_308',['Considerations',['../md_docs_2socket__interface.html#autotoc_md1656',1,'Design Considerations'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md242',1,'Future Considerations'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1825',1,'Safety Considerations'],['../md_AGENTS.html#autotoc_md43',1,'Security Considerations'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md163',1,'Security Considerations'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md295',1,'Security Considerations'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md354',1,'Security Considerations'],['../md_docs_2features_2github-agent-integration.html#autotoc_md1210',1,'Security Considerations'],['../md_docs_2socket__interface.html#autotoc_md1648',1,'Security Considerations']]],
  ['consolidated_309',['PRs Consolidated',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1084',1,'']]],
  ['consolidation_20summary_310',['Cognitive Architecture Consolidation Summary',['../md_docs_2CONSOLIDATION__SUMMARY.html',1,'']]],
  ['constants_311',['Constants',['../md_docs_2socket__interface.html#autotoc_md1671',1,'Constants'],['../md_docs_2subsumption__architecture.html#autotoc_md1725',1,'Constants']]],
  ['constants_20lines_201121_201148_312',['1. Class Constants (Lines 1121-1148)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md688',1,'']]],
  ['constants_20merge_313',['1. Constants Merge',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1089',1,'']]],
  ['constants_20py_314',['Constants: &lt;span class=&quot;tt&quot;&gt;core/constants.py&lt;/span&gt;',['../md_docs_2privilege__mapping.html#autotoc_md1479',1,'']]],
  ['constants_3a_20core_20constants_20py_315',['Constants: &lt;span class=&quot;tt&quot;&gt;core/constants.py&lt;/span&gt;',['../md_docs_2privilege__mapping.html#autotoc_md1479',1,'']]],
  ['contact_20issues_316',['Contact &amp;amp; Issues',['../md_README.html#autotoc_md2048',1,'']]],
  ['contact_20support_317',['Contact &amp;amp; Support',['../md_AGENTS.html#autotoc_md45',1,'']]],
  ['contains_20a_20heredoc_318',['Check if the entire block contains a heredoc',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md257',1,'']]],
  ['content_319',['2. BUILD GUIDELINES Content',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md721',1,'']]],
  ['contents_320',['Contents',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md961',1,'Archive Contents'],['../md_docs_2api-providers.html#autotoc_md63',1,'Table of Contents'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md412',1,'Table of Contents'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md533',1,'Table of Contents']]],
  ['context_321',['What Is SRI in the AXE Context?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1684',1,'']]],
  ['context_20files_322',['LLM Context Files',['../md_llm__prep_2codebase__overview.html#autotoc_md1970',1,'']]],
  ['context_5ftokens_323',['Key Naming Standard: &lt;span class=&quot;tt&quot;&gt;context_tokens&lt;/span&gt;',['../md_docs_2features_2configuration.html#autotoc_md1171',1,'']]],
  ['contributing_324',['Contributing',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1536',1,'🤝 Contributing'],['../md_AGENTS.html#autotoc_md40',1,'Contributing'],['../md_ARCHITECTURE.html#autotoc_md61',1,'Contributing'],['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1596',1,'Contributing'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1850',1,'Contributing'],['../md_MISSION.html#autotoc_md1985',1,'Contributing'],['../md_TODO.html#autotoc_md2248',1,'Contributing']]],
  ['contributing_20to_20archive_325',['Contributing to Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md968',1,'']]],
  ['control_326',['Control',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md653',1,'3. Filesystem Access Control'],['../md_docs_2features_2sandbox.html#autotoc_md1250',1,'3. Filesystem Access Control'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1033',1,'3. Suppression (Hierarchical Control)'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1034',1,'4. Release (Restore Control)'],['../md_docs_2features_2write-blocks.html#autotoc_md1288',1,'Directory Access Control']]],
  ['controller_327',['Subsumption Architecture Controller',['../md_docs_2subsumption__architecture.html',1,'']]],
  ['controls_20verified_328',['Resource Controls - VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md910',1,'']]],
  ['conventions_329',['Coding Conventions',['../md_AGENTS.html#autotoc_md26',1,'']]],
  ['cooperating_330',['&quot;Agents not cooperating&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1582',1,'']]],
  ['coordination_331',['Agent Coordination',['../md__8collab__shared.html#autotoc_md14',1,'']]],
  ['core_20agent_5fmanager_20py_332',['core agent_manager py',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md278',1,'3. &lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;'],['../md_docs_2codex-implementation.html#autotoc_md1015',1,'5. API Call Logic (&lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;)']]],
  ['core_20build_20systems_333',['Core Build Systems',['../md_skills_2claude__build.html#autotoc_md2102',1,'']]],
  ['core_20changes_334',['Core Changes',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md225',1,'']]],
  ['core_20components_335',['Core Components',['../md_AGENTS.html#autotoc_md38',1,'Core Components'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1095',1,'Core Components']]],
  ['core_20constants_20py_336',['Constants: &lt;span class=&quot;tt&quot;&gt;core/constants.py&lt;/span&gt;',['../md_docs_2privilege__mapping.html#autotoc_md1479',1,'']]],
  ['core_20dependencies_337',['Core Dependencies',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1775',1,'Core Dependencies'],['../md_docs_2workshop_2security-audit.html#autotoc_md1871',1,'Core Dependencies']]],
  ['core_20documentation_338',['Core Documentation',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1524',1,'']]],
  ['core_20functionality_339',['Core Functionality',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md515',1,'']]],
  ['core_20implementation_20axe_20py_340',['1. Core Implementation (axe.py)',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1612',1,'']]],
  ['core_20module_3a_20core_20privilege_5fmapping_20py_341',['Core Module: &lt;span class=&quot;tt&quot;&gt;core/privilege_mapping.py&lt;/span&gt;',['../md_docs_2privilege__mapping.html#autotoc_md1478',1,'']]],
  ['core_20principles_342',['Core Principles',['../md_MISSION.html#autotoc_md1978',1,'Core Principles'],['../md_skills_2c__modernization__expert.html#autotoc_md2095',1,'Core Principles'],['../md_skills_2cpp__modernization__expert.html#autotoc_md2152',1,'Core Principles'],['../md_skills_2cpp__refactoring__expert.html#autotoc_md2156',1,'Core Principles'],['../md_skills_2ida__pro__analysis__patterns.html#autotoc_md2166',1,'Core Principles'],['../md_skills_2python__agent__expert.html#autotoc_md2170',1,'Core Principles'],['../md_skills_2reverse__engineering__expert.html#autotoc_md2174',1,'Core Principles'],['../md_skills_2x86__assembly__expert.html#autotoc_md2178',1,'Core Principles']]],
  ['core_20privilege_5fmapping_20py_343',['Core Module: &lt;span class=&quot;tt&quot;&gt;core/privilege_mapping.py&lt;/span&gt;',['../md_docs_2privilege__mapping.html#autotoc_md1478',1,'']]],
  ['core_20safety_20features_344',['Core Safety Features',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md414',1,'']]],
  ['core_20sandbox_20fix_20core_20sandbox_20py_345',['1. Core Sandbox Fix (&lt;span class=&quot;tt&quot;&gt;core/sandbox.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1915',1,'']]],
  ['core_20sandbox_20py_346',['1. Core Sandbox Fix (&lt;span class=&quot;tt&quot;&gt;core/sandbox.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1915',1,'']]],
  ['core_20skills_20manager_20core_20skills_5fmanager_20py_347',['1. Core Skills Manager (&lt;span class=&quot;tt&quot;&gt;core/skills_manager.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md744',1,'']]],
  ['core_20skills_5fmanager_20py_348',['1. Core Skills Manager (&lt;span class=&quot;tt&quot;&gt;core/skills_manager.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md744',1,'']]],
  ['core_20tool_5frunner_20py_349',['2. Tool Runner Integration (&lt;span class=&quot;tt&quot;&gt;core/tool_runner.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1916',1,'']]],
  ['core_20tools_350',['Core Tools',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1829',1,'']]],
  ['count_351',['Line Count',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md633',1,'']]],
  ['counter_20✅_352',['Bug 2: Active Agents Counter ✅',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md775',1,'']]],
  ['counting_353',['3. Token Counting',['../md_docs_2features_2anthropic-features.html#autotoc_md1139',1,'']]],
  ['counting_20fails_354',['Token counting fails',['../md_docs_2features_2anthropic-features.html#autotoc_md1157',1,'']]],
  ['counting_20precise_20estimates_20✅_355',['3. Token Counting (Precise Estimates) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md146',1,'']]],
  ['coverage_356',['Coverage',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md728',1,'Agent Coverage'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md700',1,'Code Comments Coverage'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md160',1,'Comprehensive Coverage'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1764',1,'Enumeration Coverage'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md124',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md151',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md261',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md595',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md656',1,'Test Coverage'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md703',1,'Test Coverage']]],
  ['coverage_20analysis_357',['Part 6: Test Coverage Analysis',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md921',1,'']]],
  ['coverage_20report_358',['Code Coverage Report',['../md_docs_2workshop_2test-results.html#autotoc_md1895',1,'']]],
  ['cppcheck_20for_20c_20c_20issues_359',['Cppcheck for C/C++ issues',['../md_skills_2claude__build.html#autotoc_md2124',1,'']]],
  ['cppcheck_20static_20analysis_360',['Cppcheck (Static Analysis)',['../md_skills_2claude__build.html#autotoc_md2107',1,'']]],
  ['cppcheck_20with_20full_20details_361',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md2127',1,'']]],
  ['cpu_20usage_362',['CPU Usage',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1793',1,'']]],
  ['create_20directory_20structure_20✅_363',['Phase 1: Create Directory Structure ✅',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md622',1,'']]],
  ['create_20parent_20dirs_20if_20needed_364',['Create parent dirs if needed',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md403',1,'']]],
  ['create_20write_20files_365',['WRITE - Create/Write Files',['../md_docs_2features_2parsers.html#autotoc_md1223',1,'']]],
  ['created_366',['Created',['../md_docs_2conflict__resolution__examples.html#autotoc_md1056',1,'Arbitration Created'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md922',1,'Custom Validation Tests Created'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md509',1,'Files Created'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md648',1,'Files Created'],['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1520',1,'Files Created'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1632',1,'Files Created'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1542',1,'New Files Created'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md311',1,'Unit Tests Created']]],
  ['created_205_367',['Files Created (5)',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md149',1,'']]],
  ['created_20modified_368',['Files Created/Modified',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1326',1,'']]],
  ['created_20skills_20directory_20and_20files_369',['3. Created Skills Directory and Files',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md722',1,'']]],
  ['creating_20a_20file_370',['Example 2: Creating a File',['../md_docs_2features_2parsers.html#autotoc_md1231',1,'']]],
  ['creating_20new_20skills_371',['Creating New Skills',['../md_AGENTS.html#autotoc_md32',1,'']]],
  ['credits_372',['Credits',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md2256',1,'Attributions &amp;amp; Credits'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md503',1,'Credits']]],
  ['credits_20error_373',['No Credits Error',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md580',1,'']]],
  ['criteria_374',['Criteria',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md527',1,'Acceptance Criteria'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1626',1,'Acceptance Criteria'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md171',1,'Success Criteria'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md796',1,'Success Criteria']]],
  ['criteria_20✓_375',['Success Criteria ✓',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md759',1,'']]],
  ['criteria_20all_20met_376',['Success Criteria (All Met)',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md784',1,'']]],
  ['criteria_20met_377',['Criteria Met',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md240',1,'Success Criteria Met'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md739',1,'Success Criteria Met']]],
  ['criteria_20status_378',['Acceptance Criteria Status',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1107',1,'']]],
  ['critical_379',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md397',1,'']]],
  ['critical_20issues_20found_20re_20run_20with_20full_20details_3a_380',['If critical issues found, re-run with full details:',['../md_skills_2claude__build.html#autotoc_md2109',1,'']]],
  ['cross_20tool_20interactions_381',['Cross-Tool Interactions',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1800',1,'']]],
  ['curl_20example_382',['cURL Example',['../md_docs_2api-providers.html#autotoc_md88',1,'Chat-style cURL Example'],['../md_docs_2api-providers.html#autotoc_md69',1,'cURL Example'],['../md_docs_2api-providers.html#autotoc_md77',1,'cURL Example'],['../md_docs_2api-providers.html#autotoc_md87',1,'cURL Example'],['../md_docs_2api-providers.html#autotoc_md96',1,'cURL Example'],['../md_docs_2api-providers.html#autotoc_md105',1,'cURL Example']]],
  ['current_383',['v1.0 (Current)',['../md_docs_2features_2write-blocks.html#autotoc_md1298',1,'']]],
  ['current_20limitations_384',['Current Limitations',['../md_docs_2socket__interface.html#autotoc_md1655',1,'']]],
  ['current_20workspaces_385',['Test 2: Show Current Workspaces',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1364',1,'']]],
  ['curve_20hybrid_20linear_20exponential_386',['Progression Curve (Hybrid Linear/Exponential)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md456',1,'']]],
  ['custom_20validation_20suite_387',['Custom Validation Suite',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md836',1,'']]],
  ['custom_20validation_20tests_20created_388',['Custom Validation Tests Created',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md922',1,'']]],
  ['customizing_20privileges_389',['Customizing Privileges',['../md_docs_2privilege__mapping.html#autotoc_md1493',1,'']]]
];
