var searchData=
[
  ['l_0',['L',['../md_TODO.html#autotoc_md2210',1,'']]],
  ['languages_1',['Additional Languages',['../md__8collab__env.html#autotoc_md5',1,'']]],
  ['large_2',['Model Too Large?',['../md_docs_2ollama-guide.html#autotoc_md1445',1,'']]],
  ['large_20classes_3',['PR #2: Extract Large Classes',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md638',1,'']]],
  ['large_20models_2030gb_20best_20quality_4',['Large Models (&amp;gt; 30GB) - Best Quality',['../md_docs_2ollama-guide.html#autotoc_md1441',1,'']]],
  ['later_5',['&quot;Want to resume later&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1584',1,'']]],
  ['latest_20models_6',['Latest Models',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md541',1,'Latest Models'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md547',1,'Latest Models'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md554',1,'Latest Models'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md560',1,'Latest Models']]],
  ['layer_20assignment_7',['Layer Assignment',['../md_docs_2subsumption__architecture.html#autotoc_md1711',1,'']]],
  ['layer_20definitions_8',['Layer Definitions',['../md_docs_2subsumption__architecture.html#autotoc_md1708',1,'']]],
  ['leader_20deputy_20supervisor_20levels_2020_2029_9',['Team Leader / Deputy Supervisor (Levels 20-29)',['../md_docs_2privilege__mapping.html#autotoc_md1484',1,'']]],
  ['leader_20levels_2010_2019_10',['Senior Worker / Team Leader (Levels 10-19)',['../md_docs_2privilege__mapping.html#autotoc_md1483',1,'']]],
  ['learned_11',['Lessons Learned',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md643',1,'']]],
  ['legacy_20mode_12',['Scenario 4: Legacy Mode',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md673',1,'']]],
  ['lessons_20learned_13',['Lessons Learned',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md643',1,'']]],
  ['level_14',['Level',['../md_docs_2xp__voting.html#autotoc_md1936',1,'Vote Power Scales with Level'],['../md_docs_2codex-implementation.html#autotoc_md1009',1,'When to Use Each Level']]],
  ['level_2015_20sees_20prompt_15',['Agent Llama (Level 15) Sees Prompt',['../md_docs_2conflict__resolution__examples.html#autotoc_md1057',1,'']]],
  ['level_2025_20sees_20prompt_16',['Agent Grok (Level 25) Sees Prompt',['../md_docs_2conflict__resolution__examples.html#autotoc_md1058',1,'']]],
  ['level_2030_20attempts_17',['Agent Grok (Level 30) Attempts',['../md_docs_2conflict__resolution__examples.html#autotoc_md1069',1,'']]],
  ['level_2040_20handling_18',['Level 40+ Handling',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md458',1,'']]],
  ['level_2050_20resolves_19',['Supervisor-Level Agent (Level 50) Resolves',['../md_docs_2conflict__resolution__examples.html#autotoc_md1070',1,'']]],
  ['level_20agent_20level_2050_20resolves_20',['Supervisor-Level Agent (Level 50) Resolves',['../md_docs_2conflict__resolution__examples.html#autotoc_md1070',1,'']]],
  ['level_20analysis_21',['Function-Level Analysis',['../md_docs_2workshop_2benchmarks.html#autotoc_md1758',1,'']]],
  ['level_20milestones_22',['Level Milestones',['../md_docs_2privilege__mapping.html#autotoc_md1476',1,'Level Milestones'],['../md_docs_2privilege__mapping__quickref.html#autotoc_md1506',1,'Level Milestones']]],
  ['level_20system_23',['XP &amp;amp; Level System',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md455',1,'']]],
  ['level_20system_20✅_24',['Phase 3: Experience &amp;amp; Level System ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md482',1,'']]],
  ['level_20tiers_25',['Level Tiers',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1498',1,'']]],
  ['level_20title_20progression_26',['Level Title Progression',['../md_TODO.html#autotoc_md2243',1,'🎮 XP/Level/Title Progression'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1405',1,'Section 11 – XP / Level / Title Progression']]],
  ['level_20to_20privilege_20mapping_20system_27',['Level-to-Privilege Mapping System',['../md_docs_2privilege__mapping.html',1,'']]],
  ['levels_28',['Levels',['../md_skills_2claude__build.html#autotoc_md2136',1,'3. Document Severity Levels'],['../md_docs_2references_2quick-reference.html#autotoc_md1565',1,'Agent Ranks &amp;amp; Levels'],['../md_docs_2codex-implementation.html#autotoc_md1007',1,'Reasoning Effort Levels']]],
  ['levels_201_209_29',['Worker (Levels 1-9)',['../md_docs_2privilege__mapping.html#autotoc_md1482',1,'']]],
  ['levels_2010_2019_30',['Senior Worker / Team Leader (Levels 10-19)',['../md_docs_2privilege__mapping.html#autotoc_md1483',1,'']]],
  ['levels_2020_2029_31',['Team Leader / Deputy Supervisor (Levels 20-29)',['../md_docs_2privilege__mapping.html#autotoc_md1484',1,'']]],
  ['levels_2030_32',['Deputy Supervisor / Supervisor-Eligible (Levels 30+)',['../md_docs_2privilege__mapping.html#autotoc_md1485',1,'']]],
  ['libraries_33',['Primary Analysis Libraries',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1776',1,'']]],
  ['library_20dependencies_34',['Standard Library Dependencies',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1780',1,'']]],
  ['license_35',['License',['../md_docs_2socket__interface.html#autotoc_md1672',1,'License'],['../md_MISSION.html#autotoc_md1986',1,'License'],['../md_README.html#autotoc_md2050',1,'License']]],
  ['lifecycle_36',['Agent Lifecycle',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md500',1,'']]],
  ['like_37',['5. Simple XML tags like &amp;lt;read_file&amp;gt;, &amp;lt;shell&amp;gt;',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md256',1,'']]],
  ['limit_2050_38',['&lt;span class=&quot;tt&quot;&gt;get_broadcasts(since=None, category=None, agent=None, requires_ack_only=False, limit=50)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1309',1,'']]],
  ['limit_20errors_20413_20not_20handled_20✅_39',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['limitation_20known_20bug_40',['⚠️ COM disassembly limitation (known bug)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2191',1,'']]],
  ['limitation_3a_41',['⚠️ Known Limitation:',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md130',1,'']]],
  ['limitations_42',['Limitations',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md667',1,'Bubblewrap Limitations'],['../md_docs_2socket__interface.html#autotoc_md1655',1,'Current Limitations'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md665',1,'Known Limitations'],['../md_docs_2features_2sandbox.html#autotoc_md1262',1,'Known Limitations'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1411',1,'Known Limitations'],['../md_docs_2TESTING.html#autotoc_md1750',1,'Known Limitations'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1930',1,'Known Limitations'],['../md_docs_2features_2configuration.html#autotoc_md1183',1,'Limitations'],['../md_docs_2socket__interface.html#autotoc_md1654',1,'Limitations'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md934',1,'Part 9: Known Issues &amp;amp; Limitations']]],
  ['limitations_20by_20design_43',['Limitations (By Design)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md936',1,'']]],
  ['limitations_20expected_44',['Known Limitations (Expected)',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1378',1,'']]],
  ['limited_20error_20recovery_45',['Finding #2: Limited Error Recovery',['../md_docs_2workshop_2security-audit.html#autotoc_md1866',1,'']]],
  ['limiting_46',['Limiting',['../md_docs_2workshop_2security-audit.html#autotoc_md1867',1,'Finding #3: No Rate Limiting'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md382',1,'Rate Limiting'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md581',1,'Rate Limiting']]],
  ['limiting_20✅_47',['3. Agent Rate Limiting ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md362',1,'']]],
  ['limits_48',['Limits',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md442',1,'API Provider Limits'],['../md_docs_2global-workspace.html#autotoc_md1319',1,'Broadcast Limits'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md437',1,'Limits'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md420',1,'Recommended Work Duration Limits'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md421',1,'Why These Limits?']]],
  ['limits_20anti_20abuse_49',['Vote Limits (Anti-Abuse)',['../md_docs_2xp__voting.html#autotoc_md1937',1,'']]],
  ['limits_20increased_20for_20maximum_20shared_20view_50',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['line_51',['Command Line',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1921',1,'']]],
  ['line_20as_20before_52',['No heredoc - process line by line as before',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md259',1,'']]],
  ['line_20by_20line_20as_20before_53',['No heredoc - process line by line as before',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md259',1,'']]],
  ['line_20count_54',['Line Count',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md633',1,'']]],
  ['line_20option_55',['Command Line Option',['../md_docs_2features_2github-agent-integration.html#autotoc_md1201',1,'']]],
  ['line_20options_56',['Command-Line Options',['../md_README.html#autotoc_md2006',1,'']]],
  ['line_20requires_20graphviz_57',['Command Line (Requires GraphViz)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1118',1,'']]],
  ['linear_20exponential_58',['Progression Curve (Hybrid Linear/Exponential)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md456',1,'']]],
  ['lines_59',['lines',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md619',1,'&lt;span class=&quot;tt&quot;&gt;database/&lt;/span&gt; (542 lines)'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md618',1,'&lt;span class=&quot;tt&quot;&gt;progression/&lt;/span&gt; (67 lines)'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md620',1,'&lt;span class=&quot;tt&quot;&gt;safety/&lt;/span&gt; (50 lines)'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md617',1,'&lt;span class=&quot;tt&quot;&gt;utils/&lt;/span&gt; (33 lines)']]],
  ['lines_201121_201148_60',['1. Class Constants (Lines 1121-1148)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md688',1,'']]],
  ['lines_201150_201171_61',['2. &lt;span class=&quot;tt&quot;&gt;__init__(config: Config, project_dir: str)&lt;/span&gt; (Lines 1150-1171)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md689',1,'']]],
  ['lines_201173_201287_62',['3. &lt;span class=&quot;tt&quot;&gt;_strip_heredoc_content(cmd: str) -&amp;gt; str&lt;/span&gt; (Lines 1173-1287)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md690',1,'']]],
  ['lines_201289_201408_63',['4. &lt;span class=&quot;tt&quot;&gt;_extract_commands_from_shell(cmd: str) -&amp;gt; List[str]&lt;/span&gt; (Lines 1289-1408)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md691',1,'']]],
  ['lines_201410_201458_64',['5. &lt;span class=&quot;tt&quot;&gt;_needs_shell(cmd: str) -&amp;gt; bool&lt;/span&gt; (Lines 1410-1458)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md692',1,'']]],
  ['lines_201460_201542_65',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md693',1,'']]],
  ['lines_201544_201629_66',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md694',1,'']]],
  ['lines_20added_20modified_67',['Lines Added/Modified',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1105',1,'']]],
  ['lines_20changed_68',['Lines Changed',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md244',1,'']]],
  ['lines_20of_20code_69',['Total Lines of Code',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1633',1,'']]],
  ['links_70',['Quick Links',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md864',1,'']]],
  ['linux_20namespace_20isolation_71',['2. Linux Namespace Isolation',['../md_docs_2features_2sandbox.html#autotoc_md1249',1,'']]],
  ['list_20directory_72',['LIST_DIR - List Directory',['../md_docs_2features_2parsers.html#autotoc_md1226',1,'']]],
  ['list_20str_20lines_201289_201408_73',['4. &lt;span class=&quot;tt&quot;&gt;_extract_commands_from_shell(cmd: str) -&amp;gt; List[str]&lt;/span&gt; (Lines 1289-1408)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md691',1,'']]],
  ['list_5fdir_20list_20directory_74',['LIST_DIR - List Directory',['../md_docs_2features_2parsers.html#autotoc_md1226',1,'']]],
  ['live_20agent_20interactions_75',['Test: Live Agent Interactions',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1513',1,'']]],
  ['live_20feature_20test_20results_76',['AXE Live Feature Test Results',['../md_docs_2LIVE__TEST__RESULTS.html',1,'']]],
  ['live_20instrumentation_77',['Live Instrumentation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md875',1,'✅ VALIDATED - Hammer (Live Instrumentation)'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1831',1,'&lt;b&gt;Hammer&lt;/b&gt; (Live Instrumentation)'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1815',1,'Hammer - Live Instrumentation']]],
  ['live_20instrumentation_20benchmarks_78',['Hammer - Live Instrumentation Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1765',1,'']]],
  ['live_20session_20output_79',['SRI Agent Discussion — Live Session Output',['../md_docs_2SRI__AGENT__DISCUSSION.html',1,'']]],
  ['live_20testing_80',['Evidence from Live Testing',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md319',1,'']]],
  ['llama_81',['Llama',['../md_docs_2api-providers.html#autotoc_md82',1,'HuggingFace (Llama)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md545',1,'HuggingFace (Llama)']]],
  ['llama_20405b_20model_20deprecated_82',['Issue 2: Llama 405B Model Deprecated',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md179',1,'']]],
  ['llama_20405b_20model_20deprecated_20✅_83',['Issue 2: Llama 405B Model Deprecated ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md302',1,'']]],
  ['llama_20level_2015_20sees_20prompt_84',['Agent Llama (Level 15) Sees Prompt',['../md_docs_2conflict__resolution__examples.html#autotoc_md1057',1,'']]],
  ['llama_20via_20ollama_85',['Meta Llama (via Ollama)',['../md_README.html#autotoc_md2031',1,'']]],
  ['llm_20context_20files_86',['LLM Context Files',['../md_llm__prep_2codebase__overview.html#autotoc_md1970',1,'']]],
  ['llm_20format_87',['5. XML Function Calls (Standard LLM Format)',['../md_docs_2features_2parsers.html#autotoc_md1219',1,'']]],
  ['llm_20ready_20codebase_20overview_20—_202026_2003_2017_88',['LLM-Ready Codebase Overview — 2026-03-17',['../md_llm__prep_2codebase__overview.html',1,'']]],
  ['llm_5fsystem_5fprompt_89',['llm_system_prompt',['../md_llm__prep_2llm__system__prompt.html',1,'']]],
  ['llmprep_90',['llmprep',['../md_README.html#autotoc_md2038',1,'']]],
  ['llmprep_20settings_91',['llmprep Settings',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md526',1,'']]],
  ['llms_92',['Ollama Provider (Local LLMs)',['../md_docs_2features_2configuration.html#autotoc_md1180',1,'']]],
  ['load_93',['Section 3 – Session Save / Load',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1389',1,'']]],
  ['loading_94',['Manual Skill Loading',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md762',1,'']]],
  ['loading_20—_20session_20commands_95',['Session Saving and Loading — &lt;span class=&quot;tt&quot;&gt;/session&lt;/span&gt; commands',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1687',1,'']]],
  ['loading_20process_96',['Configuration Loading Process',['../md_docs_2features_2configuration.html#autotoc_md1167',1,'']]],
  ['local_97',['Local',['../md_README.html#autotoc_md2022',1,'Mixed Cloud + Local'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md549',1,'Usage - Transformers (Local)']]],
  ['local_20llms_98',['Ollama Provider (Local LLMs)',['../md_docs_2features_2configuration.html#autotoc_md1180',1,'']]],
  ['local_20models_99',['Ollama Integration (Local Models)',['../md_ARCHITECTURE.html#autotoc_md58',1,'']]],
  ['local_20ollama_20models_100',['With Local Ollama Models',['../md_README.html#autotoc_md2021',1,'']]],
  ['local_20only_20communication_101',['Local-Only Communication',['../md_docs_2socket__interface.html#autotoc_md1649',1,'']]],
  ['location_102',['Configuration Files Location',['../md_docs_2features_2configuration.html#autotoc_md1185',1,'']]],
  ['location_20fix_20implementation_20summary_103',['Database Location Fix - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html',1,'']]],
  ['locations_104',['Socket and PID File Locations',['../md_docs_2socket__interface.html#autotoc_md1639',1,'']]],
  ['logging_20of_20sensitive_20data_105',['Finding #5: Logging of Sensitive Data',['../md_docs_2workshop_2security-audit.html#autotoc_md1869',1,'']]],
  ['logic_106',['Logic',['../md_docs_2codex-implementation.html#autotoc_md1017',1,'Detection Logic'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md443',1,'Spawning Logic']]],
  ['logic_20core_20agent_5fmanager_20py_107',['5. API Call Logic (&lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;)',['../md_docs_2codex-implementation.html#autotoc_md1015',1,'']]],
  ['logs_108',['Logs',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md953',1,'Appendix A: Test Execution Logs'],['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1514',1,'Demo Output (Actual Runtime Logs)']]],
  ['lookup_109',['Quick Command Lookup',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1591',1,'']]],
  ['loop_110',['1. Collaboration — Supervisor Feedback Loop',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md982',1,'']]],
  ['low_111',['LOW',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md852',1,'Merge Risk: ⚠️ LOW'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md948',1,'Merge Risks: LOW']]],
  ['low_112',['3. &lt;b&gt;YAML Config&lt;/b&gt; ✅ Low',['../md_docs_2security.html#autotoc_md1604',1,'']]],
  ['low_20severity_20issues_113',['Low Severity Issues',['../md_docs_2workshop_2security-audit.html#autotoc_md1860',1,'']]],
  ['lowercase_20no_20prefixes_114',['General Rule: Lowercase, No Prefixes',['../md_docs_2features_2configuration.html#autotoc_md1173',1,'']]]
];
