var searchData=
[
  ['v_0',['V',['../md_TODO.html#autotoc_md2234',1,'']]],
  ['v1_200_20current_1',['v1.0 (Current)',['../md_docs_2features_2write-blocks.html#autotoc_md1298',1,'']]],
  ['valgrind_20memory_20analysis_2',['Valgrind (Memory Analysis)',['../md_skills_2claude__build.html#autotoc_md2104',1,'']]],
  ['validate_20command_3',['Validate Command',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1503',1,'']]],
  ['validate_20filename_4',['Validate filename',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md401',1,'']]],
  ['validated_20bonus_20xp_20calculation_5',['✅ VALIDATED - Bonus XP Calculation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md883',1,'']]],
  ['validated_20chisel_20symbolic_20execution_6',['✅ VALIDATED - Chisel (Symbolic Execution)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md872',1,'']]],
  ['validated_20configuration_20structure_7',['✅ VALIDATED - Configuration Structure',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md886',1,'']]],
  ['validated_20database_20methods_8',['✅ VALIDATED - Database Methods',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md879',1,'']]],
  ['validated_20database_20schema_9',['✅ VALIDATED - Database Schema',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md878',1,'']]],
  ['validated_20documentation_20files_10',['✅ VALIDATED - Documentation Files',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md889',1,'']]],
  ['validated_20hammer_20live_20instrumentation_11',['✅ VALIDATED - Hammer (Live Instrumentation)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md875',1,'']]],
  ['validated_20plane_20source_20sink_20enumeration_12',['✅ VALIDATED - Plane (Source/Sink Enumeration)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md874',1,'']]],
  ['validated_20saw_20taint_20analysis_13',['✅ VALIDATED - Saw (Taint Analysis)',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md873',1,'']]],
  ['validated_20test_20files_14',['✅ VALIDATED - Test Files',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md897',1,'']]],
  ['validated_20xp_20awards_20dictionary_15',['✅ VALIDATED - XP Awards Dictionary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md882',1,'']]],
  ['validation_16',['Validation',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1547',1,'3. Comprehensive Validation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md927',1,'Dependency Validation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md893',1,'Document 4: Dependency Validation'],['../md_docs_2workshop_2security-audit.html#autotoc_md1865',1,'Finding #1: Missing Input Size Validation'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1788',1,'Installation Validation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md907',1,'Part 3: Security Validation'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md912',1,'Part 4: Performance Validation'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1795',1,'Security Validation'],['../md_docs_2workshop_2test-results.html#autotoc_md1905',1,'Test Environment Validation'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md331',1,'Validation'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md766',1,'Validation'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md779',1,'Validation'],['../md_docs_2workshop_2dependency-validation.html',1,'Workshop Tools Dependency Validation'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md727',1,'YAML Validation']]],
  ['validation_20checklist_17',['Feature Validation Checklist',['../md_docs_2TESTING.html#autotoc_md1746',1,'']]],
  ['validation_20conclusion_18',['Part 10: Validation Conclusion',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md938',1,'']]],
  ['validation_20errors_19',['Validation Errors',['../md_docs_2features_2configuration.html#autotoc_md1170',1,'']]],
  ['validation_20example_20',['Validation Example',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1551',1,'']]],
  ['validation_20internal_20stripped_20version_20_3a_21',['Validation (internal, stripped version):',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md350',1,'']]],
  ['validation_20md_22',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2dependency-validation.html&quot;&gt;dependency-validation.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1838',1,'']]],
  ['validation_20md_20dependency_20validation_20md_23',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2dependency-validation.html&quot;&gt;dependency-validation.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1838',1,'']]],
  ['validation_20quality_20assurance_24',['Validation &amp;amp; Quality Assurance',['../md_docs_2workshop_2quick-reference.html#autotoc_md1826',1,'']]],
  ['validation_20report_25',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html',1,'']]],
  ['validation_20results_26',['Validation Results',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md835',1,'']]],
  ['validation_20sign_20off_27',['Validation Sign-Off',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md951',1,'']]],
  ['validation_20suite_28',['Custom Validation Suite',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md836',1,'']]],
  ['validation_20summary_29',['Validation Summary',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md978',1,'Feature Validation Summary'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1774',1,'Validation Summary']]],
  ['validation_20test_20suite_30',['Validation Test Suite',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md954',1,'']]],
  ['validation_20tests_20created_31',['Custom Validation Tests Created',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md922',1,'']]],
  ['validation_20verified_32',['Input Validation - VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md909',1,'']]],
  ['variable_33',['Variable',['../md_docs_2api-providers.html#autotoc_md68',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md76',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md86',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md95',1,'Environment Variable'],['../md_docs_2api-providers.html#autotoc_md104',1,'Environment Variable']]],
  ['variables_20summary_34',['Environment Variables Summary',['../md_docs_2api-providers.html#autotoc_md110',1,'']]],
  ['variants_35',['Pre-configured Reasoning Variants',['../md_docs_2codex-implementation.html#autotoc_md1008',1,'']]],
  ['venv_20pip_36',['Option A: Standard venv + pip',['../md_README.html#autotoc_md2000',1,'']]],
  ['verbose_37',['Verbose',['../md_skills_2claude__build.html#autotoc_md2132',1,'1. Start Silent, Investigate Verbose'],['../md_skills_2claude__build.html#autotoc_md2126',1,'Phase 3: Detailed Investigation (Verbose)']]],
  ['verbose_20by_20default_38',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md2080',1,'']]],
  ['verbose_20on_20failure_39',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md2073',1,'']]],
  ['verbose_20output_40',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md36',1,'']]],
  ['verbose_20output_3a_41',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md2112',1,'']]],
  ['verbosely_42',['5. Test Silently, Debug Verbosely',['../md_skills_2build.html#autotoc_md2076',1,'']]],
  ['verification_43',['Verification',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md236',1,'Manual Verification'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md901',1,'Part 2: Integration Verification'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1359',1,'Runtime Verification'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md137',1,'Verification'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md234',1,'Verification'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md271',1,'Verification'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md347',1,'Verification'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md713',1,'Verification']]],
  ['verification_44',['Manual verification',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md806',1,'']]],
  ['verification_20✅_45',['Test 1: Ollama Setup Verification ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1464',1,'']]],
  ['verification_20and_20reporting_46',['7. Token Savings — Verification and Reporting',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md994',1,'']]],
  ['verification_20commands_47',['Verification Commands',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1519',1,'']]],
  ['verification_20results_48',['Verification Results',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1347',1,'2. Verification Results'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md726',1,'Verification Results']]],
  ['verified_49',['VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md909',1,'Input Validation - VERIFIED'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md908',1,'No Hardcoded Secrets - VERIFIED'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md910',1,'Resource Controls - VERIFIED']]],
  ['verified_50',['Features Verified',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1373',1,'']]],
  ['verify_20no_20breakage_51',['Existing tests (verify no breakage)',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md807',1,'']]],
  ['verifying_20integration_52',['Verifying Integration',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1040',1,'']]],
  ['version_20_3a_53',['version :',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md351',1,'Execution (original version):'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md350',1,'Validation (internal, stripped version):']]],
  ['version_20check_54',['Tool Version Check',['../md__8collab__env.html#autotoc_md9',1,'']]],
  ['version_20pinning_55',['Finding #4: Dependency Version Pinning',['../md_docs_2workshop_2security-audit.html#autotoc_md1868',1,'']]],
  ['version_20support_56',['Python Version Support',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1786',1,'']]],
  ['versioned_20history_57',['3. Session Persistence — Versioned History',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md986',1,'']]],
  ['versioned_20session_20store_58',['2. Versioned Session Store',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1698',1,'']]],
  ['versioned_20under_20scripts_20patches_20dosbox_20staging_59',['dosbox-staging build patches (versioned under &lt;span class=&quot;tt&quot;&gt;scripts/patches/dosbox-staging/&lt;/span&gt;)',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2195',1,'']]],
  ['very_20common_60',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md2159',1,'']]],
  ['via_20ollama_61',['Meta Llama (via Ollama)',['../md_README.html#autotoc_md2031',1,'']]],
  ['via_20socket_62',['Sending Commands via Socket',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1630',1,'']]],
  ['view_63',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['viewing_20diagrams_64',['Viewing Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1116',1,'']]],
  ['viewing_20session_20rules_65',['Viewing Session Rules',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md495',1,'']]],
  ['vision_20—_20alignment_20assessment_66',['The &quot;Office&quot; Vision — Alignment Assessment',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md998',1,'']]],
  ['vision_20and_20sri_67',['The &quot;Office&quot; Vision and SRI',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1702',1,'']]],
  ['vision_20example_20images_68',['Vision Example (Images)',['../md_docs_2api-providers.html#autotoc_md79',1,'']]],
  ['vote_69',['Vote',['../md_docs_2xp__voting.html#autotoc_md1939',1,'Casting a Vote'],['../md_docs_2xp__voting.html#autotoc_md1956',1,'When to Vote']]],
  ['vote_20limits_20anti_20abuse_70',['Vote Limits (Anti-Abuse)',['../md_docs_2xp__voting.html#autotoc_md1937',1,'']]],
  ['vote_20power_20scales_20with_20level_71',['Vote Power Scales with Level',['../md_docs_2xp__voting.html#autotoc_md1936',1,'']]],
  ['vote_20reasons_72',['Vote Reasons',['../md_docs_2xp__voting.html#autotoc_md1958',1,'']]],
  ['vote_5fid_73',['&lt;span class=&quot;tt&quot;&gt;mark_vote_applied(vote_id)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1948',1,'']]],
  ['vote_5fxp_20voter_5falias_20voter_5flevel_20target_5falias_20xp_5fdelta_20reason_74',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['voter_5falias_20voter_5flevel_20target_5falias_20xp_5fdelta_20reason_75',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['voter_5flevel_20target_5falias_20xp_5fdelta_20reason_76',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['votes_77',['Using Negative Votes',['../md_docs_2xp__voting.html#autotoc_md1957',1,'']]],
  ['votes_78',['&lt;span class=&quot;tt&quot;&gt;apply_xp_votes(votes)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1951',1,'']]],
  ['votes_20not_20applied_79',['Votes Not Applied?',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1046',1,'']]],
  ['voting_20minsky_201986_80',['XP Voting (Minsky, 1986)',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1351',1,'']]],
  ['voting_20peer_20reputation_81',['2. XP Voting (Peer Reputation)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1032',1,'']]],
  ['voting_20system_82',['Peer XP Voting System',['../md_docs_2xp__voting.html',1,'']]],
  ['voting_20system_20database_20✅_83',['Test 3: XP Voting System + Database ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1466',1,'']]],
  ['voting_20system_20minsky_201986_84',['PR #55: XP Voting System (Minsky 1986)',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1086',1,'']]],
  ['vs_20active_20documentation_85',['Archive vs. Active Documentation',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md967',1,'']]],
  ['vs_20actual_20implementation_86',['Part 1: PR Claims vs. Actual Implementation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md870',1,'']]],
  ['vs_20after_87',['Example - Before vs After',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md348',1,'']]],
  ['vs_20chat_20completions_88',['Key Differences: Responses API vs Chat Completions',['../md_docs_2codex-implementation.html#autotoc_md1016',1,'']]],
  ['vs_20code_89',['VS Code',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1119',1,'']]],
  ['vs_20runtime_90',['Key Differences: Demos vs Runtime',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1356',1,'']]],
  ['vulnerability_20disagreement_91',['Example 1: Security Vulnerability Disagreement',['../md_docs_2conflict__resolution__examples.html#autotoc_md1052',1,'']]],
  ['vulnerability_20scan_92',['Dependency Vulnerability Scan',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1796',1,'']]]
];
