var searchData=
[
  ['i_20o_0',['Disk I/O',['../md_workshop__dependency__validation.html#autotoc_md1384',1,'']]],
  ['id_20generation_1',['Issue #5: Weak Random ID Generation',['../md_workshop__security__audit.html#autotoc_md1428',1,'']]],
  ['ida_20pro_20decompiler_20analysis_20expert_2',['IDA Pro / Decompiler Analysis Expert',['../md_skills_2ida__pro__analysis__patterns.html',1,'']]],
  ['identified_20non_20blocking_3',['Minor Issues Identified (Non-Blocking)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md813',1,'']]],
  ['if_20all_20trials_20fail_4',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['if_20critical_20issues_20found_20re_20run_20with_20full_20details_3a_5',['If critical issues found, re-run with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'']]],
  ['if_20issues_20detected_20re_20run_20with_20verbose_20output_3a_6',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['if_20issues_20found_20re_20run_20with_20full_20details_3a_7',['If issues found, re-run with full details:',['../md_skills_2claude__build.html#autotoc_md1215',1,'']]],
  ['if_20issues_20found_20run_20full_20scan_3a_8',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md1227',1,'']]],
  ['if_20needed_9',['Create parent dirs if needed',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md466',1,'']]],
  ['if_20so_20treat_20the_20whole_20block_20as_20a_20single_20command_10',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['if_20the_20entire_20block_20contains_20a_20heredoc_11',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['if_20tools_20expand_12',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['image_20generation_13',['Usage - Image Generation',['../md_MODELS__FINAL.html#autotoc_md644',1,'']]],
  ['images_14',['Vision Example (Images)',['../md_API__PROVIDERS.html#autotoc_md121',1,'']]],
  ['immediate_20actions_15',['Immediate Actions',['../md_workshop__test__results.html#autotoc_md1474',1,'']]],
  ['immediate_20actions_20completed_16',['Immediate Actions (Completed)',['../md_workshop__security__audit.html#autotoc_md1444',1,'']]],
  ['immediate_20same_20day_17',['Immediate (Same Day)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md736',1,'']]],
  ['immediately_18',['✅ &lt;b&gt;MERGE IMMEDIATELY&lt;/b&gt;',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md733',1,'']]],
  ['impact_19',['Impact',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md33',1,'Impact'],['../md_BUG__FIX__SUMMARY.html#autotoc_md205',1,'Impact'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md332',1,'Impact'],['../md_FIXES__SUMMARY.html#autotoc_md378',1,'Impact'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md398',1,'Impact'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md681',1,'Impact'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1333',1,'Impact'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md724',1,'Integration Impact'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md269',1,'Performance Impact'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md359',1,'Performance Impact'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1087',1,'Performance Impact'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md84',1,'Real-World Impact']]],
  ['impact_20after_20fix_20',['Impact After Fix',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md235',1,'']]],
  ['impact_20analysis_21',['Performance Impact Analysis',['../md_workshop__dependency__validation.html#autotoc_md1381',1,'']]],
  ['impact_20before_20fix_22',['Impact Before Fix',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md221',1,'']]],
  ['implementation_23',['Implementation',['../md_IMPROVEMENTS__FINAL.html#autotoc_md485',1,'Implementation'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md490',1,'Implementation'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md669',1,'Implementation'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'Multi-Format Tool Call Parser Implementation'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md748',1,'Part 1: PR Claims vs. Actual Implementation'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md96',1,'Ready for Implementation']]],
  ['implementation_20approach_24',['Implementation Approach',['../md_REFACTORING__NOTES.html#autotoc_md1002',1,'']]],
  ['implementation_20complete_20✅_25',['AXE Enhancement Implementation - Complete ✅',['../md_IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['implementation_20details_26',['Implementation Details',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md579',1,'Implementation Details'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1060',1,'Implementation Details'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1494',1,'Implementation Details'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1304',1,'Technical Implementation Details']]],
  ['implementation_20notes_27',['Implementation Notes',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1135',1,'']]],
  ['implementation_20priority_28',['Implementation Priority',['../md_IMPROVEMENTS__FINAL.html#autotoc_md535',1,'']]],
  ['implementation_20status_3a_20✅_20complete_29',['Implementation Status: ✅ COMPLETE',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md72',1,'']]],
  ['implementation_20summary_30',['Implementation Summary',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'Agent Skills System Implementation Summary'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'Anthropic Claude-Specific Optimizations - Implementation Summary'],['../md_IMPROVEMENTS__README.html',1,'AXE Multiagent Improvements - Implementation Summary'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html',1,'Bubblewrap Sandbox Implementation - Summary'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html',1,'Database Location Fix - Implementation Summary'],['../md_DYNAMIC__TOKENS__SUMMARY.html',1,'Dynamic Max Output Tokens Implementation Summary'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'Heredoc Execution Fix - Implementation Summary'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html',1,'Shell Operator Support Implementation Summary'],['../md_SILENT__BUILDS__IMPLEMENTATION.html',1,'Silent Builds Feature - Implementation Summary'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html',1,'Source Code Minifier Implementation Summary'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'WRITE Block Absolute Path Fix - Implementation Summary'],['../md_XML__PARSER__IMPLEMENTATION.html',1,'XML Function Call Parser - Implementation Summary']]],
  ['implementation_20summary_3a_20gpt_205_20fix_20write_20blocks_31',['Implementation Summary: GPT-5 Fix &amp;amp; WRITE Blocks',['../md_IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['implemented_32',['Implemented',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md422',1,'✅ All Features Implemented'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md749',1,'Claim 1: Four Analysis Tools Implemented'],['../md_QUICK__REFERENCE.html#autotoc_md861',1,'Future Features (Not Yet Implemented)'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1293',1,'Key Features Implemented'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md212',1,'Solution Implemented'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md222',1,'Solution Implemented'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md404',1,'Solution Implemented'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1111',1,'Solution Implemented'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1141',1,'What Was Implemented']]],
  ['implemented_20features_33',['Summary of All Implemented Features',['../md_IMPROVEMENTS__README.html#autotoc_md568',1,'']]],
  ['implemented_20features_20phases_201_205_34',['Implemented Features (Phases 1-5)',['../md_IMPROVEMENTS__README.html#autotoc_md542',1,'']]],
  ['implemented_20features_20phases_206_2010_35',['Implemented Features (Phases 6-10)',['../md_IMPROVEMENTS__README.html#autotoc_md548',1,'']]],
  ['imports_20✅_36',['Phase 3: Update Imports ✅',['../md_REFACTORING__NOTES.html#autotoc_md1005',1,'']]],
  ['improvement_20reference_20guide_37',['AXE Multi-Agent System - Improvement Reference Guide',['../md_IMPROVEMENTS__FINAL.html',1,'']]],
  ['improvements_38',['Potential Improvements',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1091',1,'']]],
  ['improvements_20implementation_20summary_39',['AXE Multiagent Improvements - Implementation Summary',['../md_IMPROVEMENTS__README.html',1,'']]],
  ['in_20axe_40',['Anthropic Claude-Specific Features in AXE',['../md_docs_2ANTHROPIC__FEATURES.html',1,'']]],
  ['in_20axe_20yaml_41',['Enable in axe.yaml',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md590',1,'']]],
  ['in_20chisel_20analysis_42',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_workshop__security__audit.html#autotoc_md1424',1,'']]],
  ['in_20ci_20cd_20security_20checks_43',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md1246',1,'']]],
  ['in_20collab_20mode_44',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['in_20collab_20mode_20✅_45',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['in_20database_20operations_46',['Issue #4: Race Condition in Database Operations',['../md_workshop__security__audit.html#autotoc_md1427',1,'']]],
  ['in_20error_20messages_47',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['in_20hammer_20module_48',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['in_20one_20response_49',['4. Multiple Files in One Response',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1485',1,'']]],
  ['in_20order_50',['Execute each block in order',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md462',1,'']]],
  ['in_20run_20method_51',['1. Defensive Programming in &lt;span class=&quot;tt&quot;&gt;run()&lt;/span&gt; Method',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md405',1,'']]],
  ['in_20security_20audits_52',['Token Savings in Security Audits',['../md_skills_2claude__build.html#autotoc_md1239',1,'']]],
  ['in_20subdirectory_53',['3. File in Subdirectory',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1484',1,'']]],
  ['in_20whitelist_20mode_20but_20not_20sandbox_20mode_54',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['included_20by_20accident_55',['included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['increased_20for_20maximum_20shared_20view_56',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['independence_57',['Module Independence',['../md_REFACTORING__NOTES.html#autotoc_md1011',1,'']]],
  ['index_58',['Symbol Index',['../md_llm__prep_2codebase__overview.html#autotoc_md573',1,'']]],
  ['indexing_59',['3. Collaborative Session Pre-indexing',['../md_README.html#autotoc_md955',1,'']]],
  ['indirect_5fflow_5fhunter_60',['indirect_flow_hunter',['../md_skills_2indirect__flow__hunter.html',1,'']]],
  ['information_61',['More Information',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1528',1,'']]],
  ['information_20disclosure_20in_20error_20messages_62',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['informational_20findings_63',['Informational Findings',['../md_workshop__security__audit.html#autotoc_md1429',1,'']]],
  ['initial_20silent_20build_64',['Phase 1: Initial Silent Build',['../md_skills_2claude__build.html#autotoc_md1229',1,'']]],
  ['injection_20in_20hammer_20module_65',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['inline_20comments_66',['3. Inline Comments',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md407',1,'']]],
  ['input_20size_20validation_67',['Finding #1: Missing Input Size Validation',['../md_workshop__security__audit.html#autotoc_md1430',1,'']]],
  ['input_20validation_20verified_68',['Input Validation - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md787',1,'']]],
  ['input_3a_69',['Input:',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md323',1,'']]],
  ['inside_20sandbox_70',['&quot;Permission denied&quot; errors inside sandbox',['../md_SANDBOX.html#autotoc_md1054',1,'']]],
  ['inspection_71',['Database Inspection',['../md_IMPROVEMENTS__README.html#autotoc_md560',1,'']]],
  ['install_20dependencies_72',['Install Dependencies',['../md_README.html#autotoc_md878',1,'']]],
  ['install_20dependencies_20silently_73',['Install dependencies silently',['../md_skills_2build.html#autotoc_md1198',1,'']]],
  ['installation_74',['Installation',['../md_AGENTS.html#autotoc_md44',1,'Installation'],['../md_README.html#autotoc_md876',1,'Installation'],['../md_README.html#autotoc_md959',1,'Installation']]],
  ['installation_20required_75',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md282',1,'']]],
  ['installation_20testing_76',['Automated Installation Testing',['../md_workshop__dependency__validation.html#autotoc_md1379',1,'']]],
  ['installation_20validation_77',['Installation Validation',['../md_workshop__dependency__validation.html#autotoc_md1378',1,'']]],
  ['instructions_78',['Build Instructions',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1340',1,'']]],
  ['instrumentation_79',['Instrumentation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md753',1,'✅ VALIDATED - Hammer (Live Instrumentation)'],['../md_README.html#autotoc_md964',1,'Hammer - Live Instrumentation'],['../md_workshop__quick__reference.html#autotoc_md1405',1,'Hammer - Live Instrumentation']]],
  ['instrumentation_20benchmarks_80',['Hammer - Live Instrumentation Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1355',1,'']]],
  ['instrumentation_20framework_81',['frida-python (Instrumentation Framework)',['../md_workshop__dependency__validation.html#autotoc_md1368',1,'']]],
  ['instrumentation_20performance_82',['Process Instrumentation Performance',['../md_workshop__benchmarks.html#autotoc_md1356',1,'']]],
  ['integrated_20tools_83',['Integrated Tools',['../md_README.html#autotoc_md872',1,'']]],
  ['integration_84',['Integration',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md698',1,'✅ Complete AXE Integration'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md755',1,'Claim 2: Database Integration'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md759',1,'Claim 3: XP System Integration'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md763',1,'Claim 4: Configuration Integration'],['../md_README.html#autotoc_md970',1,'Database Integration'],['../md_workshop__quick__reference.html#autotoc_md1410',1,'Database Integration'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html',1,'GitHub Agent Integration'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md587',1,'Integration']]],
  ['integration_209_2010_85',['🔧 Integration (9/10)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md704',1,'']]],
  ['integration_20complete_86',['Integration COMPLETE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md782',1,'Configuration Integration - COMPLETE'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md780',1,'Database Integration - COMPLETE'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md781',1,'XP System Integration - COMPLETE']]],
  ['integration_20distributed_20ai_87',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md169',1,'']]],
  ['integration_20impact_88',['Integration Impact',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md724',1,'']]],
  ['integration_20local_20models_89',['Ollama Integration (Local Models)',['../md_ARCHITECTURE.html#autotoc_md168',1,'']]],
  ['integration_20points_20summary_90',['Part 8: Integration Points Summary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md808',1,'']]],
  ['integration_20status_91',['Integration Status',['../md_PR23__VALIDATION__REPORT.html#autotoc_md810',1,'']]],
  ['integration_20test_20results_92',['Integration Test Results',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md85',1,'']]],
  ['integration_20test_20results_20test_5fworkshop_5fintegration_20py_93',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1455',1,'']]],
  ['integration_20test_20test_5fintegration_5fdatabase_5ffix_20py_94',['Integration Test (&lt;span class=&quot;tt&quot;&gt;test_integration_database_fix.py&lt;/span&gt;)',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md230',1,'']]],
  ['integration_20testing_95',['Integration Testing',['../md_workshop__dependency__validation.html#autotoc_md1388',1,'']]],
  ['integration_20tests_96',['Test File 2: Integration Tests',['../md_PR23__VALIDATION__REPORT.html#autotoc_md777',1,'']]],
  ['integration_20tests_20passed_97',['✅ Integration Tests Passed',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md434',1,'']]],
  ['integration_20verification_98',['Part 2: Integration Verification',['../md_PR23__VALIDATION__REPORT.html#autotoc_md779',1,'']]],
  ['integration_20with_20agentmanager_99',['6. Integration with AgentManager',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1301',1,'']]],
  ['integration_20with_20agents_100',['Integration with Agents',['../md_README.html#autotoc_md951',1,'Integration with Agents'],['../md_README.html#autotoc_md969',1,'Integration with Agents'],['../md_workshop__quick__reference.html#autotoc_md1414',1,'Integration with Agents']]],
  ['integration_20with_20agents_20md_101',['Integration with AGENTS.md',['../md_skills_2claude__build.html#autotoc_md1250',1,'']]],
  ['integration_20with_20axe_102',['Integration with AXE',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1155',1,'']]],
  ['integration_20with_20axe_20yaml_103',['Integration with axe.yaml',['../md_skills_2build.html#autotoc_md1178',1,'']]],
  ['integration_20with_20collaborations_104',['Integration with Collaborations',['../md_skills_2build.html#autotoc_md1179',1,'']]],
  ['integration_20with_20other_20blocks_105',['Integration with Other Blocks',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1486',1,'']]],
  ['integrity_106',['Test Data Integrity',['../md_workshop__test__results.html#autotoc_md1472',1,'']]],
  ['interactions_107',['Cross-Tool Interactions',['../md_workshop__dependency__validation.html#autotoc_md1390',1,'']]],
  ['interactive_108',['Auto-Approve Mode (Non-Interactive)',['../md_README.html#autotoc_md927',1,'']]],
  ['interactive_20demo_109',['Run interactive demo',['../md_QUICK__REFERENCE.html#autotoc_md850',1,'']]],
  ['interactive_20mode_110',['Interactive Mode',['../md_README.html#autotoc_md893',1,'']]],
  ['interactive_20testing_111',['Interactive Testing',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1493',1,'']]],
  ['interface_112',['Review Interface',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md295',1,'']]],
  ['internal_20stripped_20version_20_3a_113',['Validation (internal, stripped version):',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md413',1,'']]],
  ['investigate_20verbose_114',['1. Start Silent, Investigate Verbose',['../md_skills_2claude__build.html#autotoc_md1241',1,'']]],
  ['investigation_20verbose_115',['Phase 3: Detailed Investigation (Verbose)',['../md_skills_2claude__build.html#autotoc_md1235',1,'']]],
  ['is_20sacred_116',['1. Mission First – The Project / Task Is Sacred',['../md_IMPROVEMENTS__FINAL.html#autotoc_md525',1,'']]],
  ['is_5ftool_5fallowed_20cmd_3a_20str_20lines_201460_201542_117',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1117',1,'']]],
  ['isolated_118',['Scenario 3: Network Isolated',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1085',1,'']]],
  ['isolated_20sandbox_119',['Example 3: Network-Isolated Sandbox',['../md_SANDBOX.html#autotoc_md1039',1,'']]],
  ['isolation_120',['Isolation',['../md_SANDBOX.html#autotoc_md1030',1,'2. Linux Namespace Isolation'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1065',1,'2. Namespace Isolation'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md711',1,'3. Database Test Isolation']]],
  ['issue_121',['The Issue',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md389',1,'']]],
  ['issue_201_3a_20gpt_205_20api_20parameter_20error_20critical_122',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md460',1,'']]],
  ['issue_201_3a_20potential_20command_20injection_20in_20hammer_20module_123',['Issue #1: Potential Command Injection in Hammer Module',['../md_workshop__security__audit.html#autotoc_md1423',1,'']]],
  ['issue_201_3a_20read_20block_20access_20denied_124',['Issue 1: READ Block Access Denied',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md173',1,'']]],
  ['issue_201_3a_20read_20block_20access_20denied_20✅_125',['Issue 1: READ Block Access Denied ✅',['../md_FIXES__SUMMARY.html#autotoc_md363',1,'']]],
  ['issue_202_3a_20llama_20405b_20model_20deprecated_126',['Issue 2: Llama 405B Model Deprecated',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md177',1,'']]],
  ['issue_202_3a_20llama_20405b_20model_20deprecated_20✅_127',['Issue 2: Llama 405B Model Deprecated ✅',['../md_FIXES__SUMMARY.html#autotoc_md365',1,'']]],
  ['issue_202_3a_20memory_20exhaustion_20in_20chisel_20analysis_128',['Issue #2: Memory Exhaustion in Chisel Analysis',['../md_workshop__security__audit.html#autotoc_md1424',1,'']]],
  ['issue_202_3a_20write_20blocks_20not_20executing_20high_129',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['issue_203_3a_20auto_20approve_20not_20default_20in_20collab_20mode_130',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['issue_203_3a_20auto_20approve_20not_20default_20in_20collab_20mode_20✅_131',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['issue_203_3a_20information_20disclosure_20in_20error_20messages_132',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['issue_204_3a_20agents_20confused_20about_20read_20write_20block_20syntax_133',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['issue_204_3a_20agents_20confused_20about_20read_20write_20block_20syntax_20✅_134',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['issue_204_3a_20race_20condition_20in_20database_20operations_135',['Issue #4: Race Condition in Database Operations',['../md_workshop__security__audit.html#autotoc_md1427',1,'']]],
  ['issue_205_3a_20weak_20random_20id_20generation_136',['Issue #5: Weak Random ID Generation',['../md_workshop__security__audit.html#autotoc_md1428',1,'']]],
  ['issue_20debugging_137',['2. Build Issue Debugging',['../md_README.html#autotoc_md954',1,'']]],
  ['issues_138',['Issues',['../md_BUG__FIX__SUMMARY.html',1,'Bug Fix Summary - Multi-Agent Collaboration Issues'],['../md_API__PROVIDERS.html#autotoc_md157',1,'Common Issues'],['../md_README.html#autotoc_md977',1,'Common Issues'],['../md_workshop__dependency__validation.html#autotoc_md1387',1,'Known Security Issues'],['../md_workshop__security__audit.html#autotoc_md1425',1,'Low Severity Issues'],['../md_workshop__security__audit.html#autotoc_md1422',1,'Medium Severity Issues']]],
  ['issues_139',['issues',['../md_skills_2claude__build.html#autotoc_md1233',1,'Cppcheck for C/C++ issues'],['../md_skills_2claude__build.html#autotoc_md1234',1,'Flawfinder for security issues']]],
  ['issues_20addressed_140',['Code Review Issues Addressed',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md674',1,'']]],
  ['issues_20detected_20re_20run_20with_20verbose_20output_3a_141',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['issues_20fix_20summary_142',['AXE Multiple Issues Fix Summary',['../md_FIXES__SUMMARY.html',1,'']]],
  ['issues_20fixed_143',['Issues Fixed',['../md_FIXES__SUMMARY.html#autotoc_md362',1,'']]],
  ['issues_20found_20re_20run_20with_20full_20details_3a_144',['issues found re run with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md1215',1,'If issues found, re-run with full details:']]],
  ['issues_20found_20run_20full_20scan_3a_145',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md1227',1,'']]],
  ['issues_20identified_20non_20blocking_146',['Minor Issues Identified (Non-Blocking)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md813',1,'']]],
  ['issues_20limitations_147',['Part 9: Known Issues &amp;amp; Limitations',['../md_PR23__VALIDATION__REPORT.html#autotoc_md812',1,'']]],
  ['issues_20non_20blocking_148',['Minor Issues (Non-Blocking)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md708',1,'']]],
  ['issues_20resolved_149',['Issues Resolved',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md459',1,'']]],
  ['issues_20silent_150',['Quick check for memory issues (silent)',['../md_skills_2claude__build.html#autotoc_md1214',1,'']]],
  ['it_20works_151',['It Works',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md248',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md255',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md259',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md264',1,'How It Works']]]
];
