var searchData=
[
  ['hammer_20live_20instrumentation_0',['Hammer Live Instrumentation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md875',1,'✅ VALIDATED - Hammer (Live Instrumentation)'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1831',1,'&lt;b&gt;Hammer&lt;/b&gt; (Live Instrumentation)'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1815',1,'Hammer - Live Instrumentation']]],
  ['hammer_20live_20instrumentation_20benchmarks_1',['Hammer - Live Instrumentation Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1765',1,'']]],
  ['hammer_20module_2',['Issue #1: Potential Command Injection in Hammer Module',['../md_docs_2workshop_2security-audit.html#autotoc_md1858',1,'']]],
  ['handled_20✅_3',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['handled_20exclusively_20by_20axe_20py_20responseprocessor_4',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md253',1,'']]],
  ['handling_5',['Handling',['../md_docs_2features_2github-agent-integration.html#autotoc_md1209',1,'Error Handling'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1620',1,'Error Handling'],['../md_docs_2socket__interface.html#autotoc_md1652',1,'Error Handling'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md668',1,'Graceful Handling'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md458',1,'Level 40+ Handling'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1784',1,'pathlib (Path Handling)'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1619',1,'Signal Handling'],['../md_docs_2socket__interface.html#autotoc_md1647',1,'Signal Handling'],['../md_docs_2socket__interface.html#autotoc_md1646',1,'Stale File Handling']]],
  ['handling_20✅_20fixed_6',['1. &lt;b&gt;Path &amp;amp; File Handling&lt;/b&gt; ✅ Fixed',['../md_docs_2security.html#autotoc_md1602',1,'']]],
  ['handling_20robust_7',['Error Handling - ROBUST',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md917',1,'']]],
  ['hardcoded_20secrets_20verified_8',['No Hardcoded Secrets - VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md908',1,'']]],
  ['hardening_20flags_20silent_20build_9',['Pattern 1: Hardening Flags (Silent Build)',['../md_skills_2claude__build.html#autotoc_md2145',1,'']]],
  ['header_10',['Header',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md267',1,'']]],
  ['health_11',['Dependency Health',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md844',1,'']]],
  ['helper_12',['Build Analyzer Helper',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md384',1,'']]],
  ['helper_20✅_13',['5. Build Analyzer Dependency Helper ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md364',1,'']]],
  ['helper_20function_14',['Helper Function',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md226',1,'1. Added &lt;span class=&quot;tt&quot;&gt;get_database_path()&lt;/span&gt; Helper Function'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md229',1,'4. Exported Helper Function']]],
  ['helper_20functions_20models_20metadata_20py_15',['4. Helper Functions (&lt;span class=&quot;tt&quot;&gt;models/metadata.py&lt;/span&gt;)',['../md_docs_2codex-implementation.html#autotoc_md1014',1,'']]],
  ['helper_20tool_20setup_16',['Helper Tool Setup',['../md_docs_2TESTING.html#autotoc_md1736',1,'']]],
  ['heredoc_17',['Check if the entire block contains a heredoc',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md257',1,'']]],
  ['heredoc_20execution_20fix_20implementation_20summary_18',['Heredoc Execution Fix - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['heredoc_20execution_20fix_20summary_19',['Heredoc Execution Fix Summary',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html',1,'']]],
  ['heredoc_20parsing_20bug_20fixes_20',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['heredoc_20preserved_21',['Example 2: Heredoc Preserved',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md266',1,'']]],
  ['heredoc_20process_20line_20by_20line_20as_20before_22',['No heredoc - process line by line as before',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md259',1,'']]],
  ['hierarchical_20control_23',['3. Suppression (Hierarchical Control)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1033',1,'']]],
  ['high_24',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md398',1,'']]],
  ['high_20severity_20findings_25',['Good: Only high-severity findings',['../md_skills_2claude__build.html#autotoc_md2135',1,'']]],
  ['high_20severity_20only_26',['Quick security scan (high severity only)',['../md_skills_2claude__build.html#autotoc_md2117',1,'']]],
  ['hints_20good_27',['Type Hints - GOOD',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md918',1,'']]],
  ['historical_20comparison_28',['Historical Comparison',['../md_docs_2workshop_2test-results.html#autotoc_md1901',1,'']]],
  ['history_29',['History',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md986',1,'3. Session Persistence — Versioned History'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1106',1,'Commit History'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1817',1,'History']]],
  ['history_20and_20selection_30',['Session History and Selection',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1688',1,'']]],
  ['how_20it_20works_31',['How It Works',['../md_docs_2features_2anthropic-features.html#autotoc_md1130',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1137',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1141',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1146',1,'How It Works'],['../md_docs_2xp__voting.html#autotoc_md1935',1,'How It Works']]],
  ['how_20to_20re_20run_32',['How to re-run',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1383',1,'']]],
  ['how_20to_20use_33',['How to Use',['../md_llm__prep_2codebase__overview.html#autotoc_md1971',1,'']]],
  ['huggingface_20llama_34',['HuggingFace Llama',['../md_docs_2api-providers.html#autotoc_md82',1,'HuggingFace (Llama)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md545',1,'HuggingFace (Llama)']]],
  ['humans_35',['Tips for Humans',['../md_docs_2references_2quick-reference.html#autotoc_md1576',1,'']]],
  ['hybrid_20linear_20exponential_36',['Progression Curve (Hybrid Linear/Exponential)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md456',1,'']]]
];
