var searchData=
[
  ['o_0',['Disk I/O',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1794',1,'']]],
  ['of_20all_20implemented_20features_1',['Summary of All Implemented Features',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md505',1,'']]],
  ['of_20archive_2',['Purpose of Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md964',1,'']]],
  ['of_20changes_3',['Summary of Changes',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md194',1,'']]],
  ['of_20code_4',['Total Lines of Code',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1633',1,'']]],
  ['of_20command_20–_20escalate_20properly_5',['3. Chain of Command – Escalate Properly',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md464',1,'']]],
  ['of_20contents_6',['of Contents',['../md_docs_2api-providers.html#autotoc_md63',1,'Table of Contents'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md412',1,'Table of Contents'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md533',1,'Table of Contents']]],
  ['of_20duplicate_20execution_20before_20fix_7',['Example of Duplicate Execution (Before Fix)',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md250',1,'']]],
  ['of_20fixes_8',['Before/After Comparison of Fixes',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['of_20integration_9',['Proof of Integration',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1345',1,'']]],
  ['of_20sensitive_20data_10',['Finding #5: Logging of Sensitive Data',['../md_docs_2workshop_2security-audit.html#autotoc_md1869',1,'']]],
  ['of_20the_20problem_11',['Evidence of the Problem',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md119',1,'']]],
  ['off_12',['Off',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md862',1,'Sign-Off'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md951',1,'Validation Sign-Off']]],
  ['office_20vision_20—_20alignment_20assessment_13',['The &quot;Office&quot; Vision — Alignment Assessment',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md998',1,'']]],
  ['office_20vision_20and_20sri_14',['The &quot;Office&quot; Vision and SRI',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1702',1,'']]],
  ['ollama_15',['Ollama',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1559',1,'Enable Ollama'],['../md_README.html#autotoc_md2031',1,'Meta Llama (via Ollama)'],['../md_docs_2PROOF__OLLAMA__DEMO.html',1,'PROOF: AXE Cognitive Architecture Working with Ollama']]],
  ['ollama_16',['Manual Testing (Requires bubblewrap + ollama)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1925',1,'']]],
  ['ollama_20batch_20mode_20test_20results_17',['Ollama Batch Mode Test Results',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html',1,'']]],
  ['ollama_20integration_18',['Ollama Integration',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1101',1,'']]],
  ['ollama_20integration_20guide_19',['Ollama Integration Guide',['../md_docs_2ollama-guide.html',1,'']]],
  ['ollama_20integration_20local_20models_20',['Ollama Integration (Local Models)',['../md_ARCHITECTURE.html#autotoc_md58',1,'']]],
  ['ollama_20integration_20test_21',['Ollama Integration Test',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1358',1,'']]],
  ['ollama_20integration_20test_20results_22',['Ollama Integration Test Results',['../md_docs_2OLLAMA__TEST__RESULTS.html',1,'']]],
  ['ollama_20model_20selection_20and_20supervisor_20role_23',['Ollama Model Selection and Supervisor Role',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md976',1,'']]],
  ['ollama_20models_24',['With Local Ollama Models',['../md_README.html#autotoc_md2021',1,'']]],
  ['ollama_20provider_20local_20llms_25',['Ollama Provider (Local LLMs)',['../md_docs_2features_2configuration.html#autotoc_md1180',1,'']]],
  ['ollama_20running_20in_20background_26',['1. Ollama Running in Background',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1516',1,'']]],
  ['ollama_20setup_27',['Ollama Setup',['../md_docs_2TESTING.html#autotoc_md1734',1,'']]],
  ['ollama_20setup_20verification_20✅_28',['Test 1: Ollama Setup Verification ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1464',1,'']]],
  ['on_20exit_29',['2. Session Persistence — Autosave on Exit',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md984',1,'']]],
  ['on_20failure_30',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md2073',1,'']]],
  ['on_20security_20relevant_20output_31',['2. Focus on Security-Relevant Output',['../md_skills_2claude__build.html#autotoc_md2133',1,'']]],
  ['on_20workspace_20bug_32',['Note on Workspace Bug',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1103',1,'']]],
  ['one_20present_3a_20use_20whichever_20exists_33',['Only one present: use whichever exists',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md329',1,'']]],
  ['one_20response_34',['4. Multiple Files in One Response',['../md_docs_2features_2write-blocks.html#autotoc_md1285',1,'']]],
  ['online_20no_20installation_20required_35',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1117',1,'']]],
  ['only_36',['Quick security scan (high severity only)',['../md_skills_2claude__build.html#autotoc_md2117',1,'']]],
  ['only_20communication_37',['Local-Only Communication',['../md_docs_2socket__interface.html#autotoc_md1649',1,'']]],
  ['only_20high_20severity_20findings_38',['Good: Only high-severity findings',['../md_skills_2claude__build.html#autotoc_md2135',1,'']]],
  ['only_20one_20present_3a_20use_20whichever_20exists_39',['Only one present: use whichever exists',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md329',1,'']]],
  ['only_20security_20warnings_40',['Good: Only security warnings',['../md_skills_2claude__build.html#autotoc_md2134',1,'']]],
  ['openai_20compatible_20api_41',['Usage - OpenAI-Compatible API',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md548',1,'']]],
  ['openai_20gpt_42',['OpenAI GPT',['../md_docs_2api-providers.html#autotoc_md73',1,'OpenAI (GPT)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md552',1,'OpenAI (GPT)'],['../md_README.html#autotoc_md2029',1,'OpenAI (GPT)']]],
  ['openai_20sdk_43',['OpenAI SDK',['../md_docs_2api-providers.html#autotoc_md97',1,'Python Example (OpenAI SDK)'],['../md_docs_2api-providers.html#autotoc_md106',1,'Python Example (OpenAI SDK)']]],
  ['operating_20system_20support_44',['Operating System Support',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1787',1,'']]],
  ['operations_45',['Operations',['../md_docs_2features_2parsers.html#autotoc_md1232',1,'Example 3: Mixed Operations'],['../md_docs_2workshop_2security-audit.html#autotoc_md1862',1,'Issue #4: Race Condition in Database Operations'],['../md_docs_2features_2parsers.html#autotoc_md1221',1,'Supported Operations']]],
  ['operator_20support_20implementation_20summary_46',['Shell Operator Support Implementation Summary',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html',1,'']]],
  ['opportunities_47',['Future Optimization Opportunities',['../md_docs_2workshop_2benchmarks.html#autotoc_md1772',1,'']]],
  ['optimization_48',['Optimization',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md676',1,'']]],
  ['optimization_20opportunities_49',['Future Optimization Opportunities',['../md_docs_2workshop_2benchmarks.html#autotoc_md1772',1,'']]],
  ['optimization_20savings_50',['Section 4 – Token Optimization / Savings',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1391',1,'']]],
  ['optimization_20strategies_51',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md55',1,'']]],
  ['optimizations_20implementation_20summary_52',['Anthropic Claude-Specific Optimizations - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['option_53',['Command Line Option',['../md_docs_2features_2github-agent-integration.html#autotoc_md1201',1,'']]],
  ['option_20a_3a_20standard_20venv_20pip_54',['Option A: Standard venv + pip',['../md_README.html#autotoc_md2000',1,'']]],
  ['option_20b_3a_20using_20mkpyenv_20tool_55',['Option B: Using mkpyenv tool',['../md_README.html#autotoc_md2001',1,'']]],
  ['optional_20✅_56',['4. Files API (Beta, Optional) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md147',1,'']]],
  ['optional_20future_57',['Optional (Future)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md860',1,'']]],
  ['optional_3a_20add_20more_20diet_20etc_20if_20tools_20expand_58',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md2162',1,'']]],
  ['options_59',['Options',['../md_README.html#autotoc_md2006',1,'Command-Line Options'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md524',1,'Configuration Options']]],
  ['or_20confused_60',['&quot;Agent stuck or confused&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1583',1,'']]],
  ['order_61',['Execution Order',['../md_docs_2subsumption__architecture.html#autotoc_md1715',1,'']]],
  ['order_62',['Execute each block in order',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md399',1,'']]],
  ['organization_63',['Archive Organization',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md965',1,'']]],
  ['original_64',['Markdown Format (Original)',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md804',1,'']]],
  ['original_20test_20suite_20test_5ftool_5frunner_20py_65',['Original Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner.py&lt;/span&gt;)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md704',1,'']]],
  ['original_20version_20_3a_66',['Execution (original version):',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md351',1,'']]],
  ['other_20blocks_67',['Integration with Other Blocks',['../md_docs_2features_2write-blocks.html#autotoc_md1286',1,'']]],
  ['other_20systems_68',['Integration with Other Systems',['../md_docs_2conflict__resolution__examples.html#autotoc_md1078',1,'']]],
  ['other_20test_20modules_69',['Other test modules',['../md_docs_2TESTING.html#autotoc_md1743',1,'']]],
  ['others_70',['Others',['../md_README.html#autotoc_md2032',1,'']]],
  ['out_71',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md255',1,'']]],
  ['output_72',['Output',['../md_skills_2build.html#autotoc_md2078',1,'❌ Don&apos;t Remove All Output'],['../md_skills_2claude__build.html#autotoc_md2133',1,'2. Focus on Security-Relevant Output'],['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md988',1,'4. Supervision Behaviour — XP Rewards for Good Output'],['../md_docs_2features_2anthropic-features.html#autotoc_md1133',1,'Example Output'],['../md_docs_2privilege__mapping.html#autotoc_md1486',1,'Example Prompt Output'],['../md_docs_2features_2configuration.html#autotoc_md1169',1,'Example Startup Output'],['../md_docs_2SRI__AGENT__DISCUSSION.html',1,'SRI Agent Discussion — Live Session Output'],['../md_AGENTS.html#autotoc_md36',1,'When to Use Verbose Output']]],
  ['output_20actual_20runtime_20logs_73',['Demo Output (Actual Runtime Logs)',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1514',1,'']]],
  ['output_20tokens_20implementation_20summary_74',['Dynamic Max Output Tokens Implementation Summary',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html',1,'']]],
  ['output_3a_75',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md2112',1,'']]],
  ['overall_20assessment_76',['Overall Assessment',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md868',1,'']]],
  ['overall_20results_77',['Overall Results',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1409',1,'']]],
  ['overall_20score_3a_209_204_2010_78',['Overall Score: 9.4/10',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md941',1,'']]],
  ['overall_20test_20statistics_79',['Overall Test Statistics',['../md_docs_2workshop_2test-results.html#autotoc_md1893',1,'']]],
  ['overhead_80',['Overhead',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md675',1,'']]],
  ['override_81',['Override',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1558',1,'Agent Override'],['../md_docs_2subsumption__architecture.html#autotoc_md1723',1,'Example 2: Emergency Override']]],
  ['override_20best_20practices_82',['Override Best Practices',['../md_docs_2features_2configuration.html#autotoc_md1177',1,'']]],
  ['overrides_83',['Overrides',['../md_docs_2features_2configuration.html#autotoc_md1175',1,'Agent Overrides'],['../md_docs_2features_2configuration.html#autotoc_md1176',1,'Use Cases for Overrides']]],
  ['overview_84',['Overview',['../md_MISSION.html#autotoc_md1983',1,'Architecture Overview'],['../md_docs_2features_2sandbox.html#autotoc_md1265',1,'Component Overview'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md141',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md196',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md274',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md298',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md507',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md605',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md611',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md646',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md685',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md716',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md742',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md769',1,'Overview'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md786',1,'Overview'],['../md_docs_2codex-implementation.html#autotoc_md1003',1,'Overview'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1024',1,'Overview'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1083',1,'Overview'],['../md_docs_2features_2anthropic-features.html#autotoc_md1126',1,'Overview'],['../md_docs_2features_2configuration.html#autotoc_md1162',1,'Overview'],['../md_docs_2features_2github-agent-integration.html#autotoc_md1195',1,'Overview'],['../md_docs_2features_2parsers.html#autotoc_md1213',1,'Overview'],['../md_docs_2features_2sandbox.html#autotoc_md1246',1,'Overview'],['../md_docs_2features_2write-blocks.html#autotoc_md1278',1,'Overview'],['../md_docs_2global-workspace.html#autotoc_md1301',1,'Overview'],['../md_docs_2ollama-guide.html#autotoc_md1435',1,'Overview'],['../md_docs_2privilege__mapping.html#autotoc_md1472',1,'Overview'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1610',1,'Overview'],['../md_docs_2socket__interface.html#autotoc_md1637',1,'Overview'],['../md_docs_2subsumption__architecture.html#autotoc_md1707',1,'Overview'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1810',1,'Overview'],['../md_docs_2xp__voting.html#autotoc_md1934',1,'Overview'],['../md_skills_2build.html#autotoc_md2057',1,'Overview'],['../md_skills_2claude__build.html#autotoc_md2099',1,'Overview'],['../md_AGENTS.html#autotoc_md18',1,'Project Overview'],['../md_ARCHITECTURE.html#autotoc_md48',1,'System Overview'],['../md_docs_2TESTING.html#autotoc_md1741',1,'Test Suite Overview'],['../md_docs_2workshop_2test-results.html#autotoc_md1885',1,'Test Suite Overview']]],
  ['overview_20—_202026_2003_2017_85',['LLM-Ready Codebase Overview — 2026-03-17',['../md_llm__prep_2codebase__overview.html',1,'']]]
];
