var searchData=
[
  ['ui_20✅_0',['1. Token Usage Tracking UI ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md423',1,'']]],
  ['unit_20test_20results_20test_5fworkshop_20py_1',['Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1454',1,'']]],
  ['unit_20tests_2',['Unit Tests',['../md_PR23__VALIDATION__REPORT.html#autotoc_md776',1,'Test File 1: Unit Tests'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1491',1,'Unit Tests']]],
  ['unit_20tests_3',['Unit tests',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1520',1,'']]],
  ['unit_20tests_4',['Run all unit tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md468',1,'']]],
  ['unit_20tests_20created_5',['Unit Tests Created',['../md_FIXES__SUMMARY.html#autotoc_md374',1,'']]],
  ['unit_20tests_20passed_6',['✅ Unit Tests Passed',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md433',1,'']]],
  ['unit_20tests_20test_5fdatabase_5flocation_20py_7',['Unit Tests (&lt;span class=&quot;tt&quot;&gt;test_database_location.py&lt;/span&gt;)',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md229',1,'']]],
  ['unlzexe_20first_20very_20common_8',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md1268',1,'']]],
  ['unpackers_9',['DOS EXE Unpackers',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1339',1,'']]],
  ['up_20triggers_10',['Wake-up Triggers',['../md_IMPROVEMENTS__FINAL.html#autotoc_md480',1,'']]],
  ['update_20imports_20✅_11',['Phase 3: Update Imports ✅',['../md_REFACTORING__NOTES.html#autotoc_md1005',1,'']]],
  ['updated_20agentdatabase_20_5f_5finit_5f_5f_12',['2. Updated &lt;span class=&quot;tt&quot;&gt;AgentDatabase.__init__()&lt;/span&gt;',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md225',1,'']]],
  ['updated_20axe_20yaml_20build_20guidelines_20for_20all_20agents_13',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1142',1,'']]],
  ['updated_20function_20signatures_14',['3. Updated Function Signatures',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md226',1,'']]],
  ['updated_20functions_15',['Updated Functions',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md671',1,'']]],
  ['updated_20is_5ftool_5fallowed_20cmd_3a_20str_20lines_201460_201542_16',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1117',1,'']]],
  ['updated_20run_20cmd_3a_20str_20lines_201544_201629_17',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1118',1,'']]],
  ['updated_20tests_18',['Updated Tests',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md25',1,'']]],
  ['updates_19',['Updates',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1298',1,'5. Configuration Updates'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1300',1,'&lt;span class=&quot;tt&quot;&gt;axe.yaml&lt;/span&gt; Updates'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1299',1,'&lt;span class=&quot;tt&quot;&gt;models.yaml&lt;/span&gt; Updates'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md231',1,'Documentation Updates'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md451',1,'Documentation Updates']]],
  ['updating_20diagrams_20',['Updating Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md289',1,'']]],
  ['upgrades_21',['Key Upgrades',['../md_skills_2cpp__modernization__expert.html#autotoc_md1262',1,'']]],
  ['usage_22',['Usage',['../md_README.html#autotoc_md925',1,'Advanced Usage'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md294',1,'Agent Usage'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md260',1,'API Usage'],['../md_IMPROVEMENTS__README.html#autotoc_md559',1,'Checking Resource Usage'],['../md_workshop__dependency__validation.html#autotoc_md1383',1,'CPU Usage'],['../md_workshop__dependency__validation.html#autotoc_md1382',1,'Memory Usage'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md592',1,'Programmatic Usage'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md265',1,'Usage'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md293',1,'Usage'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md589',1,'Usage'],['../md_MODELS__FINAL.html#autotoc_md624',1,'Usage'],['../md_MODELS__FINAL.html#autotoc_md637',1,'Usage'],['../md_MODELS__FINAL.html#autotoc_md650',1,'Usage'],['../md_README.html#autotoc_md940',1,'Usage'],['../md_README.html#autotoc_md946',1,'Usage']]],
  ['usage_20automatic_23',['Basic Usage (Automatic)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1311',1,'']]],
  ['usage_20commands_20new_24',['Token Usage Commands (NEW!)',['../md_README.html#autotoc_md902',1,'']]],
  ['usage_20examples_25',['Usage Examples',['../md_IMPROVEMENTS__README.html#autotoc_md556',1,'Usage Examples'],['../md_MODELS__FINAL.html#autotoc_md655',1,'Usage Examples'],['../md_README.html#autotoc_md892',1,'Usage Examples'],['../md_SANDBOX.html#autotoc_md1036',1,'Usage Examples'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1156',1,'Usage Examples'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1310',1,'Usage Examples'],['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1341',1,'Usage Examples']]],
  ['usage_20guidelines_26',['Usage Guidelines',['../md_MISSION.html#autotoc_md608',1,'']]],
  ['usage_20image_20generation_27',['Usage - Image Generation',['../md_MODELS__FINAL.html#autotoc_md644',1,'']]],
  ['usage_20openai_20compatible_20api_28',['Usage - OpenAI-Compatible API',['../md_MODELS__FINAL.html#autotoc_md630',1,'']]],
  ['usage_20scenarios_29',['Usage Scenarios',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1082',1,'']]],
  ['usage_20statistics_30',['View Usage Statistics',['../md_README.html#autotoc_md967',1,'']]],
  ['usage_20text_20generation_31',['Usage - Text Generation',['../md_MODELS__FINAL.html#autotoc_md643',1,'']]],
  ['usage_20tracking_32',['Token Usage Tracking',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md443',1,'']]],
  ['usage_20tracking_20ui_20✅_33',['1. Token Usage Tracking UI ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md423',1,'']]],
  ['usage_20transformers_20local_34',['Usage - Transformers (Local)',['../md_MODELS__FINAL.html#autotoc_md631',1,'']]],
  ['use_35',['How to Use',['../md_llm__prep_2codebase__overview.html#autotoc_md575',1,'']]],
  ['use_20cases_20enabled_36',['Use Cases Enabled',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md36',1,'']]],
  ['use_20each_20agent_37',['When to Use Each Agent',['../md_README.html#autotoc_md913',1,'']]],
  ['use_20quiet_20flags_20in_20ci_20cd_20security_20checks_38',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md1246',1,'']]],
  ['use_20silent_20flags_20first_39',['1. Always Use Silent Flags First',['../md_skills_2build.html#autotoc_md1181',1,'']]],
  ['use_20verbose_20by_20default_40',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md1189',1,'']]],
  ['use_20verbose_20output_41',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md59',1,'']]],
  ['use_20whichever_20exists_42',['Only one present: use whichever exists',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md392',1,'']]],
  ['user_20guide_43',['WRITE Block Functionality - User Guide',['../md_WRITE__BLOCKS__GUIDE.html',1,'']]],
  ['user_3a_44',['For User:',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md454',1,'']]],
  ['users_45',['For Users',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md99',1,'']]],
  ['utilization_20trends_46',['Resource Utilization Trends',['../md_workshop__benchmarks.html#autotoc_md1360',1,'']]],
  ['utils_2033_20lines_47',['&lt;span class=&quot;tt&quot;&gt;utils/&lt;/span&gt; (33 lines)',['../md_REFACTORING__NOTES.html#autotoc_md998',1,'']]]
];
