var searchData=
[
  ['s_20favorite_0',['1. Bash XML Tags (Claude&apos;s Favorite)',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md689',1,'']]],
  ['s_20natural_20format_1',['Example 1: Claude&apos;s Natural Format',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md683',1,'']]],
  ['s_20new_2',['What&apos;s New?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1515',1,'']]],
  ['sacred_3',['1. Mission First – The Project / Task Is Sacred',['../md_IMPROVEMENTS__FINAL.html#autotoc_md525',1,'']]],
  ['safe_20commands_20for_20agents_4',['Safe Commands for Agents',['../md_IMPROVEMENTS__FINAL.html#autotoc_md532',1,'']]],
  ['safe_20defaults_20✓_5',['4. Safe Defaults ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md350',1,'']]],
  ['safety_6',['Safety',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md588',1,'']]],
  ['safety_2050_20lines_7',['&lt;span class=&quot;tt&quot;&gt;safety/&lt;/span&gt; (50 lines)',['../md_REFACTORING__NOTES.html#autotoc_md1001',1,'']]],
  ['safety_20considerations_8',['Safety Considerations',['../md_workshop__quick__reference.html#autotoc_md1415',1,'']]],
  ['safety_20features_9',['Safety Features',['../md_IMPROVEMENTS__FINAL.html#autotoc_md477',1,'Core Safety Features'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md292',1,'Safety Features']]],
  ['safety_20guarantees_10',['Safety Guarantees',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md302',1,'']]],
  ['same_20day_11',['Immediate (Same Day)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md736',1,'']]],
  ['sandbox_12',['Sandbox',['../md_SANDBOX.html#autotoc_md1039',1,'Example 3: Network-Isolated Sandbox'],['../md_SANDBOX.html#autotoc_md1049',1,'From Whitelist to Sandbox']]],
  ['sandbox_13',['&quot;Permission denied&quot; errors inside sandbox',['../md_SANDBOX.html#autotoc_md1054',1,'']]],
  ['sandbox_20doesn_20t_20protect_20by_20design_14',['What Sandbox Doesn&apos;t Protect (by design)',['../md_SANDBOX.html#autotoc_md1042',1,'']]],
  ['sandbox_20execution_20error_3a_15',['&quot;Sandbox execution error: ...&quot;',['../md_SANDBOX.html#autotoc_md1052',1,'']]],
  ['sandbox_20implementation_20summary_16',['Bubblewrap Sandbox Implementation - Summary',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['sandbox_20mode_17',['Sandbox Mode',['../md_SANDBOX.html#autotoc_md1034',1,'Enabling Sandbox Mode'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1071',1,'Enabling Sandbox Mode'],['../md_SANDBOX.html#autotoc_md1037',1,'Example 1: Default Sandbox Mode']]],
  ['sandbox_20mode_18',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['sandbox_20protects_19',['What Sandbox Protects',['../md_SANDBOX.html#autotoc_md1041',1,'']]],
  ['sandbox_20security_20model_20',['Bubblewrap Sandbox Security Model',['../md_SANDBOX.html',1,'']]],
  ['sandbox_20with_20blacklist_21',['Example 2: Restricted Sandbox with Blacklist',['../md_SANDBOX.html#autotoc_md1038',1,'']]],
  ['sanitization_22',['sanitization',['../md_FIXES__SUMMARY.html#autotoc_md370',1,'READ block sanitization'],['../md_FIXES__SUMMARY.html#autotoc_md371',1,'WRITE block sanitization']]],
  ['sanitize_20filename_3a_20strip_20trailing_20backticks_20that_20may_20be_20included_20by_20accident_23',['Sanitize filename: strip trailing backticks that may be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['save_20✅_24',['2. Session Resume/Save ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md424',1,'']]],
  ['saving_20optimizations_20new_25',['Token-Saving Optimizations (NEW!)',['../md_README.html#autotoc_md907',1,'']]],
  ['savings_26',['Example Workflow Savings',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md270',1,'']]],
  ['savings_20✅_27',['1. Prompt Caching (90% Token Savings) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md74',1,'']]],
  ['savings_20estimates_28',['Savings Estimates',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1154',1,'Token Savings Estimates'],['../md_skills_2build.html#autotoc_md1168',1,'Token Savings Estimates']]],
  ['savings_20example_29',['Token Savings Example',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md249',1,'']]],
  ['savings_20in_20security_20audits_30',['Token Savings in Security Audits',['../md_skills_2claude__build.html#autotoc_md1239',1,'']]],
  ['saw_20taint_20analysis_31',['Saw Taint Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md751',1,'✅ VALIDATED - Saw (Taint Analysis)'],['../md_README.html#autotoc_md962',1,'Saw - Taint Analysis'],['../md_workshop__quick__reference.html#autotoc_md1403',1,'Saw - Taint Analysis']]],
  ['saw_20taint_20analysis_20benchmarks_32',['Saw - Taint Analysis Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1349',1,'']]],
  ['scale_20analysis_33',['Project-Scale Analysis',['../md_workshop__benchmarks.html#autotoc_md1353',1,'']]],
  ['scan_34',['Scan',['../md_workshop__dependency__validation.html#autotoc_md1386',1,'Dependency Vulnerability Scan'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md675',1,'Security Scan'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md716',1,'Security Scan']]],
  ['scan_20high_20severity_20only_35',['Quick security scan (high severity only)',['../md_skills_2claude__build.html#autotoc_md1226',1,'']]],
  ['scan_20with_20minimal_20noise_36',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md1248',1,'']]],
  ['scan_3a_37',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md1227',1,'']]],
  ['scanner_38',['Flawfinder (C/C++ Security Scanner)',['../md_skills_2claude__build.html#autotoc_md1225',1,'']]],
  ['scenario_201_3a_20development_20workflow_39',['Scenario 1: Development Workflow',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1083',1,'']]],
  ['scenario_202_3a_20code_20analysis_40',['Scenario 2: Code Analysis',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1084',1,'']]],
  ['scenario_203_3a_20network_20isolated_41',['Scenario 3: Network Isolated',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1085',1,'']]],
  ['scenario_204_3a_20legacy_20mode_42',['Scenario 4: Legacy Mode',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1086',1,'']]],
  ['scenarios_43',['Scenarios',['../md_QUICK__REFERENCE.html#autotoc_md856',1,'Common Scenarios'],['../md_tests_2MISSION.html#autotoc_md1337',1,'Test Scenarios'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1082',1,'Usage Scenarios']]],
  ['scenarios_20executed_44',['Test Scenarios Executed',['../md_workshop__security__audit.html#autotoc_md1439',1,'']]],
  ['schema_45',['Schema',['../md_PR23__VALIDATION__REPORT.html#autotoc_md756',1,'✅ VALIDATED - Database Schema'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md509',1,'SQLite Schema']]],
  ['scons_46',['SCons',['../md_skills_2build.html#autotoc_md1177',1,'']]],
  ['scope_47',['Audit Scope',['../md_workshop__security__audit.html#autotoc_md1419',1,'']]],
  ['score_3a_209_204_2010_48',['Overall Score: 9.4/10',['../md_PR23__VALIDATION__REPORT.html#autotoc_md819',1,'']]],
  ['script_49',['2. Python Script',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1483',1,'']]],
  ['script_20demo_5fskills_5fsystem_20py_50',['8. Demonstration Script (&lt;span class=&quot;tt&quot;&gt;demo_skills_system.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1303',1,'']]],
  ['sdk_51',['SDK',['../md_API__PROVIDERS.html#autotoc_md139',1,'Python Example (OpenAI SDK)'],['../md_API__PROVIDERS.html#autotoc_md148',1,'Python Example (OpenAI SDK)']]],
  ['sdk_20error_20fixed_20✓_52',['1. Anthropic SDK Error Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md347',1,'']]],
  ['secrets_20verified_53',['No Hardcoded Secrets - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md786',1,'']]],
  ['security_54',['✅ Security',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md439',1,'']]],
  ['security_2010_2010_55',['🔒 Security (10/10)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md703',1,'']]],
  ['security_20analysis_56',['Security Analysis',['../md_workshop__security__audit.html#autotoc_md1435',1,'Dependency Security Analysis'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md28',1,'Security Analysis'],['../md_FIXES__SUMMARY.html#autotoc_md376',1,'Security Analysis']]],
  ['security_20and_20permissions_57',['Security and Permissions',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1487',1,'']]],
  ['security_20audit_58',['Security Audit',['../md_PR23__VALIDATION__REPORT.html#autotoc_md770',1,'Document 3: Security Audit'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1158',1,'Example 2: Claude Security Audit'],['../md_workshop__security__audit.html',1,'Workshop Tools Security Audit']]],
  ['security_20audit_20workflow_59',['Real-World Example: Security Audit Workflow',['../md_README.html#autotoc_md972',1,'']]],
  ['security_20audit_20workflow_20example_60',['Security Audit Workflow Example',['../md_skills_2claude__build.html#autotoc_md1228',1,'']]],
  ['security_20auditing_20workflow_61',['Security Auditing Workflow',['../md_skills_2claude__build.html#autotoc_md1209',1,'']]],
  ['security_20audits_62',['Security Audits',['../md_skills_2claude__build.html#autotoc_md1240',1,'Best Practices for Security Audits'],['../md_skills_2claude__build.html#autotoc_md1239',1,'Token Savings in Security Audits']]],
  ['security_20benefits_63',['Security Benefits',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1072',1,'']]],
  ['security_20best_20practices_64',['Security &amp;amp; Best Practices',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md92',1,'']]],
  ['security_20boundaries_65',['Security Boundaries',['../md_SANDBOX.html#autotoc_md1040',1,'']]],
  ['security_20build_20patterns_66',['Common Security Build Patterns',['../md_skills_2claude__build.html#autotoc_md1253',1,'']]],
  ['security_20builds_67',['Silent Security Builds',['../md_skills_2claude__build.html#autotoc_md1210',1,'']]],
  ['security_20checks_68',['4. Use Quiet Flags in CI/CD Security Checks',['../md_skills_2claude__build.html#autotoc_md1246',1,'']]],
  ['security_20considerations_69',['Security Considerations',['../md_AGENTS.html#autotoc_md66',1,'Security Considerations'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md93',1,'Security Considerations'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md306',1,'Security Considerations'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md358',1,'Security Considerations'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md417',1,'Security Considerations']]],
  ['security_20flags_70',['Configure with security flags',['../md_skills_2claude__build.html#autotoc_md1230',1,'']]],
  ['security_20focused_20agent_201_20agent_71',['Security-Focused Agent (1 agent)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1144',1,'']]],
  ['security_20focused_20build_20skill_72',['Claude Security-Focused Build Skill',['../md_skills_2claude__build.html',1,'']]],
  ['security_20issues_73',['Known Security Issues',['../md_workshop__dependency__validation.html#autotoc_md1387',1,'']]],
  ['security_20issues_74',['Flawfinder for security issues',['../md_skills_2claude__build.html#autotoc_md1234',1,'']]],
  ['security_20maintained_75',['Security Maintained',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1131',1,'']]],
  ['security_20maintained_20_3a_76',['✅ Still Blocked (Security Maintained):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md29',1,'']]],
  ['security_20mechanism_77',['Security Mechanism',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md32',1,'']]],
  ['security_20model_78',['Security Model',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1064',1,'1. Default-Allow Security Model'],['../md_SANDBOX.html',1,'Bubblewrap Sandbox Security Model']]],
  ['security_20recommendations_79',['Security Recommendations',['../md_workshop__security__audit.html#autotoc_md1437',1,'']]],
  ['security_20relevant_20output_80',['2. Focus on Security-Relevant Output',['../md_skills_2claude__build.html#autotoc_md1242',1,'']]],
  ['security_20report_81',['Security Report',['../md_SECURITY__REPORT.html',1,'AXE Project Security Report'],['../md_skills_2claude__build.html#autotoc_md1238',1,'Phase 4: Security Report']]],
  ['security_20scan_82',['Security Scan',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md675',1,'Security Scan'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md716',1,'Security Scan']]],
  ['security_20scan_20high_20severity_20only_83',['Quick security scan (high severity only)',['../md_skills_2claude__build.html#autotoc_md1226',1,'']]],
  ['security_20scan_20with_20minimal_20noise_84',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md1248',1,'']]],
  ['security_20scanner_85',['Flawfinder (C/C++ Security Scanner)',['../md_skills_2claude__build.html#autotoc_md1225',1,'']]],
  ['security_20specific_20tools_86',['Security-Specific Tools',['../md_skills_2claude__build.html#autotoc_md1212',1,'']]],
  ['security_20standards_20compliance_87',['Security Standards Compliance',['../md_workshop__security__audit.html#autotoc_md1442',1,'']]],
  ['security_20test_20results_20test_5fworkshop_5fsecurity_20py_88',['Security Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_security.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1457',1,'']]],
  ['security_20tool_20chain_20silent_89',['Pattern 2: Security Tool Chain (Silent)',['../md_skills_2claude__build.html#autotoc_md1255',1,'']]],
  ['security_20tool_20quick_20reference_90',['Security Tool Quick Reference',['../md_skills_2claude__build.html#autotoc_md1249',1,'']]],
  ['security_20tools_20quietly_91',['5. Combine Multiple Security Tools Quietly',['../md_skills_2claude__build.html#autotoc_md1247',1,'']]],
  ['security_20validation_92',['Security Validation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md785',1,'Part 3: Security Validation'],['../md_workshop__dependency__validation.html#autotoc_md1385',1,'Security Validation']]],
  ['security_20warnings_93',['Good: Only security warnings',['../md_skills_2claude__build.html#autotoc_md1243',1,'']]],
  ['see_94',['What Agents See',['../md_QUICK__REFERENCE.html#autotoc_md855',1,'']]],
  ['selection_20guide_95',['Model Selection Guide',['../md_API__PROVIDERS.html#autotoc_md154',1,'']]],
  ['sensitive_20data_96',['Finding #5: Logging of Sensitive Data',['../md_workshop__security__audit.html#autotoc_md1434',1,'']]],
  ['serialization_97',['json (Data Serialization)',['../md_workshop__dependency__validation.html#autotoc_md1373',1,'']]],
  ['session_98',['Session',['../md_QUICK__REFERENCE.html#autotoc_md853',1,'During Session'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md304',1,'Example Session'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md539',1,'Starting a Session'],['../md_QUICK__REFERENCE.html#autotoc_md844',1,'Starting a Session'],['../md_QUICK__REFERENCE.html#autotoc_md852',1,'Starting a Session']]],
  ['session_20commands_99',['Agent Session Commands',['../md_IMPROVEMENTS__FINAL.html#autotoc_md538',1,'']]],
  ['session_20management_100',['Session Management',['../md_REFACTORING__NOTES.html#autotoc_md1020',1,'PR #3: Extract Session Management'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md444',1,'Session Management']]],
  ['session_20management_20new_101',['Session Management (NEW!)',['../md_README.html#autotoc_md903',1,'']]],
  ['session_20notes_102',['Collaborative Session Notes',['../md__8collab__shared.html',1,'']]],
  ['session_20pre_20indexing_103',['3. Collaborative Session Pre-indexing',['../md_README.html#autotoc_md955',1,'']]],
  ['session_20resume_20save_20✅_104',['2. Session Resume/Save ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md424',1,'']]],
  ['session_20rules_105',['Viewing Session Rules',['../md_IMPROVEMENTS__README.html#autotoc_md558',1,'']]],
  ['session_20rules_20guidelines_20✅_106',['Phase 1: Session Rules &amp;amp; Guidelines ✅',['../md_IMPROVEMENTS__README.html#autotoc_md543',1,'']]],
  ['session_20rules_20the_204_20principles_107',['Session Rules (The 4 Principles)',['../md_QUICK__REFERENCE.html#autotoc_md839',1,'']]],
  ['session_20start_20pinned_20message_20_3a_108',['Display at session start (pinned message):',['../md_IMPROVEMENTS__FINAL.html#autotoc_md524',1,'']]],
  ['session_20termination_20bugs_109',['Fix Summary: AXE Session Termination Bugs',['../md_TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['session_20with_20new_20features_110',['Starting a Collaborative Session with New Features',['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'']]],
  ['sessions_111',['New Agent Commands (During Sessions)',['../md_IMPROVEMENTS__README.html#autotoc_md554',1,'']]],
  ['sessions_20new_112',['Autonomous Collaborative Sessions (NEW!)',['../md_README.html#autotoc_md932',1,'']]],
  ['settings_113',['Settings',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md597',1,'llmprep Settings'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md596',1,'Minifier Settings']]],
  ['setup_114',['Setup',['../md_README.html#autotoc_md882',1,'API Keys Setup'],['../md_README.html#autotoc_md879',1,'Clone and Setup'],['../md_MODELS__FINAL.html#autotoc_md618',1,'Environment Setup']]],
  ['setup_20commands_115',['Setup Commands',['../md_IMPROVEMENTS__FINAL.html#autotoc_md495',1,'']]],
  ['setup_20silent_116',['Pattern 4: Fuzzing Setup (Silent)',['../md_skills_2claude__build.html#autotoc_md1257',1,'']]],
  ['severity_20findings_117',['Good: Only high-severity findings',['../md_skills_2claude__build.html#autotoc_md1244',1,'']]],
  ['severity_20issues_118',['Severity Issues',['../md_workshop__security__audit.html#autotoc_md1425',1,'Low Severity Issues'],['../md_workshop__security__audit.html#autotoc_md1422',1,'Medium Severity Issues']]],
  ['severity_20levels_119',['3. Document Severity Levels',['../md_skills_2claude__build.html#autotoc_md1245',1,'']]],
  ['severity_20only_120',['Quick security scan (high severity only)',['../md_skills_2claude__build.html#autotoc_md1226',1,'']]],
  ['shared_20view_121',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['shell_20code_20blocks_122',['2. Shell Code Blocks',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md690',1,'']]],
  ['shell_20operator_20support_20implementation_20summary_123',['Shell Operator Support Implementation Summary',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html',1,'']]],
  ['short_20term_20this_20week_124',['Short-Term (This Week)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md737',1,'']]],
  ['sign_20off_125',['Sign Off',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md740',1,'Sign-Off'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md829',1,'Validation Sign-Off']]],
  ['signature_20quick_20check_20if_20all_20trials_20fail_126',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['signatures_127',['3. Updated Function Signatures',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md226',1,'']]],
  ['silence_20means_20success_128',['❌ Don&apos;t Assume Silence Means Success',['../md_skills_2build.html#autotoc_md1188',1,'']]],
  ['silent_129',['Silent',['../md_skills_2claude__build.html#autotoc_md1255',1,'Pattern 2: Security Tool Chain (Silent)'],['../md_skills_2claude__build.html#autotoc_md1256',1,'Pattern 3: Regression Testing (Silent)'],['../md_skills_2claude__build.html#autotoc_md1257',1,'Pattern 4: Fuzzing Setup (Silent)'],['../md_skills_2claude__build.html#autotoc_md1232',1,'Phase 2: Static Analysis (Silent)']]],
  ['silent_130',['silent',['../md_skills_2claude__build.html#autotoc_md1214',1,'Quick check for memory issues (silent)'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1160',1,'Runtime analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md1252',1,'Runtime analysis (silent)'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1159',1,'Static analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md1251',1,'Static analysis (silent)']]],
  ['silent_20build_131',['Silent Build',['../md_skills_2claude__build.html#autotoc_md1254',1,'Pattern 1: Hardening Flags (Silent Build)'],['../md_skills_2claude__build.html#autotoc_md1229',1,'Phase 1: Initial Silent Build']]],
  ['silent_20builds_132',['Why Silent Builds?',['../md_skills_2build.html#autotoc_md1167',1,'']]],
  ['silent_20builds_20feature_20implementation_20summary_133',['Silent Builds Feature - Implementation Summary',['../md_SILENT__BUILDS__IMPLEMENTATION.html',1,'']]],
  ['silent_20builds_20skill_134',['Silent Builds Skill',['../md_skills_2build.html',1,'']]],
  ['silent_20flags_135',['4. Combine Multiple Silent Flags',['../md_skills_2build.html#autotoc_md1184',1,'']]],
  ['silent_20flags_20first_136',['1. Always Use Silent Flags First',['../md_skills_2build.html#autotoc_md1181',1,'']]],
  ['silent_20investigate_20verbose_137',['1. Start Silent, Investigate Verbose',['../md_skills_2claude__build.html#autotoc_md1241',1,'']]],
  ['silent_20security_20builds_138',['Silent Security Builds',['../md_skills_2claude__build.html#autotoc_md1210',1,'']]],
  ['silently_139',['silently',['../md_skills_2build.html#autotoc_md1193',1,'Build silently'],['../md_skills_2claude__build.html#autotoc_md1231',1,'Build silently'],['../md_skills_2claude__build.html#autotoc_md1220',1,'Compile with ASan and run tests silently'],['../md_skills_2build.html#autotoc_md1198',1,'Install dependencies silently'],['../md_skills_2build.html#autotoc_md1199',1,'Run tests silently']]],
  ['silently_20debug_20verbosely_140',['5. Test Silently, Debug Verbosely',['../md_skills_2build.html#autotoc_md1185',1,'']]],
  ['simple_20text_20file_141',['1. Simple Text File',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1482',1,'']]],
  ['simple_20xml_20tags_20like_142',['5. Simple XML tags like &amp;lt;read_file&amp;gt;, &amp;lt;shell&amp;gt;',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md319',1,'']]],
  ['single_20command_143',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['single_20command_20mode_144',['Single Command Mode',['../md_README.html#autotoc_md895',1,'']]],
  ['sink_20enumeration_145',['Sink Enumeration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md752',1,'✅ VALIDATED - Plane (Source/Sink Enumeration)'],['../md_README.html#autotoc_md963',1,'Plane - Source/Sink Enumeration'],['../md_workshop__quick__reference.html#autotoc_md1404',1,'Plane - Source/Sink Enumeration']]],
  ['sink_20enumeration_20benchmarks_146',['Plane - Source/Sink Enumeration Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1352',1,'']]],
  ['size_147',['File Size',['../md_REFACTORING__NOTES.html#autotoc_md1015',1,'']]],
  ['size_20validation_148',['Finding #1: Missing Input Size Validation',['../md_workshop__security__audit.html#autotoc_md1430',1,'']]],
  ['skill_149',['Skill',['../md_skills_2claude__build.html',1,'Claude Security-Focused Build Skill'],['../md_skills_2build.html',1,'Silent Builds Skill']]],
  ['skill_20dataclass_150',['Skill Dataclass',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1306',1,'']]],
  ['skill_20files_151',['3. Domain-Specific Skill Files',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1296',1,'']]],
  ['skill_20loading_152',['Manual Skill Loading',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1312',1,'']]],
  ['skill_20template_153',['Example Skill Template',['../md_AGENTS.html#autotoc_md56',1,'']]],
  ['skills_154',['Creating New Skills',['../md_AGENTS.html#autotoc_md55',1,'']]],
  ['skills_20build_20md_209_204kb_155',['skills/build.md (9.4KB)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1147',1,'']]],
  ['skills_20claude_5fbuild_20md_2011_202kb_156',['skills/claude_build.md (11.2KB)',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1148',1,'']]],
  ['skills_20directory_20and_20files_157',['3. Created Skills Directory and Files',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1146',1,'']]],
  ['skills_20directory_20structure_158',['Skills Directory Structure',['../md_AGENTS.html#autotoc_md54',1,'']]],
  ['skills_20files_159',['Skills Files',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1153',1,'']]],
  ['skills_20manager_20core_20skills_5fmanager_20py_160',['1. Core Skills Manager (&lt;span class=&quot;tt&quot;&gt;core/skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1294',1,'']]],
  ['skills_20manifest_20json_161',['4. Skills Manifest (&lt;span class=&quot;tt&quot;&gt;skills/manifest.json&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1297',1,'']]],
  ['skills_20manifest_20skills_20manifest_20json_162',['4. Skills Manifest (&lt;span class=&quot;tt&quot;&gt;skills/manifest.json&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1297',1,'']]],
  ['skills_20system_163',['Skills System',['../md_AGENTS.html#autotoc_md53',1,'']]],
  ['skills_20system_20implementation_20summary_164',['Agent Skills System Implementation Summary',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['skills_5fmanager_20py_165',['1. Core Skills Manager (&lt;span class=&quot;tt&quot;&gt;core/skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1294',1,'']]],
  ['skillsmanager_20class_20api_166',['SkillsManager Class API',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1305',1,'']]],
  ['skipped_20tests_167',['Skipped Tests',['../md_workshop__test__results.html#autotoc_md1469',1,'']]],
  ['sleep_20quality_20tiers_168',['Sleep Quality Tiers',['../md_IMPROVEMENTS__FINAL.html#autotoc_md479',1,'']]],
  ['sleep_20system_169',['Sleep System',['../md_IMPROVEMENTS__FINAL.html#autotoc_md482',1,'Mandatory Sleep System'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md478',1,'Permission-Based Sleep System']]],
  ['sleep_20system_20✅_170',['Phase 6: Mandatory Sleep System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md549',1,'']]],
  ['slowing_20down_171',['&quot;System slowing down&quot;',['../md_QUICK__REFERENCE.html#autotoc_md860',1,'']]],
  ['snippet_20analysis_172',['Code Snippet Analysis',['../md_workshop__benchmarks.html#autotoc_md1350',1,'']]],
  ['so_20treat_20the_20whole_20block_20as_20a_20single_20command_173',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['solution_174',['Solution',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md21',1,'Solution'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md314',1,'Solution'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1322',1,'Solution'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1327',1,'Solution']]],
  ['solution_20implemented_175',['Solution Implemented',['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md212',1,'Solution Implemented'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md222',1,'Solution Implemented'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md404',1,'Solution Implemented'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1111',1,'Solution Implemented']]],
  ['solved_176',['Solved',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md667',1,'Problem Solved'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1502',1,'Problem Solved']]],
  ['solving_177',['Collaborative Problem Solving',['../md_README.html#autotoc_md935',1,'']]],
  ['source_20code_20minifier_20implementation_20summary_178',['Source Code Minifier Implementation Summary',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['source_20license_20default_179',['Open Source License (Default)',['../md_README.html#autotoc_md985',1,'']]],
  ['source_20sink_20enumeration_180',['Source Sink Enumeration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md752',1,'✅ VALIDATED - Plane (Source/Sink Enumeration)'],['../md_README.html#autotoc_md963',1,'Plane - Source/Sink Enumeration'],['../md_workshop__quick__reference.html#autotoc_md1404',1,'Plane - Source/Sink Enumeration']]],
  ['source_20sink_20enumeration_20benchmarks_181',['Plane - Source/Sink Enumeration Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1352',1,'']]],
  ['sources_182',['XP Sources',['../md_IMPROVEMENTS__FINAL.html#autotoc_md520',1,'']]],
  ['spaces_183',['2. Redirects Without Spaces',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1121',1,'']]],
  ['spawned_20agents_20never_20get_20turns_20✅_184',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['spawning_185',['Dynamic Spawning',['../md_IMPROVEMENTS__FINAL.html#autotoc_md504',1,'']]],
  ['spawning_20✅_186',['Phase 10: Dynamic Spawning ✅',['../md_IMPROVEMENTS__README.html#autotoc_md553',1,'']]],
  ['spawning_20logic_187',['Spawning Logic',['../md_IMPROVEMENTS__FINAL.html#autotoc_md506',1,'']]],
  ['special_20aliases_188',['Special Aliases',['../md_IMPROVEMENTS__FINAL.html#autotoc_md515',1,'']]],
  ['specific_20features_20in_20axe_189',['Anthropic Claude-Specific Features in AXE',['../md_docs_2ANTHROPIC__FEATURES.html',1,'']]],
  ['specific_20optimizations_20implementation_20summary_190',['Anthropic Claude-Specific Optimizations - Implementation Summary',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['specific_20skill_20files_191',['3. Domain-Specific Skill Files',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1296',1,'']]],
  ['specific_20tools_192',['Security-Specific Tools',['../md_skills_2claude__build.html#autotoc_md1212',1,'']]],
  ['sqlite_20schema_193',['SQLite Schema',['../md_IMPROVEMENTS__FINAL.html#autotoc_md509',1,'']]],
  ['sqlite_20storage_20✅_194',['Phase 4: Persistent SQLite Storage ✅',['../md_IMPROVEMENTS__README.html#autotoc_md546',1,'']]],
  ['sqlite3_20database_20engine_195',['sqlite3 (Database Engine)',['../md_workshop__dependency__validation.html#autotoc_md1372',1,'']]],
  ['standalone_20cli_196',['Standalone CLI',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md591',1,'']]],
  ['standard_20compliance_197',['2. AGENTS.md Standard Compliance',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1295',1,'']]],
  ['standard_20library_20dependencies_198',['Standard Library Dependencies',['../md_workshop__dependency__validation.html#autotoc_md1370',1,'']]],
  ['standards_20compliance_199',['Security Standards Compliance',['../md_workshop__security__audit.html#autotoc_md1442',1,'']]],
  ['start_200',['Start',['../md_MODELS__FINAL.html#autotoc_md617',1,'Quick Start'],['../md_README.html#autotoc_md874',1,'Quick Start'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1095',1,'Quick Start']]],
  ['start_20pinned_20message_20_3a_201',['Display at session start (pinned message):',['../md_IMPROVEMENTS__FINAL.html#autotoc_md524',1,'']]],
  ['start_20silent_20investigate_20verbose_202',['1. Start Silent, Investigate Verbose',['../md_skills_2claude__build.html#autotoc_md1241',1,'']]],
  ['started_203',['Getting Started',['../md_MISSION.html#autotoc_md610',1,'']]],
  ['starting_20a_20collaborative_20session_20with_20new_20features_204',['Starting a Collaborative Session with New Features',['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'']]],
  ['starting_20a_20session_205',['Starting a Session',['../md_IMPROVEMENTS__FINAL.html#autotoc_md539',1,'Starting a Session'],['../md_QUICK__REFERENCE.html#autotoc_md844',1,'Starting a Session'],['../md_QUICK__REFERENCE.html#autotoc_md852',1,'Starting a Session']]],
  ['statement_206',['Statement',['../md_MISSION.html#autotoc_md603',1,'Mission Statement'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md18',1,'Problem Statement'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md210',1,'Problem Statement'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md220',1,'Problem Statement'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md401',1,'Problem Statement']]],
  ['statement_20_3a_207',['Previously Failing (from problem statement):',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1133',1,'']]],
  ['static_20analysis_208',['Cppcheck (Static Analysis)',['../md_skills_2claude__build.html#autotoc_md1216',1,'']]],
  ['static_20analysis_20quietly_209',['Run static analysis quietly',['../md_skills_2claude__build.html#autotoc_md1217',1,'']]],
  ['static_20analysis_20silent_210',['Phase 2: Static Analysis (Silent)',['../md_skills_2claude__build.html#autotoc_md1232',1,'']]],
  ['static_20analysis_20silent_211',['Static analysis silent',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1159',1,'Static analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md1251',1,'Static analysis (silent)']]],
  ['static_20analyzer_212',['Clang Static Analyzer',['../md_skills_2claude__build.html#autotoc_md1222',1,'']]],
  ['static_20analyzer_20quietly_213',['Run Clang static analyzer quietly',['../md_skills_2claude__build.html#autotoc_md1223',1,'']]],
  ['statistics_214',['Statistics',['../md_llm__prep_2codebase__overview.html#autotoc_md571',1,'Code Statistics'],['../md_workshop__test__results.html#autotoc_md1458',1,'Overall Test Statistics'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md599',1,'Statistics'],['../md_workshop__quick__reference.html#autotoc_md1408',1,'Statistics'],['../md_README.html#autotoc_md967',1,'View Usage Statistics']]],
  ['statistics_20monitoring_215',['Live Statistics &amp;amp; Monitoring',['../md_README.html#autotoc_md908',1,'']]],
  ['statistics_20with_20cache_20tracking_216',['Token Statistics with Cache Tracking',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md266',1,'']]],
  ['status_217',['Status',['../md_PR23__VALIDATION__REPORT.html#autotoc_md810',1,'Integration Status'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md432',1,'Testing Status'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md446',1,'Workshop Status']]],
  ['status_20discovery_20✅_218',['4. Workshop Tools Status &amp;amp; Discovery ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md426',1,'']]],
  ['status_3a_20✅_20complete_219',['Implementation Status: ✅ COMPLETE',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md72',1,'']]],
  ['steps_220',['Steps',['../md_FIXES__SUMMARY.html#autotoc_md386',1,'Next Steps'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md453',1,'Next Steps'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md600',1,'Next Steps']]],
  ['still_20blocked_20security_20maintained_20_3a_221',['✅ Still Blocked (Security Maintained):',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md29',1,'']]],
  ['storage_222',['Persistent Storage',['../md_IMPROVEMENTS__FINAL.html#autotoc_md508',1,'']]],
  ['storage_20✅_223',['Phase 4: Persistent SQLite Storage ✅',['../md_IMPROVEMENTS__README.html#autotoc_md546',1,'']]],
  ['storage_20✅_20fixed_224',['4. &lt;b&gt;Database/Storage&lt;/b&gt; ✅ Fixed',['../md_SECURITY__REPORT.html#autotoc_md1104',1,'']]],
  ['str_20bool_20lines_201410_201458_225',['5. &lt;span class=&quot;tt&quot;&gt;_needs_shell(cmd: str) -&amp;gt; bool&lt;/span&gt; (Lines 1410-1458)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1116',1,'']]],
  ['str_20lines_201150_201171_226',['2. &lt;span class=&quot;tt&quot;&gt;__init__(config: Config, project_dir: str)&lt;/span&gt; (Lines 1150-1171)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1113',1,'']]],
  ['str_20lines_201173_201287_227',['3. &lt;span class=&quot;tt&quot;&gt;_strip_heredoc_content(cmd: str) -&amp;gt; str&lt;/span&gt; (Lines 1173-1287)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1114',1,'']]],
  ['str_20lines_201289_201408_228',['4. &lt;span class=&quot;tt&quot;&gt;_extract_commands_from_shell(cmd: str) -&amp;gt; List[str]&lt;/span&gt; (Lines 1289-1408)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1115',1,'']]],
  ['str_20lines_201460_201542_229',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1117',1,'']]],
  ['str_20lines_201544_201629_230',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1118',1,'']]],
  ['str_20list_20str_20lines_201289_201408_231',['4. &lt;span class=&quot;tt&quot;&gt;_extract_commands_from_shell(cmd: str) -&amp;gt; List[str]&lt;/span&gt; (Lines 1289-1408)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1115',1,'']]],
  ['str_20str_20lines_201173_201287_232',['3. &lt;span class=&quot;tt&quot;&gt;_strip_heredoc_content(cmd: str) -&amp;gt; str&lt;/span&gt; (Lines 1173-1287)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1114',1,'']]],
  ['strategies_233',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md165',1,'']]],
  ['strategy_234',['Persistence Strategy',['../md_IMPROVEMENTS__README.html#autotoc_md564',1,'']]],
  ['strengths_235',['Key Strengths',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md701',1,'']]],
  ['strip_20trailing_20backticks_20that_20may_20be_20included_20by_20accident_236',['strip trailing backticks that may be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['stripped_20version_20_3a_237',['Validation (internal, stripped version):',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md413',1,'']]],
  ['structure_238',['Structure',['../md_PR23__VALIDATION__REPORT.html#autotoc_md764',1,'✅ VALIDATED - Configuration Structure'],['../md_llm__prep_2codebase__overview.html#autotoc_md570',1,'Directory Structure'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1308',1,'File Structure'],['../md_ARCHITECTURE.html#autotoc_md160',1,'Module Structure'],['../md_REFACTORING__NOTES.html#autotoc_md997',1,'New Module Structure'],['../md_README.html#autotoc_md980',1,'Project Structure'],['../md_AGENTS.html#autotoc_md54',1,'Skills Directory Structure']]],
  ['structure_20✅_239',['Phase 1: Create Directory Structure ✅',['../md_REFACTORING__NOTES.html#autotoc_md1003',1,'']]],
  ['structure_20complete_240',['Module Structure - COMPLETE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md783',1,'']]],
  ['structure_20excellent_241',['Code Structure - EXCELLENT',['../md_PR23__VALIDATION__REPORT.html#autotoc_md794',1,'']]],
  ['stuck_20or_20confused_242',['&quot;Agent stuck or confused&quot;',['../md_QUICK__REFERENCE.html#autotoc_md858',1,'']]],
  ['style_243',['Python Style',['../md_AGENTS.html#autotoc_md50',1,'']]],
  ['style_20curl_20example_244',['Chat-style cURL Example',['../md_API__PROVIDERS.html#autotoc_md130',1,'']]],
  ['subdirectory_245',['3. File in Subdirectory',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1484',1,'']]],
  ['subshells_246',['3. Nested Subshells',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1122',1,'']]],
  ['subshells_20with_20parentheses_247',['1. Subshells with Parentheses',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1120',1,'']]],
  ['success_248',['❌ Don&apos;t Assume Silence Means Success',['../md_skills_2build.html#autotoc_md1188',1,'']]],
  ['success_20criteria_249',['Success Criteria',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md101',1,'Success Criteria'],['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1511',1,'Success Criteria']]],
  ['success_20criteria_20✓_250',['Success Criteria ✓',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1309',1,'']]],
  ['success_20criteria_20all_20met_251',['Success Criteria (All Met)',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1334',1,'']]],
  ['success_20criteria_20met_252',['Success Criteria Met',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md238',1,'Success Criteria Met'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1163',1,'Success Criteria Met']]],
  ['suite_253',['XML TOOL PARSER TEST SUITE',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1504',1,'']]],
  ['suite_254',['Suite',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md408',1,'4. Comprehensive Test Suite'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md774',1,'Claim 6: Test Suite'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md714',1,'Custom Validation Suite'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md715',1,'PR Test Suite'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md832',1,'Validation Test Suite']]],
  ['suite_20execution_20results_255',['Workshop Tools Test Suite Execution Results',['../md_workshop__test__results.html',1,'']]],
  ['suite_20overview_256',['Test Suite Overview',['../md_workshop__test__results.html#autotoc_md1450',1,'']]],
  ['suite_20test_5ftool_5frunner_20py_257',['Original Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1128',1,'']]],
  ['suite_20test_5ftool_5frunner_5fedge_5fcases_20py_258',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1129',1,'']]],
  ['suite_20tests_20test_5fskills_5fmanager_20py_259',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1302',1,'']]],
  ['summary_260',['Summary',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'Agent Skills System Implementation Summary'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'Anthropic Claude-Specific Optimizations - Implementation Summary'],['../md_API__PROVIDERS.html#autotoc_md153',1,'API Endpoints Summary'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md834',1,'Appendix B: File Changes Summary'],['../md_IMPROVEMENTS__README.html',1,'AXE Multiagent Improvements - Implementation Summary'],['../md_FIXES__SUMMARY.html',1,'AXE Multiple Issues Fix Summary'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html',1,'Bubblewrap Sandbox Implementation - Summary'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md817',1,'Claims Fulfillment Summary'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md430',1,'Code Changes Summary'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html',1,'Collaborative Mode Tool Syntax Fix - Summary'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html',1,'Database Location Fix - Implementation Summary'],['../md_DYNAMIC__TOKENS__SUMMARY.html',1,'Dynamic Max Output Tokens Implementation Summary'],['../md__8collab__env.html',1,'Environment Summary'],['../md_API__PROVIDERS.html#autotoc_md152',1,'Environment Variables Summary'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md745',1,'Executive Summary'],['../md_SECURITY__REPORT.html#autotoc_md1098',1,'Executive Summary'],['../md_workshop__security__audit.html#autotoc_md1418',1,'Executive Summary'],['../md_workshop__security__audit.html#autotoc_md1420',1,'Findings Summary'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html',1,'Heredoc Execution Fix - Implementation Summary'],['../md_HEREDOC__EXECUTION__FIX.html',1,'Heredoc Execution Fix Summary'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md808',1,'Part 8: Integration Points Summary'],['../md_PR23__EXECUTIVE__SUMMARY.html',1,'PR #23 Workshop Dynamic Analysis Framework - Executive Summary'],['../md_REFACTORING__NOTES.html#autotoc_md994',1,'Refactoring Summary'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html',1,'Shell Operator Support Implementation Summary'],['../md_SILENT__BUILDS__IMPLEMENTATION.html',1,'Silent Builds Feature - Implementation Summary'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html',1,'Source Code Minifier Implementation Summary'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md309',1,'Summary'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md666',1,'Summary'],['../md_skills_2build.html#autotoc_md1201',1,'Summary'],['../md_skills_2claude__build.html#autotoc_md1258',1,'Summary'],['../md_workshop__test__results.html#autotoc_md1448',1,'Test Execution Summary'],['../md_workshop__test__results.html#autotoc_md1459',1,'Test Execution Summary'],['../md_workshop__dependency__validation.html#autotoc_md1364',1,'Validation Summary'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'WRITE Block Absolute Path Fix - Implementation Summary'],['../md_XML__PARSER__IMPLEMENTATION.html',1,'XML Function Call Parser - Implementation Summary']]],
  ['summary_20documents_261',['Summary Documents',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1126',1,'']]],
  ['summary_20multi_20agent_20collaboration_20issues_262',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_BUG__FIX__SUMMARY.html',1,'']]],
  ['summary_20of_20all_20implemented_20features_263',['Summary of All Implemented Features',['../md_IMPROVEMENTS__README.html#autotoc_md568',1,'']]],
  ['summary_20of_20changes_264',['Summary of Changes',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md192',1,'']]],
  ['summary_3a_20axe_20session_20termination_20bugs_265',['Fix Summary: AXE Session Termination Bugs',['../md_TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['summary_3a_20gpt_205_20fix_20write_20blocks_266',['Implementation Summary: GPT-5 Fix &amp;amp; WRITE Blocks',['../md_IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['supervisor_20role_267',['Supervisor Role',['../md_IMPROVEMENTS__README.html#autotoc_md562',1,'']]],
  ['supervisor_20role_20assignment_268',['Supervisor Role Assignment',['../md_MODELS__FINAL.html#autotoc_md659',1,'']]],
  ['support_269',['Support',['../md_AGENTS.html#autotoc_md68',1,'Contact &amp;amp; Support'],['../md_README.html#autotoc_md871',1,'Multi-Provider AI Support'],['../md_workshop__dependency__validation.html#autotoc_md1377',1,'Operating System Support'],['../md_workshop__dependency__validation.html#autotoc_md1376',1,'Python Version Support'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md278',1,'Support']]],
  ['support_20implementation_20summary_270',['Shell Operator Support Implementation Summary',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html',1,'']]],
  ['support_20quick_20reference_271',['XML Function Call Support - Quick Reference',['../md_XML__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['supported_20✅_272',['Bug 1: XML Tag Formats Not Supported ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md196',1,'']]],
  ['supported_20build_20systems_273',['Supported Build Systems',['../md_skills_2build.html#autotoc_md1169',1,'']]],
  ['supported_20formats_274',['Supported Formats',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md668',1,'Supported Formats'],['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md688',1,'Supported Formats'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1517',1,'Supported Formats']]],
  ['supported_20models_275',['Supported Models',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md254',1,'']]],
  ['surface_20reduction_276',['Attack Surface Reduction',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1074',1,'']]],
  ['symbol_20index_277',['Symbol Index',['../md_llm__prep_2codebase__overview.html#autotoc_md573',1,'']]],
  ['symbolic_20execution_278',['Symbolic Execution',['../md_PR23__VALIDATION__REPORT.html#autotoc_md750',1,'✅ VALIDATED - Chisel (Symbolic Execution)'],['../md_README.html#autotoc_md961',1,'Chisel - Symbolic Execution'],['../md_workshop__quick__reference.html#autotoc_md1402',1,'Chisel - Symbolic Execution']]],
  ['symbolic_20execution_20benchmarks_279',['Chisel - Symbolic Execution Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1346',1,'']]],
  ['symbolic_20execution_20engine_280',['angr (Symbolic Execution Engine)',['../md_workshop__dependency__validation.html#autotoc_md1367',1,'']]],
  ['syntax_281',['Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'Issue 4: Agents Confused About READ/WRITE Block Syntax'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1479',1,'Syntax']]],
  ['syntax_20✅_282',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['syntax_20check_283',['Syntax check',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md471',1,'']]],
  ['syntax_20fix_20summary_284',['Collaborative Mode Tool Syntax Fix - Summary',['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html',1,'']]],
  ['syntax_20trees_285',['ast (Abstract Syntax Trees)',['../md_workshop__dependency__validation.html#autotoc_md1371',1,'']]],
  ['system_286',['System',['../md_IMPROVEMENTS__FINAL.html#autotoc_md498',1,'Break System'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md482',1,'Mandatory Sleep System'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md478',1,'Permission-Based Sleep System'],['../md_ARCHITECTURE.html#autotoc_md170',1,'Plugin System'],['../md_AGENTS.html#autotoc_md53',1,'Skills System'],['../md__8collab__env.html#autotoc_md1',1,'System'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md518',1,'XP &amp;amp; Level System'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md726',1,'XP System'],['../md_workshop__quick__reference.html#autotoc_md1411',1,'XP System']]],
  ['system_20✅_287',['System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md544',1,'Phase 2: Agent Aliasing System ✅'],['../md_IMPROVEMENTS__README.html#autotoc_md545',1,'Phase 3: Experience &amp;amp; Level System ✅'],['../md_IMPROVEMENTS__README.html#autotoc_md549',1,'Phase 6: Mandatory Sleep System ✅'],['../md_IMPROVEMENTS__README.html#autotoc_md552',1,'Phase 9: Break System ✅']]],
  ['system_20detection_288',['build_analyzer - Build System Detection',['../md_README.html#autotoc_md944',1,'']]],
  ['system_20implementation_20summary_289',['Agent Skills System Implementation Summary',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['system_20improvement_20reference_20guide_290',['AXE Multi-Agent System - Improvement Reference Guide',['../md_IMPROVEMENTS__FINAL.html',1,'']]],
  ['system_20integration_291',['Claim 3: XP System Integration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md759',1,'']]],
  ['system_20integration_20complete_292',['XP System Integration - COMPLETE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md781',1,'']]],
  ['system_20model_20configuration_20reference_293',['AXE Multi-Agent System - Model Configuration Reference',['../md_MODELS__FINAL.html',1,'']]],
  ['system_20monitoring_294',['psutil (System Monitoring)',['../md_workshop__dependency__validation.html#autotoc_md1369',1,'']]],
  ['system_20prompts_295',['Custom System Prompts',['../md_README.html#autotoc_md929',1,'']]],
  ['system_20resources_296',['System Resources',['../md_workshop__test__results.html#autotoc_md1471',1,'']]],
  ['system_20slowing_20down_297',['&quot;System slowing down&quot;',['../md_QUICK__REFERENCE.html#autotoc_md860',1,'']]],
  ['system_20support_298',['Operating System Support',['../md_workshop__dependency__validation.html#autotoc_md1377',1,'']]],
  ['systems_299',['Systems',['../md_skills_2claude__build.html#autotoc_md1211',1,'Core Build Systems'],['../md_README.html#autotoc_md947',1,'Detected Build Systems'],['../md_skills_2build.html#autotoc_md1169',1,'Supported Build Systems']]]
];
