var searchData=
[
  ['data_0',['Finding #5: Logging of Sensitive Data',['../md_workshop__security__audit.html#autotoc_md1434',1,'']]],
  ['data_20integrity_1',['Test Data Integrity',['../md_workshop__test__results.html#autotoc_md1472',1,'']]],
  ['data_20serialization_2',['json (Data Serialization)',['../md_workshop__dependency__validation.html#autotoc_md1373',1,'']]],
  ['database_3',['Database',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md725',1,'Database'],['../md_QUICK__REFERENCE.html#autotoc_md846',1,'Database']]],
  ['database_20542_20lines_4',['&lt;span class=&quot;tt&quot;&gt;database/&lt;/span&gt; (542 lines)',['../md_REFACTORING__NOTES.html#autotoc_md1000',1,'']]],
  ['database_20engine_5',['sqlite3 (Database Engine)',['../md_workshop__dependency__validation.html#autotoc_md1372',1,'']]],
  ['database_20inspection_6',['Database Inspection',['../md_IMPROVEMENTS__README.html#autotoc_md560',1,'']]],
  ['database_20integration_7',['Database Integration',['../md_PR23__VALIDATION__REPORT.html#autotoc_md755',1,'Claim 2: Database Integration'],['../md_README.html#autotoc_md970',1,'Database Integration'],['../md_workshop__quick__reference.html#autotoc_md1410',1,'Database Integration']]],
  ['database_20integration_20complete_8',['Database Integration - COMPLETE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md780',1,'']]],
  ['database_20location_20fix_20implementation_20summary_9',['Database Location Fix - Implementation Summary',['../md_DATABASE__LOCATION__FIX__SUMMARY.html',1,'']]],
  ['database_20methods_10',['✅ VALIDATED - Database Methods',['../md_PR23__VALIDATION__REPORT.html#autotoc_md757',1,'']]],
  ['database_20operations_11',['Issue #4: Race Condition in Database Operations',['../md_workshop__security__audit.html#autotoc_md1427',1,'']]],
  ['database_20schema_12',['✅ VALIDATED - Database Schema',['../md_PR23__VALIDATION__REPORT.html#autotoc_md756',1,'']]],
  ['database_20storage_20✅_20fixed_13',['4. &lt;b&gt;Database/Storage&lt;/b&gt; ✅ Fixed',['../md_SECURITY__REPORT.html#autotoc_md1104',1,'']]],
  ['database_20test_20isolation_14',['3. Database Test Isolation',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md711',1,'']]],
  ['dataclass_15',['Skill Dataclass',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1306',1,'']]],
  ['date_3a_20january_204_202026_16',['Date: January 4, 2026',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md420',1,'']]],
  ['day_17',['Immediate (Same Day)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md736',1,'']]],
  ['debug_20verbosely_18',['5. Test Silently, Debug Verbosely',['../md_skills_2build.html#autotoc_md1185',1,'']]],
  ['debugging_19',['Debugging',['../md_README.html#autotoc_md954',1,'2. Build Issue Debugging'],['../md_README.html#autotoc_md917',1,'Debugging']]],
  ['decisions_20',['Design Decisions',['../md_REFACTORING__NOTES.html#autotoc_md1008',1,'']]],
  ['decompiler_20analysis_20expert_21',['IDA Pro / Decompiler Analysis Expert',['../md_skills_2ida__pro__analysis__patterns.html',1,'']]],
  ['deep_5fdive_5ffunction_22',['deep_dive_function',['../md_skills_2deep__dive__function.html',1,'']]],
  ['default_23',['Default',['../md_skills_2build.html#autotoc_md1189',1,'❌ Don&apos;t Use Verbose by Default'],['../md_README.html#autotoc_md985',1,'Open Source License (Default)']]],
  ['default_20allow_20execution_24',['1. Default-Allow Execution',['../md_SANDBOX.html#autotoc_md1029',1,'']]],
  ['default_20allow_20security_20model_25',['1. Default-Allow Security Model',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1064',1,'']]],
  ['default_20build_20approach_26',['Default Build Approach',['../md_AGENTS.html#autotoc_md58',1,'']]],
  ['default_20in_20collab_20mode_27',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['default_20in_20collab_20mode_20✅_28',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_FIXES__SUMMARY.html#autotoc_md367',1,'']]],
  ['default_20sandbox_20mode_29',['Example 1: Default Sandbox Mode',['../md_SANDBOX.html#autotoc_md1037',1,'']]],
  ['defaults_20✓_30',['4. Safe Defaults ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md350',1,'']]],
  ['defensive_20programming_20in_20run_20method_31',['1. Defensive Programming in &lt;span class=&quot;tt&quot;&gt;run()&lt;/span&gt; Method',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md405',1,'']]],
  ['degradation_32',['Degradation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md806',1,'Graceful Degradation'],['../md_workshop__dependency__validation.html#autotoc_md1392',1,'Graceful Degradation']]],
  ['degradation_20monitoring_33',['Degradation Monitoring',['../md_IMPROVEMENTS__FINAL.html#autotoc_md487',1,'']]],
  ['degradation_20monitoring_20✅_34',['Phase 7: Degradation Monitoring ✅',['../md_IMPROVEMENTS__README.html#autotoc_md550',1,'']]],
  ['delivered_35',['Delivered',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md73',1,'Features Delivered'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md696',1,'What Was Delivered']]],
  ['demo_36',['Run interactive demo',['../md_QUICK__REFERENCE.html#autotoc_md850',1,'']]],
  ['demo_5fdynamic_5ftokens_20py_20new_37',['7. &lt;span class=&quot;tt&quot;&gt;demo_dynamic_tokens.py&lt;/span&gt; (NEW)',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md345',1,'']]],
  ['demo_5fskills_5fsystem_20py_38',['8. Demonstration Script (&lt;span class=&quot;tt&quot;&gt;demo_skills_system.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1303',1,'']]],
  ['demonstration_20script_20demo_5fskills_5fsystem_20py_39',['8. Demonstration Script (&lt;span class=&quot;tt&quot;&gt;demo_skills_system.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1303',1,'']]],
  ['denied_40',['Issue 1: READ Block Access Denied',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md173',1,'']]],
  ['denied_20✅_41',['Issue 1: READ Block Access Denied ✅',['../md_FIXES__SUMMARY.html#autotoc_md363',1,'']]],
  ['denied_20errors_20inside_20sandbox_42',['&quot;Permission denied&quot; errors inside sandbox',['../md_SANDBOX.html#autotoc_md1054',1,'']]],
  ['dependencies_43',['Dependencies',['../md_workshop__dependency__validation.html#autotoc_md1365',1,'Core Dependencies'],['../md_workshop__security__audit.html#autotoc_md1436',1,'Core Dependencies'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md720',1,'Dependencies'],['../md_README.html#autotoc_md950',1,'Dependencies'],['../md_workshop__quick__reference.html#autotoc_md1413',1,'Dependencies'],['../md_README.html#autotoc_md878',1,'Install Dependencies'],['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md287',1,'Module Dependencies'],['../md_README.html#autotoc_md943',1,'Optional Dependencies'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md804',1,'Required Dependencies'],['../md_workshop__dependency__validation.html#autotoc_md1370',1,'Standard Library Dependencies']]],
  ['dependencies_20git_20✅_20clean_44',['6. &lt;b&gt;Dependencies &amp;amp; Git&lt;/b&gt; ✅ Clean',['../md_SECURITY__REPORT.html#autotoc_md1106',1,'']]],
  ['dependencies_20silently_45',['Install dependencies silently',['../md_skills_2build.html#autotoc_md1198',1,'']]],
  ['dependency_20analysis_46',['Part 7: Dependency Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md803',1,'']]],
  ['dependency_20health_47',['Dependency Health',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md722',1,'']]],
  ['dependency_20helper_20✅_48',['5. Build Analyzer Dependency Helper ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md427',1,'']]],
  ['dependency_20resolution_20testing_49',['Dependency Resolution Testing',['../md_workshop__dependency__validation.html#autotoc_md1380',1,'']]],
  ['dependency_20security_20analysis_50',['Dependency Security Analysis',['../md_workshop__security__audit.html#autotoc_md1435',1,'']]],
  ['dependency_20validation_51',['Dependency Validation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md805',1,'Dependency Validation'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md771',1,'Document 4: Dependency Validation'],['../md_workshop__dependency__validation.html',1,'Workshop Tools Dependency Validation']]],
  ['dependency_20version_20pinning_52',['Finding #4: Dependency Version Pinning',['../md_workshop__security__audit.html#autotoc_md1433',1,'']]],
  ['dependency_20vulnerability_20scan_53',['Dependency Vulnerability Scan',['../md_workshop__dependency__validation.html#autotoc_md1386',1,'']]],
  ['deployment_54',['Production Deployment',['../md_workshop__dependency__validation.html#autotoc_md1395',1,'']]],
  ['deprecated_55',['Issue 2: Llama 405B Model Deprecated',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md177',1,'']]],
  ['deprecated_20✅_56',['Issue 2: Llama 405B Model Deprecated ✅',['../md_FIXES__SUMMARY.html#autotoc_md365',1,'']]],
  ['descriptions_57',['Diagram Descriptions',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md285',1,'']]],
  ['design_58',['Limitations (By Design)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md814',1,'']]],
  ['design_59',['What Sandbox Doesn&apos;t Protect (by design)',['../md_SANDBOX.html#autotoc_md1042',1,'']]],
  ['design_20decisions_60',['Design Decisions',['../md_REFACTORING__NOTES.html#autotoc_md1008',1,'']]],
  ['design_20principles_61',['Design Principles',['../md_ARCHITECTURE.html#autotoc_md166',1,'Design Principles'],['../md_IMPROVEMENTS__README.html#autotoc_md565',1,'Design Principles']]],
  ['detailed_20findings_62',['Detailed Findings',['../md_workshop__security__audit.html#autotoc_md1421',1,'']]],
  ['detailed_20investigation_20verbose_63',['Phase 3: Detailed Investigation (Verbose)',['../md_skills_2claude__build.html#autotoc_md1235',1,'']]],
  ['detailed_20test_20results_64',['Detailed Test Results',['../md_workshop__test__results.html#autotoc_md1453',1,'']]],
  ['details_65',['Details',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md442',1,'Feature Details'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md579',1,'Implementation Details'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1060',1,'Implementation Details'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1494',1,'Implementation Details'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1304',1,'Technical Implementation Details']]],
  ['details_66',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md1236',1,'']]],
  ['details_3a_67',['details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md1215',1,'If issues found, re-run with full details:']]],
  ['detected_20build_20systems_68',['Detected Build Systems',['../md_README.html#autotoc_md947',1,'']]],
  ['detected_20re_20run_20with_20verbose_20output_3a_69',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['detection_70',['Detection',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1067',1,'4. Environment Detection'],['../md_README.html#autotoc_md944',1,'build_analyzer - Build System Detection']]],
  ['detection_71',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md1237',1,'']]],
  ['detection_20✅_72',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1320',1,'']]],
  ['detection_20metrics_73',['Diff-Based Error Detection Metrics',['../md_IMPROVEMENTS__FINAL.html#autotoc_md488',1,'']]],
  ['detection_20report_74',['DOS Packer Detection Report',['../md_skills_2dos__packer__detector.html#autotoc_md1273',1,'']]],
  ['development_20environment_75',['Development Environment',['../md_AGENTS.html#autotoc_md42',1,'']]],
  ['development_20workflow_76',['Scenario 1: Development Workflow',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1083',1,'']]],
  ['diagram_77',['Class Diagram',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md286',1,'']]],
  ['diagram_20descriptions_78',['Diagram Descriptions',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md285',1,'']]],
  ['diagrams_79',['Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md279',1,'AXE Architecture Diagrams'],['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md289',1,'Updating Diagrams'],['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md281',1,'Viewing Diagrams']]],
  ['diagrams_20pyreverse_80',['Python Class Diagrams (pyreverse)',['../md_llm__prep_2codebase__overview.html#autotoc_md572',1,'']]],
  ['dictionary_81',['✅ VALIDATED - XP Awards Dictionary',['../md_PR23__VALIDATION__REPORT.html#autotoc_md760',1,'']]],
  ['diet_20etc_20if_20tools_20expand_82',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['diff_20based_20error_20detection_20metrics_83',['Diff-Based Error Detection Metrics',['../md_IMPROVEMENTS__FINAL.html#autotoc_md488',1,'']]],
  ['directory_84',['Custom Project Directory',['../md_README.html#autotoc_md926',1,'']]],
  ['directory_20access_20control_85',['Directory Access Control',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1488',1,'']]],
  ['directory_20and_20files_86',['3. Created Skills Directory and Files',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1146',1,'']]],
  ['directory_20structure_87',['Directory Structure',['../md_llm__prep_2codebase__overview.html#autotoc_md570',1,'Directory Structure'],['../md_AGENTS.html#autotoc_md54',1,'Skills Directory Structure']]],
  ['directory_20structure_20✅_88',['Phase 1: Create Directory Structure ✅',['../md_REFACTORING__NOTES.html#autotoc_md1003',1,'']]],
  ['dirs_20if_20needed_89',['Create parent dirs if needed',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md466',1,'']]],
  ['disassembly_20analysis_90',['Disassembly &amp;amp; Analysis',['../md_README.html#autotoc_md916',1,'']]],
  ['disclosure_20in_20error_20messages_91',['Issue #3: Information Disclosure in Error Messages',['../md_workshop__security__audit.html#autotoc_md1426',1,'']]],
  ['discovery_20✅_92',['4. Workshop Tools Status &amp;amp; Discovery ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md426',1,'']]],
  ['disk_20i_20o_93',['Disk I/O',['../md_workshop__dependency__validation.html#autotoc_md1384',1,'']]],
  ['display_20at_20session_20start_20pinned_20message_20_3a_94',['Display at session start (pinned message):',['../md_IMPROVEMENTS__FINAL.html#autotoc_md524',1,'']]],
  ['distributed_20ai_95',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md169',1,'']]],
  ['distributed_20processing_20ray_96',['2. Adding Distributed Processing (Ray)',['../md_ARCHITECTURE.html#autotoc_md163',1,'']]],
  ['docs_97',['Available Docs',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1094',1,'']]],
  ['document_201_3a_20quick_20reference_98',['Document 1: Quick Reference',['../md_PR23__VALIDATION__REPORT.html#autotoc_md768',1,'']]],
  ['document_202_3a_20performance_20benchmarks_99',['Document 2: Performance Benchmarks',['../md_PR23__VALIDATION__REPORT.html#autotoc_md769',1,'']]],
  ['document_203_3a_20security_20audit_100',['Document 3: Security Audit',['../md_PR23__VALIDATION__REPORT.html#autotoc_md770',1,'']]],
  ['document_204_3a_20dependency_20validation_101',['Document 4: Dependency Validation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md771',1,'']]],
  ['document_205_3a_20test_20results_102',['Document 5: Test Results',['../md_PR23__VALIDATION__REPORT.html#autotoc_md772',1,'']]],
  ['document_20severity_20levels_103',['3. Document Severity Levels',['../md_skills_2claude__build.html#autotoc_md1245',1,'']]],
  ['document_20your_20choices_104',['3. Document Your Choices',['../md_skills_2build.html#autotoc_md1183',1,'']]],
  ['documentation_105',['Documentation',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md699',1,'✅ Comprehensive Documentation'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md406',1,'2. Enhanced Documentation'],['../md_API__PROVIDERS.html',1,'AXE API Provider Documentation'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md766',1,'Claim 5: Documentation'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md89',1,'Documentation'],['../md_API__PROVIDERS.html#autotoc_md113',1,'Documentation'],['../md_API__PROVIDERS.html#autotoc_md122',1,'Documentation'],['../md_API__PROVIDERS.html#autotoc_md132',1,'Documentation'],['../md_API__PROVIDERS.html#autotoc_md140',1,'Documentation'],['../md_API__PROVIDERS.html#autotoc_md149',1,'Documentation'],['../md_README.html#autotoc_md973',1,'Documentation'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1093',1,'Documentation'],['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1315',1,'Documentation'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1125',1,'Test Documentation']]],
  ['documentation_20✅_106',['6. Comprehensive Documentation ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md428',1,'']]],
  ['documentation_2010_2010_107',['📚 Documentation (10/10)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md705',1,'']]],
  ['documentation_20access_108',['Documentation Access',['../md__8collab__env.html#autotoc_md6',1,'']]],
  ['documentation_20commands_109',['Documentation Commands',['../md__8collab__env.html#autotoc_md8',1,'']]],
  ['documentation_20comments_110',['Documentation &amp;amp; Comments',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1123',1,'']]],
  ['documentation_20comprehensive_111',['Documentation - COMPREHENSIVE',['../md_PR23__VALIDATION__REPORT.html#autotoc_md797',1,'']]],
  ['documentation_20files_112',['✅ VALIDATED - Documentation Files',['../md_PR23__VALIDATION__REPORT.html#autotoc_md767',1,'']]],
  ['documentation_20tests_113',['Documentation Tests',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1130',1,'']]],
  ['documentation_20updates_114',['Documentation Updates',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md231',1,'Documentation Updates'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md451',1,'Documentation Updates']]],
  ['documents_115',['Summary Documents',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1126',1,'']]],
  ['doesn_20t_20protect_20by_20design_116',['What Sandbox Doesn&apos;t Protect (by design)',['../md_SANDBOX.html#autotoc_md1042',1,'']]],
  ['domain_20specific_20skill_20files_117',['3. Domain-Specific Skill Files',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1296',1,'']]],
  ['don_20t_20assume_20silence_20means_20success_118',['❌ Don&apos;t Assume Silence Means Success',['../md_skills_2build.html#autotoc_md1188',1,'']]],
  ['don_20t_20remove_20all_20output_119',['❌ Don&apos;t Remove All Output',['../md_skills_2build.html#autotoc_md1187',1,'']]],
  ['don_20t_20use_20verbose_20by_20default_120',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md1189',1,'']]],
  ['dos_20exe_20unpackers_121',['DOS EXE Unpackers',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md1339',1,'']]],
  ['dos_20packer_20detection_20report_122',['DOS Packer Detection Report',['../md_skills_2dos__packer__detector.html#autotoc_md1273',1,'']]],
  ['dos_5fexe_5funpack_123',['dos_exe_unpack',['../md_skills_2dos__exe__unpack.html',1,'']]],
  ['dos_5fmemory_5farena_5fanalyzer_124',['dos_memory_arena_analyzer',['../md_skills_2dos__memory__arena__analyzer.html',1,'']]],
  ['dos_5fpacker_5fdetector_125',['dos_packer_detector',['../md_skills_2dos__packer__detector.html',1,'']]],
  ['dosbox_5femulation_5fsetup_126',['dosbox_emulation_setup',['../md_skills_2dosbox__emulation__setup.html',1,'']]],
  ['dosbox_5fint21_5ftrace_127',['dosbox_int21_trace',['../md_skills_2dosbox__int21__trace.html',1,'']]],
  ['dosbox_5fmemory_5fdump_128',['dosbox_memory_dump',['../md_skills_2dosbox__memory__dump.html',1,'']]],
  ['dosbox_5fscreenshot_129',['dosbox_screenshot',['../md_skills_2dosbox__screenshot.html',1,'']]],
  ['double_20execution_20bug_20✅_130',['Bug 4: Double Execution Bug ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md202',1,'']]],
  ['down_131',['&quot;System slowing down&quot;',['../md_QUICK__REFERENCE.html#autotoc_md860',1,'']]],
  ['download_132',['Download',['../md_README.html#autotoc_md921',1,'']]],
  ['duplicate_20command_20execution_20❌_20→_20✅_133',['Bug 1: Duplicate Command Execution ❌ → ✅',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md310',1,'']]],
  ['duplicate_20execution_134',['Example 1: No Duplicate Execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md328',1,'']]],
  ['duplicate_20execution_135',['to prevent duplicate execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md317',1,'']]],
  ['duplicate_20execution_20and_20heredoc_20parsing_20bug_20fixes_136',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['duplicate_20execution_20before_20fix_137',['Example of Duplicate Execution (Before Fix)',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md313',1,'']]],
  ['duration_20limits_138',['Recommended Work Duration Limits',['../md_IMPROVEMENTS__FINAL.html#autotoc_md483',1,'']]],
  ['during_20session_139',['During Session',['../md_QUICK__REFERENCE.html#autotoc_md853',1,'']]],
  ['during_20sessions_140',['New Agent Commands (During Sessions)',['../md_IMPROVEMENTS__README.html#autotoc_md554',1,'']]],
  ['dynamic_20analysis_20framework_20comprehensive_20validation_20report_141',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_PR23__VALIDATION__REPORT.html',1,'']]],
  ['dynamic_20analysis_20framework_20executive_20summary_142',['PR #23 Workshop Dynamic Analysis Framework - Executive Summary',['../md_PR23__EXECUTIVE__SUMMARY.html',1,'']]],
  ['dynamic_20analysis_20tools_143',['Dynamic Analysis Tools',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md697',1,'✅ Four Dynamic Analysis Tools'],['../md_README.html#autotoc_md957',1,'Workshop - Dynamic Analysis Tools']]],
  ['dynamic_20max_20output_20tokens_20implementation_20summary_144',['Dynamic Max Output Tokens Implementation Summary',['../md_DYNAMIC__TOKENS__SUMMARY.html',1,'']]],
  ['dynamic_20spawning_145',['Dynamic Spawning',['../md_IMPROVEMENTS__FINAL.html#autotoc_md504',1,'']]],
  ['dynamic_20spawning_20✅_146',['Phase 10: Dynamic Spawning ✅',['../md_IMPROVEMENTS__README.html#autotoc_md553',1,'']]]
];
