var searchData=
[
  ['g_0',['G',['../md_TODO.html#autotoc_md2209',1,'G'],['../md_TODO.html#autotoc_md2226',1,'G']]],
  ['g_20cat_20eof_1',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md328',1,'']]],
  ['gamification_20for_20agents_2',['🎮 Gamification for Agents',['../md_README.html#autotoc_md1996',1,'']]],
  ['general_20agents_2017_20agents_3',['General Agents (17 agents)',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md719',1,'']]],
  ['general_20guidelines_4',['General Guidelines',['../md_llm__prep_2project__guidance.html#autotoc_md1975',1,'']]],
  ['general_20rule_3a_20lowercase_20no_20prefixes_5',['General Rule: Lowercase, No Prefixes',['../md_docs_2features_2configuration.html#autotoc_md1173',1,'']]],
  ['generation_6',['Generation',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1927',1,'Bubblewrap Command Generation'],['../md_docs_2workshop_2security-audit.html#autotoc_md1863',1,'Issue #5: Weak Random ID Generation'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md562',1,'Usage - Image Generation'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md561',1,'Usage - Text Generation']]],
  ['get_20agent_20privileges_7',['Get Agent Privileges',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1501',1,'']]],
  ['get_20turns_20✅_8',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['get_5fagent_5fby_5falias_20alias_9',['&lt;span class=&quot;tt&quot;&gt;get_agent_by_alias(alias)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1952',1,'']]],
  ['get_5fbroadcasts_20since_20none_20category_20none_20agent_20none_20requires_5fack_5fonly_20false_20limit_2050_10',['&lt;span class=&quot;tt&quot;&gt;get_broadcasts(since=None, category=None, agent=None, requires_ack_only=False, limit=50)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1309',1,'']]],
  ['get_5fconflicts_11',['&lt;span class=&quot;tt&quot;&gt;get_conflicts()&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1311',1,'']]],
  ['get_5fdatabase_5fpath_20helper_20function_12',['1. Added &lt;span class=&quot;tt&quot;&gt;get_database_path()&lt;/span&gt; Helper Function',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md226',1,'']]],
  ['get_5fdirectives_20active_5fonly_20true_13',['&lt;span class=&quot;tt&quot;&gt;get_directives(active_only=True)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1312',1,'']]],
  ['get_5fpending_5facks_20agent_5falias_14',['&lt;span class=&quot;tt&quot;&gt;get_pending_acks(agent_alias)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1310',1,'']]],
  ['get_5fpending_5fvotes_15',['&lt;span class=&quot;tt&quot;&gt;get_pending_votes()&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1947',1,'']]],
  ['get_5fsummary_16',['&lt;span class=&quot;tt&quot;&gt;get_summary()&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1313',1,'']]],
  ['get_5fvote_5fhistory_20agent_5falias_20none_17',['&lt;span class=&quot;tt&quot;&gt;get_vote_history(agent_alias=None)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1945',1,'']]],
  ['get_5fvote_5fsummary_18',['&lt;span class=&quot;tt&quot;&gt;get_vote_summary()&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1946',1,'']]],
  ['gets_20recognized_19',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md465',1,'']]],
  ['getting_20started_20',['Getting Started',['../md_MISSION.html#autotoc_md1984',1,'']]],
  ['git_20✅_20clean_21',['6. &lt;b&gt;Dependencies &amp;amp; Git&lt;/b&gt; ✅ Clean',['../md_docs_2security.html#autotoc_md1607',1,'']]],
  ['github_20agent_20integration_22',['GitHub Agent Integration',['../md_docs_2features_2github-agent-integration.html',1,'']]],
  ['github_20agent_20integration_20md_23',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2github-agent-integration.html&quot;&gt;github-agent-integration.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1240',1,'']]],
  ['github_20agent_20integration_20md_20github_20agent_20integration_20md_24',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2github-agent-integration.html&quot;&gt;github-agent-integration.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1240',1,'']]],
  ['github_20models_25',['GitHub Models',['../md_docs_2features_2configuration.html#autotoc_md1174',1,'Exception: GitHub Models'],['../md_docs_2api-providers.html#autotoc_md100',1,'GitHub Models'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md565',1,'GitHub Models']]],
  ['global_20workspace_26',['1. Broadcasting (Global Workspace)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1031',1,'']]],
  ['global_20workspace_20baars_201988_27',['Global Workspace (Baars, 1988)',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1349',1,'']]],
  ['global_20workspace_20implementation_20guide_28',['Global Workspace - Implementation Guide',['../md_docs_2global-workspace.html',1,'']]],
  ['global_20workspace_20implementation_20summary_29',['Global Workspace Implementation Summary',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html',1,'']]],
  ['globalworkspace_30',['Integration with GlobalWorkspace',['../md_docs_2subsumption__architecture.html#autotoc_md1720',1,'']]],
  ['globalworkspace_20api_20unification_31',['2. GlobalWorkspace API Unification',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1090',1,'']]],
  ['globalworkspace_20class_32',['GlobalWorkspace Class',['../md_docs_2xp__voting.html#autotoc_md1943',1,'']]],
  ['globalworkspace_20session_5fdir_3a_20str_33',['&lt;span class=&quot;tt&quot;&gt;GlobalWorkspace(session_dir: str)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1306',1,'']]],
  ['good_34',['Type Hints - GOOD',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md918',1,'']]],
  ['good_20balance_35',['Small Models (1-2GB) - Good Balance',['../md_docs_2ollama-guide.html#autotoc_md1439',1,'']]],
  ['good_20behavior_36',['Encouraging Good Behavior',['../md_docs_2references_2quick-reference.html#autotoc_md1579',1,'']]],
  ['good_20output_37',['4. Supervision Behaviour — XP Rewards for Good Output',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md988',1,'']]],
  ['good_20work_20gets_20recognized_38',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md465',1,'']]],
  ['good_3a_20only_20high_20severity_20findings_39',['Good: Only high-severity findings',['../md_skills_2claude__build.html#autotoc_md2135',1,'']]],
  ['good_3a_20only_20security_20warnings_40',['Good: Only security warnings',['../md_skills_2claude__build.html#autotoc_md2134',1,'']]],
  ['gpt_41',['GPT',['../md_docs_2api-providers.html#autotoc_md73',1,'OpenAI (GPT)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md552',1,'OpenAI (GPT)'],['../md_README.html#autotoc_md2029',1,'OpenAI (GPT)']]],
  ['gpt_205_202_20codex_20implementation_20guide_42',['GPT-5.2 Codex Implementation Guide',['../md_docs_2codex-implementation.html',1,'']]],
  ['gpt_205_20api_20parameter_20error_20critical_43',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md397',1,'']]],
  ['gpt_205_20fix_20write_20blocks_44',['Implementation Summary: GPT-5 Fix &amp;amp; WRITE Blocks',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['gpt_20building_20c_20project_45',['Example 1: GPT Building C++ Project',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md733',1,'']]],
  ['graceful_20degradation_46',['Graceful Degradation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md928',1,'Graceful Degradation'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1802',1,'Graceful Degradation']]],
  ['graceful_20handling_47',['Graceful Handling',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md668',1,'']]],
  ['gradle_48',['Gradle',['../md_skills_2build.html#autotoc_md2066',1,'']]],
  ['graph_49',['Call Graph',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1123',1,'']]],
  ['graphviz_50',['Command Line (Requires GraphViz)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1118',1,'']]],
  ['grok_51',['Grok',['../md_docs_2api-providers.html#autotoc_md92',1,'xAI (Grok)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md558',1,'xAI (Grok)'],['../md_README.html#autotoc_md2030',1,'xAI (Grok)']]],
  ['grok_20arbitrates_52',['Agent Grok Arbitrates',['../md_docs_2conflict__resolution__examples.html#autotoc_md1059',1,'']]],
  ['grok_20level_2025_20sees_20prompt_53',['Agent Grok (Level 25) Sees Prompt',['../md_docs_2conflict__resolution__examples.html#autotoc_md1058',1,'']]],
  ['grok_20level_2030_20attempts_54',['Agent Grok (Level 30) Attempts',['../md_docs_2conflict__resolution__examples.html#autotoc_md1069',1,'']]],
  ['groundwork_20discussion_55',['Section 10 – SRI Groundwork Discussion',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1403',1,'']]],
  ['guaranteed_20compatibility_56',['Guaranteed Compatibility',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md157',1,'']]],
  ['guarantees_57',['Safety Guarantees',['../md_docs_2features_2github-agent-integration.html#autotoc_md1206',1,'']]],
  ['gui_20tests_20with_20xvfb_58',['Running interactive/GUI tests with Xvfb',['../md_docs_2TESTING.html#autotoc_md1744',1,'']]],
  ['guidance_20for_20axe_59',['Project Guidance for AXE',['../md_llm__prep_2project__guidance.html',1,'']]],
  ['guide_60',['Guide',['../md_ARCHITECTURE.html',1,'AXE Architecture and Extensibility Guide'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html',1,'AXE Multi-Agent System - Improvement Reference Guide'],['../md_docs_2TESTING.html',1,'AXE Testing Guide'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html',1,'Cognitive Architecture in AXE - User Guide'],['../md_docs_2global-workspace.html',1,'Global Workspace - Implementation Guide'],['../md_docs_2codex-implementation.html',1,'GPT-5.2 Codex Implementation Guide'],['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md293',1,'Migration Guide'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md640',1,'Migration Guide'],['../md_docs_2features_2sandbox.html#autotoc_md1267',1,'Migration Guide'],['../md_docs_2api-providers.html#autotoc_md112',1,'Model Selection Guide'],['../md_docs_2ollama-guide.html',1,'Ollama Integration Guide'],['../md_docs_2features_2write-blocks.html',1,'WRITE Block Functionality - User Guide']]],
  ['guidelines_61',['Guidelines',['../md_AGENTS.html#autotoc_md34',1,'Build Guidelines'],['../md_llm__prep_2project__guidance.html#autotoc_md1975',1,'General Guidelines'],['../md_MISSION.html#autotoc_md1982',1,'Usage Guidelines'],['../md_docs_2conflict__resolution__examples.html#autotoc_md1074',1,'XP Award Guidelines']]],
  ['guidelines_20✅_62',['Phase 1: Session Rules &amp;amp; Guidelines ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md480',1,'']]],
  ['guidelines_20content_63',['2. BUILD GUIDELINES Content',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md721',1,'']]],
  ['guidelines_20for_20all_20agents_64',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md718',1,'']]]
];
