var searchData=
[
  ['wad_20file_0',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['wake_20up_20triggers_1',['Wake-up Triggers',['../md_IMPROVEMENTS__FINAL.html#autotoc_md480',1,'']]],
  ['want_20to_20resume_20later_2',['&quot;Want to resume later&quot;',['../md_QUICK__REFERENCE.html#autotoc_md859',1,'']]],
  ['warnings_3',['Compression Warnings',['../md_README.html#autotoc_md909',1,'']]],
  ['warnings_4',['Good: Only security warnings',['../md_skills_2claude__build.html#autotoc_md1243',1,'']]],
  ['was_20delivered_5',['What Was Delivered',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md696',1,'']]],
  ['was_20implemented_6',['What Was Implemented',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1141',1,'']]],
  ['wasted_20capacity_20fixed_20✓_7',['3. Wasted Capacity Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md349',1,'']]],
  ['weak_20random_20id_20generation_8',['Issue #5: Weak Random ID Generation',['../md_workshop__security__audit.html#autotoc_md1428',1,'']]],
  ['week_9',['Short-Term (This Week)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md737',1,'']]],
  ['weights_10',['Recommended Weights',['../md_IMPROVEMENTS__FINAL.html#autotoc_md489',1,'']]],
  ['well_20being_20–_20no_20real_20bullying_11',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['what_20agents_20see_12',['What Agents See',['../md_QUICK__REFERENCE.html#autotoc_md855',1,'']]],
  ['what_20s_20new_13',['What&apos;s New?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1515',1,'']]],
  ['what_20sandbox_20doesn_20t_20protect_20by_20design_14',['What Sandbox Doesn&apos;t Protect (by design)',['../md_SANDBOX.html#autotoc_md1042',1,'']]],
  ['what_20sandbox_20protects_15',['What Sandbox Protects',['../md_SANDBOX.html#autotoc_md1041',1,'']]],
  ['what_20was_20delivered_16',['What Was Delivered',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md696',1,'']]],
  ['what_20was_20implemented_17',['What Was Implemented',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1141',1,'']]],
  ['when_20to_20use_20each_20agent_18',['When to Use Each Agent',['../md_README.html#autotoc_md913',1,'']]],
  ['when_20to_20use_20verbose_20output_19',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md59',1,'']]],
  ['whichever_20exists_20',['Only one present: use whichever exists',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md392',1,'']]],
  ['whistleblower_20feature_21',['Note on Whistleblower Feature',['../md_README.html#autotoc_md870',1,'']]],
  ['whitelist_22',['Tool Whitelist',['../md_README.html#autotoc_md915',1,'']]],
  ['whitelist_20mode_23',['Compared to Whitelist Mode',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1073',1,'']]],
  ['whitelist_20mode_24',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['whitelist_20mode_20but_20not_20sandbox_20mode_25',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['whitelist_20to_20sandbox_26',['From Whitelist to Sandbox',['../md_SANDBOX.html#autotoc_md1049',1,'']]],
  ['whole_20block_20as_20a_20single_20command_27',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['why_20axe_28',['Why AXE?',['../md_README.html#autotoc_md867',1,'']]],
  ['why_20silent_20builds_29',['Why Silent Builds?',['../md_skills_2build.html#autotoc_md1167',1,'']]],
  ['why_20these_20limits_30',['Why These Limits?',['../md_IMPROVEMENTS__FINAL.html#autotoc_md484',1,'']]],
  ['why_20these_20modules_20first_31',['Why These Modules First?',['../md_REFACTORING__NOTES.html#autotoc_md1009',1,'']]],
  ['why_20this_20matters_32',['Why This Matters',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1516',1,'']]],
  ['why_20this_20works_33',['Why This Works',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md393',1,'']]],
  ['with_20addresssanitizer_20for_20runtime_20detection_34',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md1237',1,'']]],
  ['with_20agentmanager_35',['6. Integration with AgentManager',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1301',1,'']]],
  ['with_20agents_36',['with Agents',['../md_README.html#autotoc_md951',1,'Integration with Agents'],['../md_README.html#autotoc_md969',1,'Integration with Agents'],['../md_workshop__quick__reference.html#autotoc_md1414',1,'Integration with Agents']]],
  ['with_20agents_20md_37',['Integration with AGENTS.md',['../md_skills_2claude__build.html#autotoc_md1250',1,'']]],
  ['with_20asan_20and_20run_20tests_20silently_38',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md1220',1,'']]],
  ['with_20axe_39',['Integration with AXE',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1155',1,'']]],
  ['with_20axe_20yaml_40',['Integration with axe.yaml',['../md_skills_2build.html#autotoc_md1178',1,'']]],
  ['with_20blacklist_41',['Example 2: Restricted Sandbox with Blacklist',['../md_SANDBOX.html#autotoc_md1038',1,'']]],
  ['with_20cache_20tracking_42',['Token Statistics with Cache Tracking',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md266',1,'']]],
  ['with_20cmake_43',['Example 1: C++ Project with CMake',['../md_skills_2build.html#autotoc_md1191',1,'']]],
  ['with_20collaborations_44',['Integration with Collaborations',['../md_skills_2build.html#autotoc_md1179',1,'']]],
  ['with_20copilot_45',['GitHub Models - Free with Copilot',['../md_README.html#autotoc_md887',1,'']]],
  ['with_20files_46',['Working with Files',['../md_README.html#autotoc_md896',1,'']]],
  ['with_20full_20details_47',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md1236',1,'']]],
  ['with_20full_20details_3a_48',['with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md1215',1,'If issues found, re-run with full details:']]],
  ['with_20make_49',['Example 3: Python Project with Make',['../md_skills_2build.html#autotoc_md1197',1,'']]],
  ['with_20maven_50',['Example 2: Java Project with Maven',['../md_skills_2build.html#autotoc_md1194',1,'']]],
  ['with_20minimal_20noise_51',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md1248',1,'']]],
  ['with_20new_20features_52',['Starting a Collaborative Session with New Features',['../md_IMPROVEMENTS__README.html#autotoc_md557',1,'']]],
  ['with_20newline_20e_20g_20cat_20eof_53',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md391',1,'']]],
  ['with_20other_20blocks_54',['Integration with Other Blocks',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1486',1,'']]],
  ['with_20parentheses_55',['1. Subshells with Parentheses',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1120',1,'']]],
  ['with_20quiet_20flags_56',['Configure with quiet flags',['../md_skills_2build.html#autotoc_md1192',1,'']]],
  ['with_20security_20flags_57',['Configure with security flags',['../md_skills_2claude__build.html#autotoc_md1230',1,'']]],
  ['with_20verbose_20on_20failure_58',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md1182',1,'']]],
  ['with_20verbose_20output_3a_59',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['without_20spaces_60',['2. Redirects Without Spaces',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1121',1,'']]],
  ['work_61',['Test Projects for Multi-Agent Work',['../md_MODELS__FINAL.html#autotoc_md658',1,'']]],
  ['work_20duration_20limits_62',['Recommended Work Duration Limits',['../md_IMPROVEMENTS__FINAL.html#autotoc_md483',1,'']]],
  ['work_20gets_20recognized_63',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_IMPROVEMENTS__FINAL.html#autotoc_md528',1,'']]],
  ['work_20in_20whitelist_20mode_20but_20not_20sandbox_20mode_64',['Commands work in whitelist mode but not sandbox mode',['../md_SANDBOX.html#autotoc_md1053',1,'']]],
  ['workflow_65',['Workflow',['../md_README.html#autotoc_md972',1,'Real-World Example: Security Audit Workflow'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1083',1,'Scenario 1: Development Workflow'],['../md_skills_2claude__build.html#autotoc_md1209',1,'Security Auditing Workflow'],['../md_skills_2c__modernization__expert.html#autotoc_md1206',1,'Workflow'],['../md_skills_2cpp__modernization__expert.html#autotoc_md1263',1,'Workflow'],['../md_skills_2cpp__refactoring__expert.html#autotoc_md1267',1,'Workflow'],['../md_skills_2ida__pro__analysis__patterns.html#autotoc_md1277',1,'Workflow'],['../md_skills_2x86__assembly__expert.html#autotoc_md1289',1,'Workflow']]],
  ['workflow_20example_66',['Security Audit Workflow Example',['../md_skills_2claude__build.html#autotoc_md1228',1,'']]],
  ['workflow_20examples_67',['Workflow Examples',['../md_README.html#autotoc_md952',1,'']]],
  ['workflow_20savings_68',['Example Workflow Savings',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md270',1,'']]],
  ['workflow_20template_69',['Workflow Template',['../md_skills_2reverse__engineering__expert.html#autotoc_md1284',1,'']]],
  ['working_70',['Working',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md34',1,'Agents Now Working'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1132',1,'Commands Now Working']]],
  ['working_71',['working',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md273',1,'Caching not working'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md276',1,'Files API not working']]],
  ['working_20with_20files_72',['Working with Files',['../md_README.html#autotoc_md896',1,'']]],
  ['workplace_20rules_73',['Workplace Rules',['../md_IMPROVEMENTS__FINAL.html#autotoc_md523',1,'']]],
  ['works_74',['Works',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md248',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md255',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md259',1,'How It Works'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md264',1,'How It Works'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md393',1,'Why This Works']]],
  ['workshop_20commands_20expanded_75',['Workshop Commands (EXPANDED!)',['../md_README.html#autotoc_md904',1,'']]],
  ['workshop_20dynamic_20analysis_20framework_20comprehensive_20validation_20report_76',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_PR23__VALIDATION__REPORT.html',1,'']]],
  ['workshop_20dynamic_20analysis_20framework_20executive_20summary_77',['PR #23 Workshop Dynamic Analysis Framework - Executive Summary',['../md_PR23__EXECUTIVE__SUMMARY.html',1,'']]],
  ['workshop_20dynamic_20analysis_20tools_78',['Workshop - Dynamic Analysis Tools',['../md_README.html#autotoc_md957',1,'']]],
  ['workshop_20status_79',['Workshop Status',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md446',1,'']]],
  ['workshop_20tools_80',['3. Adding New Workshop Tools',['../md_ARCHITECTURE.html#autotoc_md164',1,'']]],
  ['workshop_20tools_20benchmarks_81',['Workshop Tools Benchmarks',['../md_workshop__benchmarks.html',1,'']]],
  ['workshop_20tools_20dependency_20validation_82',['Workshop Tools Dependency Validation',['../md_workshop__dependency__validation.html',1,'']]],
  ['workshop_20tools_20quick_20reference_83',['Workshop Tools Quick Reference',['../md_workshop__quick__reference.html',1,'']]],
  ['workshop_20tools_20security_20audit_84',['Workshop Tools Security Audit',['../md_workshop__security__audit.html',1,'']]],
  ['workshop_20tools_20status_20discovery_20✅_85',['4. Workshop Tools Status &amp;amp; Discovery ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md426',1,'']]],
  ['workshop_20tools_20test_20suite_20execution_20results_86',['Workshop Tools Test Suite Execution Results',['../md_workshop__test__results.html',1,'']]],
  ['workspace_87',['Per-Agent Workspace',['../md_IMPROVEMENTS__FINAL.html#autotoc_md533',1,'']]],
  ['world_20example_3a_20reverse_20engineering_20a_20wad_20file_88',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['world_20example_3a_20security_20audit_20workflow_89',['Real-World Example: Security Audit Workflow',['../md_README.html#autotoc_md972',1,'']]],
  ['world_20impact_90',['Real-World Impact',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md84',1,'']]],
  ['write_20block_20absolute_20path_20fix_20implementation_20summary_91',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['write_20block_20format_92',['WRITE Block Format',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1480',1,'']]],
  ['write_20block_20functionality_20user_20guide_93',['WRITE Block Functionality - User Guide',['../md_WRITE__BLOCKS__GUIDE.html',1,'']]],
  ['write_20block_20sanitization_94',['WRITE block sanitization',['../md_FIXES__SUMMARY.html#autotoc_md371',1,'']]],
  ['write_20block_20syntax_95',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['write_20block_20syntax_20✅_96',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['write_20blocks_97',['Implementation Summary: GPT-5 Fix &amp;amp; WRITE Blocks',['../md_IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['write_20blocks_20not_20executing_20high_98',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md461',1,'']]],
  ['write_20exec_20blocks_99',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['write_20file_100',['Write file',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md467',1,'']]]
];
