var searchData=
[
  ['a_0',['A',['../md_TODO.html#autotoc_md2204',1,'A'],['../md_TODO.html#autotoc_md2221',1,'A']]],
  ['a_20collaboration_20session_1',['Starting a Collaboration Session',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1029',1,'']]],
  ['a_20collaborative_20session_20with_20new_20features_2',['Starting a Collaborative Session with New Features',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md494',1,'']]],
  ['a_20file_3',['Example 2: Creating a File',['../md_docs_2features_2parsers.html#autotoc_md1231',1,'']]],
  ['a_20file_20multiple_20ways_4',['Example 1: Reading a File (Multiple Ways)',['../md_docs_2features_2parsers.html#autotoc_md1230',1,'']]],
  ['a_20heredoc_5',['Check if the entire block contains a heredoc',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md257',1,'']]],
  ['a_20new_20provider_6',['Adding a New Provider',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1557',1,'']]],
  ['a_20session_7',['a Session',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md476',1,'Starting a Session'],['../md_docs_2references_2quick-reference.html#autotoc_md1569',1,'Starting a Session'],['../md_docs_2references_2quick-reference.html#autotoc_md1577',1,'Starting a Session']]],
  ['a_20session_20save_8',['Can an Agent Trigger a Session Save?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1689',1,'']]],
  ['a_20single_20command_9',['If so, treat the whole block as a single command',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md258',1,'']]],
  ['a_20vote_10',['Casting a Vote',['../md_docs_2xp__voting.html#autotoc_md1939',1,'']]],
  ['a_3a_20standard_20venv_20pip_11',['Option A: Standard venv + pip',['../md_README.html#autotoc_md2000',1,'']]],
  ['a_3a_20test_20execution_20logs_12',['Appendix A: Test Execution Logs',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md953',1,'']]],
  ['about_20read_20write_20block_20syntax_13',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['about_20read_20write_20block_20syntax_20✅_14',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md306',1,'']]],
  ['absolute_20path_20fix_20implementation_20summary_15',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['abstract_20syntax_20trees_16',['ast (Abstract Syntax Trees)',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1781',1,'']]],
  ['abuse_17',['Vote Limits (Anti-Abuse)',['../md_docs_2xp__voting.html#autotoc_md1937',1,'']]],
  ['academic_20references_20added_20to_20readme_20md_18',['Academic References Added to README.md',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1353',1,'']]],
  ['acceptance_20criteria_19',['Acceptance Criteria',['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md527',1,'Acceptance Criteria'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1626',1,'Acceptance Criteria']]],
  ['acceptance_20criteria_20status_20',['Acceptance Criteria Status',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1107',1,'']]],
  ['access_21',['Access',['../md__8collab__env.html#autotoc_md6',1,'Documentation Access'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1370',1,'Test 8: Workspace Files Access']]],
  ['access_20control_22',['Access Control',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md653',1,'3. Filesystem Access Control'],['../md_docs_2features_2sandbox.html#autotoc_md1250',1,'3. Filesystem Access Control'],['../md_docs_2features_2write-blocks.html#autotoc_md1288',1,'Directory Access Control']]],
  ['access_20denied_23',['Issue 1: READ Block Access Denied',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md175',1,'']]],
  ['access_20denied_20✅_24',['Issue 1: READ Block Access Denied ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md300',1,'']]],
  ['accessing_20workshop_20tools_25',['Accessing Workshop Tools',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1841',1,'']]],
  ['accident_26',['accident',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md190',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md191',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['accuracy_27',['Taint Propagation Accuracy',['../md_docs_2workshop_2benchmarks.html#autotoc_md1761',1,'']]],
  ['acknowledge_20broadcast_5fid_20agent_5falias_20comment_20none_28',['&lt;span class=&quot;tt&quot;&gt;acknowledge(broadcast_id, agent_alias, comment=None)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1308',1,'']]],
  ['acknowledgment_20system_29',['Acknowledgment System',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1331',1,'']]],
  ['actions_30',['Actions',['../md_docs_2workshop_2test-results.html#autotoc_md1909',1,'Immediate Actions'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md857',1,'Post-Merge Actions']]],
  ['actions_20completed_31',['Immediate Actions (Completed)',['../md_docs_2workshop_2security-audit.html#autotoc_md1879',1,'']]],
  ['active_32',['Check if Features are Active',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1041',1,'']]],
  ['active_20agents_20counter_20✅_33',['Bug 2: Active Agents Counter ✅',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md775',1,'']]],
  ['active_20documentation_34',['Archive vs. Active Documentation',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md967',1,'']]],
  ['active_5fonly_20true_35',['&lt;span class=&quot;tt&quot;&gt;get_directives(active_only=True)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1312',1,'']]],
  ['activities_36',['Break Activities',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md438',1,'']]],
  ['actual_20implementation_37',['Part 1: PR Claims vs. Actual Implementation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md870',1,'']]],
  ['actual_20runtime_20logs_38',['Demo Output (Actual Runtime Logs)',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1514',1,'']]],
  ['adaptation_39',['4. Test Adaptation',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1092',1,'']]],
  ['add_20more_20diet_20etc_20if_20tools_20expand_40',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md2162',1,'']]],
  ['add_20workspace_41',['Test 3: Add Workspace',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1365',1,'']]],
  ['added_42',['Added',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md386',1,'Commands Added'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1932',1,'Files Added'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md793',1,'Files Modified/Added'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md588',1,'New Functions Added'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md262',1,'New Tests Added'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md333',1,'New Tests Added']]],
  ['added_20get_5fdatabase_5fpath_20helper_20function_43',['1. Added &lt;span class=&quot;tt&quot;&gt;get_database_path()&lt;/span&gt; Helper Function',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md226',1,'']]],
  ['added_20modified_44',['Lines Added/Modified',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1105',1,'']]],
  ['added_20to_20readme_20md_45',['Academic References Added to README.md',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1353',1,'']]],
  ['added_20to_20requirements_20txt_46',['Added to requirements.txt',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md843',1,'']]],
  ['adding_20a_20new_20provider_47',['Adding a New Provider',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1557',1,'']]],
  ['adding_20distributed_20processing_20ray_48',['2. Adding Distributed Processing (Ray)',['../md_ARCHITECTURE.html#autotoc_md53',1,'']]],
  ['adding_20new_20ai_20providers_49',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md52',1,'']]],
  ['adding_20new_20providers_50',['Adding New Providers',['../md_docs_2features_2configuration.html#autotoc_md1184',1,'']]],
  ['adding_20new_20token_20optimization_20strategies_51',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md55',1,'']]],
  ['adding_20new_20workshop_20tools_52',['3. Adding New Workshop Tools',['../md_ARCHITECTURE.html#autotoc_md54',1,'']]],
  ['adding_20to_20archive_53',['Adding to Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md969',1,'']]],
  ['additional_20languages_54',['Additional Languages',['../md__8collab__env.html#autotoc_md5',1,'']]],
  ['additional_20resources_55',['Additional Resources',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1533',1,'📖 Additional Resources'],['../md_AGENTS.html#autotoc_md44',1,'Additional Resources'],['../md_docs_2ollama-guide.html#autotoc_md1451',1,'Additional Resources']]],
  ['additions_20for_20sri_56',['Proposed Additions for SRI',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1696',1,'']]],
  ['addressed_57',['Addressed',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md714',1,'Code Review Addressed'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md592',1,'Code Review Issues Addressed'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1627',1,'Code Review Issues Addressed'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md686',1,'Problem Addressed']]],
  ['addresssanitizer_20asan_58',['AddressSanitizer (ASan)',['../md_skills_2claude__build.html#autotoc_md2110',1,'']]],
  ['addresssanitizer_20for_20runtime_20detection_59',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md2128',1,'']]],
  ['after_60',['After',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md177',1,'After'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'After'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md239',1,'After'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md615',1,'After'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md348',1,'Example - Before vs After']]],
  ['after_20axe_20yaml_61',['After (axe.yaml)',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'']]],
  ['after_20comparison_20of_20fixes_62',['Before/After Comparison of Fixes',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html',1,'']]],
  ['after_20fix_63',['Impact After Fix',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md237',1,'']]],
  ['agent_64',['🔄 Turn-based Round-Robin Multi-Agent',['../md_TODO.html#autotoc_md2242',1,'']]],
  ['agent_65',['Security-Focused Agent (1 agent)',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md720',1,'']]],
  ['agent_201_20agent_66',['Security-Focused Agent (1 agent)',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md720',1,'']]],
  ['agent_20aliases_67',['Agent Aliases',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md449',1,'Agent Aliases'],['../md_README.html#autotoc_md2016',1,'Agent Aliases']]],
  ['agent_20aliasing_20system_20✅_68',['Phase 2: Agent Aliasing System ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md481',1,'']]],
  ['agent_20collaboration_69',['Agent Collaboration',['../md_README.html#autotoc_md1994',1,'🤝 Strong Multi-Agent Collaboration'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md737',1,'Example 3: Multi-Agent Collaboration'],['../md_skills_2build.html#autotoc_md2091',1,'Example 4: Multi-Agent Collaboration'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md574',1,'Multi-Agent Collaboration']]],
  ['agent_20collaboration_20issues_70',['Bug Fix Summary - Multi-Agent Collaboration Issues',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html',1,'']]],
  ['agent_20commands_20during_20sessions_71',['New Agent Commands (During Sessions)',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md491',1,'']]],
  ['agent_20communication_72',['Unix Socket Interface for Agent Communication',['../md_docs_2socket__interface.html',1,'']]],
  ['agent_20communication_20tokens_73',['Agent Communication Tokens',['../md_MISSION.html#autotoc_md1979',1,'']]],
  ['agent_20configuration_20axe_20yaml_74',['3. Agent Configuration (&lt;span class=&quot;tt&quot;&gt;axe.yaml&lt;/span&gt;)',['../md_docs_2codex-implementation.html#autotoc_md1013',1,'']]],
  ['agent_20coordination_75',['Agent Coordination',['../md__8collab__shared.html#autotoc_md14',1,'']]],
  ['agent_20coverage_76',['Agent Coverage',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md728',1,'']]],
  ['agent_20discussion_20—_20live_20session_20output_77',['SRI Agent Discussion — Live Session Output',['../md_docs_2SRI__AGENT__DISCUSSION.html',1,'']]],
  ['agent_20driven_20sri_20workflow_20proposed_78',['4. Agent-Driven SRI Workflow (Proposed)',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1700',1,'']]],
  ['agent_20execution_20engine_79',['Agent eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['agent_20execution_20engine_20✅_80',['AXE - Agent eXecution Engine ✅',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md192',1,'']]],
  ['agent_20expert_81',['Python Agent Expert',['../md_skills_2python__agent__expert.html',1,'']]],
  ['agent_20grok_20arbitrates_82',['Agent Grok Arbitrates',['../md_docs_2conflict__resolution__examples.html#autotoc_md1059',1,'']]],
  ['agent_20grok_20level_2025_20sees_20prompt_83',['Agent Grok (Level 25) Sees Prompt',['../md_docs_2conflict__resolution__examples.html#autotoc_md1058',1,'']]],
  ['agent_20grok_20level_2030_20attempts_84',['Agent Grok (Level 30) Attempts',['../md_docs_2conflict__resolution__examples.html#autotoc_md1069',1,'']]],
  ['agent_20integration_85',['GitHub Agent Integration',['../md_docs_2features_2github-agent-integration.html',1,'']]],
  ['agent_20integration_20md_86',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2github-agent-integration.html&quot;&gt;github-agent-integration.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1240',1,'']]],
  ['agent_20integration_20md_20github_20agent_20integration_20md_87',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2github-agent-integration.html&quot;&gt;github-agent-integration.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1240',1,'']]],
  ['agent_20interaction_20flow_88',['Agent Interaction Flow',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1038',1,'']]],
  ['agent_20interactions_89',['Test: Live Agent Interactions',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1513',1,'']]],
  ['agent_20interactions_20in_20axe_20directory_90',['2. Agent Interactions in AXE Directory',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1517',1,'']]],
  ['agent_20level_2050_20resolves_91',['Supervisor-Level Agent (Level 50) Resolves',['../md_docs_2conflict__resolution__examples.html#autotoc_md1070',1,'']]],
  ['agent_20lifecycle_92',['Agent Lifecycle',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md500',1,'']]],
  ['agent_20llama_20level_2015_20sees_20prompt_93',['Agent Llama (Level 15) Sees Prompt',['../md_docs_2conflict__resolution__examples.html#autotoc_md1057',1,'']]],
  ['agent_20none_20requires_5fack_5fonly_20false_20limit_2050_94',['&lt;span class=&quot;tt&quot;&gt;get_broadcasts(since=None, category=None, agent=None, requires_ack_only=False, limit=50)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1309',1,'']]],
  ['agent_20override_95',['Agent Override',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1558',1,'']]],
  ['agent_20overrides_96',['Agent Overrides',['../md_docs_2features_2configuration.html#autotoc_md1175',1,'']]],
  ['agent_20privileges_97',['Get Agent Privileges',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1501',1,'']]],
  ['agent_20ranks_20levels_98',['Agent Ranks &amp;amp; Levels',['../md_docs_2references_2quick-reference.html#autotoc_md1565',1,'']]],
  ['agent_20rate_20limiting_20✅_99',['3. Agent Rate Limiting ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md362',1,'']]],
  ['agent_20session_20commands_100',['Agent Session Commands',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md475',1,'']]],
  ['agent_20skills_20system_20implementation_20summary_101',['Agent Skills System Implementation Summary',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['agent_20stuck_20or_20confused_102',['&quot;Agent stuck or confused&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1583',1,'']]],
  ['agent_20system_20improvement_20reference_20guide_103',['AXE Multi-Agent System - Improvement Reference Guide',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html',1,'']]],
  ['agent_20system_20model_20configuration_20reference_104',['AXE Multi-Agent System - Model Configuration Reference',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html',1,'']]],
  ['agent_20systems_105',['Agent Systems',['../md_README.html#autotoc_md2046',1,'Multi-Agent Systems'],['../md_TODO.html#autotoc_md2252',1,'Multi-Agent Systems']]],
  ['agent_20tokens_106',['Agent Tokens',['../md_docs_2subsumption__architecture.html#autotoc_md1718',1,'']]],
  ['agent_20trigger_20a_20session_20save_107',['Can an Agent Trigger a Session Save?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1689',1,'']]],
  ['agent_20usage_108',['Agent Usage',['../md_docs_2features_2github-agent-integration.html#autotoc_md1198',1,'']]],
  ['agent_20work_109',['Test Projects for Multi-Agent Work',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md576',1,'']]],
  ['agent_20workspace_110',['Per-Agent Workspace',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md470',1,'']]],
  ['agent_5falias_111',['&lt;span class=&quot;tt&quot;&gt;get_pending_acks(agent_alias)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1310',1,'']]],
  ['agent_5falias_20agent_5flevel_20category_20message_112',['&lt;span class=&quot;tt&quot;&gt;broadcast(agent_alias, agent_level, category, message, ...)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1307',1,'']]],
  ['agent_5falias_20comment_20none_113',['&lt;span class=&quot;tt&quot;&gt;acknowledge(broadcast_id, agent_alias, comment=None)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1308',1,'']]],
  ['agent_5falias_20max_5fentries_2010_114',['&lt;span class=&quot;tt&quot;&gt;format_for_prompt(agent_alias, max_entries=10)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1314',1,'']]],
  ['agent_5falias_20none_115',['&lt;span class=&quot;tt&quot;&gt;get_vote_history(agent_alias=None)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1945',1,'']]],
  ['agent_5flevel_20category_20message_116',['&lt;span class=&quot;tt&quot;&gt;broadcast(agent_alias, agent_level, category, message, ...)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1307',1,'']]],
  ['agent_5fmanager_20py_117',['agent_manager py',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md278',1,'3. &lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;'],['../md_docs_2codex-implementation.html#autotoc_md1015',1,'5. API Call Logic (&lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;)']]],
  ['agentdatabase_20_5f_5finit_5f_5f_118',['2. Updated &lt;span class=&quot;tt&quot;&gt;AgentDatabase.__init__()&lt;/span&gt;',['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md227',1,'']]],
  ['agentdatabase_20methods_119',['AgentDatabase Methods',['../md_docs_2xp__voting.html#autotoc_md1950',1,'']]],
  ['agentmanager_120',['6. Integration with AgentManager',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md751',1,'']]],
  ['agents_121',['Agents',['../md_README.html#autotoc_md1996',1,'🎮 Gamification for Agents'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md718',1,'1. Updated axe.yaml - BUILD GUIDELINES for All Agents'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1824',1,'Integration with Agents'],['../md__8collab__env.html#autotoc_md11',1,'Notes for Agents'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md469',1,'Safe Commands for Agents']]],
  ['agents_122',['General Agents (17 agents)',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md719',1,'']]],
  ['agents_2017_20agents_123',['General Agents (17 agents)',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md719',1,'']]],
  ['agents_20confused_20about_20read_20write_20block_20syntax_124',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['agents_20confused_20about_20read_20write_20block_20syntax_20✅_125',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md306',1,'']]],
  ['agents_20counter_20✅_126',['Bug 2: Active Agents Counter ✅',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md775',1,'']]],
  ['agents_20md_127',['Integration with AGENTS.md',['../md_skills_2claude__build.html#autotoc_md2141',1,'']]],
  ['agents_20md_20for_20axe_128',['AGENTS.md for AXE',['../md_AGENTS.html',1,'']]],
  ['agents_20md_20standard_20compliance_129',['2. AGENTS.md Standard Compliance',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md745',1,'']]],
  ['agents_20never_20get_20turns_20✅_130',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['agents_20not_20cooperating_131',['&quot;Agents not cooperating&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1582',1,'']]],
  ['agents_20now_20working_132',['Agents Now Working',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md134',1,'']]],
  ['agents_20see_133',['What Agents See',['../md_docs_2references_2quick-reference.html#autotoc_md1580',1,'']]],
  ['agnostic_134',['Agnostic',['../md_README.html#autotoc_md1992',1,'🌐 Provider/Model Agnostic'],['../md_TODO.html#autotoc_md2238',1,'🌐 Provider/Model Agnostic']]],
  ['ai_135',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md59',1,'']]],
  ['ai_20providers_136',['1. Adding New AI Providers',['../md_ARCHITECTURE.html#autotoc_md52',1,'']]],
  ['alias_137',['&lt;span class=&quot;tt&quot;&gt;get_agent_by_alias(alias)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1952',1,'']]],
  ['aliases_138',['Aliases',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md449',1,'Agent Aliases'],['../md_README.html#autotoc_md2016',1,'Agent Aliases'],['../md_docs_2references_2quick-reference.html#autotoc_md1570',1,'Aliases'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md452',1,'Special Aliases']]],
  ['aliasing_20system_20✅_139',['Phase 2: Agent Aliasing System ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md481',1,'']]],
  ['alignment_140',['Theory Alignment',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1338',1,'']]],
  ['alignment_20assessment_141',['The &quot;Office&quot; Vision — Alignment Assessment',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md998',1,'']]],
  ['alignment_20minsky_201986_142',['Theory Alignment (Minsky 1986)',['../md_docs_2xp__voting.html#autotoc_md1953',1,'']]],
  ['all_20agents_143',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md718',1,'']]],
  ['all_20features_20implemented_144',['✅ All Features Implemented',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md359',1,'']]],
  ['all_20implemented_20features_145',['Summary of All Implemented Features',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md505',1,'']]],
  ['all_20met_146',['Success Criteria (All Met)',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md784',1,'']]],
  ['all_20output_147',['❌ Don&apos;t Remove All Output',['../md_skills_2build.html#autotoc_md2078',1,'']]],
  ['all_20tests_148',['[... all tests ...]',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md790',1,'']]],
  ['all_20tests_20passed_149',['✅ ALL TESTS PASSED!',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md791',1,'']]],
  ['all_20trials_20fail_150',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md2163',1,'']]],
  ['all_20unit_20tests_151',['Run all unit tests',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md405',1,'']]],
  ['allow_20execution_152',['1. Default-Allow Execution',['../md_docs_2features_2sandbox.html#autotoc_md1248',1,'']]],
  ['allow_20security_20model_153',['1. Default-Allow Security Model',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md651',1,'']]],
  ['allowed_20bug_20fixed_20_3a_154',['✅ Now Allowed (Bug Fixed):',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md131',1,'']]],
  ['alphabetical_155',['Alphabetical',['../md_TODO.html#autotoc_md2203',1,'Implemented Features (Alphabetical)'],['../md_TODO.html#autotoc_md2220',1,'Planned Features (Alphabetical)']]],
  ['also_156',['See Also',['../md_docs_2global-workspace.html#autotoc_md1323',1,'']]],
  ['always_20does_157',['What AXE ALWAYS Does',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1431',1,'']]],
  ['always_20use_20silent_20flags_20first_158',['1. Always Use Silent Flags First',['../md_skills_2build.html#autotoc_md2072',1,'']]],
  ['an_20agent_20trigger_20a_20session_20save_159',['Can an Agent Trigger a Session Save?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1689',1,'']]],
  ['analysis_160',['Analysis',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md873',1,'✅ VALIDATED - Saw (Taint Analysis)'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1832',1,'&lt;b&gt;Saw&lt;/b&gt; (Taint Analysis)'],['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1458',1,'Analysis'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1760',1,'Code Snippet Analysis'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1768',1,'Comparative Analysis'],['../md_skills_2claude__build.html#autotoc_md2107',1,'Cppcheck (Static Analysis)'],['../md_docs_2workshop_2security-audit.html#autotoc_md1870',1,'Dependency Security Analysis'],['../md_docs_2workshop_2test-results.html#autotoc_md1902',1,'Error Analysis'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1758',1,'Function-Level Analysis'],['../md_docs_2workshop_2security-audit.html#autotoc_md1859',1,'Issue #2: Memory Exhaustion in Chisel Analysis'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md915',1,'Part 5: Code Quality Analysis'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md921',1,'Part 6: Test Coverage Analysis'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md925',1,'Part 7: Dependency Analysis'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1791',1,'Performance Impact Analysis'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1763',1,'Project-Scale Analysis'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md339',1,'Root Cause Analysis'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1813',1,'Saw - Taint Analysis'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md671',1,'Scenario 2: Code Analysis'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md128',1,'Security Analysis'],['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md313',1,'Security Analysis'],['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md757',1,'Token Efficiency Analysis'],['../md_skills_2claude__build.html#autotoc_md2104',1,'Valgrind (Memory Analysis)']]],
  ['analysis_20benchmarks_161',['Saw - Taint Analysis Benchmarks',['../md_docs_2workshop_2benchmarks.html#autotoc_md1759',1,'']]],
  ['analysis_20expert_162',['Analysis Expert',['../md_skills_2ida__pro__analysis__patterns.html',1,'IDA Pro / Decompiler Analysis Expert'],['../md_skills_2x86__assembly__expert.html',1,'x86 Assembly Analysis Expert']]],
  ['analysis_20framework_20comprehensive_20validation_20report_163',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html',1,'']]],
  ['analysis_20framework_20executive_20summary_164',['PR #23 Workshop Dynamic Analysis Framework - Executive Summary',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html',1,'']]],
  ['analysis_20libraries_165',['Primary Analysis Libraries',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1776',1,'']]],
  ['analysis_20patterns_166',['Key Analysis Patterns',['../md_skills_2x86__assembly__expert.html#autotoc_md2179',1,'']]],
  ['analysis_20performance_167',['Binary Analysis Performance',['../md_docs_2workshop_2benchmarks.html#autotoc_md1757',1,'']]],
  ['analysis_20quietly_168',['Run static analysis quietly',['../md_skills_2claude__build.html#autotoc_md2108',1,'']]],
  ['analysis_20results_169',['Analysis Results',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1623',1,'Analysis Results'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1754',1,'Performance Analysis Results']]],
  ['analysis_20silent_170',['Phase 2: Static Analysis (Silent)',['../md_skills_2claude__build.html#autotoc_md2123',1,'']]],
  ['analysis_20silent_171',['analysis silent',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md736',1,'Runtime analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md2143',1,'Runtime analysis (silent)'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md735',1,'Static analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md2142',1,'Static analysis (silent)']]],
  ['analysis_20summary_172',['Analysis Summary',['../md_docs_2SRI__AGENT__DISCUSSION.html#autotoc_md1678',1,'']]],
  ['analysis_20tools_173',['Analysis Tools',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md819',1,'✅ Four Dynamic Analysis Tools'],['../md_README.html#autotoc_md2012',1,'Analysis Tools']]],
  ['analysis_20tools_20implemented_174',['Claim 1: Four Analysis Tools Implemented',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md871',1,'']]],
  ['analysis_20workspace_20axe_20source_175',['Section 9 – AXE Self-Analysis (workspace = AXE source)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1401',1,'']]],
  ['analyzer_176',['Clang Static Analyzer',['../md_skills_2claude__build.html#autotoc_md2113',1,'']]],
  ['analyzer_20dependency_20helper_20✅_177',['5. Build Analyzer Dependency Helper ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md364',1,'']]],
  ['analyzer_20helper_178',['Build Analyzer Helper',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md384',1,'']]],
  ['analyzer_20quietly_179',['Run Clang static analyzer quietly',['../md_skills_2claude__build.html#autotoc_md2114',1,'']]],
  ['and_20build_20quietly_180',['Clean and build quietly',['../md_skills_2build.html#autotoc_md2086',1,'']]],
  ['and_20extensibility_20guide_181',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['and_20feedback_182',['Rejection and Feedback',['../md_docs_2features_2github-agent-integration.html#autotoc_md1204',1,'']]],
  ['and_20files_183',['3. Created Skills Directory and Files',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md722',1,'']]],
  ['and_20heredoc_20parsing_20bug_20fixes_184',['Duplicate Execution and Heredoc Parsing Bug Fixes',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html',1,'']]],
  ['and_20loading_20—_20session_20commands_185',['Session Saving and Loading — &lt;span class=&quot;tt&quot;&gt;/session&lt;/span&gt; commands',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1687',1,'']]],
  ['and_20multiple_20workspace_20support_186',['Workspace Path Bug Fix and Multiple Workspace Support',['../md_docs_2WORKSPACE__FIX.html',1,'']]],
  ['and_20path_187',['&lt;span class=&quot;tt&quot;&gt;/tmp/bin&lt;/span&gt; and PATH',['../md_docs_2TESTING.html#autotoc_md1737',1,'']]],
  ['and_20permissions_188',['Security and Permissions',['../md_docs_2features_2write-blocks.html#autotoc_md1287',1,'']]],
  ['and_20pid_20file_20locations_189',['Socket and PID File Locations',['../md_docs_2socket__interface.html#autotoc_md1639',1,'']]],
  ['and_20reporting_190',['7. Token Savings — Verification and Reporting',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md994',1,'']]],
  ['and_20resolution_191',['Arbitration and Resolution',['../md_docs_2conflict__resolution__examples.html#autotoc_md1065',1,'']]],
  ['and_20run_20tests_20silently_192',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md2111',1,'']]],
  ['and_20safety_20improvements_193',['User Namespace Detection and Safety Improvements',['../md_docs_2NAMESPACE__DETECTION.html',1,'']]],
  ['and_20selection_194',['Session History and Selection',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1688',1,'']]],
  ['and_20sri_195',['The &quot;Office&quot; Vision and SRI',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1702',1,'']]],
  ['and_20supervisor_20role_196',['Ollama Model Selection and Supervisor Role',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md976',1,'']]],
  ['angr_20symbolic_20execution_20engine_197',['angr (Symbolic Execution Engine)',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1777',1,'']]],
  ['anthropic_20claude_198',['Anthropic Claude',['../md_docs_2api-providers.html#autotoc_md65',1,'Anthropic (Claude)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md539',1,'Anthropic (Claude)'],['../md_README.html#autotoc_md2028',1,'Anthropic (Claude)']]],
  ['anthropic_20claude_20specific_20features_20in_20axe_199',['Anthropic Claude-Specific Features in AXE',['../md_docs_2features_2anthropic-features.html',1,'']]],
  ['anthropic_20claude_20specific_20optimizations_20implementation_20summary_200',['Anthropic Claude-Specific Optimizations - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['anthropic_20features_20md_201',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2anthropic-features.html&quot;&gt;anthropic-features.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1239',1,'']]],
  ['anthropic_20features_20md_20anthropic_20features_20md_202',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2anthropic-features.html&quot;&gt;anthropic-features.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1239',1,'']]],
  ['anthropic_20sdk_20error_20fixed_20✓_203',['1. Anthropic SDK Error Fixed ✓',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md284',1,'']]],
  ['anti_20abuse_204',['Vote Limits (Anti-Abuse)',['../md_docs_2xp__voting.html#autotoc_md1937',1,'']]],
  ['any_20talking_20model_205',['ANY Talking Model',['../md_README.html#autotoc_md1993',1,'💬 Works with ANY Talking Model'],['../md_TODO.html#autotoc_md2239',1,'💬 Works with ANY Talking Model']]],
  ['api_206',['API',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md755',1,'SkillsManager Class API'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md548',1,'Usage - OpenAI-Compatible API']]],
  ['api_20beta_207',['4. Files API (Beta)',['../md_docs_2features_2anthropic-features.html#autotoc_md1144',1,'']]],
  ['api_20beta_20optional_20✅_208',['4. Files API (Beta, Optional) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md147',1,'']]],
  ['api_20call_20logic_20core_20agent_5fmanager_20py_209',['5. API Call Logic (&lt;span class=&quot;tt&quot;&gt;core/agent_manager.py&lt;/span&gt;)',['../md_docs_2codex-implementation.html#autotoc_md1015',1,'']]],
  ['api_20endpoints_20summary_210',['API Endpoints Summary',['../md_docs_2api-providers.html#autotoc_md111',1,'']]],
  ['api_20keys_211',['Testing API Keys',['../md_docs_2api-providers.html#autotoc_md116',1,'']]],
  ['api_20keys_212',['Manual testing (requires API keys)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md407',1,'']]],
  ['api_20not_20working_213',['Files API not working',['../md_docs_2features_2anthropic-features.html#autotoc_md1158',1,'']]],
  ['api_20parameter_20error_20critical_214',['✅ Issue 1: GPT-5 API Parameter Error (CRITICAL)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md397',1,'']]],
  ['api_20provider_20documentation_215',['AXE API Provider Documentation',['../md_docs_2api-providers.html',1,'']]],
  ['api_20provider_20limits_216',['API Provider Limits',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md442',1,'']]],
  ['api_20providers_217',['API Providers',['../md_README.html#autotoc_md2027',1,'']]],
  ['api_20reference_218',['API Reference',['../md_docs_2global-workspace.html#autotoc_md1305',1,'API Reference'],['../md_docs_2socket__interface.html#autotoc_md1664',1,'API Reference'],['../md_docs_2xp__voting.html#autotoc_md1942',1,'API Reference']]],
  ['api_20unification_219',['2. GlobalWorkspace API Unification',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1090',1,'']]],
  ['api_20usage_220',['API Usage',['../md_docs_2features_2anthropic-features.html#autotoc_md1142',1,'']]],
  ['api_20vs_20chat_20completions_221',['Key Differences: Responses API vs Chat Completions',['../md_docs_2codex-implementation.html#autotoc_md1016',1,'']]],
  ['appearing_222',['No Results Appearing?',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md809',1,'']]],
  ['append_20append_20to_20files_223',['APPEND - Append to Files',['../md_docs_2features_2parsers.html#autotoc_md1224',1,'']]],
  ['append_20results_20to_20response_224',['Append results to response',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md400',1,'']]],
  ['append_20to_20files_225',['APPEND - Append to Files',['../md_docs_2features_2parsers.html#autotoc_md1224',1,'']]],
  ['appendix_20a_3a_20test_20execution_20logs_226',['Appendix A: Test Execution Logs',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md953',1,'']]],
  ['appendix_20b_3a_20file_20changes_20summary_227',['Appendix B: File Changes Summary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md956',1,'']]],
  ['applied_228',['Applied',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md164',1,'Best Practices Applied'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1046',1,'Votes Not Applied?']]],
  ['apply_5fxp_5fvotes_20votes_229',['&lt;span class=&quot;tt&quot;&gt;apply_xp_votes(votes)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1951',1,'']]],
  ['applying_20manually_230',['Re-applying manually',['../dir_03443f88f6d5cae20798897259900ddf.html#autotoc_md2055',1,'']]],
  ['approach_231',['Approach',['../md_AGENTS.html#autotoc_md35',1,'Default Build Approach'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md621',1,'Implementation Approach']]],
  ['approach_20conflict_232',['Example 2: Refactoring Approach Conflict',['../md_docs_2conflict__resolution__examples.html#autotoc_md1061',1,'']]],
  ['approve_20not_20default_20in_20collab_20mode_233',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md183',1,'']]],
  ['approve_20not_20default_20in_20collab_20mode_20✅_234',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md304',1,'']]],
  ['approved_20for_20merge_235',['✅ APPROVED FOR MERGE',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md944',1,'']]],
  ['arbitrates_236',['Agent Grok Arbitrates',['../md_docs_2conflict__resolution__examples.html#autotoc_md1059',1,'']]],
  ['arbitration_20✅_237',['Test 4: Conflict Detection &amp;amp; Arbitration ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1467',1,'']]],
  ['arbitration_20and_20resolution_238',['Arbitration and Resolution',['../md_docs_2conflict__resolution__examples.html#autotoc_md1065',1,'']]],
  ['arbitration_20created_239',['Arbitration Created',['../md_docs_2conflict__resolution__examples.html#autotoc_md1056',1,'']]],
  ['arbitration_20minsky_201986_240',['Arbitration Minsky 1986',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1352',1,'Conflict Detection &amp;amp; Arbitration (Minsky, 1986)'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1087',1,'PR #56: Conflict Detection &amp;amp; Arbitration (Minsky 1986)']]],
  ['arbitration_20resolution_241',['6. Arbitration Resolution',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1036',1,'']]],
  ['architecture_242',['Architecture',['../md_README.html#autotoc_md1995',1,'🧠 Built-in Cognitive Architecture'],['../md_TODO.html#autotoc_md2241',1,'🧠 Cognitive Architecture'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1545',1,'1. Three-File Architecture'],['../md_AGENTS.html#autotoc_md37',1,'Architecture'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md431',1,'Architecture'],['../md_docs_2features_2sandbox.html#autotoc_md1264',1,'Architecture'],['../md_README.html#autotoc_md2045',1,'Cognitive Architecture'],['../md_docs_2features_2configuration.html',1,'Configuration Architecture'],['../md_docs_2privilege__mapping.html#autotoc_md1474',1,'System Architecture'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1094',1,'Unified System Architecture']]],
  ['architecture_20and_20extensibility_20guide_243',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['architecture_20benefits_244',['Architecture Benefits',['../md_docs_2subsumption__architecture.html#autotoc_md1726',1,'']]],
  ['architecture_20brooks_201986_245',['Architecture Brooks 1986',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1085',1,'PR #54: Subsumption Architecture (Brooks 1986)'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1350',1,'Subsumption Architecture (Brooks, 1986)']]],
  ['architecture_20consolidation_20summary_246',['Cognitive Architecture Consolidation Summary',['../md_docs_2CONSOLIDATION__SUMMARY.html',1,'']]],
  ['architecture_20controller_247',['Subsumption Architecture Controller',['../md_docs_2subsumption__architecture.html',1,'']]],
  ['architecture_20database_20✅_248',['Test 2: Subsumption Architecture + Database ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1465',1,'']]],
  ['architecture_20diagrams_249',['AXE Architecture Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1114',1,'']]],
  ['architecture_20features_20working_250',['3. Cognitive Architecture Features Working',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1518',1,'']]],
  ['architecture_20in_20axe_20runtime_251',['Integration Complete: Cognitive Architecture in AXE Runtime',['../md_docs_2INTEGRATION__COMPLETE.html',1,'']]],
  ['architecture_20in_20axe_20user_20guide_252',['Cognitive Architecture in AXE - User Guide',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html',1,'']]],
  ['architecture_20notes_253',['Architecture Notes',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md498',1,'Architecture Notes'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1048',1,'Architecture Notes']]],
  ['architecture_20overview_254',['Architecture Overview',['../md_MISSION.html#autotoc_md1983',1,'']]],
  ['architecture_20papers_255',['Cognitive Architecture Papers',['../md_TODO.html#autotoc_md2251',1,'']]],
  ['architecture_20tokens_256',['Cognitive Architecture Tokens',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1030',1,'']]],
  ['architecture_20working_20with_20ollama_257',['PROOF: AXE Cognitive Architecture Working with Ollama',['../md_docs_2PROOF__OLLAMA__DEMO.html',1,'']]],
  ['archive_258',['Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md969',1,'Adding to Archive'],['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1528',1,'Archive'],['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md960',1,'AXE Documentation Archive'],['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md968',1,'Contributing to Archive'],['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md970',1,'Do NOT Archive'],['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md964',1,'Purpose of Archive'],['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md966',1,'When to Use Archive']]],
  ['archive_20contents_259',['Archive Contents',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md961',1,'']]],
  ['archive_20organization_260',['Archive Organization',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md965',1,'']]],
  ['archive_20vs_20active_20documentation_261',['Archive vs. Active Documentation',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md967',1,'']]],
  ['are_20active_262',['Check if Features are Active',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1041',1,'']]],
  ['are_20now_20handled_20exclusively_20by_20axe_20py_20responseprocessor_263',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md253',1,'']]],
  ['argument_20parsing_20axe_20py_264',['3. CLI Argument Parsing (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1917',1,'']]],
  ['arguments_265',['CLI Arguments',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1374',1,'']]],
  ['as_20a_20single_20command_266',['If so, treat the whole block as a single command',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md258',1,'']]],
  ['as_20before_267',['No heredoc - process line by line as before',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md259',1,'']]],
  ['asan_268',['AddressSanitizer (ASan)',['../md_skills_2claude__build.html#autotoc_md2110',1,'']]],
  ['asan_20and_20run_20tests_20silently_269',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md2111',1,'']]],
  ['assembly_20analysis_20expert_270',['x86 Assembly Analysis Expert',['../md_skills_2x86__assembly__expert.html',1,'']]],
  ['assessment_271',['Assessment',['../md_docs_2workshop_2security-audit.html#autotoc_md1876',1,'Compliance Assessment'],['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1694',1,'Feasibility Assessment'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md868',1,'Overall Assessment'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md947',1,'Part 12: Risk Assessment'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md851',1,'Risk Assessment'],['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md998',1,'The &quot;Office&quot; Vision — Alignment Assessment']]],
  ['assignment_272',['Assignment',['../md_docs_2subsumption__architecture.html#autotoc_md1711',1,'Layer Assignment'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md577',1,'Supervisor Role Assignment']]],
  ['assume_20silence_20means_20success_273',['❌ Don&apos;t Assume Silence Means Success',['../md_skills_2build.html#autotoc_md2079',1,'']]],
  ['assurance_274',['Assurance',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md374',1,'Quality Assurance'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1826',1,'Validation &amp;amp; Quality Assurance']]],
  ['ast_20abstract_20syntax_20trees_275',['ast (Abstract Syntax Trees)',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1781',1,'']]],
  ['at_20session_20start_20pinned_20message_20_3a_276',['Display at session start (pinned message):',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md461',1,'']]],
  ['attack_20surface_20reduction_277',['Attack Surface Reduction',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md661',1,'']]],
  ['attempts_278',['Agent Grok (Level 30) Attempts',['../md_docs_2conflict__resolution__examples.html#autotoc_md1069',1,'']]],
  ['attributions_20credits_279',['Attributions &amp;amp; Credits',['../dir_f8bf3b3db987cef055901402344d3f8d.html#autotoc_md2256',1,'']]],
  ['audit_280',['Audit',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md892',1,'Document 3: Security Audit'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md734',1,'Example 2: Claude Security Audit'],['../md_docs_2workshop_2security-audit.html',1,'Workshop Tools Security Audit']]],
  ['audit_20md_281',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2security-audit.html&quot;&gt;security-audit.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1837',1,'']]],
  ['audit_20md_20security_20audit_20md_282',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2security-audit.html&quot;&gt;security-audit.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1837',1,'']]],
  ['audit_20scope_283',['Audit Scope',['../md_docs_2workshop_2security-audit.html#autotoc_md1854',1,'']]],
  ['audit_20workflow_284',['Example: Security Audit Workflow',['../md_docs_2global-workspace.html#autotoc_md1321',1,'']]],
  ['audit_20workflow_20example_285',['Security Audit Workflow Example',['../md_skills_2claude__build.html#autotoc_md2119',1,'']]],
  ['auditing_286',['Security Auditing',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1846',1,'']]],
  ['auditing_20workflow_287',['Security Auditing Workflow',['../md_skills_2claude__build.html#autotoc_md2100',1,'']]],
  ['audits_288',['Audits',['../md_skills_2claude__build.html#autotoc_md2131',1,'Best Practices for Security Audits'],['../md_skills_2claude__build.html#autotoc_md2130',1,'Token Savings in Security Audits']]],
  ['authentication_289',['Authentication',['../md_docs_2socket__interface.html#autotoc_md1651',1,'']]],
  ['author_290',['Author',['../md_README.html#autotoc_md2052',1,'']]],
  ['authorization_20matrix_291',['Command Authorization Matrix',['../md_docs_2privilege__mapping__quickref.html#autotoc_md1499',1,'']]],
  ['auto_20approve_20not_20default_20in_20collab_20mode_292',['Issue 3: Auto-approve Not Default in Collab Mode',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md183',1,'']]],
  ['auto_20approve_20not_20default_20in_20collab_20mode_20✅_293',['Issue 3: Auto-approve Not Default in Collab Mode ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md304',1,'']]],
  ['auto_20escalation_294',['Example 4: Deadline Auto-Escalation',['../md_docs_2conflict__resolution__examples.html#autotoc_md1071',1,'']]],
  ['autoconf_20configure_295',['Autoconf/Configure',['../md_skills_2build.html#autotoc_md2062',1,'']]],
  ['automated_20installation_20testing_296',['Automated Installation Testing',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1789',1,'']]],
  ['automated_20tests_297',['Run automated tests',['../md_docs_2references_2quick-reference.html#autotoc_md1574',1,'']]],
  ['automatic_298',['Basic Usage (Automatic)',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md761',1,'']]],
  ['automatic_20features_299',['Automatic Features',['../md_docs_2features_2anthropic-features.html#autotoc_md1132',1,'']]],
  ['automatic_20session_20checkpoint_300',['1. Automatic Session Checkpoint',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1697',1,'']]],
  ['automation_20—_20periodic_20summary_20broadcasts_301',['5. Automation — Periodic Summary Broadcasts',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md990',1,'']]],
  ['autosave_20on_20exit_302',['2. Session Persistence — Autosave on Exit',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md984',1,'']]],
  ['available_303',['Model Available',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1455',1,'']]],
  ['available_304',['Extended thinking not available',['../md_docs_2features_2anthropic-features.html#autotoc_md1156',1,'']]],
  ['available_20docs_305',['Available Docs',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md681',1,'']]],
  ['available_20falling_20back_20to_20unrestricted_20mode_306',['&quot;bubblewrap not available, falling back to unrestricted mode&quot;',['../md_docs_2features_2sandbox.html#autotoc_md1270',1,'']]],
  ['available_20features_307',['Available Features',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1235',1,'']]],
  ['available_20in_20runtime_308',['3. Features Available in Runtime',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1348',1,'']]],
  ['available_20models_309',['Available Models',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md567',1,'']]],
  ['available_20references_310',['Available References',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1589',1,'']]],
  ['award_20guidelines_311',['XP Award Guidelines',['../md_docs_2conflict__resolution__examples.html#autotoc_md1074',1,'']]],
  ['awards_312',['Awards',['../md_docs_2conflict__resolution__examples.html#autotoc_md1075',1,'Standard Awards'],['../md_docs_2references_2quick-reference.html#autotoc_md1566',1,'XP Awards'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1822',1,'XP Awards'],['../md_docs_2xp__voting.html#autotoc_md1941',1,'XP Awards']]],
  ['awards_20deduplication_313',['3. XP Awards Deduplication',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1091',1,'']]],
  ['awards_20dictionary_314',['✅ VALIDATED - XP Awards Dictionary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md882',1,'']]],
  ['axe_315',['AXE',['../md_AGENTS.html',1,'AGENTS.md for AXE'],['../md_docs_2features_2anthropic-features.html',1,'Anthropic Claude-Specific Features in AXE'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md731',1,'Integration with AXE'],['../md_docs_2xp__voting.html#autotoc_md1959',1,'Integration with AXE'],['../md_llm__prep_2project__guidance.html',1,'Project Guidance for AXE'],['../md_AGENTS.html#autotoc_md22',1,'Running AXE'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1629',1,'Starting AXE'],['../md_README.html#autotoc_md1989',1,'What is AXE?'],['../md_README.html#autotoc_md1991',1,'Why AXE?']]],
  ['axe_20agent_20execution_20engine_316',['AXE Agent eXecution Engine',['../md_MISSION.html',1,'AXE - Agent eXecution Engine'],['../md_README.html',1,'AXE - Agent eXecution Engine']]],
  ['axe_20agent_20execution_20engine_20✅_317',['AXE - Agent eXecution Engine ✅',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md192',1,'']]],
  ['axe_20always_20does_318',['What AXE ALWAYS Does',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1431',1,'']]],
  ['axe_20api_20provider_20documentation_319',['AXE API Provider Documentation',['../md_docs_2api-providers.html',1,'']]],
  ['axe_20architecture_20and_20extensibility_20guide_320',['AXE Architecture and Extensibility Guide',['../md_ARCHITECTURE.html',1,'']]],
  ['axe_20architecture_20diagrams_321',['AXE Architecture Diagrams',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1114',1,'']]],
  ['axe_20cognitive_20architecture_20working_20with_20ollama_322',['PROOF: AXE Cognitive Architecture Working with Ollama',['../md_docs_2PROOF__OLLAMA__DEMO.html',1,'']]],
  ['axe_20context_323',['What Is SRI in the AXE Context?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1684',1,'']]],
  ['axe_20directory_324',['2. Agent Interactions in AXE Directory',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1517',1,'']]],
  ['axe_20directory_20✅_325',['Test 5: Full Integration in AXE Directory ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1468',1,'']]],
  ['axe_20docs_20features_20anthropic_20features_20md_20anthropic_20features_20md_326',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2anthropic-features.html&quot;&gt;anthropic-features.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1239',1,'']]],
  ['axe_20docs_20features_20github_20agent_20integration_20md_20github_20agent_20integration_20md_327',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2github-agent-integration.html&quot;&gt;github-agent-integration.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1240',1,'']]],
  ['axe_20docs_20features_20parsers_20md_20parsers_20md_328',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2parsers.html&quot;&gt;parsers.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1238',1,'']]],
  ['axe_20docs_20features_20sandbox_20md_20sandbox_20md_329',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2sandbox.html&quot;&gt;sandbox.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1236',1,'']]],
  ['axe_20docs_20features_20write_20blocks_20md_20write_20blocks_20md_330',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2write-blocks.html&quot;&gt;write-blocks.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1237',1,'']]],
  ['axe_20docs_20references_20quick_20reference_20md_20quick_20reference_20md_331',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2references_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1590',1,'']]],
  ['axe_20docs_20workshop_20benchmarks_20md_20benchmarks_20md_332',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2benchmarks.html&quot;&gt;benchmarks.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1836',1,'']]],
  ['axe_20docs_20workshop_20dependency_20validation_20md_20dependency_20validation_20md_333',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2dependency-validation.html&quot;&gt;dependency-validation.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1838',1,'']]],
  ['axe_20docs_20workshop_20quick_20reference_20md_20quick_20reference_20md_334',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1835',1,'']]],
  ['axe_20docs_20workshop_20security_20audit_20md_20security_20audit_20md_335',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2security-audit.html&quot;&gt;security-audit.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1837',1,'']]],
  ['axe_20docs_20workshop_20test_20results_20md_20test_20results_20md_336',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2test-results.html&quot;&gt;test-results.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1839',1,'']]],
  ['axe_20documentation_337',['AXE Documentation',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1522',1,'']]],
  ['axe_20documentation_20archive_338',['AXE Documentation Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md960',1,'']]],
  ['axe_20enhancement_20implementation_20complete_20✅_339',['AXE Enhancement Implementation - Complete ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html',1,'']]],
  ['axe_20feature_20catalog_340',['AXE Feature Catalog',['../md_TODO.html',1,'']]],
  ['axe_20features_341',['AXE Features',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1234',1,'']]],
  ['axe_20framework_20compatibility_342',['AXE Framework Compatibility',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1799',1,'']]],
  ['axe_20improvement_20suggestions_343',['AXE Improvement Suggestions',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html',1,'']]],
  ['axe_20integration_344',['✅ Complete AXE Integration',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md820',1,'']]],
  ['axe_20live_20feature_20test_20results_345',['AXE Live Feature Test Results',['../md_docs_2LIVE__TEST__RESULTS.html',1,'']]],
  ['axe_20multi_20agent_20system_20improvement_20reference_20guide_346',['AXE Multi-Agent System - Improvement Reference Guide',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html',1,'']]],
  ['axe_20multi_20agent_20system_20model_20configuration_20reference_347',['AXE Multi-Agent System - Model Configuration Reference',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html',1,'']]],
  ['axe_20multiagent_20improvements_20implementation_20summary_348',['AXE Multiagent Improvements - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html',1,'']]],
  ['axe_20multiagent_20quick_20reference_20card_349',['AXE Multiagent - Quick Reference Card',['../md_docs_2references_2quick-reference.html',1,'']]],
  ['axe_20multiple_20issues_20fix_20summary_350',['AXE Multiple Issues Fix Summary',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html',1,'']]],
  ['axe_20native_20blocks_351',['AXE Native Blocks',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md609',1,'3. AXE Native Blocks'],['../md_docs_2features_2parsers.html#autotoc_md1217',1,'3. AXE Native Blocks']]],
  ['axe_20native_20format_352',['Example 3: AXE Native Format',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md603',1,'']]],
  ['axe_20native_20read_20write_20exec_20blocks_353',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md252',1,'']]],
  ['axe_20never_20does_354',['What AXE NEVER Does',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1430',1,'']]],
  ['axe_20project_20security_20report_355',['AXE Project Security Report',['../md_docs_2security.html',1,'']]],
  ['axe_20py_356',['axe py',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1346',1,'1. Code Integration (axe.py)'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1612',1,'1. Core Implementation (axe.py)'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1917',1,'3. CLI Argument Parsing (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1918',1,'4. Collaborative Session Support (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)'],['../md_docs_2WORKSPACE__FIX.html#autotoc_md1919',1,'5. New &lt;span class=&quot;tt&quot;&gt;/workspace&lt;/span&gt; Command (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)'],['../md_docs_2privilege__mapping.html#autotoc_md1480',1,'Integration: &lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;']]],
  ['axe_20py_20collaborativesession_357',['4. &lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt; (CollaborativeSession)',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md279',1,'']]],
  ['axe_20py_20refactoring_20notes_358',['AXE.PY Refactoring Notes',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html',1,'']]],
  ['axe_20py_20responseprocessor_359',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md253',1,'']]],
  ['axe_20quick_20references_360',['AXE Quick References',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1588',1,'']]],
  ['axe_20roadmap_361',['Implications for AXE Roadmap',['../md_docs_2SRI__AGENT__DISCUSSION.html#autotoc_md1680',1,'']]],
  ['axe_20runtime_362',['Integration Complete: Cognitive Architecture in AXE Runtime',['../md_docs_2INTEGRATION__COMPLETE.html',1,'']]],
  ['axe_20self_20analysis_20workspace_20axe_20source_363',['Section 9 – AXE Self-Analysis (workspace = AXE source)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1401',1,'']]],
  ['axe_20session_20termination_20bugs_364',['Fix Summary: AXE Session Termination Bugs',['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['axe_20sessions_365',['Using Cognitive Features in AXE Sessions',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1028',1,'']]],
  ['axe_20source_366',['Section 9 – AXE Self-Analysis (workspace = AXE source)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1401',1,'']]],
  ['axe_20test_20mission_367',['AXE Test Mission',['../md_tests_2MISSION.html',1,'']]],
  ['axe_20testing_20guide_368',['AXE Testing Guide',['../md_docs_2TESTING.html',1,'']]],
  ['axe_20user_20guide_369',['Cognitive Architecture in AXE - User Guide',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html',1,'']]],
  ['axe_20with_20updated_20code_370',['Restarting AXE With Updated Code',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1690',1,'']]],
  ['axe_20workshop_20tools_371',['AXE Workshop Tools',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1827',1,'']]],
  ['axe_20yaml_372',['axe yaml',['../md_docs_2codex-implementation.html#autotoc_md1013',1,'3. Agent Configuration (&lt;span class=&quot;tt&quot;&gt;axe.yaml&lt;/span&gt;)'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md181',1,'After (axe.yaml)'],['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md180',1,'Before (axe.yaml)'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md519',1,'Enable in axe.yaml'],['../md_skills_2build.html#autotoc_md2069',1,'Integration with axe.yaml']]],
  ['axe_20yaml_20build_20guidelines_20for_20all_20agents_373',['1. Updated axe.yaml - BUILD GUIDELINES for All Agents',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md718',1,'']]],
  ['axe_20yaml_20updates_374',['&lt;span class=&quot;tt&quot;&gt;axe.yaml&lt;/span&gt; Updates',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md750',1,'']]],
  ['axe_20yaml_20user_20configuration_375',['3. axe.yaml (User Configuration)',['../md_docs_2features_2configuration.html#autotoc_md1166',1,'']]]
];
