var searchData=
[
  ['r_0',['R',['../md_TODO.html#autotoc_md2213',1,'R'],['../md_TODO.html#autotoc_md2231',1,'R']]],
  ['race_20condition_20in_20database_20operations_1',['Issue #4: Race Condition in Database Operations',['../md_docs_2workshop_2security-audit.html#autotoc_md1862',1,'']]],
  ['random_20id_20generation_2',['Issue #5: Weak Random ID Generation',['../md_docs_2workshop_2security-audit.html#autotoc_md1863',1,'']]],
  ['ranks_20levels_3',['Agent Ranks &amp;amp; Levels',['../md_docs_2references_2quick-reference.html#autotoc_md1565',1,'']]],
  ['rate_20limiting_4',['Rate Limiting',['../md_docs_2workshop_2security-audit.html#autotoc_md1867',1,'Finding #3: No Rate Limiting'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md382',1,'Rate Limiting'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md581',1,'Rate Limiting']]],
  ['rate_20limiting_20✅_5',['3. Agent Rate Limiting ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md362',1,'']]],
  ['ray_6',['2. Adding Distributed Processing (Ray)',['../md_ARCHITECTURE.html#autotoc_md53',1,'']]],
  ['ray_20integration_20distributed_20ai_7',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md59',1,'']]],
  ['re_20applying_20manually_8',['Re-applying manually',['../dir_03443f88f6d5cae20798897259900ddf.html#autotoc_md2055',1,'']]],
  ['re_20run_9',['How to re-run',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1383',1,'']]],
  ['re_20run_20cppcheck_20with_20full_20details_10',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md2127',1,'']]],
  ['re_20run_20with_20full_20details_3a_11',['re run with full details:',['../md_skills_2claude__build.html#autotoc_md2109',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md2106',1,'If issues found, re-run with full details:']]],
  ['re_20run_20with_20verbose_20output_3a_12',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md2112',1,'']]],
  ['re_20toolchain_20summary_13',['RE Toolchain summary',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2197',1,'']]],
  ['read_20block_20access_20denied_14',['Issue 1: READ Block Access Denied',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md175',1,'']]],
  ['read_20block_20access_20denied_20✅_15',['Issue 1: READ Block Access Denied ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md300',1,'']]],
  ['read_20block_20sanitization_16',['READ block sanitization',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md307',1,'']]],
  ['read_20files_17',['READ - Read Files',['../md_docs_2features_2parsers.html#autotoc_md1222',1,'']]],
  ['read_20read_20files_18',['READ - Read Files',['../md_docs_2features_2parsers.html#autotoc_md1222',1,'']]],
  ['read_20write_20block_20syntax_19',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['read_20write_20block_20syntax_20✅_20',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md306',1,'']]],
  ['read_20write_20exec_20blocks_21',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md252',1,'']]],
  ['reading_22',['Further Reading',['../md_docs_2TESTING.html#autotoc_md1752',1,'']]],
  ['reading_20a_20file_20multiple_20ways_23',['Example 1: Reading a File (Multiple Ways)',['../md_docs_2features_2parsers.html#autotoc_md1230',1,'']]],
  ['readme_20md_24',['README md',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1353',1,'Academic References Added to README.md'],['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2182',1,'tests/fixtures/README.md']]],
  ['ready_25',['Integration Ready',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1334',1,'']]],
  ['ready_20codebase_20overview_20—_202026_2003_2017_26',['LLM-Ready Codebase Overview — 2026-03-17',['../md_llm__prep_2codebase__overview.html',1,'']]],
  ['ready_20for_20implementation_27',['Ready for Implementation',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md166',1,'']]],
  ['real_20bullying_28',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md463',1,'']]],
  ['real_20environment_29',['Testing in Real Environment',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1460',1,'']]],
  ['real_20world_20impact_30',['Real-World Impact',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md154',1,'']]],
  ['reason_31',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['reasoning_20✅_32',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md145',1,'']]],
  ['reasoning_20effort_20levels_33',['Reasoning Effort Levels',['../md_docs_2codex-implementation.html#autotoc_md1007',1,'']]],
  ['reasoning_20effort_20parameter_34',['Reasoning Effort Parameter',['../md_docs_2codex-implementation.html#autotoc_md1006',1,'']]],
  ['reasoning_20variants_35',['Pre-configured Reasoning Variants',['../md_docs_2codex-implementation.html#autotoc_md1008',1,'']]],
  ['reasons_36',['Vote Reasons',['../md_docs_2xp__voting.html#autotoc_md1958',1,'']]],
  ['recognized_37',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md465',1,'']]],
  ['recommendation_38',['Recommendation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md943',1,'Part 11: Merge Recommendation'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md854',1,'Recommendation']]],
  ['recommendations_39',['Recommendations',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md945',1,'Post-Merge Recommendations'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md168',1,'Recommendations'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1771',1,'Recommendations'],['../md_docs_2workshop_2dependency-validation.html#autotoc_md1804',1,'Recommendations'],['../md_docs_2workshop_2security-audit.html#autotoc_md1878',1,'Recommendations'],['../md_docs_2workshop_2test-results.html#autotoc_md1908',1,'Recommendations'],['../md_docs_2workshop_2security-audit.html#autotoc_md1872',1,'Security Recommendations']]],
  ['recommendations_20prioritized_40',['Recommendations (Prioritized)',['../md_docs_2security.html#autotoc_md1608',1,'']]],
  ['recommended_20models_20for_20testing_20ci_41',['Recommended Models for Testing/CI',['../md_docs_2ollama-guide.html#autotoc_md1437',1,'']]],
  ['recommended_20next_20steps_42',['Recommended Next Steps',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1704',1,'']]],
  ['recommended_20weights_43',['Recommended Weights',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md426',1,'']]],
  ['recommended_20work_20duration_20limits_44',['Recommended Work Duration Limits',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md420',1,'']]],
  ['recover_5fhigh_5flevel_5fmodel_45',['recover_high_level_model',['../md_skills_2recover__high__level__model.html',1,'']]],
  ['recovery_46',['Recovery',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1803',1,'Error Recovery'],['../md_docs_2workshop_2security-audit.html#autotoc_md1866',1,'Finding #2: Limited Error Recovery']]],
  ['recursive_20improvement_20—_20future_20work_47',['SRI (Self-Recursive Improvement) — Future Work',['../md_docs_2SRI__FUTURE__WORK.html',1,'']]],
  ['redirects_20without_20spaces_48',['2. Redirects Without Spaces',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md697',1,'']]],
  ['reduction_49',['Reduction',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md661',1,'Attack Surface Reduction'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md512',1,'Token Reduction']]],
  ['refactor_20implementation_20summary_50',['Configuration Refactor - Implementation Summary',['../md_docs_2REFACTOR__SUMMARY.html',1,'']]],
  ['refactoring_20approach_20conflict_51',['Example 2: Refactoring Approach Conflict',['../md_docs_2conflict__resolution__examples.html#autotoc_md1061',1,'']]],
  ['refactoring_20expert_52',['C++ Refactoring Expert',['../md_skills_2cpp__refactoring__expert.html',1,'']]],
  ['refactoring_20notes_53',['AXE.PY Refactoring Notes',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html',1,'']]],
  ['refactoring_20prs_202_203_54',['Future Refactoring (PRs #2 &amp;amp; #3)',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md637',1,'']]],
  ['refactoring_20summary_55',['Refactoring Summary',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md613',1,'']]],
  ['refactors_56',['Common Refactors',['../md_skills_2cpp__refactoring__expert.html#autotoc_md2157',1,'']]],
  ['reference_57',['Reference',['../md_docs_2global-workspace.html#autotoc_md1305',1,'API Reference'],['../md_docs_2socket__interface.html#autotoc_md1664',1,'API Reference'],['../md_docs_2xp__voting.html#autotoc_md1942',1,'API Reference'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html',1,'AXE Multi-Agent System - Model Configuration Reference'],['../md_docs_2features_2anthropic-features.html#autotoc_md1149',1,'Configuration Reference'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md890',1,'Document 1: Quick Reference'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html',1,'Multi-Format Tool Call Parser - Quick Reference'],['../md_docs_2privilege__mapping__quickref.html',1,'Privilege Mapping Quick Reference'],['../md__8collab__env.html#autotoc_md7',1,'Quick Reference'],['../md_docs_2api-providers.html#autotoc_md109',1,'Quick Reference'],['../md_skills_2claude__build.html#autotoc_md2140',1,'Security Tool Quick Reference'],['../md_MISSION.html#autotoc_md1980',1,'Token Reference'],['../md_docs_2workshop_2quick-reference.html',1,'Workshop Tools Quick Reference'],['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html',1,'XML Function Call Support - Quick Reference']]],
  ['reference_58',['dumpexe command reference',['../dir_b87ca3cfcec86d8417c05c08ca43e288.html#autotoc_md2190',1,'']]],
  ['reference_20card_59',['AXE Multiagent - Quick Reference Card',['../md_docs_2references_2quick-reference.html',1,'']]],
  ['reference_20commands_60',['Quick Reference Commands',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md474',1,'']]],
  ['reference_20data_61',['1. models.yaml (Static Model Reference Data)',['../md_docs_2features_2configuration.html#autotoc_md1164',1,'']]],
  ['reference_20guide_62',['AXE Multi-Agent System - Improvement Reference Guide',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html',1,'']]],
  ['reference_20md_63',['reference md',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1590',1,'&lt;a class=&quot;el&quot; href=&quot;md_docs_2references_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1835',1,'&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;']]],
  ['reference_20md_20quick_20reference_20md_64',['reference md quick reference md',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1590',1,'&lt;a class=&quot;el&quot; href=&quot;md_docs_2references_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1835',1,'&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;']]],
  ['references_65',['References',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1589',1,'Available References'],['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1588',1,'AXE Quick References'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md161',1,'Quick References'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md530',1,'References'],['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md644',1,'References'],['../md_docs_2codex-implementation.html#autotoc_md1022',1,'References'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1050',1,'References'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1108',1,'References'],['../md_docs_2features_2anthropic-features.html#autotoc_md1159',1,'References'],['../md_docs_2features_2sandbox.html#autotoc_md1275',1,'References'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1342',1,'References'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1432',1,'References'],['../md_docs_2privilege__mapping.html#autotoc_md1495',1,'References'],['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1526',1,'References'],['../md_docs_2subsumption__architecture.html#autotoc_md1727',1,'References'],['../md_skills_2build.html#autotoc_md2093',1,'References'],['../md_skills_2claude__build.html#autotoc_md2150',1,'References'],['../md_TODO.html#autotoc_md2250',1,'References'],['../md_README.html#autotoc_md2044',1,'Scientific References'],['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1595',1,'Using These References']]],
  ['references_20added_20to_20readme_20md_66',['Academic References Added to README.md',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1353',1,'']]],
  ['references_20quick_20reference_20md_20quick_20reference_20md_67',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2references_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;',['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1590',1,'']]],
  ['regression_20testing_68',['Regression Testing',['../md_docs_2workshop_2test-results.html#autotoc_md1900',1,'']]],
  ['regression_20testing_20silent_69',['Pattern 3: Regression Testing (Silent)',['../md_skills_2claude__build.html#autotoc_md2147',1,'']]],
  ['regressions_70',['✅ No Regressions',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md375',1,'']]],
  ['regressions_71',['Check for regressions',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md406',1,'']]],
  ['rejection_20and_20feedback_72',['Rejection and Feedback',['../md_docs_2features_2github-agent-integration.html#autotoc_md1204',1,'']]],
  ['related_20collaboration_20files_73',['Related Collaboration Files',['../md__8collab__shared.html#autotoc_md13',1,'']]],
  ['related_20documentation_74',['Related Documentation',['../md_docs_2features_2configuration.html#autotoc_md1192',1,'Related Documentation'],['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1243',1,'Related Documentation'],['../dir_40532c8bf6e900a8fce3c7e85195e014.html#autotoc_md1594',1,'Related Documentation'],['../md_docs_2socket__interface.html#autotoc_md1663',1,'Related Documentation'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1848',1,'Related Documentation'],['../md_docs_2xp__voting.html#autotoc_md1962',1,'Related Documentation']]],
  ['related_20systems_75',['Related Systems',['../md_docs_2privilege__mapping.html#autotoc_md1496',1,'']]],
  ['release_76',['Manual Release',['../md_docs_2subsumption__architecture.html#autotoc_md1714',1,'']]],
  ['release_20restore_20control_77',['4. Release (Restore Control)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1034',1,'']]],
  ['relevant_20output_78',['2. Focus on Security-Relevant Output',['../md_skills_2claude__build.html#autotoc_md2133',1,'']]],
  ['reliability_20metrics_79',['Reliability Metrics',['../md_docs_2workshop_2test-results.html#autotoc_md1899',1,'']]],
  ['removal_80',['Removal',['../md_docs_2features_2github-agent-integration.html#autotoc_md1207',1,'']]],
  ['remove_20all_20output_81',['❌ Don&apos;t Remove All Output',['../md_skills_2build.html#autotoc_md2078',1,'']]],
  ['remove_20workspace_82',['Test 4: Remove Workspace',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1366',1,'']]],
  ['removed_3a_20axe_20native_20read_20write_20exec_20blocks_83',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md252',1,'']]],
  ['repl_20integration_84',['REPL Integration',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1621',1,'']]],
  ['report_85',['Report',['../md_docs_2security.html',1,'AXE Project Security Report'],['../md_docs_2workshop_2test-results.html#autotoc_md1895',1,'Code Coverage Report'],['../md_skills_2dos__packer__detector.html#autotoc_md2164',1,'DOS Packer Detection Report'],['../md_skills_2claude__build.html#autotoc_md2129',1,'Phase 4: Security Report'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html',1,'PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report']]],
  ['reporting_86',['7. Token Savings — Verification and Reporting',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md994',1,'']]],
  ['reports_87',['PR Reports (&lt;span class=&quot;tt&quot;&gt;pr-reports/&lt;/span&gt;)',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md963',1,'']]],
  ['reports_20index_88',['PR Reports Index',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md972',1,'']]],
  ['reports_20pr_20reports_89',['PR Reports (&lt;span class=&quot;tt&quot;&gt;pr-reports/&lt;/span&gt;)',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md963',1,'']]],
  ['reputation_90',['2. XP Voting (Peer Reputation)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1032',1,'']]],
  ['request_20process_91',['Pull Request Process',['../md_AGENTS.html#autotoc_md41',1,'']]],
  ['request_20protocol_92',['Request Protocol',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md439',1,'']]],
  ['required_93',['⚠️ Manual Testing Required',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md372',1,'']]],
  ['required_94',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1117',1,'']]],
  ['required_20dependencies_95',['Required Dependencies',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md926',1,'']]],
  ['requirements_96',['Requirements',['../md_AGENTS.html#autotoc_md20',1,'Requirements'],['../md_docs_2api-providers.html#autotoc_md85',1,'Requirements'],['../md_docs_2api-providers.html#autotoc_md103',1,'Requirements'],['../md_docs_2features_2github-agent-integration.html#autotoc_md1205',1,'Requirements'],['../md_docs_2features_2sandbox.html#autotoc_md1251',1,'Requirements'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1843',1,'Requirements'],['../md_AGENTS.html#autotoc_md25',1,'Test Requirements']]],
  ['requirements_20txt_97',['Added to requirements.txt',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md843',1,'']]],
  ['requires_20api_20keys_98',['Manual testing (requires API keys)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md407',1,'']]],
  ['requires_20bubblewrap_20ollama_99',['Manual Testing (Requires bubblewrap + ollama)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1925',1,'']]],
  ['requires_20graphviz_100',['Command Line (Requires GraphViz)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md1118',1,'']]],
  ['requires_5fack_5fonly_20false_20limit_2050_101',['&lt;span class=&quot;tt&quot;&gt;get_broadcasts(since=None, category=None, agent=None, requires_ack_only=False, limit=50)&lt;/span&gt;',['../md_docs_2global-workspace.html#autotoc_md1309',1,'']]],
  ['reset_5fvote_5flimits_102',['&lt;span class=&quot;tt&quot;&gt;reset_vote_limits()&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1949',1,'']]],
  ['resolution_103',['Resolution',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1036',1,'6. Arbitration Resolution'],['../md_docs_2conflict__resolution__examples.html#autotoc_md1065',1,'Arbitration and Resolution']]],
  ['resolution_20broadcast_104',['Resolution Broadcast',['../md_docs_2conflict__resolution__examples.html#autotoc_md1060',1,'']]],
  ['resolution_20examples_105',['Conflict Resolution Examples',['../md_docs_2conflict__resolution__examples.html',1,'']]],
  ['resolution_20testing_106',['Dependency Resolution Testing',['../md_docs_2workshop_2dependency-validation.html#autotoc_md1790',1,'']]],
  ['resolved_107',['Resolved',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1088',1,'Integration Challenges Resolved'],['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md396',1,'Issues Resolved']]],
  ['resolves_108',['Supervisor-Level Agent (Level 50) Resolves',['../md_docs_2conflict__resolution__examples.html#autotoc_md1070',1,'']]],
  ['resource_20controls_20verified_109',['Resource Controls - VERIFIED',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md910',1,'']]],
  ['resource_20monitoring_110',['Resource Monitoring',['../md__8collab__env.html#autotoc_md10',1,'Resource Monitoring'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md467',1,'Resource Monitoring'],['../md_docs_2references_2quick-reference.html#autotoc_md1572',1,'Resource Monitoring']]],
  ['resource_20tracking_20✅_111',['Phase 5: Resource Tracking ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md484',1,'']]],
  ['resource_20usage_112',['Checking Resource Usage',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md496',1,'']]],
  ['resource_20utilization_20trends_113',['Resource Utilization Trends',['../md_docs_2workshop_2benchmarks.html#autotoc_md1770',1,'']]],
  ['resources_114',['Resources',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1533',1,'📖 Additional Resources'],['../md_AGENTS.html#autotoc_md44',1,'Additional Resources'],['../md_docs_2ollama-guide.html#autotoc_md1451',1,'Additional Resources'],['../md__8collab__env.html#autotoc_md2',1,'Resources'],['../md_docs_2workshop_2test-results.html#autotoc_md1906',1,'System Resources'],['../md_docs_2ollama-guide.html#autotoc_md1438',1,'Tiny Models (&amp;lt; 1GB) - Best for CI/Minimal Resources']]],
  ['respect_20well_20being_20–_20no_20real_20bullying_115',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md463',1,'']]],
  ['response_116',['4. Multiple Files in One Response',['../md_docs_2features_2write-blocks.html#autotoc_md1285',1,'']]],
  ['response_117',['Append results to response',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md400',1,'']]],
  ['response_20commented_20out_118',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md255',1,'']]],
  ['response_20format_119',['Response Format',['../md_docs_2socket__interface.html#autotoc_md1643',1,'']]],
  ['response_20qwen2_205_20coder_3a1_205b_120',['Supervisor response (qwen2.5-coder:1.5b)',['../md_docs_2SRI__AGENT__DISCUSSION.html#autotoc_md1676',1,'']]],
  ['responseprocessor_121',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md253',1,'']]],
  ['responses_20api_20vs_20chat_20completions_122',['Key Differences: Responses API vs Chat Completions',['../md_docs_2codex-implementation.html#autotoc_md1016',1,'']]],
  ['restart_20slash_20command_20primitive_123',['3. &lt;span class=&quot;tt&quot;&gt;restart&lt;/span&gt; Slash Command / Primitive',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1699',1,'']]],
  ['restarting_20axe_20with_20updated_20code_124',['Restarting AXE With Updated Code',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1690',1,'']]],
  ['restore_20control_125',['4. Release (Restore Control)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1034',1,'']]],
  ['restricted_20sandbox_20with_20blacklist_126',['Example 2: Restricted Sandbox with Blacklist',['../md_docs_2features_2sandbox.html#autotoc_md1257',1,'']]],
  ['restrictions_127',['Environment Restrictions',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md666',1,'']]],
  ['result_128',['Result',['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html#autotoc_md1457',1,'']]],
  ['result_3a_129',['Result:',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md352',1,'']]],
  ['results_130',['Results',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1347',1,'2. Verification Results'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1623',1,'Analysis Results'],['../md_docs_2LIVE__TEST__RESULTS.html',1,'AXE Live Feature Test Results'],['../md_docs_2workshop_2test-results.html#autotoc_md1888',1,'Detailed Test Results'],['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md894',1,'Document 5: Test Results'],['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md155',1,'Integration Test Results'],['../md_docs_2OLLAMA__BATCH__TEST__RESULTS.html',1,'Ollama Batch Mode Test Results'],['../md_docs_2OLLAMA__TEST__RESULTS.html',1,'Ollama Integration Test Results'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1409',1,'Overall Results'],['../md_docs_2workshop_2security-audit.html#autotoc_md1873',1,'Penetration Testing Results'],['../md_docs_2workshop_2benchmarks.html#autotoc_md1754',1,'Performance Analysis Results'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md511',1,'Performance Results'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md127',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md206',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md235',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md263',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md346',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md513',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md596',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md655',1,'Test Results'],['../md_docs_2archive_2implementation-summaries_2TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md780',1,'Test Results'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1549',1,'Test Results'],['../md_docs_2workshop_2security-audit.html#autotoc_md1875',1,'Test Results'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1098',1,'Testing Results'],['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html#autotoc_md1335',1,'Testing Results'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1625',1,'Testing Results'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md835',1,'Validation Results'],['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md726',1,'Verification Results'],['../md_docs_2workshop_2test-results.html',1,'Workshop Tools Test Suite Execution Results']]],
  ['results_20appearing_131',['No Results Appearing?',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md809',1,'']]],
  ['results_20md_132',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2test-results.html&quot;&gt;test-results.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1839',1,'']]],
  ['results_20md_20test_20results_20md_133',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2test-results.html&quot;&gt;test-results.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1839',1,'']]],
  ['results_20test_5fworkshop_20py_134',['Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1889',1,'']]],
  ['results_20test_5fworkshop_5fintegration_20py_135',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1890',1,'']]],
  ['results_20test_5fworkshop_5fperformance_20py_136',['Performance Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_performance.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1891',1,'']]],
  ['results_20test_5fworkshop_5fsecurity_20py_137',['Security Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_security.py&lt;/span&gt;)',['../md_docs_2workshop_2test-results.html#autotoc_md1892',1,'']]],
  ['results_20to_20response_138',['Append results to response',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md400',1,'']]],
  ['results_20workspace_20commands_139',['Interactive Testing Results - Workspace Commands',['../md_docs_2INTERACTIVE__TEST__RESULTS.html',1,'']]],
  ['resume_20later_140',['&quot;Want to resume later&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1584',1,'']]],
  ['resume_20save_20✅_141',['2. Session Resume/Save ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md361',1,'']]],
  ['retry_20with_20verbose_20on_20failure_142',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md2073',1,'']]],
  ['reverse_20engineering_143',['Reverse Engineering',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1845',1,'']]],
  ['reverse_20engineering_20expert_144',['Reverse Engineering Expert',['../md_skills_2reverse__engineering__expert.html',1,'']]],
  ['reverse_20engineering_20tools_145',['Reverse Engineering Tools',['../md__8collab__env.html#autotoc_md4',1,'']]],
  ['reverse_20engineering_20workflow_20—_20dumpexe_20integration_146',['6. Reverse-Engineering Workflow — dumpexe Integration',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md992',1,'']]],
  ['reverse_20engineering_20workflow_20notes_147',['Reverse-Engineering Workflow Notes',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md1000',1,'']]],
  ['review_148',['Code Review',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md152',1,'']]],
  ['review_20addressed_149',['Code Review Addressed',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md714',1,'']]],
  ['review_20checklist_150',['Code Review Checklist',['../md_AGENTS.html#autotoc_md42',1,'']]],
  ['review_20findings_151',['Review findings',['../md_skills_2claude__build.html#autotoc_md2115',1,'']]],
  ['review_20flow_152',['Review Flow',['../md_docs_2features_2github-agent-integration.html#autotoc_md1203',1,'']]],
  ['review_20interface_153',['Review Interface',['../md_docs_2features_2github-agent-integration.html#autotoc_md1199',1,'']]],
  ['review_20issues_20addressed_154',['Review Issues Addressed',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md592',1,'Code Review Issues Addressed'],['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1627',1,'Code Review Issues Addressed']]],
  ['rewards_20–_20good_20work_20gets_20recognized_155',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md465',1,'']]],
  ['rewards_20for_20good_20output_156',['4. Supervision Behaviour — XP Rewards for Good Output',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md988',1,'']]],
  ['risk_20assessment_157',['Risk Assessment',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md947',1,'Part 12: Risk Assessment'],['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md851',1,'Risk Assessment']]],
  ['risk_3a_20⚠️_20low_158',['Merge Risk: ⚠️ LOW',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md852',1,'']]],
  ['risks_3a_20low_159',['Merge Risks: LOW',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md948',1,'']]],
  ['roadmap_160',['Implications for AXE Roadmap',['../md_docs_2SRI__AGENT__DISCUSSION.html#autotoc_md1680',1,'']]],
  ['robin_20multi_20agent_161',['🔄 Turn-based Round-Robin Multi-Agent',['../md_TODO.html#autotoc_md2242',1,'']]],
  ['robust_162',['Error Handling - ROBUST',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md917',1,'']]],
  ['role_163',['Role',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md976',1,'Ollama Model Selection and Supervisor Role'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md499',1,'Supervisor Role']]],
  ['role_20assignment_164',['Supervisor Role Assignment',['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md577',1,'']]],
  ['rollback_20plan_165',['Rollback Plan',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md949',1,'']]],
  ['root_20cause_166',['Root Cause',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md120',1,'Root Cause'],['../md_docs_2archive_2implementation-summaries_2COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md213',1,'Root Cause'],['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md249',1,'Root Cause'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md327',1,'Root Cause']]],
  ['root_20cause_20analysis_167',['Root Cause Analysis',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md339',1,'']]],
  ['root_20directory_168',['Project Files (Root Directory)',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1534',1,'']]],
  ['round_20robin_20multi_20agent_169',['🔄 Turn-based Round-Robin Multi-Agent',['../md_TODO.html#autotoc_md2242',1,'']]],
  ['rule_3a_20lowercase_20no_20prefixes_170',['General Rule: Lowercase, No Prefixes',['../md_docs_2features_2configuration.html#autotoc_md1173',1,'']]],
  ['rules_171',['Rules',['../md_docs_2features_2configuration.html#autotoc_md1172',1,'Model ID Rules'],['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1553',1,'Model ID Rules'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md453',1,'Rules'],['../md_docs_2subsumption__architecture.html#autotoc_md1719',1,'Suppression Rules'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md495',1,'Viewing Session Rules'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md460',1,'Workplace Rules']]],
  ['rules_20guidelines_20✅_172',['Phase 1: Session Rules &amp;amp; Guidelines ✅',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md480',1,'']]],
  ['rules_20integration_173',['Session Rules Integration',['../md_docs_2conflict__resolution__examples.html#autotoc_md1081',1,'']]],
  ['rules_20the_204_20principles_174',['Session Rules (The 4 Principles)',['../md_docs_2references_2quick-reference.html#autotoc_md1564',1,'']]],
  ['run_175',['How to re-run',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1383',1,'']]],
  ['run_20all_20unit_20tests_176',['Run all unit tests',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md405',1,'']]],
  ['run_20automated_20tests_177',['Run automated tests',['../md_docs_2references_2quick-reference.html#autotoc_md1574',1,'']]],
  ['run_20clang_20static_20analyzer_20quietly_178',['Run Clang static analyzer quietly',['../md_skills_2claude__build.html#autotoc_md2114',1,'']]],
  ['run_20cmd_3a_20str_20lines_201544_201629_179',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md694',1,'']]],
  ['run_20commands_180',['EXEC - Run Commands',['../md_docs_2features_2parsers.html#autotoc_md1225',1,'']]],
  ['run_20cppcheck_20with_20full_20details_181',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md2127',1,'']]],
  ['run_20full_20scan_3a_182',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md2118',1,'']]],
  ['run_20interactive_20demo_183',['Run interactive demo',['../md_docs_2references_2quick-reference.html#autotoc_md1575',1,'']]],
  ['run_20method_184',['1. Defensive Programming in &lt;span class=&quot;tt&quot;&gt;run()&lt;/span&gt; Method',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md342',1,'']]],
  ['run_20static_20analysis_20quietly_185',['Run static analysis quietly',['../md_skills_2claude__build.html#autotoc_md2108',1,'']]],
  ['run_20tests_20quietly_186',['Run tests quietly',['../md_skills_2build.html#autotoc_md2087',1,'']]],
  ['run_20tests_20silently_187',['Run tests silently',['../md_skills_2build.html#autotoc_md2090',1,'']]],
  ['run_20tests_20silently_188',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md2111',1,'']]],
  ['run_20with_20full_20details_3a_189',['run with full details:',['../md_skills_2claude__build.html#autotoc_md2109',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md2106',1,'If issues found, re-run with full details:']]],
  ['run_20with_20verbose_20output_3a_190',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md2112',1,'']]],
  ['runner_20integration_20core_20tool_5frunner_20py_191',['2. Tool Runner Integration (&lt;span class=&quot;tt&quot;&gt;core/tool_runner.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1916',1,'']]],
  ['running_192',['Server Not Running?',['../md_docs_2ollama-guide.html#autotoc_md1446',1,'']]],
  ['running_20axe_193',['Running AXE',['../md_AGENTS.html#autotoc_md22',1,'']]],
  ['running_20in_20background_194',['1. Ollama Running in Background',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1516',1,'']]],
  ['running_20interactive_20gui_20tests_20with_20xvfb_195',['Running interactive/GUI tests with Xvfb',['../md_docs_2TESTING.html#autotoc_md1744',1,'']]],
  ['running_20tests_196',['Running Tests',['../md_AGENTS.html#autotoc_md24',1,'']]],
  ['running_20the_20tests_197',['Running the Tests',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1470',1,'']]],
  ['runtime_198',['Runtime',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1348',1,'3. Features Available in Runtime'],['../md_docs_2INTEGRATION__COMPLETE.html',1,'Integration Complete: Cognitive Architecture in AXE Runtime'],['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1356',1,'Key Differences: Demos vs Runtime']]],
  ['runtime_20analysis_20silent_199',['Runtime analysis silent',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md736',1,'Runtime analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md2143',1,'Runtime analysis (silent)']]],
  ['runtime_20detection_200',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md2128',1,'']]],
  ['runtime_20directory_20fallback_201',['Runtime Directory Fallback',['../md_docs_2SOCKET__IMPLEMENTATION__SUMMARY.html#autotoc_md1617',1,'']]],
  ['runtime_20logs_202',['Demo Output (Actual Runtime Logs)',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1514',1,'']]],
  ['runtime_20verification_203',['Runtime Verification',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1359',1,'']]]
];
