var searchData=
[
  ['x_0',['X',['../md_TODO.html#autotoc_md2218',1,'']]],
  ['x86_20assembly_20analysis_20expert_1',['x86 Assembly Analysis Expert',['../md_skills_2x86__assembly__expert.html',1,'']]],
  ['xai_20grok_2',['xAI Grok',['../md_docs_2api-providers.html#autotoc_md92',1,'xAI (Grok)'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md558',1,'xAI (Grok)'],['../md_README.html#autotoc_md2030',1,'xAI (Grok)']]],
  ['xml_20format_20new_3',['XML Format (New!)',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md803',1,'']]],
  ['xml_20function_20call_20parser_20implementation_20summary_4',['XML Function Call Parser - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html',1,'']]],
  ['xml_20function_20call_20support_5',['XML Function Call Support',['../md_docs_2features_2parsers.html#autotoc_md1220',1,'']]],
  ['xml_20function_20call_20support_20quick_20reference_6',['XML Function Call Support - Quick Reference',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['xml_20function_20calls_20standard_20llm_20format_7',['5. XML Function Calls (Standard LLM Format)',['../md_docs_2features_2parsers.html#autotoc_md1219',1,'']]],
  ['xml_20tag_20formats_20not_20supported_20✅_8',['Bug 1: XML Tag Formats Not Supported ✅',['../md_docs_2archive_2implementation-summaries_2BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['xml_20tags_9',['4. Simple XML Tags',['../md_docs_2features_2parsers.html#autotoc_md1218',1,'']]],
  ['xml_20tags_20claude_20s_20favorite_10',['XML Tags Claude s Favorite',['../md_docs_2archive_2implementation-summaries_2MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md607',1,'1. Bash XML Tags (Claude&apos;s Favorite)'],['../md_docs_2features_2parsers.html#autotoc_md1215',1,'1. Bash XML Tags (Claude&apos;s Favorite)']]],
  ['xml_20tags_20like_11',['5. Simple XML tags like &amp;lt;read_file&amp;gt;, &amp;lt;shell&amp;gt;',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md256',1,'']]],
  ['xml_20tool_20parser_20test_20suite_12',['XML TOOL PARSER TEST SUITE',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__IMPLEMENTATION.html#autotoc_md789',1,'']]],
  ['xp_20award_20guidelines_13',['XP Award Guidelines',['../md_docs_2conflict__resolution__examples.html#autotoc_md1074',1,'']]],
  ['xp_20awards_14',['XP Awards',['../md_docs_2references_2quick-reference.html#autotoc_md1566',1,'XP Awards'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1822',1,'XP Awards'],['../md_docs_2xp__voting.html#autotoc_md1941',1,'XP Awards']]],
  ['xp_20awards_20deduplication_15',['3. XP Awards Deduplication',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1091',1,'']]],
  ['xp_20awards_20dictionary_16',['✅ VALIDATED - XP Awards Dictionary',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md882',1,'']]],
  ['xp_20calculation_17',['✅ VALIDATED - Bonus XP Calculation',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md883',1,'']]],
  ['xp_20level_20system_18',['XP &amp;amp; Level System',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md455',1,'']]],
  ['xp_20level_20title_20progression_19',['XP Level Title Progression',['../md_TODO.html#autotoc_md2243',1,'🎮 XP/Level/Title Progression'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1405',1,'Section 11 – XP / Level / Title Progression']]],
  ['xp_20rewards_20for_20good_20output_20',['4. Supervision Behaviour — XP Rewards for Good Output',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md988',1,'']]],
  ['xp_20sources_21',['XP Sources',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md457',1,'']]],
  ['xp_20system_22',['XP System',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md848',1,'XP System'],['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1097',1,'XP System'],['../md_docs_2workshop_2quick-reference.html#autotoc_md1821',1,'XP System']]],
  ['xp_20system_20integration_23',['Claim 3: XP System Integration',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md881',1,'']]],
  ['xp_20system_20integration_20complete_24',['XP System Integration - COMPLETE',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html#autotoc_md903',1,'']]],
  ['xp_20voting_20minsky_201986_25',['XP Voting (Minsky, 1986)',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1351',1,'']]],
  ['xp_20voting_20peer_20reputation_26',['2. XP Voting (Peer Reputation)',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1032',1,'']]],
  ['xp_20voting_20system_27',['Peer XP Voting System',['../md_docs_2xp__voting.html',1,'']]],
  ['xp_20voting_20system_20database_20✅_28',['Test 3: XP Voting System + Database ✅',['../md_docs_2OLLAMA__TEST__RESULTS.html#autotoc_md1466',1,'']]],
  ['xp_20voting_20system_20minsky_201986_29',['PR #55: XP Voting System (Minsky 1986)',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1086',1,'']]],
  ['xp_5fdelta_20reason_30',['&lt;span class=&quot;tt&quot;&gt;vote_xp(voter_alias, voter_level, target_alias, xp_delta, reason)&lt;/span&gt;',['../md_docs_2xp__voting.html#autotoc_md1944',1,'']]],
  ['xvfb_31',['Running interactive/GUI tests with Xvfb',['../md_docs_2TESTING.html#autotoc_md1744',1,'']]]
];
