var searchData=
[
  ['w_0',['W',['../md_TODO.html#autotoc_md2217',1,'W'],['../md_TODO.html#autotoc_md2235',1,'W']]],
  ['wake_20up_20triggers_1',['Wake-up Triggers',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md417',1,'']]],
  ['want_20to_2',['I want to...',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1532',1,'']]],
  ['want_20to_20resume_20later_3',['&quot;Want to resume later&quot;',['../md_docs_2references_2quick-reference.html#autotoc_md1584',1,'']]],
  ['warning_20message_4',['2. Improved Warning Message',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1418',1,'']]],
  ['warning_20test_5',['Startup Warning Test',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1426',1,'']]],
  ['warnings_6',['Good: Only security warnings',['../md_skills_2claude__build.html#autotoc_md2134',1,'']]],
  ['was_20delivered_7',['What Was Delivered',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md818',1,'']]],
  ['was_20done_8',['What Was Done',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1540',1,'']]],
  ['was_20implemented_9',['What Was Implemented',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md717',1,'']]],
  ['wasted_20capacity_20fixed_20✓_10',['3. Wasted Capacity Fixed ✓',['../md_docs_2archive_2implementation-summaries_2DYNAMIC__TOKENS__SUMMARY.html#autotoc_md286',1,'']]],
  ['ways_11',['Example 1: Reading a File (Multiple Ways)',['../md_docs_2features_2parsers.html#autotoc_md1230',1,'']]],
  ['weak_20random_20id_20generation_12',['Issue #5: Weak Random ID Generation',['../md_docs_2workshop_2security-audit.html#autotoc_md1863',1,'']]],
  ['week_13',['Short-Term (This Week)',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md859',1,'']]],
  ['weights_14',['Recommended Weights',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md426',1,'']]],
  ['well_20being_20–_20no_20real_20bullying_15',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md463',1,'']]],
  ['what_20agents_20see_16',['What Agents See',['../md_docs_2references_2quick-reference.html#autotoc_md1580',1,'']]],
  ['what_20axe_20always_20does_17',['What AXE ALWAYS Does',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1431',1,'']]],
  ['what_20axe_20never_20does_18',['What AXE NEVER Does',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1430',1,'']]],
  ['what_20exists_20today_19',['What Exists Today',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1686',1,'']]],
  ['what_20is_20axe_20',['What is AXE?',['../md_README.html#autotoc_md1989',1,'']]],
  ['what_20is_20missing_20for_20full_20sri_21',['What Is Missing for Full SRI',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1692',1,'']]],
  ['what_20is_20sri_20in_20the_20axe_20context_22',['What Is SRI in the AXE Context?',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1684',1,'']]],
  ['what_20s_20integrated_3a_23',['What&apos;s Integrated:',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1026',1,'']]],
  ['what_20s_20missing_20without_20user_20namespace_24',['What&apos;s Missing Without User Namespace',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1423',1,'']]],
  ['what_20s_20new_25',['What&apos;s New?',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md800',1,'']]],
  ['what_20sandbox_20doesn_20t_20protect_20by_20design_26',['What Sandbox Doesn&apos;t Protect (by design)',['../md_docs_2features_2sandbox.html#autotoc_md1261',1,'']]],
  ['what_20sandbox_20protects_27',['What Sandbox Protects',['../md_docs_2features_2sandbox.html#autotoc_md1260',1,'']]],
  ['what_20this_20proves_28',['What This Proves',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1515',1,'']]],
  ['what_20was_20delivered_29',['What Was Delivered',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html#autotoc_md818',1,'']]],
  ['what_20was_20done_30',['What Was Done',['../md_docs_2REFACTOR__SUMMARY.html#autotoc_md1540',1,'']]],
  ['what_20was_20implemented_31',['What Was Implemented',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md717',1,'']]],
  ['what_20works_20without_20user_20namespace_32',['What Works Without User Namespace',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1422',1,'']]],
  ['what_20you_20need_33',['🔍 Finding What You Need',['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1531',1,'']]],
  ['when_20to_20use_20archive_34',['When to Use Archive',['../dir_764977a981e0196af530aae41d6254b7.html#autotoc_md966',1,'']]],
  ['when_20to_20use_20each_20level_35',['When to Use Each Level',['../md_docs_2codex-implementation.html#autotoc_md1009',1,'']]],
  ['when_20to_20use_20verbose_20output_36',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md36',1,'']]],
  ['when_20to_20vote_37',['When to Vote',['../md_docs_2xp__voting.html#autotoc_md1956',1,'']]],
  ['where_20to_20find_20it_3a_38',['Where to Find It:',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1027',1,'']]],
  ['whichever_20exists_39',['Only one present: use whichever exists',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md329',1,'']]],
  ['whitelist_20mode_40',['Compared to Whitelist Mode',['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md660',1,'']]],
  ['whitelist_20to_20sandbox_41',['From Whitelist to Sandbox',['../md_docs_2features_2sandbox.html#autotoc_md1268',1,'']]],
  ['whole_20block_20as_20a_20single_20command_42',['If so, treat the whole block as a single command',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md258',1,'']]],
  ['why_20axe_43',['Why AXE?',['../md_README.html#autotoc_md1991',1,'']]],
  ['why_20silent_20builds_44',['Why Silent Builds?',['../md_skills_2build.html#autotoc_md2058',1,'']]],
  ['why_20these_20limits_45',['Why These Limits?',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md421',1,'']]],
  ['why_20these_20modules_20first_46',['Why These Modules First?',['../md_docs_2archive_2implementation-summaries_2REFACTORING__NOTES.html#autotoc_md628',1,'']]],
  ['why_20this_20matters_47',['Why This Matters',['../md_docs_2archive_2implementation-summaries_2XML__PARSER__QUICK__REFERENCE.html#autotoc_md801',1,'']]],
  ['why_20this_20works_48',['Why This Works',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md330',1,'']]],
  ['why_20unshare_20user_20try_20is_20safe_49',['Why &lt;span class=&quot;tt&quot;&gt;--unshare-user-try&lt;/span&gt; is Safe',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1421',1,'']]],
  ['with_20addresssanitizer_20for_20runtime_20detection_50',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md2128',1,'']]],
  ['with_20agentmanager_51',['6. Integration with AgentManager',['../md_docs_2archive_2implementation-summaries_2SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md751',1,'']]],
  ['with_20agents_52',['Integration with Agents',['../md_docs_2workshop_2quick-reference.html#autotoc_md1824',1,'']]],
  ['with_20agents_20md_53',['Integration with AGENTS.md',['../md_skills_2claude__build.html#autotoc_md2141',1,'']]],
  ['with_20any_20talking_20model_54',['with ANY Talking Model',['../md_README.html#autotoc_md1993',1,'💬 Works with ANY Talking Model'],['../md_TODO.html#autotoc_md2239',1,'💬 Works with ANY Talking Model']]],
  ['with_20asan_20and_20run_20tests_20silently_55',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md2111',1,'']]],
  ['with_20axe_56',['with AXE',['../md_docs_2archive_2implementation-summaries_2SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md731',1,'Integration with AXE'],['../md_docs_2xp__voting.html#autotoc_md1959',1,'Integration with AXE']]],
  ['with_20axe_20yaml_57',['Integration with axe.yaml',['../md_skills_2build.html#autotoc_md2069',1,'']]],
  ['with_20blacklist_58',['Example 2: Restricted Sandbox with Blacklist',['../md_docs_2features_2sandbox.html#autotoc_md1257',1,'']]],
  ['with_20cache_20tracking_59',['Token Statistics with Cache Tracking',['../md_docs_2features_2anthropic-features.html#autotoc_md1148',1,'']]],
  ['with_20cloud_20models_60',['With Cloud Models',['../md_README.html#autotoc_md2020',1,'']]],
  ['with_20cmake_61',['Example 1: C++ Project with CMake',['../md_skills_2build.html#autotoc_md2082',1,'']]],
  ['with_20collaborations_62',['Integration with Collaborations',['../md_skills_2build.html#autotoc_md2070',1,'']]],
  ['with_20collaborative_20sessions_63',['Integration with Collaborative Sessions',['../md_docs_2global-workspace.html#autotoc_md1315',1,'']]],
  ['with_20full_20details_64',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md2127',1,'']]],
  ['with_20full_20details_3a_65',['with full details:',['../md_skills_2claude__build.html#autotoc_md2109',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md2106',1,'If issues found, re-run with full details:']]],
  ['with_20globalworkspace_66',['Integration with GlobalWorkspace',['../md_docs_2subsumption__architecture.html#autotoc_md1720',1,'']]],
  ['with_20level_67',['Vote Power Scales with Level',['../md_docs_2xp__voting.html#autotoc_md1936',1,'']]],
  ['with_20local_20ollama_20models_68',['With Local Ollama Models',['../md_README.html#autotoc_md2021',1,'']]],
  ['with_20make_69',['Example 3: Python Project with Make',['../md_skills_2build.html#autotoc_md2088',1,'']]],
  ['with_20maven_70',['Example 2: Java Project with Maven',['../md_skills_2build.html#autotoc_md2085',1,'']]],
  ['with_20minimal_20noise_71',['Comprehensive security scan with minimal noise',['../md_skills_2claude__build.html#autotoc_md2139',1,'']]],
  ['with_20new_20features_72',['Starting a Collaborative Session with New Features',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__README.html#autotoc_md494',1,'']]],
  ['with_20newline_20e_20g_20cat_20eof_73',['Both present: combine with newline (e.g., &quot;cat &amp;lt;&amp;lt; EOF&quot; + &quot;\\nlines\\nEOF&quot;)',['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md328',1,'']]],
  ['with_20ollama_74',['PROOF: AXE Cognitive Architecture Working with Ollama',['../md_docs_2PROOF__OLLAMA__DEMO.html',1,'']]],
  ['with_20other_20blocks_75',['Integration with Other Blocks',['../md_docs_2features_2write-blocks.html#autotoc_md1286',1,'']]],
  ['with_20other_20systems_76',['Integration with Other Systems',['../md_docs_2conflict__resolution__examples.html#autotoc_md1078',1,'']]],
  ['with_20parentheses_77',['1. Subshells with Parentheses',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md696',1,'']]],
  ['with_20quiet_20flags_78',['Configure with quiet flags',['../md_skills_2build.html#autotoc_md2083',1,'']]],
  ['with_20security_20flags_79',['Configure with security flags',['../md_skills_2claude__build.html#autotoc_md2121',1,'']]],
  ['with_20updated_20code_80',['Restarting AXE With Updated Code',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1690',1,'']]],
  ['with_20verbose_20on_20failure_81',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md2073',1,'']]],
  ['with_20verbose_20output_3a_82',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md2112',1,'']]],
  ['with_20xvfb_83',['Running interactive/GUI tests with Xvfb',['../md_docs_2TESTING.html#autotoc_md1744',1,'']]],
  ['without_20spaces_84',['2. Redirects Without Spaces',['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md697',1,'']]],
  ['without_20user_20namespace_85',['Without User Namespace',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1422',1,'What Works Without User Namespace'],['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1423',1,'What&apos;s Missing Without User Namespace']]],
  ['work_86',['Work',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1413',1,'Future Work'],['../md_docs_2SRI__FUTURE__WORK.html',1,'SRI (Self-Recursive Improvement) — Future Work'],['../md_docs_2archive_2implementation-summaries_2MODELS__FINAL.html#autotoc_md576',1,'Test Projects for Multi-Agent Work']]],
  ['work_20duration_20limits_87',['Recommended Work Duration Limits',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md420',1,'']]],
  ['work_20gets_20recognized_88',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md465',1,'']]],
  ['work_20in_20unrestricted_20mode_20but_20not_20sandbox_20mode_89',['Commands work in unrestricted mode but not sandbox mode',['../md_docs_2features_2sandbox.html#autotoc_md1272',1,'']]],
  ['worker_20levels_201_209_90',['Worker (Levels 1-9)',['../md_docs_2privilege__mapping.html#autotoc_md1482',1,'']]],
  ['worker_20team_20leader_20levels_2010_2019_91',['Senior Worker / Team Leader (Levels 10-19)',['../md_docs_2privilege__mapping.html#autotoc_md1483',1,'']]],
  ['workflow_92',['Workflow',['../md_docs_2global-workspace.html#autotoc_md1321',1,'Example: Security Audit Workflow'],['../md_docs_2archive_2implementation-summaries_2SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md670',1,'Scenario 1: Development Workflow'],['../md_skills_2claude__build.html#autotoc_md2100',1,'Security Auditing Workflow'],['../md_skills_2c__modernization__expert.html#autotoc_md2097',1,'Workflow'],['../md_skills_2cpp__modernization__expert.html#autotoc_md2154',1,'Workflow'],['../md_skills_2cpp__refactoring__expert.html#autotoc_md2158',1,'Workflow'],['../md_skills_2ida__pro__analysis__patterns.html#autotoc_md2168',1,'Workflow'],['../md_skills_2x86__assembly__expert.html#autotoc_md2180',1,'Workflow']]],
  ['workflow_20—_20dumpexe_20integration_93',['6. Reverse-Engineering Workflow — dumpexe Integration',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md992',1,'']]],
  ['workflow_20example_94',['Security Audit Workflow Example',['../md_skills_2claude__build.html#autotoc_md2119',1,'']]],
  ['workflow_20notes_95',['Reverse-Engineering Workflow Notes',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md1000',1,'']]],
  ['workflow_20proposed_96',['4. Agent-Driven SRI Workflow (Proposed)',['../md_docs_2SRI__FUTURE__WORK.html#autotoc_md1700',1,'']]],
  ['workflow_20savings_97',['Example Workflow Savings',['../md_docs_2features_2anthropic-features.html#autotoc_md1152',1,'']]],
  ['workflow_20template_98',['Workflow Template',['../md_skills_2reverse__engineering__expert.html#autotoc_md2175',1,'']]],
  ['working_99',['Working',['../md_docs_2PROOF__OLLAMA__DEMO.html#autotoc_md1518',1,'3. Cognitive Architecture Features Working'],['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md134',1,'Agents Now Working'],['../md_docs_2archive_2implementation-summaries_2SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md708',1,'Commands Now Working'],['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1045',1,'Tokens Not Working?']]],
  ['working_100',['working',['../md_docs_2features_2anthropic-features.html#autotoc_md1155',1,'Caching not working'],['../md_docs_2features_2anthropic-features.html#autotoc_md1158',1,'Files API not working']]],
  ['working_20with_20ollama_101',['PROOF: AXE Cognitive Architecture Working with Ollama',['../md_docs_2PROOF__OLLAMA__DEMO.html',1,'']]],
  ['workplace_20rules_102',['Workplace Rules',['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md460',1,'']]],
  ['works_103',['Works',['../md_docs_2features_2anthropic-features.html#autotoc_md1130',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1137',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1141',1,'How It Works'],['../md_docs_2features_2anthropic-features.html#autotoc_md1146',1,'How It Works'],['../md_docs_2xp__voting.html#autotoc_md1935',1,'How It Works'],['../md_docs_2archive_2implementation-summaries_2HEREDOC__EXECUTION__FIX.html#autotoc_md330',1,'Why This Works']]],
  ['works_20with_20any_20talking_20model_104',['Works with ANY Talking Model',['../md_README.html#autotoc_md1993',1,'💬 Works with ANY Talking Model'],['../md_TODO.html#autotoc_md2239',1,'💬 Works with ANY Talking Model']]],
  ['works_20without_20user_20namespace_105',['What Works Without User Namespace',['../md_docs_2NAMESPACE__DETECTION.html#autotoc_md1422',1,'']]],
  ['workshop_20benchmarks_20md_20benchmarks_20md_106',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2benchmarks.html&quot;&gt;benchmarks.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1836',1,'']]],
  ['workshop_20dependency_20validation_20md_20dependency_20validation_20md_107',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2dependency-validation.html&quot;&gt;dependency-validation.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1838',1,'']]],
  ['workshop_20dynamic_20analysis_20framework_20comprehensive_20validation_20report_108',['PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report',['../md_docs_2archive_2pr-reports_2PR23__VALIDATION__REPORT.html',1,'']]],
  ['workshop_20dynamic_20analysis_20framework_20executive_20summary_109',['PR #23 Workshop Dynamic Analysis Framework - Executive Summary',['../md_docs_2archive_2pr-reports_2PR23__EXECUTIVE__SUMMARY.html',1,'']]],
  ['workshop_20quick_20reference_20md_20quick_20reference_20md_110',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2quick-reference.html&quot;&gt;quick-reference.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1835',1,'']]],
  ['workshop_20security_20audit_20md_20security_20audit_20md_111',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2security-audit.html&quot;&gt;security-audit.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1837',1,'']]],
  ['workshop_20status_112',['Workshop Status',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md383',1,'']]],
  ['workshop_20test_20results_20md_20test_20results_20md_113',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2workshop_2test-results.html&quot;&gt;test-results.md&lt;/a&gt;',['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1839',1,'']]],
  ['workshop_20tools_114',['Workshop Tools',['../md_ARCHITECTURE.html#autotoc_md54',1,'3. Adding New Workshop Tools'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1841',1,'Accessing Workshop Tools'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1827',1,'AXE Workshop Tools'],['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1407',1,'Section 12 – Workshop Tools'],['../md_docs_2conflict__resolution__examples.html#autotoc_md1079',1,'Workshop Tools'],['../dir_49e56c817e5e54854c35e136979f97ca.html#autotoc_md1527',1,'Workshop Tools'],['../dir_7e275f28aa370bdbeec7244f496ce598.html#autotoc_md1828',1,'Workshop Tools'],['../md_README.html#autotoc_md2014',1,'Workshop Tools']]],
  ['workshop_20tools_20benchmarks_115',['Workshop Tools Benchmarks',['../md_docs_2workshop_2benchmarks.html',1,'']]],
  ['workshop_20tools_20dependency_20validation_116',['Workshop Tools Dependency Validation',['../md_docs_2workshop_2dependency-validation.html',1,'']]],
  ['workshop_20tools_20quick_20reference_117',['Workshop Tools Quick Reference',['../md_docs_2workshop_2quick-reference.html',1,'']]],
  ['workshop_20tools_20security_20audit_118',['Workshop Tools Security Audit',['../md_docs_2workshop_2security-audit.html',1,'']]],
  ['workshop_20tools_20status_20discovery_20✅_119',['4. Workshop Tools Status &amp;amp; Discovery ✅',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__COMPLETE.html#autotoc_md363',1,'']]],
  ['workshop_20tools_20test_20suite_20execution_20results_120',['Workshop Tools Test Suite Execution Results',['../md_docs_2workshop_2test-results.html',1,'']]],
  ['workspace_121',['Workspace',['../md_docs_2COGNITIVE__ARCHITECTURE__GUIDE.html#autotoc_md1031',1,'1. Broadcasting (Global Workspace)'],['../md_docs_2archive_2implementation-summaries_2IMPROVEMENTS__FINAL.html#autotoc_md470',1,'Per-Agent Workspace'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1365',1,'Test 3: Add Workspace'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1366',1,'Test 4: Remove Workspace']]],
  ['workspace_20axe_20source_122',['Section 9 – AXE Self-Analysis (workspace = AXE source)',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1401',1,'']]],
  ['workspace_20baars_201988_123',['Global Workspace (Baars, 1988)',['../md_docs_2INTEGRATION__COMPLETE.html#autotoc_md1349',1,'']]],
  ['workspace_20bug_124',['Note on Workspace Bug',['../md_docs_2CONSOLIDATION__SUMMARY.html#autotoc_md1103',1,'']]],
  ['workspace_20command_20axe_20py_125',['5. New &lt;span class=&quot;tt&quot;&gt;/workspace&lt;/span&gt; Command (&lt;span class=&quot;tt&quot;&gt;axe.py&lt;/span&gt;)',['../md_docs_2WORKSPACE__FIX.html#autotoc_md1919',1,'']]],
  ['workspace_20commands_126',['Interactive Testing Results - Workspace Commands',['../md_docs_2INTERACTIVE__TEST__RESULTS.html',1,'']]],
  ['workspace_20directories_127',['Section 5 – Multiple Workspace Directories',['../md_docs_2LIVE__TEST__RESULTS.html#autotoc_md1393',1,'']]],
  ['workspace_20directories_20—_20ux_20polish_128',['8. Multiple Workspace Directories — UX Polish',['../md_docs_2AXE__IMPROVEMENT__SUGGESTIONS.html#autotoc_md996',1,'']]],
  ['workspace_20files_20access_129',['Test 8: Workspace Files Access',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1370',1,'']]],
  ['workspace_20implementation_20guide_130',['Global Workspace - Implementation Guide',['../md_docs_2global-workspace.html',1,'']]],
  ['workspace_20implementation_20summary_131',['Global Workspace Implementation Summary',['../md_docs_2GLOBAL__WORKSPACE__SUMMARY.html',1,'']]],
  ['workspace_20management_132',['Workspace Management',['../md_README.html#autotoc_md2013',1,'']]],
  ['workspace_20path_20bug_20fix_20and_20multiple_20workspace_20support_133',['Workspace Path Bug Fix and Multiple Workspace Support',['../md_docs_2WORKSPACE__FIX.html',1,'']]],
  ['workspace_20support_134',['Workspace Path Bug Fix and Multiple Workspace Support',['../md_docs_2WORKSPACE__FIX.html',1,'']]],
  ['workspaces_135',['Workspaces',['../md_README.html#autotoc_md2023',1,'Multiple Workspaces'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1364',1,'Test 2: Show Current Workspaces'],['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1368',1,'Test 6: Clear Workspaces']]],
  ['workspaces_20comma_20separated_136',['Test 5: Set Multiple Workspaces (Comma-Separated)',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1367',1,'']]],
  ['workspaces_20from_20cli_137',['Test 1: Multiple Workspaces from CLI',['../md_docs_2INTERACTIVE__TEST__RESULTS.html#autotoc_md1363',1,'']]],
  ['world_20impact_138',['Real-World Impact',['../md_docs_2archive_2implementation-summaries_2ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md154',1,'']]],
  ['write_20block_20absolute_20path_20fix_20implementation_20summary_139',['WRITE Block Absolute Path Fix - Implementation Summary',['../md_docs_2archive_2implementation-summaries_2ABSOLUTE__PATH__FIX__SUMMARY.html',1,'']]],
  ['write_20block_20format_140',['WRITE Block Format',['../md_docs_2features_2write-blocks.html#autotoc_md1280',1,'']]],
  ['write_20block_20functionality_20user_20guide_141',['WRITE Block Functionality - User Guide',['../md_docs_2features_2write-blocks.html',1,'']]],
  ['write_20block_20sanitization_142',['WRITE block sanitization',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md308',1,'']]],
  ['write_20block_20syntax_143',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_docs_2archive_2implementation-summaries_2BEFORE__AFTER__COMPARISON.html#autotoc_md187',1,'']]],
  ['write_20block_20syntax_20✅_144',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_docs_2archive_2implementation-summaries_2FIXES__SUMMARY.html#autotoc_md306',1,'']]],
  ['write_20blocks_145',['Implementation Summary: GPT-5 Fix &amp;amp; WRITE Blocks',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html',1,'']]],
  ['write_20blocks_20md_146',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2write-blocks.html&quot;&gt;write-blocks.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1237',1,'']]],
  ['write_20blocks_20md_20write_20blocks_20md_147',['&lt;a class=&quot;el&quot; href=&quot;md_docs_2features_2write-blocks.html&quot;&gt;write-blocks.md&lt;/a&gt;',['../dir_1a0dd6ec8f01d1985574a039da34db44.html#autotoc_md1237',1,'']]],
  ['write_20blocks_20not_20executing_20high_148',['✅ Issue 2: WRITE Blocks Not Executing (HIGH)',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md398',1,'']]],
  ['write_20create_20write_20files_149',['WRITE - Create/Write Files',['../md_docs_2features_2parsers.html#autotoc_md1223',1,'']]],
  ['write_20exec_20blocks_150',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_docs_2archive_2implementation-summaries_2DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md252',1,'']]],
  ['write_20file_151',['Write file',['../md_docs_2archive_2implementation-summaries_2IMPLEMENTATION__SUMMARY.html#autotoc_md404',1,'']]],
  ['write_20files_152',['WRITE - Create/Write Files',['../md_docs_2features_2parsers.html#autotoc_md1223',1,'']]],
  ['write_5fpid_5ffile_20none_153',['&lt;span class=&quot;tt&quot;&gt;write_pid_file() -&amp;gt; None&lt;/span&gt;',['../md_docs_2socket__interface.html#autotoc_md1667',1,'']]]
];
