var searchData=
[
  ['race_20condition_20in_20database_20operations_0',['Issue #4: Race Condition in Database Operations',['../md_workshop__security__audit.html#autotoc_md1427',1,'']]],
  ['random_20id_20generation_1',['Issue #5: Weak Random ID Generation',['../md_workshop__security__audit.html#autotoc_md1428',1,'']]],
  ['ranks_20levels_2',['Agent Ranks &amp;amp; Levels',['../md_QUICK__REFERENCE.html#autotoc_md840',1,'']]],
  ['rate_20limiting_3',['Rate Limiting',['../md_workshop__security__audit.html#autotoc_md1432',1,'Finding #3: No Rate Limiting'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md445',1,'Rate Limiting'],['../md_MODELS__FINAL.html#autotoc_md663',1,'Rate Limiting']]],
  ['rate_20limiting_20✅_4',['3. Agent Rate Limiting ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md425',1,'']]],
  ['rate_20limiting_20new_5',['Rate Limiting (NEW!)',['../md_README.html#autotoc_md906',1,'']]],
  ['ray_6',['2. Adding Distributed Processing (Ray)',['../md_ARCHITECTURE.html#autotoc_md163',1,'']]],
  ['ray_20integration_20distributed_20ai_7',['Ray Integration (Distributed AI)',['../md_ARCHITECTURE.html#autotoc_md169',1,'']]],
  ['re_20run_20cppcheck_20with_20full_20details_8',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md1236',1,'']]],
  ['re_20run_20with_20full_20details_3a_9',['re run with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md1215',1,'If issues found, re-run with full details:']]],
  ['re_20run_20with_20verbose_20output_3a_10',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['read_20block_20access_20denied_11',['Issue 1: READ Block Access Denied',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md173',1,'']]],
  ['read_20block_20access_20denied_20✅_12',['Issue 1: READ Block Access Denied ✅',['../md_FIXES__SUMMARY.html#autotoc_md363',1,'']]],
  ['read_20block_20sanitization_13',['READ block sanitization',['../md_FIXES__SUMMARY.html#autotoc_md370',1,'']]],
  ['read_20write_20block_20syntax_14',['Issue 4: Agents Confused About READ/WRITE Block Syntax',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md185',1,'']]],
  ['read_20write_20block_20syntax_20✅_15',['Issue 4: Agents Confused About READ/WRITE Block Syntax ✅',['../md_FIXES__SUMMARY.html#autotoc_md369',1,'']]],
  ['read_20write_20exec_20blocks_16',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['ready_20codebase_20overview_20—_202026_2001_2013_17',['LLM-Ready Codebase Overview — 2026-01-13',['../md_llm__prep_2codebase__overview.html',1,'']]],
  ['ready_20for_20implementation_18',['Ready for Implementation',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md96',1,'']]],
  ['real_20bullying_19',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['real_20world_20example_3a_20reverse_20engineering_20a_20wad_20file_20',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['real_20world_20example_3a_20security_20audit_20workflow_21',['Real-World Example: Security Audit Workflow',['../md_README.html#autotoc_md972',1,'']]],
  ['real_20world_20impact_22',['Real-World Impact',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md84',1,'']]],
  ['reasoning_20✅_23',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md75',1,'']]],
  ['recognized_24',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_IMPROVEMENTS__FINAL.html#autotoc_md528',1,'']]],
  ['recommendation_25',['Recommendation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md821',1,'Part 11: Merge Recommendation'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md732',1,'Recommendation']]],
  ['recommendations_26',['Recommendations',['../md_PR23__VALIDATION__REPORT.html#autotoc_md823',1,'Post-Merge Recommendations'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md98',1,'Recommendations'],['../md_workshop__benchmarks.html#autotoc_md1361',1,'Recommendations'],['../md_workshop__dependency__validation.html#autotoc_md1394',1,'Recommendations'],['../md_workshop__security__audit.html#autotoc_md1443',1,'Recommendations'],['../md_workshop__test__results.html#autotoc_md1473',1,'Recommendations'],['../md_workshop__security__audit.html#autotoc_md1437',1,'Security Recommendations']]],
  ['recommendations_20prioritized_27',['Recommendations (Prioritized)',['../md_SECURITY__REPORT.html#autotoc_md1107',1,'']]],
  ['recommended_20weights_28',['Recommended Weights',['../md_IMPROVEMENTS__FINAL.html#autotoc_md489',1,'']]],
  ['recommended_20work_20duration_20limits_29',['Recommended Work Duration Limits',['../md_IMPROVEMENTS__FINAL.html#autotoc_md483',1,'']]],
  ['recover_5fhigh_5flevel_5fmodel_30',['recover_high_level_model',['../md_skills_2recover__high__level__model.html',1,'']]],
  ['recovery_31',['Recovery',['../md_workshop__dependency__validation.html#autotoc_md1393',1,'Error Recovery'],['../md_workshop__security__audit.html#autotoc_md1431',1,'Finding #2: Limited Error Recovery']]],
  ['redirects_20without_20spaces_32',['2. Redirects Without Spaces',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1121',1,'']]],
  ['reduction_33',['Reduction',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1074',1,'Attack Surface Reduction'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md583',1,'Token Reduction']]],
  ['refactoring_20expert_34',['C++ Refactoring Expert',['../md_skills_2cpp__refactoring__expert.html',1,'']]],
  ['refactoring_20notes_35',['AXE.PY Refactoring Notes',['../md_REFACTORING__NOTES.html',1,'']]],
  ['refactoring_20prs_202_203_36',['Future Refactoring (PRs #2 &amp;amp; #3)',['../md_REFACTORING__NOTES.html#autotoc_md1018',1,'']]],
  ['refactoring_20summary_37',['Refactoring Summary',['../md_REFACTORING__NOTES.html#autotoc_md994',1,'']]],
  ['refactors_38',['Common Refactors',['../md_skills_2cpp__refactoring__expert.html#autotoc_md1266',1,'']]],
  ['reference_39',['Reference',['../md_README.html#autotoc_md911',1,'Agent Reference'],['../md_MODELS__FINAL.html',1,'AXE Multi-Agent System - Model Configuration Reference'],['../md_README.html#autotoc_md901',1,'Chat Commands Reference'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md267',1,'Configuration Reference'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md768',1,'Document 1: Quick Reference'],['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html',1,'Multi-Format Tool Call Parser - Quick Reference'],['../md__8collab__env.html#autotoc_md7',1,'Quick Reference'],['../md_API__PROVIDERS.html#autotoc_md151',1,'Quick Reference'],['../md_skills_2claude__build.html#autotoc_md1249',1,'Security Tool Quick Reference'],['../md_MISSION.html#autotoc_md606',1,'Token Reference'],['../md_workshop__quick__reference.html',1,'Workshop Tools Quick Reference'],['../md_XML__PARSER__QUICK__REFERENCE.html',1,'XML Function Call Support - Quick Reference']]],
  ['reference_20card_40',['Reference Card',['../md_QUICK__REFERENCE.html',1,'AXE Multiagent - Quick Reference Card'],['../md_README.html#autotoc_md990',1,'Quick Reference Card']]],
  ['reference_20commands_41',['Quick Reference Commands',['../md_IMPROVEMENTS__FINAL.html#autotoc_md537',1,'']]],
  ['reference_20guide_42',['AXE Multi-Agent System - Improvement Reference Guide',['../md_IMPROVEMENTS__FINAL.html',1,'']]],
  ['references_43',['References',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md91',1,'Quick References'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md277',1,'References'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md601',1,'References'],['../md_REFACTORING__NOTES.html#autotoc_md1025',1,'References'],['../md_SANDBOX.html#autotoc_md1056',1,'References'],['../md_skills_2build.html#autotoc_md1202',1,'References'],['../md_skills_2claude__build.html#autotoc_md1259',1,'References']]],
  ['regression_20testing_44',['Regression Testing',['../md_workshop__test__results.html#autotoc_md1465',1,'']]],
  ['regression_20testing_20silent_45',['Pattern 3: Regression Testing (Silent)',['../md_skills_2claude__build.html#autotoc_md1256',1,'']]],
  ['regressions_46',['✅ No Regressions',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md438',1,'']]],
  ['regressions_47',['Check for regressions',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md469',1,'']]],
  ['rejection_20and_20feedback_48',['Rejection and Feedback',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md300',1,'']]],
  ['related_20collaboration_20files_49',['Related Collaboration Files',['../md__8collab__shared.html#autotoc_md13',1,'']]],
  ['relevant_20output_50',['2. Focus on Security-Relevant Output',['../md_skills_2claude__build.html#autotoc_md1242',1,'']]],
  ['reliability_20metrics_51',['Reliability Metrics',['../md_workshop__test__results.html#autotoc_md1464',1,'']]],
  ['removal_52',['Removal',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md303',1,'']]],
  ['remove_20all_20output_53',['❌ Don&apos;t Remove All Output',['../md_skills_2build.html#autotoc_md1187',1,'']]],
  ['removed_3a_20axe_20native_20read_20write_20exec_20blocks_54',['4. REMOVED: AXE native &lt;span class=&quot;tt&quot;&gt;READ/WRITE/EXEC&lt;/span&gt; blocks',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md315',1,'']]],
  ['report_55',['Report',['../md_SECURITY__REPORT.html',1,'AXE Project Security Report'],['../md_workshop__test__results.html#autotoc_md1460',1,'Code Coverage Report'],['../md_skills_2dos__packer__detector.html#autotoc_md1273',1,'DOS Packer Detection Report'],['../md_skills_2claude__build.html#autotoc_md1238',1,'Phase 4: Security Report'],['../md_PR23__VALIDATION__REPORT.html',1,'PR #23 Workshop Dynamic Analysis Framework - Comprehensive Validation Report']]],
  ['request_20process_56',['Pull Request Process',['../md_AGENTS.html#autotoc_md64',1,'']]],
  ['request_20protocol_57',['Request Protocol',['../md_IMPROVEMENTS__FINAL.html#autotoc_md502',1,'']]],
  ['required_58',['⚠️ Manual Testing Required',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md435',1,'']]],
  ['required_59',['Online (No installation required)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md282',1,'']]],
  ['required_20dependencies_60',['Required Dependencies',['../md_PR23__VALIDATION__REPORT.html#autotoc_md804',1,'']]],
  ['requirements_61',['Requirements',['../md_AGENTS.html#autotoc_md43',1,'Requirements'],['../md_API__PROVIDERS.html#autotoc_md127',1,'Requirements'],['../md_API__PROVIDERS.html#autotoc_md145',1,'Requirements'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md301',1,'Requirements'],['../md_SANDBOX.html#autotoc_md1032',1,'Requirements'],['../md_AGENTS.html#autotoc_md48',1,'Test Requirements']]],
  ['requirements_20txt_62',['Added to requirements.txt',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md721',1,'']]],
  ['requires_20api_20keys_63',['Manual testing (requires API keys)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md470',1,'']]],
  ['requires_20graphviz_64',['Command Line (Requires GraphViz)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md283',1,'']]],
  ['resolution_20testing_65',['Dependency Resolution Testing',['../md_workshop__dependency__validation.html#autotoc_md1380',1,'']]],
  ['resolved_66',['Issues Resolved',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md459',1,'']]],
  ['resource_20controls_20verified_67',['Resource Controls - VERIFIED',['../md_PR23__VALIDATION__REPORT.html#autotoc_md788',1,'']]],
  ['resource_20monitoring_68',['Resource Monitoring',['../md__8collab__env.html#autotoc_md10',1,'Resource Monitoring'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md530',1,'Resource Monitoring'],['../md_QUICK__REFERENCE.html#autotoc_md847',1,'Resource Monitoring']]],
  ['resource_20tracking_20✅_69',['Phase 5: Resource Tracking ✅',['../md_IMPROVEMENTS__README.html#autotoc_md547',1,'']]],
  ['resource_20usage_70',['Checking Resource Usage',['../md_IMPROVEMENTS__README.html#autotoc_md559',1,'']]],
  ['resource_20utilization_20trends_71',['Resource Utilization Trends',['../md_workshop__benchmarks.html#autotoc_md1360',1,'']]],
  ['resources_72',['Resources',['../md_AGENTS.html#autotoc_md67',1,'Additional Resources'],['../md__8collab__env.html#autotoc_md2',1,'Resources'],['../md_workshop__test__results.html#autotoc_md1471',1,'System Resources']]],
  ['respect_20well_20being_20–_20no_20real_20bullying_73',['2. Respect &amp;amp; Well-Being – No Real Bullying',['../md_IMPROVEMENTS__FINAL.html#autotoc_md526',1,'']]],
  ['response_74',['4. Multiple Files in One Response',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1485',1,'']]],
  ['response_75',['Append results to response',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md463',1,'']]],
  ['response_20commented_20out_76',['calls.extend(parse_axe_native_blocks(response)) # COMMENTED OUT',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md318',1,'']]],
  ['responseprocessor_77',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['restricted_20sandbox_20with_20blacklist_78',['Example 2: Restricted Sandbox with Blacklist',['../md_SANDBOX.html#autotoc_md1038',1,'']]],
  ['restrictions_79',['Environment Restrictions',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1079',1,'']]],
  ['result_3a_80',['Result:',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md415',1,'']]],
  ['results_81',['Results',['../md_workshop__test__results.html#autotoc_md1453',1,'Detailed Test Results'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md772',1,'Document 5: Test Results'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md85',1,'Integration Test Results'],['../md_workshop__security__audit.html#autotoc_md1438',1,'Penetration Testing Results'],['../md_workshop__benchmarks.html#autotoc_md1344',1,'Performance Analysis Results'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md582',1,'Performance Results'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md27',1,'Test Results'],['../md_BUG__FIX__SUMMARY.html#autotoc_md204',1,'Test Results'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md233',1,'Test Results'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md326',1,'Test Results'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md409',1,'Test Results'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md584',1,'Test Results'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md678',1,'Test Results'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1068',1,'Test Results'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1330',1,'Test Results'],['../md_workshop__security__audit.html#autotoc_md1440',1,'Test Results'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md713',1,'Validation Results'],['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1150',1,'Verification Results'],['../md_workshop__test__results.html',1,'Workshop Tools Test Suite Execution Results']]],
  ['results_20appearing_82',['No Results Appearing?',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1524',1,'']]],
  ['results_20test_5fworkshop_20py_83',['Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1454',1,'']]],
  ['results_20test_5fworkshop_5fintegration_20py_84',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1455',1,'']]],
  ['results_20test_5fworkshop_5fperformance_20py_85',['Performance Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_performance.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1456',1,'']]],
  ['results_20test_5fworkshop_5fsecurity_20py_86',['Security Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_security.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1457',1,'']]],
  ['results_20to_20response_87',['Append results to response',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md463',1,'']]],
  ['resume_20later_88',['&quot;Want to resume later&quot;',['../md_QUICK__REFERENCE.html#autotoc_md859',1,'']]],
  ['resume_20save_20✅_89',['2. Session Resume/Save ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md424',1,'']]],
  ['retry_20with_20verbose_20on_20failure_90',['2. Retry with Verbose on Failure',['../md_skills_2build.html#autotoc_md1182',1,'']]],
  ['reverse_20engineering_20a_20wad_20file_91',['Real-World Example: Reverse Engineering a WAD File',['../md_README.html#autotoc_md898',1,'']]],
  ['reverse_20engineering_20expert_92',['Reverse Engineering Expert',['../md_skills_2reverse__engineering__expert.html',1,'']]],
  ['reverse_20engineering_20tools_93',['Reverse Engineering Tools',['../md__8collab__env.html#autotoc_md4',1,'']]],
  ['review_94',['Code Review',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md82',1,'']]],
  ['review_20addressed_95',['Code Review Addressed',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1138',1,'']]],
  ['review_20checklist_96',['Code Review Checklist',['../md_AGENTS.html#autotoc_md65',1,'']]],
  ['review_20findings_97',['Review findings',['../md_skills_2claude__build.html#autotoc_md1224',1,'']]],
  ['review_20flow_98',['Review Flow',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md299',1,'']]],
  ['review_20interface_99',['Review Interface',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md295',1,'']]],
  ['review_20issues_20addressed_100',['Code Review Issues Addressed',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md674',1,'']]],
  ['rewards_101',['XP Rewards',['../md_README.html#autotoc_md971',1,'']]],
  ['rewards_20–_20good_20work_20gets_20recognized_102',['4. Performance &amp;amp; Rewards – Good Work Gets Recognized',['../md_IMPROVEMENTS__FINAL.html#autotoc_md528',1,'']]],
  ['risk_20assessment_103',['Risk Assessment',['../md_PR23__VALIDATION__REPORT.html#autotoc_md825',1,'Part 12: Risk Assessment'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md729',1,'Risk Assessment']]],
  ['risk_3a_20⚠️_20low_104',['Merge Risk: ⚠️ LOW',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md730',1,'']]],
  ['risks_3a_20low_105',['Merge Risks: LOW',['../md_PR23__VALIDATION__REPORT.html#autotoc_md826',1,'']]],
  ['robin_20analysis_106',['Round-Robin Analysis',['../md_README.html#autotoc_md933',1,'']]],
  ['robust_107',['Error Handling - ROBUST',['../md_PR23__VALIDATION__REPORT.html#autotoc_md795',1,'']]],
  ['role_108',['Supervisor Role',['../md_IMPROVEMENTS__README.html#autotoc_md562',1,'']]],
  ['role_20assignment_109',['Supervisor Role Assignment',['../md_MODELS__FINAL.html#autotoc_md659',1,'']]],
  ['rollback_20plan_110',['Rollback Plan',['../md_PR23__VALIDATION__REPORT.html#autotoc_md827',1,'']]],
  ['root_20cause_111',['Root Cause',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md20',1,'Root Cause'],['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html#autotoc_md211',1,'Root Cause'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md312',1,'Root Cause'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md390',1,'Root Cause']]],
  ['root_20cause_20analysis_112',['Root Cause Analysis',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md402',1,'']]],
  ['round_20robin_20analysis_113',['Round-Robin Analysis',['../md_README.html#autotoc_md933',1,'']]],
  ['rules_114',['Rules',['../md_IMPROVEMENTS__FINAL.html#autotoc_md516',1,'Rules'],['../md_IMPROVEMENTS__README.html#autotoc_md558',1,'Viewing Session Rules'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md523',1,'Workplace Rules']]],
  ['rules_20guidelines_20✅_115',['Phase 1: Session Rules &amp;amp; Guidelines ✅',['../md_IMPROVEMENTS__README.html#autotoc_md543',1,'']]],
  ['rules_20the_204_20principles_116',['Session Rules (The 4 Principles)',['../md_QUICK__REFERENCE.html#autotoc_md839',1,'']]],
  ['run_20all_20unit_20tests_117',['Run all unit tests',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md468',1,'']]],
  ['run_20automated_20tests_118',['Run automated tests',['../md_QUICK__REFERENCE.html#autotoc_md849',1,'']]],
  ['run_20clang_20static_20analyzer_20quietly_119',['Run Clang static analyzer quietly',['../md_skills_2claude__build.html#autotoc_md1223',1,'']]],
  ['run_20cmd_3a_20str_20lines_201544_201629_120',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1118',1,'']]],
  ['run_20cppcheck_20with_20full_20details_121',['Re-run cppcheck with full details',['../md_skills_2claude__build.html#autotoc_md1236',1,'']]],
  ['run_20full_20scan_3a_122',['If issues found, run full scan:',['../md_skills_2claude__build.html#autotoc_md1227',1,'']]],
  ['run_20interactive_20demo_123',['Run interactive demo',['../md_QUICK__REFERENCE.html#autotoc_md850',1,'']]],
  ['run_20method_124',['1. Defensive Programming in &lt;span class=&quot;tt&quot;&gt;run()&lt;/span&gt; Method',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md405',1,'']]],
  ['run_20static_20analysis_20quietly_125',['Run static analysis quietly',['../md_skills_2claude__build.html#autotoc_md1217',1,'']]],
  ['run_20tests_20quietly_126',['Run tests quietly',['../md_skills_2build.html#autotoc_md1196',1,'']]],
  ['run_20tests_20silently_127',['Run tests silently',['../md_skills_2build.html#autotoc_md1199',1,'']]],
  ['run_20tests_20silently_128',['Compile with ASan and run tests silently',['../md_skills_2claude__build.html#autotoc_md1220',1,'']]],
  ['run_20with_20full_20details_3a_129',['run with full details:',['../md_skills_2claude__build.html#autotoc_md1218',1,'If critical issues found, re-run with full details:'],['../md_skills_2claude__build.html#autotoc_md1215',1,'If issues found, re-run with full details:']]],
  ['run_20with_20verbose_20output_3a_130',['If issues detected, re-run with verbose output:',['../md_skills_2claude__build.html#autotoc_md1221',1,'']]],
  ['running_20axe_131',['Running AXE',['../md_AGENTS.html#autotoc_md45',1,'']]],
  ['running_20tests_132',['Running Tests',['../md_AGENTS.html#autotoc_md47',1,'']]],
  ['runtime_20analysis_20silent_133',['Runtime analysis silent',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1160',1,'Runtime analysis (silent)'],['../md_skills_2claude__build.html#autotoc_md1252',1,'Runtime analysis (silent)']]],
  ['runtime_20detection_134',['Compile with AddressSanitizer for runtime detection',['../md_skills_2claude__build.html#autotoc_md1237',1,'']]]
];
