var searchData=
[
  ['languages_0',['Additional Languages',['../md__8collab__env.html#autotoc_md5',1,'']]],
  ['large_20classes_1',['PR #2: Extract Large Classes',['../md_REFACTORING__NOTES.html#autotoc_md1019',1,'']]],
  ['later_2',['&quot;Want to resume later&quot;',['../md_QUICK__REFERENCE.html#autotoc_md859',1,'']]],
  ['latest_20models_3',['Latest Models',['../md_MODELS__FINAL.html#autotoc_md623',1,'Latest Models'],['../md_MODELS__FINAL.html#autotoc_md629',1,'Latest Models'],['../md_MODELS__FINAL.html#autotoc_md636',1,'Latest Models'],['../md_MODELS__FINAL.html#autotoc_md642',1,'Latest Models']]],
  ['learned_4',['Lessons Learned',['../md_REFACTORING__NOTES.html#autotoc_md1024',1,'']]],
  ['legacy_20mode_5',['Scenario 4: Legacy Mode',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1086',1,'']]],
  ['lessons_20learned_6',['Lessons Learned',['../md_REFACTORING__NOTES.html#autotoc_md1024',1,'']]],
  ['level_2040_20handling_7',['Level 40+ Handling',['../md_IMPROVEMENTS__FINAL.html#autotoc_md521',1,'']]],
  ['level_20analysis_8',['Function-Level Analysis',['../md_workshop__benchmarks.html#autotoc_md1348',1,'']]],
  ['level_20system_9',['XP &amp;amp; Level System',['../md_IMPROVEMENTS__FINAL.html#autotoc_md518',1,'']]],
  ['level_20system_20✅_10',['Phase 3: Experience &amp;amp; Level System ✅',['../md_IMPROVEMENTS__README.html#autotoc_md545',1,'']]],
  ['levels_11',['Levels',['../md_skills_2claude__build.html#autotoc_md1245',1,'3. Document Severity Levels'],['../md_QUICK__REFERENCE.html#autotoc_md840',1,'Agent Ranks &amp;amp; Levels']]],
  ['libraries_12',['Primary Analysis Libraries',['../md_workshop__dependency__validation.html#autotoc_md1366',1,'']]],
  ['library_20dependencies_13',['Standard Library Dependencies',['../md_workshop__dependency__validation.html#autotoc_md1370',1,'']]],
  ['license_14',['License',['../md_README.html#autotoc_md986',1,'Commercial License'],['../md_MISSION.html#autotoc_md612',1,'License'],['../md_README.html#autotoc_md984',1,'License']]],
  ['license_20default_15',['Open Source License (Default)',['../md_README.html#autotoc_md985',1,'']]],
  ['lifecycle_16',['Agent Lifecycle',['../md_IMPROVEMENTS__README.html#autotoc_md563',1,'']]],
  ['like_17',['5. Simple XML tags like &amp;lt;read_file&amp;gt;, &amp;lt;shell&amp;gt;',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md319',1,'']]],
  ['limit_20errors_20413_20not_20handled_20✅_18',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['limitation_3a_19',['⚠️ Known Limitation:',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md30',1,'']]],
  ['limitations_20',['Limitations',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1080',1,'Bubblewrap Limitations'],['../md_SANDBOX.html#autotoc_md1043',1,'Known Limitations'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1078',1,'Known Limitations'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md812',1,'Part 9: Known Issues &amp;amp; Limitations']]],
  ['limitations_20by_20design_21',['Limitations (By Design)',['../md_PR23__VALIDATION__REPORT.html#autotoc_md814',1,'']]],
  ['limited_20error_20recovery_22',['Finding #2: Limited Error Recovery',['../md_workshop__security__audit.html#autotoc_md1431',1,'']]],
  ['limiting_23',['Limiting',['../md_workshop__security__audit.html#autotoc_md1432',1,'Finding #3: No Rate Limiting'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md445',1,'Rate Limiting'],['../md_MODELS__FINAL.html#autotoc_md663',1,'Rate Limiting']]],
  ['limiting_20✅_24',['3. Agent Rate Limiting ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md425',1,'']]],
  ['limiting_20new_25',['Rate Limiting (NEW!)',['../md_README.html#autotoc_md906',1,'']]],
  ['limits_26',['Limits',['../md_IMPROVEMENTS__FINAL.html#autotoc_md505',1,'API Provider Limits'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md500',1,'Limits'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md483',1,'Recommended Work Duration Limits'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md484',1,'Why These Limits?']]],
  ['limits_20increased_20for_20maximum_20shared_20view_27',['Limits (Increased for Maximum Shared View)',['../md__8collab__shared.html#autotoc_md15',1,'']]],
  ['line_20as_20before_28',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['line_20by_20line_20as_20before_29',['No heredoc - process line by line as before',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md322',1,'']]],
  ['line_20count_30',['Line Count',['../md_REFACTORING__NOTES.html#autotoc_md1014',1,'']]],
  ['line_20option_31',['Command Line Option',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md297',1,'']]],
  ['line_20requires_20graphviz_32',['Command Line (Requires GraphViz)',['../dir_185e1be576cc3aab87068787be53911a.html#autotoc_md283',1,'']]],
  ['linear_20exponential_33',['Progression Curve (Hybrid Linear/Exponential)',['../md_IMPROVEMENTS__FINAL.html#autotoc_md519',1,'']]],
  ['lines_34',['lines',['../md_REFACTORING__NOTES.html#autotoc_md1000',1,'&lt;span class=&quot;tt&quot;&gt;database/&lt;/span&gt; (542 lines)'],['../md_REFACTORING__NOTES.html#autotoc_md999',1,'&lt;span class=&quot;tt&quot;&gt;progression/&lt;/span&gt; (67 lines)'],['../md_REFACTORING__NOTES.html#autotoc_md1001',1,'&lt;span class=&quot;tt&quot;&gt;safety/&lt;/span&gt; (50 lines)'],['../md_REFACTORING__NOTES.html#autotoc_md998',1,'&lt;span class=&quot;tt&quot;&gt;utils/&lt;/span&gt; (33 lines)']]],
  ['lines_201121_201148_35',['1. Class Constants (Lines 1121-1148)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1112',1,'']]],
  ['lines_201150_201171_36',['2. &lt;span class=&quot;tt&quot;&gt;__init__(config: Config, project_dir: str)&lt;/span&gt; (Lines 1150-1171)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1113',1,'']]],
  ['lines_201173_201287_37',['3. &lt;span class=&quot;tt&quot;&gt;_strip_heredoc_content(cmd: str) -&amp;gt; str&lt;/span&gt; (Lines 1173-1287)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1114',1,'']]],
  ['lines_201289_201408_38',['4. &lt;span class=&quot;tt&quot;&gt;_extract_commands_from_shell(cmd: str) -&amp;gt; List[str]&lt;/span&gt; (Lines 1289-1408)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1115',1,'']]],
  ['lines_201410_201458_39',['5. &lt;span class=&quot;tt&quot;&gt;_needs_shell(cmd: str) -&amp;gt; bool&lt;/span&gt; (Lines 1410-1458)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1116',1,'']]],
  ['lines_201460_201542_40',['6. Updated &lt;span class=&quot;tt&quot;&gt;is_tool_allowed(cmd: str)&lt;/span&gt; (Lines 1460-1542)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1117',1,'']]],
  ['lines_201544_201629_41',['7. Updated &lt;span class=&quot;tt&quot;&gt;run(cmd: str, ...)&lt;/span&gt; (Lines 1544-1629)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1118',1,'']]],
  ['lines_20changed_42',['Lines Changed',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md242',1,'']]],
  ['links_43',['Quick Links',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md742',1,'']]],
  ['linux_20namespace_20isolation_44',['2. Linux Namespace Isolation',['../md_SANDBOX.html#autotoc_md1030',1,'']]],
  ['list_20str_20lines_201289_201408_45',['4. &lt;span class=&quot;tt&quot;&gt;_extract_commands_from_shell(cmd: str) -&amp;gt; List[str]&lt;/span&gt; (Lines 1289-1408)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1115',1,'']]],
  ['live_20instrumentation_46',['Live Instrumentation',['../md_PR23__VALIDATION__REPORT.html#autotoc_md753',1,'✅ VALIDATED - Hammer (Live Instrumentation)'],['../md_README.html#autotoc_md964',1,'Hammer - Live Instrumentation'],['../md_workshop__quick__reference.html#autotoc_md1405',1,'Hammer - Live Instrumentation']]],
  ['live_20instrumentation_20benchmarks_47',['Hammer - Live Instrumentation Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1355',1,'']]],
  ['live_20statistics_20monitoring_48',['Live Statistics &amp;amp; Monitoring',['../md_README.html#autotoc_md908',1,'']]],
  ['live_20testing_49',['Evidence from Live Testing',['../md_FIXES__SUMMARY.html#autotoc_md382',1,'']]],
  ['llama_50',['Llama',['../md_API__PROVIDERS.html#autotoc_md124',1,'HuggingFace (Llama)'],['../md_MODELS__FINAL.html#autotoc_md627',1,'HuggingFace (Llama)']]],
  ['llama_20405b_20model_20deprecated_51',['Issue 2: Llama 405B Model Deprecated',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md177',1,'']]],
  ['llama_20405b_20model_20deprecated_20✅_52',['Issue 2: Llama 405B Model Deprecated ✅',['../md_FIXES__SUMMARY.html#autotoc_md365',1,'']]],
  ['llama_20free_20tier_20available_53',['HuggingFace (Llama) - Free Tier Available!',['../md_README.html#autotoc_md886',1,'']]],
  ['llm_20context_20files_54',['LLM Context Files',['../md_llm__prep_2codebase__overview.html#autotoc_md574',1,'']]],
  ['llm_20ready_20codebase_20overview_20—_202026_2001_2013_55',['LLM-Ready Codebase Overview — 2026-01-13',['../md_llm__prep_2codebase__overview.html',1,'']]],
  ['llm_5fsystem_5fprompt_56',['llm_system_prompt',['../md_llm__prep_2llm__system__prompt.html',1,'']]],
  ['llmprep_20codebase_20preparation_57',['llmprep - Codebase Preparation',['../md_README.html#autotoc_md938',1,'']]],
  ['llmprep_20settings_58',['llmprep Settings',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md597',1,'']]],
  ['loading_59',['Manual Skill Loading',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1312',1,'']]],
  ['local_60',['Usage - Transformers (Local)',['../md_MODELS__FINAL.html#autotoc_md631',1,'']]],
  ['local_20models_61',['Ollama Integration (Local Models)',['../md_ARCHITECTURE.html#autotoc_md168',1,'']]],
  ['location_20fix_20implementation_20summary_62',['Database Location Fix - Implementation Summary',['../md_DATABASE__LOCATION__FIX__SUMMARY.html',1,'']]],
  ['logging_20of_20sensitive_20data_63',['Finding #5: Logging of Sensitive Data',['../md_workshop__security__audit.html#autotoc_md1434',1,'']]],
  ['logic_64',['Spawning Logic',['../md_IMPROVEMENTS__FINAL.html#autotoc_md506',1,'']]],
  ['logs_65',['Appendix A: Test Execution Logs',['../md_PR23__VALIDATION__REPORT.html#autotoc_md831',1,'']]],
  ['low_66',['LOW',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md730',1,'Merge Risk: ⚠️ LOW'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md826',1,'Merge Risks: LOW']]],
  ['low_67',['3. &lt;b&gt;YAML Config&lt;/b&gt; ✅ Low',['../md_SECURITY__REPORT.html#autotoc_md1103',1,'']]],
  ['low_20severity_20issues_68',['Low Severity Issues',['../md_workshop__security__audit.html#autotoc_md1425',1,'']]]
];
