var searchData=
[
  ['t_20assume_20silence_20means_20success_0',['❌ Don&apos;t Assume Silence Means Success',['../md_skills_2build.html#autotoc_md1188',1,'']]],
  ['t_20protect_20by_20design_1',['What Sandbox Doesn&apos;t Protect (by design)',['../md_SANDBOX.html#autotoc_md1042',1,'']]],
  ['t_20remove_20all_20output_2',['❌ Don&apos;t Remove All Output',['../md_skills_2build.html#autotoc_md1187',1,'']]],
  ['t_20use_20verbose_20by_20default_3',['❌ Don&apos;t Use Verbose by Default',['../md_skills_2build.html#autotoc_md1189',1,'']]],
  ['table_20of_20contents_4',['Table of Contents',['../md_API__PROVIDERS.html#autotoc_md105',1,'Table of Contents'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md475',1,'Table of Contents'],['../md_MODELS__FINAL.html#autotoc_md615',1,'Table of Contents'],['../md_README.html#autotoc_md864',1,'Table of Contents']]],
  ['tag_20formats_20not_20supported_20✅_5',['Bug 1: XML Tag Formats Not Supported ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md196',1,'']]],
  ['tags_20claude_20s_20favorite_6',['1. Bash XML Tags (Claude&apos;s Favorite)',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html#autotoc_md689',1,'']]],
  ['tags_20like_7',['5. Simple XML tags like &amp;lt;read_file&amp;gt;, &amp;lt;shell&amp;gt;',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md319',1,'']]],
  ['taint_20analysis_8',['Taint Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md751',1,'✅ VALIDATED - Saw (Taint Analysis)'],['../md_README.html#autotoc_md962',1,'Saw - Taint Analysis'],['../md_workshop__quick__reference.html#autotoc_md1403',1,'Saw - Taint Analysis']]],
  ['taint_20analysis_20benchmarks_9',['Saw - Taint Analysis Benchmarks',['../md_workshop__benchmarks.html#autotoc_md1349',1,'']]],
  ['taint_20propagation_20accuracy_10',['Taint Propagation Accuracy',['../md_workshop__benchmarks.html#autotoc_md1351',1,'']]],
  ['task_20complete_20detection_20✅_11',['Bug 1: False &quot;TASK COMPLETE&quot; Detection ✅',['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1320',1,'']]],
  ['task_20is_20sacred_12',['1. Mission First – The Project / Task Is Sacred',['../md_IMPROVEMENTS__FINAL.html#autotoc_md525',1,'']]],
  ['tasks_13',['Common Tasks',['../md_skills_2python__agent__expert.html#autotoc_md1281',1,'']]],
  ['technical_20implementation_20details_14',['Technical Implementation Details',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1304',1,'']]],
  ['techniques_15',['Key Techniques',['../md_skills_2ida__pro__analysis__patterns.html#autotoc_md1276',1,'']]],
  ['template_16',['Template',['../md_AGENTS.html#autotoc_md56',1,'Example Skill Template'],['../md_skills_2reverse__engineering__expert.html#autotoc_md1284',1,'Workflow Template']]],
  ['term_20this_20week_17',['Short-Term (This Week)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md737',1,'']]],
  ['termination_20bugs_18',['Fix Summary: AXE Session Termination Bugs',['../md_TASK__COMPLETION__FIX__SUMMARY.html',1,'']]],
  ['test_20categories_19',['Test Categories',['../md_workshop__test__results.html#autotoc_md1452',1,'']]],
  ['test_20compatibility_20',['1. Test Compatibility',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md709',1,'']]],
  ['test_20connection_21',['Test Connection',['../md_MODELS__FINAL.html#autotoc_md619',1,'']]],
  ['test_20coverage_22',['Test Coverage',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md24',1,'Test Coverage'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md81',1,'Test Coverage'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md324',1,'Test Coverage'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md677',1,'Test Coverage'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1069',1,'Test Coverage'],['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1127',1,'Test Coverage']]],
  ['test_20coverage_20analysis_23',['Part 6: Test Coverage Analysis',['../md_PR23__VALIDATION__REPORT.html#autotoc_md799',1,'']]],
  ['test_20data_20integrity_24',['Test Data Integrity',['../md_workshop__test__results.html#autotoc_md1472',1,'']]],
  ['test_20documentation_25',['Test Documentation',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1125',1,'']]],
  ['test_20effectiveness_26',['Test Effectiveness',['../md_workshop__test__results.html#autotoc_md1463',1,'']]],
  ['test_20environment_27',['Test Environment',['../md_workshop__benchmarks.html#autotoc_md1345',1,'Test Environment'],['../md_workshop__test__results.html#autotoc_md1449',1,'Test Environment']]],
  ['test_20environment_20validation_28',['Test Environment Validation',['../md_workshop__test__results.html#autotoc_md1470',1,'']]],
  ['test_20execution_20logs_29',['Appendix A: Test Execution Logs',['../md_PR23__VALIDATION__REPORT.html#autotoc_md831',1,'']]],
  ['test_20execution_20summary_30',['Test Execution Summary',['../md_workshop__test__results.html#autotoc_md1448',1,'Test Execution Summary'],['../md_workshop__test__results.html#autotoc_md1459',1,'Test Execution Summary']]],
  ['test_20failures_20none_31',['Test Failures (None)',['../md_workshop__test__results.html#autotoc_md1468',1,'']]],
  ['test_20file_201_3a_20unit_20tests_32',['Test File 1: Unit Tests',['../md_PR23__VALIDATION__REPORT.html#autotoc_md776',1,'']]],
  ['test_20file_202_3a_20integration_20tests_33',['Test File 2: Integration Tests',['../md_PR23__VALIDATION__REPORT.html#autotoc_md777',1,'']]],
  ['test_20files_34',['Test Files',['../md_PR23__VALIDATION__REPORT.html#autotoc_md775',1,'✅ VALIDATED - Test Files'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md26',1,'New Test Files'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md801',1,'PR Test Files']]],
  ['test_20files_20executed_35',['Test Files Executed',['../md_workshop__test__results.html#autotoc_md1451',1,'']]],
  ['test_20isolation_36',['3. Database Test Isolation',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md711',1,'']]],
  ['test_20mission_37',['AXE Test Mission',['../md_tests_2MISSION.html',1,'']]],
  ['test_20projects_20for_20multi_20agent_20work_38',['Test Projects for Multi-Agent Work',['../md_MODELS__FINAL.html#autotoc_md658',1,'']]],
  ['test_20quality_20metrics_39',['Test Quality Metrics',['../md_workshop__test__results.html#autotoc_md1462',1,'']]],
  ['test_20requirements_40',['Test Requirements',['../md_AGENTS.html#autotoc_md48',1,'']]],
  ['test_20results_41',['Test Results',['../md_workshop__test__results.html#autotoc_md1453',1,'Detailed Test Results'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md772',1,'Document 5: Test Results'],['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md85',1,'Integration Test Results'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md27',1,'Test Results'],['../md_BUG__FIX__SUMMARY.html#autotoc_md204',1,'Test Results'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md233',1,'Test Results'],['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md326',1,'Test Results'],['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md409',1,'Test Results'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md584',1,'Test Results'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md678',1,'Test Results'],['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1068',1,'Test Results'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1330',1,'Test Results'],['../md_workshop__security__audit.html#autotoc_md1440',1,'Test Results']]],
  ['test_20results_20test_5fworkshop_20py_42',['Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1454',1,'']]],
  ['test_20results_20test_5fworkshop_5fintegration_20py_43',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1455',1,'']]],
  ['test_20results_20test_5fworkshop_5fperformance_20py_44',['Performance Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_performance.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1456',1,'']]],
  ['test_20results_20test_5fworkshop_5fsecurity_20py_45',['Security Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_security.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1457',1,'']]],
  ['test_20scenarios_46',['Test Scenarios',['../md_tests_2MISSION.html#autotoc_md1337',1,'']]],
  ['test_20scenarios_20executed_47',['Test Scenarios Executed',['../md_workshop__security__audit.html#autotoc_md1439',1,'']]],
  ['test_20silently_20debug_20verbosely_48',['5. Test Silently, Debug Verbosely',['../md_skills_2build.html#autotoc_md1185',1,'']]],
  ['test_20statistics_49',['Overall Test Statistics',['../md_workshop__test__results.html#autotoc_md1458',1,'']]],
  ['test_20suite_50',['XML TOOL PARSER TEST SUITE',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1504',1,'']]],
  ['test_20suite_51',['Test Suite',['../md_HEREDOC__EXECUTION__FIX__SUMMARY.html#autotoc_md408',1,'4. Comprehensive Test Suite'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md774',1,'Claim 6: Test Suite'],['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md715',1,'PR Test Suite'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md832',1,'Validation Test Suite']]],
  ['test_20suite_20execution_20results_52',['Workshop Tools Test Suite Execution Results',['../md_workshop__test__results.html',1,'']]],
  ['test_20suite_20overview_53',['Test Suite Overview',['../md_workshop__test__results.html#autotoc_md1450',1,'']]],
  ['test_20suite_20test_5ftool_5frunner_20py_54',['Original Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1128',1,'']]],
  ['test_20suite_20test_5ftool_5frunner_5fedge_5fcases_20py_55',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1129',1,'']]],
  ['test_20suite_20tests_20test_5fskills_5fmanager_20py_56',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1302',1,'']]],
  ['test_20test_5fintegration_5fdatabase_5ffix_20py_57',['Integration Test (&lt;span class=&quot;tt&quot;&gt;test_integration_database_fix.py&lt;/span&gt;)',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md230',1,'']]],
  ['test_5fdatabase_5flocation_20py_58',['Unit Tests (&lt;span class=&quot;tt&quot;&gt;test_database_location.py&lt;/span&gt;)',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md229',1,'']]],
  ['test_5fdynamic_5fmax_5ftokens_20py_20new_59',['6. &lt;span class=&quot;tt&quot;&gt;tests/test_dynamic_max_tokens.py&lt;/span&gt; (NEW)',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md344',1,'']]],
  ['test_5fintegration_5fdatabase_5ffix_20py_60',['Integration Test (&lt;span class=&quot;tt&quot;&gt;test_integration_database_fix.py&lt;/span&gt;)',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md230',1,'']]],
  ['test_5fmodels_5fyaml_20py_61',['5. &lt;span class=&quot;tt&quot;&gt;tests/test_models_yaml.py&lt;/span&gt;',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md343',1,'']]],
  ['test_5fskills_5fmanager_20py_62',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1302',1,'']]],
  ['test_5ftool_5frunner_20py_63',['Original Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1128',1,'']]],
  ['test_5ftool_5frunner_5fedge_5fcases_20py_64',['Edge Case Test Suite (&lt;span class=&quot;tt&quot;&gt;test_tool_runner_edge_cases.py&lt;/span&gt;)',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1129',1,'']]],
  ['test_5fworkshop_20py_65',['Unit Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1454',1,'']]],
  ['test_5fworkshop_5fintegration_20py_66',['Integration Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_integration.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1455',1,'']]],
  ['test_5fworkshop_5fperformance_20py_67',['Performance Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_performance.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1456',1,'']]],
  ['test_5fworkshop_5fsecurity_20py_68',['Security Test Results (&lt;span class=&quot;tt&quot;&gt;test_workshop_security.py&lt;/span&gt;)',['../md_workshop__test__results.html#autotoc_md1457',1,'']]],
  ['test_5fxml_5ftool_5fparser_20py_69',['$ python3 test_xml_tool_parser.py',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1503',1,'']]],
  ['testing_70',['Testing',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1149',1,'4. Comprehensive Testing'],['../md_workshop__dependency__validation.html#autotoc_md1379',1,'Automated Installation Testing'],['../md_workshop__dependency__validation.html#autotoc_md1380',1,'Dependency Resolution Testing'],['../md_FIXES__SUMMARY.html#autotoc_md382',1,'Evidence from Live Testing'],['../md_workshop__dependency__validation.html#autotoc_md1388',1,'Integration Testing'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1493',1,'Interactive Testing'],['../md_SANDBOX.html#autotoc_md1055',1,'Manual Testing'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1492',1,'Manual Testing'],['../md_workshop__test__results.html#autotoc_md1465',1,'Regression Testing'],['../md_AGENTS.html#autotoc_md46',1,'Testing'],['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md228',1,'Testing'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md271',1,'Testing'],['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md307',1,'Testing'],['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md351',1,'Testing'],['../md_FIXES__SUMMARY.html#autotoc_md373',1,'Testing'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md395',1,'Testing'],['../md_IMPROVEMENTS__README.html#autotoc_md555',1,'Testing'],['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md594',1,'Testing'],['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html#autotoc_md676',1,'Testing'],['../md_QUICK__REFERENCE.html#autotoc_md848',1,'Testing'],['../md_REFACTORING__NOTES.html#autotoc_md1012',1,'Testing'],['../md_SANDBOX.html#autotoc_md1044',1,'Testing'],['../md_TASK__COMPLETION__FIX__SUMMARY.html#autotoc_md1324',1,'Testing'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1490',1,'Testing']]],
  ['testing_20✅_71',['Phase 4: Testing ✅',['../md_REFACTORING__NOTES.html#autotoc_md1006',1,'']]],
  ['testing_209_2010_72',['✅ Testing (9/10)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md706',1,'']]],
  ['testing_20api_20connections_73',['Testing API Connections',['../md_README.html#autotoc_md978',1,'']]],
  ['testing_20api_20keys_74',['Testing API Keys',['../md_API__PROVIDERS.html#autotoc_md158',1,'']]],
  ['testing_20required_75',['⚠️ Manual Testing Required',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md435',1,'']]],
  ['testing_20requires_20api_20keys_76',['Manual testing (requires API keys)',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md470',1,'']]],
  ['testing_20results_77',['Penetration Testing Results',['../md_workshop__security__audit.html#autotoc_md1438',1,'']]],
  ['testing_20silent_78',['Pattern 3: Regression Testing (Silent)',['../md_skills_2claude__build.html#autotoc_md1256',1,'']]],
  ['testing_20status_79',['Testing Status',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md432',1,'']]],
  ['tests_80',['Tests',['../md_SHELL__OPERATOR__SUPPORT__SUMMARY.html#autotoc_md1130',1,'Documentation Tests'],['../md_FIXES__SUMMARY.html#autotoc_md375',1,'Existing Tests'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md397',1,'Existing Tests'],['../md_AGENTS.html#autotoc_md47',1,'Running Tests'],['../md_workshop__test__results.html#autotoc_md1469',1,'Skipped Tests'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md776',1,'Test File 1: Unit Tests'],['../md_PR23__VALIDATION__REPORT.html#autotoc_md777',1,'Test File 2: Integration Tests'],['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1491',1,'Unit Tests'],['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md25',1,'Updated Tests']]],
  ['tests_81',['tests',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1505',1,'[... all tests ...]'],['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md468',1,'Run all unit tests'],['../md_QUICK__REFERENCE.html#autotoc_md849',1,'Run automated tests'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1520',1,'Unit tests']]],
  ['tests_20added_82',['Tests Added',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md325',1,'New Tests Added'],['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md396',1,'New Tests Added']]],
  ['tests_20created_83',['Tests Created',['../md_PR23__VALIDATION__REPORT.html#autotoc_md800',1,'Custom Validation Tests Created'],['../md_FIXES__SUMMARY.html#autotoc_md374',1,'Unit Tests Created']]],
  ['tests_20passed_84',['✅ ALL TESTS PASSED!',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1506',1,'']]],
  ['tests_20passed_85',['Tests Passed',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md434',1,'✅ Integration Tests Passed'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md433',1,'✅ Unit Tests Passed']]],
  ['tests_20quietly_86',['Run tests quietly',['../md_skills_2build.html#autotoc_md1196',1,'']]],
  ['tests_20silently_87',['tests silently',['../md_skills_2claude__build.html#autotoc_md1220',1,'Compile with ASan and run tests silently'],['../md_skills_2build.html#autotoc_md1199',1,'Run tests silently']]],
  ['tests_20test_5fdatabase_5flocation_20py_88',['Unit Tests (&lt;span class=&quot;tt&quot;&gt;test_database_location.py&lt;/span&gt;)',['../md_DATABASE__LOCATION__FIX__SUMMARY.html#autotoc_md229',1,'']]],
  ['tests_20test_5fdynamic_5fmax_5ftokens_20py_20new_89',['6. &lt;span class=&quot;tt&quot;&gt;tests/test_dynamic_max_tokens.py&lt;/span&gt; (NEW)',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md344',1,'']]],
  ['tests_20test_5fmodels_5fyaml_20py_90',['5. &lt;span class=&quot;tt&quot;&gt;tests/test_models_yaml.py&lt;/span&gt;',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md343',1,'']]],
  ['tests_20test_5fskills_5fmanager_20py_91',['7. Comprehensive Test Suite (&lt;span class=&quot;tt&quot;&gt;tests/test_skills_manager.py&lt;/span&gt;)',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1302',1,'']]],
  ['tests_20verify_20no_20breakage_92',['Existing tests (verify no breakage)',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1522',1,'']]],
  ['text_20file_93',['1. Simple Text File',['../md_WRITE__BLOCKS__GUIDE.html#autotoc_md1482',1,'']]],
  ['text_20generation_94',['Usage - Text Generation',['../md_MODELS__FINAL.html#autotoc_md643',1,'']]],
  ['that_20may_20be_20included_20by_20accident_95',['that may be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['the_204_20principles_96',['Session Rules (The 4 Principles)',['../md_QUICK__REFERENCE.html#autotoc_md839',1,'']]],
  ['the_20entire_20block_20contains_20a_20heredoc_97',['Check if the entire block contains a heredoc',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md320',1,'']]],
  ['the_20issue_98',['The Issue',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md389',1,'']]],
  ['the_20problem_99',['Evidence of the Problem',['../md_ABSOLUTE__PATH__FIX__SUMMARY.html#autotoc_md19',1,'']]],
  ['the_20project_20task_20is_20sacred_100',['1. Mission First – The Project / Task Is Sacred',['../md_IMPROVEMENTS__FINAL.html#autotoc_md525',1,'']]],
  ['the_20whole_20block_20as_20a_20single_20command_101',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['then_20exepack_102',['Then EXEPACK',['../md_skills_2dos__packer__detector.html#autotoc_md1270',1,'']]],
  ['then_20pklite_103',['Then PKLITE',['../md_skills_2dos__packer__detector.html#autotoc_md1269',1,'']]],
  ['these_20are_20now_20handled_20exclusively_20by_20axe_20py_20responseprocessor_104',['These are now handled EXCLUSIVELY by axe.py ResponseProcessor',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md316',1,'']]],
  ['these_20limits_105',['Why These Limits?',['../md_IMPROVEMENTS__FINAL.html#autotoc_md484',1,'']]],
  ['these_20modules_20first_106',['Why These Modules First?',['../md_REFACTORING__NOTES.html#autotoc_md1009',1,'']]],
  ['thinking_107',['2. Extended Thinking',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md252',1,'']]],
  ['thinking_20enhanced_20reasoning_20✅_108',['2. Extended Thinking (Enhanced Reasoning) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md75',1,'']]],
  ['thinking_20not_20available_109',['Extended thinking not available',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md274',1,'']]],
  ['this_20matters_110',['Why This Matters',['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1516',1,'']]],
  ['this_20week_111',['Short-Term (This Week)',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md737',1,'']]],
  ['this_20works_112',['Why This Works',['../md_HEREDOC__EXECUTION__FIX.html#autotoc_md393',1,'']]],
  ['thought_113',['Chain of Thought',['../md_README.html#autotoc_md934',1,'']]],
  ['thread_114',['Background Monitor Thread',['../md_IMPROVEMENTS__FINAL.html#autotoc_md531',1,'']]],
  ['tier_20available_115',['HuggingFace (Llama) - Free Tier Available!',['../md_README.html#autotoc_md886',1,'']]],
  ['tiers_116',['Sleep Quality Tiers',['../md_IMPROVEMENTS__FINAL.html#autotoc_md479',1,'']]],
  ['tips_20for_20humans_117',['Tips for Humans',['../md_QUICK__REFERENCE.html#autotoc_md851',1,'']]],
  ['to_20prevent_20duplicate_20execution_118',['to prevent duplicate execution',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md317',1,'']]],
  ['to_20requirements_20txt_119',['Added to requirements.txt',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md721',1,'']]],
  ['to_20response_120',['Append results to response',['../md_IMPLEMENTATION__SUMMARY.html#autotoc_md463',1,'']]],
  ['to_20resume_20later_121',['&quot;Want to resume later&quot;',['../md_QUICK__REFERENCE.html#autotoc_md859',1,'']]],
  ['to_20sandbox_122',['From Whitelist to Sandbox',['../md_SANDBOX.html#autotoc_md1049',1,'']]],
  ['to_20use_123',['How to Use',['../md_llm__prep_2codebase__overview.html#autotoc_md575',1,'']]],
  ['to_20use_20each_20agent_124',['When to Use Each Agent',['../md_README.html#autotoc_md913',1,'']]],
  ['to_20use_20verbose_20output_125',['When to Use Verbose Output',['../md_AGENTS.html#autotoc_md59',1,'']]],
  ['to_20whitelist_20mode_126',['Compared to Whitelist Mode',['../md_SANDBOX__IMPLEMENTATION__SUMMARY.html#autotoc_md1073',1,'']]],
  ['to_20whitelist_20mode_127',['&quot;bubblewrap not available, falling back to whitelist mode&quot;',['../md_SANDBOX.html#autotoc_md1051',1,'']]],
  ['token_20counting_128',['3. Token Counting',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md257',1,'']]],
  ['token_20counting_20fails_129',['Token counting fails',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md275',1,'']]],
  ['token_20counting_20precise_20estimates_20✅_130',['3. Token Counting (Precise Estimates) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md76',1,'']]],
  ['token_20efficiency_20analysis_131',['Token Efficiency Analysis',['../md_SKILLS__SYSTEM__IMPLEMENTATION__SUMMARY.html#autotoc_md1307',1,'']]],
  ['token_20format_132',['Token Format',['../md_docs_2GITHUB__AGENT__INTEGRATION.html#autotoc_md298',1,'']]],
  ['token_20limit_20errors_20413_20not_20handled_20✅_133',['Bug 3: Token Limit Errors (413) Not Handled ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md200',1,'']]],
  ['token_20optimization_20strategies_134',['4. Adding New Token Optimization Strategies',['../md_ARCHITECTURE.html#autotoc_md165',1,'']]],
  ['token_20purpose_135',['Token Purpose',['../md_MISSION.html#autotoc_md607',1,'']]],
  ['token_20reduction_136',['Token Reduction',['../md_MINIFIER__IMPLEMENTATION__SUMMARY.html#autotoc_md583',1,'']]],
  ['token_20reference_137',['Token Reference',['../md_MISSION.html#autotoc_md606',1,'']]],
  ['token_20saving_20optimizations_20new_138',['Token-Saving Optimizations (NEW!)',['../md_README.html#autotoc_md907',1,'']]],
  ['token_20savings_20✅_139',['1. Prompt Caching (90% Token Savings) ✅',['../md_ANTHROPIC__IMPLEMENTATION__SUMMARY.html#autotoc_md74',1,'']]],
  ['token_20savings_20estimates_140',['Token Savings Estimates',['../md_SILENT__BUILDS__IMPLEMENTATION.html#autotoc_md1154',1,'Token Savings Estimates'],['../md_skills_2build.html#autotoc_md1168',1,'Token Savings Estimates']]],
  ['token_20savings_20example_141',['Token Savings Example',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md249',1,'']]],
  ['token_20savings_20in_20security_20audits_142',['Token Savings in Security Audits',['../md_skills_2claude__build.html#autotoc_md1239',1,'']]],
  ['token_20statistics_20with_20cache_20tracking_143',['Token Statistics with Cache Tracking',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md266',1,'']]],
  ['token_20truncation_20fixed_20✓_144',['2. Token Truncation Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md348',1,'']]],
  ['token_20usage_20commands_20new_145',['Token Usage Commands (NEW!)',['../md_README.html#autotoc_md902',1,'']]],
  ['token_20usage_20tracking_146',['Token Usage Tracking',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md443',1,'']]],
  ['token_20usage_20tracking_20ui_20✅_147',['1. Token Usage Tracking UI ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md423',1,'']]],
  ['tokens_148',['Agent Communication Tokens',['../md_MISSION.html#autotoc_md605',1,'']]],
  ['tokens_20implementation_20summary_149',['Dynamic Max Output Tokens Implementation Summary',['../md_DYNAMIC__TOKENS__SUMMARY.html',1,'']]],
  ['tool_20call_20parser_20implementation_150',['Multi-Format Tool Call Parser Implementation',['../md_MULTI__FORMAT__PARSER__IMPLEMENTATION.html',1,'']]],
  ['tool_20call_20parser_20quick_20reference_151',['Multi-Format Tool Call Parser - Quick Reference',['../md_MULTI__FORMAT__PARSER__QUICK__REFERENCE.html',1,'']]],
  ['tool_20chain_20silent_152',['Pattern 2: Security Tool Chain (Silent)',['../md_skills_2claude__build.html#autotoc_md1255',1,'']]],
  ['tool_20efficiency_20comparison_153',['Tool Efficiency Comparison',['../md_workshop__benchmarks.html#autotoc_md1359',1,'']]],
  ['tool_20interactions_154',['Cross-Tool Interactions',['../md_workshop__dependency__validation.html#autotoc_md1390',1,'']]],
  ['tool_20parser_20test_20suite_155',['XML TOOL PARSER TEST SUITE',['../md_XML__PARSER__IMPLEMENTATION.html#autotoc_md1504',1,'']]],
  ['tool_20quick_20reference_156',['Security Tool Quick Reference',['../md_skills_2claude__build.html#autotoc_md1249',1,'']]],
  ['tool_20syntax_20fix_20summary_157',['Collaborative Mode Tool Syntax Fix - Summary',['../md_COLLAB__TOOL__SYNTAX__FIX__SUMMARY.html',1,'']]],
  ['tool_20version_20check_158',['Tool Version Check',['../md__8collab__env.html#autotoc_md9',1,'']]],
  ['tool_20whitelist_159',['Tool Whitelist',['../md_README.html#autotoc_md915',1,'']]],
  ['toolchain_160',['Build Toolchain',['../md__8collab__env.html#autotoc_md3',1,'']]],
  ['tools_161',['Tools',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md697',1,'✅ Four Dynamic Analysis Tools'],['../md_ARCHITECTURE.html#autotoc_md164',1,'3. Adding New Workshop Tools'],['../md_README.html#autotoc_md937',1,'Analysis Tools'],['../md_README.html#autotoc_md897',1,'Executing Tools'],['../md_README.html#autotoc_md872',1,'Integrated Tools'],['../md__8collab__env.html#autotoc_md4',1,'Reverse Engineering Tools'],['../md_skills_2claude__build.html#autotoc_md1212',1,'Security-Specific Tools'],['../md_workshop__quick__reference.html#autotoc_md1401',1,'Tools'],['../md_README.html#autotoc_md957',1,'Workshop - Dynamic Analysis Tools']]],
  ['tools_20benchmarks_162',['Workshop Tools Benchmarks',['../md_workshop__benchmarks.html',1,'']]],
  ['tools_20dependency_20validation_163',['Workshop Tools Dependency Validation',['../md_workshop__dependency__validation.html',1,'']]],
  ['tools_20expand_164',['Optional: add more (DIET, etc.) if tools expand',['../md_skills_2dos__packer__detector.html#autotoc_md1271',1,'']]],
  ['tools_20implemented_165',['Claim 1: Four Analysis Tools Implemented',['../md_PR23__VALIDATION__REPORT.html#autotoc_md749',1,'']]],
  ['tools_20quick_20reference_166',['Workshop Tools Quick Reference',['../md_workshop__quick__reference.html',1,'']]],
  ['tools_20quietly_167',['5. Combine Multiple Security Tools Quietly',['../md_skills_2claude__build.html#autotoc_md1247',1,'']]],
  ['tools_20security_20audit_168',['Workshop Tools Security Audit',['../md_workshop__security__audit.html',1,'']]],
  ['tools_20status_20discovery_20✅_169',['4. Workshop Tools Status &amp;amp; Discovery ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md426',1,'']]],
  ['tools_20test_20suite_20execution_20results_170',['Workshop Tools Test Suite Execution Results',['../md_workshop__test__results.html',1,'']]],
  ['top_20models_171',['Top Models',['../md_API__PROVIDERS.html#autotoc_md108',1,'Top Models'],['../md_API__PROVIDERS.html#autotoc_md116',1,'Top Models'],['../md_API__PROVIDERS.html#autotoc_md125',1,'Top Models'],['../md_API__PROVIDERS.html#autotoc_md135',1,'Top Models'],['../md_API__PROVIDERS.html#autotoc_md143',1,'Top Models']]],
  ['trace_5fexecution_5fpath_172',['trace_execution_path',['../md_skills_2trace__execution__path.html',1,'']]],
  ['tracking_173',['Tracking',['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md266',1,'Token Statistics with Cache Tracking'],['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md443',1,'Token Usage Tracking']]],
  ['tracking_20✅_174',['Phase 5: Resource Tracking ✅',['../md_IMPROVEMENTS__README.html#autotoc_md547',1,'']]],
  ['tracking_20ui_20✅_175',['1. Token Usage Tracking UI ✅',['../md_IMPLEMENTATION__COMPLETE.html#autotoc_md423',1,'']]],
  ['trailing_20backticks_20that_20may_20be_20included_20by_20accident_176',['trailing backticks that may be included by accident',['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md188',1,'Sanitize filename: strip trailing backticks that may be included by accident'],['../md_BEFORE__AFTER__COMPARISON.html#autotoc_md189',1,'Sanitize filename: strip trailing backticks that may be included by accident']]],
  ['transformers_20local_177',['Usage - Transformers (Local)',['../md_MODELS__FINAL.html#autotoc_md631',1,'']]],
  ['treat_20the_20whole_20block_20as_20a_20single_20command_178',['If so, treat the whole block as a single command',['../md_DUPLICATE__EXECUTION__FIX__SUMMARY.html#autotoc_md321',1,'']]],
  ['trees_179',['ast (Abstract Syntax Trees)',['../md_workshop__dependency__validation.html#autotoc_md1371',1,'']]],
  ['trends_180',['Resource Utilization Trends',['../md_workshop__benchmarks.html#autotoc_md1360',1,'']]],
  ['trials_20fail_181',['Fallback signature quick-check if all trials fail',['../md_skills_2dos__packer__detector.html#autotoc_md1272',1,'']]],
  ['triggers_182',['Triggers',['../md_IMPROVEMENTS__FINAL.html#autotoc_md499',1,'Break Triggers'],['../md_IMPROVEMENTS__FINAL.html#autotoc_md480',1,'Wake-up Triggers']]],
  ['troubleshooting_183',['Troubleshooting',['../md_API__PROVIDERS.html#autotoc_md156',1,'Troubleshooting'],['../md_docs_2ANTHROPIC__FEATURES.html#autotoc_md272',1,'Troubleshooting'],['../md_MODELS__FINAL.html#autotoc_md661',1,'Troubleshooting'],['../md_README.html#autotoc_md976',1,'Troubleshooting'],['../md_SANDBOX.html#autotoc_md1050',1,'Troubleshooting'],['../md_workshop__dependency__validation.html#autotoc_md1397',1,'Troubleshooting'],['../md_XML__PARSER__QUICK__REFERENCE.html#autotoc_md1523',1,'Troubleshooting']]],
  ['truncation_20fixed_20✓_184',['2. Token Truncation Fixed ✓',['../md_DYNAMIC__TOKENS__SUMMARY.html#autotoc_md348',1,'']]],
  ['try_20unlzexe_20first_20very_20common_185',['Try unlzexe first (very common)',['../md_skills_2dos__packer__detector.html#autotoc_md1268',1,'']]],
  ['turns_20✅_186',['Bug 2: Spawned Agents Never Get Turns ✅',['../md_BUG__FIX__SUMMARY.html#autotoc_md198',1,'']]],
  ['txt_187',['Added to requirements.txt',['../md_PR23__EXECUTIVE__SUMMARY.html#autotoc_md721',1,'']]],
  ['type_20hints_20good_188',['Type Hints - GOOD',['../md_PR23__VALIDATION__REPORT.html#autotoc_md796',1,'']]]
];
